### ISSUE TITLE
width resizing does not work with autoSize: true

### ISSUE THREAD

**Issue by djpentz** [fancyapps/fancyBox#100]
I don't quite understand why this aspect of fancybox2 remains so confusing, when the concept, in my opinion is so simple. If autoSize is true, then I expect it to autoSize the height AND the width. Currently if autoSize is true, _only_ the height is adjusted, and whats more I have to call update() to get this effect. Why is that? v1 did not require an explicit API call. Why not resize the height too, using minWidth/maxWidth as limiters to prevent overflow?

I'm really disappointed in fancybox2 after assuming (my mistake - I should have tried it first) from the documentation that it had the resizing capabilities that fancybox1 was so sorely missing. At this rate, I could have stuck with fancybox1 _without_ paying the license fee and simply tweaked the JS myself since fancybox2 has brought me no benefits over v1.

Given that this is no longer free software, I hope this weakness in fancybox2 will be addressed quickly!

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
