### ISSUE TITLE
Maintain proper focus when opened by triggered click

### ISSUE THREAD

**Issue by slavafomin** [fancyapps/fancyBox#1000]
Hello!

I'm triggering click event on the FancyBox link element in order to show FancyBox popup:

``` javascript
// Handling click event on the button.
$('#some-button').click(function() {
  // Triggering click event on the fancybox link.
  $('#fancybox-link').click();
});
```

When this happens, FancyBox is not gaining the «focus», i.e. when I press arrow buttons on the keyboard, the parent window of the website is scrolling instead of FancyBox navigating through the gallery items.

---

P/S: issue number #1000, I'm lucky! = )

**Comment by slavafomin** [comment]
# Workaround

From user perspective this problem can be fixed by adding the following callback:

```javascript
$('.photo').fancybox({
  // ...
  afterShow: function () {
    this.wrap.focus();
  }
});
```

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
