### ISSUE TITLE
iOS & Windows Phone Scrolling Issues

### ISSUE THREAD

**Issue by TcPhilBushnell** [fancyapps/fancyBox#1001]
Hi,

We're using fancybox on our website and have been asked to stop the dialog from moving around on the screen (generally) across mobile devices. I came across a fix for Android and iOS by setting

``` javascript
$.fancybox({
    scrolling: 'hidden',
    helpers: {
        overlay: {
            locked: true 
        }
    });
```

but Windows Phone consistently behaves differently.

If the page behind the fancybox is larger than the fancybox itself, then even with this fix applied you can continue to scroll past the bottom and reveal the rest of the page. The 'rest of the page' has no overlay (i.e. the alpha background scrolls up with the page) and you can continue scrolling till the bottom of the actual page.

If the page is already at the bottom when the fancybox is opened then (logically) you cannot scroll past the fancybox. It appears that when you scroll past the fancybox, Windows Phone ignores `position: fixed`. My reasoning for this is that our cookie dialog popup also disappears when this scrolling happens.

If any more information is required then please ask away.

Regards,

**Phil Bushnell**

**Comment by TcPhilBushnell** [comment]
I have also found that iOS doesn't quite work as expected either. The dialog no longer moves around the page but you can still scroll the background which then breaks scrolling within the dialog. Someone else has asked a question about this issue (http://osdir.com/ml/fancybox/2014-03/msg00000.html) with no responses.

It seems as if the touch events are passed through the overlay. I have improved this issue by using the options
```javascript
    afterShow: () => {
        $('body').bind('touchmove', (e) => {
            e.preventDefault();
        });
    },
    beforeClose: () => {
        $('body').unbind('touchmove');
    }
```
so that you cannot scroll the page from the alpha overlay background but even with this, the background page can continue to be scrolled from inside the dialog (e.g. scroll up when overlay content is at the top).

Regards,

**Phil Bushnell**

**Comment by TcPhilBushnell** [comment]
Further investigation has lead to noticing that touch events in the iframe don't count as part of the parent page but do effect the parent page. I used
```javascript
    $('.fancybox-overlay').bind('touchstart', function (e) {
        e.preventDefault();
        $(body').css('background', '#000');
    });
```
to see that the background only changes colour when you `touchstart` on the alpha overlay only and not within the iframe (change the selector to iframe to see no background changes at all).

Regards,

**Phil Bushnell**

**Comment by creativetim** [comment]
:+1:

**Comment by wtran** [comment]
```javascript
$('body').on('touchmove', function(e) {
    if($('.fancybox-overlay').length) { e.preventDefault(); }
});
```

**Comment by Craigy-** [comment]
+1
But I have same issue in Chrome on Android 4.2.

**Comment by fancyapps** [comment]
V3 is especially designed for mobile.
