### ISSUE TITLE
Send data from iframe to parent.

### ISSUE THREAD

**Issue by abdelali-touil** [fancyapps/fancyBox#1002]
Hi, 
I searched to find a solution to the problem of sending data from iframe to the parent window, I finally found a solution,
we must create a function in the parent and call it in iframe

this is the code,
iFrame :
$('#CloseButton').on('click', function(){
    parent.callMe('My data');
    parent.jQuery.fancybox.close();
});

Parent : 

<script>
function callMe(data){
        console.log(data);
    }
</script>

Please, if it is an other solution, posted it.

best regards

**Comment by fancyapps** [comment]
That is indeed how you can access parent page.
