### ISSUE TITLE
when the image link doesnt contain the image extension its not working

### ISSUE THREAD

**Issue by yvz5** [fancyapps/fancyBox#1004]
i have a php file for showing images say : image.php?id=12321, if i put this to the a element it doesnt show any image file, but i have put an extra querysting element at the end with .jpg and it works .

-  image.php?id=12321 doesnt work.
-  image.php?id=12321&e=.jpg - works

**Comment by fancyapps** [comment]
The script can not guess if link should open the image.  You have to specify the content type. See FAQ on the homepage.
