### ISSUE TITLE
Fancybox is reducing image brightness

### ISSUE THREAD

**Issue by baezcarlos** [fancyapps/fancyBox#1005]
Hi, Im developing a website for a photographer, but the fancybox is reducing the image brightness, how can I avoid that?

Thanks

**Comment by fancyapps** [comment]
Are you sure? If you open your image directly in the browser, does it look different?

**Comment by baezcarlos** [comment]
Well you are right, If I open the image directly in the browser it looks the same (low brightness), but when I download the image directly from my FTP it looks different (high brightness)

**Comment by baezcarlos** [comment]
Do you have any idea what can I do? 

Thank u very much

**Comment by fancyapps** [comment]
Are you sure you view and download the same file? I can not image what could cause this. 
What image format are you using, jpg? Could you link to that image?

**Comment by baezcarlos** [comment]
Problem solved. My mistake, my hosting has a big delay so it was showing the older images (without brightness)

Thank u very much fancyapps
