### ISSUE TITLE
High-resolution vimeo thumbnail

### ISSUE THREAD

**Issue by jeremymouton** [fancyapps/fancyBox#1006]
When I use fancyBox to display a Vimeo video, the poster images is very low-res. The embedded video poster looks fine.

Codepen: http://codepen.io/anon/pen/gbjVYX

I noticed that if you go fullscreen and then close fullscreen, the remaining thumbnail stays high-res. 

>  If your video is at least 960px wide, you can embed the player at that size or smaller to get that higher res thumbnail. Once the player hits 640px wide or below, it will switch to that thumbnail size.

-- https://vimeo.com/forums/feature_requests/topic:32794

Any thoughts on how I might fix this?

**Comment by fancyapps** [comment]
I do not think it is possible to somehow force vimeo to show different thumbnail.
