### ISSUE TITLE
Next and Prev arrows

### ISSUE THREAD

**Issue by andresr19** [fancyapps/fancyBox#1007]
Hallo there

Is there a way to put next and prev arrows when using DOM elements?

//DOM element:
$.fancybox( $("#inline"), {
    title : 'Custom Title'
});

I have a custom grid with N cards and every card displays another custom div (that's why im using DOM element approach) it works like a charm but it happen not to display the prev and next arrows, any chance to make it work? or it works only with li: a: img ?

Bye thx

**Comment by Kaito23** [comment]
hey,
maybe this helps you:
http://stackoverflow.com/a/8932037/2044537
Greetings
Kaito
