### ISSUE TITLE
Adding selector as a option for grouping when initiating from a dom node object

### ISSUE THREAD

**Issue by cosmosgenius** [fancyapps/fancyBox#1008]
I am trying to integrate fancybox with angular. Fancybox 2.0 moved the grouping to use selector which comes from the jquery call. So if we make a call from the DOM Node object the grouping does not work as there is no passed in selector.

Is it possible to added an option to pass in the selector when initiating from an object? or some other mechanism for grouping when initiating from individual objects rather than from selector.

**Comment by fancyapps** [comment]
You can pass `live : false` as an argument to apply plugin to selected elements.

**Comment by cosmosgenius** [comment]
Does that help with grouping(gallery) the images? What I was trying to do this is to add individual DOM Node object in a group eg `gallery1`. So when any of those(individual nodes) is clicked the gallery would have them as well as any node which i would add manually later on to the same `gallery1`. Does that make sense?

**Comment by fancyapps** [comment]
You could create your custom group on click event display it using $.fancybox.open()
