### ISSUE TITLE
Image not showing in Chrome on iPad Mini

### ISSUE THREAD

**Issue by ersatzpole** [fancyapps/fancyBox#1011]
Hi,
I tried to open some images today using fancy box (wordpress) which always open fine in every browser on a desktop and on the iPhone. On iPad Mini in Chrome no image appears, just the overlay (opaque layer underneath where the image should be). Is this a known bug? This is the only browser /device combination I have ever experienced this with.

**Comment by fancyapps** [comment]
It should work fine. Could you show your page?

**Comment by ersatzpole** [comment]
Thank you for your reply. I'm trying to get an image and a more detailed explanation of the occurance. It is not my machine which I tried it out on so just waiting to hear back.

**Comment by fancyapps** [comment]
I suggest upgrading to v3, it is especially designed to work on mobile devices.
