### ISSUE TITLE
Scrollbar not showing

### ISSUE THREAD

**Issue by dwaqaddi** [fancyapps/fancyBox#1012]
Hi,

Having an issue with fancybox. The vertical scrollbar is not showing. I'm using windows 8, chrome browser. It works on other browsers, but not working with chrome.

![pasted_image_at_2015_03_19_04_32_pm_1024](https://cloud.githubusercontent.com/assets/2783884/6728019/87485466-ce61-11e4-8ec7-56716121adfe.png)

```
$('.read').fancybox({
        width: 740,
        autoSize: false,
        autoHeight: true,
        padding: 30,
        fitToView: false
});

```

Thanks,
Darwin

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
