### ISSUE TITLE
Fancy box resize issue

### ISSUE THREAD

**Issue by SteveQ88** [fancyapps/fancyBox#1013]
Hi I have been struggling with this issue for a long time now and I was wondering if you could help me please.

It seems that when the content is too long for the window height it shrinks the width as in the picture... when the window size is large enough the width is fine.
here is my js 

$(".fancybox").fancybox({  
            padding : 0,
            minWidth  : 280,
            beforeShow: function () {
                this.title = $(this.element).attr('title');
                this.title = '<h4>' + this.title + '</h4>' + '<p>' + $(this.element).parent().find('img').attr('alt') + '</p>';
            },
            helpers : {
                title : { type: 'inside' },

```
        }
    });

$('.fancybox-media').fancybox({
    openEffect  : 'none',
    closeEffect : 'none',
    helpers : {
        media : {}
    }
});
```

I am using fancyBox version: 2.1.5 (Fri, 14 Jun 2013)

![img_0057](https://cloud.githubusercontent.com/assets/8135124/6766875/08047fa8-d010-11e4-969c-173ddc34b2a8.jpg)

Thanks

Steve

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
