### ISSUE TITLE
MYSQL code to display selected images

### ISSUE THREAD

**Issue by Kobusjpd** [fancyapps/fancyBox#1015]
Hello There,
I am setting up a photo gallery using MYSQL. the photos are categorised within the database and a web page prompts for options. After the person browsing the site sumbits his query, the pages selects the specific images which I need to display using fancyBox.

MY QUESTION.
Where do I add my code and I need to replace the fixed img tags with the array op intput from MYSQL query?
Looking forward to your reply.
Blessings.

**Comment by fancyapps** [comment]
You can use demo page to get an idea about general structure.
