### ISSUE TITLE
databound asp.net controls empty on postback

### ISSUE THREAD

**Issue by joneastwood** [fancyapps/fancyBox#1016]
I have 2 fancy box forms on a page, both post back and validate what the user has entered via ajax

One form has a drop down list that's hard coded:

```
                                <asp:DropDownList ID="cmbKPIPeriod" cssclass="selbox" runat="server">
                                    <asp:ListItem Value="" Text="Select"></asp:ListItem>
                                    <asp:ListItem Value="D" Text="1 Day"></asp:ListItem>
                                    <asp:ListItem Value="W" Text="1 Week"></asp:ListItem>
                                    <asp:ListItem Value="M" Text="1 Month"></asp:ListItem>
                                </asp:DropDownList>
```

This works fine and the selected value is retained.

The other form has 2 drop down lists and one is data bound and the other is populated from code.

This form does not work and the selected values are always blank

I have the $('.fancybox').fancybox({parent:"form:first"}); set so they are being included in the form correctly

please advise as i am tearing my hear out

Thanks

Jon.

**Comment by fancyapps** [comment]
I`m sorry, I`m not familiar with asp.net.
