### ISSUE TITLE
300ms delay between background overlay and popup content display on touch devices

### ISSUE THREAD

**Issue by friend8** [fancyapps/fancyBox#1017]
https://github.com/fancyapps/fancyBox/commit/e50c0d825cb5deb5e6081ce0ad7cb0f8f8e0a2d0#diff-0b3e5ad148eba7288614a6a501640941L583 introduced a 300ms delay.

Why does the 300ms delay for touch devices exist here?
It leads to a noticable delay between showing the grey background overlay and the actual popup window.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
