### ISSUE TITLE
AJAX mode of FancyBox2: middle button scrolling hangs up when background starts to scroll

### ISSUE THREAD

**Issue by Felix-neko** [fancyapps/fancyBox#1019]
Gentlemen! I want to create a pop-up with a few images and HTML code in it.
I make it with AJAX mode of FancyBox2.

Alas, when I start to scroll i with my middle button, it hangs up just at the moment, when the background page starts scrolling too.

Cannot you disable background page scrolling? Or how can I do it manually?

Here's a minimal example of the problem:

https://www.sendspace.com/file/90y0wv

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
