### ISSUE TITLE
Specify More Fancybox parameters via data-fancybox-attribute. 

### ISSUE THREAD

**Issue by AdamHess** [fancyapps/fancyBox#1020]
I work on a CMS system and I'd like my CMS users to be able to specify fancybox parameters in their HTML instead of relying on me to try to create a "Catch all" for them by creating a global selector to apply. 

So I'd like them to be able to specify:

min and maxWidth, opening type (elastic etc) and so on for each element without me having to do it for them with javascript (which they are much less comfortable with using) 

so like 

data-fancybox-type="iframe" or data-fancybox-maxWidth="300" as part of the element specs.

**Comment by fancyapps** [comment]
If using v3, you can use "data-options":

```
<a data-fancybox data-options='{"caption" : "My caption", "src : "iframe.html"}' href="javascript:;">
	Open external page using iframe
</a>
```
