### ISSUE TITLE
Fancybox does not open with this image: http://212.101.18.246/axis-cgi/jpg/image.cgi

### ISSUE THREAD

**Issue by wt69** [fancyapps/fancyBox#1021]
Here is an example:
http://jsfiddle.net/24ysn4t7/1/

The second image (linked to other source) works well, the first image does not open the fancybox (open image in same window).
Bug?

Thanks
Thomas

**Comment by Eschon** [comment]
I think that has something todo with that the url you are using does not with a typical image file extension like .jpg or .png. I had a similar issue once. Adding the class fancybox.image makes it work.
See example: http://jsfiddle.net/Eschon/18dga114/

**Comment by wt69** [comment]
great! Thank you. This works.

Maybe anyway a bug?

**Comment by fancyapps** [comment]
The script just can not guess that this link will lead to the image.
