### ISSUE TITLE
Fancybox and Content loaded through JavaScript

### ISSUE THREAD

**Issue by amandagray825** [fancyapps/fancyBox#1022]
Very simply, I've set up a page where content is loaded within a div by selecting a link in the sidebar. This content contains images that when clicked, a larger image pops up (using Fancybox). Unfortunately, the dynamic content on the page disappears as soon as the fancybox opens, and does not reappear when the fancybox is closed.

Help! Is there a better way to set this up?

Below is the code I'm using to load the content, and each of the divs with content has a style of display: none except for the content that is visible on the page load.

```
<script type="text/javascript" charset="utf-8">
$(".left-list a").click(function(e) {
    $("#copy > div").hide();
    $(this.hash).show();
    e.preventDefault();
});
$("#copy > div").not("#intro, #intro div").hide();
</script>
```

**Comment by fancyapps** [comment]
Sorry, this would be custom coding.
