### ISSUE TITLE
Does Fancybox have retina compatibility for content images?

### ISSUE THREAD

**Issue by darren-dos** [fancyapps/fancyBox#1023]
Just added "retina.js(http://imulus.github.io/retinajs/)" on a project which basically serves a larger "@2x" image depending on the devices pixel ratio however I have come across an issue... 
I need to load a larger "@2x" image into fancybox depending on the device pixel ratio, my understanding was that fancybox has this capability, if so how does this work, is there any code I need to enable?

**Comment by jeffhuang** [comment]
Would also love to have this feature. I'm also using retina.js and fancybox is not compatible.

**Comment by fancyapps** [comment]
v3 supports srcset and you could probably use it for serving different images depending on pixel density. Also, you could simply use afterLoad callback to downsize image, if needed.
