### ISSUE TITLE
Remove border from Fancybox V3 Beta

### ISSUE THREAD

**Issue by anjx** [fancyapps/fancyBox#1027]
Hi,
I've modified jquery.fancybox.js file to remove the white border around images and to enlarge it.
The original codes on the line 98 and 99:
padding   : 15,                 // space inside box, around content
margin    : [30, 55, 30, 55],           // space between viewport and the box

the code modified:
padding   : 0,                  // to remove white border
margin    : [20, 15, 20, 15],           // to enlarge images

Now if I use fancybox on iphone 6, I see a wrong width of the site body, with a white bar on the right.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
