### ISSUE TITLE
FancyBox and z-index Chrome's bug

### ISSUE THREAD

**Issue by digitart** [fancyapps/fancyBox#1028]
When you have an element with negative z-index and position "fixed" or "absolute", fancybox-overlay shows correctly over the whole page but child elements are cropped according to the original size of the negative z-index element, no matter their position on the code or in the DOM.

Fancybox in pages with negative z-index elements works fine in Firefox, but breaks in Chrome/Safari/Opera.

![gan abogados fancybox error](https://cloud.githubusercontent.com/assets/866228/7548718/cecd4124-f5db-11e4-96d9-cd6ffc3cb4df.jpg)

I found a solution proposed in http://stackoverflow.com/questions/19258739/absolute-positioned-html5-video-element-with-negative-z-index-breaks-background and in http://stackoverflow.com/questions/17068361/chrome-positionfixed-inside-positionabsolute-breaking-with-iframe-video

I added this to my style.css file and the problem seems to be fixed in all operating systems:

`.fancybox-lock .fancybox-overlay{
    -webkit-backface-visibility: hidden;
    -webkit-transform: translateZ(0);
}`

Apparently Chrome treats negative z-index elements as some sort of 3D rotated divs

In my tests, only `-webkit-backface-visibility: hidden;` do the trick, but It would be great to have both lines included in the jquery.fancybox.css native file.

Hope it helps to someone with the same problem!

**Comment by slacker87** [comment]
Not specifically fancybox related but your fix helped me too digitart, thanks!

**Comment by fancyapps** [comment]
Why would you use negative z-index? It does not make sense to me.

**Comment by digitart** [comment]
Hi fancyapps. Being the default "surface" level z-index 0 , you can go up or down of this "surface" for many reasons, including design issues or behavior issues interacting with other scripts. In my case I used negative z-index to show a video in the background to archive the behavior required by my customer. It doesn't have to with FancyBox at all, but it turned out that the reported Chrome bug. Being negative numbers part of the z-index specification, it made sense to have a circumvent to that bug at the time. I don't know if Chrome fixed it by now.

**Comment by fancyapps** [comment]
Thanks for your info. I hope this issue would not occur using v3.
