### ISSUE TITLE
$.fancybox is undefined

### ISSUE THREAD

**Issue by damongant** [fancyapps/fancyBox#1030]
Everything works fine, except for the global functions that are supposed to control the currently open fancybox.

**Comment by evinugur** [comment]
Check to see if `$` is even defined then or if the fancybox file and/or jquery is properly included via `<script>`.

**Comment by DamonGant** [comment]
Yup, jQuery does not run in noConflict mode and $.fn works fine.

**Comment by evinugur** [comment]
Are you including `jquery.fancybox.pack.js` via a `<script>` tag. If you are, you can check in Chrome's developer tools under network to see if it 404's.

**Comment by DamonGant** [comment]
As I mentioned everything else - namely $("selector").fancybox() - works fine.  
So nope, I'm quite dumb enough to struggle with including a script properly, thanks for the effort tho :+1:

**Comment by evinugur** [comment]
Didn't mean to offend you, I actually misunderstood your question, could you post a minimal HTML file that replicates your issue. I can try taking a look at it since my projects are heavily dependent on `$.fancybox.close()` among a few other global functions.
