### ISSUE TITLE
Fancybox "Quickview" Errors

### ISSUE THREAD

**Issue by JewelryBuzzBox** [fancyapps/fancyBox#1031]
Hi the product "Quick View" on my Shopify theme is suddenly not working. I have asked several people and nothing seems to help the issue, please help. 
I have attached a screenshot  Let me know thanks. JewelryBuzzBox.com 
![screen shot 2015-05-20 at 12 56 11 pm](https://cloud.githubusercontent.com/assets/10568800/7739324/c8d1f5c6-ff13-11e4-8569-97e8927f6e86.png)

**Comment by fancyapps** [comment]
Sorry, I am not familiar with that product.
