### ISSUE TITLE
YouTube Fancybox skips to full screen (Google Tag Manager issue)

### ISSUE THREAD

**Issue by oldmanwerther** [fancyapps/fancyBox#1033]
This consistent in IE browsers, mainly.  Thought I'd share this problem as I've come across it a few times on different sites. 

Problem: Launching YouTube video via Fancybox pops open fancybox briefly and immediately skips to displaying video in full screen (essentially not utilizing the fancybox modal). 

Cause: Specifically Google Tag Manager  was adding an event listener to the fancybox anchor tag. Somehow it doesn't play nicely when adding an additional click event listener to the anchor tag, so it executes the GTM but then seems to skip the Fancybox and defaults to returning the YouTube url instead.

Solution: If using Google Tag Manager, create a rule to prevent exit event click tracking to fancybox anchore tag elements. You can do this by targeting a class on the element.

**Comment by grmilbrand** [comment]
Hey Robert.
I'm having this exact same issue, but I don't know much about GTM, yet. I was wondering if you could help walk me through your solution. Thanks!

**Comment by grmilbrand** [comment]
I have data-behavior="modalize" on all my YouTube links that I want in the modal. So I created a variable for data-behavior then set up a trigger for modalize Videos that checks if data-behavior = "modalize"

**Comment by thibs27** [comment]
Hi oldmanwerther,
I'm new to google tag manager and I was wondering how I could implemente your solution.

Thanks

**Comment by Onotoley** [comment]
+1 same issue
