### ISSUE TITLE
Safari on iOS causing fancybox to move off to the right

### ISSUE THREAD

**Issue by bman-80stees** [fancyapps/fancyBox#1034]
I was testing Fancybox 2.1.5 to see if it were something we wanted to use and noticed some weird behavior on iPhone 6+ with iOS 8.3 using the native Safari browser. When having a gallery of images and tapping the next button, the background seems to move with the scrolling of the fancyBox and in turn, the page content is off the left side of the screen while fancyBox is way off to the right. I'm not sure how else to describe it.  The desktop works fine, the background(page content) says put when cycling through the images in the gallery. The mobile version, the background(page content) moves when cycling through the gallery. Is there some option that I'm not aware of that can fix this or is this a new bug since the iPhone and iOS is newer than the version of fancyBox?

Here are my settings for mobile:
`$(window).ready(function() {
      var wi = $(window).width();
            if (wi <= 629){  
$("a.variousmbl")
    .attr('rel', 'gallerymbl')
    .fancybox({
        fitToView : false,
    maxWidth : 600,
    maxHeight : 800,
        autoSize : false,
        preload : 0,
        aspectRatio : true,
        loop : true,
        index : 3
    }); 
  }
});`

**Comment by phylaxis** [comment]
I am noticing this issue as well on iOS. It happens when you click between gallery images. The background seems to slide to the left and up a bit revealing the content underneath and giving a "flicker" like effect.

You can see it here: http://03c7bc9.netsolhost.com/listing/banyan-estate/

In Safari on iOS click an image and then tap to go through the gallery of images.

Would like to find a fix if it's possible.

Thanks

**Comment by BackuPs** [comment]
Hi 

set the prev next  effect to fade and easing to linear

			nextEffect : 'fade', // 'elastic', 'fade' or 'none'
			nextSpeed  : 250,
			nextEasing : 'linear',
			nextMethod : 'changeIn',

			// Changing previous gallery item
			prevEffect : 'fade', // 'elastic', 'fade' or 'none'
			prevSpeed  : 250,
			prevEasing : 'linear',
			prevMethod : 'changeOut',

Best regards,
BackuPs

**Comment by fancyapps** [comment]
V3 is is specially designed for mobile devices.
