### ISSUE TITLE
Upwards of 2 secs to load fancy box with lots of dom elements due to margin wildcard *

### ISSUE THREAD

**Issue by joelpittet** [fancyapps/fancyBox#1038]
I've been seeing upwards of 2 second load time in chrome due to $('*') in beforeShow.

```
            if (this.margin !== false) {
                $('*').filter(function(){
                    return ($(this).css('position') === 'fixed' && !$(this).hasClass("fancybox-overlay") && !$(this).hasClass("fancybox-wrap") );
                }).addClass('fancybox-margin');

                this.el.addClass('fancybox-margin');
            }
```

Removing that didn't seem to affect the modal and was much more performant.  Can you explain what it's trying to do so that maybe we can find a better solution?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by joelpittet** [comment]
3 doesn't have this wildcard?

**Comment by fancyapps** [comment]
Nope. It fixes jumping of fixed positioned elements differently - http://fancybox.docs/3.0/#faq

**Comment by joelpittet** [comment]
Not a jumping issue, this is don performance issue

**Comment by fancyapps** [comment]
The whole point of `$('*').` was to find all fixed positioned elements and to add some CSS class that  compensates missing scrollbar.

**Comment by joelpittet** [comment]
Sorry miss-read your "nope" to mean it was still there. The $('*') should have been scoped or at least static cached.

**Comment by fancyapps** [comment]
It was actually removed at some point. Sorry that it was not informed there.
