### ISSUE TITLE
How to overcome same origin policy?

### ISSUE THREAD

**Issue by EmreErdogan** [fancyapps/fancyBox#1039]
In the documentation it is noted that ajax requests will not be performed where same origin policy is not complied with. 

> Note, ajax requests are subject to the same origin policy. If fancyBox will not be able to get content type, it will try to guess based on 'href' and will quit silently if would not succeed (this is different from previous versions where 'ajax' was used as default type or an error message was displayed).

I am using fancyBox in a PhoneGap application where **same origin policy** is not an issue.

So I am trying to find a workaround to overcome fancyBox's behavior for cross origin requests.

In my case I have the following html and script:
##### HTML

``` html
<a class="fancybox" rel="group" href="OTHERDOMAIN.com/resize.php?src=images/big_image_1.jpg&w=640&h=480"><img src="small_image_1.jpg" alt="" /></a>
<a class="fancybox" rel="group" href="OTHERDOMAIN.com/resize.php?src=images/big_image_2.jpg&w=640&h=480"><img src="small_image_2.jpg" alt="" /></a>
```
##### JavaScript

``` javascript
$(document).ready(function(){
    $('.fancybox').fancybox();
});
```

**Note:** This problem occurs only when I request dynamic images (i.e. images resized on the fly  and sent out by a php file). I tried sending `Access-Control-Allow-Origin: *` header via both my resize.php script and the web server but had no success.

**Comment by fancyapps** [comment]
I have no idea what are you trying to say, but by looking at your code, I can see that you have no specified content type and the script most probably will fail to recognize your links.
