### ISSUE TITLE
Fancybox issues: swf sizing, repostioning fancybox, close on hover out

### ISSUE THREAD

**Issue by laughingturtle** [fancyapps/fancyBox#1040]
I'm trying to resize the swf by grabbing the width and height with the `afterLoad: function()`, it's not working. I'm also trying to position the fancybox near the element it's connected to with `beforeShow: function()` , which is also not working.

I'm trying to close fancybox `on hover out` Right now `$("a.fancybox-effects-c-swf").hide();` is hiding the wrong thing, it's hiding the original trigger element on the page, and not the fancybox :(

Here's the html:

```
<a class="fancybox-effects-c-swf" width="300" height="250" href="object.swf" title="<b>Title: </b>Lorem ipsum dolor sit amet, consectetur adipiscing elit"><img src="assets/imgs/web/2.jpg" alt="" /></a>
```

Here's my JS thus far:

```
$("a.fancybox-effects-c-swf").fancybox({
            fitToView: false,
            autosize: false,
            wrapCSS    : 'fancybox-custom',
            closeClick : true,
            openEffect : 'elastic',
            openSpeed  : 150,
            closeEffect : 'elastic',
            closeSpeed  : 150,
            helpers : {
                overlay: {
                locked: false
                },
                title : {
                    type : 'inside'
                },  
                beforeShow: function(){
                var position = this.element.offset();
                $("fancybox-effects-c-swf")._getPosition = function() {
                    return position;
                }},               
                afterLoad: function(){
                    this.width = $(this.element).data("width");
                    this.height = $(this.element).data("height");
                }
            }})
            .hover(function () {
            $(this).click();
        }, function(){
            $("a.fancybox-effects-c-swf").hide();
        });
```

If I use `$('.fancybox-wrap').hide();` instead of `$("a.fancybox-effects-c-swf").hide();` on `mouseover` fancybox does not open.

**Comment by fancyapps** [comment]
Sorry, your issue is just too .. long. Anyway, v3 is released some time ago, but it does not support swf files out of box. If you really need, you can create a custom html markup and display it using $.fancybox.open()
