### ISSUE TITLE
Overlay hide issue

### ISSUE THREAD

**Issue by PeterBroom** [fancyapps/fancyBox#1041]
Receiving "Uncaught TypeError: Cannot read property 'hide' of undefined" due to $('.fancybox-overlay').remove().hide(); line 1778

This is trying to hide something that has been removed thus breaking the js after you close and then recall same fancybox instance.

**Comment by fancyapps** [comment]
Sorry, I have no idea what could cause this. Anyway, try upgrading to v3.
