### ISSUE TITLE
Fancybox overlay error

### ISSUE THREAD

**Issue by averichev** [fancyapps/fancyBox#1042]
I want show fancybox when calling ajax request

But if i open overlay before open fancybox - i have errror **_"this.el is undefined"**_ on line 1818 
_this.el.addClass('fancybox-lock');_

``` javascript
$(document).on('click', '[data-fancy]', function (e) {
        e.preventDefault();

        // show loading and overlay
        //$.fancybox.helpers.overlay.open(); // this line causes an error
        $.fancybox.showLoading();

        // post ajax request
        $.post('/ajax/', {}, function (r) {
            // open fancybox with ajax result
            $.fancybox.open(r);
        });
    })
```

what is the problem

please, reply

or show example of solving my problem (fancybox with post request )

**Comment by fancyapps** [comment]
I have no idea what could cause this. Anyway, try upgrading to v3.
