### ISSUE TITLE
Fancybox 2 and bootstrap 3.3

### ISSUE THREAD

**Issue by loloseven** [fancyapps/fancyBox#1043]
Hello, 
I would like to use the iframe tool of fancybox 2 to show links in a popup. 
My website is based on the urbanic template using bootstrap : 
http://www.templatemo.com/live/templatemo_395_urbanic

My index page and all my folders are ok (js/fancybox folder...).
I put those lines in the head section : 

<script type="text/javascript" src="js/jquery.min.js"></script>

```
<script type="text/javascript" src="fancybox/source/jquery.fancybox.pack.js"></script>

<link rel="stylesheet" href="fancybox/source/jquery.fancybox.css" type="text/css" media="screen"/>

<script type="text/javascript">
    $(document).ready(function () {
        /* This is basic - uses default settings */

        $("a.iframe").fancybox();

    });
</script>
```

And those lines into the body section :   

<a class="fancybox fancybox.iframe" href="http://www.nhl.com/">Open the website into a frame</a>

<script type="text/javascript">
    $(document).ready(function() {

        $('a.fancybox').fancybox();

    });
</script>
    

Unfortunately my link open directly in the browser and do not open in a popup.... 
If i keep only the above code in the body section.... the iframe is working fine... the website opens in a popup.
But if i keep the content of the body intact it is not worling the links do not open in a popup...
Si it seems that there is a compatibiliy problem beetween the body of my bootstrap template and the code of the fancybox iframe....

If anybody could help me to solve this problem.... :)
Thank you very much !

**Comment by loloseven** [comment]
the code of the body section is the following (in .jpg)....
I am not able to write it correctly in the message ....

![code_body_section](https://cloud.githubusercontent.com/assets/12967849/8255572/1ac5be86-16a1-11e5-9fac-b2b1246c6a23.JPG)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
