### ISSUE TITLE
Fancybox image dissapears 

### ISSUE THREAD

**Issue by Ahhmmogh** [fancyapps/fancyBox#1045]
website - http://sportsentertainmentattorney.com/sports-law/

Hi, I am trying to use fancybox with the layerslider wp plugin which allows you to use attributes. When I call the fancybox class on my slides the thumbnail dissapears. I dont use <a tags> or anything to link the images. Just set the classes as fancybox for each slide. Any help would be appreciated, thank you

**Comment by fancyapps** [comment]
I`m sorry, I`m not familiar with that plugin.
