### ISSUE TITLE
Closing Fancybox and Reload Parent Div

### ISSUE THREAD

**Issue by gavy81** [fancyapps/fancyBox#1046]
Hi, I am stuck at a point where i need to close the fancybox and refresh only the parent div. i tried something like this: 

<div align="right">
    <button onclick="parent.done_with_msg();">Close</button>
</div> 

the above is within the fancybox iframe: 

on parent i wrote: 

inside document ready: 

function done_with_msg(id) {
    $("#taskTabInner").load('includek.php' + " #taskTabInner"); 
}

but that does not seems to work and throws an error in chrome 

Uncaught TypeError: parent.done_with_msg is not a function

**Comment by fancyapps** [comment]
Sorry, I have no idea what do you mean by "Reload Parent Div".
