### ISSUE TITLE
manually setting content to fancybox > synchronous XMLHTTPRequest warning > original function is dead

### ISSUE THREAD

**Issue by sweiguny** [fancyapps/fancyBox#1047]
Hi,

when i am setting the content of the fancybox manually, then the wellknown warning of the browser appears:

> Synchronous XMLHttpRequest on the main thread is deprecated because of
> its detrimental effects to the end user's experience. For more help,
> check http://xhr.spec.whatwg.org/.

this occurs when i am calling fancybox that way:

```
$("#submitBtn).submit(function() {
    $.ajax(url, {
        dataType: 'html',
        async: true,
        success: function(result) {
            $.fancybox.open({
                content:    $(result),
                autoSize:   false
            });
        }
    });
});
```

no way, that there is a synchronous request.

this is pretty problematic, because it seems to me, that the function, that causes the synchronous request is not callable any more after the first attempt. i then get an error message:

> Uncaught TypeError: $(...).submit is not a function.

**Comment by sweiguny** [comment]
i found out, that if there are script tags with a src attribute in the content you are passing to fancybox, then the error appears.

i guess, that the fancybox buffers the content and waits until all the javascript files are loaded... but this is just a bad guess, because on link tags with href attribute the behavior does not occur.

i skimmed over the source code, but i did not get it how this exactly works, because i do not have the time go more into the details.

i think that this is an issue which may appear more often.

**Comment by fancyapps** [comment]
The script just creates markup containing the content you provided. The rest is up to the browser.
