### ISSUE TITLE
fancybox meets django - django-fancybox

### ISSUE THREAD

**Issue by bashu** [fancyapps/fancyBox#1048]
O hai,

Here is my small contribution https://github.com/bashu/django-fancybox

![screen shot 2015-07-05 at 16 01 35](https://cloud.githubusercontent.com/assets/144783/8511205/b55b9ace-2326-11e5-87a9-50fbeddfe773.png)

**Comment by SalahAdDin** [comment]
I am using fancibox whitout an implementantion.
Can you put a screen show for your packages?

**Comment by bashu** [comment]
yes, sure

**Comment by fancyapps** [comment]
Thanks for your work. You should mention about fancybox licensing.
