### ISSUE TITLE
How to apply Fancybox (beginner)

### ISSUE THREAD

**Issue by FawnNyx** [fancyapps/fancyBox#1049]
For the life of me I can't seem to get Fancybox to work on my site. Any help would be much appreciated. I even followed this guy's video and no dice: http://tutvid.com/webdesign/dreamweaver/how-to-use-fancybox-jquery-tutorial/

Here is my code that I was working with (I kept it really simple so I couldn't mess it up...didn't work...):

`<!doctype html>`
`<html>`
`<head>`
`<meta charset="utf-8" />`
`<title>This better Work</title>`

`<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>`

`<!---//////////////////Fancybox JScript//////////////////--->   `

   ` <link rel="stylesheet" href="js/fancybox/source/jquery.fancybox.css" type="text/css" media="screen"/>`
    `<script type="text/javascript" src="js/fancybox/source/jquery.fancybox.pack.js"></script>`

`</head>`

`<body>`

`<div><a class="fancybox" href="js/fancybox/images/1_b.jpg"><img src="js/fancybox/images/1_s.jpg" width="250" height="251" /></a></div>`

`<!--//////////////Javascript Links//////////////-->`

`<script type="text/javascript">
    $(document).ready(function() {
    $(".fancybox").fancybox();
    });
</script>`
`</body>`
`</html>`

**Comment by fancyapps** [comment]
Open developer tools (hit F12) and look for error messages, they should you give a clue. .
The typical problem is that file paths need to be adjusted. Make sure that "js/fancybox/source/jquery.fancybox.pack.js" leads to actual file. And it is better to use absolute paths like "/js/fancybox/source/jquery.fancybox.pack.js".

**Comment by FawnNyx** [comment]
you were right! the paths seem to be the issue...I think... well, I tried looking at the example code that Fancybox came with, and pretty much copied and pasted. Then it worked...
![screen shot 2015-07-13 at 9 37 27 pm](https://cloud.githubusercontent.com/assets/13176683/8666521/93246e18-29a7-11e5-9422-e222857d1c35.png)
Although I'm not too sure why this worked and the other didn't....
