### ISSUE TITLE
Fancybox 3 dead?

### ISSUE THREAD

**Issue by rjgamer** [fancyapps/fancyBox#1050]
Hi,

is fancyBox 3 dead?

Best regards

**Comment by thiagocoelho** [comment]
300+ Opened issues, 40 pull requests.. Maybe almost dead? No commits in the past two years.

**Comment by hebbet** [comment]
fancybox 3 was never released as stable.

**Comment by SalahAdDin** [comment]
´The main administrator don't merge the PR.

**Comment by unitedworx** [comment]
fancybox 2 works pretty well. i was shocked to find fancybox 3 beta earlier today workign with swipe gestures on my iphone!!! (main reson of lookign for an updated version! )

it would be nice if the developers gave over the projects to other capable developers if there is no time to maintain it! i search all over and dint really find anythign as capable, clean and simple as fancybox! with swipe gesture support!

**Comment by SalahAdDin** [comment]
We need other support or admin.

**Comment by dakur** [comment]
@fancyapps : Do you plan to continue in developping fancybox further? It's very useful app and the touch support in v3 beta is really useful feature - many people can't wait the stable version. Or are you giving up? Maybe someone else would develop it? Please make an announcement about this, so we know if we can count with fancybox further, or we have to find another solution or developer. Thank you and thank you for your current work on it.

**Comment by SalahAdDin** [comment]
WHe need really really really a new repository's admin, fancyapps user seems deed :'(

**Comment by eladnova** [comment]
I'd love to see FancyBox continue to be developed into V3. Having purchased a multi-domain license some time ago, I use it (V2) extensively. Despite most of the frameworks having their own modal options, FB has always been a favourite. Any updates @fancyapps ?

**Comment by phylaxis** [comment]
Is there a guide for upgrading from Fancybox 2 to the Fancybox 3 beta?

**Comment by michaelwoodruff** [comment]
This repo is unfortunately abandon. I am looking for alternative. Possibly Magnific Popup.

http://dimsemenov.com/plugins/magnific-popup/

**Comment by fancyapps** [comment]
Do not worry, the next major version is under development.

**Comment by unitedworx** [comment]
Nice to hear that fancybox might be getting some love. Haven't yet found an alerative for mobile devices. Anything I found was ugly code or really not working that well. The cleanest I have found in terms of its up is photoswipe however it needs tons of vanilla us code in order to work

**Comment by matiwinnetou** [comment]
@fancyapps is there any new version I am still torn whether to use fancybox2 and fancybox3. We have a commercial license.

**Comment by pinta83** [comment]
Any new on this ?

**Comment by Patta** [comment]
there are commits

**Comment by robfaas** [comment]
Excuse me @fancyapps but is it really so hard to be open about this? Now people (like me) keep up hope that version 3 might come alive someday. For years nothing is happening. I'd rather have you to speak out the truth. And, in case a new version really is being developed, then please give us a date!

**Comment by unitedworx** [comment]
@robfaas just use https://sachinchoolur.github.io/lightGallery/ and be done with it. searched a lot for months for alternatives and this is the best one I could find that works with touch devices, supports iframes, videos, has autoplay. and lots of other stuff.

**Comment by fancyapps** [comment]
Actually, v3 is just around the corner! I'm planning to release next beta this week and final version next month.

**Comment by pinta83** [comment]
Wow :)
Thats actually great news since i used beta for production site due to lack of scripts that provide everything Fancybox does :)

**Comment by robfaas** [comment]
Wow, @fancyapps , that would be great! 
@unitedworx : yeah, I also like http://unitegallery.net/ and http://photoswipe.com/ but I used Fancyapps in a lot of sites, and I am familiar with the source & options, so I would prefer to stick with it :)

**Comment by fancyapps** [comment]
See #1169

**Comment by misurex** [comment]
@fancyapps 
Thank you for your commitment, we all love your work.
Have you any update on the release date?

Thank you once again.

**Comment by misurex** [comment]
On the fancybox beta1 I really love the button that allows to display the full size of an image. Good work, I hardly wait for the official release.

**Comment by wenom64** [comment]
@misurex #1169

**Comment by SalahAdDin** [comment]
@fancyapps please!

**Comment by fancyapps** [comment]
In case someone missed, v3 has been released recently - http://fancyapps.com/fancybox/3/

**Comment by sorinpopescu** [comment]
Great! One question - V3 is compatiple with V2 scripts already in place or those needs to be updated?
Thanks

**Comment by fancyapps** [comment]
@sorinpopescu While there are similarities, they work completely different. If you are using v2 without customization, then you can simply switch to v3, otherwise - I would suggest to take a fresh start.
