### ISSUE TITLE
Fancybox Video Issue

### ISSUE THREAD

**Issue by ttseng** [fancyapps/fancyBox#1052]
I'm trying to use Fancybox to play mp4 videos from a URL, but when the user clicks on a video, it triggers a download rather than the fancybox player.  You can test it out on this page:

http://buildinprogress.media.mit.edu/projects/2565/steps

Previously, I was able to get around this by pointing to a webm video instead of mp4, but I have since removed webm conversion from my site.

Is there a way to get around this?  It is happening in Chrome and Safari.

**Comment by fancyapps** [comment]
mp4 videos are not supported out of the box. You could build an object and display it using $.fancybox.open()
