### ISSUE TITLE
Issue with fancybox-lock being not appended after once on click. 

### ISSUE THREAD

**Issue by josleow** [fancyapps/fancyBox#1053]
On gallery view, click first time and it will show fancybox which stays without being scroll up and down while fancybox overlay is scrolled. I saw that html tag has fancybox-lock class but after clicking again, fancybox doesn't stay locked as before. Checked on inspect and found that html tag doesn't have fancybox-lock class. So how to have this class back again in html tag after first click?

Version: 2.1.5

**Comment by fancyapps** [comment]
I suggest you to upgrade to v3.
