### ISSUE TITLE
Beta (3) - Error!!! Icon Expand don't be shown by special window-dimension

### ISSUE THREAD

**Issue by derSteffen** [fancyapps/fancyBox#1057]
Hello,

SOMETIMES....
if you have an image with landscape-dimension and your window has potrait-dimension the expand-Icon don't be shown.

If you have an image with potrait-dimension and your window has landscape-dimension the expand-Icon don't be shown.

I don't know!!!!!!!

Thanks very much!

Greetings

**Comment by derSteffen** [comment]
Hello, has anybody an idea?
Thanks!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by derSteffen** [comment]
Has anybody an idea to solve this problem?

Thank you very much!

Greettings

**Comment by derSteffen** [comment]
My dirty solution:
Change this:
```Javascript
canExpand = (width_ < maxWidth_ || height_ < maxHeight_) && ( current.aspectRatio ? (width < maxWidth && height < maxHeight && width < origWidth && height < origHeight) : ((width < maxWidth || height < maxHeight) && (width < origWidth || height < origHeight)) );
```
in this:
```Javascript
// canExpand = (width_ < maxWidth_ || height_ < maxHeight_) && ( current.aspectRatio ? (width < maxWidth && height < maxHeight && width < origWidth && height < origHeight) : ((width < maxWidth || height < maxHeight) && (width < origWidth || height < origHeight)) );			
if ((inner.height() < origHeight) || (inner.width() < origWidth)) { canExpand = true; }
```

If you change in the css the
a.fancybox-expand {
    position: absolute;
    top: 0;
    right: 0;
....}
you can use caption as over-type!

Greetings

**Comment by SalahAdDin** [comment]
Don't close this issue, maybe other person can help you later with a better fix.
