### ISSUE TITLE
Fancybox overlay not getting created at all but thumbs are

### ISSUE THREAD

**Issue by paramsinghvc** [fancyapps/fancyBox#1058]
I'm trying to use fancybox in my angular app through a directive. Its working fine in rest of my angular apps where I have used the same directive.Basically, I want a gallery with thumbnails type fancybox.
The problem I'm facing in my current project is that only the thumbnails are showing up and the overlay isn't being getting created at all. Attached is the screenshot of the elements tab in the developers console in chrome.
![screen shot 2015-08-13 at 6 48 35 pm](https://cloud.githubusercontent.com/assets/4329912/9250656/61eb3c5c-41ec-11e5-81e9-21ba7a8b250c.png)
![screen shot 2015-08-13 at 6 48 59 pm](https://cloud.githubusercontent.com/assets/4329912/9250657/61ecc93c-41ec-11e5-9a88-1c6d878c1f82.png)

**Comment by SalahAdDin** [comment]
Awesome, how do you a slider as these?

**Comment by paramsinghvc** [comment]
Oh.. These are not slider, that's the back side of the overlay (which is not getting displayed)

**Comment by fancyapps** [comment]
Maybe you have some JS errors on your page? They can lead to strange issues..
