### ISSUE TITLE
Problem with 'title: type: over' related to php generated images

### ISSUE THREAD

**Issue by borsti87** [fancyapps/fancyBox#1065]
Hello together,

I've a problem by using fancybox2 with following settings:

html:

```
<a title="Lorem ipsum dolor sit amet" class="galerie_group" href="getimage.php?id=0">
<img src="getpreview.php?id=0" alt=""/>
</a>
```

js:

```
$("a.galerie_group").fancybox({
    type : 'image',
    helpers : {
        title: {
            type: 'over'
        }
    }
});
```

I got:
![fancy2](https://cloud.githubusercontent.com/assets/8202684/10125056/2e942ef6-6567-11e5-98f1-6cc734809512.png)
You see the title background goes not to the end of the image, how can I fix this?
If I use normal image-files everything is fine.

Best regrades
borsti87

PS: I used jQuery JavaScript Library v1.11.3 with fancyBox - jQuery Plugin v2.1.5

**Comment by borsti87** [comment]
Is there no one who can help me?

**Comment by fancyapps** [comment]
Just play with CSS.

**Comment by borsti87** [comment]
Wow what a help! And therefore I wait over one year?

**Comment by fancyapps** [comment]
You are welcome! :) Give v3 a try! 
Have a nice day!
