### ISSUE TITLE
fancy box debugger problem.

### ISSUE THREAD

**Issue by hybaig** [fancyapps/fancyBox#1067]
I have a strange problem. I am using fancybox plugin in my codeigniter project. The fancybox runs smoothly on the local server but when i uploaded the project on the live server, the fancy box would open with a width 100 px and height 100px (Since minWidth and minHeight are both defined 100px in the js file of fancybox) and then if i click on the debugger let's say firebug on firefox, the fancybox becomes normal i.e it takes the size of the content inside. The content im using is html content. I hope u cant understand my problem and provide a solution.

**Comment by relaxnow** [comment]
I had a similar issue where FancyBox would load some AJAX content that would display an image, but it would not wait for the image in the AJAX content to get loaded to 'fitToView'.
So by default it would get 100px by 100px as minimum until you change the viewport (like when you open up your browsers debugging bar) then it would trigger an update.

I worked around this by adding the following option:
```js
          /**
           * So when we load the image HTML via AJAX,
           * fancybox is unable to see any content until the image is first loaded.
           * So for images that the user did not have in their cache,
           * it would 'fitToView' and use the minimum 100x100 size.
           * Never updating it until a browser resize.
           *
           * What we've added here is a check that sees if there are any images in the fancybox
           * and if there are wait until they are loaded and trigger a fancybox update.
           */
          afterShow: function checkUpdateRequired(context) {
            var $img = $('.fancybox-inner img', context);
            if ($img.length === 0) {
              return;
            }

            if (!$img[0].complete) {
              window.setTimeout(function() {
                checkUpdateRequired(context)
              }, 500);
              return;
            }

            $.fancybox.update();
          }
```

**Comment by fancyapps** [comment]
Sorry, I have no idea what could cause this issue. Try upgrading to v3.
