### ISSUE TITLE
Prevent page in the background from scrolling on mobile devices

### ISSUE THREAD

**Issue by nicky112** [fancyapps/fancyBox#1069]
Hi there,

I can't prevent my page from which I opened the fancybox from scrolling in on my mobile device if I just want to scroll the content inside the fancy box. This is a weird behavior. Any clue of how to fix the "background page"?

This is how I initialize my boxes:

```
        $('.fancybox').fancybox({
            onStart : function() {
                $("body").css({'overflow':'hidden'});
                $("#fancybox-overlay").css({"position":"fixed"});
            },
            onClosed : function() {$("body").css({'overflow':'visible'});} 
        });
```

**Comment by Vmadmax** [comment]
same issue here

**Comment by Craigy-** [comment]
+1

**Comment by JMarqz** [comment]
+1

It would be nice have a solution for this bug in mobile devices!

**Comment by fancyapps** [comment]
V3 is especially designed for mobile.
