### ISSUE TITLE
putting a slider into a fancybox pop up window

### ISSUE THREAD

**Issue by xplorer80** [fancyapps/fancyBox#1073]
Hi ! 

i'd wish to add my "layerslider" slider into fancybox, to have it in a bigger size, pop up, when i click on a link ( zoom link ) . 

each work fine on its side , but i'm having troubles to apply fancybox to layerslider. 

for now, i'm using an Href=id method , but i'm getting a pop up message saying : "the requested content cannot be loaded. please try again later" . 

i'm using this code :

 .... a class="fancybox" rel="group" href="#Layerslider"><img src= ...."images/bg.jpg" alt="" style="width:300px"/></a ....

can i ask you for some help to achieve this ? 
i don't know how i could do with an iframe, since the iframe use such method : 

data-fancybox-type="iframe" href="/demo/iframe.html" 

..... so , same story again i suppose. and the iframe links another page into the current page, by definition, while the slider is already in the page and not in another page. 
i'm a bit confused. 

thanks for your attention,

Adrien

**Comment by xplorer80** [comment]
edit : i tried something different : 

putting the divs of the layer slider nested into another div with an id="wrap" . 

then in the fancybox <a> , i used this wrap id :+1: 
.... a class="fancybox" rel="group" href="#Layerslider"></a ....

now , if it opens the fancybox , it displays the slider into the fancybox ( with scrolling elements on the side ) , but once i close it, the slider has disapeared from the page ! 

it's not easy.

**Comment by fancyapps** [comment]
Maybe upgrading to v3 will help.
