### ISSUE TITLE
swf - base parameter ignored

### ISSUE THREAD

**Issue by adventmedia** [fancyapps/fancyBox#1076]
Loading a swf with Fancybox - the href is
asset = "/portfolio/media/cheesy/DeckRun.swf?dev=true&offline=true&base=/portfolio/media/cheesy/"
Using the javascript call:
 $.fancybox({
            href: asset,
            width: w,
            height: h
        });

The base parameter is ignored; the swf looks for the referenced assets at the site root instead (this is the default behaviour; unless 'base' is set, the swf looks for assets relative to the page it is embedded in). Very odd as the other two parameters (def, offline) are passed in.
Workaround is to just to place referenced assets at the site root… less than ideal!

**Comment by fancyapps** [comment]
I have no idea what is causing this, but you could, for example, build your own flash object and display it using $.fancybox.open( '<your html code>' )
