### ISSUE TITLE
Problem when open another instance of fancybox from already opened one

### ISSUE THREAD

**Issue by djAjax** [fancyapps/fancyBox#1077]
When open another instance of fancybox from already opened one the fancybox-wrap is not inserted inside the fancybox-overlay.

To fix this I added one line of code for close: function(event)
$('.fancybox-overlay').remove();

If there is another solution please write a feedback.
![xhi2jpl](https://cloud.githubusercontent.com/assets/9333602/11118872/1170b1e0-894e-11e5-92be-ef4b502d4f86.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/9333602/11118893/2ec610a0-894e-11e5-8198-9b501da11c6e.png)

**Comment by azenzen** [comment]
thanks a lot!!!
i have the same problem..TAT

**Comment by azenzen** [comment]
hi djAjax,
i add your code and another bug show up.
if i close the fancybox and click the trigger again, it will show the error message "The requested content cannot be loaded.Please try again later."
can you fix that?
thx.

**Comment by djAjax** [comment]
Hi,
I am sorry but this error is not caused by that code you have been added.
This is caused by the incorrect url for fancybox.
I do not have this problem.
Please send me a feedback if all is ok.

**Comment by azenzen** [comment]
hi,
url is correct because first time i click the trigger it works well. but if i close it and click again, that error msg show up.
so i try to put your code to that line. it seems that no more error.
anyway thanks for your comment, helps me a lot!!

code:
if (!F.isOpen || event === true) {
	$('.fancybox-wrap').stop(true).trigger('onReset').remove();
	$('.fancybox-overlay').remove();//azenzen
	F._afterZoomOut();
} else {
...

**Comment by djAjax** [comment]
Very nice, thanks!

**Comment by fancyapps** [comment]
V3 supports multiple instances.
