### ISSUE TITLE
bower.json duplicate main file

### ISSUE THREAD

**Issue by Horttcore** [fancyapps/fancyBox#1078]
`{
    "name": "fancybox",
    "main": [
        "source/jquery.fancybox.js",
        …
        "source/jquery.fancybox.pack.js"
    ],
    …
}`

I think it would be better if only the packed version would be in the main object and not both.

**Comment by Traksewt** [comment]
Actually, the bower spec says to not include minified files in the main. So include the unpacked version instead.
https://github.com/bower/spec/blob/master/json.md
"Do not include minified files."

**Comment by fancyapps** [comment]
Duplicate of #820
