### ISSUE TITLE
Responsive iframe on mobile devices with scroll bars

### ISSUE THREAD

**Issue by ingozoell** [fancyapps/fancyBox#1080]
Hi,  

the lightbox works fine by browser size scaling, too. Just on mobile devices it will not work fore me. On mobile devices i got horizontal scroll bars.

**I use:**
WordPress 4.3.1
Fancybox Version 2.1.3
Bootstrap 3.2
Please see also my screenshot (iPhone 5s) and Dev-Link: http://zahnheilkunde.preview.anyframe.de/

**My Code:**

jQuery(document).ready(function($){

```
$(".fancybox, .iframe").fancybox({
    maxWidth    : 1170,
    // maxHeight    : 600,
    fitToView   : false,
    width       : '96%',
    height      : '96%',
    autoSize    : false,
    closeClick  : false,
    openEffect  : 'fade',
    closeEffect : 'fade',
    padding     : '0',
    'type'      : 'iframe',
        helpers: {
            title   : null ,
            overlay : { locked: false,

                css : {
                    // 'background' : 'rgba(0, 0, 0, 0.8)'
                    'background' : 'rgba(0,0,0, 0.85)'
                }
            }
        }
});
```

});

![device](https://cloud.githubusercontent.com/assets/2229940/11501277/334c9a7e-9833-11e5-9d35-87e8046dd40a.jpg)

Thanks
Ingo

**Comment by ingozoell** [comment]
I found the issue. Was an by WP Theme options settings. Blpease close this. Thanks

**Comment by K-Thompson** [comment]
Hi ingozoell ,

Can you enlighten us what you changed to fix the above problem?

Hopefully whatever you did will fix my problem and perhaps others as well.

Thanks.

**Comment by vrunjeti** [comment]
I believe the problem is that the `scrolling` option gets overridden on devices with touchscreens due to this code from the source:

```
if (type === 'iframe' && isTouch) {
	coming.scrolling = 'scroll';
}
```

A hacky workaround is to comment that out, and the `scrolling` option should work as expected. See a slightly more detailed explanation [here](https://github.com/fancyapps/fancyBox/issues/1101#issuecomment-201037908).

**Comment by fancyapps** [comment]
I do not think that scrolling option has something to do with this. I guess your page is missing viewport meta tag (something like "<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">").
