### ISSUE TITLE
In documentation, autoWidth and autoHeight are not described correctly

### ISSUE THREAD

**Issue by rafpaf** [fancyapps/fancyBox#1082]
The description of auto**Width** is "If set to true, for 'inline', 'ajax' and 'html' type content **height** is auto determined. If no dimensions set this may give unexpected results"
The description of auto**Height** is "If set to true, for 'inline', 'ajax' and 'html' type content **width** is auto determined. If no dimensions set this may give unexpected results"

**Comment by fancyapps** [comment]
Yeah, sorry about that.
