### ISSUE TITLE
Automatically skips to the next item in gallery

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancyBox#1084]
Hey!

I'm using fancybox 3 beta and some users are telling me that when they open a gallery with dynamically loaded content it automatically skips to the next and the next and the next quickly and then repeats. It's not set to auto or slideshow and I can't recreate the problem myself. I am using HTML5 video inside the fancybox if that helps.

I tried to get some user info and it seems like one were using Snow Leopard and Safari. Not much to go on unfortunately.

Any idea what it can be?

Thank you!!

**Comment by fancyapps** [comment]
Sorry, no idea. But the v3 is available for some time.

**Comment by seabasss** [comment]
I figured out that the space bar started the slideshow and sometimes that triggered it. I disabled that and now it works!
