### ISSUE TITLE
Images that doesn't have image extension

### ISSUE THREAD

**Issue by PhpMax** [fancyapps/fancyBox#1086]
Hello,

How can I use fancy-box to show images that doesn't have image extension like (jpg, jpeg, png, gif), I mean sometimes upload centers provide image url like:

http://domain.com/index.php?page=uc&down=1&id=4q619bmtf3rtxq1
or
http://domain.com/d-4q619bmtf3rtxq1
or
http://domain.com/image673.html

Lightbox can display all these image urls, colorbox can display them by custom settings.

Is there a custom settings for fancybox. I tried iframe but it only can display the last url type.

Thanks.

**Comment by PhpMax** [comment]
Solved:

The solution is to force your type, like so - $(".selector").fancybox({'type' : 'image'});

**Comment by woohling** [comment]
didn't work with Fancybox3. Is your version 2 or 3?

**Comment by fancyapps** [comment]
@woohling add `data-type="image"` to your links:

```HTML
<a href="images.php?id=123" data-type="image" data-caption="Caption">
	Show image
</a>
```

**Comment by woohling** [comment]
It worked! Thanks😃
