### ISSUE TITLE
Can't close fancybox after exiting fullscreen YouTube video

### ISSUE THREAD

**Issue by uxweb** [fancyapps/fancyBox#1088]
Hi!, thanks for been created such a great fancy app!! i'm enjoying it so much!.

Just discovered one thing i'm not sure if it is intended or not.

I open a youtube video in fancybox according to the main page example, then i press the fullscreen youtube player button to watch video in fullscreeen, then press esc to go out of fullscreen and then if i press esc again to close fancybox it doesn't close the fancybox.

I think that focus is out of fancybox and it doesn't catch the keypress.

If i click on the padding on facybox and then press the esc key, then it closes.

Is this intended? or is there a way to fix it?.

Thanks!!

**Comment by fancyapps** [comment]
You see, youtube videos are created inside an iframe tag. And when you click somewhere on the video, the iframed page gains focus and keyboard events are fired only inside it (and not the parent element). 
Sadly, I think there is nothing we can do.
