### ISSUE TITLE
How to show fancy box in a div

### ISSUE THREAD

**Issue by andrewskobliakov** [fancyapps/fancyBox#1089]
Hi! I have gallery and would like to show fancy box not over whole screen but in the parent div of gallery overlapping gallery thumbnails. Is that possible?

**Comment by webmarkelov** [comment]
I think this is not possible with standard tools API

**Comment by leonejo** [comment]
Yes. It is possible within the fancybox version 2.1.5, using the "parent" parameter, 

$(".fancybox").fancybox({parent:"#mydiv",fixed:false,helpers:{overlay:{fixed:false}}});
