### ISSUE TITLE
Thumbnail helper for fancyBox Global leaking problem

### ISSUE THREAD

**Issue by a7madgamal** [fancyapps/fancyBox#1090]
version: 1.0.7 (Mon, 01 Oct 2012)
I was testing our gallery component and mocha is complaining about a global leak for variable $list
I THINK it is not defined in the init function because when I added it the error was gone
kindly confirm this and I can make create a pull request for you :)
thanks!

**Comment by fancyapps** [comment]
Hi, You should try v3.
