### ISSUE TITLE
Fancybox 3 - Scrolls to top of page

### ISSUE THREAD

**Issue by ozknozsrt** [fancyapps/fancyBox#1093]
Hi guys,

If my .foo click to a.fancybox.. but i want clicking don't scroll top of page.

How is going on?

**Comment by MaffooClock** [comment]
I had the same problem and found the solution in another issue: https://github.com/fancyapps/fancyBox/issues/1003#issuecomment-77388871

**Comment by ozknozsrt** [comment]
@MaffooClock thanks for information

**Comment by WhiteSama** [comment]
And whats is solutions for this issue in fancybox**3**? Another answers good for fancybox v.2, but not for v.3

**Comment by fancyapps** [comment]
I have never encountered such issue, but, if this is caused by hiding the scrollbar, try setting - 

`$.fancybox.defaults.hideScrollbar = false;`

**Comment by WhiteSama** [comment]
Thx, it's solve my prolem

**Comment by adc91** [comment]
> I have never encountered such issue, but, if this is caused by hiding the scrollbar, try setting -
> 
> `$.fancybox.defaults.hideScrollbar = false;`

Thanks!!

**Comment by KelsoField** [comment]
if anyone has this issue, change backFocus: false, in .js

**Comment by jhonsore** [comment]
Hey,

I had a headache for solving this problem too loosing about 2 hours to solve it.

Unfortunately nothing said before helped me.

But, after looking my inspector panel on Chrome i saw that when Fancybox open it adds a class in my page called fancybox-active.

I solved this issue adding this line of coding:

```
.fancybox-active{
  height: 100% !important;
}
```

I holp it helps someone, some day.

Happy coding guys!

**Comment by fancyapps** [comment]
I wonder what CSS you have for html/body elements that causes page scrolling. As you can see on any demo, there are no issues at all.

**Comment by caramori** [comment]
I am having the exact same problem, except no solution work and after scrolling to the top the page freezes as if there was an overlay still active and nothing else works.

**Comment by caramori** [comment]
> I wonder what CSS you have for html/body elements that causes page scrolling. As you can see on any demo, there are no issues at all by default.

Ok, apparently what causes the automatic scroll to the top is:

html {
  min-height:100%;
  height:100%;
}

I had this css for footer and background purposes. So, in case someone decides to investigate further on this. That's a good start.

**Comment by Urel-GitHub** [comment]
The @caramori solution (remove height: 100%; from html) worked for me. Thanks!

**Comment by Nic787** [comment]
> > I wonder what CSS you have for html/body elements that causes page scrolling. As you can see on any demo, there are no issues at all by default.
> 
> Ok, apparently what causes the automatic scroll to the top is:
> 
> html {
> min-height:100%;
> height:100%;
> }
> 
> I had this css for footer and background purposes. So, in case someone decides to investigate further on this that's a good start.

I had this problem too. Add this in your css :
.fancybox-active{
    height:100%;
}
It fixed it for me.

**Comment by leandrozanardo** [comment]
Try this, it worked for me

`$(".fancybox").fancybox({
    openEffect: "none",
    closeEffect: "none",
    helpers: {
        overlay: {
            locked: false
        }
    },
    beforeShow:function(){ 
        $('html').css('overflowX', 'visible'); 
        $('body').css('overflowY', 'hidden'); 
    },
    afterClose:function(){ 
        $('html').css('overflowX', 'hidden');
        $('body').css('overflowY', 'visible'); 
    }
});`
