### ISSUE TITLE
rapid transitions in image gallery when using mousewheel with trackpad.

### ISSUE THREAD

**Issue by gitmihalis** [fancyapps/fancyBox#1094]
Using OS X and chrome: the images in the gallery switch rapidly between images when using the trackpad. The problem seems to be that the mouseWheel plugin is too sensitive and is flipping through the gallery for every increment of the X and Y axis.

**Comment by fancyapps** [comment]
That is a very annoying problem with Macs. You see - when you swipe, it starts triggering scroll events and there is no possible way to stop them triggering. E.g., you bind scroll event - user swipes - scroll event is triggered and processed (for example, gallery image is changed) - the scroll events keep firing - the script tries to stop them, for example, unbinds scroll events and then binds again - but they keep firing out of nowhere!

**Comment by naveedahmed** [comment]
It's been almost 3 years since the last comment. Have there been any developments on this front to avoid this issue? @gitmihalis ?
