### ISSUE TITLE
Flickering on IOS 9 when going from one image to the next even on your own gallery demo @fancybox.com

### ISSUE THREAD

**Issue by BackuPs** [fancyapps/fancyBox#1095]
Hi

if i go to this page http://fancyapps.com/fancybox/#examples and open the fancybox image gallery on a ipad or iphone and go to the next image the screen flickers (resizes) to a smaller screen and then resizes back to the correct size again.

It is a very unusual and annoying issue. It does not happen on android or f.e. ios 7.

Could you please provide a fix?

Thank you

Best regards,
B.

**Comment by BackuPs** [comment]
Hi 

I found the fix by setting the prev next  effect to fade and easing to linear

			nextEffect : 'fade', // 'elastic', 'fade' or 'none'
			nextSpeed  : 250,
			nextEasing : 'linear',
			nextMethod : 'changeIn',

			// Changing previous gallery item
			prevEffect : 'fade', // 'elastic', 'fade' or 'none'
			prevSpeed  : 250,
			prevEasing : 'linear',
			prevMethod : 'changeOut',

Best regards,
BackuPs

**Comment by fancyapps** [comment]
Please, upgrade to v3, it was designed for mobile devices.
