### ISSUE TITLE
How can I use parent's css/js inside child iframe?

### ISSUE THREAD

**Issue by namaljayathunga** [fancyapps/fancyBox#1097]
I use bootstrap css and jQuery inside node-webkit. I can't use css/js file inside child frame for some cases. so how can I use parent's css/js file for child page? Thanks

**Comment by fancyapps** [comment]
I think you should ash this to node-webkit community, because fancybox just creates container and and an iframe for content. Then you should access parent page using the same techniques as from any other iframe.
