### ISSUE TITLE
Fancybox Showing Scroll Bars only in Windows 10 Chrome

### ISSUE THREAD

**Issue by dumbo0001** [fancyapps/fancyBox#1101]
This seems to happen on computers with a touch screen. See: 
http://www.unknownerror.org/opensource/fancyapps/fancyBox/q/stackoverflow/2268330/jquery-fancybox-but-i-don39t-want-scrollbars

**Comment by vrunjeti** [comment]
I tried many of those suggestions (which I believe originally came from http://stackoverflow.com/questions/2268330/jquery-fancybox-but-i-dont-want-scrollbars). I ended up with this mess:

```
$('.fancybox-media').fancybox({
  afterShow: function(){
    this.inner.css({
      overflow: 'hidden'
    })
  },
  overflow: 'hide',
  type: 'iframe',
  scrolling: 'no',
  iframe: {
    scrolling: 'no',
    preload: true
  },
  helpers: {
    media: {},
    overlay: {
      css: { 'overflow' : 'hidden' }
    }
  }
})
```

The only one that "worked" was the `afterShow` method, but there is a very noticeably delay between opening the video and hiding the scrollbars.

Digging into the source, I found that the lines that cause this problem are:

```
if (type === 'iframe' && isTouch) {
	coming.scrolling = 'scroll';
}
```

This might explain why this might seem to only be an issue for Windows 10 computers, but this code suggests that it's an issue with devices with touchscreens (of which many happen to be running Windows 10). 

If you want to solve the problem in a hacky way, you can comment those lines out (around line 880), and it should no longer override the `scrolling` option. i.e. you still have to set `scrolling: no` in your configuration, and it should work as expected. 

Obviously, doing so will leave the implications of handling the scrollbars on devices with touchscreens up to you (but I still wonder why this design decision was made).

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
