### ISSUE TITLE
Multiple Sprite Images

### ISSUE THREAD

**Issue by coyote10** [fancyapps/fancyBox#1103]
I haven't edited or messed with any of the original jquery.fancybox.css code, but for some reason I am getting a doubling up of the close and left arrow sprites in the upper right hand corner. Anyone had anything like this happen?
![multiple](https://cloud.githubusercontent.com/assets/17953437/13900795/2433ff2c-edd4-11e5-9309-afb9698b4838.jpg)

**Comment by tsbain** [comment]
@coyote10 - Did you get this fixed? I cannot get the close image to show at all.

**Comment by coyote10** [comment]
@tsbain - No I never did figure it out. I ended up going with a different lightbox altogether.

**Comment by fancyapps** [comment]
@tsbain @coyote10  Without seeing your page, I can only guess that some css rule affects fancybox.

**Comment by tsbain** [comment]
@fancyapps @coyote10 - Thanks, guys. I did get it working, although I can't remember now how I did it. I can go back and look at it if you'd like. Just let me know.
