### ISSUE TITLE
Fancybox overrides scrolling option on devices with touchscreens

### ISSUE THREAD

**Issue by vrunjeti** [fancyapps/fancyBox#1105]
Fancybox seems to override the `scrolling` option for some people, and I believe that the source of this issue stems from these lines of code from the source:

```
if (type === 'iframe' && isTouch) {
    coming.scrolling = 'scroll';
}
```

I think this suggests that this is only an issue on devices with touchscreens, which might be consistent with some others' issues on [Windows 10](https://github.com/fancyapps/fancyBox/issues/1101) and [phones](https://github.com/fancyapps/fancyBox/issues/1080).

I'm posting this as a new issue since I believe it might help others with the same problem. A quick and hacky fix could be to remove/comment those lines of code out, but I am wondering why the design decision of forcing scrollbars on touchscreen devices has been made in the first place.

**Comment by mrdaneeyul** [comment]
I'm getting the same thing. Chrome sometimes reports as a touch screen as well.

I implemented the custom fix below so to allow us to control the scrollbars, but like vrunjeti, I'm wondering why the decision was made in the first place, since it's an inline style that's almost impossible to override. Anyway, here's my fix:

```
if (type === 'iframe' && isTouch && coming.scrolling !== 'no') {
    coming.scrolling = 'scroll';
}
```

**Comment by fancyapps** [comment]
Hi. This trick fixed scrolling on iOS and mobile browsers would no need to display scrolbars anyway.
This snippet also is included in v3, but the check for "isTouch" is different and should not detect falsy on desktops.
