### ISSUE TITLE
No Auto Play = Fuzzy Youtube Thumb

### ISSUE THREAD

**Issue by gera3d** [fancyapps/fancyBox#1108]
Ok I can't seem to figure this out.  If I turn auto play off on youtube the thumbnail that shows up is fuzzy even though we have a high quality custom thumbnail in place.  Any idea what causing this?

**Comment by fancyapps** [comment]
Sorry, no idea. Maybe upgrading to v3 will help. There you are able to set your custom thumbnails, if needed.
