### ISSUE TITLE
The "PDF viewer" goes to unauthorized site.

### ISSUE THREAD

**Issue by prcoy** [fancyapps/fancyBox#1111]
Okay, I know it's not your problem exactly but the "Open PDF" viewer (http://jsfiddle.net/RHaAX/) is going to some other site that the one you have. Your FancyBox just shows a blank so I cut and pasted the "http://samplepdf.com/sample.pdf" just to see why it was blank. **Wow** did I get the wrong web page!. Perhaps you could look into a different PDF file temporarily?

**Comment by fancyapps** [comment]
Thanks, I'll change path to other sample file.
