### ISSUE TITLE
How to change where fancybox2 looks for it's supporting images like fancybox_loading.gif etc

### ISSUE THREAD

**Issue by jamesla** [fancyapps/fancyBox#1114]
I'm trying to set up grunt integration and need to change where fancybox2 looks for it's supporting images like fancybox_loading.gif etc currently they seem to look in the same folder that the css is in.

Does anybody know how I can do this?

**Comment by fancyapps** [comment]
fancybox does not look for css file itself :) You can put it anywhere, just make sure that it gets loaded in your page :)
