### ISSUE TITLE
Set start and end timing when youtube autoplay on fancybox popup

### ISSUE THREAD

**Issue by faliqaiman** [fancyapps/fancyBox#1115]
I would like to set the youtube video timing when fancybox trigger. But it wont happen and seems like it will start normally even if I set the start and end time on the youtube link. How to solve this issue?

Here's the youtube code when set the start and end time.

`https://www.youtube.com/v/chElHV99xak?start=53&end=59`

**Comment by k-man** [comment]
have you found an answer, I'm also looking for a solution to that problem

**Comment by fancyapps** [comment]
Try using v3 - http://fancyapps.com/fancybox/3/

**Comment by k-man** [comment]
Does it apply to websites ?

**Comment by fancyapps** [comment]
What do you mean by that?

**Comment by k-man** [comment]
I thought it works only for mobile apps 

I figure it out... It worked like a charm

Thanks a million

**Comment by k-man** [comment]
any idea how to change the youtube dimensions, i.e. width and height ?

**Comment by fancyapps** [comment]
Good question, I will create a sample and update documentation about that tomorrow (going to sleep right now :))

**Comment by k-man** [comment]
Sure, waiting for the answer, 
take care :))

**Comment by faliqaiman** [comment]
for fancybox v2, I'm using the helpers and add this code;

$(".media-stability").fancybox({
  helpers: {
    media: {},
  },
  youtube: {
    autoplay: 1,
    start: 152,
    end: 163,
  },
});

**Comment by faliqaiman** [comment]
By the way, can you update on fancyapp v3 licensing agreement?
Thanks

**Comment by fancyapps** [comment]
@faliqaiman check samples at Documentation - http://fancyapps.com/fancybox/3/docs/#embedding
And I`m working on licensing info right now.

**Comment by k-man** [comment]
fancyapps  you did not answer me regarding how to change the youtube dimensions, i.e. width and height ?

**Comment by fancyapps** [comment]
@k-man I kinda hoped you would check that link (http://fancyapps.com/fancybox/3/docs/#embedding) and find out about sizing :)
Basically, just use CSS to control dimensions (http://codepen.io/fancyapps/pen/PWZrzw?editors=1100):

```
.fancybox-slide--video .fancybox-content {
	width  : 800px;
	height : 600px;
	max-width  : 80%;
	max-height : 80%;
  margin: 0;
}
```

**Comment by GeorgeRT** [comment]
So what was the solution?  I've tried different permutations starting with the youtube provided URL and using the CodePen from the #embedding documentation (http://codepen.io/fancyapps/pen/mRVNyO?editors=1000):

https://youtu.be/gHE5pun0kqg?t=5m32s
https://www.youtube.com/gHE5pun0kqg?t=5m32s
https://www.youtube.com/watch?v=gHE5pun0kqg&amp;t=5m32s
https://www.youtube.com/watch?v=gHE5pun0kqg&amp;start=5m32s

Thanks.

**Comment by fancyapps** [comment]
For YouTube - https://www.youtube.com/watch?v=_sI_Ps7JSEk&amp;start=50
For Vimeo - https://vimeo.com/191947042#t=50s

**Comment by GeorgeRT** [comment]
Got it. Use start & convert to seconds.  Thanks!
