### ISSUE TITLE
Fancybox bower install doesn't include minified files?

### ISSUE THREAD

**Issue by kramer65** [fancyapps/fancyBox#1116]
I've just installed the bower package for fancybox, and to my surprise it doesn't contain minified versions of the css and js files. Am I missing something or was this done on purpose?

**Comment by fancyapps** [comment]
The should be "jquery.fancybox.pack.js" and there is no minified css yet.

**Comment by kramer65** [comment]
Ah now I see. Is there a reason it is called `.pack.js` instead of the more common `.min.js`?

**Comment by fancyapps** [comment]
Back in the 2008 it was not so common :) I think it will be changed when v3 will come out.

**Comment by kramer65** [comment]
Ah I understand. didnt' realise this plugin is so old already.. :-)

Not a biggie this anyway, just a heads up that you can make the plugin better with very simple changes (changing around a couple names and minifying the css).

Cheers!

**Comment by marcwieland95** [comment]
By the way. Is there a plan when version 3 will be ready?

**Comment by fancyapps** [comment]
V3 is available for some time.
