### ISSUE TITLE
Click on content inside iframe kills fancyBox keyboard navigation (prev/next via Arrow keys)

### ISSUE THREAD

**Issue by ZaneCEO** [fancyapps/fancyBox#1118]
Hi,
I've a peculiar issue with fancyBox.

First of all: [here is my demo of the issue](https://onedrive.live.com/redir?resid=558D3A55BFED4CC5!6906&authkey=!AMYNF6GKqA_k078&ithint=file%2czip).

The problem is this: I've a page with multiple link. Each link opens a fancyBox iframe URL with some content in it.

Example of the "main" page:

```
<a rel="gallery" class="fancybox fancybox.iframe" href="content1.html">link1</a>
<a rel="gallery" class="fancybox fancybox.iframe" href="content2.html">link2</a>
<a rel="gallery" class="fancybox fancybox.iframe" href="content4.html">link3</a>
```

```
<script>
        var fancyboxOptions = {
                    autoSize    : false,
                    fitToView   : true,
                    width       : '50%',
                    height      : '50%',
        };

        $(".fancybox").fancybox(fancyboxOptions);
</script>
```

Example of the iframe-opened page:

```
<p>
    Example text Example text Example text Example text Example text Example text
</p>
```

If you just open the links everything works fine: you can use the keyboard's Arrow keys left and right to go to the next and previous link.

The issue arises when you click anything inside the fancyBox-opened window: the click disrupts the ability to use the keyboard to go next/prev.

Switching to fancybox.ajax effectively solves the problem, but the whole page is pretty complex and many part are already coded with the iframe-based approach in mind, so switching fancyBox method is not an option.

I was wondering if you could have a look at it and maybe easily fix the issue on your side.

Thank you very much for your time.

Note: [at first I thought it was jquery-expander](https://github.com/kswedberg/jquery-expander/issues/115) but the behaviour is easily reproducible even without it.

**Comment by vool** [comment]
same issue here

**Comment by fancyapps** [comment]
The script listens to "keydown" events on the page, but when iframe gets focus, these events get triggerred only inside the iframe. You can, for example, just add something like this inside your iframed page:

```JavaScript
<script>
	$( document ).on('keydown.fb', function (e) {
		var keycode = e.keyCode || e.which;

		if ( keycode === 27 ) {
			e.preventDefault();
			parent.jQuery.fancybox.close();
			return;
		}
	});
</script>
```

**Comment by vool** [comment]
Hi Thanks for the swift reply. Don't think that is my issue.. I have an iframe in a gallery when I try to click on any content in the inner page it triggers the next/previous action on the gallery.
Maybe I am missing something ?

**Comment by fancyapps** [comment]
Sorry, I can not image what exactly is happening there - "it triggers the next/previous action". Maybe you are clicking on the navigation arrows?

**Comment by vool** [comment]
No, if I am correct in gallery mode js detects where on modal you click, if you click anywhere on the left side (and not just the navigation arrows) i goes back and if you click on the right hand side it goes forward.
Is this not right ? Is there a way to disable this and just use the navigation arrows ?

**Comment by fancyapps** [comment]
No, it does not work that way :) I am pretty sure you are clicking on the arrows. Move then outside using CSS or just disable them.

**Comment by vool** [comment]
Are we talking about the same thing here ?
:)

https://www.youtube.com/watch?v=nl1oE5edCA8

**Comment by fancyapps** [comment]
Press right mouse button and choose "Inspect" (or "Inspect Element" - depending on browser) to reveal what element you are clicking on. In your video, you are clicking on navigation links. You probably got confused when I called them "arrows", because they just contain arrow icons.

**Comment by vool** [comment]
That's the issue, these elements won't let me click any content that lies in the iFrame under them. 

Si there any way around this ?

**Comment by fancyapps** [comment]
1) Move arrows - http://jsfiddle.net/Xh3B2/
2) Do not show them - http://jsfiddle.net/fwwhp8cL/

**Comment by vool** [comment]
Thanks, that did the job !
