### ISSUE TITLE
Title-bar readjusted in IE 10 and below

### ISSUE THREAD

**Issue by Samantha996** [fancyapps/fancyBox#1120]
Fancy-Box
Location: JqueryfancyBox.js
Issue: A certain line in the switch statement located on line 1912 re-sizes with width of the of the title bar for IE 10 and below.

Ex:
`switch(type) {
                                                                case 'inside':
                                                                                target = F.skin;
                                                                break;

```
                                                            case 'outside':
                                                                            target = F.wrap;
                                                            break;

                                                            case 'over':
                                                                            target = F.inner;
                                                            break;

                                                            **default: // 'float'
                                                                            target = F.skin;

                                                                            title.appendTo('body');

                                                                            if (IE) {
                                                                                            **title.width( title.width() );**
                                                                            }

                                                                            title.wrapInner('<span class="child"></span>');

                                                                            //Increase bottom margin so this title will also fit into viewport
                                                                            F.current.margin[2] += Math.abs( getScalar(title.css('margin-bottom')) );
                                                            break;
                                            }

                                            title[ (opts.position === 'top' ? 'prependTo'  : 'appendTo') ](target);
                            }
            };` 
```

A declared width could be added as an attempt to resolve the issue, however, it does not fill the exact width size
![ie3](https://cloud.githubusercontent.com/assets/18430190/15410298/d4981640-1dcd-11e6-8fc4-27b032e2a383.png)

 In addition, the title bar does not re-size along with the screen size, as shown below:
![ie2](https://cloud.githubusercontent.com/assets/18430190/15410319/e536567e-1dcd-11e6-8acb-5d0ebd2615da.png)

The specific error is located on line 1912, in where the default case at the end of the switch statement re-sizes the title bar if the browser being used is IE, 

```
                                                                            if (IE) {
                                                                                            **title.width( title.width() );**
                                                                            }
```

Due to this line of code, the width of the title bar in IE 10 or below is readjusted and an inline width is added to the title bar HTML. This causes the width in the original CSS files to be overridden by the new calculated width. 

In order to rectify the issue, the user must add an !important line next to the width of the title bar. While this does fix the problem at hand, it complicates the issue for the user and causes the user to implement CSS syntax that is not usually recommended.
![ie1](https://cloud.githubusercontent.com/assets/18430190/15410324/e925e696-1dcd-11e6-8be6-8dfb3915f663.png)

A jsFiddle has been created to demonstrate the problem and the solution.

https://jsfiddle.net/r35uy3sp/1/ -- Issue
https://jsfiddle.net/r35uy3sp/2/ -- Solution

**Comment by fancyapps** [comment]
Thanks for your work! I guess somebody will find this useful.
