### ISSUE TITLE
a bug when url has @

### ISSUE THREAD

**Issue by pwtitle** [fancyapps/fancyBox#1121]
<a href="http://u.linktour.com/development/198/bf/b7.jpg@800w" target="_blank" rel="group" class="lightbox"><img src="http://u.linktour.com/development/198/bf/b7.jpg@60h" style="margin-right:10px;height:60px;" class="thumb"></a>

It can not work when A href has "@"

**Comment by fancyapps** [comment]
Same as #1119 and many more.

**Comment by pwtitle** [comment]
thanks
