### ISSUE TITLE
Add module to npm

### ISSUE THREAD

**Issue by DCKT** [fancyapps/fancybox#1122]
Hello,

It might be cool to use fancyBox with npm. 
Maybe by wrapping all the code in a function export ?

Thanks for your work :)

**Comment by SalahAdDin** [comment]
But, if i don't bad remember, the npm module exist.

**Comment by martijngastkemper** [comment]
Which of the NPM modules is the real one: https://www.npmjs.com/browse/keyword/fancybox

**Comment by fancyapps** [comment]
There is no "official" one, try any of these.

**Comment by martijngastkemper** [comment]
Thanks for the answer. I prefer to use the direct source so I add ``"fancybox": "https://github.com/fancyapps/fancyBox#master"`` to my ``package.json``.

**Comment by webmarkelov** [comment]
Master branch will can change, better specify the tag:
 ``` npm i -S git://github.com/fancyapps/fancyBox.git#3.0 ```

**Comment by fancyapps** [comment]
The npm package named "fancybox" is a fork by someone else. The owner changed versioning and now he claims that he can not transfer ownership due to versioning mismatch.

**Comment by SalahAdDin** [comment]
Add fancybox-official or some like this :D

**Comment by jorrit** [comment]
Or `fancyapps-fancybox`.

**Comment by fancyapps** [comment]
Hi, everybody! I have created a scoped package and it can be found here: 
https://www.npmjs.com/package/@fancyapps/fancybox

And this is how you can install it:
`npm install @fancyapps/fancybox`

I just need to refine my workflow, to make npm+gulp+github work nicely.

**Comment by fancyapps** [comment]
Hello, again!

I just wanted to inform that v3.0.48 is the same as v3.0.47, I just had to increase version numbering before publishing to npmjs.org (publishing package was not successful on the first try).

Sorry if this caused any misunderstanding.

**Comment by cbovis** [comment]
I've attempted to introduce fancybox to our codebase using `require('@fancyapps/fancybox')` however I get the following error:

_TypeError: t is not a function. (In 't(document)', 't' is undefined)_

We're packaging up frontend code using webpack which has been fine so far for other libraries installed via NPM.

**Comment by fancyapps** [comment]
@cbovis Looks like you are using minified version and therefore error message is not quite obvious, I can bet it complains about missing jQuery, because `t(document)` probably is `$(document)` somewhere in the code.

So, could you check that jQuery is actually loaded for you?

**Comment by SalahAdDin** [comment]
@fancyapps, good work man, thank you.

**Comment by danielnieto** [comment]
@cbovis I had the same issue, it is because jQuery is 'missing' (webpack doesn't expose it globally) so a quick workaround would be to do this in the same file you require fancybox: 
```javascript
window.$ = window.jQuery = require("jquery");
```
however this feels kind of dirty to me, so I've found that by adding jQuery as a webpack plugin it works like a charm:


```javascript

//webpack.config.js
...
plugins: [
        new webpack.ProvidePlugin({
            'jQuery': 'jquery',
            'window.jQuery': 'jquery',
            'jquery': 'jquery',
            'window.jquery': 'jquery',
            '$': 'jquery',
            'window.$': 'jquery'
        })
    ]
...
```
After you do this, you can just require fancybox as you would expect
```javascript
const fancybox = require("@fancyapps/fancybox");
```
 without even requiring jquery.

I've found the first solution here: [https://laracasts.com/discuss/channels/elixir/how-to-use-jquery-plugins-wwebpack](https://laracasts.com/discuss/channels/elixir/how-to-use-jquery-plugins-wwebpack) they suggest another solution but it didn't work for me (setting jQuery as plugin and passing it on the require function)

**Comment by SalahAdDin** [comment]
@danielnieto I think would very good add your considerations in the documentation.
