### ISSUE TITLE
AutoSize and update function works only on Firefox

### ISSUE THREAD

**Issue by Salamafet** [fancyapps/fancyBox#1123]
Hello,

I use iFrame with form. After validate form I need to resize the fancybox for the confirmation message.

I use this function parent.$.fancybox.update();

But it's only works on Firefox. I have try on Chrome, IE, Edge, Opera and even Midori.

This my fancybox configuration:

``` javascript
$(".support").fancybox({
    openEffect  : 'fade',
    closeEffect : 'fade',
    maxWidth : '50%',
    maxHeight : '85%',
    width       : '50%',
    //height    : '85%',
    //minHeight : '5%',
    minWidth    : '50%',
    padding     : 1,
    margin      : 1,
    autoSize    : true,
    closeBtn : false,
    autoResize : true,
    autoCenter : true,
    autoHeight : true,
    fitToView  : false,

    //####################
    type : 'iframe',
    //####################
    helpers   : { 
        overlay : {closeClick: false}
    }
}).trigger("click");
```

I have try many configuration without success.

Here is [my testing website](http://mail.zorio.fr/hotline)
I have disable form verification if you want to test. Without the maxHeight the frame is equal to 9973 px on my screen.

Thanks for your help.

**Comment by fancyapps** [comment]
Please, upgrade to v3 and report if you are still experiencing this issue. I have no idea why auto-size would not work on Chrome, therefore a working demo would help.
