### ISSUE TITLE
Using jQuery 3.0.0 breaks fancybox thumbnails :-(

### ISSUE THREAD

**Issue by clausharup** [fancyapps/fancyBox#1125]
Using Fancybox v. 3 & thumbnails does not seem to work with jQuery 3.0.0

**Comment by ystar** [comment]
jquery 3 remove .load function for dom. 
see https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed
You can hack the code:  jquery.fancybox-thumbs.js Line 71
$("<img />").load
=>
$("<img />").on('load',

**Comment by vmorari** [comment]
//Load each thumbnail
     $.each(obj.group, function (i) {
       var el   = obj.group[ i ],
         href = thumbSource( el );

       if (!href) {
         return;
       }

       $("<img />").on("load", function () {
         var width  = this.width,
           height = this.height,
           widthRatio, heightRatio, parent;

         if (!that.list || !width || !height) {
           return;
         }
this is what i have by default on the lines 63 - 79 and the thumbs are not working. any idea why ?

**Comment by fancyapps** [comment]
Looks like you are using older version, please, upgrade to the latest.
