### ISSUE TITLE
Fancybox Overlay Issue

### ISSUE THREAD

**Issue by ergineroglu** [fancyapps/fancyBox#1126]
We are loading fancybox css file dynamically after page load and try to open fancybox with overlay active and custom html content. 

Sometimes overlay doesn't appear. If we try to open fancybox with a delay, probability of getting no overlay is decreasing, but it is not totally gone away.

Sometimes overlay does not appear and in these cases overlay div is not generated:
![emagaza segmentify facebook test](https://cloud.githubusercontent.com/assets/5336000/16515637/cbdca67c-3f7b-11e6-9bf9-418f71fcf3bb.png)

We are using version: 2.1.5 (Fri, 14 Jun 2013)

Our initialization code is given below:

``` js
var fancyboxParams = {
  minHeight: 10,
  width: params.width || 'auto',
  height: params.height || 'auto',
  autoSize: false,
  autoWidth: params.width ? false : true,
  autoHeight: params.height ? false : true,
  autoHide: params.autoHide,
  topRatio: params.topRatio || topRatio,
  leftRatio: params.leftRatio || leftRatio,
  title: title,
  helpers: {
    title: (title && params.windowStyle !== 'seamless') ? {
      type: 'inside',
      position: 'top'
    } : null,
    overlay: (params.overlay != "false") ? {} : null
  },
  content: notificationBody,
  fixed: false, // HADDITION - scroll with the page 16.10.2015
  wrapCSS: (params.cssClass || "") + " " + "fancybox-" + (params.windowStyle || "seamless"),
  beforeShow: function () {
    cssCode && $('<style />').html(params.cssCode).prependTo(this.outer);
    try {
      javascriptCode && eval(javascriptCode);
      beforeShow.call(this); // change context
    }
    catch (err) {
      $.fancybox.close(true);
    }
  },
  afterClose: function () {
    $(".fancybox-segmentify").remove();
  }
};

if (params.isModal == 'true') {
  fancyboxParams.closeBtn = false;
  fancyboxParams.closeClick = false;
  fancyboxParams.keys = null;
  if (fancyboxParams.helpers.overlay) {
    fancyboxParams.helpers.overlay.closeClick = false;
  }
}

$.fancybox(fancyboxParams);
```

We load fancybox css dynamically like:

``` js
_loadCSS: function (url, onload) {
      // Load css file
      var link = document.createElement('link');
      link.type = 'text/css';
      link.rel = 'stylesheet';
      link.media = 'screen';
      if (onload && typeof onload === 'function') {
        if (typeof link.onreadystatechange !== 'undefined') link.onreadystatechange = function () {
          if (this.readyState == 'loaded' || this.readyState == 'complete') {
            onload();
            link.onreadystatechange = null;
          }
        };
        else link.onload = onload;
      }
      link.href = url;
      document.getElementsByTagName('head')[0].appendChild(link);
      return link;
    },
```

**Comment by awansoekamto** [comment]
Same issue here. 19 days and still no one tries to fix this?

**Comment by indotek68** [comment]
Same here issue here. I had to do some crazy hack just to add an overlay if the fancybox-overlay did not load.

**Comment by ergineroglu** [comment]
It is a game changer for us and there is no solution, even reply, in one month. 
We are considering switching to other alternatives

**Comment by K-Thompson** [comment]
To those that write it is a "game changer" or are complaining that there is lack of response, I say to you, "who cares about you?".  It's amazing that so many feel entitled to on going support and use a threatening tone when a project doesn't do what you need it to do. It's as if threatening that you are not going to use it is going to magically get your issues resolved.

It's not. This project is, for all practical purposes, apparently abandoned.

It's a great lightbox if it does what you want it to do, use it. If not, move on, or of course, you can always take the source and fix it.


Cheers.

**Comment by fancyapps** [comment]
I`m sorry, but I have no idea what could cause this issue. Seeing some demo would help. 
Anyway, try upgrading to v3.
