### ISSUE TITLE
Need Enhancement : Show Custom Social Share button on fancybox load

### ISSUE THREAD

**Issue by KarthikDev81** [fancyapps/fancybox#1128]
Hi,
Thanks for fancybox. It's very useful and elegant display. In my scenario, I need Popup Image with thumbnail. I used thumbnail coding its working fine. But need social share for each and every image. For ex: I need this code for every image load in fancybox.
https://codepen.io/jacmaes/pen/HJkae

**Comment by fancyapps** [comment]
What would clicking on these buttons do?

**Comment by fancyapps** [comment]
Hi,

Recently, a new "Share" module was added. Any feedback is welcome!
