### ISSUE TITLE
beta version on `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [fancyapps/fancyBox#1133]
hi, recently we want to add v3 beta 1 to cdnjs.com, i want to confirm are v3 beta 1 files also on git repo?
and is it possible to have a git tag for it or in the future? 
http://fancyapps.com/fancybox/beta/

https://github.com/cdnjs/cdnjs/issues/6191
https://github.com/cdnjs/cdnjs/pull/8357

**Comment by fancyapps** [comment]
v3 is already on git, but looks like it will be accessible when 3.0 branch will be switched with the master (in couple of days).

**Comment by maruilian11** [comment]
Thanks!

**Comment by fancyapps** [comment]
@maruilian11 I`m sorry, I misunderstood your question. I thought you were asking about current state of v3, but now I understand that you were referring to old beta. That beta was not made public on github and was just a preview, it was not meant for public use. 

Sorry about misunderstanding.

**Comment by maruilian11** [comment]
It's ok. Sorry I'm not a native English speaker.
We are going to add v3 ASAP. Thanks!
