### ISSUE TITLE
fancyBox not working on small screen such as mobile and tablet or any screen less than 992 px width

### ISSUE THREAD

**Issue by ayman6784** [fancyapps/fancyBox#1135]
Hi there 

I'm using a theme based on bootstrap 3.1 on drupal and I'm tried to use fancyBox on some images I notice when I use the class col-md or col-sm or col-xs for the div which contains the fancybox image, the image not pop up and the images only apper as thumbs on any screen smaller than 992 px, but it working on any screen larger than 992, however the fancybox is working on small screen if I removed the class col-XX

here my code ( which not working on small screen )
`<div` class="col-md-3 col-sm-3 col-xs-6 "`>`
`<`a href="http://newdrop.xxx.org/sites/default/files/22.jpg"  class="fancybox fancybox-insert-image" data-fancybox-group="gallery-all"`>`
`<`img typeof="foaf:Image" src="http://newdrop.xxx.org/sites/default/files/styles/medium/public/22.jpg?itok=1XedBAwt" alt=""  class="image-medium" /`>`
`<`/a`>``<`/div`>`

`<`div class="col-md-3 col-sm-3 col-xs-6 "`>`
`<`a image-pop href="http://newdrop.xxx.org/sites/default/files/33.jpg"  class="fancybox fancybox-insert-image" data-fancybox-group="gallery-all"`>`
  `<`img typeof="foaf:Image" src="http://newdrop.xxx.org/sites/default/files/styles/medium/public/33.jpg?itok=x2WI930u" alt=""  class="image-medium" /`>`
`</a`>`<`/div`>`

and here the working code, if I removed col-XX
`<div`>`
`<`a href="http://newdrop.xxx.org/sites/default/files/22.jpg"  class="fancybox fancybox-insert-image" data-fancybox-group="gallery-all"`>`
`<`img typeof="foaf:Image" src="http://newdrop.xxx.org/sites/default/files/styles/medium/public/22.jpg?itok=1XedBAwt" alt=""  class="image-medium" /`>`
`<`/a`>``<`/div`>`

`<`div`>`
`<`a image-pop href="http://newdrop.xxx.org/sites/default/files/33.jpg"  class="fancybox fancybox-insert-image" data-fancybox-group="gallery-all"`>`
  `<`img typeof="foaf:Image" src="http://newdrop.xxx.org/sites/default/files/styles/medium/public/33.jpg?itok=x2WI930u" alt=""  class="image-medium" /`>`
`</a`>`<`/div`>`

Any suggestion 

Thanks

**Comment by fancyapps** [comment]
Screen size can not affect fancyBox functionality.
