### ISSUE TITLE
Composer Support

### ISSUE THREAD

**Issue by Magi1053** [fancyapps/fancyBox#1137]
This package is not listed on https://packagist.org/

I have also attempted to add this repository to my composer.json using:

```
"repositories": [
    {
      "name": "fancyapps/fancyBox",
      "url": "https://github.com/fancyapps/fancyBox.git",
      "type": "git"
    }
  ]
```

But I get the error 

> [InvalidArgumentException]
>   Could not find package fancyapps/fancybox at any version for your minimum-stability (stable). Check the package
>   spelling or your minimum-stability

**Comment by kitsguru** [comment]
Composer is used for PHP dependencies.

You likely want to use bower for JS code repositories.
