### ISSUE TITLE
Thumbnails duplicated

### ISSUE THREAD

**Issue by rocklance** [fancyapps/fancyBox#1142]
Hello,
I'm using fancybox to display some images.
The issue is that when i'm opening the fancybox from MacBook or iMac, the arrows and cancel button aren't visible and sometimes the thumbnails are duplicated, but the images are displayed properly.
If you can check this issue from OS X device,  test it here : 
http://dabeatspot.com/songs/59333-smoke-chambers/

**Comment by fancyapps** [comment]
Hi, If you still have this issue, then, please, comment.
