### ISSUE TITLE
Img Scrolling to Top

### ISSUE THREAD

**Issue by lgund** [fancyapps/fancyBox#1147]
Hey,

I am using Fancybox for my Images on https://teamspeak.first-coder.de/. If I click there a Image and I scroll automatic to the top of the page.... First I thought it´s cause it´s a link (<a>) but I´ve tried also as a div element... it´s the same.

But there is also something rly strange. If I click a picture and it will open in full screen it also open my sidemenu o_O. 

You can have a live example at https://teamspeak.first-coder.de/

**Comment by DredderGun** [comment]
Same problem!
I tried to paste this code
`    $('.image').fancybox({
        helpers: {
            overlay: {
                locked: false
            }
        }
    });`
But it didn`t help me

**Comment by morgant** [comment]
I am running into a variant of this issue as well. Using fancybox 2.1.5, I have anchor links which have fancybox registered on them, but they insist on scrolling to the element and I have yet to be able to prevent the default click/scroll to action.

**Comment by fancyapps** [comment]
Try upgrading to v3.

**Comment by morgant** [comment]
@fancyapps Actually, upgrading to 5.1.6 did the trick. There's a lot more packed into that version than the one change noted in the release notes (see Issue #1202).
