### ISSUE TITLE
different galleries in same page with different dimentions

### ISSUE THREAD

**Issue by kodjoe** [fancyapps/fancyBox#1151]
hello I'm using fancubox 3.0 Beta version and I would like to know if 
we can have different galleries in same page with different dimentions ?

I mean one gallery with margin another without and the last one in fullscreen ?

I have to play with jquery.fancybox.css or  jquery.fancybox.js or both of them ?

thank you

**Comment by fancyapps** [comment]
You could call` $('your selector').fancybox({ /* your options */});` for each gallery and pass different options for each of them.
