### ISSUE TITLE
Fancybox Next Previous buttons not showing up even if rel="gallery" applied

### ISSUE THREAD

**Issue by hashir-dhattiwala** [fancyapps/fancyBox#1153]
Please check my site (Magento CE 1.9.3.0) with custom News module displayed in Center [here](http://115.112.143.25/ECO/mag/magento193/).

As you can see, the Facnybox popup is configured and works fine, but the next previous buttons doesn't show up even if rel="gallery" is used.

Below is the code I am using.
```
$cnjQ('.news-owlgrid').children().find('a.cn-read-more').each(function() {
		$cnjQ(this).click(function() {
			var contentHref = $cnjQ(this).attr('href');
			$cnjQ.fancybox({
				//'type': 'iframe',
				'width': 600,
				'height': 'auto',
				'autoSize': false,
				'showNavArrows': true,
				//'content': $cnjQ(contentHref).show(),
				'content': $cnjQ(contentHref).html(),
				'beforeLoad': function() {},
			});
		});
	});
```
Let me know why this occurs and how to fix it, as I don't want to replace this popup library with others.

Waiting....
Hashir

**Comment by fancyapps** [comment]
Why are you using ".each(function() {" ? You are attaching fancybox to each link individually.

**Comment by hashir-dhattiwala** [comment]
I have content structure such that I have to have a "Read More" link inside each news item so that clicking on it's own "Read More" link will only open it's own news in popup, so I don't get, how could I change structure and keep all the read-more links or all the content boxes in one parent box ?

Do you have any idea how could I not use "each" function and still achieve same result with minor structural changes if needed ?

Could you help out here ?

**Comment by fancyapps** [comment]
I do not understand where is your problem, you can use fancybox without any additional code - http://jsfiddle.net/T6NKD/472/
