### ISSUE TITLE
Empty data-fancybox-title attribute is ignored

### ISSUE THREAD

**Issue by Stadly** [fancyapps/fancyBox#1154]
When specifying something like `<a href="#foo" title="Information" data-fancybox-title="">More info</a>`, the fancybox should have no title, since `data-fancybox-title` is specified to be the empty string. Instead the empty `data-fancybox-title` is ignored and the `title` attribute is used instead. This happens when specifying any value that is evaluated to false, such as data-fancybox-title="0", where the title should be "0", but is instead "Information" from the `title` attribute.

**Comment by fancyapps** [comment]
Please, upgrade to v3 where data attributes are checked for existence.

**Comment by Stadly** [comment]
How do I install v3 using Bower?

**Comment by fancyapps** [comment]
v3 currenty lives in 3.0 branch, therefore you could use something like this:

`bower install fancyapps/fancyBox#3.0 --save`
