### ISSUE TITLE
Reset a fancybox instance?

### ISSUE THREAD

**Issue by sethdorris** [fancyapps/fancyBox#1157]
So I'm trying use fancybox to display a summary of an order after a user clicks on "Add to Cart" button. However, this only works one time, and I think it is becuase Fancybox cannot reinitialize on the second click.

I need a fancybox to be initialized for each time the user clicks the "Add to Cart" button so that a user can click the "Continue Shopping" button which closes the fancybox and add another color of the same item to their cart if they want to, without having to refresh the page / reload the JS.

so the first time a user loads the page this is what my DOM will contain (for the hidden a tag for the fancybox)

```html 
<a class="displayNone iframe" id="addedToCartHiddenLink" href="#"></a>
```
A form is submitted, and on submit initializes and triggers the hiddenAnchorTag

```js
 $("#addToCartForm").submit(function (e) {
                var serializedData = $(this).serializeArray();
                serializedData.push({ name: "skuSelectionSubmit", value: $("#addToCartButton").val() });
                // call to serialize() isn't including this
                $.post($(this).attr("action"), serializedData, function (data) {
                    if (data) {
                        $("#addedToCartHiddenLink")
                            .fancybox({
                                'height': 640,
                                'width': 980,
                                'autoDimensions': false,
                                'onClosed': function () {
                                    console.log("CLosed");
                                    updateCartInfo();
                                },
                                onComplete: function() {
                                    //This removes the load mask added in the $(document).on("click", "#addToCartButton", function () call in product-sku-selection.js
                                    $("#productDetails").removeLoadMask();
                                    //For accessibility we set focus to the fancybox iframe, otherwise focus is still on the parent page.
                                    $("#fancybox-frame").focus();
                                },
                                content: data
                            })
                            .trigger("click");
                        //adds event listener to the html content loaded via AJAX call above into the fancybox to close the fancybox
                        $(document).on("click", "#quickViewContinueShopping", function() {
                            document.getElementById("fancybox-close").click();
                        })
                    }
                });
                e.preventDefault();
            });
```
The problem here is, I feel like I need a fancybox.destroy() method to get rid of the instance of fancybox so that if the user clicks the "Add to Cart" button again, the fancybox can be reinitialized.

I've tried manually writing a method to do that where I delete the hiddenAnchorTag from the DOM and rebuild it, but that didn't work.

Anyone know of a way to do this?

**Comment by fancyapps** [comment]
Seems like you need to understand how fancybox works. 
When you do $('YOUR_SELECTOR').fancybox({....}); then you are making elements matching YOUR_SELECTOR clickable. And when users click on one of them, then the script will try to figure out content source and type by looking at that element.
But you can open fancybox manually, like http://jsfiddle.net/hLeprz73/ - and you can generate the content on the fly. Or you could just simply update some inline element and display that instead.

**Comment by sethdorris** [comment]
Okay, so I changed the code to this... 

```js
$("#addToCartForm").submit(function (e) {
                e.preventDefault();
                var serializedData = $(this).serializeArray();
                serializedData.push({ name: "skuSelectionSubmit", value: $("#addToCartButton").val() });
                // call to serialize() isn't including this
                $.post($(this).attr("action"), serializedData, function (data) {
                    if (data) {
                        $.fancybox({
                            'height': 640,
                            'width': 980,
                            'autoDimensions': false,
                            'onClosed': function() {
                                console.log("CLosed");
                                updateCartInfo();
                            },
                            content: data,
                            onComplete: function() {
                                //This removes the load mask added in the $(document).on("click", "#addToCartButton", function () call in product-sku-selection.js
                                $("#productDetails").removeLoadMask();
                                //For accessibility we set focus to the fancybox iframe, otherwise focus is still on the parent page.
                                $("#fancybox-frame").focus();
                            }
                        });

                        $(document).on("click", "#quickViewContinueShopping", function() {
                            $.fancybox.close();
                        })
                    }
                });
            });
```
and the close button (which is part of the ajax returned content) does not work... however the close set my fancybox does, and if I try to click on the "AddToCart" button again to fire off the same AJAX request for a new item, I get this error

`VM15532:39 Uncaught TypeError: Cannot read property 'hide' of undefined`

which is thrown by fancybox code here

```js
_abort = function() {
			loading.hide();

			imgPreloader.onerror = imgPreloader.onload = null;

			if (ajaxLoader) {
				ajaxLoader.abort();
			}

			tmp.empty();
		},
```

Also the button in the AJAX content "Continue Shopping" which calls `$.fancybox.close()` throws this error

`VM15532:933 Uncaught TypeError: Cannot read property 'is' of undefined`

which is thrown here in fancybox

```js
$.fancybox.close = function (dismiss) {
		if (busy || wrap.is(':hidden')) {
			return;
		}

		busy = true;

		if (currentOpts && false === currentOpts.onCleanup(currentArray, currentIndex, currentOpts)) {
			busy = false;
			return;
		}
```
at the wrap.is because wrap is undefined.... why is wrap undefined and why is loading undefined?
