### ISSUE TITLE
How do i make an ess grid video FULL screen when clicked? 

### ISSUE THREAD

**Issue by mike212916** [fancyapps/fancyBox#1159]
Hello, my theme support referred me here, hoping someone can help. 

I have an Ess grid on my WordPress. I have set up it to play video from lightbox. 

But when im on my website, and i click play, it plays very small.

Question: How do I make it so that when the video is clicked. it goes to FULL screen?

Thanks,
Mike

**Comment by fancyapps** [comment]
You could try (mething like this http://jsfiddle.net/xck5huL7/ ), but it will not work due to security conecerns, you will receive an error message like "Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.".
