### ISSUE TITLE
`scrolling: no` doesn't take effetcs with iframes (rel. 2.15)

### ISSUE THREAD

**Issue by massimo-cassandro** [fancyapps/fancyBox#1160]
I need to hide scroll bars usinh an iframe, but I can't find the way

I tried with all these parameters

```
scrolling    : 'no',
iframe       : {scrolling: 'no'},

beforeShow   : function() {
    $(this.inner).css({
        'overflow': 'hidden'
    });
},
afterShow    : function() {
    this.inner.css({
        'overflow': 'hidden'
    });
}
```

Only `afterShow` works but scroll bars are removed after iframe is loaded, causing an unpleasant effect

**Comment by fancyapps** [comment]
Please, upgrade to v3 where scrolling should work as expected.
