### ISSUE TITLE
Update method do not work

### ISSUE THREAD

**Issue by mediaceh** [fancyapps/fancyBox#1161]
When i call $.fancybox.update() it do not pass several condition
`if (!F.isOpen || didUpdate) {	
				return;
			}`
F.isOpen is false in my case. Next condition wich it do not pass
`if (!current || F.isClosing) {
					return;
				}`
current  is false in my case.

It my code of call window 
`    $.fancybox.open({
			href : url,
			scrolling: 'no',
			titleShow: false,
			type: 'iframe',
			padding: 0,
			maxWidth: 610,
			//maxHeight: 1450,
			fitToView: false,
			//autoSize: false,
			autoSize: true,
			//autoResize: true,
			closeBtn: false,
			helpers: {
				overlay: {
					locked: false
				}
			},
			//onUpdate: function() { $(this).update();  }
		});`
If i resize browser widow fancybox updated and set height of content in 100%.  But after call a update method nothing happens.

**Comment by fancyapps** [comment]
Please, update to v3. There you can control width/height using CSS or override it using JS.
