### ISSUE TITLE
fancybox - preventing losing data when closing an iframe container while uploading files

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancyBox#1162]
is there a way to have fancybox running, but force it to keep an instance active inside an iframe which I want to use to upload files to the server by the user? so that the file uploading process is not cancelled when the user exits the fancy lightbox momentarily or even accidentally?

your help is greatly appreciated.

**Comment by fancyapps** [comment]
You could, for example, use "beforeClose" callback to do something with your data and even prevent closing if needed.
