### ISSUE TITLE
Fancybox does not opening on first click

### ISSUE THREAD

**Issue by acreed829** [fancyapps/fancyBox#1163]
Hi, i have used fancybox on this website: https://bestdigitals.ru/product/smartfon-xiaomi-redmi-note-3-pro-32gb-black/

i'm calling the fancybox eith the next code: 
<script type="text/javascript">
    jQuery(document).ready(function() {
        if(MatchMedia("only screen and (min-width: 760px)")){
        $(".fancybox").fancybox({
            beforeLoad  : false,
            fitToView   : false,
            width       : 'auto',
            maxWidth      : '100%',
            autoSize    : true,
            fitToView   : 'auto',
            closeClick  : false,
            openEffect  : 'none',
            closeEffect : 'none',
            controls    : true,
            prevEffect  : 'none',
            nextEffect  : 'none',
            helpers : {
                title   : {
                    type: 'outside'
                },
                thumbs  : {
                    width   : 60,
                    height  : 60
                }
            }
        });
        }
    });
</script>

The problem - the fancybox is not opening untill the entire page is not loaded (i guess), because if i open the page and I click on image - the fancybox open on 4-5th click.
The same code i have used here: http://acreed.c48404.tmweb.ru/product/smartfon-xiaomi-redmi-note-3-pro-16gb-black/
and is works great. Can you help please

**Comment by fancyapps** [comment]
Looks like you have some some kind of preloading script that displays loading icon over the image and therefore it is not clickable.
