### ISSUE TITLE
Too Many Videos

### ISSUE THREAD

**Issue by BillMeeks** [fancyapps/fancyBox#1164]
I've set up a Sharepoint page where I have several clickable thumbnails in a grid that you can click on and load a video in fancybox. Unfortunately after adding around 9 videos to the page they have issues loading. The fancybox will pop up but it's empty, and sometimes the page locks up and I have to refresh. I'm assuming it might be a memory error? Is there any way to unload previous videos from memory when the user closes the fancybox?

**Comment by fancyapps** [comment]
Works fine for me - http://jsfiddle.net/rodt8w0k/
