### ISSUE TITLE
In default "download" package, videos in demo>index.html do not work

### ISSUE THREAD

**Issue by beckah** [fancyapps/fancyBox#1166]
The default download that is linked on http://fancyapps.com/fancybox/#examples :

![Button on website](http://i.imgur.com/ygiB6YX.png)

Has the project file fancyapps-fancyBox > demo > index.html.
In this file none of the videos are properly being displayed.

**Comment by fancyapps** [comment]
If you are viewing on local computer, then they would not work (and ajax emaple, too).

**Comment by beckah** [comment]
I have CORES enabled via a chrome extension. Is there any reason why this won't work when locally hosted?

**Comment by fancyapps** [comment]
Just use a webserver or install webserver on your computer. Personally, I use VirtualBox and Laravel Homestead.
