### ISSUE TITLE
two box then the last not center,fancybox version is 2.1.5

### ISSUE THREAD

**Issue by kunyin1010** [fancyapps/fancyBox#1168]
I use fancybox with a capsule
		alert : function(msg,closeFlag,callBack) {
		    var reg = new RegExp("\\[([^\\[\\]]*?)\\]", 'igm'); 
		    var html = document.getElementById("MessageBox_message").innerHTML;
		    var result = html.replace(reg, function (node, key) { return { 'Content': msg }[key]; });
		    $.fancybox(result, {
		        'padding': 0,
		        'scrolling': 'visible',
		        'closeBtn': true,
		        'modal': false,
                        'scrollOnCenter':true,
		        afterClose:function(){
		        	if(closeFlag){
		        		parent.$.fancybox.close();
		        	}
		        	if(callBack){
						callBack();
					}
		        }
		    });
		},

when callBack also has a alert,and the main page has a scroll bar,scrollOnCenter don't work,who can help me?

**Comment by fancyapps** [comment]
Why would you close fancybox using afterClose callback? It does not make sense to me, because it is already gone at that point.
