### ISSUE TITLE
v3 Custom Interactions / Zooming

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1175]
I may be getting overly ambitious for day one, but here we go.

I would like to change the interaction that occurs when clicking/tapping the slide.

By default, this initiates the zoom. I would instead like this to show/hide the info bar, controls and caption. 

I would then like to create a custom zoom button in the control bar.

On touchscreen, pinching should still zoom the image.

So I'm guessing I need to know how to access the zoomIn and zoomOut functions using callbacks, and how to replace the slide click/tap action. 

If such things are even possible ... if not, is this something you could keep in mind for a future release?

Thanks,
Matt

**Comment by mjcampagna** [comment]
Just tried things on my iPhone and realized it works mostly as I want there, insofar as tapping hiding the UI. That's great! I might be okay then with things as they are, and will perhaps put a custom button in the control bar to show/hide captions on desktop ...

**Comment by fancyapps** [comment]
Working on this.

**Comment by fancyapps** [comment]
I just wanted to inform that it is taking a bit more time than expected. But it continues to take shape - http://imgur.com/a/EfhzQ :)

**Comment by fancyapps** [comment]
v3.1 allows to customize click action and animation/transition effects.
