### ISSUE TITLE
v3 Margins and Zooming

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1179]
When zooming an image, the margin option is not respected, and so it's not possible to pan the image such that the top or bottom most portions are not overlaid by the caption or control bars. I would very much like for images to respect the margin values when zoomed in.

**Comment by fancyapps** [comment]
That is actually intentionally designed to maximize available space while zooming.

But, the layout is created to be very customizable - you can move or resize each block and therefore you can do something like this: http://codepen.io/fancyapps/pen/ggrRBP


Remove default margin:
```
$('[data-fancybox="images"]').fancybox({
  margin: 0
})
```

Make sliding area smaller:
```
.fancybox-slider-wrap {
  top: 44px;
  bottom: 44px;
}
```

**Comment by mjcampagna** [comment]
Thanks! That works for me.

**Comment by madeckel** [comment]
I also would prefer to have a margin (same value for top bottom left right) also when an image is zoomed in. But at the current version there's no longer a "fancybox-slider-wrap" class.  I tried out several modifications but I wasn't successful, I only get margins on top and left. How would it work at the current version?
