### ISSUE TITLE
v3 Creating side-panel like fancybox-thumbs

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1180]
So I'm attempting to create another side-panel, similar to fancybox-thumbs. I have partially succeeded in this, though I'm not able to get the translate styling working on on the slide. This is what I'm working with so far:

```javascript
onInit : function( instance ) {

		instance.$refs.menuButton = $('<button class="fancybox-button fancybox-button--menu" title="Menu"></button>')
			.appendTo( instance.$refs.buttons );

		instance.$refs.menuButton.on('touchend click', function(e) {
			e.stopPropagation();
			e.preventDefault();

			instance.$refs.container.toggleClass('fancybox-container--menu');
		});

		instance.$refs.menu = $('<div class="fancybox-menu"></div>')
			.appendTo( instance.$refs.container );

},
```

I then have styling in place that moves the controls, caption and slider to the right, positions and displays the panel appropriately, etc. Much the same as fancybox-thumbs, except that when opening thumbnails, there are some inline CSS translate properties added to the image slide to move things over, and I'm not seeing how to toggle those values.

Am I taking the right approach with this?

**Comment by mjcampagna** [comment]
I guess what I'm hoping is that there's a built-in function for recalculating the image position/scale ... ?

**Comment by mjcampagna** [comment]
I think I've found it. Calling `instance.scaleToFit();` in my .on() function seems to do the trick.

I would still be curious to know whether you feel I'm taking the right approach with this, or if there's a better way. Thanks!

**Comment by fancyapps** [comment]
I guess you are looking for `update( immediately, andSlides, andContent);` and use it like  `instance.update( true, true, true );` 

I actually was having hard time naming methods and choosing options; still not sure if it chose right.

**Comment by mjcampagna** [comment]
Yes, that works nicely.

Is there a way to trigger a closure of the thumbnails (when open) by clicking any other button?

Also, is there a callback when the thumbnails are opened or closed?

**Comment by fancyapps** [comment]
OK, I`ll try to give you some details about fancybox internals, I hope this will help you to better understand how fancyBox works and will help you in the future.

1) Run this snippet in js console while fancybox is active - `$.fancybox.getInstance()` - this should return current fancybox instance.

2) Inspect that object. take a look at keys:
    - first, at the top, there will be listed keys whose name is starting with $ - these are jQuery references to DOM objects like $caption (obviously, this is refering to element containing caption! :));
    - next, there comes objects whose names are capitalized - these are instance objects of plugins/extensions (or whatever you wish to call them) like FullScreen or Thumbs;
    - then comes internally used properties/objects that you probably should not touch. But, for example, you could try to mess with  `group` object to add/remove items from gallery.

So, this is how you can get access to, for example, Thumbs object - 
`$.fancybox.getInstance().Thumbs` - check that out and you will find methods (under `__proto__`) like:

`$.fancybox.getInstance().Thumbs.toggle();`
`$.fancybox.getInstance().Thumbs.show();`
`$.fancybox.getInstance().Thumbs.hide();`


About callbacks - these are not currently implemented, because I did not thought that someone would need them. Btw, why would you need them?

**Comment by mjcampagna** [comment]
@fancyapps Thanks! That's helpful. I've been digging around in your JS as well, and it's surprisingly well organized and relatively easy to follow. Nice work! The only problem is that my Javascript isn't quite on par with yours, so I can follow a lot of it, but then there are places I get lost.

> About callbacks - these are not currently implemented, because I did not thought that someone would need them. Btw, why would you need them?

I'm experimenting with creating additional drawers, similar in format to your Thumbs drawer, but which would contain other types of content (i.e. social media links for sharing, a cart interface, etc.).

I've roughed in some drawers to test functionality, so nothing final at this point. Let's say my drawer is named "Menu". So I can open and close Menu. When I open Menu, I can check whether Thumbs is open using instance.Thumbs.isVisible, and if so, I can close it to prevent drawers overlapping (potential z-index conflict).

However, when opening Thumbs, I have no way of checking whether Menu is open, so can't close it in the same way. A callback on Thumbs, such as "onToggle", would theoretically allow me to check the state of other instances I've created, such as Menu, and to close them if necessary.

Hopefully that makes enough sense. I'm probably a bit of an edge case, but I have a habit of heavily customizing lightboxes. One of the reasons I'm so excited about Fancybox 3 is that is does seem to be very flexible in this regard, and so could make an excellent replacement for my current implementations of Photoswipe and Magnific.

**Comment by mjcampagna** [comment]
For all of the modules -- Thumbs, Fullscreen, Slideshow -- it might be nice to have a consistent set of callbacks: onStart, onEnd, onToggle. It's Thumbs I'm most concerned with at the moment, but I could see potential uses for all.

**Comment by mjcampagna** [comment]
Okay, here's a question. Say I've got this:

```html
<a href="page.html" data-fancybox="gallery" data-src="image.jpg">
<img src="thumbnail.jpg" />
</a>
```

In the Fancybox instance, "current" refers to the IMG element. How can I reference the trigger, the A element? For example, if I want to get the 'href' value, or the value of some extra 'data-' attribute.

**Comment by fancyapps** [comment]
1) `current` actually refers to the current galley object, you can just inspect it to check what it contains:

`$.fancybox.getInstance().current;`

2) Original element is hidden under `current.opts.$orig`

**Comment by mjcampagna** [comment]
That's perfect. Thanks! I wouldn't have found that; I did go digging around in the instance earlier, but didn't find it.
