### ISSUE TITLE
Callback events not fired when attached using $.fancybox.open()

### ISSUE THREAD

**Issue by Phil-G** [fancyapps/fancyBox#1183]
If I open a fancybox like so:
`$.fancybox.open({ src: '/MyPage.htm', beforeClose: function () { console.debug('beforeClose'); } });`
my beforeClose function is never called. I'm not sure if any of the events work.

**Comment by fancyapps** [comment]
Hi, Sorry, the API has changed a bit. Your snippet would work for v2, but now you would need to use 'opts' to pass custom options:

```
$.fancybox.open(
	{
		src : 'iframe.html',
		opts : {
			beforeClose: function (instance, current) {
				console.debug( 'beforeClose: ' );
				console.debug( current );
			}
		}
	}
);
```

This separation helps when working with group objects, for example, check value of `current` in snippet above. In v2 there would be a total mess - all options and object properties would be all together, but now you can easy see object properties like its index (`index`), some flags (like `isLoaded`), reference to content object (`$content`) and so on. And all options are available under `opts` property.
