### ISSUE TITLE
FancyBox 3 : group of youtube video, only first youtube video works

### ISSUE THREAD

**Issue by sachacohenfr** [fancyapps/fancyBox#1188]
Hey !

All is in the the title, when i create a group of video with FancyBox, I have the right element count (1/3) but when i click on arrow, the video leave and nothing append, I have a grey screen (overlay).

**Comment by phifa** [comment]
same here

**Comment by fancyapps** [comment]
Hi, Upgrade to the latest! 

Working demo : http://codepen.io/fancyapps/pen/apBWQv?editors=1000
