### ISSUE TITLE
Cannot create a modal dynamically 

### ISSUE THREAD

**Issue by mnickey** [fancyapps/fancyBox#1189]
When I write this hard coded in my index.html it appears as a modal, the desired result. This also tells me that .fancybox is connected and working.
```
        <div class="myModal" id="modal">
            <a class="fancybox fancybox.iframe" href="https://www.youtube.com/embed/UeztI8FbAJ0">Google me</a>
        </div>
```
However, when I create a function to create multiple lines after a get call to YouTubes v3 API it redirects the page to the corresponding video. Each of the returned results are appended to the ID of `#results` div.
```
function getOutput(item){
    var videoId = item.id.videoId;
    var title = item.snippet.title;
    var description = item.snippet.description;
    var thumb = item.snippet.thumbnails.high.url;
    var channelTitle = item.snippet.channelTitle;
    var videoDate = item.snippet.publishedAt;

    // Build Output String
    var output =
        '<li>' +
        '<div class="list-left">' +
        '<img src="'+thumb+'">' +
        '</div>' +
        '<div class="list-right myModal" >' +
        '<h3>' +
        '<a class="fancybox fancybox.iframe" href="https://www.youtube.com/embed/'+ videoId +'">'+title+'</a>' +
        '</h3>' +
        '<small>By <span class="cTitle">'+channelTitle+'</span> on '+videoDate+'</small>' +
        '<p>'+description+'</p>' +
        '</div>' +
        '</li>' +
        '<div class="clearfix"></div>';

    return output;
}
```

**Comment by mjcampagna** [comment]
Your script-built modal doesn't exist on the page, so Fancybox doesn't see it when it runs. Try building your modal following an `.on("click", ...)` event.

Otherwise you will need to append() the built HTML into the page, so that the markup exists before Fancybox runs.

**Comment by mnickey** [comment]
Great catch and thank you very much!
