### ISSUE TITLE
Inline Modal, Multiple Close Buttons

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1190]
I've found a bug. When opening an inline modal, the script creates a button[data-fancybox-close] element. If I open the modal again, it creates another button, and another every time the modal is opening, without ever removing the button from the modal container. So if I open the modal four times, there are four buttons stacked on top of each other.

**Comment by fancyapps** [comment]
Good catch! :) I fixed that and it will be included in the next commit. 

btw, I`m right now working on huge update that will bring performance improvements. I hope I`ll finish today.

**Comment by mjcampagna** [comment]
Sounds great! Thanks for the quick response, and I'll be looking forward to the performance improvements. =D
