### ISSUE TITLE
closeClickOutside doesn't work in Chrome

### ISSUE THREAD

**Issue by manueljrr** [fancyapps/fancyBox#1191]
I set closeClickOutside = True but in Google Chrome doesn't work. Firefox work fine.

**Comment by mjcampagna** [comment]
Case and syntax matter.

```javascript
closeClickOutside : true,
```

**Comment by manueljrr** [comment]
Case and syntax is right, but I noted when the fancybox touches the bottom of the window the outside click doesn't work.

**Comment by fancyapps** [comment]
Are you using the latest version?

**Comment by manueljrr** [comment]
Yes, I downloaded the core.js file from this repo (latest push 4 days ago). For now I have forced that the fancybox can not reach 100% of the width of the window.

**Comment by fancyapps** [comment]
The latest version was committed 15 hours ago :)

Anyway, I recommend creating structure of your modal content to something like this - http://codepen.io/fancyapps/pen/JEoOvK?editors=1100

e.g., separate header, content and footer; set content height to something like max-height: 50vh;
