### ISSUE TITLE
data-options not being read when used with data-fancybox

### ISSUE THREAD

**Issue by Phil-G** [fancyapps/fancyBox#1192]
When using `data-fancybox` and` data-options`, the options are not being read.
Example:
`<a href="javascript:void(0)" data-src="http://www.google.com" data-fancybox="window1" data-options="{iframe: {scrolling: 'yes'}}">Open</a>`

**Comment by fancyapps** [comment]
You must be careful to write valid JSON, this should work:

`<a href="javascript:void(0)" data-src="http://www.google.com" data-fancybox="window1" data-options='{"iframe": {"scrolling": "yes"}}'>Open</a>`

**Comment by Phil-G** [comment]
Interesting
`<a href="javascript:void(0)" data-src="http://www.google.com" data-fancybox="window1" data-options='{"iframe": {"scrolling": "yes"}}'>Open</a>` works

`<a href="javascript:void(0)" data-src="http://www.google.com" data-fancybox="window1" data-options="{'iframe': {'scrolling': 'yes'}}">Open</a>`  does not

I though the quotes were interchangeable
