### ISSUE TITLE
Can't use Select element in modal

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1195]
I'm opening an inline modal with some form elements. Unfortunately, I'm not able to use any select element appearing in Fancybox.

**Comment by fancyapps** [comment]
Thanks. I`m in the middle of rewriting large pieces of code, but in the meanwhile you can disable gestures or fix source code by adding addition check for select element inside "isClickable" method (guestures.js).

**Comment by mjcampagna** [comment]
Thanks! That will work for now, and I'll be looking forward to the next commit.

**Comment by fancyapps** [comment]
Should be fixed.

**Comment by mjcampagna** [comment]
Further developments on this. Select elements are now clickable, but something about Fancybox is preventing interaction events with those select elements. For example:

```javascript
$('select').on('change', function(){ 
	console.log("The option is changed!");
});

$('select').on('click', function(){ ... });
$('select').change(function(){ ... });
```

If I kill Fancybox and interact with the select inline in the page, then things work just fine.
