### ISSUE TITLE
Callback beforeLoad / beforeShow

### ISSUE THREAD

**Issue by Webtransformer** [fancyapps/fancyBox#1196]
Hi, I want to append custom markup before fancyBox is loading. I tried with beforeLoad and beforeShow but everytime I click the next or previous button these two callbacks are executed every time.
What is the right callback? I want to execute a function on initialisation of fancybox.

thanks in advance

**Comment by fancyapps** [comment]
Hi, 

Looks like you are looking for "onInit" callback, but it really depends on your needs.

Where do you want to place that that custom markup and what is the purpose of that?

J.

**Comment by Webtransformer** [comment]
I want to attach an custom close button outside the fancybox wrapper.

**Comment by fancyapps** [comment]
@Webtransformer a quick example: http://codepen.io/fancyapps/pen/QdMLNw

**Comment by Webtransformer** [comment]
Thanks for your very fast response!
Currently I am using fancyBox v2.1.5.
Do I have to switch to another version?

**Comment by fancyapps** [comment]
For the example above - yes, see http://fancyapps.com/fancybox/3/

**Comment by Webtransformer** [comment]
Didn´t know about this version. Thank you very much!
