### ISSUE TITLE
Cannot detect on('change') events on Select elements

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1197]
I replied to [our thread a few days about about select elements](https://github.com/fancyapps/fancyBox/issues/1195), but as that thread is closed, I wanted to make sure this would be seen. If you have some preference on this sort of conduct in reporting issues, please let me know. 

Anyway, here's the thing:

Select elements are now clickable, but something about Fancybox is preventing interaction events with those select elements. For example:

```javascript
$('select').on('change', function(){ 
	console.log("The option is changed!");
});

$('select').on('click', function(){ ... });
$('select').change(function(){ ... });
```

If I kill Fancybox and interact with the select inline in the page, then things work just fine.

**Comment by fancyapps** [comment]
Oh, I accidentally copy/pasted wrong issue number in commit title, that commit actually fixes #1199

**Comment by fancyapps** [comment]
btw, I tested "select" element and it works fine for me - http://codepen.io/fancyapps/full/MJvEZm/

**Comment by mjcampagna** [comment]
Thanks. The problem seems to be limited to dynamically created select elements. Can you please take a look at this? http://codepen.io/mjcampagna/pen/qRXVgW

**Comment by mjcampagna** [comment]
The problem might be that even the containing element doesn't exist at the time the on() function is running; I might need to choose a persistent parent selector ... This problem might be mine, not yours. I'll dig further into it.

**Comment by fancyapps** [comment]
Quite obvious. Think about how your code executes:

1) You try to bind "change" event to element having ID "my-select". But this element does not yet exist!

2) User opens fancybox, element "#my-select" is created.

3) User changes "#my-select", nothing happens. Why? Because it is fresh, without any "change" event.

**Comment by mjcampagna** [comment]
Looks like we're writing replies simultaneously. I came to the same conclusion just now. Thanks for confirming it!

**Comment by fancyapps** [comment]
Yes, that`s right :)
Basically, your code would work, if you would use "delegated" events, for example:

```
$('body').on('change', '#my-select', function() {
	$("#my-test").html("The option value is changed to: " + $( this ).val() );
});
```
