### ISSUE TITLE
Commercial Licensing

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1198]
I've been waiting to see the license page setup on the Fancybox 3 site, but that still hasn't happened. I'm curious about the cost of licensing Fancybox 3 for inclusion in commercial web software.

**Comment by ckristo** [comment]
+1 .. I'm planning to use fancybox on a commercial website. What if I purchase a license for v2 now, may I upgrade to v3 later on?

**Comment by fancyapps** [comment]
v3 is a free upgrade. Licensing basically stays the same. 
Each commercial software or theme for sale requires one "Extended License".

**Comment by mjcampagna** [comment]
> v3 is a free upgrade. Licensing basically stays the same. Each commercial software or theme for sale requires one "Extended License".

Beautiful! Thank you. Is that "Extended License" the fancyBox Multi Domain License, on [this page](http://sites.fastspring.com/fancyapps/product/store)? If not, please point me to the correct point of purchase. I'm ready to pull the trigger on licensing.

**Comment by fancyapps** [comment]
Yes, it is the same (naming will be simplified to "Single/Extended").
