### ISSUE TITLE
loop:false, swiping from last image reveals the first

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1199]
I think this is a new bug since rewriting the positioning code. When loop:false is set, and you swipe from the last image in a set as if moving to the next image (which doesn't exist), the first slide is revealed in transition -- as if the slideshow is attempting to loop, though it's not supposed to -- then the slideshow snaps back to the last image.

**Comment by HerrPi** [comment]
Is this Bug really fixed? Does it have something to do with #1197?
My setting loop: false is still not working. The gallery goes from the last to the first image and vice versa.

**Comment by HerrPi** [comment]
I'm talking about the 3.0 branch, btw. I tested it with v3.0.19.

**Comment by fancyapps** [comment]
Are you sure you are using correct selector? e.g. if you are having something like his - $("something").fancybox(...); - then $("something") actually returns collection of your elements?
Because this issue was fixed, but maybe you are not using it correctly and therefore default values are applied.
