### ISSUE TITLE
Second fancybox opening

### ISSUE THREAD

**Issue by Sam116** [fancyapps/fancyBox#1201]
Fancybox v3. If i open second modal window, current do not close and new inserted after it. In v2 of fancybox it works correctly.

**Comment by fancyapps** [comment]
I can`t believe this! Multiple modal instances is the major feature of v3, but you report this as an issue.

Anyway, you can close previous instance before opening a new one using `$.fancybox.close();`, if needed.

**Comment by camilawaz** [comment]
hi @fancyapps 
I'm open a new instance inside of one too, but I need the first one to close once the second is opened. 
I tried $.fancybox.close(); with beforeLoad, but it doesn't work. How can I set $.fancybox.close();  to close just the first one (it has a different baseClass). 
heres a very poor and quick code pen: https://codepen.io/camila_waz/pen/LzNgaj
Thanks

**Comment by camilawaz** [comment]
@fancyapps makes perfect sense. Thanks a mil 👍
