### ISSUE TITLE
Version numbers not updated in source code

### ISSUE THREAD

**Issue by RichardDavies** [fancyapps/fancybox#1202]
The version number was not incremented from 2.1.5 to 2.1.6 in various source code files when version 2.1.6 was released. For example, jquery.fancybox.js still claims to be v2.1.5.

**Comment by morgant** [comment]
+1

**Comment by morgant** [comment]
In addition to version numbers in jquery.fancybox.js & jquery.fancybox.css not being updated, the changelog was not updated.

**Comment by fancyapps** [comment]
Sorry, totally forgot that version numbering was not auto-updating there. In 3.0 branch gulp is configured to update it automatically.
