### ISSUE TITLE
fancybox-lock & fancybox-margin

### ISSUE THREAD

**Issue by GeorgeRT** [fancyapps/fancyBox#1204]
These class toggle seem to be missing in V3.  I think someone else may be having a problem with the content shifting when the scrollbar (overflow) is hidden when fancybox opens.  Thanks.

**Comment by mjcampagna** [comment]
Scrollbars are tricky business these days. For example, using desktop Chrome, if there's a mouse plugged in, there will be a scrollbar; if there is no mouse, no scrollbar. So we might check to see whether we have a scrollbar in this way:

```javascript
$(document).ready(function() {
	if ( $(window).width() < window.outerWidth ) {

	}
});
```
To put this to use with Fancybox, we might try something like this:

```javascript
$(document).on('onInit.fb', function(e, instance) {
	if ( $(window).width() < window.outerWidth ) {
		var addMargin = window.outerWidth - $(window).width();
		$('body').css({
			marginRight : addMargin,
			overflow    : 'hidden'
		});
	}
});

$(document).on('afterClose.fb', function(e, instance) {
	$('body').removeAttr('style');
});
```

**Comment by GeorgeRT** [comment]
Thanks. I'll use this if fancyapps won't incorporate in V3.  Right now I'm reusing V2 definitions of those two classes & toggling them in afterLoad/afterClose.

**Comment by fancyapps** [comment]
Just add `compensate-for-scrollbar` class to avoid shifting
 http://fancyapps.com/fancybox/3/docs/#faq
