### ISSUE TITLE
Something wrong, when image have "()" name in url.

### ISSUE THREAD

**Issue by alexBirder** [fancyapps/fancyBox#1205]
When the image has a caliper in the address, the image can not be opened.
Try it yourself and fix it please.

**Comment by mjcampagna** [comment]
Jānis may or may not want or be able to implement a workaround for this, but you really ought to use "web-safe" file name conventions when publishing images online. That mean letters, numbers, hyphens and underscores only.

**Comment by fancyapps** [comment]
If you are learning PHP, take a look at this useful method - http://php.net/manual/en/function.urlencode.php
Read http://www.faqs.org/rfcs/rfc3986.html to learn about "Reserved Characters".
