### ISSUE TITLE
V3 closeBtn

### ISSUE THREAD

**Issue by GeorgeRT** [fancyapps/fancyBox#1207]
V3 closeBtn: false - still shows button if type is iframe.  Thanks.

**Comment by fancyapps** [comment]
Works for me. 

But, It will be visible if you are opening and pdf file (how could you close it otherwise?).

See this demo - http://codepen.io/fancyapps/pen/pRavyP

**Comment by GeorgeRT** [comment]
I have added a "Home" button instead of a close: https://test.jojie.one/CSCalamine

**Comment by fancyapps** [comment]
First, I noticed that you are using fancyBox in the old way. You should use it like this:

```
$.fancybox.open(
  [
    {
      src : 'https://player.vimeo.com/video/167833502?autoplay=1&amp;portrait=0&amp;byline=0&amp;api=1',
      type : 'iframe'
    }
  ], {
    fullScreen : false,
    closeBtn   : false
  });
  
```
e.g. $.fancybox.open( [ array of elements ], { group options } ); where each element has to have src and optional options - { src : { 'link', opts : {} }

Secondly, yeah, I forgot to mention that close button will be visible for not only pdf files, but also other "media" types - video (youtube/vimeo), maps. It was meant to prevent situation when user is not able to close the modal content. 
You can overcome this by using direct links, like in the example above.

I have also updated the demo - http://codepen.io/fancyapps/pen/pRavyP?editors=0010

**Comment by GeorgeRT** [comment]
Thanks, will work on that.
