### ISSUE TITLE
Using fancybox 3 with html 5 video 

### ISSUE THREAD

**Issue by bmiddmjs** [fancyapps/fancyBox#1208]
This may be a similar question to issue 1203 ...
Upfront apologies- I'm not a great programmer.
I can't get an HTML5 video to open (multiple source files). I get the fancybox overlay with a thin white strip in the center. Does fancybox have this functionality or does it just work for http links such as vimeo and youtube. 

Basically:
< video data-fancybox controls width="200" height="auto">
< source src="http://example.com/video.mp4" type="video/mp4">
< source src="http://example.com/video.webm" type="video/webm">
< /video>

**Comment by mjcampagna** [comment]
I may be mistaken, but I think Fancybox lacks that functionality. I suggest using an iframe or inline modal, with the usual video elemtn(s) therein.

**Comment by bmiddmjs** [comment]
I have been using the following code for html5 video with fancybox 1 which works but is non-responsive. I have not been able to adapt it to fancybox 3 (frankly because I am not skilled enough of a programmer):

$(document).ready(function(){ fancyPopup();});function fancyPopup() {var el = "";var posterPath = "";var replacement = "";
  var videoTag = "";var fancyBoxId = "";var posterPath = "";var videoTitle = "";$("video").each(function () {el = "";posterPath = "";replacement = "";
  videoTag = "";fancyBoxId = "";posterPath = "";videoTitle = "";el = $(this);fancyBoxId = this.id + "_fancyBox";videoTag = el.parent().html();posterPath = el.attr("poster");
  videoTitle = "Play Video " + this.id; replacement = "<a title='" + videoTitle + "' id='" + fancyBoxId + "' href='javascript:;'><img src='" + posterPath + "' class='img-link'/></a>"
  el.parent().replaceWith(replacement); $("[id=" + fancyBoxId + "]").fancybox({'content': videoTag,'title': videoTitle,'padding': 0,
  'showCloseButton': true,'enableEscapeButton': true,'titlePosition': 'none',}); });}

**Comment by bmiddmjs** [comment]
Oh and I forgot to say Thank you for your response mjcampagna.

**Comment by fancyapps** [comment]
Html5 video is not yet supported out of the box. The problem is - html5 video can contain a lot of attributes - multiple content sources, subtitles in multiple languages, posters, etc. So, the question is - how to pass all of that? And would it not be an overhead?

Anyway, you can display any HTML using fancybox. So, if you can build a video element, you should be able to display using `$.fancybox.open`:

`$.fancybox.open('<b>Some html code</b>');`

**Comment by bmiddmjs** [comment]
Thanks for the reply! Love the new version. Video works fine if I do a simple < a data-fancybox href="#video"> after putting the video in a hidden container. My concern is for SEO and that the video would not be indexed. I am trying a sample video this way and will see in a few days if Google is able to index it.  I will also try programming as your suggested above ($.fancybox.open('<b>Some html code</b>'); to see on indexing.

**Comment by fancyapps** [comment]
If your video will be inside hidden div, I think you should be fine.

**Comment by bmiddmjs** [comment]
Update: HTML5 videos rank fine on google using either method.  No SEO problems. Thanks for your help!
