### ISSUE TITLE
setting showOnStart inside the onInit function

### ISSUE THREAD

**Issue by aflipphi** [fancyapps/fancyBox#1211]
I'm using multiple galleries on the same page, however some galleries only have 1 image.
By settings the 

> thumbs : {
>     showOnStart : true
> }

will display the thumbs of galleries with multiple images, but this settings throws an jquery error on the 'single image' galleries.
By using the onInit function I can get the number of slides for the clicked instance but how can I set the showOnStart inside this function?

I have tried:
- jQuery.fancybox.thumbs.showOnStart = true; // No luck, gives notice 'Cannot read property 'show' of undefined'
- Adding the thumbs snippet to this function // No effect

**Comment by fancyapps** [comment]
"but this settings throws an jquery error on the 'single image' galleries." - what error? I do not see any issue.

**Comment by aflipphi** [comment]
Code snippet currently in use:
```
jQuery(document).ready( function() {
            jQuery('[data-fancybox]').fancybox({
                loop: false,
                thumbs : {
                    showOnStart : true
               }
           })
       })
```
When clicking on a gallery with a single image this gives 'Cannot read property 'show' of undefined'

**Comment by fancyapps** [comment]
Again, no issue for me - http://codepen.io/fancyapps/pen/OWvaQo?editors=1010

**Comment by fancyapps** [comment]
Example of displaying thumbs manually :

```
jQuery(document).ready( function() {
  jQuery('[data-fancybox]').fancybox({
    loop: false,
    beforeMove : function( instance ) {
      if ( instance.firstRun ) {
        instance.Thumbs.show();
      }
    }
  })
})
```
