### ISSUE TITLE
Change content in beforeLoad callback

### ISSUE THREAD

**Issue by Tsyklop** [fancyapps/fancyBox#1212]
How to change content in the beforeLoad callback?

my code:

```
$('a.register').fancybox({
        beforeLoad: function () {
            var content = $(this).content;
            for(var c in Sloyev.countries) {
                var option = $('<option value=""></option>');
                option.text(Sloyev.countries[c]).attr('value', c);
                content.find('select.countries').append(option);
            }
        }
    });
```

But i get error;

Thanks.

**Comment by fancyapps** [comment]
1) Why would you use "beforeLoad" callback, if it is called right before loading the content? That makes no sense.

2) This is how you typically would access content:

```
$('[data-fancybox]').fancybox({
  afterLoad : function( instance, slide ) {
    console.info( slide.$content );
  }
});
```

Note: Check out "slide" object to see other useful properties, for example, "$slide" is DOM element where content lives.

**Comment by Tsyklop** [comment]
@fancyapps Please, can you add examples in wiki. Thanks.
