### ISSUE TITLE
V3 - Uncaught TypeError: $slide.unbind is not a function in JS line 1273

### ISSUE THREAD

**Issue by contreforme** [fancyapps/fancyBox#1215]
In v3, straight out of the box i get this error : 

Uncaught TypeError: $slide.unbind is not a function (in JS line) 1273

if use jQuery from https://code.jquery.com/jquery-3.1.1.slim.min.js

**Comment by SaraThepot** [comment]
Hi contreforme.
.unbind() is deprecated from jQuery 3.0, I replace it with .off() and all seems work.

The line 1273 become: `.off( 'refresh' )`
