### ISSUE TITLE
Cant open modal window $.fancybox.open()

### ISSUE THREAD

**Issue by Tsyklop** [fancyapps/fancyBox#1216]
I try open modal window:
```

        $.fancybox.open($('div#users_form'), {
            afterLoad: function(instance, slide) {
                do work...
            }
        }, 2);
```

But I see the download. And yet.
I tried to take a purely html of the block - has turned out, but I would like to open the entire form.

what wrong?

**Comment by fancyapps** [comment]
If you want to display inline content manually, then it would be like this:

```
  $.fancybox.open({
    src  : '#users_form',
    type : 'inline',
    opts : {
      onComplete : function() {
        console.info('done!');
      }
    }
  });
```


See demo - http://codepen.io/fancyapps/pen/JEVLgN?editors=1010
