### ISSUE TITLE
Button in Caption Cannot Be Clicked

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1217]
So I'm keen to put a button into the caption -- specifically, attach the button to div.fancybox-caption-wrap -- but the inserted button is not clickable. Instead, clicks are occurring on the slide or fancybox-bg.

How can I make this button interactive?

**Comment by mjcampagna** [comment]
I've managed to work around this.

**Comment by fancyapps** [comment]
Works for me. Maybe you attached click handler before caption is created?
