### ISSUE TITLE
Problem with youtube videos on mobile browsers (android)

### ISSUE THREAD

**Issue by lomunet** [fancyapps/fancyBox#1218]
In first time, sorry for may poor english... 

I'm trying to use fancybox to show a youtube video in the pop-up, but when popup is open and I touch the youtube's "play" button, the  pop-up close down unexpectly ... after a lot of investigations, I Have seen the next problem:

jQuery generate this code:
`<div class="fancybox-overlay fancybox-overlay-fixed" style="width: auto; height: auto; display: block;"></div>`

using chrome developers tools, I have seen that without 'display:block' value all goes fine...

Can you help me?

**Comment by fancyapps** [comment]
Upgrade to v3.
