### ISSUE TITLE
I can't switch from image to image

### ISSUE THREAD

**Issue by carolineclara** [fancyapps/fancyBox#1220]
Hi !

I'm using this plugin, but when I open an image I don't have arrow buttons, so i can't switch my images. I have to close it, to open a new one.
All my images have the same rel name, to make a group, but it doesn't work.

there is a page for example : http://www.agence-eliot.com/achat-vente/maison-de-charme-proche-centre/

Thanks for your help !

**Comment by mjcampagna** [comment]
I think the problem is that you're using DIV elements instead of A. Change this:

```html
<div class="mini-thumb fancybox" rel="gallery" ...
```

to:

```html
<a class="mini-thumb fancybox" rel="gallery" ...
```

**Comment by fancyapps** [comment]
Looks like it is now working fine for you.
