### ISSUE TITLE
fancyBox 3 - SlideShow does not loop

### ISSUE THREAD

**Issue by dsheyp** [fancyapps/fancyBox#1222]
i'm trying with fancyBox 3 and found some issues. when i do the following

```
var $finstance = $.fancybox.open($('.fancybox'),{
   margin: [0,0],
   speed : 330,
   loop : true,
   .......
});
$finstance.SlideShow.start();
```

the slideshow will play each image one time and then stop. i think `loop: true` should be infinitely looping the slideshow.
also the duration for each image is still hard coded in the SlideShow class as  `speed  : 3000` . it would be nice if there was some option for this value.

best
dsheyp

**Comment by mjcampagna** [comment]
So what I'm seeing is that speed and loop work correctly when manually browsing the slideshow, but that they have no impact on the auto-play.

@fancyapps Perhaps I could propose being able to set slideshow options in such a manner as this?

```javascript
$instance.SlideShow.start({
	loop  : true,
	speed : 100
});
```

**Comment by fancyapps** [comment]
The latest commit contains a fix for "looping". Also, it is now possible to pass custom SlideShow speed:

```
slideShow : {
	speed : 500
}
```

**Comment by tranhuuphu** [comment]
add js

$('[data-fancybox="gallery"]').fancybox({
		loop  : true
	});
