### ISSUE TITLE
I can not highlight text

### ISSUE THREAD

**Issue by Geptor** [fancyapps/fancyBox#1227]
Hello.
I open the text block, but the text in it can not be select.

(Google Translate)

**Comment by fancyapps** [comment]
Hi,

This is caused by "touch" events, but you can simply disable them.
You can either set options using data attribute (update to the latest version for this to work):

```
<a data-fancybox data-src="#myElement" href="javascript:;" data-options='{"touch" : false}'>
	Click me
</a>
```

or when initializing fancyBox:

```
$('selector').fancybox({
	touch: false
});
```
