### ISSUE TITLE
Add a carousel/slider function to FancyBox

### ISSUE THREAD

**Issue by omarjuvera** [fancyapps/fancybox#1228]
This is not an issue but a request/suggestion:

Please add a carousel/slider function to FancyBox!

FancyBox is great! but without being able to have a slider function, it means to either load another plugin for a slider and in turn, slower and heavier loads. OR forget about FancyBox all together and use the slider plugin with CSS to compensate for the lack of FancyBox. Usually, my choice falls in the latter.

**Comment by fancyapps** [comment]
By "add a carousel/slider function" you mean - you want to use fancyBox as a simple image slider on the page and clicking on image would display it larger?

I actually was considering this feature while creating v3, but decided to leave this for v4.

**Comment by Danniemite** [comment]
This is a +1 for this too. This feature would make this code perfect.

**Comment by fancyapps** [comment]
I`m planning this for v4. 

Please let me know if you any additional ideas/suggestions or missing something in the current version.

**Comment by aroldjacx** [comment]
Yeah was just searching for this in hopes in not having to integrate another slider with fancy!
The capabilities are their with hacks but looking forward to v4. Right now i tried using it with slick 1.6.0 and i am getting quick-view-bullets duplication's because of slick (tabindex=0) automation. view dev project here. http://jax-media.com/agency/wca/new/index.html click on grace potter under Artist line up

**Comment by aroldjacx** [comment]
ok Solved the conflict. Just make sure your slick function includes = infinite: false

**Comment by michey55** [comment]
Just a question regarding the carousel/slider function: Is it possible to set up a simple kind of an autoplaying slideshow using options like modal=false, autoplaying=true? I mean something just displaying images and captions on the same place without having to use the zooming up modal overlay.

**Comment by durbanski** [comment]
Just came to this thread, and you could also take some inspiration from Swiper slider regarding to many useful methods i used in the past:
http://idangero.us/swiper/api/

**Comment by beyz** [comment]
Hi, I am having issue when I use with slick slider as below:
https://codepen.io/bder/pen/KKpOayV

Any advise much appreciated. Thank you in advance.

**Comment by fancyapps** [comment]
There are some examples in the docs - https://fancyapps.com/fancybox/3/docs/#faq-6

FYI - this issue will be gone once v4 will be released, you can preview it here - https://fancyapps.com/next/

**Comment by beyz** [comment]
New version looks great, it has everything in one box. I am wondering how the thumbs advance as you click them, if it was something like _fotorama_ it would have been so much convenient. 

I have tried current version with the latest slick but it didn't work, probably some changes on slick files.

**Comment by fancyapps** [comment]
@beyz That will be customizable. Thumbs is just another instance of Carousel, therefore the same options will be available.

**Comment by beyz** [comment]
@fancyapps Thank you, I am so looking forward to your new version. Any idea when you would release the new version?

**Comment by fancyapps** [comment]
I am afraid I can not give any estimate.

**Comment by jaywalker291** [comment]
Nice work @fancyapps  V4 looks good. As someone alluded to above, Swiper is probably the king of carousels  with it's excellent set of options and detailed documentation (swiperjs.com/api/). It plays well with fancybox3, but I would prefer to have one library for both lightbox and carousel. 

I hope v4 can have similar options for lazy loading as Swiper does, specifically control over when the next slide is  loaded (on transition, or ahead of time). Also Swiper has useful events such as "slideChangeTransitionEnd" for triggering custom functions per slide. I use this to display optional overlay content per slide, depending on if such content was added to the slide via our CMS. 

I"ll be purchasing v4 commercial license as soon as you release it and after testing that it fits our purpose, thanks!

**Comment by beyz** [comment]
It looks none of the features on V4 seems to be working on IE 11.
