### ISSUE TITLE
$.fancybox.open('#container') Excludes Target

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1229]
This doesn't work: 

```javascript
$.fancybox.open('#container');
```

This works, but only gives me the inner contents:

```javascript
$.fancybox.open('#container').html();
```

What's the best way to open #container itself?

This seems to be behaviorally different from the result you get when using "data-fancybox data-src", as doing that seems to retain the targeted container in the popup.

**Comment by fancyapps** [comment]
I have updated docs about this - http://fancybox.docs/3.0/#api

Basically, follow the general syntax:

```
$.fancybox.open({
	src  : '#hidden-content',
	type : 'inline',
	opts : {
		onComplete : function() {
			console.info('done!');
		}
	}
});
```
