### ISSUE TITLE
Iphone, Ipad or touch swipe possible?

### ISSUE THREAD

**Issue by o-l-e** [fancyapps/fancyBox#123]
Would it be tricky to have swipe functions on iPhone, iPad or other touch devices?
I don't know if this is something that can be added on the side of Fancybox (triggering prev/next)?
Any tips on this would be appreciated.

Thanks

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by klihelp** [comment]
Lightgallery does swping really well on desktop too
https://github.com/sachinchoolur/lightgallery.js
