### ISSUE TITLE
Incapability work with jQuery 1.7.1

### ISSUE THREAD

**Issue by MaXL-ru** [fancyapps/fancyBox#1234]
Packaged version for fancyBox v2.1.6  does work with jQuery 1.7.1 (jquery.fancybox.pack.js).

Code:

```js
f("<div/>").text(c.data("fancybox-title")||c.attr("title"))
```

return undefined, if title and data-fancybox-title attributes not exists.

Not optimize version of this file work correctly, becaouse it have next code:

```js
title : $('<div/>').text( element.data('fancybox-title') || element.attr('title') || '' )
```

**Comment by fancyapps** [comment]
If I remember correctly, minimum version of jQuery was something like 1.8.x

**Comment by MaXL-ru** [comment]
See https://github.com/fancyapps/fancyBox/blob/master/fancybox.jquery.json
```"jquery": ">=1.7"```
