### ISSUE TITLE
v3 Feature: close fancybox on browser back

### ISSUE THREAD

**Issue by stephangrass** [fancyapps/fancyBox#1236]
Hi,
I think it would be a nice feature, if an opend fancybox-layer will be closed when the user clicked the browser back-button.

Or?

**Comment by fancyapps** [comment]
I think someone already asked for this.  And the answer is the same - yes, it would be nice and I can image situations where this could be very useful, but just think about it - you want to control the behavior of the software! Do you really think that browsers would just [easily allow this](https://www.irt.org/script/311.htm)? Think about all the possible issues this could bring.
