### ISSUE TITLE
fancy box and iframe don't work on ios iphone

### ISSUE THREAD

**Issue by joesleiman** [fancyapps/fancyBox#1237]
it's work fine on all browser and android also , just on iphone when i say click on href link the fancy box loads and still loading all the time , it didn't disappear , and the content of the iframe didn't appear although i add preload : false

**Comment by fancyapps** [comment]
Demo? Version?

**Comment by joesleiman** [comment]
fancybox version : .2.1.5 
jquery : 1.12.4
`<div` class="hm-meter-wrapper"><a class="fancybox fancybox.iframe" ng-href="{{$ctrl.url}}"      id="check"><img ng-src="{{$ctrl.imgSrc}}" `width="{{$ctrl.imgWidth}}"/></a></div>`
`` jQuery(document)
                .ready(
                    function () {
                        var selector = '#' + $ctrl.id + ' .hm-meter-wrapper .fancybox';
                        jQuery(selector).fancybox(
                            {
                                minHeight: '480px',
                                autoHeight: true,
                                autoResize: true,
                                autoCenter: true
                            }
                        );
                    });``

**Comment by joesleiman** [comment]
I find this solution : 

As a side note, the whitelist system is required as of Cordova Tools 5.0.0 (April 21, 2015). For Phonegap Build, that means since cli-5.1.1 (16 Jun 2015)

Add this to your config.xml

```
<plugin name="cordova-plugin-whitelist"      source="npm" spec="1.1.0" />
<allow-navigation href="*" />
<allow-intent href="*" />
<access origin="*" /> <!-- Required for iOS9 -->
```
NOTE YOUR APP IS NOW INSECURE. IT IS UP TO YOU TO SECURE YOUR APP.
Add the following to your index.html

```
<meta http-equiv="Content-Security-Policy" 
         content="default-src *; 
                  style-src * 'self' 'unsafe-inline' 'unsafe-eval'; 
                  script-src * 'self' 'unsafe-inline' 'unsafe-eval';">
```
