### ISSUE TITLE
iFrame height and width not set correctly in FancyBox 3

### ISSUE THREAD

**Issue by leecollings** [fancyapps/fancyBox#1239]
When updating from 2 to 3 and using data attributes, the height and width of iFrame content defaults to maximum, causing false aspect ratio on mobile, and ugly padding when using iframe content smaller than the window size.

Example:
```
<a rel="nofollow" data-fancybox data-src="https://content.understand.com/bellavou.player?PresentationID='.get_video_ID()['presentation'].'&amp;CatalogID='.get_video_ID()['catalog'].'" href="javascript:;">
    <span class="fa fa-li fa-play-circle"></span>'.get_the_title($post->ID).
'</a>
```

This appears as 
![image](https://cloud.githubusercontent.com/assets/6681733/23220671/9ed9f234-f91a-11e6-984d-e9c0e080a588.png)

The mobile example of a YouTube video:
```
<a class="img splash video" rel="nofollow" data-fancybox href="//www.youtube.com/embed/'.get_post_meta($patientStory->ID, 'youtube', true).'">
    <img class="img-responsive img-rounded center-block" src="//img.youtube.com/vi/'.get_post_meta($patientStory->ID, 'youtube', true).'/mqdefault.jpg" alt="'.get_the_title($patientStory->ID).' intro video" />
</a>
```

Will appear as: 
![image](https://cloud.githubusercontent.com/assets/6681733/23220732/ccbef302-f91a-11e6-9e49-8c0bc7bd9eb5.png)

**Comment by fancyapps** [comment]
In your first example you are using default settings and default iframe dimensions are set by css:
```
width: 80%;
height: calc(100% - 88px);
```
You can change them by overriding CSS or using iframe option.
 
About second example, if you want to keep aspect ratio of youtube video, then check this demo - http://codepen.io/fancyapps/pen/dNzaQq

I guess someday this will be built-in.

**Comment by leecollings** [comment]
What if I want the width and height of the iFrame content box to automatically match the content within? As in, I don't want to set a specific height or width, or a height or width relative to the parent (the browser window)?

**Comment by fancyapps** [comment]
It will be automatically, if iframe content is accessible. E.g., browser allows to access it (iframe has to be same domain, port, etc, see https://en.wikipedia.org/wiki/Same-origin_policy).
btw, working demo on the homepage.

**Comment by leecollings** [comment]
No, it's an external domain content (
http://development.bellavou.co.uk/videos/ - The animated video library)


Lee

**Comment by fancyapps** [comment]
In that case, you wont be able to access iframes. But, seems that they share same css rules, so you could just use them. (e.g., simply set `max-width: 960px;`).

Another notes:
1) I think you should fix js errors you have; "Uncaught RangeError: Maximum call stack size exceeded." - does not sound good;
2) Your footer/header is jumpting when opening/closing fancybox, but there is an easy fix, see http://fancybox.docs/3.0/#faq

**Comment by leecollings** [comment]
I think I'm going to forget version 3, as it seems to have some bugs in it, and missing features. Version 2 was able to do this fine, which is a shame.

Also, I've tried to fix the aspect ratio using that link you sent, but it has no effect when viewing YouTube videos on a mobile. They still appear as large portrait lightboxes taking up most of the screen.

**Comment by fancyapps** [comment]
I am quite surprised to hear that. Iframes in v2 works generally the same and I do not see any bugs in v3 or something important missing.
