### ISSUE TITLE
Fancybox external link isn't working

### ISSUE THREAD

**Issue by nwtech** [fancyapps/fancyBox#1241]
I had another [thread open regarding fancybox](http://stackoverflow.com/questions/42118865/using-cookies-to-not-show-a-popup-based-on-particular-actions) and getting it to work with cookies. Cookies now seem to be working, however, I've lost the functionality to get external links to work.

Here's the HTML:

    <div style="display:none">
        <a class="fancybox" href="#donation-info" alt=""/></a>
        <div id="donation-info">
            <?php if (get_field('donation_box_text', 'option')){
                echo '<h2>To all our readers:</h2>';
                echo '<p>' . get_field('donation_box_text', 'option') . '</p>';
                echo '<div style="text-align:center"><a href="' . get_field('donation_link', 'option') . '" id="donate" class="donate-link" />Donate</a></div>';
            }; ?>
    
        </div>
    </div>

Here's the JS:

    $(function () {
      // Define cookie name
      var cookieName = 'hide_donate';
    
      // Configure fancyBox
      $('.fancybox').fancybox({
          autoDimensions: false,
          autoSize: false,
          height: 'auto',
          padding: 0,
          width: 650,
          beforeLoad: function() {
            // Returning false will stop fancybox from opening
            return ! $.cookie(cookieName);
          },
          afterClose: function() {
            // Set cookie to hide fancybox for 1 day
            $.cookie(cookieName, true, { expires: 1 });
          }
      });
    
      // Handle donate click event
      $('a#donate').on('click', function (event) {
          event.preventDefault(); 
    
          // Hide fancybox and set cookie to hide fancy box for 7 days
          $.fancybox.close();
          $.cookie(cookieName, true, { expires: 7 });
      });
    
      // Launch fancyBox on first element
      setTimeout(function () {
          $(".fancybox").trigger('click');
      }, 2000);
    });

I'm not sure what's wrong, but I've tried adding `type: 'inline',` to the argument list, also  `$("#donation-info").attr("href", "#donate");` to add the href elements back to the link, but nothing seems to be working. any suggestions?

**Comment by fancyapps** [comment]
Your code makes no sense, the logic should be like this:

First, check if cookie exists:
1) if exists - do nothing, just nothing!
2) else, set cookie, show fancybox.

Also, displaying fancybox by trigger the link is also wrong. You should simply open it manually, check documentation.

Anyway, the Github issues should be about real issues, not asking for help.
