### ISSUE TITLE
data-selector attribute not working on ajax responses

### ISSUE THREAD

**Issue by jerryjoplin** [fancyapps/fancyBox#1242]
The data-selector attribute is not used for selecting nodes in an ajax response if a selector is in the url.  It looks like the functionality is there by appending a selector to the data-src instead.  Looking for the best way to implement this since it appears to work contrary to the documentation (or maybe this is a feature for overriding the data-selector, I'm mainly just confused by this)

when supplied It appears to use this syntax: 
  data-src="my_page.com/path/to/ajax/ #two" 

Instead of this:
  data-src="my_page.com/path/to/ajax/" data-selector="#two" 

jquery.fancybox.js has this code which appears to parse the selector from the source string:
```
                // Check if url contains selector used to filter the content
                // Example: "ajax.html #something"
                if ( type === 'ajax' ) {
                    srcParts = src.split(/\s+/, 2);

                    if ( srcParts.length > 1 ) {
                        obj.src = srcParts.shift();

                        obj.opts.selector = srcParts.shift();
                    }
                }
```

**Comment by fancyapps** [comment]
Have you seen documentation? There is an ajax example demonstrating the data-selector usage - http://codepen.io/fancyapps/pen/MJwWKz?editors=1100

**Comment by jerryjoplin** [comment]
The example doesn't work if there's a selector in the URL.   I removed the selectors from the URL and it worked okay.  Thanks...

**Comment by fancyapps** [comment]
I have updated example to demonstrate both usages. 

I`m confused - what exactly was not work for you?

**Comment by jerryjoplin** [comment]
Have you seen my question?    This causes it to break: data-src="my_page.com/path/to/ajax/ #two"

**Comment by fancyapps** [comment]
Have you seen my exampe? This works for me - 

```
<a data-fancybox data-type="ajax" data-src="http://codepen.io/fancyapps/pen/wgavbY.html #two" href="javascript:;">
	Use selector from  "src" value
</a>
```

**Comment by jerryjoplin** [comment]
YES I saw the example!  Did you read my question at all?   If you specify BOTH the data-src overrides the data-selector.    End of story...

**Comment by fancyapps** [comment]
Oh, sorry, I did not realize that you have selector in both places. 

Aso, I think that parsing selector from src will be dropped in the future.

**Comment by jerryjoplin** [comment]
Got it, and sorry if the interaction between us was a bit rocky.  Fancybox is awesome and you're a great developer, thanks for making it available.   I found one other issue with the licensing but will open a new ticket.  Thanks again - Jerry

**Comment by fancyapps** [comment]
That ok, I should have red your question more carefully :)

About licensing - it basically stays the same and v3 is a free upgrade. I`m working right now on the homepage and there will be all the information.

**Comment by jerryjoplin** [comment]
Thanks again, that answers the other question on licensing.  I'll watch the homepage and thanks again for an awesome product - the best I've seen in this category of software.
