### ISSUE TITLE
Image carousel with top to down transition

### ISSUE THREAD

**Issue by prem911** [fancyapps/fancybox#1243]
This isnot an issue and need ways to implement this. I m creating a book preview which basically will have more than 1 image previews. I'm trying to override the slide transition from left-right to top-down. Peeked into the code to look for options but could not find it.
Any suggestions or snippets. I'm trying out FB3 now.

**Comment by fancyapps** [comment]
Sorry, horizontal direction is hard-coded and there is currently no option to change it.

I'm curious, why do you think that vertical navigation would suit better? In my opinion, something like http://builtbywill.com/booklet/#/ would work better for book preview.

**Comment by fancyapps** [comment]
I was thinking about this and decided that this feature will be implemented. But I can not tell you when and whether it will be included in the v3 or v4.

**Comment by prem911** [comment]
Never mind, I did a bit of jugglery with jquery and scroll event to create
a nice multipage vertical scrolling image gallery. This mimicks my pdf
nicely.

**Comment by fancyapps** [comment]
Using v3.1, you can create your own transition effects, see this demo - https://codepen.io/fancyapps/pen/VbRdbg
