### ISSUE TITLE
Left/Right padding - Fancybox 3

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancyBox#1244]
Hi,
how can we add padding left/right so that the image is not "touching" the viewport but has some space around?

Thanks.

**Comment by fancyapps** [comment]
Hi,

Maybe you are looking for "margin" option? Also, you can play with CSS to change position and dimensions of content area.

**Comment by jeenoshibu** [comment]
fancy box 2 had the option to set the CSS elements via js. Does fancy box 3 has it?

**Comment by fancyapps** [comment]
You can do anything within callbacks.

**Comment by jeenoshibu** [comment]
I am no talking about callbacks. During fancybox initialization using js , can we set css props. If so which all can we set.

**Comment by fancyapps** [comment]
Instead of doing `$().smth({ css : {})` , simply do `$().smth({ afterLoad: (instance, current) => current.$content.css() })`. This allows you to do to a lot of thing in one place + you can choose values based on screen width etc.
