### ISSUE TITLE
Callback not fires on $.fancybox.open()

### ISSUE THREAD

**Issue by kosha-industry** [fancyapps/fancyBox#1246]
$('.profile-report').click(function () {
      var profileId = $(this).data('profile-id');
      $.fancybox.open({
        src: '/tmpl/form/report-profile-form',
        type: 'ajax',
        onComplete: function () {
          // want set profile id in form's hidden input
          console.log(123); //not working (v3.0.22)
        }
      });
    });

**Comment by fancyapps** [comment]
Hi, Looks like you are trying to use syntax from v2, but the it has changed a bit. You see, in v2 group items consisted or mix of object properties (for example, "isLoaded") and object options (for example, callbacks) and it was hard to distinguish them. Therefore it was decided to store options under "opts" property and your example would look like this:


```
$('.profile-report').click(function () {
  var profileId = $(this).data('profile-id');
  $.fancybox.open({
    src: '/tmpl/form/report-profile-form',
    type: 'ajax',
    opts: {
      onComplete: function () {
        // want set profile id in form's hidden input
        console.log(123); //working v3
      }
    }
  });
});
```

**Comment by kosha-industry** [comment]
Thank you sir, all works 👍
