### ISSUE TITLE
Newest version has skewing image issues?

### ISSUE THREAD

**Issue by saltnpixels** [fancyapps/fancybox#1247]
I had to downgrade to about a few weeks ago version because the newest version is squishing my images!!

https://www.dropbox.com/s/xabuioig52inmua/Screenshot%202017-02-28%2013.16.04.png?dl=0

I was using this to get all my images on the page that had the same data-profile-images
```
//when this item is clicked get all other images with same data-profile-images and open gallery
$('.quick-bio').on('click', '.profile-image > a', function() {
  $profile_id = $(this).attr('data-profile-images');
  var links = $('[data-profile-images="' + $profile_id + '"]');
  $.fancybox.open( links, {}, links.index( this ) );
  return false;
});

```

**Comment by fancyapps** [comment]
1. Your image is not loading for me, you can post images here, on GitHub.
2. I have tested fancyBox on various devices and browsers and have never experienced any issue with images. I guess it has something to do with your page. So, could provide a link to your page? 
3. Are they displaying like images, and not inside iframe? If so, have you set content type to "image" for your links?

btw, with "newest version" you mean really the newest, right? (The last update was today 😄 )

**Comment by saltnpixels** [comment]
thanks for replying.
I am using newest version!
You can't view the pages unless signed in to view profiles on the site....

I can give you a password and username... but somehow privately...

**Comment by saltnpixels** [comment]
thanks for helping out. 
turns out im a moron.

I updated the js but not the css part. so it worked halfway...
