### ISSUE TITLE
Scale to actual / scale to fit triggered by right click

### ISSUE THREAD

**Issue by zmwangx** [fancyapps/fancybox#1248]
First of all I like the click to scale feature in v3. That said, right clicking also triggers the scale to actual / scale to fit animation^ (see caveat below), which is rather annoying, and I suspect it's not the intended behavior.

I briefly looked at the code and `Guestures.prototype.ontap` appears to be responsible, but it is not immediately clear to me how right click events are associated to `ontap` here.

^This is the case in Chrome and Firefox; in Safari, the behavior is even more counterintuitive: first, the context menu is open (and nothing happens to the image); then, when the cursor is released from the context menu upon completion, it becomes the grabber and initiates dragging.

---

OS and browser versions, in case they matter (most likely not):

- macOS 10.12.3;
- Chrome 56.0.2924.87;
- FirefoxDeveloperEdition 53.0a2;
- Safari 10.0.3.

**Comment by fancyapps** [comment]
Hi, thanks. I`ll add a check for witch button is pressed.

**Comment by fancyapps** [comment]
Please, update to the latest commit.

**Comment by zmwangx** [comment]
5cd17e3 fixed it, thanks!
