### ISSUE TITLE
Click event on mobile devices doesn't work

### ISSUE THREAD

**Issue by Anoxy** [fancyapps/fancybox#1250]
Hello, i've been trying out Fancybox 3 and run into a some kind of problem.

When I open popup via fancybox, spans, divs and other elements other than buttons / inputs have disabled click events but only on mobile devices - what could possibly go wrong ?

**Comment by fancyapps** [comment]
Hi, The script adds touch events for swiping. If you want, you can disable them by setting touch: false.

**Comment by Anoxy** [comment]
Thanks a lot, it seems that it solved issue
