### ISSUE TITLE
Zoom issue, possibly when data-width/height is not set

### ISSUE THREAD

**Issue by mortentoo** [fancyapps/fancybox#1251]
I'm experiencing some strange behaviour when zooming in/out. I have not set the image data-width or data-height attributes, since I couldn't see a straight-forward way of doing this in wordpress (though there may be a workaround).

When clicking zoom, it correctly zooms in the first time. However, on zoom out, the image is suddenly smaller and placed in the top-left corner of where it should be. Changing the browser window size forces it to update and rescale itself.

Also, when panning after having zoomed, it sometimes zooms in further, making the image more than 100%.

I should note that I'm using Firefox 51.0.1 and Mac OS 10.11.6

![zoom behaviour](https://cloud.githubusercontent.com/assets/11890765/23458420/85dcf8b4-fe7c-11e6-92cf-7785598dcf17.gif)

EDIT:
For fun I tried manually setting the data-width and data-height attributes, and it seems to solve it. Wouldn't it be possible to automatically retrieve these from the src image?

**Comment by fancyapps** [comment]
Hi. Could you show your page? I have not experienced such issue and I have no idea what could cause that.
These missing data attributes should not affect that. They are used to calculate zoom position before full image is loaded and before real image dimensions could be determined.

**Comment by fancyapps** [comment]
Also, make sure you have the latest js AND css files.

btw, when viewing demos on homepage or from docs, are you experiencing any issue?

**Comment by mortentoo** [comment]
I'll probably put the website online within a few days, but until then: the html surround the image:

`<p><a class="fancybox" data-fancybox="gallery-1902" href="http://amorten.com/wp-content/uploads/2017/02/DSF3980.jpg"><img class="alignnone size-medium wp-image-1904" src="http://amorten.com/wp-content/uploads/2017/02/DSF3980-620x413.jpg" alt="" srcset="http://amorten.com/wp-content/uploads/2017/02/DSF3980-620x413.jpg 620w, http://amorten.com/wp-content/uploads/2017/02/DSF3980-310x207.jpg 310w, http://amorten.com/wp-content/uploads/2017/02/DSF3980-768x512.jpg 768w, http://amorten.com/wp-content/uploads/2017/02/DSF3980-2560x1707.jpg 2560w, http://amorten.com/wp-content/uploads/2017/02/DSF3980-1240x827.jpg 1240w, http://amorten.com/wp-content/uploads/2017/02/DSF3980-3840x2560.jpg 3840w" sizes="(max-width: 320px) 310px, 620px" height="413" width="620"></a> <a class="fancybox" data-fancybox="gallery-1902" href="http://amorten.com/wp-content/uploads/2017/02/DSF3993.jpg"><img class="alignnone size-medium wp-image-1905" src="http://amorten.com/wp-content/uploads/2017/02/DSF3993-620x413.jpg" alt="" srcset="http://amorten.com/wp-content/uploads/2017/02/DSF3993-620x413.jpg 620w, http://amorten.com/wp-content/uploads/2017/02/DSF3993-310x207.jpg 310w, http://amorten.com/wp-content/uploads/2017/02/DSF3993-768x512.jpg 768w, http://amorten.com/wp-content/uploads/2017/02/DSF3993-2560x1707.jpg 2560w, http://amorten.com/wp-content/uploads/2017/02/DSF3993-1240x827.jpg 1240w, http://amorten.com/wp-content/uploads/2017/02/DSF3993-3840x2560.jpg 3840w" sizes="(max-width: 320px) 310px, 620px" height="413" width="620"></a> <a class="fancybox" data-fancybox="gallery-1902" href="http://amorten.com/wp-content/uploads/2017/02/DSF4012.jpg"><img class="alignnone size-medium wp-image-1906" src="http://amorten.com/wp-content/uploads/2017/02/DSF4012-620x413.jpg" alt="" srcset="http://amorten.com/wp-content/uploads/2017/02/DSF4012-620x413.jpg 620w, http://amorten.com/wp-content/uploads/2017/02/DSF4012-310x207.jpg 310w, http://amorten.com/wp-content/uploads/2017/02/DSF4012-768x512.jpg 768w, http://amorten.com/wp-content/uploads/2017/02/DSF4012-2560x1707.jpg 2560w, http://amorten.com/wp-content/uploads/2017/02/DSF4012-1240x827.jpg 1240w, http://amorten.com/wp-content/uploads/2017/02/DSF4012-3840x2560.jpg 3840w" sizes="(max-width: 320px) 310px, 620px" height="413" width="620"></a> <a class="fancybox" data-fancybox="gallery-1902" href="http://amorten.com/wp-content/uploads/2017/02/DSF4030.jpg"><img class="alignnone size-medium wp-image-1907" src="http://amorten.com/wp-content/uploads/2017/02/DSF4030-413x620.jpg" alt="" srcset="http://amorten.com/wp-content/uploads/2017/02/DSF4030-413x620.jpg 413w, http://amorten.com/wp-content/uploads/2017/02/DSF4030-310x465.jpg 310w, http://amorten.com/wp-content/uploads/2017/02/DSF4030-768x1152.jpg 768w, http://amorten.com/wp-content/uploads/2017/02/DSF4030-1707x2560.jpg 1707w, http://amorten.com/wp-content/uploads/2017/02/DSF4030-827x1240.jpg 827w, http://amorten.com/wp-content/uploads/2017/02/DSF4030-620x930.jpg 620w, http://amorten.com/wp-content/uploads/2017/02/DSF4030.jpg 3264w" sizes="(max-width: 320px) 310px, 620px" height="620" width="413"></a></p>`

**Comment by fancyapps** [comment]
You are right, thanks! Sorry about that, I missed that. 
I`ll fix this.

**Comment by mortentoo** [comment]
No problem. Thank you for fancybox! Overall I find it to be quite an improvement over fancybox 2. I'm perhaps only missing a few options like different transitions and potentially disabling the zoom behaviour.

**Comment by fancyapps** [comment]
OK, last commit contains a quick fix for issues if "speed" is set to 0.

Anyway, I plan to start working on v3.1 soon and there will be some api changes, for example, there will be different options to customize animations and an option for toggling opening/closing animation.

Could you describe what do you mean by "different transitions"? What would you want to be able to do?
Well, it is possible to create custom animations using CSS, but it is currently not perfect, an example - http://codepen.io/fancyapps/pen/EWPZMN?editors=1100 
If you are looking for complex transitions like exploding images and stuff, then I do not think they will be included.

Any recommendations or missing something, feel free to comment.

**Comment by mortentoo** [comment]
No I wasn't thinking about any fancy stuff like that. I didn't realize it was done in CSS - which is cool. I'll look into that. But to answer your question, I was simply thinking about different sliding directions, fading and such. The Ken Burns effect suggested would also be nice.

Anyways, thanks! I'll keep an eye out for v3.1
