### ISSUE TITLE
baseClass

### ISSUE THREAD

**Issue by di180690** [fancyapps/fancybox#1252]
I'm trying to add baseClass option when call $.fancybox.open, but it doesn't appears.

**Comment by fancyapps** [comment]
Works fine for me, maybe you are using wrong syntax, for v3 it is like this:

```JS
$.fancybox.open( '<div>Hi!</div>', {
    baseClass : 'TEST'
});
```

**Comment by di180690** [comment]
what am I doing wrong?

```
$.fancybox.open({
    type: 'inline',
    src: '.modal',
    opts: {
        baseClass: 'govno'
    }
});
```

**Comment by fancyapps** [comment]
Sorry, it should be documented. "baseClass" and "parentEl" options have to be passed as group options, because these are not per-item, but per instance. Therefore, it should be like this:

```JS
$.fancybox.open({
    type : 'inline',
    src  : '#hidden-content',
    opts : {}
}, {
    baseClass: 'TEST'
});
```
