### ISSUE TITLE
Form does not have focus when opened

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1253]
I've got this opening a popup with a search form. When the popup opens, though, the input element does not have focus. 

```html
		<li id="search_tool" data-fancybox="search" data-src="#search"><span>Search</span>
			<div id="search">
			<form action="..." method="GET" class="form">
				<input type="text" id="q" name="q" value="" placeholder="Enter search, hit Return..." />
				<button type="submit">Search</button>
			</form>    
			</div>
```

```javascript
	$('[data-fancybox=search]').fancybox({
		baseClass : 'fb-search',
		focus         : true
	});
```

**Comment by fancyapps** [comment]
Sorry, there was a typo that broke focusing, the last commit should fix that.

btw, your html code looks weird. Do you really put all the stuff inside <li> tag, including that form?

**Comment by mjcampagna** [comment]
Thanks for the quick fix!

**Comment by fancyapps** [comment]
@mjcampagna This year, I`m working full time on this project :)
