### ISSUE TITLE
Inline content overflow issue

### ISSUE THREAD

**Issue by hatemdeeb** [fancyapps/fancybox#1254]
FancyBox - Inline content
http://codepen.io/fancyapps/pen/MJYOOd?editors=1000
Can't scroll up and down.

**Comment by fancyapps** [comment]
What do you mean - "Can't scroll up and down"? That demo works fine, I even do not see any issue with larger content -  http://codepen.io/fancyapps/pen/peyYLQ?editors=1000

Please, be more specific!

**Comment by fancyapps** [comment]
Maybe you are using touch device? If you need, you can disable "touch" events by setting touch:false, example:

````JS
<a data-fancybox data-src="#lipsum" href="javascript:;" class="btn" data-options='{"touch" : false}'>Open demo</a>
````

This will be included into v3.1.

**Comment by hatemdeeb** [comment]
Try scrolling using the mouse button(without mouse wheel).

**Comment by fancyapps** [comment]
So, the issue you are trying to describe is - "clicking on the scrollbar closes modal", am I right?

**Comment by hatemdeeb** [comment]
Yes, you are right!
Thank you!
