### ISSUE TITLE
closeBtn and showCloseButton not working correctly

### ISSUE THREAD

**Issue by joeygallegos** [fancyapps/fancybox#1257]
I have the below setup for a configured modal:

```javascript
// get the html
var html = $('[data-for=social]').html();
// setup the modal
var opts = {
	modal: true,
	scrolling: 'no',
	openEffect: 'elastic',
	openSpeed: 150,
	closeBtn: false,
	showCloseButton: false,
	afterClose: function() {
		// cookie code
		console.log("getModal(): Close");
	}
}
$.fancybox.open(html, opts, null);
```

And when the modal opens, the showCloseButton and closeBtn options are not being accounted for. The HTML is still rendered and shown on the modal.

Is this user error or a potential bug?

**Comment by fancyapps** [comment]
By looking at your code I cannot tell if you are using v2 or v3, because you have mixed options from both.
For v3 - look for "closeBtn" and "smallBtn" options - http://fancyapps.com/fancybox/3/docs/#options

btw, `$.fancybox.open(html, opts, null);` - there is no need to pass `null`

**Comment by joeygallegos** [comment]
I am using V3, please see below:
```javascript
// setup the modal
var opts = {
	modal: true,
	scrolling: 'no',
	openEffect: 'elastic',
	openSpeed: 150,
	closeBtn: false,
	afterClose: function() {
		console.log("getModal(): Close");
	}
}
$.fancybox.open(html, opts);
```

This still produces the close button, thoughts?

**Comment by fancyapps** [comment]
If you want to hide both close buttons (one is appended to the html content and one is inside the toolbar), your code should be like this:

```JS
$.fancybox.open({
	type    : 'html',
	content : YOUR_HTML_CODE,
	opts    : {
		buttons  : false,
		smallBtn : false
	}
});
```

There are no scrolling, openEffect and openSpeed options.

**Comment by joeygallegos** [comment]
Thanks for your help, I finally got the desired outcome with your help and by reading part of the code here:
[https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L14-L154](https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L14-L154)
```javascript
var html = $('[data-for=social]').html();

var opts = {
	'buttons': false,
	'smallBtn': false,
	'afterClose': function() {
		console.log("getModal(): Close");
	}
}

$.fancybox.open(html, opts);
```
