### ISSUE TITLE
Migration to v3 from v2 with jwplayer in a FancyBox

### ISSUE THREAD

**Issue by bcordis** [fancyapps/fancybox#1261]
Is there a good solution for this

Example
http://stackoverflow.com/questions/17294625/jwplayer-with-fancy-box

Active code
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/blob/development/com_biblestudy/media/js/fancybox.js

Would love the help. Been trying a few things but did not work.

**Comment by fancyapps** [comment]
Hi, Your code probably would look like this:

```JS

$.fancybox.open({
	content : '<div id="video_container">Loading the player ... </div>',
	type    : 'html',
	opts    : {
		smallBtn   : false,
		onComplete : function( instance, current ) {
			console.info('Complete! The content is inside this element: ');
			console.info( current.$slide );
		}
	}
});
```

You can use "onComplete" callback to do your stuff, for example, initialize "jwplayer".
