### ISSUE TITLE
support email not working

### ISSUE THREAD

**Issue by luftfisch** [fancyapps/fancybox#1262]
I just bought the fancyBox Extended Commercial license and tried to ask a question to your support email expecting the "premium support" offered on your website:

    <support@fancyapps.com>: Recipient address rejected: User unknown in
    virtual mailbox table (in reply to RCPT TO command)

**Comment by fancyapps** [comment]
Hi,

Sorry about that, I contacted the sysadmin and it should be fixed soon. In meantime, you can contact me using info ata fancyapps or dm on twitter.

Thanks.

**Comment by fancyapps** [comment]
Just for information - the admin fixed this about the same time this report was created.
