### ISSUE TITLE
Display Exif Data

### ISSUE THREAD

**Issue by iMerica** [fancyapps/fancybox#1268]
Hi Jānis,

I just purchased a commercial license and I'm about to begin making a custom layout that displays EXIF information (aperture, ISO, shutter speed etc) to the right of the image. Can you point me in the right direction for passing new data to the fancybox instance?

I was hoping I could pass each instance the data inline like:

```html
 <a href="image.jpg" data-fancybox data-exif="{exif_ison}"><img src="image.jpg"></a>
```

Any thoughts on the best way to proceed? Perhaps using one of the callback functions?

Thanks!

Michael

**Comment by fancyapps** [comment]
Hi,

There are several implementation possibilities. For example, you could create a hidden table next to the each link and display it inside the fancyBox. Or you could store exif data in json and then build table using JS.

Example of how to store and get data from links. HTML:

```HTML
<a data-exif='{"shutter":"1/60","aperture":"f2.8","iso":"200"}' href="big.jpg" data-fancybox="images">
      <img src="small.jpg" />
  </a>
```

Then you can create a standalone snippet (similar to how fancybox built-in modules work):
```JS
$(document).on('beforeMove.fb', function( e, instance, current ) {

  var exifData = current.opts.$orig ? current.opts.$orig.data( 'exif' ) : '';
  
  console.info( 'exifData: ' );
  console.info( exifData  );
  
});
```

http://codepen.io/fancyapps/pen/RppgYO?editors=1010

**Comment by iMerica** [comment]
Very cool. Thanks!
