### ISSUE TITLE
CSS Transition-in Not Happening

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1269]
I don't have an example online, unfortunately, but what's happening in development is that my modals are not transitioning in when opened; they just pop. 

On close, I am seeing transitions out. 

Opening images seems fine; I'm seeing this with other content types, though (i.e. inline). 

Any thoughts where I might look to solve this?

**Comment by fancyapps** [comment]
Hi, There is no default transition, but you can create your own using CSS:
http://codepen.io/fancyapps/pen/MJYOOd?editors=1100

**Comment by mjcampagna** [comment]
Even your "no transition" example in that pen transitions in with a nice fade. I'm missing that entirely, and not sure why. Maybe a CSS conflict someplace ... any thoughts where I might go looking for such a thing, or why that basic transition in might be failing?

**Comment by fancyapps** [comment]
Hmm... maybe you have set speed to 0?

**Comment by mjcampagna** [comment]
Nope. I just tried forcing the default speed to a very slow value. It's not
applying at all to opening my inline modals; only applies on close. It
applies to both opening and closing of images, though.

**Comment by fancyapps** [comment]
I tried to figure out the reason, but no luck. Could you show your page? (You can do that privately, too)

**Comment by mjcampagna** [comment]
Thanks for checking into it. There's nothing I can show at the moment, as things are not yet online. Hopefully I will have something available to show soon, and I will come back to this then.

**Comment by fancyapps** [comment]
The script simply sets "transition-duration" property for overlay element and the value is taken from "speed" option. Therefore background fade transition duration matches image zoom animation. 
But html elements simply appear, they have no fade-in transition by default. The fading background gives fake illusion that they are fading-in, too.

**Comment by mjcampagna** [comment]
Good explanation. It might be there's no problem here then. The inline popups in question are large, so it might be they're occupying so much screen real estate, the illusion created by the background transition is shattered. I'll keep an eye on things as I go. Thanks!

**Comment by fancyapps** [comment]
Then try adding fading transition by yourself, example:

```CSS
.your-element {
  opacity: 0;
  transition: opacity 0.3s;
}

.fancybox-slide--complete .your-element {
  opacity: 1;
}
```

**Comment by mjcampagna** [comment]
I did try that. It got a little strange. Fancybox would fade in it's background, and then the content, rather than a simultaneous transition. I will like just live with it as is.
