### ISSUE TITLE
Callback parameter uncertainty

### ISSUE THREAD

**Issue by iMerica** [fancyapps/fancybox#1273]
Hi, 

This is more of a documentation bug, but the callback functions don't list the parameters that they accept. It would be helpful if instead of showing this:

```
  // Callbacks 
  beforeLoad	 : $.noop,
  afterLoad    : $.noop,      
```
they were described like this:

```
  beforeLoad: (event, instance, current) => {},
  afterLoad: (event, instance, current) => {},
  onComplete: () => {}
```

This way it's easy to understand what data each callback deals with. In lieu of this missing information, can you let me know what each callback uses?

**Comment by iMerica** [comment]
A short sentence describing each callback and when it's invoked would be super helpful too.

**Comment by fancyapps** [comment]
Hi, I`ll add additional info. Thanks.

**Comment by fancyapps** [comment]
In case you missed, there already is a short description for each callback - http://fancyapps.com/fancybox/3/docs/#events

**Comment by iMerica** [comment]
Oh cool - thanks! I didn't catch that.
