### ISSUE TITLE
Fancybox link to Hotlink prevented items returns false

### ISSUE THREAD

**Issue by MHCreations** [fancyapps/fancybox#1274]
I have inherited a website with images on it that should only be accessed from within the website.

This currently uses Hotlink Protection via .htaccess and this works however, some image thumbnails have fancybox popup links so that clicking on the thumbnail causes the fancybox to show the full sized image.

Fancybox is throwing the response:

>     The requested content cannot be loaded.
>     Please try again later.

Which is because the hotlink protection is somehow obstructing the fancybox, even though this call is coming from within the domain to be allowed.

How can I work around this issue?

Cheers

**Comment by fancyapps** [comment]
Hi,

First, do these images really exist? Can you include them directly in your page (e.g., <img src="your_image.jpg" />) - will they appear? 

Have you checked for server response (using developer tools)?

Basically, if images exist and you can load them from your page, then fancybox should work fine.

**Comment by MHCreations** [comment]
The images exist and fancybox works fine until I swap the htaccess and apply the hotlink prevention method. Then the images fail to load in fancybox. 

htaccess:
```

RewriteEngine on
RewriteCond %{HTTP_REFERER} !^$
RewriteCond %{HTTP_REFERER} !^http(s)?://(www\.)?mydoomain.com [NC]
RewriteRule \.(jpg|jpeg|png|gif)$ - [NC,F,L] 
```

**Comment by fancyapps** [comment]
But can you include them in your page directly after creating these rules?

**Comment by MHCreations** [comment]
Yes.

**Comment by MHCreations** [comment]
I was posting really to enquire if there is any sort of possible setting in the options to set to get fancybox to change behaviour if told (via the options) that a hotlink prevention method is in place. But by the sounds if it the behaviour I'm noticing isn't expected.

**Comment by fancyapps** [comment]
But what could fancybox possibly do differently if such option would exists? It is just a JavaScript! It creates an image object using something like `var img = new Image()`, then sets src and callbacks. The rest is up to the browser.
