### ISSUE TITLE
90e0dcf broke tap to hide/show controls on mobile

### ISSUE THREAD

**Issue by zmwangx** [fancyapps/fancybox#1276]
90e0dcf introduced a bug on mobile (Safari on iOS 10) where after a single tap which hides the controls (`.fancybox-controls`), subsequent single taps fail to reveal it.

Note that the caption (`.fancybox-caption-wrap`), if there is one, isn't affected. It is hidden or shown on every single tap.

**Comment by fancyapps** [comment]
Thanks for reporting! I`m working on this.

**Comment by fancyapps** [comment]
The last commit should fix this. Sorry for trouble!
