### ISSUE TITLE
Turn off grab to close

### ISSUE THREAD

**Issue by Tusko** [fancyapps/fancybox#1277]
Hey!
Can I disable grab up/down to close fancybox window?

**Comment by fancyapps** [comment]
Hi,

To disable touch events, you can either set `touch:false` using data attribute:

```
<a data-fancybox data-src="#myElement" href="javascript:;" data-options='{"touch" : false}'>
	Click me
</a>
```

or when initializing fancyBox:

```
$('selector').fancybox({
	touch: false
});
```

If you want to disable only vertical movement,  set `touch: { vertical : false }`

**Comment by Tusko** [comment]
@fancyapps awesome!
Thank you so much!

**Comment by Tusko** [comment]
@fancyapps doesn't work if html uploaded via AJAX
http://azuz.dev0.site/lviv-interactive-map/

try to click on the marker

**Comment by fancyapps** [comment]
My first guess would be that you have mixed `'` and `"`. See the difference:
`data-options='{"touch" : false}'` - works
`data-options="{'touch' : false}"` - does not

Confusing, I know, but that is how it works: 
https://api.jquery.com/data/#data-html5
https://en.wikipedia.org/wiki/JSON#Data_types.2C_syntax_and_example

**Comment by Tusko** [comment]
@fancyapps awesome2
You're right!

**Comment by fancyapps** [comment]
Also, I noticed header jumping when opening/closing fancybox.
It is easy to fix, all you have to do:
1) add "compensate-for-scrollbar" CSS class for your <header> element;
2) and add "transition: transform 0.5s;" CSS rule to that element, too (this disables margin property animation, but allows animated transforming)


Btw, I like hover animation on buttons, looks nice.

**Comment by kamilwronka** [comment]
@fancyapps 

Hello! I'd like to ask you a question. I have a problem with touch events in your gallery. The thing is, when my image is zoomed in, swiping vertically is closing the gallery and user can't see full image because of it. Is there any option to disable only closing the gallery when zoomed in?

**Comment by Tusko** [comment]
@kamilwronka 
try this:

```
$('[data-fancybox="gallery"]').fancybox({
    touch: false
});
```
