### ISSUE TITLE
Another hash module issue

### ISSUE THREAD

**Issue by priceinjector** [fancyapps/fancybox#1278]
If the page url has hash then fancybox hash module treats it wrong by thinking that the hash is the gallery hash. From there an exception is thrown...

The issue starts here:
the url is : http://localhost:8080/testApp/#/testHash

`parseUrl()` returns this object:
`url = Object {hash: "/testHash", index: 1, gallery: "/testHash"}`
also if the hash has "-" in it then it is wrong to split by "-" to find the gallery index
for example: http://localhost:8080/testApp/#/search-result/aaa
the url object in this case is totally wrong:
`url = Object {hash: "/search-result/aaa", index: 1, gallery: "/search"}`

then  in `triggerFromUrl( url )` the exception is thrown by:
`$( "#" + url.gallery + "" ).trigger( 'click' );`
Uncaught Error: Syntax error, unrecognized expression: #/testHash

**Comment by fancyapps** [comment]
Thanks for your patience! I added special character escaping to fix your first issue and some tweaks to fix other one.

I really did not want to create ugly hashes like `#gid=gallery&pid=1`. 
This looks definitely better - `#gallery-1`.

**Comment by priceinjector** [comment]
Thanks for a quick fix! You do awesome support :)
I start thinking that it is not so ugly...and if it reduces the future bugs maybe it is a better approach :)

**Comment by priceinjector** [comment]
Tested it...Now it throw exception at:

$el = $( "[data-fancybox='" + $.escapeSelector( url.gallery ) + "']" ).eq( url.index - 1 );

Uncaught TypeError: $.escapeSelector is not a function
    at triggerFromUrl

**Comment by fancyapps** [comment]
Oh, I forgot it is since jQuery version 3. What a bummer.  I`m surprised it was not created earlier.

**Comment by fancyapps** [comment]
@priceinjector Last commit contains a simple polyfill for "$.escapeSelector" method.

**Comment by priceinjector** [comment]
Works now, Thanks!!
