### ISSUE TITLE
Fancybox 3 Fullscreen by default

### ISSUE THREAD

**Issue by smaddy** [fancyapps/fancybox#1280]
I would like to open fancybox in fullscreen mode by default

**Comment by fancyapps** [comment]
Hi, With the latest update, it is now possible to start in fullscreen.

You can either set all instances to open by default:

``` JS
$.fancybox.defaults.fullScreen = { requestOnStart : true };
```

or for selected group:


``` JS
$('[data-fancybox="images"]').fancybox({
	fullScreen : {
		requestOnStart : true
	}
});
```

**Comment by dmtr81** [comment]
Hi fancyapps,

tried using requestOnStart to start fullscreen, but it does not work. Also searched for "requestOnStart" in the project source codes, and could not find it. Is this feature really implemented?
There is also nothing about it in the documentation.

**Comment by dmtr81** [comment]
Sorry, found. It sould be
```
fullScreen : {
    autoStart: true
}
```

**Comment by fancyapps** [comment]
This has been changed in v3.1, module options `requestOnStart` / `showOnStart` are renamed to simple `autoStart`

**Comment by dmtr81** [comment]
Thanks!
Is there a solution to close fullscreen fancybox clicking back button on mobile?
Right now I start fullscreen fancybox with "autoStart: true" option on mobile. And I want to close fancybox when user clicks "back" button on mobile. But instead, it just switches from fullscreen to normal mode.

**Comment by smaddy** [comment]
would like to see the feature as described by dmtr81 too - one click close for fullscreen - desktop and mobile :)

**Comment by fancyapps** [comment]
@smaddy sorry, no clue what do you mean by "one click close for fullscreen - desktop".

**Comment by dmtr81** [comment]
@fancyapps, may be it's just ESC click to close fancybox, instead of switch to normal mode.

**Comment by fancyapps** [comment]
@dmtr81 Esc key click is handled by browser when in full-screen mode and looks like it can not be cached using js.

**Comment by dmtr81** [comment]
@fancyapps, ok, but what about mobile "back" that was in my initial question. Is it possible to use it somehow to close fancybox instance?

**Comment by fancyapps** [comment]
I have not tested yet, but I guess it will be the same as on desktop.

**Comment by dmtr81** [comment]
@fancyapps, please, see pull request https://github.com/fancyapps/fancybox/pull/1502

**Comment by fancyapps** [comment]
@dmtr81 but it seems that after your changes, fancyBox will close every time full-screen mode changes, even after clicking fullScreen button in the toolbar. And that would be confusing.

**Comment by dmtr81** [comment]
@fancyapps, right. That's why I added it as an optional feature in the config file. If user likes this functionality, he may activate it.
Anyway, it is up to you to accept this pull request or not.

**Comment by Kernonen** [comment]
Hello, 
My document has two iframes and one of them holds Fancybox. Is there a way to display images fullscreen (i.e. not only in the iframe that contains Fancybox but over the 2 iframes) ?

**Comment by fancyapps** [comment]
@Kernonen Hi, It is not supported out of the box, but you can add your own click handler that starts new instance in parent iframe by using `parent.jQuery.fancybox.open()`
