### ISSUE TITLE
Remove hash URL for galleries

### ISSUE THREAD

**Issue by andsplat** [fancyapps/fancybox#1281]
Thanks for fancybox! I'm sorry if this is explained elsewhere. I'm having a hard time figuring out if one can not have the URL changed when viewing galleries. If images are in a gallery, the URL changes with /#galleryname-1. 

Is there a way to not have the URL modified? I would like to not add all of the image views to a user's browser history as to not have the images reappear if they use the browser back and forward buttons.

**Comment by fancyapps** [comment]
Hi, There are two options:

1. Build your own packed version of fancyBox. You can find all modules in src/js folder; you can use gulp to concatenate and minify only the ones you need.

2. Disable hash module by using this snipet (make sure you have the latest version):
`$.fancybox.defaults.hash = false;`

**Comment by andsplat** [comment]
Thanks! I'm new to editing JavaScript. Is there anywhere in particular that I need to add the code snipet that you provided in option 2 above?

**Comment by fancyapps** [comment]
Just somewhere after including fancyBox JS file. And make sure you are using the latest code (updated today).

**Comment by andsplat** [comment]
Awesome. Thank you!
