### ISSUE TITLE
instance.$lastFocus inconsistency

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1282]
I've found what I think is a bug. Or it's odd at the very least.

In Chrome, when I lean on instance.$lastFocus, I get the trigger element, as expected, as desired.

In Safari, however, this returns the body element, which is causing me some problems.

Running this in each browser should make the issue observable:

```javascript
$.fancybox.defaults.onComplete = function(instance){
  console.log(instance.$lastFocus)
};
```

**Comment by fancyapps** [comment]
The script uses `document.activeElement` to store current active element. And, according to https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement there are indeed some inconsistencies across browsers:

> Note: On Mac, elements that aren't text input elements tend not to get focus assigned to them.
