### ISSUE TITLE
Can't override default settings

### ISSUE THREAD

**Issue by grocc** [fancyapps/fancybox#1285]
Hello, hope someone can help me.
If i add this code
`$("[data-fancybox]").fancybox({
	infobar : false,
	buttons : false
});`
in my JS file i still see all the data, like the settings in not override.
Can someone help me?

**Comment by fancyapps** [comment]
Works fine for me. Could you show your page?

- make sure that your code goes after your have included fancyBox JS file;
- and make sure you are including fancyBox JS file only once (and jQuery, too).

**Comment by grocc** [comment]
Hi!
- It's included only one, and JQuery too
- My script is placed after and inside document ready
I'm afraid, but i'm working on a local site and i can't share the url.

I've also tried with
`data-options='{"caption" : "Just a try"}'`
but the caption was not overridded too

Finally
`data-caption="Just a try"`
work fine. The problem is that i have to override even the baseTpl, and so i need the js config too!

Any idea?

**Comment by fancyapps** [comment]
Hi, You are right about "caption" option, sorry about that. But other options should work fine, see any demo found on documentation, for example, this one: http://codepen.io/fancyapps/pen/ygeYGx?editors=1010
