### ISSUE TITLE
Fancybox 3 and the latest version of Nicescroll does not work scrolling in the modal window

### ISSUE THREAD

**Issue by makissm21** [fancyapps/fancybox#1289]
Scrolling does not work in the modal window, it works only if you twist the wheel into a non-block.

**Comment by fancyapps** [comment]
Hi, How are you using it? Any example, demo page?

**Comment by makissm21** [comment]
http://test1.cmski.ru/laboratornyj-kompleks/
http://shot.qip.ru/00QPGK-2mqQ2hHys/ click link http://shot.qip.ru/00QPGK-6mqQ2hHyt/

**Comment by fancyapps** [comment]
Works fine for me - http://codepen.io/fancyapps/pen/yMopKV?editors=1010

**Comment by makissm21** [comment]
Thank you very much!!! It really works !!!
