### ISSUE TITLE
Max width on iframe manual open

### ISSUE THREAD

**Issue by davorpeic** [fancyapps/fancybox#1290]
Hi @fancyapps 

first of all, great v3 update, I love it.

I'm trying to limit width on my manually opened iframe, before I was using width and maxWidth, but now it looks like that is not working, I also not seeing this options in Default object in the docs, are this configs available?

```
$.fancybox.open({
            src  : url,
            type : 'iframe'
        },{
            fullScreen : false,
            closeBtn   : true,
            width: '95%',
            maxWidth: '960px'                
        });
```

thanks

**Comment by fancyapps** [comment]
Hi, Thanks!

In v3, it is a bit different as it avoids complex calculations and delegates this to the browser :)

See documentation http://fancyapps.com/fancybox/3/docs/#iframe e.g.:

```JS
$("[data-fancybox]").fancybox({
	iframe : {
		css : {
			width : '600px'
		}
	}
});
```
