### ISSUE TITLE
FancyBox 2 open open two, or more modals bug

### ISSUE THREAD

**Issue by Tsyklop** [fancyapps/fancybox#1291]
I have two modal windows. The second one opens with the first.
Both modal window in favor of the screen - it means to be to scroll.
But on the second screen, scroll is not.

I noticed that with such a bug, another structure is html.

First window:
```
<div class="fancybox-overlay fancybox-overlay-fixed" style="width: auto; height: auto; display: block;"><div class="fancybox-wrap fancybox-desktop fancybox-type-inline fancybox-opened" tabindex="-1" style="width: 906px; height: auto; position: absolute; top: 20px; left: 306px; opacity: 1; overflow: visible;"><div class="fancybox-skin" style="padding: 0px; width: auto; height: auto;"><div class="fancybox-outer"><div class="fancybox-inner" style="overflow: auto; width: 906px; height: 224px;">

MODAL CONTENT

</div></div><a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a></div></div></div>
```

Second window:

`<div class="fancybox-overlay fancybox-overlay-fixed" style="display: block; width: auto; height: auto;"></div>`
and 
`<div class="fancybox-wrap fancybox-desktop fancybox-type-inline fancybox-opened" tabindex="-1" style="width: 906px; height: auto; position: absolute; top: 20px; left: 306px; opacity: 1; overflow: visible;">`
 Block outside the `div.fancybox-overlay`.

**Comment by fancyapps** [comment]
I'm sorry I could not understand what you wanted to say.

Could you, please, create an example demonstrating your issue (just for some example found on documentation) or create screencast.

**Comment by Tsyklop** [comment]
@fancyapps 
First modal:
![1](https://cloud.githubusercontent.com/assets/6783568/23944548/eb96f7ae-097b-11e7-8ef7-a4181dc768ed.png)

Open Second modal from first modal:
![2](https://cloud.githubusercontent.com/assets/6783568/23944563/fdb01560-097b-11e7-83c1-7d0d162672d8.png)

**Comment by fancyapps** [comment]
Sorry, v2 is not supported any more. Please, upgrade to v3.
