### ISSUE TITLE
Fancybox v3 - Filtering Issue

### ISSUE THREAD

**Issue by JochenKo** [fancyapps/fancybox#1294]
Hello everyone,

I have an issue with a filter function that works in fancybox-v2.
The problem starts when you do this:

1. Click on an image
2. Click on some filter "Animals"
3. Click on an image and it dosen't show up.

I just edited the "data-fancybox-group" to "data-fancybox" that my function fits to fancybox-v3.

test-site: [Fancybox-v3-Filter.zip](https://github.com/fancyapps/fancybox/files/845265/Fancybox-v3-Filter.zip)

**Comment by fancyapps** [comment]
I`m sorry, but please, isolate the problem and create a reduced test case and a live example. For example, use codepen to fork any demo found on documentation.
