### ISSUE TITLE
Fancybox v3 - Filtering Issue

### ISSUE THREAD

**Issue by JochenKo** [fancyapps/fancybox#1295]
Hello everyone again,

I have an issue with a filter function that works in fancybox-v2.
The problem starts when you do this:

1. Click on an image
2. Click on some filter e.g. "Animals"
3. Click on an image and the fancybox dosen't show up.

**The problem** is when you click an image if "View all" is active and than you chance it to a filter e.g. "Animals". If you click now an image the fancybox starts a new fancybox-container but doesn't show up.

I just edited the "data-fancybox-group" to "data-fancybox" that my function fits to fancybox-v3.

**codepen link:** http://codepen.io/JochenKo/pen/bqoqLX
**online-link:** http://jochenkonrad.de/Fancybox-v3-Filter/fancybox-v3-test_01.html

**Comment by fancyapps** [comment]
Hi, again :)

Why don`t you just use Isotype, see this demo - http://codepen.io/fancyapps/pen/EZKYPN
It is so much easier.

**Comment by JochenKo** [comment]
Hey, thanks for the answer.

I already used Isotope in some projects, but I like to keep it small as possible.
My filter-script is working well in fancybox-v2, but I like the new "touch" feature and the movement style from the fancybox-v3. This is very nice for mobile devices.

I like to do a small tutorial in a few weeks about "wordpress filter + fancybox" for mobile device. So it will be nice to use the new fancybox-v3 and not just the old fancybox-v2.

Is there any way to fix or avoid this problem?
Did you know how isotope avoids this problem?


**online fancybox-v2-Filter:** http://www.jochenkonrad.de/Fancybox-v2-Filter/fancybox-v2-test_01.html

**Comment by fancyapps** [comment]
The problem is related to general concept of "data", .e.g, it is not good idea to mix html5 attributes like "data-fancybox" and jQuery ".data()", because it can lead to unexpected results. I will fix this in the next release. In the meantime, you can add a workaround to your code, simple set both of them:

`.attr("data-fancybox")` and `.data("fancybox", "gallery")`

See - http://codepen.io/anon/pen/GWMYaq?editors=1010

**Comment by JochenKo** [comment]
ok, thanks for your time and help.

This is nice to avoid this problem =)

I will add this workaround to my tutorial. Can you close this issue when the problem is fixed in the next release, so I can see for my tutorial when the problem is fixed.

Have a nice day and thanks again.

**Comment by schumannumw** [comment]
I had this question as well and couldn't get anything to work. Thanks for the response! 

My problem now is that I have some images that are present in multiple categories. Not just one. 
From the codepen example Id be looking at having a data-filter on some of my images such as the following. 
data-filter="anim land arch"

But that doesn't work.  Any suggestions?

**Comment by JochenKo** [comment]
Hey schumannumw,

Mr. Fancybox's workaround is working very well and the issue will be fixed soon.

But I think your problem is that you use more than one word in "data-filter" attribute and that dosn't work in HTML5. The solution is to check if the parent div class has the same value as your filter than get the filter value into the "data-filter" attribute. The parent div can have more than one class and you can activate the fancybox with the "fancybox-item" on the parent div.

I hope you understand my filter-script and my description.

https://codepen.io/JochenKo/pen/wJjYZR

**Comment by fancyapps** [comment]
It just depends on your code related to filtering. 

I recently created this fun demo - http://codepen.io/fancyapps/pen/GWxrRe - works well having multiple filter values, but it does not use isotope.

**Comment by schumannumw** [comment]
Thanks for your help everyone. The structure in the last demo you sent was almost identical to what I had. 
Thank You, Thank You. Works Perfect!

**Comment by fancyapps** [comment]
btw, here is really simple filter demo - https://codepen.io/fancyapps/pen/YQKPYX?editors=1010
