### ISSUE TITLE
fancybox 3, custom sizes for multiple fancyboxes

### ISSUE THREAD

**Issue by LiamDawe** [fancyapps/fancybox#1296]
So, previously in fancybox 2 you would have something like this:
```
	$(".who_likes").fancybox({
		maxWidth	: 800,
		maxHeight	: 600,
		fitToView	: false,
		width		: '70%',
		height		: '60%',
		autoSize	: false,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none'
	});
```

I have multiple like that, as I use different sizes for different things. I can't find anything in the docs on how to adjust sizing for multiple fancyboxes like we used to?

**Comment by fancyapps** [comment]
Hi,

v3 avoids using JS to size and center the content (except images) and it allows you control dimensions using CSS. For example - http://codepen.io/fancyapps/pen/MJYOOd?editors=1100
