### ISSUE TITLE
Conflict with Bootstrap Daterangepicker

### ISSUE THREAD

**Issue by ODLTechnology** [fancyapps/fancybox#1297]
Hi,

There is a conflict with bootstrap daterangepicker [http://www.daterangepicker.com/](url).
When i apply new dates, the daterangepicker is closing, but the fancybox too. How can i prevent the close event from the daterangepicker to keep the fancybox opened ?

Thanks

**Comment by fancyapps** [comment]
Hi,

Please, create a reduced test case and a live example. Ideally, use codepen to fork any demo found on documentation.

Thanks.
