### ISSUE TITLE
Fancybox V3: protect video from download

### ISSUE THREAD

**Issue by set4kay** [fancyapps/fancybox#1298]
Please I want to know how to protect download of video in fancybox by right clicking.

Also the video height is minimal; about 1px in mozilla firefox browser.

Thank you.

**Comment by fancyapps** [comment]
Hi, What do you mean - " video height is minimal; about 1px"?

https://github.com/fancyapps/fancybox#bugs-and-feature-requests

**Comment by set4kay** [comment]
Hi,
I'm really sorry, what I mean is that the video doesn't cover the entire 800px by 600px dimension in firefox unlike chrome; here are snapshots to mozilla view and chrome view respectively:
 
![mozilla view](https://cloud.githubusercontent.com/assets/26410958/24041778/3a14606c-0b0f-11e7-82f9-f1e3b3b8aef5.jpg)
![chrome view](https://cloud.githubusercontent.com/assets/26410958/24041779/3ac9acec-0b0f-11e7-85cd-db570ee53332.jpg)

I however found a some lines of JavaScript online that does the magic, I'm not yet good with Javascript:

$("[data-fancybox]").fancybox({
    type: 'iframe',
    width: 800,
    height: 580,
    // add
    fitToView: false,
    iframe : {
      preload : false
    }
    });

But the problem with using this code is that it stops the code used to protect image from download from working:

$("[data-fancybox]").fancybox({
		image : {
		  protect: true
	   }   
	});

Below is a snapshot of my inline script:

![script](https://cloud.githubusercontent.com/assets/26410958/24041918/debabfee-0b0f-11e7-9027-5952eb69c7b3.PNG)


Thank You

I'll appreciate your help here.

**Comment by Cu8eeeR** [comment]
Unfortunately Firefox seems to be worst and worst - I had several issues with non working parts of websites which I maintain - no issue on other browsers, code was written according to the latest standards, but Firefox refused to show it properly. Maybe that's why Firefox's popularity has been decreasing for last two years. Despite of these issues it would be nice to find the issue and make it working in Firefox.

**Comment by fancyapps** [comment]
In v3.1. you will be able to set "protect: true" and it will disable right click on any content (it now works only for images).

The API in v3 is changed a lot, there are no more options like "width", "height" and "fitToView". You have to controll content dimensions using CSS - http://fancyapps.com/fancybox/3/docs/#iframe

**Comment by fancyapps** [comment]
FYI, v3.1 is now published and it has `protect: true` option to disable right click on any content.

btw, if you use the same selector multiple times (e.g. `$("[data-fancybox]").fancybox()`) then only the last one will work.
