### ISSUE TITLE
Fancybox iframe lacks support of scrolling

### ISSUE THREAD

**Issue by getmyprog** [fancyapps/fancybox#1299]
When fancybox try to load an iframe with a very large content, it should open it with a scroll bar.
Right now, it just clips it.

example for the issue:
```
<a data-fancybox data-src="http://www.ynet.co.il/home/0,7340,L-184,00.html" href="javascript:;">
    External page
</a>
```

**Comment by fancyapps** [comment]
Hi, This is how you can control iframe scolling:

```JS
$('[data-fancybox]').fancybox({
  iframe : {
    scrolling : 'auto'
  }
});
```

Actually, I can not remember why default value is "no", I think it probably works better when iframe content dimensions can be calculated and iframe is autosized.

**Comment by getmyprog** [comment]
Thanks for the response,
I think it should be auto as default...

Anyway, I've played with this answer a little, and found out that I've opened the fancybox with .open function, so the structure should be:


`"opts":{
                    iframe : {
                        scrolling : 'yes',
                        css : {
                            'width': '100%',
                            'height': '90%'
                        }
                    },`
Am I correct?

**Comment by fancyapps** [comment]
Yes, you are correct. I think I`ll change to "auto" for the next release. I`ll just make some tests to see what works best.

**Comment by PendoNL** [comment]
The docs need an update as well, it says there the following should be used as options:

```
{
    iframe: {
        attr: {
            scrolling: 'auto'
        }
    }
}
```

while the working settings are:

```
{
    iframe: {
        scrolling: 'auto'
    }
}
```

**Comment by fancyapps** [comment]
@PendoNL If you are using fancyBox v3.1, then this if how you set iframe tag attributes, including `scrolling`:

```JS
$('[data-fancybox]').fancybox({
  iframe : {
    attr : {
      scrolling: 'no'
    }
  }
});

```

Demo - https://codepen.io/anon/pen/pwNmqm?editors=1010

**Comment by PendoNL** [comment]
Point taken! I was using `3.0.47` from CDN.
