### ISSUE TITLE
Flash banners are intractable when opened on IE11 & Chrome

### ISSUE THREAD

**Issue by VadimLu** [fancyapps/fancybox#1300]
I have flash banners in my website, embedded with SWFobject 2.2.
I use Fancybox 3 to open them nicely, using inline content.

Some of the banners include interaction, for example shooting at ducks, but when I try to open this banner on IE11 & Chrome, and shoot the ducks, nothing is happening, in Firefox it works fine!

I've noticed that this is related to touch, when I disable touch from the JS library, it works fine on all of the browsers, is there a fix for this without disabling touch?

This is the [page](http://www.vldesign.co.il/banners_2_en.htm), click on the ducks thumbnail image and try to shoot the ducks on chrome & IE.

Please, this is very urgent to me, I will appreciate this very much!
Thank you!

Vadim.

**Comment by mjcampagna** [comment]
You're killing me. With this, and your other post about XHTML, you're clearly working in a bygone era. That being the case, A) Can I borrow the time machine you arrived in? And B) You should probably roll back to Fancybox 2, as that's the version contemporary with the standards you appear to be operating with.

**Comment by VadimLu** [comment]
Thank you for your reply Matthew,

You are more than right about the dinosaur website hah, this is an old
website, actually a lot of websites still use xhtml as I see, I have a few
clients that their websites use XHTML, and we definitely need to rebuild
them at some time, you know it depends on client's decision to invest his
money in renewing his website, but today we develope responsive websites
with HTML5, till than I thought that there's a solution with this touch
problem because I have another client which use flash on his xhtml and has
the same problem, so I thought you can help me with this and point me to a
temporary solution..

Thank you!
vadim.

**Comment by Cu8eeeR** [comment]
I think there should not be any temporary solutions - it is a step back. 

If you wanna use FancyBox then update your websites to follow latest standards...

**Comment by VadimLu** [comment]
Hey, we just did the same test on an html 5 website and seems that the same problem occured... only if we disable touch, it is possibe to click on elements inside the banner, something is covering the banner, we tried to change z-index.. not helped.. so it's not belong to the type of the page,  we don't want to disable touch and this plugin is great... on firefox works great, very strange...

**Comment by fancyapps** [comment]
When I open your page using Chrome to inspect element you are trying to open:

`<div style="display: none;" id="2"><div id="interactive_flash_2" style="visibility: visible;"></div></div>`

The same element when I`m using FireFox:

`<div style="display:none;" id="2"><object type="application/x-shockwave-flash" data="../portfolio/banners/interactive_flash/Interactive_Flash_2.swf" id="interactive_flash_2" style="visibility: visible;" height="90" width="728"><param name="wmode" value="opaque"></object></div>`

See any difference? 

I have no idea what causes this.
