### ISSUE TITLE
"data-fancybox" is not a member of a group specified for any attribute

### ISSUE THREAD

**Issue by VadimLu** [fancyapps/fancybox#1301]
What about XHTML support? "data-fancybox" and "data-src" are not valid markups, my page fails to pass the check when I test it on https://validator.w3.org/

Thank you!

Vadim.

**Comment by mjcampagna** [comment]
And yet they are fully valid HTML5. Why are you still adhering to the olden
days of XHTML?
-- 

--
Matthew Campagna
The Turning Gate | http://theturninggate.net
Photographers Plugins and Resources

**Comment by fancyapps** [comment]
Hi,

First, do not take code validators too seriously. These tools are designed to help developers identify possible issues, but it does not necessary mean that you should blindly follow everything they say. It is the same as with JSLint - I think (like many other developers) that is is too strict and therefore I use JSHint.

If you really care about validating your HTML code, you can avoid using these html5 attributes, simply create your custom click events on your elements and then start fancyBox manually using `$.fancybox.open()` method.
