### ISSUE TITLE
Don`t work events v3

### ISSUE THREAD

**Issue by Tsyklop** [fancyapps/fancybox#1302]
I add elements with the help of IС, and created events for them with the help of `$(document).on(...)`
But event not working.
example:
http://codepen.io/Tsyklop/pen/RpjXVj

**Comment by fancyapps** [comment]
Hi, Sorry, the API has changed a bit, this is how it works now - http://codepen.io/anon/pen/JWMdXM?editors=1111

**Comment by Tsyklop** [comment]
@fancyapps Thanks)
