### ISSUE TITLE
Fancybox v3: touch behaviour

### ISSUE THREAD

**Issue by dermansi** [fancyapps/fancybox#1303]
Disabling touch doesn't prevent controls from behind hidden on touch move (like scrolling down on fancybox content hides controls, scrolling again shows them again)
fancybox type was ajax

**Comment by dermansi** [comment]
Disabling touch doesn't prevent controls from behind hidden on touch move

**Comment by fancyapps** [comment]
I have no idea what are you trying to describe, sorry.

**Comment by dermansi** [comment]
I'll try to provide a codepen tomorrow
