### ISSUE TITLE
How correctly to include fb in such structure?

### ISSUE THREAD

**Issue by Fezas** [fancyapps/fancybox#1304]
How correctly to include fb in such structure?
`<li><a href="" rel="group" data-fancybox class="fnbox"><img class="stretchRight backfon img"  /></a><div><div>Открытка</div><div>Шелкография в 2 цвета, лак с подъемом. </div></div></li>`
For fb3 necessarily jquery 3.0?

**Comment by mjcampagna** [comment]
This will open the href target:

```html
<li><a href="" data-fancybox="group">...</a></li>
```

Or: 

```html
<li><button data-fancybox="group" data-src="#fb-modal">...</button>
<div id="fb-modal"><div>Открытка</div><div>Шелкография в 2 цвета, лак с подъемом. </div></div>
</li>
```

**Comment by Fezas** [comment]
Thanks... But.... Fb3 is started. But can not load the image. Instead, it's a gray box.
`<li id="736" data-filter="otkrytki" class="elems-item pokazat_vse otkrytki"><a href="" rel="group" data-fancybox="group" class="fnbox" title="Открытка &quot;Венинефть&quot;"><img class="stretchRight backfon img" alt="Открытка &quot;Венинефть&quot;" src="/upload/resize_cache/iblock/813/310_400_140cd750bba9870f18aada2478b24840a/8139bbe91fdd37e9d545f05e51852168.jpg" /></a><div><div>Открытка &quot;Венинефть&quot;</div><div>Шелкография в 2 цвета, лак с подъемом. </div></div></li>`
