### ISSUE TITLE
Licensing for commercial projects based on opensource projects with FB included

### ISSUE THREAD

**Issue by seigieu** [fancyapps/fancybox#1305]
I wanted to ask, how does license handle such situations.

If opensource project includes free license and someone is using this project to extend it and change then use as commercial application.
For example I use OS based project with FancyBox, then change template for my customer? Does free license apply to all subprojects even if they're commercial?

**Comment by fancyapps** [comment]
Hi,

In this case, if you include fancyBox under open source license terms, your commercial project should be open sourced, too. To avoid that, you would need to obtain commercial license.

**Comment by gacekssj4** [comment]
So, for example. If I build online shop for my customers, then if it includes Fancybox I can't really use it, nor my client can? More it should concern my client, should he buy license then?

**Comment by fancyapps** [comment]
The best option for you would be to provide fancyBox as an optional module/plugin with a note that your clients would need a separate license (if using it).
