### ISSUE TITLE
Multiple instances showing up behind other open instances

### ISSUE THREAD

**Issue by 1TheMuffinMan** [fancyapps/fancybox#1309]
I'm using fancybox to show inline html that has a product description and some images. When clicking the images I open another fancybox which works well, however any new fancybox's don't set their z-index properly so they show up behind any opened modals.

You can observe with this code:
    1.  `$.fancybox.open('<div class="message"><h2>First box</h2><p>You are awesome!</p></div>');`
    2,  `$.fancybox.open('<div class="message"><h2>Second box</h2><p>You are awesome!</p></div>');`

When invoking 1. you will see fancy box and then if you invoke 2. while 1. is open you will observe that 2. is behind 1.

**Comment by fancyapps** [comment]
Sorry, your code works fine for me. Any demo/screenshot? Maybe you are using an old version of jQuery?
Please, give any clue.

**Comment by fancyapps** [comment]
See this demo - http://codepen.io/fancyapps/pen/EWENZy?editors=1010

**Comment by 1TheMuffinMan** [comment]
@fancyapps Thanks for the quick response and demo. After comparing code it appears that there was an issue with the minified css that I downloaded from npm. I replaced it with the version on the main site.
