### ISSUE TITLE
How do I open gallery in full screen mode?

### ISSUE THREAD

**Issue by moazam1** [fancyapps/fancybox#1310]
Thanks for making an excellent plugin. I would like to open a gallery in a full screen. Right now I am using following code: 

`beforeLoad: function() {
            $.fancybox.getInstance().FullScreen.launch();
        }`

Above code is working fine but I see flicker because it switches to full screen mode from normal mode. I have checked docs but I couldn't found any hint. Any help will be greatly appreciated. 

Thanks

**Comment by fancyapps** [comment]
Hi, Thanks!

It would be like this -

```JS
$('[data-fancybox="images"]').fancybox({
	fullScreen : {
		requestOnStart : true // Request fullscreen mode on opening
	}
});
```

See demo - http://codepen.io/fancyapps/full/OpvgRL/
As you can see, it would work better without zoom animation, but the option to disable that animation will be available in the next release.

**Comment by moazam1** [comment]
I have already added that but it's not working.

**Comment by fancyapps** [comment]
Maybe you are using a bit outdated version, try updating to the latest.
