### ISSUE TITLE
Disable #group from URLs on Gallery Images

### ISSUE THREAD

**Issue by saaqi** [fancyapps/fancybox#1312]
Hello, Please tell me how I can disable #group from url's when I use data-fancybox="group" with gallery images.

Because when I close the image and press the back button it just goes back to example.com/#group and opens up the image again instead of going back to the previous page.

Thank you

**Comment by fancyapps** [comment]
Hi. If you wish to disable hash module, use this snippet (after including JS file):

`$.fancybox.defaults.hash = false;`

**Comment by saaqi** [comment]
Wow that was a quick reply. Thank you so very much.

I read that and I thought I had to use hash = false like this

**Comment by fancyapps** [comment]
That would be too late, because hash is checked at the page load.
