### ISSUE TITLE
Browser back button

### ISSUE THREAD

**Issue by rawkinrich** [fancyapps/fancybox#1313]
Hi all,

Apologies for my ignorance if this has already been solved. I have upgraded to Fancybox 3 and I have a problem.

When browsing images via Fancybox and the closing to browse the page, when clicking the browsers back button it relaunches Fancybox.

How to fix?

Many thanks

**Comment by fancyapps** [comment]
Hi. If you wish to disable hash module, use this snippet (after including JS file):

$.fancybox.defaults.hash = false;
