### ISSUE TITLE
Autoplay Slideshow

### ISSUE THREAD

**Issue by bora77** [fancyapps/fancybox#1314]
Hey guys, I just upgraded to fb3, but I cannot find a simple way to autoplay the images without clicking the play button...

Any ideas please? Isn't there a config option?

**Comment by fancyapps** [comment]
Hi,

There is currently no such option.

Module option naming in v3.1 will be unified and "thumbs", "fullScreen" and "slideShow" will have "autoStart" option.

**Comment by pieterratering** [comment]
Ah, that would be great. I had exactly the same question. Can't wait for 3.1 ;-)

**Comment by jeangontijo** [comment]
`$("[data-fancybox]").fancybox({
        afterLoad: function() {
            
            if (!$('.fancybox-button--play').hasClass("fancybox-button--pause")) {
                $('.fancybox-button--play').trigger('click');
            }
        }
    });`

**Comment by jeangontijo** [comment]
`$("[data-fancybox]").fancybox({
        afterLoad: function() {
            
            if (!$('.fancybox-button--play').hasClass("fancybox-button--pause")) {
                $('.fancybox-button--play').trigger('click');
            }
        }
    });`

**Comment by jeangontijo** [comment]
```
$("[data-fancybox]").fancybox({
        afterLoad: function() {
            
            if (!$('.fancybox-button--play').hasClass("fancybox-button--pause")) {
                $('.fancybox-button--play').trigger('click');
            }
        }
    });
```

**Comment by fancyapps** [comment]
FYI, v3.1 is now published and there is an option for that : `slideShow : { autoStart : true }`
