### ISSUE TITLE
Dynamically Pause YouTube Video via Unfocused Window from FancyBox

### ISSUE THREAD

**Issue by mikethedj4** [fancyapps/fancybox#1317]
I already know how to play/pause a YouTube video dynamically as you can see from (my weave](http://mikethedj4.github.io/kodeWeave/editor/#8d47a5b359582487390ebba52757ea9e).

However I'm having difficulty getting it to work dynamically with FancyBox using onBlur (when the window is not focused video should pause).

Here's my Pen: http://codepen.io/anon/pen/wJXoJy?editors=0010

**NOTE**: This is being done for an Android application and the video plays when the phone is locked which is against Google's policies. I tried using `document.addEventListener("pause")` but it didn't work that way either. The problem is getting it to work dynamically with FancyBox. (I'm using FancyBox 3)

If anyone can help it'd be greatly appreciated.

**Comment by fancyapps** [comment]
Hi,

Here is a demo - http://codepen.io/fancyapps/pen/jBKowp?editors=1010

Basically, idea is that you initialize fancyBox after YouTube API is available and then you can use YouTube API methods inside fancyBox callback.
