### ISSUE TITLE
Can not download images on smartphones and tablets

### ISSUE THREAD

**Issue by Bondye** [fancyapps/fancybox#1318]
When user may download the image, I use 
$('[data-fancybox]').fancybox({
	image : {
		protect: false
	}
});

This works on a PC, but using a smartphone or tablet, I cannot download the image (context menu doesn't show up).

- Tested on Android devices
- Tested in Chrome
- FancyBox v3.0.47

**Comment by fancyapps** [comment]
This is not related to "protect" option, but to touch events. Correct me if I am wrong, but I do not think it is possible to have touch events (swipe, etc) and default browser behavior simultaneously.

**Comment by Bondye** [comment]
Sorry, but I am sure you can mix touch events and have the context menu coming up.

For example, I often use [SlickJS](http://kenwheeler.github.io/slick/)
If you look @ "Lazy loading" or "Fade" you can swipe, but also hold down for the context menu.

**Comment by fancyapps** [comment]
Hmm, maybe on android (have not checked yet), but it does not work that way on iOS.

**Comment by Bondye** [comment]
After commenting line 3032 the context menu is showing.

I don't know the consequences, but this works for me.

**Comment by fancyapps** [comment]
:) that breaks everything on desktop and background starts scrolling on iOS

**Comment by Bondye** [comment]
Indeed, I added a check, (quick and dirty :P) 

#3031
e.stopPropagation();
if( e.type === 'mousedown' ) {
	e.preventDefault();
}

**Comment by mjcampagna** [comment]
The best solution I've come up with is to create a download button in the slideshow. I can share code later if interested -- a bit busy to work it out right now -- but you can add a link to the UI such as:

```html
<a href="image.jpg" target="_blank" download>Download</a>
```

On desktop, the image should download. On mobile, the image opens in a new window, where it can be interacted with using browser-native features.
