### ISSUE TITLE
Can't close Inline-Fancybox with scrollbar when clicking on the outside

### ISSUE THREAD

**Issue by pechisworks** [fancyapps/fancybox#1319]
After opening the Fancybox-Modal, i can't close it by clicking on the outside.
This only happens, when the Modal is higher (so with a scrollbar) than the screen.

Please see the this codepen below:
https://codepen.io/anon/pen/aJKqMN

Version: v3.0.47

This is happening because of the gestures.js ontouchstart() Method, Line 141:
```
if ( isClickable( $target ) || isClickable( $target.parent() ) || ( isScrollable( $target ) ) ) {
			return;
}
```

**Comment by fancyapps** [comment]
Closing on click was disabled for scrollable items, because otherwise it would not be possible to scroll on mobile devices.  Next commit will contain a fix where it checks for mobile device.

**Comment by vollyimnetz** [comment]
@fancyapps i dont had seen your current code, but i coded a small lightbox for my own purpose a few weeks ago. 
To fix this you have to check if the click event has bubbled or if it is directly performed on the Backdrop.

I love your lightbox - using it since version 1.

**Comment by fancyapps** [comment]
Thanks.

This has been improved lately.
