### ISSUE TITLE
Possible to change template for fancybox-slide?

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1320]
Each photo has comments located in a database on my server. I would like to have a small div element below or beside each image in the slide that I can load the comments into. Is there a way to edit this?

**Comment by fancyapps** [comment]
I would suggest you to simply use callbacks to create your element, for example, onInit and then use, for example, onComplete callback to load comment for selected image.

There is example having statistic block for each gallery - http://codepen.io/fancyapps/full/XMKjrJ/  - but you can teak it to change contents for each image.
