### ISSUE TITLE
Remove fancybox history on close

### ISSUE THREAD

**Issue by mortentoo** [fancyapps/fancybox#1322]
When opening fancybox it currently changes the URL (and add to the browser history I presume), which is all great and being able to navigate back with the back button also makes some sense.

However, if you close fancybox and hit the back button it will re-open fancybox and start going backwards through the browser/fancybox history. This breaks the "natural" site navigation.

I'd suggest either...

- counting history additions and use history.go(-x) to revert history back to before fancybox was first opened

- add an option to completely disable history

- perhaps some pop or replace function to alternatively remove history

I'm no expert on using the HTML5 browser history, but read up on it here: [http://html5doctor.com/history-api/](url)

**Comment by fancyapps** [comment]
Hi. If you wish to disable hash module, use this snippet (after including JS file):

`$.fancybox.defaults.hash = false;`

**Comment by mortentoo** [comment]
Cool, thanks. Was looking for something like this.

It may make sense to use `history.replaceState()` when navigating in fancybox (since it has it's own back/forward navigation). This could leave option for URL's directly to a gallery, while maintaining back/forward navigation in the browser.

**Comment by fancyapps** [comment]
Thanks for your suggestion. I have already implemented "replaceState" and it works better when pressing back button. It will be available in the next commit.

**Comment by mortentoo** [comment]
Glad you liked it as well, and happy to help :)

**Comment by hobadams** [comment]
Hey @fancyapps - Do you have an ETA on the commit containing the 'replaceState' fix?  Thanks so much

**Comment by fancyapps** [comment]
@hobadams Hi, It has been included in 3.1 branch - https://github.com/fancyapps/fancybox/tree/3.1

**Comment by hobadams** [comment]
@fancyapps - amazing...thank you  <3

**Comment by fancyapps** [comment]
Unfortunately, it is not possible to remove entry from browser history. 
There has been some improvements related to hash module in v3.1, though.

**Comment by Jaded-Design** [comment]
It's also important to note that you don't *have* to put the $.fancybox.defaults.hash = false; after the JS file if you just wrap it in a doc ready function.

**Comment by vndevil** [comment]
$.fancybox.defaults.hash = false;

Resolved issue :D

**Comment by Heberty** [comment]
> Oi. Se você deseja desativar o módulo hash, use este trecho (depois de incluir o arquivo JS):
> 
> `$.fancybox.defaults.hash = false;`

Brother, you are a monster! Thank you!
