### ISSUE TITLE
Option to disable place back focus on cleanup?

### ISSUE THREAD

**Issue by michaelegan** [fancyapps/fancybox#1327]
I ran into a Chrome bug where CSS-based hovers were getting "stuck" in the on position when Fancybox 3 was focusing the original click target and the target was out of view. (In my case behind a hover state controlled by a CSS transform.)

Since the afterClose callback occurs ahead of the place back focus call I was looking for an way to make the code below optional. I tried a few different ways but was only able to fix the hover bug by removing it completely.

`// Place back focus
if ( self.$lastFocus ) {
  self.$lastFocus.focus();
}`

**Comment by fancyapps** [comment]
Hi, In the next release, you will be able to disable by setting `focusBack: false`.

**Comment by fancyapps** [comment]
FYI, it has been implemented.
