### ISSUE TITLE
[FeatureRequest] mobile: jQuery vibrate integration and displaying fancybox-button--left/right 

### ISSUE THREAD

**Issue by joszz** [fancyapps/fancybox#1329]
Hi

Thanks for your awesome work on the new and improved FancyBox. I've always used FancyBox with great pleasure, cause I feel this is the most flexible and extendible lightbox/modal dialog out there!

I was fiddling around a bit with the latest v3 release, and I was wondering if it was somehow possible to have [jQuery vibrate](https://github.com/Illyism/jquery.vibrate.js) hooked up in FancyBox. I tried hooking up the buttons on the afterLoad event with something like this, no go though;
```
$("[data-fancybox]").fancybox({
        afterLoad: function () {
            $("button").vibrate();
        }
});
```

Also it would be nice to have an option to show the left/right buttons for mobile view. I found that you use mediaqueries to hide them so I just overwrote that with my own CSS, not a big deal but it's nicer when it's actually integrated. This is my overwrite;
```
@media (max-width: 800px) {
    .fancybox-infobar {
        width: 100%;
        text-align: center;
    }

    .fancybox-button--left,
    .fancybox-button--right {
        display: inline !important;
    }
}
```

The reason I want these displayed is that I use FancyBox with iFrames and the swiping functionality doesn't work that well. The iFrame covers too much of the viewport so it's almost impossible to swipe to make it go to the next iFrame.

Just feature requests. Would be awesome if you found time to implement them (and agree with them :))

**Comment by fancyapps** [comment]
Hi, Thanks!

I would suggest to use onComplete callback and select buttons only inside fancyBox:

```JS
$('[data-fancybox]').fancybox({
  onComplete : function( instance, current ) {
    current.$slide.find('button').vibrate();
  }
});
```

I created a demo using the vibrate plugin - http://codepen.io/fancyapps/pen/MpPmwo 
I have not tested on Android, but even examples found on that plugin homepage - http://illyism.github.io/jquery.vibrate.js/ - does not seem to work on iOS (I tested on Safari and Chrome).

Also, it is perfectly normal to override default fancyBox CSS rules. The infobar arrows are hidden on small screen sizes as they can overlap other buttons (if centered). In v3.1 there will be available classical arrows at the screen edges.

**Comment by joszz** [comment]
Thanks for the answer!
The vibrate plugin works on android is what I'm sure of. Your demo doens't work yet, i'll dig in a bit deeper. Wouldn't be surprised if the event bubble is stopped somewhere.

**Comment by fancyapps** [comment]
I tested on my Android Nexus tablet just now and even if this article - il.ly/vibrate  - states that my browser supports Vibration API, examples are just not working. 

But then I realized, my tabled probably has not vibrating capability :)

If the previous demo is not working for you, maybe you could just try native API usage like `window.navigator.vibrate(200);` because I do not see reason why some jQuery plugin would not work inside fancyBox modal window.
