### ISSUE TITLE
Sample code for YouTube embedding is incorrect. (Fancybox3)

### ISSUE THREAD

**Issue by sakotsu** [fancyapps/fancybox#1331]
Hi,

Fancybox3 is great work!
I will use it whit thank!

Please check the following code.

http://fancyapps.com/fancybox/3/docs/#embedding
[Embedding] > [Video parameters]

current code (error?)
`<a data-fancybox href="https://www.youtube.com/watch?v=_sI_Ps7JSEk&amp;autoplay=1&amp;rel=0&amp;controls=0&amp;showinfo=0">`

may be correct
`<a data-fancybox href="https://www.youtube.com/watch?v=_sI_Ps7JSEk&autoplay=1&rel=0&controls=0&showinfo=0">`

＼(^o^)／ Fancy!!

**Comment by fancyapps** [comment]
Hi!

`&amp;` is just encoded `&` - http://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

**Comment by sakotsu** [comment]
thank you & sorry.
