### ISSUE TITLE
1 issue and 3 FancyBox parameter questions.

### ISSUE THREAD

**Issue by radddar** [fancyapps/fancybox#1332]
Hello,
Thanks for your job, it's great plugin. It works very well.
My english is very bad !

I use the FancyBox3 with zoomify. I have 1 issue and 3 FancyBox parameter questions.

1)  **Inline HTML**
The background is similar and dark in the zoomify box and in my base page.
I call the fancy inline (clic "Help to Zoom ?"). Then I close the Fancy Box.
All i good BUT THE BACKGROUND becomes WHITE ! Why? How to do to keep the background ?

Here is here is my code Extremely simplified :

```
=======
<body style="background-color:#262626;">
<!--====  Zoomify=====-->
   <div style="width:1198px; height:627px; margin:auto; border:1px; border-style:solid; border-color:#3F3F3F; background-color:#262626;" ></div>
<!--====  Fancy BOX  =====-->
	<div style="text-align:center">
	<a style="color:#dc5130" data-fancybox data-src="#Zoom" href="javascript:;">Help to Zoom ?</a>
	</div>
<!--==Fancy Inline======-->
<div style="display: none;" id="Zoom">
	<p>HELP</p>
</div>
</body>
=======

```

2) I presente a zoomify box with fancyBox in an iframe.
Is it possible to put a small close button at top right of the slide and not right top of the page?

3)I don't find how to code this options :
 	// Should display toolbars
	infobar : true,
	buttons : true,
	// What buttons should appear in the toolbar
	slideShow  : true,
	fullScreen : true,
	thumbs     : true,
	closeBtn   : true,
Can you help me, pleae?

4) In your exemple :  **Full size image goes below thumbnails**.  in http://codepen.io/fancyapps/pen/zNWLoG
There is no caption. If i put a caption : 
<a href="https:/ex.jpg" data-fancybox="group01" data-caption="blabla>
The space occupied by the caption is very high, and the image comes in.
How to decrease the height of the captions and place the image above the white line, please?

Thanks,
ps : where is the donate button?

**Comment by radddar** [comment]
**the inline code** : 

> =======
> <body style="background-color:#262626;">
> 
>    <div style="width:1198px; height:627px; margin:auto; border:1px; border-style:solid; border-color:#3F3F3F; background-color:#262626;" ></div>
> 
> 	<div style="text-align:center">
> 	<a style="color:#dc5130" data-fancybox data-src="#Zoom" href="javascript:;">Help to Zoom ?</a>
> 	</div>
> 
> <div style="display: none;" id="Zoom">
> 	<p>HELP</p>
> </div>
> </body>
> =======

**Comment by fancyapps** [comment]
Hi,

1) https://github.com/fancyapps/fancybox#bugs-and-feature-requests

2) Use `smallBtn` option to display close button - http://codepen.io/anon/pen/MpzRrW?editors=1010 - and you can use CSS to style/reposition if needed.

3) In v3.1 you will be able to customize what buttons to display

4) Use CSS to style caption. It is currently not possible to display caption right below content (it would require heavy calculations to resize content to make sure it fits with caption). But, if your caption is not long, just a few words, you can fake this by adding space at the bottom using margin option.

**Comment by radddar** [comment]
Hello from Lyon - France
Thank you for your quick and excellent answers.
2) You say: "Use smallBtn option to display close button - http://codepen.io/anon/pen/MpzRrW?editors=1010 - and you can use CSS to style/reposition if needed."
I tested your code ... I can not get it working.
Here is my code that does not work:
`<!DOCTYPE html>
<html lang="en">
<head>
    <title>TEST FANCY2</title>
    <meta charset="utf-8">
        
	<script src="js/jquery-3.2.0.min.js"></script>
	<link rel="stylesheet" type="text/css" href="css/jquery.fancybox2.css">
	<script src="js/jquery.fancybox.min.js"></script>

	<script type="text/javascript">
	// Slide Sans BARRE Bouton mais avec petit bouton
	$('[data-fancybox]').fancybox({
	  buttons  : false,
	  smallBtn : true
	});
	</script>
</head>

<body>

<h2>fancyBox - Iframe</h2>

<p>
  <a data-fancybox data-src="http://codepen.io/fancyapps/full/jyEGGG/" href="javascript:;">
    External page
  </a>
</p>

</body>
</html>
`
3) "In v3.1 you will be able to customize what buttons to display"
How to be warned when V3.1 will be operational, please?

thanks for all.
