### ISSUE TITLE
Fancybox v3 ignores data-options

### ISSUE THREAD

**Issue by cubecms** [fancyapps/fancybox#1335]
There seems to be a problem with usage of data-options.

This is the code:

`<a data-fancybox data-options='{"caption": "My caption", "src": "iframe.html", "css": {"maxWidth": "500", "width": "500", "maxHeight": "300", "height": "300"}}' href="javascript:;" title="abc">`

The caption shown below the iframe is always "abc" instead of "My caption" and the settings für width and height are also ignored.

**Comment by fancyapps** [comment]
Hi,

You are right about caption, this has been already discussed somewhere and fixed in my development version. This will be included in the next commit (v3.1 coming next week).

If you wish to size iframe, then these options goes under "iframe", e.g., 

```
iframe : {
  css : {
    width : '80vw'
    ..
  }
}

```

**Comment by fancyapps** [comment]
Hi,

This is how your link could be:

`  <a data-fancybox data-options='{"caption": "My caption", "src": "https://www.youtube.com/watch?v=N_EJK-qNJE8", "iframe" : { "css": {"maxWidth": "500", "width": "500", "maxHeight": "300", "height": "300" } } }' href="javascript:;" title="abc" class="btn">Click me</a>`

Demo - https://codepen.io/anon/pen/yXYQVq?editors=1010
