### ISSUE TITLE
Issue with IE11 - 'The Requested Content cannot be loaded. Please try again later'

### ISSUE THREAD

**Issue by PinoGris** [fancyapps/fancybox#1337]
Following HTML works fine in Firefox, Chrome and Safari, but running it in IE11 yields 
'The Requested Content cannot be loaded. Please try again later'.
Can anyone help me out please ?

[fancy3tst.txt](https://github.com/fancyapps/fancybox/files/888078/fancy3tst.txt)

**Comment by fancyapps** [comment]
Quite probably, the requested content cannot be loaded. 
https://github.com/fancyapps/fancybox#bugs-and-feature-requests

**Comment by PinoGris** [comment]
I apologize already now if you condsider this reaction out of order, in which case this will be my last communication on this subject.

However, I don't understand why this works fine with FF, Chrome and Safari, but not in IE11.
On top of that, when I remove the gallery type of setup by replacing <data-fancybox="sa"> by <data-fancybox>, it also works for IE11.

**Comment by fancyapps** [comment]
If the demos http://codepen.io/fancyapps/pen/jyEGGG/?editors=1000 are working fine for you (they are for me), then how can I help you without seeing your page or a live example demonstrating your issue?

**Comment by PinoGris** [comment]
For your information : in this case of mine, the html seems to be working fine for IE11 with 'web'-images
<code><HREF="http://www.xyz.net/image.jpg" data-fancybox="blog"></code>, but not with 'local'-images <code><HREF="image.jpg" data-fancybox="blog"></code>

**Comment by fancyapps** [comment]
Thanks for info. Then my guesses are:

1. Your images are not on docroot.

2. Maybe your browser has some settings/addons enabled that restricts viewing local files.
