### ISSUE TITLE
Themeforest Theme License Issue

### ISSUE THREAD

**Issue by arkabhowmik** [fancyapps/fancybox#1339]
Hello,

Thank you for the wonderful plugin. I have a particular question in reference to usage in a  Themeforest theme. 

Let's say I use a Extended Commercial License of Fancybox @119 USD. So, now I am able to use Fancybox inside my theme. So, the theme can be bought by both end users (for their own website as non-commercial usage) or AGENCIES (as commercial usage) WHO CAN THEN SELL IT TO ONE CLIENT ONLY FOR EACH SINGLE LICENSE OF THE THEME PURCHASED.

But here is my question. Do the individual agencies need to purchase separate license for the Fancybox plugin for every time they purchase my theme for every single of their own clients?

With regards,
Arka

**Comment by fancyapps** [comment]
Hi,

These would be typical usage examples and appropriate license for each one:

1. You are developing one website for yourself / one client
    One Single license

2. You are agency / freelancer developing websites for your clients
    One Single license for each website OR one Extended license to cover all websites created by you (your clients would not need to purchase another license)

3. You are going to sell your work to multiple clients, for example, theme on Themeforest
    One Extended license for each theme and your clients would not need to purchase another license

And the answer to your question - your license would cover them.

**Comment by arkabhowmik** [comment]
Hello,

I have got your response. Thank you. I however, have another question regarding licensing in a ThemeForest plugin. As a plugin can be purchased (as an extended licensed product besides regular licensing) for including it in a theme and sold to multiple users, will this be also covered under my license ?

With regards,
Arka

**Comment by fancyapps** [comment]
@arkabhowmik Yes, you can include in your themes, just remember - for each theme you need additional Extended license.

**Comment by arkabhowmik** [comment]
Maybe you did not read my question properly. Can I include it in a plugin that I sell on Themeforest ( which can then be purchased by my customers as an extended license and then they can include it in their own themes for sale to multiple clients) ?

**Comment by fancyapps** [comment]
You are right, I missed on that. In that case, sorry, no, it is not allowed.
