### ISSUE TITLE
bug mobile views

### ISSUE THREAD

**Issue by Oleksandr07** [fancyapps/fancybox#1345]
When opening a modal window from your phone, if it is less than the phone screen not working input checkbox and scripts http://joxi.ru/v29nN36U6weKAG . The problem found in this piece of code `void 0:u.opts.touch?void(e.originalEvent&&2==e.originalEvent.button||(e.stopPropagation(),e.preventDefault(),!u||o.instance.isAnimating||o.instance.isClosing||!o.startPoints||o.startPoints.length>1&&!u.isMoved` . Disabling `e.stopPropagation(),e.preventDefault()` everything works fine.  The version of fancyBox v3.0.30, fancyBox v3.0.47

**Comment by justerest** [comment]
For this theme:
in mobile view mode can't change items if item view block has overflow: 'scroll'

**Comment by DivaResli** [comment]
I use Fancybox 2.1.5 to show images on my website. I noticed that it's not working properly in smartphone and Iphone. I think I must update to Fancybox3. How can I do it?

**Comment by fancyapps** [comment]
@DivaResli I do not understand the question, it is quite obvious:

1) remove old files; 
2) read http://fancybox.docs/3.1/#usage 
3) download files or use CDN/bower/npm - your choice; 
4) start using it!

@Oleksandr07 This should be fixed some time ago. I suggest upgrading to 3.1 branch, if you are not already using it.

@justerest If you mean swiping horizontally when content can be scrolled vertically, then I suggest using some navigation elements.
