### ISSUE TITLE
mobile not support well

### ISSUE THREAD

**Issue by viponedream** [fancyapps/fancybox#1347]
i use a phone to open the website http://fancyapps.com/fancybox/3/
and Product quick view   open demo
the picture  doesn't appear in the center of the phone screen. but on the right bottom.

**Comment by fancyapps** [comment]
Works fine for me - tested on iOS and Android Chrome.

**Comment by viponedream** [comment]
![Uploading @HBDK(NY6[QXIAC(7DRJ19M.jpg…]()

**Comment by fancyapps** [comment]
What phone, browser, browser version?
