### ISSUE TITLE
mobile like this?

### ISSUE THREAD

**Issue by viponedream** [fancyapps/fancybox#1348]
![hbdk ny6 qxiac 7drj19m](https://cloud.githubusercontent.com/assets/16624529/24755616/823b7f52-1b0d-11e7-841e-29e10be9c0d4.jpg)

**Comment by viponedream** [comment]
android phone

**Comment by fancyapps** [comment]
1. Do not make duplicated posts.

2. Make your issue reports reasonable - what browser and version are you using? Android has million versions. 

3. If you are having an outdated browser that does not support CSS3, then you are out of luck.
