### ISSUE TITLE
Hot enable buttons in custom layout?

### ISSUE THREAD

**Issue by leotankilevich** [fancyapps/fancybox#1349]
Hello. I got problems with the buttons. I used your "quick view" template.  I added buttons in **baseTpl**

But onclick nothing happend((

`$(function() {
    if ($('.gallery').length > 0) {
        var sliderSize = {
            height: 0,
            width: 0
        }
        $(".gallery img").each(function() {
            this.naturalWidth > sliderSize.width ? sliderSize.width = this.naturalWidth : false;
            this.naturalHeight > sliderSize.height ? sliderSize.height = this.naturalHeight : false;
            $(this).closest('a')
                .addClass('gal')
                .attr({
                    'data-fancybox': 'images',
                    'href': $(this).attr('src')
                });
            $(".gal").fancybox({
                baseClass: 'quick-view-container',
                infobar: true,
                buttons: true,
                thumbs: true,
                margin: 0,
                touch: {
                    vertical: false
                },
                closeClickOutside: false,
                baseTpl: '<div class="fancybox-container" role="dialog">' +
                            '<div class="quick-view-content">' +
                                '<div class="quick-view-carousel">' +
                                    '<div class="fancybox-slider-wrap"><ul class="fancybox-slider"></ul></div>' +
                                '</div>' +
                                '<a data-fancybox-previous id="prev"class="fancybox-button fancybox-button--left" title="Previous"></a>' +
                                '<a data-fancybox-next id="next" class="fancybox-button fancybox-button--right" title="Next"></a>' +
                                '<div class="quick-view-aside"></div>' +
                                '<div data-fancybox-close class="close"></div>' +
                            '</div>' +
                        '</div>',

                onInit: function(instance) {

                    /*

                        #1 Create bullet navigation links

                    */

                    var bullets = '<ul class="quick-view-bullets">';

                    for (var i = 0; i < instance.group.length; i++) {
                        bullets += '<li><a data-index="' + i + '" href="javascript:;"><span>' + (i + 1) + '</span></a></li>';
                    }

                    bullets += '</ul>';

                    $(bullets).on('click touchstart', 'a', function() {
                            var index = $(this).data('index');

                            $.fancybox.getInstance(function() {
                                this.jumpTo(index);
                            });

                        })
                        .appendTo(instance.$refs.container.find('.quick-view-carousel'));
                    

                },

                beforeMove: function(instance) {
                    instance.$refs.container.find('.quick-view-bullets')
                        .children().removeClass('active')
                        .eq(instance.currIndex).addClass('active');

                }
                
            });

        });
    };
});`

**Comment by fancyapps** [comment]
What buttons? I do not see any buttons :)

Have you heard of tools like jsfiddle or codepen? It just takes one click to fork any demo of fancyBox and use it as a template to create a code demonstrating your issue.

**Comment by fancyapps** [comment]
If you mean this option `buttons: true` then the script will only toggle existing ones, then you need to have a `<div class="fancybox-buttons"></div>` element where buttons will be created.
