### ISSUE TITLE
baseClass option not working with fancybox.open

### ISSUE THREAD

**Issue by MichaelSamteladze** [fancyapps/fancybox#1351]
Here is sample code that never assigns base class 

`$.fancybox.open({
        type: 'iframe',
        src: 'page.html',
        opts: {
            baseClass: 'myCustomClass',
        }
    });`

**Comment by fancyapps** [comment]
Hi, 

Sorry about confusion. You see, this option is applied before gallery objects are processed, therefore you need to use like this:

```JS
$.fancybox.open({
    type : 'iframe',
    src  : 'page.html'
}, {
    baseClass : 'myCustomClass',
});
```

See - http://codepen.io/fancyapps/pen/XRrKWQ

Also, this option is not updated when changing gallery item. The idea was that you set `baseClass` once per group and `slideClass` for each group item individually.
