### ISSUE TITLE
Fancybox and Video-js

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1352]
Hi,

I'm loading content via ajax with embedded video-js instances. When I'm opening/closing or replacing the current content in the Fancybox I have to load this function for the videos to still be working. It seems like an ugly hack to loop through all video instances every time I open and close and it also removes the whole video visually before it actually closes the Fancybox which is not super pretty. Any suggestions? Thank you!

```
$.fn.disposeVideo = function(e) {
	$('.video-js').each(function(e) {
		var videoID = $(this).attr('id');
		var player = videojs(videoID);
		player.dispose();
	});
};

beforeLoad: function(instance, slide) {
	$(this).disposeVideo();
},
beforeClose: function(instance, slide) {
	$(this).disposeVideo();
}
```

**Comment by fancyapps** [comment]
Hi, 

Could you, please, create some demo using Codepen or jsfiddle? I am not familiar with videojs, maybe you could somehow stop video inside `beforeClose` as it will be removed later anyway.
