### ISSUE TITLE
Having Trouble Using Data Attribute in onComplete

### ISSUE THREAD

**Issue by brittonk** [fancyapps/fancybox#1356]
I want to load photo comments in a custom layout panel but I can't seem to pass
$(this).attr('data-picid')

to the onComplete function.

**Comment by brittonk** [comment]
Probably not the cleanest of solutions, but I resolved my issue by having the captioning function include a hidden div with the values I needed and retrieved them in the onComplete function for pulling the photo comments.

**Comment by fancyapps** [comment]
Hi, This is how you can get data from clicked link - http://codepen.io/fancyapps/pen/RppgYO

I think it is perfectly fine to store something (for example, comments) in hidden div and display them when opening. You could, of course, use ajax to load them, but it is unnecessary unless you have tons of images.
