### ISSUE TITLE
getInstance().JumpTo() too slow

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1358]
I'm navigating between my content with this function, but on some pages it seems like the content is too heavy to load and the only thing visible is the black overlay. Almost like it tries to start the animation before the content is ready. Any ideas? Thanks!
```

$(document).on('click', '#items tr', function () {
	var index = $(this).data('row');
	$.fancybox.getInstance().jumpTo( index, 600 );
});
```

Is there a when ready function like getInstance().whenready().jumpTo() or something? This is just my guess what's going on.

**Comment by fancyapps** [comment]
Hi, what type of content are you opening? Why have you set open duration of `600`?

**Comment by seabasss** [comment]
I'm loading ajax pages with a lot of database content. I tried a higher number (600) thinking that was a delay or slower animation. Maybe this will work better in 3.1 without the whole page sliding.

**Comment by fancyapps** [comment]
Sorry, I do not understand - you set animation duration 600ms, and you are wondering why animation takes too long? Am I correct?

**Comment by seabasss** [comment]
Just so I understand how it works. Is the jumpTo() not fired until the getInstance is fully loaded?
If it is, then my problem lies somewhere else.

`$.fancybox.getInstance().jumpTo()`

Please ignore the 600. I was experiencing problem with the animation not being able to catch up with the amount of data I loaded so I just tried a bunch of different numbers. Again, I'm not using fancybox the standard way hehe. I load 3 modal boxes next to each other with a bunch of databasedata in every slide of a fancybox-gallery. Maybe just pushing it to the limit. Again, I think it will run a lot smoother in 3.1 without the sliding animation.

Thanks!

**Comment by fancyapps** [comment]
When you call, for example:

`$.fancybox.getInstance().jumpTo(1, 0)`

The script will create a new slide (if needed) and will immediately set position to center (without any animation).

**Comment by seabasss** [comment]
Wow, I've tried 200, 400, 600, 1000. Never thought of 0. Brilliant. Works so much better now!
I had to move some functions that I run on before and afterLoad, but work better than ever now.

Thank you!
