### ISSUE TITLE
Wordpress and Fancybox 3 issue

### ISSUE THREAD

**Issue by muzKore** [fancyapps/fancybox#1359]
Hey all. Kind of a bug report and kind of not. When logged into wordpress with an active fancybox3 slideshow, the top bar clashes with the infobar and navigation causing neither to show. I tested it in browsers (Chrome and FF) that are not logged in and it works fine. While technically it is a bug, the general public (unless they have logged into your site as a member) wont see the nav and info box. Comments work fine as by default they are at the bottom. Even after all fo that, it's an awesome plugin and hopefully this saves someone out there some pain. I lost two hours and a few fingernails :(

**Comment by fancyapps** [comment]
Hi,

If you wish, you can easily push fancyBox down using CSS. It is not possible to it automatically without an ugly hack.

**Comment by muzKore** [comment]
Okay. From what I could see, the boxes weren't there but I will take a closer look. Thanks for the response.

**Comment by fancyapps** [comment]
I`m sorry, I do not have WP to test at the moment, I can only guess what you are talking about (no idea what do you mean by "boxes").

**Comment by muzKore** [comment]
Apologies for not explaining myself. I was referring to <div class="fancybox-controls">and everything inside it. When not logged in, it is easily seen at the top which is perfect. When you are logged in, the black wordpress admin bar up the top somehow makes the box hide. It is not underneath. It is just not there. To be honest, for me that is not an issue as it is not for a site where people looking at it would be logged in.
Anyway, just wanted to let you know and appreciate your great product. Looking forward to buying some licenses and using it in some upcoming projects.

**Comment by fancyapps** [comment]
Thanks :) 

Try adding something like this:

```CSS
.admin-bar .fancybox-container {
  top: 32px;
}
```

**Comment by ssosina** [comment]
@muzKore I'm curious to know how you implemented Fancybox 3 to your Wordpress site. Are you using JQuery 1.12.4 that ships with Wordpress or a hosted version (latest JQery 3.2.1)?

**Comment by muzKore** [comment]
@ssosina Check your email :)

**Comment by dickkirkland** [comment]
Hiya. I'm having the same issue with the fancybox 3 plugin for Wordpress. As long as I'm logged out of the WP site, functionality is fine, but when logged in and editing posts & pages, clicking on a fancybox trigger of any kind causes the page to come a halt, disables scrolling, etc. Currently running WordPress 4.9.6. Maybe there is a new version of jQuery that is disabling the functionality of fancybox 3 when logged in? No .js errors in console.
