### ISSUE TITLE
Problems in iOS 10.3

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1360]
Hi Janus,

This discussion of Photoswipe has been brought to my attention, and Fancybox 3 (and other lightboxes) are apparently suffering the same issue. I wanted to make sure you were aware of it:
https://github.com/dimsemenov/PhotoSwipe/issues/1315

Cheers,
Matt

**Comment by fancyapps** [comment]
Hi,

This will be "fixed" in the next release. The only workaround I found was to increase timeout when content is resized after orientation is changed. 

In previous versions it was sufficient to update content size two frames after orientation is changed, but now the browser updates page after some delay.

**Comment by mjcampagna** [comment]
Glad to hear. I'll keep an eye on the commits for this fix. Thanks!

**Comment by squidgemonster** [comment]
Is there a manual fix that can be posted for this before it gets officially rolled into a release? Appreciate this is more Apple screwing up, but even the 500ms delay 'fix' would make it less of an issue...

**Comment by fancyapps** [comment]
@squidgemonster well, you can edit js file and insert setTimeout where needed or you can try upgrading to v3.1 - https://github.com/fancyapps/fancybox/tree/3.1 - work on documentation is in progress.

**Comment by fancyapps** [comment]
FYI, v3.1 is now published.
