### ISSUE TITLE
Video size

### ISSUE THREAD

**Issue by Thor111** [fancyapps/fancybox#1365]
Hello, i have a problem with the video size. I have 2 YouTube videos, the first is 640x360px, the second 560x315 px. The problem is, every video start in the same size. Can anybody help? TY.

**Comment by Thor111** [comment]
What I mean is: the maximum size may be only 640x360px and 560x315px. The videos start but much larger.

**Comment by fancyapps** [comment]
Hi,

As videos are just iframed paged, you can set options like for any other content having type "iframe":

```HTML
<a data-fancybox data-options='{"iframe" : {"css" : {"max-width" : "640px", "max-height" : "360px"}}}' href="https://www.youtube.com/watch?v=_sI_Ps7JSEk&amp;autoplay=1&amp;rel=0&amp;controls=0&amp;showinfo=0">
      YouTube video
</a>
```

Demo - http://codepen.io/fancyapps/pen/wdvQYy?editors=1010

Keep in mind that there is currently no option to keep aspect ratio, therefore there might be visible black bars if viewport is smaller.
