### ISSUE TITLE
Cannot clickOutside to close when content is large

### ISSUE THREAD

**Issue by KENICHI88** [fancyapps/fancybox#1367]
Hi. I meet a problem that is with content within popup is large. When popup opened, I click outside the content, nothing happens. My expect is close the popup. Could you take a look?
Thanks, Kenichi

**Comment by fancyapps** [comment]
Hi, This will be fixed in the next release.

**Comment by mathiassen1990** [comment]
Sounds good, when do you expect next release to be? :)

**Comment by fancyapps** [comment]
It took more time that expected, but I am now near finish line. Just final touches.

**Comment by mathiassen1990** [comment]
Great to hear! good job!

**Comment by fancyapps** [comment]
FYI, after many tests, updates and tweaks, v3.1 is now published.
