### ISSUE TITLE
Disable Esc key in fancybox 3.

### ISSUE THREAD

**Issue by sohrabzia** [fancyapps/fancybox#1368]
Is there any way to disable esc key in fancybox 3?

**Comment by fancyapps** [comment]
Hi,

There is currently no such option to disable esc key closing.

Why would you need this? If you want to make your form "modal", you can either set `modal` option or disable keyboard using `keyboard` option.

**Comment by sohrabzia** [comment]
thanks a lot. disabling keyboard is what i needed, Ill be careful next time before opening issue. Thanks a lot.

**Comment by gadlol** [comment]
There are sometimes that we need to disable esc button from closing the fancybox and the form not to be modal and we want keyboard navigation.

Can you please implement an option to prevent closing popup when user presses esc button?

**Comment by fancyapps** [comment]
You could just disable default keyboard handling and create your own based on your specific needs.

**Comment by gadlol** [comment]
It would be much easier with an option closeOnEsc...
