### ISSUE TITLE
Iframe... Download???

### ISSUE THREAD

**Issue by Thor111** [fancyapps/fancybox#1369]
Hello, when i open a iframe, on windows it look great, but with a mac i have a download button?
Can anybody help? TY.

![iframe](https://cloud.githubusercontent.com/assets/27402968/25005010/6045694a-2057-11e7-910d-26bb603528f0.jpg)

**Comment by fancyapps** [comment]
Hi,

I have never seen such button (at least, I can not remember), although I am occasionally using Mac :)

What is inside that iframe?

**Comment by Thor111** [comment]
only 2 Div's .... one in blue and one in white....
I think, it's a problem on the mac of my girlfriend... she have this problem also with fancybox2 and iframe... only Browser Mozilla....

**Comment by fancyapps** [comment]
Is this for every iframed page or just one? Are you experiencing this when viewing demos from the homepage?

**Comment by brendon** [comment]
@Thor111, is it perhaps a browser plugin producing that? Have you tried the same browser on another machine?

**Comment by vincent-cm** [comment]
It is something like a youtube downloader

**Comment by fancyapps** [comment]
I`ll assume that some plugin or software is adding this button.
