### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by rorc** [fancyapps/fancybox#1371]

**Comment by fancyapps** [comment]
https://www.npmjs.com/package/@fancyapps/fancybox

`npm install @fancyapps/fancybox`

**Comment by rorc** [comment]
Ok, thanks, will be great if that can see in docs 😄

**Comment by fancyapps** [comment]
Yes, sorry about that.

**Comment by rorc** [comment]
By the way, you are published module not properly (without exports object) =(
https://docs.npmjs.com/getting-started/creating-node-modules
Therefore have error on load `TypeError: t is not a function`

**Comment by rorc** [comment]
@fancyapps By the way, you are published module not properly (without exports object) ☹️
https://docs.npmjs.com/getting-started/creating-node-modules
Therefore have error on load TypeError: t is not a function.
File including, excluding dependencies.

**Comment by fancyapps** [comment]
Sorry, there is currently no built in support for amd, commonjs, node.js, [name any next most awesome thing here], ...

**Comment by rorc** [comment]
@fancyapps 😭
When will? 😃

**Comment by chpio** [comment]
you could try using [this deprecated (but working) fork](https://www.npmjs.com/package/fancybox)
