### ISSUE TITLE
Problem with "back-button"

### ISSUE THREAD

**Issue by Thor111** [fancyapps/fancybox#1374]
Hi, there is a problem ... when i use the fancybox 3, and look the images... after that, i click the button "back", i don't come to the page before, i come to the images.... 

The button is a Javascript, history back...

Is this a problem with the new version?

TY for help. Greetings Thorsten

**Comment by Thor111** [comment]
Ah, now i read #1322 ... where can i resolve that problem?

**Comment by Thor111** [comment]
sry for my english, i am from Germany... ;-)

**Comment by fancyapps** [comment]
Hi,

Either disable hash module or wait for new version where this will be a bit updated.
