### ISSUE TITLE
Possible to get access to clicked element onInit

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1375]
With `onComplete` I can use `slide.ops.$orig` to get info about the clicked element, but slide doesn't seem to be available for `onInit`.

Is there any way to get the clicked element to be used in the `onInit` event?

**Comment by fancyapps** [comment]
Hi, Something like this

```JS
$('[data-fancybox]').fancybox({
  onInit: function( instance ) {
    
    // Group objects
    console.info( instance.group );
    
    // Start index
    console.info( instance.currIndex );
    
    // Clicked element 
    console.info( instance.group[ instance.currIndex ].opts.$orig );
  
  }
});
```

http://codepen.io/fancyapps/pen/aWObzj?editors=1010
