### ISSUE TITLE
Fancybox 3.0.47 weird glitch on iPhone in portrait orientation

### ISSUE THREAD

**Issue by fabelmik** [fancyapps/fancybox#1377]
I have also reported this problem on stackoverflow.com:
https://stackoverflow.com/questions/43450951/fancybox-3-0-47-weird-glitch-on-iphone-in-portrait-orientation

When you scroll to bottom of page on iPhone in portrait orientation the bottom iOS browser toolbar appears, and that seems to mess with the operations of fancybox.

I have a page with a list of products, and each product image is set up with fancybox. Initially when clicking on a product image the fancybox modal popup shows correctly, but when I scroll to bottom of page and the iOS browser toolbar appears, then when I click on product image the fancybox opens and quickly goes to background. If I then swipe the image appears quickly and closes.

I have recorded a short video demonstrating this weird behavior. Watch the video here: https://www.genius-webdesign.com/images/weird-fancybox.ios-glitch.mp4

Does anyone know what is causing this, and how to solve the problem?

**Comment by fabelmik** [comment]
Hi,
sure, but i would prefer not to give it here in public, because it is a dev. site.
Can I send you the link as PM ?

**Comment by fancyapps** [comment]
Sure, you can DM on Twitter or send an email.

**Comment by fabelmik** [comment]
Thank you. I´ve sent you a direct message on Twitter.

**Comment by fancyapps** [comment]
Try to implement fancyBox in a correct way.
