### ISSUE TITLE
Is event delegation possible with fancybox

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1378]
I'm not sure if this is the correct terminology, but is it possible to use fancybox on elements that are not  yet on the page when it loads? 

For example I have something like this:

```
$('.test').fancybox({
  infobar: false 
})
```

When the page loads there are no elements that match but then I have infinite scrolling which later adds elements that match as the user scrolls down.

**Comment by fancyapps** [comment]
Hi,

1) "Live" works out of the box if you are using "data-fancybox" attribute - http://codepen.io/fancyapps/pen/oBrMwN

2) When you execute `$('.test').fancybox()`, you are simply attaching a default click handler to your selected elements and fancyBox is then started inside this click event. 
If you wish, you can create your own click handler:
    ``` JS
    $(document).on('click', '.test', function() {
      var $collection = $( '.test' );
  
      $.fancybox.open( $collection, {
        // Here goes group options
      }, $collection.index( this )  );
  
      return false;
    });
    ```
    http://codepen.io/fancyapps/pen/jyjpGz
