### ISSUE TITLE
Adds "fancybox-show-controls" and "fancybox-controls--canzoomOut"

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1383]
Hi,

I open fancyboxes in different ways, but when I open it with $.fancybox.open() it adds "fancybox-show-controls" and "fancybox-controls--canzoomOut". The latter one gives me problems. Can I turn those off without going into the source code?

I've tried hideControls: true but it didn't work.

This fixes it but is there a different way?

```
onComplete: function( instance, slide ) {
	$('.fancybox-container').removeClass('fancybox-show-controls fancybox-controls--canzoomIn fancybox-controls--canzoomOut fancybox-controls--canGrab');
}
```

Thank you!

**Comment by fancyapps** [comment]
Hi,

I`m right now working on v3.1 and I`m close to completion. Just today I am planning to finish everything related to layout. I will look into this issue, too.

**Comment by fancyapps** [comment]
FYI, v3.1 has been published and I think there should be no issue with those classnames. There is no option to turn them off, though.
