### ISSUE TITLE
Add options to on load fancybox3

### ISSUE THREAD

**Issue by sohrabzia** [fancyapps/fancybox#1385]
Hi,

I am opening fancybox on page load.
``
 $.fancybox.open($('[data-testPopup]'));
``

I want to add option to it, I added  separately but it is not working.

here are the options i want to add on page load fancybox

```
 $('[data-testPopup]').fancybox({
      slideShow :false,
      	fullScreen : false,
	thumbs     : false,
	closeBtn   : false,
	closeClickOutside : false,
	infobar : false,
	buttons : false,
	smallBtn : false,
	touch : false,
	keyboard : false
  });
```

**Comment by fancyapps** [comment]
Hi,

The easiest way probably would be to attach fancybox with your options, like in your second snippet, and then trigger click event on one of the elements:

`$('[data-testPopup]').eq(0).trigger('click');`

btw, looks like you want to disable all user interaction, sorry, I forgot to implement "modal" option and discovered it only recently when working on v3.1.

**Comment by sohrabzia** [comment]
Thank you sir, it is working now, can you please add this feature  (adding option on auto loading fancyboxes) in v3.1 please.

**Comment by Viggoleinen** [comment]
When using the suggested code below to open fancybox on page load, the "parent" page scrolls to top on iPhone when you close the popup. How can this be prevented?

`$('[data-testPopup]').eq(0).trigger('click');`

Details: On my site, users are redirected back one page upon submitting a form (automatically to the previous scrolling position). Once this is done, a fancypopup "success" message is shown using the code above. When they close this popup, the page auto scrolls to top when using an iPhone. They are not scrolled to the top when closing the fancypopup, if the popup is triggered the normal way (by clicking on a link).
