### ISSUE TITLE
How to disable outline on close

### ISSUE THREAD

**Issue by stefarossi** [fancyapps/fancybox#1386]
When closing fancybox 3, the element which triggered it shows the outline (that blue line which surrounds the element). How can I disable this behaviour?

Thanks.

**Comment by fancyapps** [comment]
Hi,

The script places focus back to the last active element. You can either use CSS to remove outline from focused element or wait for v3.1 where will be option to disable placing focus back.

**Comment by stefarossi** [comment]
I see. I didn't want to set `outline: 0` for accessibility reasons, but I'll do that for now. I'm looking forward to v3.1.

Thank you.

**Comment by fancyapps** [comment]
If you care for accessibility, then you do not want to disable it :) The purpose of outline is to improve accessibility so users would know what element is in focus :)

http://a11yproject.com/posts/never-remove-css-outlines/
