### ISSUE TITLE
CSS transform translate causing blurred images/text

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1389]
I'm wondering if you encountered or were aware of this issue. It is sometimes hard to notice. An example can be seen looking at your Product Quick View example on the main page. If you slowly resize the browser window you will see the text and image become blurry. The blur comes and goes as you resize. There are a couple questions on SO that mention this but there doesn't seem to be an answer that works.

https://stackoverflow.com/questions/42669491/css-translate-with-percentage-causes-blurred-image

https://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry

**Comment by fancyapps** [comment]
Hi,

This issue will be gone after v3.1 will be released, because the principle of sliding will be totally different.

**Comment by rrcdr** [comment]
Great, thanks for the update!

**Comment by fancyapps** [comment]
FYI, v3.1 has been published and it should work better now. You will probably see blurriness while animating, though.
