### ISSUE TITLE
IOS, gallery and below the pop-up window, white screen

### ISSUE THREAD

**Issue by makissm21** [fancyapps/fancybox#1390]
I use fancybox 3 on this page if I use the gallery, and below the button with the popup form, when I click on it the white window appears, what could be the problem?
Problem in iOS in different browsers
link to the page [http://oikumena.org/ekspeditsiya-1/](url)
Screen [http://shot.qip.ru/00QPGK-1mqQ2hHSI/](url) button on which I click

**Comment by fancyapps** [comment]
The problem is caused by this CSS rule

```CSS
html, body {
    overflow: hidden!important;
}
```

This causes the script to calculate scroll position incorrectly. So, either try to update your page without changing overflow of wait for fancyBox v3.1 where it will be positioned a bit differently.

**Comment by makissm21** [comment]
Why does it work on other pages, but not here?

**Comment by fancyapps** [comment]
I`m sorry, I do not have time right now to investigate your page. I`m now focused on finishing work on v3.1.

**Comment by fancyapps** [comment]
FYI, v3.1 has been published, try it out.
