### ISSUE TITLE
Feature multiple fancybox like facebook?

### ISSUE THREAD

**Issue by rorc** [fancyapps/fancybox#1391]

**Comment by fancyapps** [comment]
Hi, Multiple instances is a major feature of fancyBox v3. For example, see ajax demo from the homepage - ajax response contains links and clicking them opens new fancybox instance without closing the current one.

**Comment by rorc** [comment]
Hi) And i can create new instances infinite?)

**Comment by fancyapps** [comment]
I can not guaranteed infinite instances, but a reasonable number should work fine :)

**Comment by rorc** [comment]
Ok, thanks 😄
