### ISSUE TITLE
Fancybox3 scrolls down with tabs inside

### ISSUE THREAD

**Issue by perfilev** [fancyapps/fancybox#1392]
Hello!
Fancybox3 scrolls down after clicking on tabs with different height content.
Tinymce editor inside first tab initializing after fancbox appears if it matters.

![1](https://cloud.githubusercontent.com/assets/1576298/25306332/c1125f4c-2793-11e7-8f74-a363eeb4f207.png)
![2](https://cloud.githubusercontent.com/assets/1576298/25306334/c4d3b310-2793-11e7-804c-7d653adeed16.png)
![3](https://cloud.githubusercontent.com/assets/1576298/25306335/c702fac4-2793-11e7-8624-9938eaeb293d.png)

**Comment by fancyapps** [comment]
Hi,

I guess that "jumping/scrolling" is caused by focusing, try to set "focus: false".

Content size and position is not controlled by JavaScript, there are some CSS rules applied that leaves it up to the browser. Therefore I do not see that there is something in the code that needs to be fixed.

**Comment by perfilev** [comment]
Already tried.
Init string:
`    $("[data-fancybox]").fancybox({
        focus: false,
        ajax: {
            css: {
                width: '90%'
            }
        }
    });
`
![screencast 2017-04-22 20-19-59](https://cloud.githubusercontent.com/assets/1576298/25306611/3e515ada-2799-11e7-81db-8ff109b6339c.gif)

**Comment by fancyapps** [comment]
Are you using some script for tabs or some custom JavaScript code?

**Comment by perfilev** [comment]
Only jquery-ui tabs w/ standard options.

**Comment by fancyapps** [comment]
Are you using some script for tabs or some custom JavaScript code?

**Comment by fancyapps** [comment]
I made a quick demo and works fine - http://codepen.io/fancyapps/pen/pPbpgE?editors=1100

**Comment by perfilev** [comment]
Thanks for your time, Jānis!
Sorted out with it: script tried to smooth scroll to hash with tab name.
Fancybox FTW!
