### ISSUE TITLE
Thumbnails modules in 3.1

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1393]
@fancyapps Just curious whether you've made any improvements to the thumbnails module in the upcoming release. I'd mentioned some time back that I would like to have some callbacks to work with -- specifically, something like onOpen, onClose, and the ability to detect isOpen / isClosed.

This is mostly so that I can open or close the thumbnails programmatically when triggering other events, or so that I can have other events open or close the thumbnails to as needed.

**Comment by fancyapps** [comment]
Thanks for reminding, I`ll look into this.

**Comment by fancyapps** [comment]
Hi,

Wow, how quickly time passes. It is unbelievable how much time it takes to answer all emails.

Anyway, there are now `onThumbsShow` and `onThumbsHide` callbacks available, and this is how you can check if thumbs are open - `$.fancybox.getInstance().Thumbs.isVisible`.

**Comment by mjcampagna** [comment]
Brilliant! I'm traveling at the moment, but will be looking forward to getting hands-on with these when I'm back to work in a few days. Thanks, Janis!
