### ISSUE TITLE
Buttons not showing after AJAX request

### ISSUE THREAD

**Issue by perfilev** [fancyapps/fancybox#1394]
After updating page content with ajax request fancybox controls not showing again.
And I can't close large sized window by clicking outside too (the same issue here: https://github.com/fancyapps/fancybox/issues/1367). I know you working on it, just FYI.

Maybe it's because I'm closing fancybox with JS?

$(document).on('submit', '.ajax-content form', function (e) {
...
        $.ajax({
...
            success: function (response) {
                var $instance = $.fancybox.getInstance();
                $instance.close();
                ajaxUpdate();
...

Here is the demo:

![screencast 2017-04-24 09-24-58](https://cloud.githubusercontent.com/assets/1576298/25324890/0407f22e-28d1-11e7-9194-968167945052.gif)

**Comment by fancyapps** [comment]
I`m sorry, but I have no idea, I have updated the demo with close button - http://codepen.io/fancyapps/pen/pPbpgE - and it works as expected.

Controls are displayed when "updateControls" adds "fancybox-show-controls" class to container. And I do not see why it would not execute this.

So, since I can not see you page, I can only start guessing game - what console says, are there any messages? Is "fancybox-show-controls" applied to container? What options for fancyBox are you using? Maybe you have some CSS that might intefere?

**Comment by lenarx** [comment]
I have this problem too and i found the cause.
My ajax request contain css and js. Example (login form popup):
```
<link href="/assets/1d4a9368/authchoice.css" rel="stylesheet">
<div class="login_popup def_popup" id="login_popup">
<form id="login_form" class="login_form" action="/login/?fancybox=true" method="post">
<span class="or">Или</span>
<div class="form-group field-login-form-login required">
<input type="text" id="login-form-login" class="form-control" name="login-form[login]" placeholder="E-mail" autofocus="autofocus" tabindex="1" aria-required="true">
<div class="help-block"></div>
</div>
    <div class="form-inline">
        <div class="form-group field-login-form-password required">
<input type="password" id="login-form-password" class="form-control" name="login-form[password]" placeholder="Пароль" tabindex="2" aria-required="true">
</div>        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-sm" tabindex="3">Войти</button>        </div>
    </div>

    <span class="recovery-link"><a href="/user/forgot/">Забыли пароль?</a></span>


    </form>
    <div class="reg_link">
        Или <a class="popup ajax-window" href="/signup/" data-fancybox="1" data-src="/signup/" data-type="ajax" data-loop="0" data-smallbtn="1">зарегистрируйтесь</a>    </div>

<button data-fancybox-close="" class="fancybox-close-small"></button></div><script src="/assets/a3d6ed30/jquery.js"><button data-fancybox-close="" class="fancybox-close-small"></button></script>
<script src="/assets/23ac206b/yii.js"><button data-fancybox-close="" class="fancybox-close-small"></button></script>
<script src="/assets/1d4a9368/authchoice.js"><button data-fancybox-close="" class="fancybox-close-small"></button></script>
<script src="/assets/23ac206b/yii.activeForm.js"><button data-fancybox-close="" class="fancybox-close-small"></button></script>
<script type="text/javascript">$('#connect-widget').authchoice();
jQuery('#login_form').yiiActiveForm([{"id":"login-form-login","name":"login","container":".field-login-form-login","input":"#login-form-login","enableAjaxValidation":true,"validateOnChange":false,"validateOnBlur":false},{"id":"login-form-password","name":"password","container":".field-login-form-password","input":"#login-form-password","enableAjaxValidation":true,"validateOnChange":false,"validateOnBlur":false}], []);<button data-fancybox-close="" class="fancybox-close-small"></button></script>
```

The following line from core.js append closeBtnTpl to first inner html element (in my case it's link tag):
`slide.$content.find( '.fancybox-close-small' ).remove().end().eq(0).append( slide.opts.closeTpl );`

**Comment by fancyapps** [comment]
So, if you want to have automatically created small close button, then first element of your ajax response should be some wrapping element.
