### ISSUE TITLE
Add a class when item is zoomable

### ISSUE THREAD

**Issue by ivanmoralesv** [fancyapps/fancybox#1395]
I want to make a better zoom interface, hiding the header and thumbnails when the image is zoomed. But for achieve that, I need a class when the image is zoomable.

Actually there is a class "fancybox-controls--canzoomIn" but when is zoomed the class disappears. Something like adding an additional class "**fancybox-controls--canzoom**" for zoomable images that doesn't dissappears would be the solution.

Thanks in advance!

**Comment by fancyapps** [comment]
Hi, When I was working on v3, I was thinking about whether to add such class or not. Back then I decided that zoomIn/Out would be sufficient. But now for v3.1 I think I am going to add `fancybox-is-zoomable` and rename previously used classnames to `fancybox-is-zoomedIn` / `fancybox-is-zoomedOut`.

**Comment by fancyapps** [comment]
FYI, it has been implemented in v3.1. 

Actually, I would like to see what are your ideas about "better zoom interface". I`m planning to improve zooming API in v3.2 and I would like to know what could be improved even more to help customizing fancyBox.
