### ISSUE TITLE
Click on the overlay Android, iOS

### ISSUE THREAD

**Issue by alexgrimm87** [fancyapps/fancybox#1397]
Closing fancybox3 when clicking on the overlay on Android, iOS don't work

**Comment by fancyapps** [comment]
It is not supposed to close. But it will be possible in v3.1 to choose what to do when user clicks on content or outside.

**Comment by alexgrimm87** [comment]
In the fancybox2 when you click on the black semitransparent background the PopUp is closed

**Comment by fancyapps** [comment]
Yes, but nowadays people are used that on mobile devices (using apps like fb, twitter and other), one tap toggles interface and double tap zooms images.
