### ISSUE TITLE
Support in old browsers?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1398]
Hey!

Do you have any info on which browsers will work with FancyBox 3 and which are limited or not working at all?

I get some emails about the fancybox not opening from members. I've asked for browser versions but the only one I've gotten so far is Safari 7.0.5. I don't have an old machine or old browsers so I can't test it myself. It is very possible that it is something else in my code that is making the fancybox not open too.

Thanks

**Comment by fancyapps** [comment]
Hi,

I`m sorry, I`m not able to test on old versions of Safari, too. I think Safari 7.0.5 is sure old, but not that much and it should work. Any message from console would help to determine the cause of the problem.

The script should work fine on any browser that supports fixed positioning and CSS transitions.
