### ISSUE TITLE
PDF in iFrame not opening in Chrome 59

### ISSUE THREAD

**Issue by michael-nee** [fancyapps/fancybox#1403]
Getting a blank screen when opening up a PDF in Chrome 59.  Worked on 58.  Webpages work fine.

Tested in other browsers and working fine.

Seems to be an issue with Chrome:

https://productforums.google.com/forum/#!topic/chrome/71gBGe8rq5M

**Comment by fancyapps** [comment]
Hi,

Thanks, but that is why PDF support is not listed as "main feature" of fancyBox - it is just so unpredictable. You see, the script creates DOM structure, but the rendering is up to the browser.

And that is why there is a note "rendering depends on the client environment" next to the PDF example.
