### ISSUE TITLE
Hotkey for fullscreen is not working

### ISSUE THREAD

**Issue by bjarnef** [fancyapps/fancybox#1405]
I just had a look at the Fancybox 3 showcase image gallery here http://fancyapps.com/fancybox/3/ and noticed that the hotkey `Full screen (F)` not is working. `Close (Esc)`, `Slideshow (P)` and `Thumbnails (G)` hotkeys does work though.

Maybe also toggle the fullscreen icon, when the mode change like in PhotoSwipe plugin http://photoswipe.com and maybe an option to show the zoom in/out as a toolbar button.

It would also be great to be able to add custom buttons, e.g. for direct download of image or social share.

**Comment by fancyapps** [comment]
Hi, Thanks! This has been fixed in v3.1 - http://codepen.io/fancyapps/pen/LyNXqr 
You can find code here - https://github.com/fancyapps/fancybox/tree/3.1 - but documentation is in progress.

**Comment by fancyapps** [comment]
FYI, v3.1 has been released.

See this demo how to create custom button (from http://fancyapps.com/fancybox/3/docs/#faq) -
 https://codepen.io/fancyapps/pen/JJPYLL 

It is planned to improve API for zooming in v3.2 and to include an option to display zoom icons, too.
