### ISSUE TITLE
inconsistent behavior when initializing with js and initializing with data- attributes

### ISSUE THREAD

**Issue by seiyria** [fancyapps/fancybox#1408]
if you initialize with data-fancybox, you get all of the buttons and slider and etc. if you initialize by doing $('selector').fancybox() you don't get anything.

it's a bit frustrating to debug even though the defaults should supposedly work

**Comment by fancyapps** [comment]
Are you sure?

**Comment by seiyria** [comment]
For some reason I can't repro it in a jsfiddle, but when you call _run  here:
`$(document).on('click.fb-start', '[data-fancybox]', _run);`

this is not the same way fancybox is initialized so if I were to do `$(selector).fancybox()` it just calls init, but you have some extra logic:

`items = items.length ? items.filter( '[data-fancybox="' + value + '"]' ) : $( '[data-fancybox=' + value + ']' );`

this is the difference between the two ways of initializing it. so I'll have to do $.fancybox.open instead of $().fancybox()
