### ISSUE TITLE
Doesn't work with other plugin

### ISSUE THREAD

**Issue by metalized** [fancyapps/fancybox#1409]
Hi,

I want to use fancybox with owl carousel. But doesn't working. 

## Here is the code

><div class="vendor-big item">
                <div class="content">
                    <a href="https://res.cloudinary.com/xxxxxxx/image/upload/w_auto,c_pad,b_rgb:000,fl_lossy,f_auto,dpr_auto,ar_16:9/l_watermark-xxxxxxx,w_0.33,fl_relative,g_center/v{{version}}/{{public_id}}">
                        <img data-src="https://res.cloudinary.com/xxxxxxx/image/upload/w_auto,c_pad,b_rgb:000,fl_lossy,f_auto,dpr_auto,ar_16:9/l_watermark-xxxxxxx,w_0.33,fl_relative,g_center/v{{version}}/{{public_id}}"
                             class="cld-responsive gallery-cell-image"
                             data-fancybox="gallery"
                             alt="{{../this.vendor.name}}"/>
                    </a>
                </div>
            </div>

## Here is the result

![fancybox-error](https://cloud.githubusercontent.com/assets/1047572/25666238/9adff288-3028-11e7-8d1f-60f62593680f.PNG)

![fancybox-error-2](https://cloud.githubusercontent.com/assets/1047572/25666270/b272bea8-3028-11e7-8032-0d043a136bc2.PNG)

Thanks for help!

**Comment by fancyapps** [comment]
Looks like you have to add `data-type="image"` to your links.

**Comment by metalized** [comment]
@fancyapps thanks for your solution.
