### ISSUE TITLE
onComplete fires twice when gallery first opens.

### ISSUE THREAD

**Issue by bennyb** [fancyapps/fancybox#1410]
This only seems to be an issue on instances that's are passed an array of images rather then called on a selector.  
Example here:
https://jsfiddle.net/bennyb/fdsL6u8y/

**Comment by fancyapps** [comment]
Hi,

I recreated this using fancyBox v3.1 and it works fine - http://codepen.io/fancyapps/pen/pPrRGw

Yes, v3.1 is not released yet since documentation is not complete, but the code can be considered to be complete.

Just for your information, callbacks have been changed:

```
beforeMove -> beforeShow
onComplete -> afterShow
//afterMove    : removed
```

**Comment by bennyb** [comment]
Thats great. Thanks

**Comment by fancyapps** [comment]
FYI, v3.1 is now published.
