### ISSUE TITLE
Offset of a fervent transition by fancybox3.0.47

### ISSUE THREAD

**Issue by radddar** [fancyapps/fancybox#1411]
Hello,
The following simplified example shows a transition on an image.
    http://t.matic.free.fr/t1t/test07.html
A panel slides from the bottom on a height of 30% of the container with 2 buttons.
One clicks on the "test" button which calls a window fancybox inline.
On return, the image is placed in a shift of 30% of the container.
Strangely if you write 60% instead of 30% in my property css ".PANIMG-B" everything is fine.
I have searched a lot, without success.
Is this bug or a bad script on my part, please?

Here is the code:

```
<head>
    <title>Test</title>
    <meta charset="utf-8">
<!--=====================  FANCYBOX ====================-->
     <script src="js/jquery-3.2.0.min.js"></script>
	<link rel="stylesheet" type="text/css" href="css/jquery.fancybox.css">
	<script src="js/jquery.fancybox.min.js"></script>

<!--====================  My style ======================-->
	<style> 
/** contener for the picture **/
		.grid_IMG-1{
			width: 300px;
			position:relative;
			overflow:hidden;
			border:1px solid #000;
		}
/** IMAGE 100% + transition out **/
		.ZoomIMG{
			width:100%;
			transition:0.4s;
		}
/** PANO from bottom + transition out **/
		.PanoIMG-B{
			width:100%;
			position:absolute;
			text-align:center;
			height: 30%; 				/** !!## ISSUE ##!! **/
			margin-bottom:0px;
			bottom:-100px;
			opacity:0;
			background-color:rgba(69,63,16,0.7);
			transition:0.4s;
		}
/** transition in **/
	/** Picture **/
		.grid_IMG-1:hover .ZoomIMG {
			transform:scale(1.8);
			transition:1s;
		}
	/** PANO **/
		.grid_IMG-1:hover .PanoIMG-B {
			opacity:1;
			bottom:0px;
			transition:0.4s;
		}
/** LINK **/
		a{
			padding:0 1em;
			background:white
		}
	</style>
<!---------------------------------------------------------------------------->
</head>
<body>
	<div class="grid_IMG-1">
		<img class="ZoomIMG" src="http://lh4.ggpht.com/_fFi6sniUesA/S_WMlSMtSWI/AAAAAAAAFIM/fVEE_1s-qdM/s640/DSC00082.JPG">
		<div class="PanoIMG-B">
			<br><a href="">Reload</a>
			<a href="javascript:;" data-fancybox data-src="#test">Test</a>
		</div>
	</div>
<!--============ FancyBox Inline "test" =================-->
	<div style="display: none;" id="test">
		<div>Here is the test</div>
		<p> Please Close... <br>And the height from<br>.PanoIMG-B{height: 30%;}<br>stay after !!! <br><br> "Reload" to start again</p>
	</div>
<!---------------------------------------------------------------------------->
</body>
```

**Comment by fancyapps** [comment]
Hi,

Hard to tall what could cause this. Could you try this using v3.1 from https://github.com/fancyapps/fancybox/tree/3.1 ?

**Comment by radddar** [comment]
Thanks for your quick reply and your work on francybox.
V3.1 does not change anything. Alas.
  (Is this a beta or definitive version of 3.1, please?)

If I do not find the solution, I should change a lot of the design of my site. Long work.
If you find the reason for this problem, it would be appreciated.
thank you

**Comment by fancyapps** [comment]
Yes, this is final version. Upgrading should not be much problem, the main API difference is that callbacks have been changed a bit (they are like in v2 - beforeShow/afterShow replaces beforeMove/beforeMove/onComplete - because the script is not a simple slider anymore, but something hybrid) and in layout - "fancybox-slider-wrap"/"fancybox-slider" elements are replaced by "fancybox-stage" element.

The mechanism of toggling page scrollbar has been tweaked, maybe that caused the problem.
