### ISSUE TITLE
iOS scrolling PDF not working

### ISSUE THREAD

**Issue by eddiesprietsma** [fancyapps/fancybox#1412]
Hello,

When I have a PDF in the fancybox with multiple pages it doesn't scroll to the other page.
Any sollutions on this? Did I do something wrong?

With kind regards,

Eddie

**Comment by fancyapps** [comment]
Hi,

This seems to be an old issue of iOS - http://stackoverflow.com/questions/15854537/make-embedded-pdf-scrollable-in-ipad

If you really need to embed iframe for iOS, maybe try using pdf.js
