### ISSUE TITLE
upgrade to v3 with 'href' option?

### ISSUE THREAD

**Issue by JailhouseJoe** [fancyapps/fancybox#1414]
Hi

I used to create instances of fancybox in an angular directive and pass it the 'href' option when using v1.3.4. It doesnt look like this is available in fancybox 3 as its not listed in the API? I tried using straightforward html attributes on the tag but this is not playing nice as javascript is running before the document is rendered(which also wasnt happening in 1.3.4). I guess what im asking is what is the fancybox 3 equivalent of this code?

    	module.directive('fancybox', function(){
    		return {
    			restrict: 'A',

    			link: function(scope, element, attrs){
    				$(element).fancybox({  
    					enableEscapeButton: true,
    					centerOnScroll: true,
    					'href': '/Version/ProductMini/' + attrs.ngHref,
    					autoScale: false,
    					autoDimensions: true
    				});
    			}
    		}
    	});
Many thanks
Joe

**Comment by fancyapps** [comment]
Just check documentation - http://fancyapps.com/fancybox/3/docs/#api

It would be something like this:

```JS
$.fancybox.open({
	src  : '/Version/ProductMini/' + attrs.ngHref,
	type : 'inline'
});
```

**Comment by JailhouseJoe** [comment]
Hi, a speedy response! However I did mention in OP that ive already tried using straightforward attributes on the tag as you prescribe as solution. I guess there is no equivalent to the "href" option when intialising with js which is what i was looking for as ive scoured the api and tried many things. Thanks all the same.

**Comment by fancyapps** [comment]
Well, try using "src" option (I'm too lazy to test it right now, sorry 😄) or change logic of your code. You see, when you call ".fancybox()" method, it just adds click event to selected items. And what happens inside that click event - it just gets links and calls `$.fancybox.open()` where actual magic happens. So, in your case, I would probably do something like this:

```JS
	module.directive('fancybox', function(){
		return {
			restrict: 'A',

			link: function(scope, element, attrs){
				$(element).one('click', function() {
					fancybox.open({  
					    src   : '/Version/ProductMini/' + attrs.ngHref,
					    type : 'ajax',
					    opts : {}
					});
				});
			}
		}
	});
```

**Comment by JailhouseJoe** [comment]
well mr 'lazy' fancyapps ;-p i really appreciate the effort made to swiftly answer my query and your explanation went someway toward what i think is a viable solution. whether my modus operandi is the attribute or js call seems to make no difference to the fact that javascript which was previously running inline after the 1.3.4 fancybox loads (eg cloudzoom.QuickStart()) is now not running on v3. I have solved it by moving this code into an afterLoad function. I thank you once again for clarification on where the "black box" of the library lies which led me to unearth my solution.
