### ISSUE TITLE
Reposition navigation buttons

### ISSUE THREAD

**Issue by reformed** [fancyapps/fancybox#1415]
Is there a way to reposition the navigation buttons so that instead of absolute positioning at the top of the page, they can be positioned immediately above or below the slide, adjacent to the slide?

**Comment by fancyapps** [comment]
Hi,

Do you mean exactly as is in version 3.1 - http://codepen.io/fancyapps/pen/LyNXqr ?

**Comment by reformed** [comment]
Yes, thanks. When will 3.1 be released?

**Comment by fancyapps** [comment]
If you wish, you can already start using it - https://github.com/fancyapps/fancybox/tree/3.1 - or wait a bit when documentation will be ready and it will be "released".

**Comment by fancyapps** [comment]
FYI, v3.1 is now published.
