### ISSUE TITLE
Load Data with next and previous button with Ajax in WP

### ISSUE THREAD

**Issue by Taymiyyah89** [fancyapps/fancybox#1416]
Hi,

I have a ajax request in which the data for a item displayed in the fancy lightbox. Its works, but now i want to know if it possible to jump to next or previous post entry when one click on next or prev button. 

My idea was first that i close the lightbox when one clicked the next/prev button and then init again the function which fetch the modal. 

         $( '.project-load' ).on( 'click', function ( event ) {
                event.preventDefault();
                var $this = $( this );
                var getId = $this.closest( "[data-post-id], .project-entry-media" ).data( 'post-id' ),
                    id = getId;

                loadModal( getId );

            } );

            function loadModal( post_id ) {
                $.fancybox.open( {
                    type: 'ajax',
                    src: rpLocalize.ajaxUrl,
                    opts: {
                        ajax: {
                            settings: {
                                data: {
                                    action: 'rp_ajax_project_modal',
                                    id: post_id,
                                    nonce: rpLocalize.rpProjectModal.nonce,
                                }
                            }
                        },

                        onComplete: function () {

                            $( '.next-ajax' ).on( 'click', function ( event ) {
                                event.preventDefault();
                                var post_id = $( this ).data( 'post-id' );

                                 // Not Work
                                $.fancybox.cancel();
                                loadModal( post_id );

                            } );
                        }
                    }
                } );

Sry for my bad english.

**Comment by fancyapps** [comment]
Hi,

You could get reference to previous instance and close it immediately after opening a new one:

```JS
var previousInstance = $.fancybox.getInstance(); 

loadModal( post_id );

if ( previousInstance ) {
    previousInstance.close();
}
```

**Comment by Taymiyyah89** [comment]
Thanks. It worked perfect 👍
