### ISSUE TITLE
Creating space between slides

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1418]
If I change the size of the `.fancybox-stage` how can I modify the spacing between slides. In this example the slides appear to be touching. Is there a way to create a gap?

https://codepen.io/anon/pen/NjXqNg

**Comment by fancyapps** [comment]
Hi,

There was an option for that in v3.0, but now it is missing after big rewrite. The problem is how to combine dragging and sliding transition. I`ll try to figure out a solution.

**Comment by rrcdr** [comment]
ok thanks!

**Comment by fancyapps** [comment]
Hi,

`gutter` option (horizontal space between slides) is now back, upgrade to the latest.
