### ISSUE TITLE
autoplay on modal

### ISSUE THREAD

**Issue by yangkennyk** [fancyapps/fancybox#1419]
it would be nice to have an autoplay on mobile feature. I was going to use fancybox for the project but ended up needing to create my own simple modal + use youtube api to trigger playing a youtube video on mobile when modal is opened.

**Comment by fancyapps** [comment]
Hi,

If you want to open and play youtube video automatically, then why would you need lightbox/modal?

**Comment by yangkennyk** [comment]
the lightbox/modal would still be used for desktop.

here's a video of what I ended up making. it might make what I'm trying to say a little more clear.

https://drive.google.com/file/d/0B-O_vQNEYcdqRFdFMVFpdmJzRVE/view?usp=sharing

I feel as if it smooths the user experience on mobile just a little teeny bit more since it skips that second button press to play the video. 

Do you think there's no value in that? just curious.

**Comment by fancyapps** [comment]
Maybe some day, when media module will be rewritten, this will be implemented, too. Right now the script just parses links and creates iframe with appropriate source link. But to archive autoplay on mobile devices, the script would have to download youtube api and use that.
