### ISSUE TITLE
Safari overlay flicker bug?

### ISSUE THREAD

**Issue by beneklisefski** [fancyapps/fancyBox#142]
I'm using the latest version of fancybox for a photo gallery. When viewing in Safari 5.1.1 there is a very quick flash of background content where the overlay disappears. It happens when the first image has just finished opening, and then again when clicking between gallery items (flash shows just after animation completes).

Can't see the problem in Firefox, or Chrome.

In IE (testing in 7) Fancybox doesn't initiate at all. Links go directly to the large images.

Example: http://benekdesign.com/clients/findaband/profile.html

Click on any of the artist images at top to open slideshow.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
