### ISSUE TITLE
showOnStart doesn't appear to work no matter what I do

### ISSUE THREAD

**Issue by zachphillips** [fancyapps/fancybox#1420]
I've tried both:
```
    $('[data-fancybox="video"]').fancybox({
      thumbs : {
        showOnStart : true;
      }
    })
```

and `$.fancybox.defaults.thumbs = { showOnStart : true };`

**Comment by fancyapps** [comment]
Hi,

If you have upgraded to v3.1, then options have been changed a bit:

```JS
thumbs : {
        autoStart   : false,   // Display thumbnails on opening
        hideOnClose : true     // Hide thumbnail grid when closing animation starts
}
```

Option naming has been unified and now all modules have option `autoStart` (if available).

**Comment by zachphillips** [comment]
Thank you so much for the quick response, but sorry... That doesn't work either... I'm in 3.0.47. I went to 3.1.2 to try your other options and that didn't work either.

**Comment by fancyapps** [comment]
I do not see why they would not work, there are multiple demos using v3.0, for example - http://codepen.io/fancyapps/pen/vgRajd

Are you sure your links get selected by `$('[data-fancybox="video"]')` ?

**Comment by zachphillips** [comment]
You know what... I just deleted my script where I thought I was calling it, and it's loading anyway. Does fancybox grab things automatically now? And if so, how do I set its behaviors?

**Comment by fancyapps** [comment]
Yes, if you add `data-fancybox` to your links, then fancyBox will start automatically using default options.

btw, correct way to change some default sub-option would be like this:

`$.fancybox.defaults.thumbs.autoStart = true;` 

(or `showOnStart` if using v3.0)

**Comment by zachphillips** [comment]
Is it possible to pay you for some premium support? I'm having a lot of issues with the documentation and what I want to do I'm sure is pretty simple and could be handled with a ten minute call. Happy to pay well. It will save me a lot of time.

**Comment by fancyapps** [comment]
If that is not something complex, you can ask here anyway.

One year of premium support is included with any new "Extended Commercial license" license purchase.

**Comment by zachphillips** [comment]
Okay, well I went ahead and paid for extended commercial license just now anyway, because I really appreciate your help. Here's where I am: https://shortorder.co/home

<img width="1787" alt="screen shot 2017-05-09 at 11 24 06 am" src="https://cloud.githubusercontent.com/assets/636635/25858592/1cbf5700-34aa-11e7-8071-a57d400f2651.png">

And I want to be here:

<img width="1786" alt="screen shot 2017-05-09 at 11 25 58 am" src="https://cloud.githubusercontent.com/assets/636635/25858906/f5f426cc-34aa-11e7-874d-16993bed308d.png">

You'll notice I'm using the caption area for a cool thing already. I want the thumbnails to autoload at the bottom (and I'd love to be able to actually put a title on the thumbnails but that's not a dealbreaker).

I want to put a title above the video, put the title of the previous and next videos instead of x/9 and prev/next arrows, and some additional links below the video, all within the fancybox-content context.

I'm running 3.0.47, and I tried upgrading to 3.1.2 but it sort of broke everything... so I think I'm fine staying with 3.0 if it would be less work.

**Comment by fancyapps** [comment]
While your mockup might look simple for you, it is certainly not from coding view. The main concern is about sizing everything - do you want to have your video responsive? Does it have maximum width/height? What if additional content under video contains huge text, then what? - Should the content be scrollable or video should resize to tiny size? Same goes for small screens (mobile) - there would probably be no space to display everything.

**Comment by zachphillips** [comment]
The video already is set up responsive, and works well. On mobile I hide the caption below, but would show the content above and below, which is super small, like one small line of text.

**Comment by zachphillips** [comment]
Wow, I mean, that does do it, but I don't understand how it works... How does fancybox know about the `video-content` element?

It does appear to work though, that I could get my whole setup in here like this, and I could still do it programmatically, so that does work. Thank you.

**Comment by fancyapps** [comment]
In this demo, if the link has `href="#video-1"` then clicking it would open element having ID `video-1` (e.g., element `<div id="video-1" class="video-content">..<.div>`).

The only problem with this demo is that iframe height is hardcoded in CSS (`max-height: calc(100vh - 270px)`) and I found height just experimenting - I changed it until scrollbars disappeared.

**Comment by zachphillips** [comment]
Oh I actually really like this also because it means I can custom name the targets. I have the video height solved on my end. Any thoughts on the previous/next idea?

**Comment by fancyapps** [comment]
It is actually quite simple: just use callback to get next/previous gallery items and create links inside infobar.

```JS
$('[data-fancybox="video"]').fancybox({
  smallBtn : false,
  infobar  : true,
  arrows   : false,
  margin   : 0,
  thumbs   : {
    autoStart : true
  },
  beforeShow : function(instance, current) {
    var prev = instance.group[ current.index - 1];
    var next = instance.group[ current.index + 1];
    
    // Remove any previously created link
    $("#video-link-left, #video-link-right").remove();
    
    if ( prev ) {
      instance.$refs.infobar.prepend(
        '<a data-fancybox-prev href="" id="video-link-left">' + prev.opts.$orig.attr('title') + '</a>'
      );
    }
    
    if ( next ) {
      instance.$refs.infobar.append(
        '<a data-fancybox-next href="" id="video-link-right">' + next.opts.$orig.attr('title') + '</a>'
      );
    }
    
  }
});
```

I have updated the demo - http://codepen.io/anon/pen/bWLVrj
