### ISSUE TITLE
Documentation is unclear on how to set HTML with options

### ISSUE THREAD

**Issue by brendon** [fancyapps/fancybox#1421]
I struggled a bit to find out how to show a fancybox with html content and options. Eventually I saw this: https://github.com/fancyapps/fancybox/blob/3.0/src/js/core.js#L371 and that gave me the clue that I should be using the `content` key and not the `src` key. This could probably be clarified in the last example of Core Methods in the documentation site.

**Comment by fancyapps** [comment]
Hi,

Thanks, I`ll add some additional description. 

Actually, opening HTML content is the simplest that can be:

```JS
$.fancybox.open('<div><h2>Hi!</h2><p>This is some content</p></div>', {
    touch : false
});
```

**Comment by brendon** [comment]
Ah that's interesting. I thought I tried something like that. I probably didn't do it right since I tried again now and it works a treat :)

Thanks for that!
