### ISSUE TITLE
Option to stay at the exact position after touch / drag

### ISSUE THREAD

**Issue by skowie** [fancyapps/fancybox#1422]
Hi there!

After dragging a zoomed image and releasing the mouse or finger the image moves a little bit further in the direction it was dragged. While this is cool when doing quick gestures (like flicking), it's not good if you dragged the image to an exact location you wanted it to stay in.

I'd like to remove this function for a project. I dug through the JS and tried some changes but it didn't work :(

**Where can I change this behaviour? Is it possible to have an option for that?** Thank you.

PS: Thanks for making this great script!
(I'm pretty new to GitHub and this stuff, so please excuse and tell me if I did something wrong.)

**Comment by fancyapps** [comment]
Hi,

The latest commit adds new option `touch.momentum` that can be used to disable continues movement.

btw, you can use defaults to change this option, too:

`$.fancybox.defaults.touch.momentum = false;`
