### ISSUE TITLE
How to ignore mouse slide?

### ISSUE THREAD

**Issue by nicdnepr** [fancyapps/fancybox#1423]
I use latest fancybox with image slider/carousel
When user slides the image fancybox catch a click and opens
How can I catch only single clicks with fancybox and ignore clicks with slides?

**Comment by fancyapps** [comment]
Sorry, I do not understand you, what is "mouse slide", "clicks with slides"? What do you mean by "user slides the image fancybox catch a click and opens"?

**Comment by nicdnepr** [comment]
mouse slide- user press button, then move mouse left\right,then release button
When user release button after slide fancybox  appears

**Comment by Meliorik** [comment]
Hello!
The same problem with SlickSlider. If slide images in slider, fancybox3 opens a large picture. Fancybox2 not have this problem.

**Comment by fancyapps** [comment]
So, you are talking about "dragging", right? 

When you call `$('selector').fancybox();`, the script adds `click` event that calls `$.fancybox.open()` when user clicks on selected elements. So, it should not start when dragging. 

Can you show some example demonstrating your issue?

**Comment by nicdnepr** [comment]
yes it's like "dragging" but nothing drags
here is site with example- modern-hostel.com/golitsyno, need to scroll down and there will be image gallery
the problem apeears if user release button inside image, if release outside fancybox not appear

**Comment by fancyapps** [comment]
I actually have no idea why this would work with v2, because they work basically the same.

Also, I believe this is not problem of fancyBox. If user drags slider, then it makes no sense to trigger click event after releasing.

**Comment by Meliorik** [comment]
For example,
http://gray-inn.ru/fancybox2/
http://gray-inn.ru/fancybox3/
Only fancybox3 script has changed, but when dragging slider a large picture opens.

**Comment by fancyapps** [comment]
@Meliorik Thanks for the demos! I`ll try to figure out something about this.

**Comment by nicdnepr** [comment]
@Meliorik I tried fancybox2 but still fancybox appear after stop gradding

**Comment by nicdnepr** [comment]
I use Swiper

**Comment by fancyapps** [comment]
@Meliorik I looked at your examples, compared source code of v3 and v2, checked source code of Slick carousel and everything seemed fine. So I created a quick demo - http://codepen.io/fancyapps/pen/gWvorB - and it works fine. 

Slick carousel works exactly as I had imagined - it checks dragged distance and if it is larger than some value, then it prevents click event. And therefore opening of fancyBox is not triggered when swiping.

**Comment by fancyapps** [comment]
Same goes for Swiper - http://codepen.io/fancyapps/pen/eWVyVg - I do not see any issue.

**Comment by Meliorik** [comment]
@fancyapps I'm sorry, but I did not understand how you solved the problem? ))

**Comment by fancyapps** [comment]
So, basically, I do not know what could cause problem for you. Maybe you are using old version of jQuery and/or carousel? Maybe try changing order of scripts? Maybe try upgrading to fancyBox v3.1? I really do not know what else to add...

**Comment by Meliorik** [comment]
@fancyapps http://codepen.io/Meliorik/pen/EmQQPR
I added the initialization with options and fancybox3 began to open large images when slide.
Without JavaScript initialization (as your example) fancybox3 works fine.

**Comment by fancyapps** [comment]
OK, I debugged Slick carousel source code and I figured out what causes this problem. Turns out that Slick listens for click events on wrapping element and therefore it can not stop click events from within slides. 

And now I understand why it works with v2 (and only partly with v3), because v2 uses delegated events - they can be canceled from parent element.

I remember I removed that option due to fact that it caused trouble for some people, but looks like it needs be brought back.

**Comment by Meliorik** [comment]
can add item in options for enable delegated events...
@fancyapps, thank you for greater work! I'll wait next version fancybox...

**Comment by fancyapps** [comment]
Too bad that `.selector` has been removed from jQuery since 3.0 - https://api.jquery.com/selector/

Therefore it is no more possible to make it work automatically and you have to pass `selector` by yourself:

```JS
$().fancybox({
  selector : '[data-fancybox="images"]',
  thumbs   : false
});
```

http://codepen.io/fancyapps/pen/gWvorB
