### ISSUE TITLE
【fancybox 3】BACK and FOWARD botton in the browser do not navigate the web page back or foward

### ISSUE THREAD

**Issue by syshut** [fancyapps/fancybox#1424]
I zoomed in the picture and zoomed it out, then click the browser's BACK button to go back, but the web page did NOT go back, instead the picture zoomed in again.

It will only happen when the picture is in a group ( value of "data-fancybox" attribute is not empty ).

This would not happen over fancybox 2.

**Comment by syshut** [comment]
http://fancyapps.com/fancybox/3/
You can test it on this official page.

**Comment by fancyapps** [comment]
Of course, that this did not happen with fancyBox v2, because "hash" module is added only recently.

So, either disable hash module or upgrade to v3.1 (will be published shortly; you can get it here - https://github.com/fancyapps/fancybox/tree/3.1)
