### ISSUE TITLE
Mistakenly opened an iframe fancybox?

### ISSUE THREAD

**Issue by vincent-cm** [fancyapps/fancybox#1425]
<div style=" height: 100px;">
                  <a class="" data-fancybox="hello" rel="hello" href="{{url}}">
                    <img src="{{url}}"
                         style="width: auto; height: auto;max-width: 100px;max-height: 100px"/>
                  </a>
</div>

Then the fancybox came wrapped with an iframe which is not expected and the image is not vertically and horizontally aligned:

![screen shot 2017-05-10 at 10 50 10 am](https://cloud.githubusercontent.com/assets/22391049/25893129/88415626-356e-11e7-9a9b-0b9a2d762c13.png)

![screen shot 2017-05-10 at 10 50 25 am](https://cloud.githubusercontent.com/assets/22391049/25893187/cb6508da-356e-11e7-8054-38662e3ae6d7.png)

**Comment by fancyapps** [comment]
Hi,

When script fails to detect content type from url, it uses iframe as fallback (because you can open anything inside iframe). You can add `data-type="image"` to mark your link as an image.
