### ISSUE TITLE
fullscreen HTML5 video and closing button 

### ISSUE THREAD

**Issue by dekar91** [fancyapps/fancybox#1426]
Hi!

I try to display html5 video inside fancybox.
I use this piece of html;
```
    <a id="general-trailer" class="js-fb-video" >Show </a>

    <div style="display:none">
        <video vidth="100%" height="100%" controls id="trailer" src="<?= $model->getFirstTrailer() ?>" poster="<?= $model->getFirstTrailerPoster() ?>"></video>
    </div>
```

and js:

```
            $.fancybox.open({
                src  : '#trailer',
              type : 'inline',
                opts : {
                  smallBtn   : true,
                  fullscreen:false,
                  closeBtn   : true,

                    onComplete : function() {
                        $('#trailer').get(0).play();
                    }

                }
            });
```

It result we can see following:
http://joxi.net/bmo0PB0C6Y1P2y

My question is:
How to coerce fancybox to place close button inside white space, how it was is version 1?
What is correct way to get fullscreen button work properly with video, or hide it ?

Thank you.

**Comment by fancyapps** [comment]
Hi,

You just have to display some element containing video and not video element itself - http://codepen.io/anon/pen/ybvxmM?editors=1010

What do you mean by "get fullscreen button work properly with video", e.g., what is not working properly now?

**Comment by dekar91** [comment]
Thank you.

It seems better, but now I see two closing cross - one in the right corner of modal window and the other at the right corner of the browser tab. I just copy your example in my project.

How to solve this?

What I said about fullscreen button I mean it would be great if fancybox modal button could control fullscreen of video tag.

**Comment by fancyapps** [comment]
1) Probably because that example uses v3.1 (https://github.com/fancyapps/fancybox/tree/3.1)

2) You could rebind click event of that button to what you want. But do you really want that? And do you really want to display only full-screen button in top-right corner? I think it would look weird.

**Comment by dekar91** [comment]
Thank you once more.

When I updated to 3.1 the code started work exactly how I need.
Have a nice day!
