### ISSUE TITLE
fancybox 3, does not work swipe on inline elements

### ISSUE THREAD

**Issue by Nordstyle** [fancyapps/fancybox#1428]
Only the first slide on the desktop works. How can I solve this problem? Maybe I do not use any options? 
Example posted here http://cn57945.tmweb.ru/ , section our projects. 
help me please someone :(

**Comment by fancyapps** [comment]
Hi,

Try upgrading to v3.1, it should work fine, see this demo - http://codepen.io/anon/pen/KmZxyM?editors=1010

**Comment by Nordstyle** [comment]
Where can i download 3.1? The official site only version v3.0.47. Or is that it?

**Comment by Nordstyle** [comment]
I understood what the problem is. If the inline element has a height greater than the user's screen height then the swipe breaks down

**Comment by fancyapps** [comment]
You can get code from GitHub - https://github.com/fancyapps/fancybox/tree/3.1
