### ISSUE TITLE
fancybox 3.1 does not support jquery 1.12.4

### ISSUE THREAD

**Issue by syshut** [fancyapps/fancybox#1429]
Is fancybox 3.1 designed like this?

**Comment by fancyapps** [comment]
Works fine for me. Even using jQuery v1.9.1

**Comment by syshut** [comment]
I mean i cannot change the option like this:
$('[data-fancybox="images"]').fancybox({
    touch : {
        vertical : false
    },
    transitionEffect : "slide",
});
There is no effect.

**Comment by fancyapps** [comment]
http://codepen.io/anon/pen/ybKVoo - works fine for me

btw, to be honest, I`m a bit tired creating a demo for each "issue", could you, please, next time create some example clearly demonstrating your issue?

**Comment by syshut** [comment]
@fancyapps 
I'm sorry for that, but just before I opened this issue, i've exported this code:
 http://codepen.io/anon/pen/KmZxyM?editors=1010
and replaced the jquery library 3 with 1.12. After that I opened this issue.
Thanks very much, I'll test it again.

**Comment by fancyapps** [comment]
I updated that demo with jQuery v1.12.4 and it just works. Maybe you did not update link correctly.

Also, each time something goes wrong, check developer tools first. The console should give you some clue what causes the issue.
