### ISSUE TITLE
Callbacks for Next and Prev ?

### ISSUE THREAD

**Issue by andyscott12** [fancyapps/fancybox#143]
Hi,

Wondering how you can bind arrow keys in fancybox as there is no callbacks ?

i.e. was hoping to run a function on "Next" and "Prev" however there aren't any callbacks for these ?

At the moment I am just using

```
$('.fancybox-item').click(function () {
//blah
});
```

But this only binds a click and not for keypress left and right ?

**Comment by VuongTran21** [comment]
Hello everyone: I have problem with Fancybox. Now I want to change next and previous button to my next and previous button, how do I do ?
