### ISSUE TITLE
Infinite loop always starts at first photo

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1431]
I noticed that if I set `loop : true` then no matter which photo I click, fancybox always starts at the first photo. Is this intended? Any way to prevent this behavior?

**Comment by fancyapps** [comment]
Thanks for reporting. Looks like a regression from one of previous commits.

**Comment by fancyapps** [comment]
Seems to be working fine - https://codepen.io/anon/pen/EmEeQZ?editors=1010
