### ISSUE TITLE
Clicking scrollbar causes fancybox to close

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1432]
Clicking the vertical scrollbar with fancybox active causes fancybox to close making the scrollbar unusable. Here is an example

https://codepen.io/anon/pen/PmRQOw

**Comment by fancyapps** [comment]
Wow, I never though someone would want to make whole page scrollable. I mean, you can have scrollable content, but there is no hack to check if clicked into container scroll area.

**Comment by rrcdr** [comment]
I had something similar working in 3.0

https://codepen.io/anon/pen/ybKjrO

Maybe I need to make some different changes to baseTpl?

**Comment by fancyapps** [comment]
Sorry, this seems to be regression, just like other issue you posted (I`m still working on it). Sorry about that.

**Comment by rrcdr** [comment]
No worries at all. Your quick responses are awesome! Thanks for the excellent plugin!

**Comment by fancyapps** [comment]
Should work fine now.
