### ISSUE TITLE
iframe example for loading a PDF does not work

### ISSUE THREAD

**Issue by robbiegod** [fancyapps/fancybox#1433]
I'm using Chrome.  I go to http://fancyapps.com/fancybox/3/docs/#iframe and click View demo on Codepen.  That link takes me here: http://codepen.io/fancyapps/pen/BpymvO?editors=1000

I click the SAMPLE PDF FILE text link.  I see the lightbox open, but it never loads the PDF.  I only see a white box with fullscreen and close buttons.

I tested in Edge and the PDF link worked so this must be an issue specific to Chrome.  I'm using Chrome v57.0.2987.133

**Comment by fancyapps** [comment]
Hi,

The problem with PDF is that fancyBox is not downloading, rendering or doing anything with the pdf file - your browser does that. 

If I remember correctly, Chrome v58 has some issues related to iframed PDF files.
