### ISSUE TITLE
Add text-align: center to .fancybox-button

### ISSUE THREAD

**Issue by brendon** [fancyapps/fancybox#1438]
If one is using an `<a>` to create a button in the toolbar (as per one of your FAQ's), and one is also using an icon set like fontawesome, the icon doesn't appear in the centre of the button because of the difference in `text-align` between `<a>` and `<button>`.

What do you think about adding `text-align: center;` to `.fancybox-button`?

**Comment by fancyapps** [comment]
Hi,

This is included in the latest commit (3.1 branch).

**Comment by brendon** [comment]
Thanks for that :)
