### ISSUE TITLE
slideShow false, but keyboard true?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1441]
Hey,

I want to be able to navigate between slides with the arrow keys, but not starting a slideshow with the space bar. Is that possible?

If I turn keybord to false it disables both the space bar and the arrow keys and slideShow set to false doesn't have any effect on the space bar.

Thanks!

**Comment by fancyapps** [comment]
Hi,

This is fixed in the last commit. Demo - http://codepen.io/anon/pen/vmzVor?editors=1010

**Comment by seabasss** [comment]
Great thanks!

It seems like the clickOutside: false is not working in this version. Is that called something else now?

Thanks!

**Comment by fancyapps** [comment]
@seabasss The problem with "clickOutside" was that it is ambiguous for layouts like this - http://codepen.io/fancyapps/pen/MmVEzQ 

Therefore a new option is available - "clickSlide".

**Comment by seabasss** [comment]
If I add clickOutside : false in your first link http://codepen.io/anon/pen/vmzVor?editors=1010 it doesn't work (same as is happening for me), but in the second link it works http://codepen.io/fancyapps/pen/MmVEzQ

What am I missing?

**Comment by fancyapps** [comment]
:) OK, I`ll try to explain.

clickOutside has no effect in the first link, because when you click outside the image, you actually click on the slide element, and you can swipe/pan here.

But on the 2nd link you clearly see the difference - clickOutside is called when you really click outside - on the dark area. But clickSlide - when you click on the left block (but not on the image, in that case would clickContent occur). Slide element is repositioned and has white background.

**Comment by seabasss** [comment]
Ok, got it thanks!

What was confusing to me was that I have this code and it doesn't look like a slide but I need slideClose for it to work.

```
	$("[data-fancybox]").fancybox({
		loop : false,
		opacity : 'auto',
		margin : [0, 0],
		gutter : 30,
		infobar : false,
		toolbar : false,
		slideShow  : false,
		fullScreen : false,
		thumbs     : false,
		closeBtn   : false,
		autoFocus  : false,
		smallBtn : false,
		clickOutside : false,
		clickSlide : false,
		touch : false,
		keyboard : false,
		beforeClose: function( instance, slide) {
			$(this).disposeVideo();
		}
	});
```

**Comment by fancyapps** [comment]
You want to close or not to close when clicked? Your code disables closing - http://codepen.io/anon/pen/vmzVor?editors=1010

**Comment by seabasss** [comment]
I don't want it to close. clickSlide : false fixed it! But since my code is only opening one thing it didn't seem like a slide to me hehe. Works now, thanks!

**Comment by fancyapps** [comment]
btw, if you want to have a real "modal" (no buttons, keyboard, click events, etc), you can simply set `modal:true`, see http://codepen.io/fancyapps/pen/NjXbXw #4

**Comment by seabasss** [comment]
Ah, that's neat, thank you! I have one more questions reg the modals but I'm opening a new issue for that! Thx again

**Comment by fancyapps** [comment]
@seabasss maybe you would be interested in using something like https://gitter.im/fancyapps/fancybox ? 

It is just I feel like I am already chatting with couple of people here on github issue comments and something like gitter.im/slack/whatever would help communicate faster.
