### ISSUE TITLE
showLoading() on fancyBox3

### ISSUE THREAD

**Issue by milhouse1337** [fancyapps/fancybox#1442]
Hi!

How can we show the spinner manually, I did this in fancyBox2 and it worked great:

`$.fancybox.showLoading();`

It's not working anymore and I even tried the following without success. Is there a workaround ?

`$.fancybox.getInstance().showLoading( $.fancybox.getInstance().current );`

Thank you!

**Comment by fancyapps** [comment]
Hi,

See this demo I recently created when someone asked for something similar - https://codepen.io/anon/pen/qmKRMe

Basically, you just have to call `showLoading` after initial loading is done:


```
afterShow : function(instance, current) {

    instance.showLoading( current );

    ...
}

```

Note: that demo uses v3.1 where callbacks have changed a bit, they are now actually similar to v2.
