### ISSUE TITLE
Swipe not working on mobile when vertical scrollbar is present

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1443]
I have `overflow-y: auto` on `.fancybox-container` and when the vertical scrollbar is present on mobile the swipe gestures do not work. I am using Nexus 5x with chrome.

Here is an example of my layout: https://codepen.io/anon/pen/PmRQOw

**Comment by fancyapps** [comment]
Basically, you are asking for dual-scrollable layout that would scroll image list and also the layout. 

I`ll look what I can do.

**Comment by rrcdr** [comment]
I just wanted to let you know it worked for me in 3.0

https://codepen.io/anon/pen/ybKjrO

But the custom layout was quite a bit different. I couldn't figure out any type of layout change in 3.1 that would fix it

**Comment by fancyapps** [comment]
It is because click/tap event listener is now on the whole container, so you can close modal clicking outside. And this new feature causes this new issue :) 

btw, do you really want ti have this layout? I think this would look better - http://codepen.io/fancyapps/pen/MmVEzQ or maybe http://codepen.io/fancyapps/pen/VbBvWN

**Comment by rrcdr** [comment]
I have a similar layout to your first example when the view is wide enough, but there isn't enough room when a user is viewing the page from a phone so I need to put the container below the fancybox gallery instead of beside it. I am certainly open to changing the layout, but I think it would still require putting the container below.

I thought of having only the container itself scrollable instead of the whole page so that the fancybox gallery is always visible, but I feel like it is a better experience for the user to be able to scroll the whole page, maybe I'm wrong. If it is not possible maybe I will have to just make the container scrollable.

Thanks very much.

**Comment by fancyapps** [comment]
Looks like I managed to solve this. Could you try this out?

**Comment by rrcdr** [comment]
Yes it works perfectly! Thanks so much for the time and effort and I also appreciate your input regarding mobile.

**Comment by fancyapps** [comment]
I hope the last commit improved this and did not break anything :) You see, I tried to make it so that it would be easy to build more complex layouts, like this - http://codepen.io/fancyapps/pen/ZKqaKO
