### ISSUE TITLE
Not working on IE "the requested content couldn't be loaded"

### ISSUE THREAD

**Issue by mttindustries** [fancyapps/fancybox#1444]
It worked fine on everything else but when I test it on IE 11 10 and edge I get the "the requested content couldn't be loaded. Please try again later" message. I don't understand. I've followed everything via the instructions. Even tested it with further data-types and setting the class to trigger the old fashioned why via javascript and still nothing.

```
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script src="assets/js/jquery.fancybox.min.js"></script>
<link href="assets/css/jquery.fancybox.min.css" rel="stylesheet" type="text/css">
```

```
<div class="gallery">
<div class="image"><a class="fancybox" data-fancybox="gallery" data-type="image" data-srcset="assets/image/kinder.jpg" href="assets/image/kinder.jpg"><img src="assets/image/kinder2.jpg" alt=""></a></div>
  <div class="image"><a data-fancybox="gallery" href="assets/image/kinder2.jpg"><img src="assets/image/kinder2.jpg" alt=""></a></div>
  <div class="image"><a data-fancybox="gallery" href="assets/image/kinder2.jpg"><img src="assets/image/kinder2.jpg" alt=""></a></div>
  <div class="image"><a data-fancybox="gallery" href="assets/image/kinder2.jpg"><img src="assets/image/kinder2.jpg" alt=""></a></div>
</div>
```

```
<script>
	$(document).ready(function() {

			// You can use as usual :
			 $( '.fancybox' ).fancybox();


			// or just create links having "data-fancybox" attribute

		});

</script>
```
![chrome](https://cloud.githubusercontent.com/assets/17806425/26194095/a99573ec-3bfa-11e7-9372-0b2146e034bb.jpg)
![ie](https://cloud.githubusercontent.com/assets/17806425/26194096/a99a8666-3bfa-11e7-95ff-bedcafaef9f9.jpg)

`

**Comment by fancyapps** [comment]
I do not know how to help you as you have not provided link to your page.

If you are developing locally and trying to display images from your computer, then you have to check your browser settings ( https://superuser.com/questions/676087/force-ie-to-open-local-files-in-the-intranet-zone-trusted-sites )

**Comment by mttindustries** [comment]
why would you close it before I can even respond. Yes I am running the page
locally. Yes I have checked those settings as you mentioned and no it's
still not working

**Comment by fancyapps** [comment]
There is nothing I can do to help you. Just install some webserver on your computer. Many features will not work if developing locally (ajax, video, etc) due to browser restrictions.
