### ISSUE TITLE
Multiple modal containers top aligned?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1445]
I love the modal function, but is there a way to top align all of them with css or in the js code? If I have 2 divs next to each other they both center vertically. It looks great with one, and sometimes even with two, but how can I get both of them to align at the top? If both of them can still be centered on the page based on the tallest of the two that's a bonus, but maybe that's very tricky? E.g. they're still top aligned to each other but centered on the page.

Please let me know if you want me to draw this out to clarify.

Thanks!

**Comment by fancyapps** [comment]
Could you show some demo with your current progress?

E.g., it is not clear, you are displaying a gallery of inline elements or just one that contains multiple child blocks that you want to align? If so, then just do the same you would do without using fancybox - if you can align them on the page, then you should be able to do inside fancybox..

**Comment by fancyapps** [comment]
I hope you managed to deal with your layout.
