### ISSUE TITLE
There is no way to toggle caption

### ISSUE THREAD

**Issue by grinfax** [fancyapps/fancybox#1446]
There is no way to toggle the caption. The Caption either always shows or is always hidden. Ideally there would be some functionality to allow the user to choose to show or hide the captions.

**Comment by fancyapps** [comment]
Hi,

Caption is toggled along with other interface elements when calling `toggleControls`:

`$.fancybox.getInstance().toggleControls();`

Similarly, there are `showControls` and `hideControls` methods.

If you want to show/hide only caption element, you can do simply:

`$.fancybox.getInstance().$refs.caption.toggle();`
