### ISSUE TITLE
Add thumbnail in the gallery when its an iframe slide

### ISSUE THREAD

**Issue by dbo90** [fancyapps/fancybox#1447]
Is there any way to specify a thumbnail for the gallery when its an "iframe slide"? I know there's no automatic way for fancybox to auto select a thumbnail for an "iframe slide" but is there an option for specify manually a thumbnail for it?

for example, if my 6th slide is an iframe page I would like to specify a thumbnail in the gallery for it:
<img width="1439" alt="2" src="https://cloud.githubusercontent.com/assets/1612229/26251457/f2db7952-3c72-11e7-94b6-8d61f1d4b787.png">

**Comment by fancyapps** [comment]
Hi, 

Add `data-thumb="link/to/thumb.jpg"` to your iframed link.
