### ISSUE TITLE
Class attribute API

### ISSUE THREAD

**Issue by iMerica** [fancyapps/fancybox#1448]
Hi,

I purchased a license to Fancybox, but it looks like I may not be able to use it. 

I need to achieve the lightbox effect by only adding a particular class to an `<img />` tag. Has anyone figured out a way to do this? The documentation only demonstrates how to use Fancybox by wrapping img elements in anchor tags like this:

```html
<a href="image.jpg" data-fancybox data-caption="My caption">
  <img src="thumbnail.jpg" alt="" />
</a>
```
In my case, I need to use fancybox like this:

```html
<img class="fancybox" src="thumbnail.jpg"  />
```

This way Fancybox can be a drop-in replacement to Materialbox in Materialize CSS.

**Comment by iMerica** [comment]
See materialize's materialbox: http://materializecss.com/media.html

```html
 <img class="materialboxed" width="650" src="images/sample-1.jpg">
```

```js
 $(document).ready(function(){
    $('.materialboxed').materialbox();
  });
```

**Comment by fancyapps** [comment]
There a few options.

1) You could, for example, use JS to add wrap each image in anchor.

2) If you do not care about zooming, then you can simply add `data-fancybox` and `data-src` attributes to your link - http://codepen.io/anon/pen/NjEqmE

3) If you want zooming, then you have to set starting point ($thumb) and you can do this by creating custom click event:

```JS
$('.fancybox').click(function() {
  $.fancybox.open({
    src    : this.src,
    $thumb : $(this)
  });
});
```

http://codepen.io/anon/pen/NjEqmE

**Comment by iMerica** [comment]
Very cool! 

I didn't know I could get it to work using only data attributes. I'll definitely go that route! I was trying to avoid too much DOM manipulation by surrounding each `<img>` with a `<a>`.
