### ISSUE TITLE
Mousedown and newest version

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1450]
Hey,

I'm running this code to hide divs that are "toggleable" inside of my ajax-fancyboxes. In the latest version of fancybox something in the code made it not work anymore. Ideas?

```
$(document).mousedown(function (e)
{
	if ($('.hidden-container').is(":visible") && !$('.dont-hide').is(":visible")) {
		var container = $(".parent-container");
		if (!container.is(e.target)
			&& container.has(e.target).length === 0)
		{
			container.find('.hidden-container').hide();
		}
	}
});
```

Edit // It seems to only work if I click on certain elements like span, input and em, but not div. Did you add something in the latest code that disables something if a div is clicked on?

**Comment by fancyapps** [comment]
Hi, 

The last commit should fix this.
