### ISSUE TITLE
Invalid URL scheme:

### ISSUE THREAD

**Issue by mdemblani** [fancyapps/fancybox#1452]
While developing locally, embedding a YouTube video, with the complete URL, the url scheme taken by fancy-box is that of the domain and not of the url provided, even though the url has the scheme: part present in it. For example, if I run my webpage at http://localhost, then the url for the youtube video used by fancy-box is http://youtube.com/video. But if I run my webpage using the file:// way, without a localserver, then the scheme taken by fancy box is of file:, i.e. the url used is file://youtube.com/video, although the original url provided is http://youtube.com/video.

**Comment by fancyapps** [comment]
Hi,

The actual url starts with "//", e.g., `//www.youtube.com/embed/qAx19EZ6-2w` 
I believe this is the best practice as it avoids issues when mixing http and https.

Anyway, you just have to use some webserver to properly develop locally. You will run into issues with ajax, IE, etc.
