### ISSUE TITLE
Possible to force hide the address bar on mobile when opening fancybox?

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1454]
My custom layout has a submit form at the bottom. Something like this - https://codepen.io/anon/pen/MmxjbY

The content in the fancybox-comments container below the fancybox-stage varies but when the container is empty the form should be aligned with the bottom of the visible screen.

The problem comes up if I open fancybox on mobile when the address bar is showing. The css I'm using with vh doesn't account for the size of the address bar and the form is pushed below what is visible despite the content being empty.

I'm wondering if there's a way to force hide the address bar when you open fancybox on mobile to prevent this problem.

**Comment by fancyapps** [comment]
Hi,

Check this post with latest updates -
https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html

Summary: this is made intentionally and therefore you probably should avoid using vh. 

I would suggest you to use css fixed position to place form at the bottom.
