### ISSUE TITLE
fancybox buttons position

### ISSUE THREAD

**Issue by rijosh** [fancyapps/fancybox#1458]
How can i move 'fancybox-buttons' inside the image popup 

![fancybox-issue](https://cloud.githubusercontent.com/assets/9720488/26629828/2fe9e8fa-4615-11e7-8be2-8eae23ddebc2.jpg)

**Comment by fancyapps** [comment]
Short answer - you can not.

Each image lives in own slide and, while you could use callbacks to move toolbar into image wrapper, it would look weird when swiping.
