### ISSUE TITLE
RegExp is not working properly for Base64 data:image

### ISSUE THREAD

**Issue by narekghazaryan** [fancyapps/fancybox#1460]
Your regular expression ( (^data:image\/[a-z0-9+\/=]*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg|ico)((\?|#).*)?$) ) does not match the subject string (data:image/png;base64,iVBOR ... etc) . I think we should add ";" to the "[a-z0-9+\/=]" and your RegExp should looks like  (^data:image\/[a-z0-9+\/=;]*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg|ico)((\?|#).*)?$) . 
P.S Why are you included "=" and "+" to "[a-z0-9+\/=]" and what is the metter ?

**Comment by fancyapps** [comment]
That regex has been around for years, since v2, I think.

Anyway, works fine for me - https://codepen.io/anon/pen/wewQgZ
