### ISSUE TITLE
Can't disable thumbnails in the toolbar with data-options

### ISSUE THREAD

**Issue by BA437** [fancyapps/fancybox#1461]
My apologies if this has already been solved, I couldn't find a solution for this. 

I wanted to disable the thumbnails option in the toolbar so I used
    `data-options='{"thumbs":"false"}'`
However, this doesn't work for some reason. I know the `data-options` attribute is working as I was able to disable the slideshow option successfully. 

For now, I've disabled the thumbnails with css but I would like to know why I can't disable thumbs with `data-options`.

**Comment by fancyapps** [comment]
Hi,

Looks like `"false"` needs to be without `"`, like this : `data-options='{"thumbs": false}'`

https://codepen.io/anon/pen/EXYMyZ

**Comment by BA437** [comment]
I'm sorry, but for some reason that doesn't work for me either. I tried that earlier and it just disables the slideshow option, the thumbnail option is still present.

**Comment by fancyapps** [comment]
Make sure you are using the latest version.

**Comment by BA437** [comment]
I checked, I'm using v3.0.47. I even replaced my jQuery with the latest version, it unfortunately made no difference.

**Comment by fancyapps** [comment]
By latest I mean from 3.1 branch :) 
(It will be published in upcoming days; you can get it here - https://github.com/fancyapps/fancybox/tree/3.1 )

**Comment by BA437** [comment]
Oh, I didn't even notice that there was a v3.1 branch. I just tried it out and it works! :+1: 

Thanks for the support and quick replies!
