### ISSUE TITLE
Custom closeTpl without fancybox-close-small class appends multiple buttons

### ISSUE THREAD

**Issue by rftb** [fancyapps/fancybox#1463]
Hey, love the revamped style of Fancybox, kudos!

I wanted to do a custom button style, so I removed the fancybox-close-small class from the button and added my own. But every time I close the fancybox and reopen without refreshing the page, it appends another button so I've got multiple buttons at a time. If I add the fancybox-close-small class back, it no longer appends multiple buttons.

Here's my init code for reference:
```javascript
$('[data-fancybox').fancybox({
    focus: false,
    closeTpl: '<button data-fancybox-close class="fancybox-close fancybox-close-small"></button>'
});
```

**Comment by fancyapps** [comment]
Hi,

I remember that this issue was reported and was fixed in 3.1 branch some time ago. 

v3.1 will be released in upcoming days, but you can preview it here - https://github.com/fancyapps/fancybox/tree/3.1

**Comment by rftb** [comment]
Oh sweet, thanks a ton!

**Comment by fancyapps** [comment]
FYI, v3.1 has been published, but I forgot to mention in changelog that `closeTpl` option is now `btnTpl.smallBtn`. Sorry about that.

Example:

```JS
$('[data-fancybox').fancybox({
    smallBtn : true,
    toolbar  : false,
    btnTpl   : {
      smallBtn : '<button data-fancybox-close="" class="fancybox-button fancybox-button--close" title="Close"></button>'
    }
});
```

Demo - https://codepen.io/anon/pen/KqdxoK
