### ISSUE TITLE
fancybox-wrap overflow change

### ISSUE THREAD

**Issue by flybeye** [fancyapps/fancybox#1465]
how do you change the overflow style element for the fancybox-wrap class in Fancybox v2.1.7 ?

the close button in the right hand top corner looks to be cut off by the overflow style.

**Comment by fancyapps** [comment]
Hi,

Sorry, v2.x is no longer supported.  It is recommend to upgrade to v3. These versions are not compatible, therefore it would be best to take a fresh start.

**Comment by lneveu** [comment]
Hi,

I've also experiment this bug. It's due to a bug from jQuery animate function... I've tried to fix it, but the only solution I foud was to add a custom class for the wrap element ("wrapCss" options) with "overflow" set to "visible !important".
