### ISSUE TITLE
Don't go idle if mouse hovering over arrow

### ISSUE THREAD

**Issue by ffolkes** [fancyapps/fancybox#1466]
Thank you for always providing such prompt replies to everyone. :)

I'm using the latest from the 3.1 branch, and I wanted to suggest that idle mode not be triggered if the mouse is still hovering over one of the arrows. If someone is clicking through, pauses to look, then clicks again just as idle mode kicks in, they will end up accidentally performing clickOutside.

**Comment by fancyapps** [comment]
Hi, Thanks for suggestion! I`ll look into this.

**Comment by fancyapps** [comment]
Navigation arrows are now hidden using opacity only, therefore user still can click on them when idling.
