### ISSUE TITLE
Use mouse scroll wheel optionally (up/down = prev/next)

### ISSUE THREAD

**Issue by ge0rgecz** [fancyapps/fancybox#1467]
Plase allow using scroll wheel to slide photos (up/down = prev/next). Its user friendly, and users expects this functionality.

**Comment by MattXcz** [comment]
+1

**Comment by rafaelduim** [comment]
+1

**Comment by webaschtl** [comment]
Yes, I am waiting for this feature, too :)

Last "update": https://twitter.com/thefancyapps/status/841532381504905216

**Comment by Eldenroot** [comment]
+1

**Comment by fancyapps** [comment]
Hello, everyone!

There has been recently added a basic mouse wheel support. Please, update to the latest code from the GitHub.

**Comment by webaschtl** [comment]
Thanks a lot!

**Comment by Eldenroot** [comment]
Working fine, can be closed :) @fancyapps
