### ISSUE TITLE
Stylize captions and fade/rotate transition

### ISSUE THREAD

**Issue by imza86** [fancyapps/fancybox#1469]
Hi this is my site http://www.noor-azmi.com/element/projects.html
 
Is there anyway i can stylize the captions?
Example in the first thumbnail project the caption is "The H Resort Beau Vallon - Mahe Seychelles" , I would like the "The H Resort Beau Vallon" to be bigger in size while "Mahe Seychelles" to be smaller font and below it in another line. Is that possible

2nd issue is the transition when changing image. Sorry but i am quite new to this so u need to tell me the exact thing that i need to do.

This is the JS in my page . pls say exactly what and where to write for the fade or rotate transition.
<script>    
                            $('[data-fancybox="project1"]').fancybox({
                            slideShow : {
                            autoStart : true,
                            preload: '40',
                            
                                         },
                           
                                });
                            
                        $('[data-fancybox="project2"]').fancybox({
                            slideShow : {
                            autoStart : true,
                            
                                         },
                            
                                });

Thanks

**Comment by imza86** [comment]
Hi, anyone can help me ? What exactly do i write to make the fade or rotate transition ? This is my exact code below

`<script>
                            
                            $.fancybox.defaults.loop = true;
                                        
                            $('[data-fancybox="project1"]').fancybox({
                            slideShow : {
                            autoStart : true,
                            preload: '40',
                             'cyclic': true,
                            
                                         },
                           
                                });
                            
                        $('[data-fancybox="project2"]').fancybox({
                            slideShow : {
                            autoStart : true,
                            
                                         },
                            
                                });
                        
                        $('[data-fancybox="project3"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                            
                        $('[data-fancybox="project4"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                            
                        $('[data-fancybox="project5"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                            
                                });
                            
                        $('[data-fancybox="project6"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                        
                        $('[data-fancybox="project7"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                            
                                });
                        
                        $('[data-fancybox="project8"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                            
                                });
                            
                        $('[data-fancybox="project9"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                            
                            </script>`

**Comment by fancyapps** [comment]
Try to indent your code properly to properly  see what have you written.
