### ISSUE TITLE
add/remove callbacks from an existing instance

### ISSUE THREAD

**Issue by dsheyp** [fancyapps/fancybox#1470]
Hi

Wouldn't it be nice beeing able to change e.g. the "beforeLoad" callback after an instance has been initialized? Something like:

```
var instance = $.fancybox.getInstance();
instance.off('beforeLoad', this.handleBeforeLoad, this);
instance.on('beforeLoad', that.handleBeforeLoad, that);
```

I just run into a usecase where it would make sense for me to keep the existing instance but modify the callbacks. Don't know if this is possible?

Thanks

**Comment by fancyapps** [comment]
You could simply set some flag indicating if you have processed something, you can freely create new instance variables, like:

```JS
$('[data-fancybox]').fancybox({
  beforeLoad: function( instance, slide ) {
    if ( !instance.done) {
      console.info( 'do something once!' )
    }
    instance.done = true;
  }
});
```

https://codepen.io/anon/pen/GEgbZM

But, if you really want to toggle callback, you could bind/unbind these global event handlers - 

```JS
$(document).on('beforeLoad.fb', function( e, instance, slide ) { });
```
