### ISSUE TITLE
Infinite loop image gallery 

### ISSUE THREAD

**Issue by imza86** [fancyapps/fancybox#1471]
This is my site [(http://www.noor-azmi.com/element/projects.html)]

Currently my image gallery is on autoplay, how do i make it not to stop on the last image but instead just keep playing and looping back,

Same goes for manual, if the user click on the nav arrow, it will not stop at last image. After last image, it goes back to 1st image. Thanks

**Comment by fancyapps** [comment]
Just set `loop: true`

**Comment by fancyapps** [comment]
You can, for example, update defaults, this will affect all future instances - 

`$.fancybox.defaults.loop = true;`

Or per instance -

```
$('[data-fancybox]').fancybox({
	loop : true
});
```

**Comment by imza86** [comment]
Thank you very much.
