### ISSUE TITLE
Change margins when mobile

### ISSUE THREAD

**Issue by ffolkes** [fancyapps/fancybox#1472]
Is it possible to change the value of 'margin' (the fancybox option) depending on whether or not a mobile device is viewing? I saw "// Custom options when mobile device is detected" but that appears to only be regarding clicks? I have a large margin for desktop viewing (to create a nice mat effect) but when viewing on a mobile device I'd like to set the margin to 0. Thank you. :)

**Comment by fancyapps** [comment]
Hi,

You can use `mobile` for any option, e.g,: `mobile : { margin : 0 }`

**Comment by ffolkes** [comment]
Thank you for the prompt reply. :) I am encountering a weird problem. When I put ANY margin setting in mobile { }, the thumbnails always disappear. For example:

Thumbnails appear fine:
$("[data-fancybox]").fancybox({
	margin : [100, 100],
	thumbs : {
		autoStart   : true,
		hideOnClose : true
	},
	mobile : {
	},
});

But with this thumbnails don't appear on desktop or mobile, even though in this test margin is set identically:
$("[data-fancybox]").fancybox({
	margin : [100, 100],
	thumbs : {
		autoStart   : true,
		hideOnClose : true
	},
	mobile : {
		margin : { 100, 100 },
	},
});

**Comment by fancyapps** [comment]
Well, thumbnails are hidden automatically if screen size is smaller than 800px. 
But this limitation will be removed in next release (in response feedback 😄 )

**Comment by ffolkes** [comment]
Thank you again for the reply. :) I understand that, but the problem I'm having is that thumbnails are going away even on my computer when margin is defined as anything (even 0) under mobile. Shouldn't the two examples above work identically when viewed on a computer?

**Comment by fancyapps** [comment]
I`m sorry, I can no longer follow you, could you show some demo/screens demonstrating your issue?

Could it be because of this syntax error - `margin : { 100, 100 }`, it should be an array, e.g, `margin : [ 100, 100 ]`

**Comment by ffolkes** [comment]
Ah, that was it! Perhaps I need some sleep. Sorry for wasting your time, and thank you so much for your patience! :)

**Comment by ffolkes** [comment]
Am I doing something wrong, or is it not possible to disable thumbnails on mobile?

mobile : {
	thumbs : {
		autoStart   : false,
	},
}

**Comment by fancyapps** [comment]
To disable any module, simply set, for example, `thumbs : false`.

btw, I am now thinking to redesign thumbnail module and display thumbs in one line at the bottom of the screen on small screens. Maybe as an option.

**Comment by ffolkes** [comment]
That would be cool to have as an option, I saw your example on codepen and it is what inspired me to use thumbnails, but I ended up using them on the side since many of my photos were portrait. Thank you for such a well designed tool. :)
