### ISSUE TITLE
Show marker on Google map

### ISSUE THREAD

**Issue by mikeebee** [fancyapps/fancybox#1474]
Hi!

Is it possible to also show a map marker when using the native Google Map Fancybox feature?

Cheers,
Mike

**Comment by fancyapps** [comment]
Hi, 

Looks like the script does not recognize links that include marker, I`ll try to update.

**Comment by mikeebee** [comment]
That would be awesome, thanks so much!

**Comment by sayedwasim** [comment]
Any idea when this can be fixed? 
Thank you so much.

**Comment by fancyapps** [comment]
Hi,

Sorry, I forgot to inform that this has been implemented for some time, see this demo - https://codepen.io/fancyapps/pen/pwzvvr?editors=1000

Basically, these link formats are supported:

```HTML

<a data-fancybox href="https://www.google.com/maps/search/Empire+State+Building/">Marker #1 </a>

<a data-fancybox href="https://www.google.com/maps/search/?api=1&query=centurylink+field">Marker #2</a>

<a data-fancybox href="https://www.google.com/maps/search/?api=1&query=47.5951518,-122.3316393">Marker #3</a>
```
