### ISSUE TITLE
Crazy Image Zooming in 3.1.20

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1476]
I was starting to work with 3.1.19 and all was fine. I just updated to 3.1.20, and images are suddenly going crazy. When I launch an image, it zooms in huge; click it, and it zooms out to thumbnail size.

**Comment by fancyapps** [comment]
Hi,

If you are using jQuery v3.1.1, then, please, upgrade to the latest (3.2.1). There seems to an issue with that jQuery version (works fine with older and newer versions).

**Comment by mjcampagna** [comment]
I was using 3.1.0. Just updated to 3.2.1 and all is well. Thanks!
