### ISSUE TITLE
Fancybox redirects to local files?

### ISSUE THREAD

**Issue by Elmcityescape** [fancyapps/fancybox#1477]
Trying to implment fancybox 3. 
testing with a youtube video and using the below
The frame loads but then can't access the video or image or whatever i throw there.
When i look at the chrome console it shows its looking for a local file?
```
<section data-sr id="video" class="video u-full-width featured-bg-image">
  <h4 class="centered">
    <a data-fancybox href="https://youtu.be/GfCL1VJ4WbQ" class="button inverted circle"> 
      <i class="fa fa-play"></i>
    </a>
  </h4>
</section>
```

**Comment by fancyapps** [comment]
Hi,

Your snippet works as expected - https://codepen.io/anon/pen/jwWoLW?editors=1000 

Maybe you are opening local file directly on your browser? 

`Some functionality (ajax, iframes, etc) will not work when you're opening local files on your computer, the code must be running on a web server `
