### ISSUE TITLE
backFocus option noch working

### ISSUE THREAD

**Issue by inware** [fancyapps/fancybox#1478]
it seems that the option backFocus is not working. on line 2475 it probably should be self.current.opts.backFocus instead of !!!self.current.focusBack. at least this solved the issue for me.

**Comment by fancyapps** [comment]
Hi,

Thanks, there indeed is naming mismatch.

**Comment by schnubb** [comment]
have you any plan when it will be fixed?

**Comment by fancyapps** [comment]
Should be fixed in v3.1.22

Sorry for delay. Test - https://codepen.io/anon/pen/EvGGxj
