### ISSUE TITLE
Fancybox Multiple Instance Bug

### ISSUE THREAD

**Issue by reramjiawan** [fancyapps/fancybox#1481]
Hello,

Fancybox has a bug which happens when you "spam click" a fancybox enabled image to which it will open a myriad of overlays.

Try here https://codepen.io/fancyapps/pen/WjVXyx?editors=1000

It would be nice to disable this functionality if required.

**Comment by fancyapps** [comment]
Hi,

Could you provide working url?

**Comment by reramjiawan** [comment]
Updated.

**Comment by fancyapps** [comment]
Sorry, I do not understand - where is the issue? What is "spam click"?

**Comment by reramjiawan** [comment]
Try here otherwise.

[https://s.codepen.io/boomerang/iFrameKey-8f461e19-06c7-6dbc-62ca-8ec7e44b6f98/index.html?editors=1000](url)

**Comment by fancyapps** [comment]
Links like that do not work, they are for your session only.

**Comment by reramjiawan** [comment]
Ah I did not know. If you could open the iframe that codepen loads in a seperate tab you will see the issue when you repeatedly and fast left click one of the images.

**Comment by fancyapps** [comment]
I guess you are either clicking unbelievably fast or your computer is slow, because after the click the overlay is created and next clicks should be on overlay (and not link).

**Comment by reramjiawan** [comment]
Doubleclick speed also causes it.

Is there a way to disable multiple instances?

**Comment by reramjiawan** [comment]
Either way it registers all the click events and fires them off on after another if the overlay event did not happen yet.

**Comment by reramjiawan** [comment]
I tested this also at home and at work same problem. In all browsers Chrome, Edge, Opera, Safari, IE, Firefox.

**Comment by reramjiawan** [comment]
`    // Default click handler for "fancyboxed" links
    // ============================================

    function _run( e ) {
        var target	= e.currentTarget,
            opts	= e.data ? e.data.options : {},
            items	= e.data ? e.data.items : [],
            value	= $(target).attr( 'data-fancybox' ) || '',
            index	= 0;

        e.preventDefault();
        e.stopPropagation();

        // Get all related items and find index for clicked one
        if ( value ) {
            items = items.length ? items.filter( '[data-fancybox="' + value + '"]' ) : $( '[data-fancybox="' + value + '"]' );
            index = items.index( target );

            // Sometimes current item can not be found
            // (for example, when slider clones items)
            if ( index < 0 ) {
                index = 0;
            }

        } else {
            items = [ target ];
        }

        $.fancybox.open( items, opts, index );
    }`

Maybe if you can store the currentTarget in an oldTarget variable and see if it has already been clicked before firing the $.fancybox.open(); function.

**Comment by reramjiawan** [comment]
I have fixed it and made a pull request for it thank you.
