### ISSUE TITLE
Saving photos to phone

### ISSUE THREAD

**Issue by emage** [fancyapps/fancybox#1483]
Is there a feature or plugin needed to be able to save fancybox gallery to phone?  For example - tap and hold to save /download image to phone.

**Comment by fancyapps** [comment]
Unfortunately, I am not sure if this is even possible.

**Comment by emage** [comment]
Since i have upgraded to the latest version, this custom download button no longer works.

code pen: https://codepen.io/Emage/pen/BgGdWo

I tried this FAQs: http://fancyapps.com/fancybox/3/docs/#faq-3
as well.

Am i missing something?

Thanks

**Comment by acwolff** [comment]
@emage  the download button works OK as you can see [here](https://andrewolff.jalbum.net/FB_JustifiedGallery/).

**Comment by emage** [comment]
@acwolff 
Can you share how you customized that download snippet? I'm using the FAQs but as you can see its not working.
BTW, i like how you setup tooltip on those icons too!

**Comment by acwolff** [comment]
@emage the download button in the [demo album](https://andrewolff.jalbum.net/FB_JustifiedGallery/) download the ligthbox image and uses standard fancyBox code.

As an option you can also download the original image, in which case I have added some extra code:

    $.fancybox.defaults.btnTpl.downloadOrg = '<a target="_blank" download=""  href="" id="downloadOrg" data-fancybox-downloadOrg class="fancybox-button fancybox-button--downloadOrg" title="Download original image">' +
     '<svg viewBox="0 0 40 40"><path d="M13,16 L20,23 L27,16 M20,7 L20,23 M10,24 L10,28 L30,28 L30,24" /></svg></a>';
 
     function initFancyBox() {
     $('[data-fancybox="S"]').fancybox({
     	idleTime: false,
    	onInit: function(instance) {
    	if (enableTaps) { 		
    		tippy('[title]', {
    			touchHold: true,
    			arrow: true,  // false gives problems
    			flipBehavior: ['top', 'left'], 
    			size: 'large',
    			duration: 500,
    			theme: 'user',
    			animation: 'scale',
          		appendTo : instance.$refs.container[0],
       			zIndex : 99999
        		});
    	};
        },
         beforeShow : function() {
    		slide_index= this.index ;
    		$('#downloadOrg').attr('href', srcOrgImg[slide_index]);
        },
	
        buttons : [
        ,'slideShow'
        ,'downloadOrg'
        ,'close'       
      ]
    }); 
    }

The tooltips are made with the [tippy.js library](https://github.com/atomiks/tippyjs); you see the initialization code above.

**Comment by emage** [comment]
@acwolff 
Thank you!
