### ISSUE TITLE
btnTpl not affecting .fancybox-close-small in inline modal

### ISSUE THREAD

**Issue by frshjb373** [fancyapps/fancybox#1484]
Trying to add an attribute for google analytics to the `.fancybox-close-small`. I have the following jQuery, but it's adding the toolbar buttons on upper right which I do not want:

```
jQuery('[data-fancybox="whitepaper"]').fancybox({
	smallBtn : true,
	toolbar : false,
	closeClickOutside: false,
    btnTpl : {
      smallBtn : '<button data-fancybox-close="" class="fancybox-button fancybox-button--close" title="Close"></button>'
    }
});
```

Screenshot:
<img width="643" alt="screen shot 2017-06-13 at 10 53 44 am" src="https://user-images.githubusercontent.com/7178139/27096820-321a01c0-5027-11e7-8c1d-c07f6b877eda.png">

Code outputting nothing in the small button inside popup:
`<button data-fancybox-close="" class="fancybox-close-small">×</button>`

**Comment by fancyapps** [comment]
Hi,

Your snippet works fine, just make sure you are using the latest from v3.1

See demo - https://codepen.io/anon/pen/VWjJvE

**Comment by frshjb373** [comment]
That fixed issue for adding attribute to button, however that broke `closeClickOutside: false` and now box is closing when clicked outside. Please advise.

**Comment by fancyapps** [comment]
@frshjb373 set `clickSlide: false`

**Comment by ali27001** [comment]
I have the problem, too. How did you solve it

**Comment by fancyapps** [comment]
@ali27001 What problem?

**Comment by ali27001** [comment]
![image](https://user-images.githubusercontent.com/34340185/40706024-331342a2-63f5-11e8-84ff-d36fcc7606ec.png)
close icon is not what I want

**Comment by fancyapps** [comment]
`buttons` option is what you need.

**Comment by ali27001** [comment]
![image](https://user-images.githubusercontent.com/34340185/40963129-42d992e4-68b0-11e8-99c3-9eecb4ff557b.png)
 I want you to look like this. Close the icon on the picture. not elsewhere

**Comment by fancyapps** [comment]
@ali27001 Then take a look at this demo - https://codepen.io/fancyapps/full/BrxwqO
