### ISSUE TITLE
Custom caption bug?

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1485]
I'm having an issue setting custom caption source with 3.1. I've checked documentation and have ended up with this function:

```javascript
		caption : function( instance, item ) {
			var caption;
			if ( item.type === 'image' ) {
				return $(this).closest('figure').find('figcaption').html();
			}
		},
```

The caption is properly displaying for images that have captions. The problem I am having, though, is that if I go from an image with caption, to an image without caption, then the first caption does not clear.

For clarity, I have this:

Image 01
Has caption

Image 02
Does not have caption

If I navigate from Image 01 to 02, I see this result:

Image 01
Image 01 Caption

Image 02
Image 01 Caption

I would expect Image 02 to be blank.

**Comment by fancyapps** [comment]
Hi,

I suspect that `$(this).closest('figure')` would find something even you do not expect :)
Also, I do not see an issue here - https://codepen.io/fancyapps/pen/bRbVaG?editors=1010

**Comment by mjcampagna** [comment]
Sorry, but that doesn't make sense to me. How then would I get the caption for the current item, if the figcaption element is not wrapped within the anchor?

**Comment by fancyapps** [comment]
Why did you choose to use `closest`? What html structure do you have? Your code would find closest `figcaption`, even from different element that is clicked.

**Comment by mjcampagna** [comment]
Abbreviated, my structure is this:

```html
<figure>
<a href="..." data-fancybox>
<img src="..." />
</a>
<figcaption></figcaption>
</figure>
```

Trying this function, the caption gets properly reported when empty. But if I "return false" or try to leave empty when there is no caption, then the previous caption is not cleared.

```javascript
		caption : function( instance, item ) {
			var caption;
			if ( item.type === 'image' ) {
				caption = $(this).closest('figure').find('figcaption');
				if ( caption.is(':empty') ) {
					return "I am empty";
				} else {
					return caption.html();
				}
			}
		},
```

**Comment by mjcampagna** [comment]
Looking at 3.0.47, I found this:

```javascript
            // Reveal or create new caption
            if ( $caption ) {
                $caption.empty();
            }

            if ( caption && caption.length ) {
                $caption.html( caption );
...
```

Version 3.1.x doesn't seem to have an equivalent action to empty the caption. Only this:

```javascript
            self.$caption = caption && caption.length ? $caption.html( caption ) : null;
```

**Comment by fancyapps** [comment]
I would choose different selector:

```JS
  caption : function( instance, item ) {
      return $(this).parent().find('figcaption').html();
  }
```

Seems to work fine  - https://codepen.io/anon/pen/vZXXmL?editors=1010

But your snippet works fine, too - https://codepen.io/anon/pen/PjGGJp?editors=1010

**Comment by mjcampagna** [comment]
I found this solves it, changing the 3.1 script from:

```javascript
            self.$caption = caption && caption.length ? $caption.html( caption ) : null;
```

To: 

```javascript
            if ( $caption ) { $caption.empty(); }
            self.$caption = caption && caption.length ? $caption.html( caption ) : null;
```

My actual HTML is a little more complicated than the abbreviated snippet above, due to having some extra markup inside the figure element for various thumbnail layouts and UI. I can't use .parent(). 

Still, the behavior I'm seeing on my side is different than the codepen. I'm not seeing any good explanation for it.

**Comment by mjcampagna** [comment]
This also works:

```javascript
            self.$caption = caption && caption.length ? $caption.html( caption ) : $caption.empty();
```

**Comment by fancyapps** [comment]
OK, now I got this. You see, there is a reason why caption is not emptied. Open any demo I previously gave and try navigating. You will see that caption nicely fades way when item does not have caption. If caption would be emptied, then it would just suddenly vanish.

**Comment by mjcampagna** [comment]
I've tried removing my custom styling. If I do that, then I get the intended behavior. 

For my implementation, though, the caption area is always visible.

So, in the current version, the situation seems to be that when the current slide has no caption, then the previous caption remains in place, but is hidden via CSS. Because my CSS doesn't hide the caption, the previous caption remains visible.

**Comment by mjcampagna** [comment]
Okay, I understand then the reason you're not emptying the caption. I wonder if there's some way we can have the best of both worlds? Maybe an option to empty the caption? Or perhaps I can empty the caption using callbacks?

**Comment by fancyapps** [comment]
Yes, you can do it manually using any callback and you can get reference to caption element like this - `instance.$refs.caption`.

**Comment by mjcampagna** [comment]
Cool. Adding "instance.$refs.caption.empty();" to the beforeShow callback seems to be solving it for me then.
