### ISSUE TITLE
Mouse dragging inside fancybox closes it

### ISSUE THREAD

**Issue by Iworb** [fancyapps/fancybox#1486]
I have a canvas inside fancybox (actually it's fabricjs canvas) and when I'm trying to move objects on a canvas vertically it closes the fancybox.
I've tried to set data-options like `{modal: true}` or `{touch:{vertical:false,momentum:false}}`, but there's no changes.
Here is the [fiddle](https://jsfiddle.net/xvvoertz/1/). Open a modal and try to drag red square to the bottom.

**Comment by nebrot** [comment]
data-options='{"touch": false}' works for me: https://jsfiddle.net/xvvoertz/2/

**Comment by Iworb** [comment]
True. Well, documentation options should be updated in this case, there is no word about `touch` option by itself could be set to `false`. It is represented as object.

**Comment by fancyapps** [comment]
@Iworb Documentation update is in progress, but 3rd example from "inline" example https://codepen.io/fancyapps/pen/NjXbXw?editors=1100 demonstrates this, too.
