### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by myTinCart** [fancyapps/fancybox#1487]
When using the slideshow feature (one "data-fancybox" attribute assigned to multiple images),  IE 11 has intermittent problems loading the lightbox large (destination) image.   Instead, when the image thumb is clicked, the lightbox only "lights up"  the image thumbnail instead of opening the destination image and enlarging that.   Closing the lightbox and then clicking the thumbnail a second time appears to correct it.

**Comment by fancyapps** [comment]
Works fine for me. Can you show an example demonstrating this issue?
