### ISSUE TITLE
afterClose event does not get triggered

### ISSUE THREAD

**Issue by michael-nee** [fancyapps/fancybox#1489]
The afterClose event is not working with my code.  beforeClose works fine but I need some code to run after closing an inline modal.

`$.fancybox.open({
                src: '#signature-container',
                type: 'inline',
                opts: {
                    afterClose: function () {
                        $('#signature-container').show();
                    },
                    "touch": true,
                    "smallBtn": false
                }
            });`

I'm just wanting to unhide a div after opening it inline.

**Comment by fancyapps** [comment]
Hi,

1) `afterClose` works;
2) your snippet works, too.

Demo - https://codepen.io/anon/pen/OgbgeP?editors=1010

btw, was it so hard for you to create a demo before creating an issue?
