### ISSUE TITLE
Disabling zoom-in

### ISSUE THREAD

**Issue by makarqa** [fancyapps/fancybox#1490]
I want to disable zoom-in for large images when they are already opened. 
I have seen Your answer in the issue #1355, but I can`t find this feature in docs. 
Thanks

**Comment by fancyapps** [comment]
Hi,

You can control what happens on click event using `clickContent` option - 


```
Possible values:
  "close"           - close instance
  "next"            - move to next gallery item
  "nextOrClose"     - move to next gallery item or close if gallery has only one item
  "toggleControls"  - show/hide controls
  "zoom"            - zoom image (if loaded successfully)
  false             - do nothing
```

**Comment by makarqa** [comment]
Thank You! Sorry for disturbing.
