### ISSUE TITLE
onComplete?

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1494]
Version 3.0.x has an onComplete callback; this appears to be missing in 3.1.

Is there an equivalent in the current version? Does afterShow cover this?

**Comment by fancyapps** [comment]
Hi,

Since the general idea of how content appears have changed, the previously used callbacks does not fit, therefore:

```
`beforeMove` -> renamed to `beforeShow`
`afterMove`  -> removed 
`onComplete` -> renamed to `afterShow`
```

**Comment by mjcampagna** [comment]
Perfect. Thanks!
