### ISSUE TITLE
Image is blurred during zoom animation

### ISSUE THREAD

**Issue by slashby** [fancyapps/fancybox#1495]
Hi

I found a bug. When open an image with high resolution on a desktop, image is blurred (Safari and FireFox browsers) till animation is completed. It appears for "zoom" animation effect. When animation is completed, the image looks normal. Demo: https://codepen.io/anon/pen/wegdaq (expand Codeine working area to see it).

**Comment by fancyapps** [comment]
Hi,

I wish there would be something I could do, I already have spent incredible amount of time on this. Zoom animation is now using CSS transform to scale. While this has good performance, the downside is that extremely large images are blurry on some browsers during animation. 

Waiting fro proper http://caniuse.com/#feat=web-animation support.
