### ISSUE TITLE
clickOutside vs. clickSlide

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1496]
I thought I might have a problem with clickOutside, but on further investigation, I think I'm just not understanding the context.

So there's content, the modal or image,etc. And that interaction is clickContent.

The "slide" seems to occupy the full viewport, cover all areas external to the content. That interaction is clickSlide.

So, when is it appropriate or useful to use clickOutside? Because the "outside" as I'm able to see it is actually the empty part of the slide.

Just curious. Thanks!

**Comment by fancyapps** [comment]
Hi,

This separation is needed when creating different layout, take a look at this demo - https://codepen.io/fancyapps/pen/ZKqaKO - how do you think, where would you have to click to trigger `clickOutside`?

So, here you can
 
- click on the image - `clickContent`
- on white space around image (e.g., slide) - `clickSlide`
- on the dark area - `clickOutside` 


I had hard time trying to figure out simple, unambiguous naming, but I am not sure if I succeeded.

**Comment by mjcampagna** [comment]
Thanks for the clarification. That's helpful. =D
