### ISSUE TITLE
Style ERROR message

### ISSUE THREAD

**Issue by Cu8eeeR** [fancyapps/fancybox#1497]
"The requested content cannot be loaded. <br/> Please try again later." 

`I would like to add <span style="">TEXT</span> CSS for this text (or for the second part "Please try again later.". How to do that? In v3.0 there was no issue with adding <span style tag>, now in v3.1 it breaks the whole JS.`

Thank you very much! I would like to center the text and make it smaller (font-size 11px)

https://github.com/fancyapps/fancybox/blob/master/dist/jquery.fancybox.js#L348

**Comment by fancyapps** [comment]
Hi,

You can customize html markup using `errorTpl` option or using translation:

`$.fancybox.defaults.i18n.en.ERROR = "<h2>Oops!</h2><p>Something went wrong.</p>";`

https://codepen.io/anon/pen/YQZwaM?editors=1010

**Comment by Cu8eeeR** [comment]
OK, I tried. Anyway is possible to add span class into translation or not?

**Comment by fancyapps** [comment]
Why not, even my example contains some html code.

**Comment by Cu8eeeR** [comment]
OK, thats why I created this issue. When I added span class the pop up window is broken, not shown

**Comment by Cu8eeeR** [comment]
@fancyapps - still without any success, when I add span class -> fancybox is not working

**Comment by fancyapps** [comment]
@Cu8eeeR why don`t you create a demo (just fork any codepen demo)
