### ISSUE TITLE
data-options - can't get src to work

### ISSUE THREAD

**Issue by stharvey** [fancyapps/fancybox#1498]
Hello,
I can't seem to get the data-options method to work.

This is my code:

```
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>

<link  href="css/jquery.fancybox.min.css" rel="stylesheet">
<script src="js/jquery.fancybox.min.js"></script>

<a data-fancybox data-options='{"caption" : "My caption", "src" : "images/image.jpg"}' href="javascript:;" >
	Open 
</a>
```
I receive the message "The requested content cannot be loaded. please try again later".

Do you know what I am doing wrong?

Thanks for a great script.

**Comment by stharvey** [comment]
Sorry - ignore my comment - I had made a typo in the code!

**Comment by stharvey** [comment]
Hello - just for your info.  There seems to be a typo in your documentation:

**"src :** instead of **"src" :**
```
<a data-fancybox data-options='{"caption" : "My caption", "src : "iframe.html"}' href="javascript:;">
	Open external page using iframe
</a>
```

**Comment by fancyapps** [comment]
@stharvey Thanks for noticing and reporting, I have fixed and added a demo - https://codepen.io/fancyapps/pen/vZxLyb?editors=1000

**Comment by stharvey** [comment]
Thank you very much!

1 more related query.  I am trying to use the "buttons" option in data-options like this:


```
data-options='{"buttons" : [
'close'], "src" : "iframe.html"}
```
I've also tried: {"buttons" : "[&apos;close&apos;]", "src" : ........

Can you give me some advice on the correct method to define buttons using data-options

Thanks a lot.

**Comment by fancyapps** [comment]
@stharvey Sorry, it would be like this:

```HTML
<a data-fancybox data-options='{"caption" : "My caption", "src" : "https://codepen.io/about/", "type" : "iframe", "buttons" : [ "close" ] }' href="javascript:;" class="btn">
	Open external page
</a>
```

but due to how `$.extend` works, this snippet adds new entry to button array instead of replacing it. I`ll update to code to make it work as expected.

**Comment by stharvey** [comment]
Ok, great, thanks a lot - really appreciate your support.
