### ISSUE TITLE
my options are ignored

### ISSUE THREAD

**Issue by Mexikaner9** [fancyapps/fancybox#1499]
I'm trying to use your great gallery, but my options are ignored.
Please help me.
I do not want any URL change, I do not want thumbs and I would like to use the language German.
Here is my example: http://nirvana.bplaced.net/Franz/ 
And here is my code:
[CODE]
$('[data-fancybox]').fancybox({
  selector : '[data-fancybox="images"]',
  loop     : true,
	protect : false,
	animationEffect : "zoom",
	transitionEffect : "fade",
hash     : false,
thumbs   : false,
	arrows : true,
	infobar : true,
	toolbar : true,
	buttons : [
		'slideShow',
		'fullScreen voll',
		'close'
	],
	lang : 'de',
	i18n : {
		'de' : {
			CLOSE       : 'Schliessen',
			NEXT        : 'Weiter',
			PREV        : 'Zurück',
			ERROR       : 'Die angeforderten Daten konnten nicht geladen werden. <br/> Bitte versuchen Sie es später nochmal.',
			PLAY_START  : 'Diaschau starten',
			PLAY_STOP   : 'Diaschau beenden',
			FULL_SCREEN : 'Vollbild',
			THUMBS      : 'Vorschaubilder'
		}
	}
});
[/CODE]

**Comment by fancyapps** [comment]
Hi,

Why do you have `selector : '[data-fancybox="images"]',` ? You are using `data-fancybox="group"`, therefore your selector would not find anything.
