### ISSUE TITLE
ipad  iframe MUST have href='javascript:;' 

### ISSUE THREAD

**Issue by aussieguy55** [fancyapps/fancybox#1500]
followed your documentation  and set up some  iframes on a lot of pages
in all browsers it worked Except Ipad 's  chrome and  safari

ipad........ it refused to open the iframe 
5 hours later  I viewed the page source on fancyapps.com and found  href='javascript:;"  was added to the attributes
you should change your documentation to include the href='javascript:;'

**Comment by fancyapps** [comment]
Hi,

I have no idea why are you sure about this, it works fine with any `href` attribute, because the script uses `data-src` value first.

**Comment by aussieguy55** [comment]
whooops   .... I **missed seeing** the href='javascript:   in your docs cause it was hidden by the scroll bar

all my html files  did not contain the href=  cause I need to learn to read better
and they worked  without it ....   except for ipad

thank you for this script... 
made changing from the old lytebox  i was using easy.
