### ISSUE TITLE
Contact NPM support to solve the fancybox package dispute

### ISSUE THREAD

**Issue by jtojnar** [fancyapps/fancybox#1501]
Since @olsonpm [does not want to](https://github.com/olsonpm/fancybox/issues/3) transfer the package until `generation` component of the version is incremented, the next step is [contacting NPM support](https://www.npmjs.com/policies/disputes) to resolve this.

The argument is that the assumptions based on semver were already broken. Any update relying on semver semantics would have broken the app anyway – well, if the package actually kept up with upstream.

Because fancybox uses `generation.major.minor` scheme, publishing `3.1.20` as `fancybox` would actually be bumping a major version. And while it is semantically different from bumping a generation, the implications for consumers are the same, amending the unfortunate version mismatch.

**Comment by fancyapps** [comment]
Yes, I agree, but this has been solved by using scoped package. Eventually, there will be fancyBox v4 and then this will be completely sorted out.

**Comment by jtojnar** [comment]
Unfortunately the scoped packages do no work on LTS Debian/Ubuntu version of NPM.

**Comment by fancyapps** [comment]
Are you sure? I did not found that there would be issues with that, it should work - http://manpages.ubuntu.com/manpages/yakkety/man7/npm-scope.7.html

Also, I am using Ubuntu and works fine for me.

**Comment by jtojnar** [comment]
Unfortunately, scoped packages require [NPM 2.7](https://docs.npmjs.com/getting-started/scoped-packages). Ubuntu Trusty provides [1.3.10](https://packages.ubuntu.com/trusty/npm) and Debian [1.4.21](https://packages.debian.org/jessie/npm).

I [did not find](https://github.com/SSilence/selfoss/pull/949) a way to install fancybox on these platforms.

**Comment by fancyapps** [comment]
Have you tried upgrading? I know, it can be a pain :) 
npm recently updated to v5, therefore you are using quite outdated version.

**Comment by jtojnar** [comment]
Personally, I use Arch so I have fairly recent version of NPM, some of our users have these systems installed on their servers and I can imagine installing software by other means than distribution’s package manager is a maintenance nightmare.
