### ISSUE TITLE
Strange images zoom after show

### ISSUE THREAD

**Issue by Tusko** [fancyapps/fancybox#1504]
Hey!
I have a strange bug on my website http://laroserie.dev0.site/our-works/
After image opened - it's zoomed with wrong aspect ratio.
I don't use any custom settings for `fancybox`

Can you help me?

   * macOS Sierra 10.12.5
   * Chrome 58.0.3029.110
   * jQuery 3.1.1
   * fancyBox v3.1.20

**Comment by fancyapps** [comment]
Hi,

Upgrade jQuery to the latest (v3.2.x)
( this issue is caused by this bug - https://github.com/jquery/jquery/issues/3193 )

**Comment by Tusko** [comment]
@fancyapps 
WOW! Thank you so much!
