### ISSUE TITLE
Fancybox 3.1 issues with IE 11

### ISSUE THREAD

**Issue by imza86** [fancyapps/fancybox#1505]
I was on the verge of completing this project when i just realised there is some issues in IE11. [http://www.noor-azmi.com/element/projects.html](http://www.noor-azmi.com/element/projects.html )

The site is 100% fine all other browsers except IE 11. Issues in IE 11, cannot loop, doesnt autoplay and sometimes next photo does not appear.

This is my code:
`<script>
                            
                            $.fancybox.defaults.loop = true;
                            $.fancybox.defaults.transitionEffect="fade",
                            
                            $('[data-fancybox="images"]').fancybox({
                            slideShow : {
                            autoStart : true
                           
                           
                            
                                         },
                           
                                });
                            
                        $('[data-fancybox="project2"]').fancybox({
                            slideShow : {
                            autoStart : true
                            
                                         },
                            
                                });
                        
                        $('[data-fancybox="project3"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                            
                        $('[data-fancybox="project4"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                            
                        $('[data-fancybox="project5"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                            
                                });
                            
                        $('[data-fancybox="project6"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                        
                        $('[data-fancybox="project7"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                            
                                });
                        
                        $('[data-fancybox="project8"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                            
                                });
                            
                        $('[data-fancybox="project9"]').fancybox({
                            slideShow : {
                            autoStart : true
                                         },
                           
                                });
                            
                            
                            </script>`

Pls help, thanks.

**Comment by fancyapps** [comment]
Hi,

Your page is not accessible, but I do not see why fancyBox would not work on IE11. Works fine for me.
Make sure that:
1) You have the latest jQuery
2) Your page does not have JS errors (any JS error can break further code execution)
3) You are not opening file directly in the browser (e.g., you have to use some webserver to test properly)

**Comment by imza86** [comment]
Hi, I am not sure why my page is not accessible. I dont think there is anything wrong with it. I just clicked on it and is totally fine  Nevertheless  i have uploaded it to another domain [](http://www.element.com.sg/projects.html) 

The only issue i am facing now is in IE 11 is that in the slideshow especially after the 1st loop, suddenly image is blank. The blank image is random example image 3 is fine during 1st loop then 2nd loop it is blank and then during 3rd loop it is ok. Also if use the arrow navigation and not the autoplay you can clearly see some images suddenly is blank. I dont have this issue in other browsers.

If u need a video of this i can show you.

**Comment by fancyapps** [comment]
This page is accessible and works fine for me. Maybe try cleaning cache.

btw, to fix page shifting when opening/closing fancyBox, remove `width: 100%;` from `body` tag,

Also, you have tons of html and css errors - no closed tags, footer is outside body, `line-height: auto;` is no valid value, etc :)
