### ISSUE TITLE
Incorrect $lastFocus element

### ISSUE THREAD

**Issue by Iworb** [fancyapps/fancybox#1506]
When `div` element with `data-src` attribure used to open fancybox instance `$lastFocus` property set to `body` instead of element which actually opened it. There's no problem with link element `a`, because it could be focused.
Is there another way to check which element opened current instance of fancybox?

**Comment by fancyapps** [comment]
Hi,

`$lastFocus` should not be used for that - this is just reference to `document.activeElement` and value of that attribute depends on OS/browser.

When you are using some callback, then you will receive two arguments - instance and current slide object. Reference to link will be found under `slide.opts.$orig`, example (from documentation):

```JS
<script type="text/javascript">
	$("[data-fancybox]").fancybox({
		afterShow: function( instance, slide ) {

			// Tip: Each event passes useful information within the event object:

			// Object containing references to interface elements
			// (background, buttons, caption, etc)
			// console.info( instance.$refs );

			// Current slide options
			// console.info( slide.opts );

			// Clicked element
			// console.info( slide.opts.$orig );

			// Reference to DOM element of the slide
			// console.info( slide.$slide );

		}
	});
</script>
```
