### ISSUE TITLE
Pointer link in caption area not work

### ISSUE THREAD

**Issue by urbanqee** [fancyapps/fancybox#1507]
I made a Japanese page on how to use Fancybox3.
But there are two problems.
1) Pointer link in caption area does not work.
2) PDF file does not work with Iframe on IE-11.

thanks.

**Comment by fancyapps** [comment]
Hi,

1) What do you mean by "pointer link"? Anchor elements should work.
2) This is something that depends on browser/user computer. fancyBox is just creating a markup, but the rest is up to the browser.

**Comment by urbanqee** [comment]
I am not good at English.
1. What do you mean by "pointer link"? Anchor elements should work.
adding social button in caption area. Button click not work.
Please see my demo page. 
http://urbanqee.com/webutil/photo/fancybox3/fancybox31-socialbutton-demo.html

**Comment by fancyapps** [comment]
Pointer events are disabled on caption area by default (so you can click through it), but you can simply reenable by:

```CSS
.fancybox-caption-wrap {
  pointer-events: all;
}
```

or you can set this for each button individually.

**Comment by urbanqee** [comment]
I added CSS, share Twitter  very good.
thanks.
