### ISSUE TITLE
Some images are not closed at gesture up / down on the phone

### ISSUE THREAD

**Issue by NeXan87** [fancyapps/fancybox#1512]
On the phone on **FancyBox v3.1.20** some images are not closed with gestures up / down. On the previous version **FancyBox v3.0.22** there is no such problem. To make it clear, I took a video and posted it on Youtube.
Browser - **Yandex Browser and Chrome**
Site: https://v-thailand.com/kachestvo-pitevoy-vodyi-v-tailande/
Youtube: https://www.youtube.com/watch?v=VkCJ0JEdd6s

**Comment by fancyapps** [comment]
Hi,

Sorry for the late update, this should be fixed for some time.
