### ISSUE TITLE
White screen doc in iframe on mobie

### ISSUE THREAD

**Issue by Zverushko** [fancyapps/fancybox#1517]
Hello!

i have link (tag a) with href ro pdf file

after add .fancybox() on my link i have well work pdf on desktop and white screen on mobile. 

example on my site - https://kashkovskiy.ru/
Lowest link on page.

how i cant fix that?
thx!

**Comment by fancyapps** [comment]
Hi,

The script just creates markup, but how content is rendered is up to the browser.  
If you want to have broader pdf support, try using https://mozilla.github.io/pdf.js/
