### ISSUE TITLE
blank iframe showing in lightbox for website

### ISSUE THREAD

**Issue by mrmitche** [fancyapps/fancybox#1518]
I have two iframes embedded with FancyBox3. One uses a url from an iframe embed code, the other is just a url to another website. The iframe to open another website in the a fancybox lightbox just shows a blank white page. 

As you can see on http://herstoryproject.me/, the Tour link works and the Letters link shows nothing in the lightbox. Is this not supported on by FancyBox3?

**Comment by fancyapps** [comment]
Hi,

Looks like you have forgot to add `data-fancybox data-type="iframe"` attributes to that link.

**Comment by mrmitche** [comment]
@fancyapps I actually updated the site late lastnight to be a normal link and forgot to update this post. The code below is what I had that wasn't working.
`<p><a data-fancybox data-type="iframe" data-src="https://www.thinglink.com/mediacard/938789130744102913?autoplay=1" href="javascript:;">Working iframe</a></p>`
`<p><a data-fancybox data-type="iframe" data-src="https://samanthalevine.atavist.com/letters" href="javascript:;">Not working iframe</a></p>`

**Comment by fancyapps** [comment]
Try embedding your page directly, it shows blank page, too:

`<iframe src="https://samanthalevine.atavist.com/letters" />`

so, what did you expect? :)
