### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by AlexHaid** [fancyapps/fancybox#1523]
Hello!
v3 really looks great, thank you for update!
But there's something with navigation buttons on screen edges (previous/next). 
I did every step that written at quick start guide, but they didn't appear. As default, they have to appear instantly, according to

arrows : true

Please, I need an advice. What I did wrong?
Sorry for broken english and thank you in advance!

**Comment by fancyapps** [comment]
Hi,

1) these arrows are included from v3.1, so, make sure you are using the latest versio;
2) make sure that your links have same value for `data-fancybox` attribute, for example, `data-fancybox="group"`
