### ISSUE TITLE
Touch + Text can be selected

### ISSUE THREAD

**Issue by nsynsynsy** [fancyapps/fancybox#1527]
I can't highlight or select the text if I enable touch function.

How can I let the user select the text in inline modal and keep the touch function?

**Comment by fancyapps** [comment]
Hi,

See 3rd sample from https://codepen.io/fancyapps/pen/NjXbXw

Basically, just set "touch: false" and you will be able to select the text.

**Comment by nsynsynsy** [comment]
I know. But If I disable touch function, the user cannot use swipe function on mobile, am I right?

But is it possible to maintain 2 function, touch and highlight text?

**Comment by Stadly** [comment]
Is it possible to only enable touch for mobile? Something like this:

    {
      ...
      touch: false,
      mobile: {
        touch: {
          vertical: true,
          momentum: true
        }
      }
    }

**Comment by Stadly** [comment]
Alternatively, enable `touch` when `type` is `image`, but now when `type` is `html`?

**Comment by fancyapps** [comment]
It would be easier to set different options for image gallery and html content. Sorry, it is correctly not possible to do it automatically.

**Comment by fancyapps** [comment]
@erichstark touch is only available starting from v3. And what do you mean by `highlight text more than a few characters` ? Maybe you are looking for http://fancyapps.com/fancybox/3/docs/#faq-5 ?

**Comment by erichstark** [comment]
It is okay now. I had problem with some events collision between fancybox v2 and jquery.mobile library. After removing jq.mobile it works well.
