### ISSUE TITLE
Prevent from open

### ISSUE THREAD

**Issue by decadence** [fancyapps/fancybox#1529]
Hello.
I have latest version.
How can I prevent fancybox from open?

I have gallery which has main photo (that should start fancybox) and some thumbnails (which should not start fancybox but they must be in gallery when fancybox is shown). If I remove fancybox init for thumbnails  they are not in fancybox gallery. If I add fancybox init for thumbnails click on them start fancybox but I want to click on them start other actions without fancybox.
fancybox 2 respects `return false;` in other click event handlers, but fancybox 3 start regardless of it.

`beforeShow` and `return false` not working.

**Comment by fancyapps** [comment]
Hi,

jQuery plugin is just a tiny (really tiny, can check core.js file) part of the whole code and all it does it binds click event and calls  `$.fancybox.open()` afterwards. If you want something special, you can create your own click handler.

**Comment by decadence** [comment]
It's nothing special and it worked with fancyBox 2.
I just want to prevent FB from open.
I can't see any `.on('click')` code so I can't prevent it with 
```js
$(".should_not_close_fancybox").click(function(){
return false;
});
```

**Comment by decadence** [comment]
I can create my own click handler but therefore thumbnails won't be in fancybox gallery when it's open.

**Comment by fancyapps** [comment]
But where is the issue, your snippet works fine - https://codepen.io/anon/pen/owVBmM?editors=1010

**Comment by decadence** [comment]
Hm... you're right. Thanks I will investigate further.

**Comment by decadence** [comment]
Oh I see. Problem appears when I init fancybox manually.
You can reproduce it by adding 
` $('a').fancybox();`
on top of the JS section.

**Comment by decadence** [comment]
Putting it below not helping too

**Comment by fancyapps** [comment]
Looks like `e.stopImmediatePropagation();` does the job -


```JS
$(".should_not_open_fancybox").on('click', function(e) {
  e.stopImmediatePropagation();

  return false;
});

$('[data-fancybox="images"]').fancybox();
```




https://codepen.io/anon/pen/gREmxp?editors=1010

**Comment by decadence** [comment]
@fancyapps Thank you so much! It works now. I just forgot about this method and by some reason think `return false;` handle this. Obviously it doesn't.
One question I have: as I can see by default fancybox attachs to [data-fancybox] elements. Is it ok if I apply `fancybox` function (second time I suppose) to these elements with some options?

**Comment by fancyapps** [comment]
Sure, you can even use any selector.

**Comment by decadence** [comment]
Ok. Thanks for the help!
