### ISSUE TITLE
SCRSET  does not work correctly

### ISSUE THREAD

**Issue by Mexikaner9** [fancyapps/fancybox#1531]
I've created a gallery ( http://nirvana.bplaced.net/FB ) with SCRSET, but unfortunately it does not work correctly.
It works correctly on my desktop computer, but only the large pictures are displayed on my iPhone.
Why does it not work correctly? What is wrong with my code?

**Comment by fancyapps** [comment]
Hi,

The script generates markup according to specs, the rest is up to the browser. Unfortunately, browser behavior is not consistent, for example, some will not download new one if image is cached (event if it supposedly should), making it difficult to test.
