### ISSUE TITLE
beforeShow and afterClose on ver.3

### ISSUE THREAD

**Issue by Aharito** [fancyapps/fancybox#1532]
Hi!
On FancyBox v.2, I used code like this:
```
<script type="text/javascript">

   $(document).ready(function() {
      $('.my-button').fancybox({
         beforeShow:  function(){ $('.my-button').addClass('hidden'); },
         afterClose:  function(){ $('.my-button').removeClass('hidden'); }
      });
   });

</script>
```

.my-button element is outside of FB container.

But in v.3 this code dont work?

I will be grateful for the hint, how to write the same code in version 3

**Comment by fancyapps** [comment]
Hi,

I do not see why it would not work in v3 - https://codepen.io/anon/pen/xreaxX
