### ISSUE TITLE
Thier is some way only on Desktop to make the gallery without swipe?

### ISSUE THREAD

**Issue by Siton-Systems** [fancyapps/fancybox#1534]
I want "regular" lightbox" on a desktop and only on mobile-tablet to use all the amazing swipes/pinch and so on of fanceBOX.

**Why?**
From UI aspect on desktop the "old" [lightbox ](http://lokeshdhakar.com/projects/lightbox2/) it's better in my opinion -  like the Facebook site (i always want to go to the next images by click on the img).

I can add media q and 50% btn - but I destroy the overlay of the gallery + I want future updates I don't want to change the structure too much. Any ideas?

**Comment by fancyapps** [comment]
Hi,

You can use `mobile` option to set different settings for mobile devices. Something like this:

```JS
touch  : false,
mobile : {
    touch : true
}
```
