### ISSUE TITLE
Issues only in FIREFOX 54.0.1

### ISSUE THREAD

**Issue by bmanu** [fancyapps/fancybox#1535]
I used fancybox long years back in one of my site. Last week I added GTM (Google Tag Manager) code in my site 'head' area. Then the FANCYBOX behavior is not working properly. After that I have updated the jQuery easing from 'jquery.easing-1.3.pack.js' to 'jquery.easing-1.4.1.pack.js'. Then its working fine in ALL the browsers (MAC & WINDOWS) other than FIREFOX. I am using the latest version of Firefox.

Error is "TypeError: e is undefined" !!!

Will some one help me about this ?

Thanks

**Comment by fancyapps** [comment]
https://github.com/fancyapps/fancybox#bugs-and-feature-requests

**Comment by bmanu** [comment]
Sorry I am not exactly understand why close this ?

**Comment by fancyapps** [comment]
I`m sorry, but what did you expect? You have not given any clue.

1) fancyBox version?
2) jQuery version?
3) a link to page demonstrating your issue?

**Comment by bmanu** [comment]
Extremely Sorry : 
 - http://tech.stuv.com/fr/espaces-pro/espace-presse/photos-bois/realisation-stuv-22.html
 - fancyBox v2.1.5
 - jQuery v1.10.2

I have tried the new version of fancyBox 3 & its css too, but not working only in Firefox
Thanks

**Comment by bmanu** [comment]
Hello, Is that ok ?
Thanks

**Comment by fancyapps** [comment]
Sorry, no idea what could cause this. Maybe try updating jQuery to the latest from 1.x branch - https://code.jquery.com/jquery-1.12.4.min.js 

Is there any particular reason to not upgrade to fancyBox v3?

**Comment by bmanu** [comment]
No reason. But its long back work, So no time to update it. (Billing issue). WHY this is only not working in FIREFOX ? ....

Thanks

**Comment by bmanu** [comment]
My friend, I have updated the jQuery too to https://code.jquery.com/jquery-1.12.4.min.js

Still issue, can you advice me any way to solve this ?

Thanks

**Comment by fancyapps** [comment]
Since official demo of v2 works fine - http://fancyapps.com/fancybox/demo/ - I have no clue what could cause this issue on your page.

Also, v2 is not supported for a long time, but you can freely upgrade to v3.

**Comment by bmanu** [comment]
Yes friend... Its working fine WITH out GTM (Google Tag Manager) code. When add gtm code its breaking.

Can you have a look on your v3 with GTM code ? .. on Firefox ?

Thanks
