### ISSUE TITLE
HTML5 video/audio controls don't work on IE11,Edge

### ISSUE THREAD

**Issue by kaji2** [fancyapps/fancybox#1536]
I'd like to open a video like this,
```html
<div id="video">
  <video src="video.mp4" controls autoplay></video>
</div>

<a data-fancybox data-src="#video">trigger</a>
```
or this.
```html
<script>
  $(function(){
    $('.trigger').on('click',function(){  
      $.fancybox.open('<div><video src="video.mp4" controls autoplay></video></div>');
    });
  });
</script>

<a class="trigger">trigger</a>
```
Both code could work, but after opening fancybox, video controls don't work on IE11 and Edge.
Controls have reaction of hover, but nothing happens by clicking.

(As you would guess, everything works well on Firefox and Chrome. )

**Comment by fancyapps** [comment]
Hi,

Simply disable "touch", example: https://codepen.io/anon/pen/dRBzXZ?editors=1010

**Comment by kaji2** [comment]
So nice!!!
I am grateful for your support.
