### ISSUE TITLE
[V3]how to update a instance when the tag's data-src value changed?

### ISSUE THREAD

**Issue by max-wen** [fancyapps/fancybox#1537]
Hi there!  Here comes with an example that show the way I'm using Fancybox v3.x

```html

<a data-fancybox data-type="iframe" data-src="before.html">Click me</a>

<script>
$('[data-fancybox]').fancybox({
    beforeShow:function( instance, current ) {
        $('.fancybox-newpage').attr('href', current.src);
    }
});


// Then I change the a tag's data-src triggered by another event
$('a').attr('data-src', 'after.html');


</script>

```

My issue is after I changed the `data-src` value by other scripts and then click the link , Fancybox still shows before.html's content in the iframe.

Please help.

**Comment by fancyapps** [comment]
Hi,

Have you tried using `$('a').data('src', 'after.html');` ?

**Comment by max-wen** [comment]
@fancyapps It works , thanks.😁
