### ISSUE TITLE
Gallery grouping when initializing with jQuery

### ISSUE THREAD

**Issue by matthillco** [fancyapps/fancybox#1538]
In Fancybox 3, how do I combine gallery grouping with jQuery initialisation options?

If I add `data-fancybox="gallery"` to my image anchors, and then add some options to a jQuery intialisation object on the same selector, the options seem to be completely ignored?

For example, none of these options do anything for me. I still get the hashing, toolbar and standard buttons:

	$('[data-fancybox="gallery"]').fancybox({
		toolbar : true,
		hash : false,
		buttons : [
			'fullScreen',
			'close'
		],		
	});

**Comment by fancyapps** [comment]
Hi,

Your snippet looks fine and works as expected - https://codepen.io/anon/pen/XarbLq?editors=1010

**Comment by matthillco** [comment]
Ah, I just realised it's an issue in 3.0.47, but if I update to 3.1.20 it's fine. Sorry about that.
