### ISSUE TITLE
iPhone issues - Unable to scroll and fancybox has a large space below it

### ISSUE THREAD

**Issue by Caroline-Elisa** [fancyapps/fancybox#154]
Hi there,

I have noticed that a few people are having issues with Fancybox on their iPads and iPhones, here's my two cents.

Firstly, and most importantly, I am unable to scroll on an iframe popup. There are no scrollbars, nor can I use my finger as this just scrolls the page in the background.

Secondly, there margin below Fancybox is quite large, which means the screen space is not being maximised.

Hoping there is a solution, as this is a great plugin! However at this rate I am going to have to find another. :(

**Comment by ronkelsch** [comment]
I have been working on this problem for over a week using iframe, object, and embed. All produce a scroll bar effectively, but the iPad fails to show the whole document past the height given. Many use height of 100%, but this only means 100% of the browser and not the iframe or object. I have tried several methods of jQuiery, but the document does not appear. The only solution is to put the height to 10,000px or an amount larger than the largest document. If the document is so large, simply place a link at the bottom to reload the page to show the menu.
