### ISSUE TITLE
PDFs not scrolling on IOS

### ISSUE THREAD

**Issue by lockboxpm** [fancyapps/fancybox#1542]
When attempting to iframe a website on IOS, it works fine, but when attempting to open a PDF with multiple pages it doesn't seem to access the secondary pages.

**Comment by fancyapps** [comment]
Hi,

It is not advised to display pdf files on mobile devices due to device limitations. See, for example, this post - https://stackoverflow.com/questions/8237708/making-embedded-pdf-scrollable-in-ipad

As solution, you could try using PDF.js - https://mozilla.github.io/pdf.js/
