### ISSUE TITLE
Upgrade Fancybox from v2.1.5 to v3.1.20

### ISSUE THREAD

**Issue by PrestaShark** [fancyapps/fancybox#1544]
Hi!
Im trying to polish Prestashop with latest fancybox and im quite impressed!
Also im not js developer and need some little help with one function located in js/tools.js catalogue.
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.15/js/tools.js at line 426

I have notticed that without add $.fancybox.open at line 452 firebug gives error **TypeError: $.fancybox is not a function**
After that popup is launched but with five close buttons...
http://imgurl.pl/img/fancy_597664fdef667.jpg

How to remove them and how to put this button to main fancybox window?
`<button` class="btn btn-ms" type="submit" value="true" onclick="$.fancybox.close();window['productcommentRefreshPage'](JSON.parse(unescape('0')), 0)">

Also here
Thanks!!! https://stackoverflow.com/questions/45290473/upgrade-fancybox-from-v2-1-5-to-v3-1-20

**Comment by fancyapps** [comment]
Hi,

You are right, `$.fancybox` is indeed not a function and you have to replace with `$.fancybox.open()`

Regarding this multiple button issue, simply put your content inside some wrapping element. If you wish to customize html for this button, use `tpl.smallBtn` option.

**Comment by PrestaShark** [comment]
@fancyapps its works! Yeah!
http://imgurl.pl/img/fancy-works_597704a6433bc.jpg
