### ISSUE TITLE
Animation effect ignored - Fancybox3 only opens with spinner effect

### ISSUE THREAD

**Issue by eriksilver** [fancyapps/fancybox#1546]
When I click on the text/link with the click handler to open the Fancybox quick view modal, it started opening with a spinner effect, where the box twists, get very narrow and then expands into full view. 
I'd like just a simple fade in. 
I've tried adding animation effect in several spots, but it's not working. What is the right option and where to add it to adjust the opening animation effect? 

Sorry, this is on a development theme that is not live, so I can't share a preview. 

Here is my Fancybox code:
  $("body").on("click", ".product-quick-view", function(event) {
    event.preventDefault();
    var elem = $(this);

    $.fancybox.open({
        src  : '/products/' + $(elem).data('handle') + '?view=modal',
        type : 'ajax',
        animationEffect : false,
        opts : {
            animationEffect : false,
            baseClass: "quick-view-modal", 
            afterShow : function( instance, current ) {
                console.info( 'quick view done!' );
            },
        	ajax : {
          		settings : {
                        animationEffect : false,  
            	        data : {
              		quickview : true,
              		view : "modal"
            		}
          		}
        	}
        }
    });
  });

**Comment by fancyapps** [comment]
Hi,

Make sure you are using the latest version (currently v3.1.2; see https://cdnjs.com/libraries/fancybox)

**Comment by eriksilver** [comment]
Thank you, Jānis. I have version 3.1.2, but still have the issue. Any other ideas? 

<link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.20/jquery.fancybox.css" rel="stylesheet" type="text/css" media="all" />
--
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.20/jquery.fancybox.js" type="text/javascript"></script>

**Comment by fancyapps** [comment]
Well, it should work fine - https://codepen.io/anon/pen/OjVEvE

```JS
$.fancybox.open({
    src  : 'https://codepen.io/fancyapps/pen/oBgoqB.html',
    type : 'ajax',
    animationEffect : "fade"
});
```

**Comment by khaliljan** [comment]
I recently headed up to check fancybox v3. over all its greatness, just have stuck up how to add transition effect/costume transition to [Quick Product View](http://fancyapps.com/fancybox/3/#quick-view-1) of the fancybox v3 when i fire the modal. and also  data-caption="" not working in  [Quick Product View](http://fancyapps.com/fancybox/3/#quick-view-1).

**Comment by fancyapps** [comment]
@khaliljan What effect are you looking for?

btw, did you know there are multiple demos for "Quick View"?

https://codepen.io/fancyapps/pen/wdmGZJ
https://codepen.io/fancyapps/pen/MmVEzQ
https://codepen.io/fancyapps/pen/ZKqaKO

**Comment by khaliljan** [comment]
was looking for opening/closing transition effect like "fade", which seems solved in your [codepen example](https://codepen.io/fancyapps/pen/wdmGZJ).

**Comment by fancyapps** [comment]
It is "solved" by using this option: `animationEffect   : "fade"`

**Comment by zano-aa** [comment]
As of today on the latest version of v3,  on a ajax call, the option animationEffect : "fade" or false or whichever, are not working 

the code above :

$.fancybox.open({
    src  : 'https://codepen.io/fancyapps/pen/oBgoqB.html',
    type : 'ajax',
    animationEffect : "fade"
});

Does not work

The codepen looks like it's reacting but I believe the option is ignored for ajax

**Comment by fancyapps** [comment]
Everything works and has been working perfectly fine for years - https://codepen.io/fancyapps/pen/yxmrWZ?editors=1100
