### ISSUE TITLE
Q: Combine fancyBox3 and MixItUp 

### ISSUE THREAD

**Issue by Siton-Systems** [fancyapps/fancybox#1547]
It's works fine but I want each time to loop throw the filter gallery. I know this is out of topic but maybe someone knows how to solve this.

In my example when you click "category-2" you should only get one image in lightbox (and not all images).

https://codepen.io/ezra_siton/pen/JydYqm

Should works Like in this example:
https://codepen.io/kushelbek/pen/QvGexw

**Comment by Siton-Systems** [comment]
Never mind. I succsed. Thanks anyway

**Comment by pashaUSA** [comment]
**Ezra-Siton-UIX,** would you mind sharing how you did it?

**Comment by fancyapps** [comment]
@pashaUSA Hi, You just have to tweak "selector" option so that it returns only visible items excluding duplicates. If you would have created codepen demo, it would be easy to help you.

**Comment by Ezra-Siton-UIX** [comment]
> **Ezra-Siton-UIX,** would you mind sharing how you did it?

https://codepen.io/ezra_siton/pen/JydYqm
