### ISSUE TITLE
FancyBox 3.x.x Commercial Licenses

### ISSUE THREAD

**Issue by sbguy** [fancyapps/fancybox#1548]
Hi, 
appologies to bring up this question inside github issue section, but there is no contact us section. I need to clear some things up about the commercial licenses. 

My team and I just bought the unlimited license as a matter of fact we didn't see any way to embed our key within the library. What are we supposed to do with our license key once we bought it? 
We plan to use this often and we wanted to be 100% legit!

Thank you for your time.

**Comment by fancyapps** [comment]
Hi,

You can reach me through Twitter DM (https://twitter.com/thefancyapps) or here - https://gitter.im/fancyapps/fancybox

There is no need to use license key anyway, just keep it.

**Comment by Spoonbill** [comment]
Hi Jānis
Can I confirm the above please.

'The licence key does not need to be embedded anywhere on any website?'

It would be useful to put this information on the purchase page or receipt for the license.
i have been trying to find out where to put the licence key details for months. The information does not seem to be available.
By the way, Fancybox 3 is great thanks

**Comment by fancyapps** [comment]
Yes, that is right, just keep it. In future, it might be used to access member area or something like that.
Sorry for misunderstanding.

Thanks!

**Comment by korinaM** [comment]
Hi Jānis, I downloaded media boxes and i wanted to use fancybox, when i tried the code offline it was working ok but when i uploaded it to go live it didn't work. I also downloaded the commercial licence. Could you help me out? 
Thanks

**Comment by fancyapps** [comment]
@korinaM how can I help you without seeing your code?

**Comment by korinaM** [comment]
Hi,  this is the code:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<title>Photos</title>

<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<title>Photos</title>


<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">


<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
		
<link href="css/stylesRESP.css" rel="stylesheet" type="text/css" media="screen" />
<link href="css/demoPhotogallery.css" rel="stylesheet" type="text/css" media="screen" />
<link href="css/demoPhotogallery2.css" rel="stylesheet" type="text/css" media="screen" />
 
<link rel="stylesheet" href="plugin/components/Font Awesome/css/font-awesome.min.css"> 
<link rel="stylesheet" href="plugin/components/Fancybox/jquery.fancybox.min.css"> 
<link rel="stylesheet" type="text/css" href="plugin/css/mediaBoxes.css"> 

</head>

<body>
<div class="columne-12 columne-t-12">
 <div id="main_content_projects2">       
      
		<div class="content grid-container">

		
	
        <div id="grid">

              
                <div class="media-box indoors">
                    <div class="media-box-image mb-open-popup" data-src="gallery/athens1.jpg">
                        <div data-width="752" data-height="500" data-thumbnail="gallery/thumbnails/athens1_th.jpg" ></div>
                      
                    </div>
                </div>

              
                <div class="media-box photography">
                    <div class="media-box-image mb-open-popup" data-src="gallery/NY12.jpg">
                        <div data-width="752" data-height="560" data-thumbnail="gallery/thumbnails/NY12_th.jpg" ></div>
                   
                    </div>
                </div>

       	</div> 

        

	</div> 


	
	<script src="plugin/components/jQuery/jquery-1.11.3.min.js"></script>
	
	
	<script src="plugin/components/Isotope/jquery.isotope.min.js"></script>
	<script src="plugin/components/imagesLoaded/jquery.imagesLoaded.min.js"></script>
	<script src="plugin/components/Transit/jquery.transit.min.js"></script>
	<script src="plugin/components/jQuery Easing/jquery.easing.js"></script>
	<script src="plugin/components/Waypoints/waypoints.min.js"></script>
	<script src="plugin/components/Modernizr/modernizr.custom.min.js"></script>
	<script src="plugin/components/Fancybox/jquery.fancybox.min.js"></script> 
	<script src="plugin/js/jquery.mediaBoxes.dropdown.js"></script>
	<script src="plugin/js/jquery.mediaBoxes.js"></script>

	<script>

	    $('#grid').mediaBoxes({
	    	filterContainer: '#filter',
	    	search: '#search',
	    	columns: 3,
	    	boxesToLoadStart: 9,
	    	boxesToLoad: 9,
	    	horizontalSpaceBetweenBoxes: 30,
        	verticalSpaceBetweenBoxes: 30,
        	minBoxesPerFilter: 20,
        	deepLinkingOnFilter: false,
        	fancybox: {
        		thumbs : { autoStart : true },    // Display thumbnails on opening/closing
        	}
	    }); 
</script>


<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="js/demoPhotogallery.js"></script>

</body>
</html>

**Comment by fancyapps** [comment]
@korinaM my guess is that you have not correct urls. Maybe they should be like `data-src="/gallery/athens1.jpg"`, but it is hard to tell, I have somewhere lost my magic ball, so I can not be sure.
