### ISSUE TITLE
How to add #hash url to inline html?

### ISSUE THREAD

**Issue by Siton-Systems** [fancyapps/fancybox#1550]
In your examples/docs, i dont see how i can do this.
https://codepen.io/fancyapps/pen/NjXbXw

Thanks

**Comment by fancyapps** [comment]
Hi,

It is the same as for other content types - value of `data-fancybox` is used for hash. You can see example on the homepage:

`<a data-fancybox="modal" data-src="#modal" href="javascript:;">Inline Content</a>`

**Comment by Siton-Systems** [comment]
Thanks! work perfectly!!
