### ISSUE TITLE
Cannot get gallery "loop" to work / Info bar not appearing

### ISSUE THREAD

**Issue by Honeypenny** [fancyapps/fancybox#1552]
I am using fancyBox v3.1.20 and cannot get the images to loop and the info bar does not appear.  Using html5.  (My changes to fancybox script are shown commented with date and initials).

In the head:
<script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
<link  href="js/fancybox/jquery.fancybox.min.css" rel="stylesheet">

In the body: 
<script src="js/fancybox/jquery.fancybox.min.js"></script>
<script src="js/fancybox/jquery.mousewheel.min.js"></script>
<script>
$( '[data-fancybox]' ).fancybox({
	caption : function( instance, item ) {
		var caption = $(this).data('caption') || '';

		return '(<span data-fancybox-index></span>/<span data-fancybox-count></span>)' + ( caption.length ? ' ' + caption : '' );
	}
});
</script>

I have set the fancybox javascript options thus:

  // Private default settings
    // ========================

    var defaults = {

        // Enable infinite gallery navigation
		// Changed from false to true on 20/07/2017 -GH
        loop : true,

        // Space around image, ignored if zoomed-in or viewport smaller than 800px
        margin : [44, 0],

        // Horizontal space between slides
        gutter : 50,

        // Enable keyboard navigation
        keyboard : true,

        // Should display navigation arrows at the screen edges
        arrows : true,

        // Should display infobar (counter and arrows at the top)
		// Changed from false to true on 20/07/2017 -GH
        infobar : true,

        // Should display toolbar (buttons at the top)
        toolbar : true,

        // What buttons should appear in the top right corner.
        // Buttons will be created using templates from `btnTpl` option
        // and they will be placed into toolbar (class="fancybox-toolbar"` element)
        buttons : [
            'slideShow',
            'fullScreen',
            'thumbs',
            'close'
        ],

        // Detect "idle" time in seconds
        //Changed to 10 from 4 on 27/07/2017 -GH
        idleTime : 10,

        // Should display buttons at top right corner of the content
        // If 'auto' - they will be created for content having type 'html', 'inline' or 'ajax'
        // Use template from `btnTpl.smallBtn` for customization
		// Following changed from 'auto' to 'true' on 20/07/2017 -GH
		// Changed back to 'auto' on 27/07/2017 -GH
        smallBtn : 'auto',

        // Disable right-click and use simple image protection for images
		//Changed from 'false' to 'true' on 20/07/2017 -GH
        protect : true,

        // Shortcut to make content "modal" - disable keyboard navigtion, hide buttons, etc
        modal : false,

        image : {

            // Wait for images to load before displaying
            // Requires predefined image dimensions
            // If 'auto' - will zoom in thumbnail if 'width' and 'height' attributes are found
            preload : "auto",

        },

**Comment by fancyapps** [comment]
Hi,

Looks like you have to learn about jQuery and how jQuery plugins work generally. Here are a couple links for the start:

- https://learn.jquery.com/about-jquery/how-jquery-works/
- https://learn.jquery.com/plugins/basic-plugin-creation/

Basically, never edit files directly, but pass options when initializing the plugin.
