### ISSUE TITLE
Error when using gulp and minify - undefined is not an object (evaluating 'l.width')

### ISSUE THREAD

**Issue by outofcontrol** [fancyapps/fancybox#1554]
We are using the Laravel Elixir package to build and minify our JS files in Gulp. Running 'gulp' and there are no errors. Running 'gulp --production' gives this error:

    undefined is not an object (evaluating 'l.width')

The Gulp file has:

    elixir(function(mix) {
        mix.sass('app.scss','public/assets/css');
        mix.copy(paths.node_modules + paths.fontawesome + 'fonts/**', 'public/assets/fonts');
        mix.copy('./resources/assets/fonts/**', 'public/assets/fonts');
        mix.browserify('app.js', 'public/assets/js');
    });

app.js has:

    window.$ = window.jQuery = require('jquery')
    require('./lightbox');

and lightbox.js has:

    'use strict';

    const fancybox = require('@fancyapps/fancybox');

A solution to this issue would be awesome, or a work around such that only fancybox didn't get minimized.

**Comment by fancyapps** [comment]
Hi,

I wish I could help, but I have absolutely no idea. You have mixed so many tools (Node, Laravel, Laravel Elixir, gulp, Browserify, RequireJS), but I have not mastered all of them. And that error message does not give me any clue.

**Comment by Patta** [comment]
@outofcontrol jquery.fancybox.min.js is already minified

**Comment by outofcontrol** [comment]
@patta Understood. My work flow combines and minizes JS from items installed via NPM. Perhaps installing with an NPM workflow is not the way to go? It would be nice if fancybox played more nicely with NPM, or am I missing something in how to manage it?

**Comment by outofcontrol** [comment]
For others who stumble on this, the fix is to simply modify package.json so main points to the unminified js version.
