### ISSUE TITLE
Gallery popup first photo always opens in zoom mode

### ISSUE THREAD

**Issue by alexander-code** [fancyapps/fancybox#1555]
Hi,

I noticed the following issue. I have data-fancybox="group" for a set of images. When I click on the image
the popup open the first photo always in zoom mode and aligns the image to the right. When I start to navigate through the images every image even the first who was zoomed works properly.

Any idea what is going wrong?

Thanks in advance.

**Comment by fancyapps** [comment]
Hi, Sound like you need to upgrade jQuery to the latest (v3.0.x and v3.1.x had a bug affecting width/height calculations, see https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/)

**Comment by alexander-code** [comment]
Hi, thanks for the reply. I already use jQuery 3.0.0, do you think it worth to try the 3.2.0?

**Comment by alexander-code** [comment]
It's ok, I downloaded jQuey 3.2.0 and the issue has been fixed :)

Thanks a lot!
