### ISSUE TITLE
iPhone fancybox iframe width height issue

### ISSUE THREAD

**Issue by alexander-code** [fancyapps/fancybox#1556]
Hi,

I noticed the following issue using fancyBox v3.1.20 with jQuery 3.2.0

I have a `<li><a data-fancybox="iframe" data-type="iframe" data-src="./mypage.php?id=4" href="javascript:;">`

I have this js code:
`<script type="text/javascript">
		$.fancybox.defaults.hash = false;
		$("[data-fancybox]").fancybox();
	</script>`

In iPhone devices (no matter the browser, issue is there for safari, chrome etc) when I click on a product and the popup iframe opens, it opens with much bigger width and height, can not fit in device width.

*In Android devices it works like a charm.

Any ideas?

**Comment by fancyapps** [comment]
Hi,

Sorry, I can not reproduce this. Seeing live demo would help.

**Comment by alexander-code** [comment]
Hi, 
yes, you can not reproduce it unless you have an iPhone because in browsers and emulators works fine and in Android also.

I dig deeper and I found what cause this issue, I fixed it but I have a new issue.

Let me first tell you about the fix. I found that iPhone ignores the css width direction for iframes but it obeys at min-width!!!! So I put an inline style to the div wrapper of my popup page and eventually I managed to make it work in iPhone. 

Now I had another issue after the fix. In the popup page I have also an image gallery, when you click on the image opens at the center of the total document height (that means that the user will not see the image because it's outside of the visible area) and not at the center of the visible screen height. Not to mention that this happens in iPhone only again...

Any clue about that?

**Comment by alexander-code** [comment]
Hi Jānis, did you read my latest reply?

**Comment by fancyapps** [comment]
Hi! As I said, without seeing your page, I have no clue. All my tests work fine. Maybe your page has some CSS that misleads calculations of page dimensions.

**Comment by l2aelba** [comment]
Same with me @alexander-code

**Comment by fancyapps** [comment]
I hope you guys understand, that comments like these are completely useless. Any demo (a real, live test page, not just some snippet) would help to identify and fix any issue.

**Comment by l2aelba** [comment]
@fancyapps Yeah, I know, But I fixed on my own case :D

**Comment by fancyapps** [comment]
@l2aelba  I am glad that you could sort out this.

Anyway, the script tries to calculate page dimensions, but, if you ever tried to do something like that by yourself, then you probably have discoverer that this is not as easy as it looks from the start. For example, top margin to the first visible element on a page can push page down, thus misleading calculations.
