### ISSUE TITLE
Images not resizing on horizontal Iphone 6 plus

### ISSUE THREAD

**Issue by WebWeave** [fancyapps/fancybox#1557]
When you open a image in Fancybox holding the phone vertical, and while the image is open you turn the phone horizontal the images don't resize properly.

<img width="390" alt="schermafbeelding 2017-07-31 om 10 57 05" src="https://user-images.githubusercontent.com/17380630/28770335-0ba7e9a2-75df-11e7-851f-48e113f61779.png">

<img width="390" alt="schermafbeelding 2017-07-31 om 10 57 05" src="https://user-images.githubusercontent.com/17380630/28770351-21ae9e3a-75df-11e7-9f7a-19e78afbdb0b.jpeg">

**Comment by fancyapps** [comment]
Hi,

Make sure you are using the latest version.
