### ISSUE TITLE
Is there an example for albums?

### ISSUE THREAD

**Issue by kikky7** [fancyapps/fancybox#1559]
I want something like this, i.e.:

I have 4 group of galleries (albums), let's name them album1, album2, album3 and album4. Every album has it's own images. I want to show only 4 images (1st image of every album) and on click to show only images of the clicked album. If I click on album1 it should show slideshow of images of that album only.

Is there an example of this, can this be done with this plugin? Because for 29$ I want such a feature.
I've tried with data-src, but that's only for a single content block.

Only alternative is to create a new page for every album, but I don't want to go with such a solution, I want everything on a single page.

**Comment by fancyapps** [comment]
Hi,

Simply make 4 groups of links, but make only first one visible (for each group), just like in this example - https://codepen.io/fancyapps/pen/WjVXyx?editors=1000
