### ISSUE TITLE
Compute sizes when data-srcset is used

### ISSUE THREAD

**Issue by durchanek** [fancyapps/fancybox#1561]
Presently, when using data-srcset, sizes="100vw" is automatically added to responsive images. However this is correct only when image has width:height ratio larger than the browser window ratio. For all other images, this causes browser to download larger image than necessary.
Possible solution would be calculate size from window ratio and image ratio.

**Comment by durchanek** [comment]
Another solution (probably easier to implement and more flexible) would be to read data-sizes from corresponding link tag the same way as data-srcset and allow developer to control this.

**Comment by fancyapps** [comment]
Hi. Thanks for suggestion. This has been improved lately.
