### ISSUE TITLE
Fancybox toolbar and Google Translate

### ISSUE THREAD

**Issue by Honeypenny** [fancyapps/fancybox#1562]
FancyBox 3 works fine until I add the Google Translate function to the page. When the Translate is clicked, Google installs a toolbar that either hides or displaces the fancyBox toolbar. Once the Google Translate bar is closed the fancyBox toolbar appears again. As I doubt that I can get Google to move their toolbar, is there an easy way to move the fancybox toolbar?
I'm using version 3.1.20 of fancybox.

**Comment by fancyapps** [comment]
Hi,

You can use CSS to move it anywhere you want. You can even re-arrange blocks to move it, for example, at the bottom.
