### ISSUE TITLE
No animation for images that where initially outside the frame

### ISSUE THREAD

**Issue by ErikKrause** [fancyapps/fancybox#1564]
Hello,

I ran into a strange problem. I use fancybox 3.1.20 on a zurb foundation powered page. Images that where outside the viewable region don't animate, but simply show up. Images at the beginning of the page animate. See https://codepen.io/anon/pen/zzWmQG First try with one of the first images, then scroll down to a row that hasn't been visible before and try there. I use FF 54 on windows 10 but this is consistent across browsers, tested with Chrome, IE and Edge and on windows 7.

**Comment by fancyapps** [comment]
Hi,

I`m surprised that you describe this feature as "a strange problem" :) The code checks if thumbnails is visible and will animate only if at least some pixels are "really" visible. It is most useful when combining with sliders as it would be weird if animation would start from invisible slide. See this example -  https://codepen.io/anon/pen/Nvbdjg - open same image and navigate to the last slide, closing it will not start zoom-out animation.

**Comment by ErikKrause** [comment]
But the thumbnails are visible! Scroll down the page and click a thumbnail (which must be visible of course). It doesn't animate.

**Comment by fancyapps** [comment]
Oh, sorry, I misunderstood your comment. I`ll try to figure out why is this happening.

**Comment by ErikKrause** [comment]
I think I found it. `<body>` is height: 100% This is a default by foundation. From global.scss: 
` // Must be 100% for off canvas to work`
`html, body { height: 100%; }`
Apparently this leads to a wrong calculation in getThumbPos causing visiblePixelY to be negative.

**Comment by fancyapps** [comment]
Yes, seems that setting `html` height to 100% causes this problem. You can simply fix that using this snippet:

```CSS
.fancybox-enabled {
    height: auto;
}
```

**Comment by Hurmeli** [comment]
This problem still persists. The css snippet didn't change anything for me.
