### ISSUE TITLE
Page jump up if fancybox 3 open

### ISSUE THREAD

**Issue by jan1971** [fancyapps/fancybox#1565]
Halo. 
Its possible fixed position web page under fancybox overlay if fancybox is open?
I can not find a solution :(
We have long page and if image or dialog box is down, after click whole page under overlay jump tu top of body and past close skrol bach down...
Thank you very much for help!
Jan

**Comment by fancyapps** [comment]
Hi,

The script sets `overflow:hidden` to hide scrollbars and that causes this problem. So, just don`t make your page fixed position, I think it can cause other problems, too (especially on mobile devices).
