### ISSUE TITLE
I have to press back twice to leave album,when the fancybox is closed not through back,but through drag down or close button.

### ISSUE THREAD

**Issue by Zzcaocao** [fancyapps/fancybox#1569]
I have to press back twice to leave album,when the fancybox is closed not through back,but through drag down or click close button.

I think when I drag down or click  close button,the url is replace by last page's url,but not go back to the last page,so when I want to leave album,I have to press back twice

**Comment by fancyapps** [comment]
Make sure you are using the latest (currently v3.1.20).

**Comment by Zzcaocao** [comment]
I am sure.
The project use vue-router,fancybox is initialize with data attributes,not has other options.
I can see that the page not go back across the brower's forward button in toolebar, when I close fancybox  through drag down or click close button,

**Comment by Zzcaocao** [comment]
@fancyapps I am sure.
The project use vue-router,fancybox is initialize with data attributes,not has other options.
I can see that the page not go back across the brower's forward button in toolebar, when I close fancybox through drag down or click close button,
