### ISSUE TITLE
modify content before show

### ISSUE THREAD

**Issue by h4mpy** [fancyapps/fancybox#1571]
is it possible to modify slide content in beforeShow event? it works in afterShow (and worked in onComplete event)
```
afterShow: function(instance, slide){
	slide.$slide.find('div').html('1'); //work
},
beforeShow: function(instance, slide){
	slide.$slide.find('div').html('1'); //doesn't work
}

```

**Comment by fancyapps** [comment]
Hi, Have you tried using `afterLoad` callback? 

btw, there is a reference to the content - `slide.$content`

**Comment by h4mpy** [comment]
thanks, it works
```
afterLoad: function(instance, slide) {
	slide.$content.find('...').;
}
```
