### ISSUE TITLE
2 bugs: Increase from second click and does not work back button in browser

### ISSUE THREAD

**Issue by slav-ok** [fancyapps/fancybox#1574]
Video bugs: https://youtu.be/lpMPZ3hjnak

1. On the product page. The first click on the product opens the gallery. Then to enlarge the photo you need to do 2 clicks. At the first click in the gallery, the photo does not increase. How to fix it?
2. If on the product page, click and view the photos in the gallery. Then the back button in the browser does not work.

**Comment by fancyapps** [comment]
Hi,

1) I can not reproduce this on your page and I have never experienced any of these issues.
2) What browser are you using?

**Comment by slav-ok** [comment]
i use browser crome

**Comment by slav-ok** [comment]
chrome*

**Comment by slav-ok** [comment]
1. Please try again, I'm having a problem on some computers
How could I incorrectly install the script?

**Comment by fancyapps** [comment]
Thanks for your feedback. I will push an update at the beginning of the next week and that should fix this.

**Comment by slav-ok** [comment]
thank you so much)

**Comment by slav-ok** [comment]
Did you see both bugs or only one?

**Comment by fancyapps** [comment]
Yes, sorry about that. The first one occurs only in some scenarios (when image aspect ratio is just "right" 😄), therefore it was hard to notice. I think I fixed it recently in my development version, I`ll make some tests to be sure. 
I`ll look what I can do about 2nd one.

**Comment by slav-ok** [comment]
super! I really like the plugin

**Comment by gonzaloemanuelcastillo** [comment]
Hi Fancy. Sorry, could you fix the first bug? I have the same problem in my portfolio 😕

**Comment by slav-ok** [comment]
Yes, pease fix) I am much waiting.

**Comment by fancyapps** [comment]
Hi,

Sorry, I forgot to update this issue, the fixes have been implemented for some time.

**Comment by slav-ok** [comment]
Hello, sorry . Could you fix my bug?
