### ISSUE TITLE
Open posts lightbox via url params

### ISSUE THREAD

**Issue by ola-halima** [fancyapps/fancybox#1575]
I want to add post sharing to my website. Currently, I have posts open up in a fancybox gallery. I'd like to be able to share the link to the posts and have it link back to my post already opened up in the lightbox. Not sure how to do that since fancybox uses data attributes. Is there a way to open a page in lightbox using a url like:
.../archive/post-123?fancy_box=true

**Comment by fancyapps** [comment]
Hi,

While you can open any url using `data-fancybox` attribute by default (for example,  http://fancyapps.com/fancybox/3/#modal ), you can simply trigger click event on your links, too. So, if your url has some attribute like `fancy_box=true`, simply detect it (serverside or JS, it is your choice) and then do something like `$('my_link').trigger('click');`
