### ISSUE TITLE
How to set interaction options for slider/entirely disable zoom

### ISSUE THREAD

**Issue by J0hnGa1t** [fancyapps/fancybox#1576]
I'm very new to javascript and webdesign in general which is why I'm running into some basic problems using the Fancybox 3 plugin. I managed to successfully set it up within the Kirby CMS but I can't figure out how to set the interaction option for my sliders. I would like to globally disable zooming when an image in the open slider is clicked. Instead, the slider should close. In the fancybox 3 documentation I found the options available for interaction, but I fail to implement them into my site. And unfortunately nobody on stackoverflow responded to me when I posted the same question there, which is why I'm posting it here.

As of right now I have the options for my sliders set up like this:

  ```
  <script type="text/javascript">

       $("[data-fancybox]").fancybox({

         thumbs          : false,

         hash            : false,

         loop            : true,

         keyboard        : true,

         toolbar         : false,

         animationEffect : false,

         arrows          : true,

       });

    </script>
```

**Comment by fancyapps** [comment]
Hi,

Just use `clickContent` option:

```JS
$("[data-fancybox]").fancybox({
  thumbs          : false,
  hash            : false,
  loop            : true,
  keyboard        : true,
  toolbar         : false,
  animationEffect : false,
  arrows          : true,
  clickContent    : false
});
```

Demo - https://codepen.io/anon/pen/XaabLJ?editors=1010
