### ISSUE TITLE
Horizontal touch slide

### ISSUE THREAD

**Issue by mdss-single** [fancyapps/fancybox#1577]
How to disable horizontal touch sliding?
If I set modal:true option, then close outside option not working.
I tried to combine both option: modal:true and clickOutside:'close', but it's not working.

**Comment by mdss-single** [comment]
And I see some problem when sliding to left/right non image content.
Layer sliding with scrollbar.
For fix it set overflow:auto for .fancybox-stage and remove oveflow:hidden for .fancybox-slide
![screenshot_3](https://user-images.githubusercontent.com/11454517/29231775-1b621ece-7ef1-11e7-82da-677e1dba5180.png)

**Comment by fancyapps** [comment]
Hi,

Currently, you can only disable touch events entirely using `touch:false` or disable vertical dragging using `touch: { vertical : false }`.
