### ISSUE TITLE
Page scrollbar disappears after closing modal

### ISSUE THREAD

**Issue by iBars** [fancyapps/fancybox#1578]
On [site](http://doma-nk.ru) when I click button "Заказать звонок" (at right top of site, with phone icon) and then close opened modal, scrollbar of site disappearing. How to fix it?

**Comment by iBars** [comment]
It's extremely important issue which stops selling on site.
After closing fancybox page totally unable to scroll

Please, fix it

**Comment by fancyapps** [comment]
Hi,

Please, fix JS errors on your site, for example, this one:

`script_v2.js:88 Uncaught TypeError: Cannot read property 'top' of undefined`

Any JS error can break further execution of the code.
