### ISSUE TITLE
Portrait images not respecting margin on mobile

### ISSUE THREAD

**Issue by ffolkes** [fancyapps/fancybox#1579]
First I want to thank you for always being so helpful and prompt with those who need help. :)

I'm having a problem with only portrait images on mobile not respecting the values set via margin. I have spent hours trying to troubleshoot this. For small-screen devices, I want to have 0 margin. I have it set to 0, 0 and it works perfectly for landscape photos. However portrait-oriented photos have big margins on all sides. I tested changing the non-mobile margin to 0 and resizing my browser's window and it behaves as expected with both landscape and portrait images. So the weirdness is only on mobile, and only portrait images.

**Comment by fancyapps** [comment]
Hi,

Sorry for not being prompt, but I have no clue about your issue. Any screenshot/demo might help.

"margin" option is ignored when viewport width is smaller than 800px and is set to 0. Therefore I do not understand what issue you could have.
