### ISSUE TITLE
fancyBox not work from links rendered through AJAX

### ISSUE THREAD

**Issue by dwlamb** [fancyapps/fancybox#1582]
I am having an issue with fancyBox opening in an iframe for content so-called 'hard-coded' in the DOM vs content that loads in the DOM from an AJAX endless scroll.

To expand on those two meanings:  The page initially loads with 15 div's of content.  Scrolling, more content is loaded. If a link with the requisite class and data tags is of the first 15 is clicked, the content loads as it should in an iframe.  If a link with the requisite class and data tags **after** the first 15 is clicked, the content loads in the browser, replacing the content of the original page.   

The div's for either source are rendered by the exact same php code.  Below are code samples from the DOM

Hard code:
`<a class="moreinfo" data-fancybox-type="iframe" href="http://<site>/detail/70">`

AJAX rendered:
`<a class="moreinfo" data-fancybox-type="iframe"  href="http://<site>/detail/85">`

javaScript:
`$(document).ready(function() {
	$("a.moreInfo").fancybox({
		'type'		:	'iframe'
	});
});`

This problem only materialised after upgrading from version 2.1.5 to version 3.1.20.  Previous to upgrading, the content arrived in the DOM the same way by AJAX call or hard-coded.

I am having the same results with jQuery 1.12.4, 2.2.4 and 3.2.1.  I am having issues with jQuery 3.2.1 and other javaScripts on this site, so I don't want to use that version.

**Comment by fancyapps** [comment]
Hi,

It was quite hard to understand your comment, but I guess what you are looking for is event delegation. You see, v2.x used it automatically, but it is no more possible to do so using jQuery v3, therefore you can enable this feature using `selector` option, example:

```JS
$().fancybox({
  selector : '[data-fancybox="images"]',
  thumbs   : false,
  hash     : false,
});
```

Demo - https://codepen.io/fancyapps/pen/gWvorB
