### ISSUE TITLE
Image scaling

### ISSUE THREAD

**Issue by beliyadm** [fancyapps/fancybox#1584]
Hi!
Thank you for the plugin, I'm using it for a long time.
On version 3 (3.1.20) there was a situation of image scaling after a click on the preview, an example of (http://piarplus.pbelkov.net/contacts) (after the text)
The code is standard: a data-fancybox = "gallery", JS params not use.
Thanks for your help

**Comment by fancyapps** [comment]
Hi,

Please, upgrade jQuery to the latest (at least v3.2.0), because v3.0.x and v3.1.x have a bug that affects calculations.

**Comment by beliyadm** [comment]
Прекрасно, благодарю за совет! Была версия Jquery 3.1.1, обновление до последней 3.2.1 помогло!
