### ISSUE TITLE
fancybox ajax, opens multiple boxes instead of one

### ISSUE THREAD

**Issue by LiamDawe** [fancyapps/fancybox#1585]
Here's an odd one. I'm loading content via AJAX, but fancybox seems to open one for each top level div in the returned content.

So say your returned content is:
```
<div>some content</div>
<div>more content</div>
```
It will open one for each by default.

Is there a way to prevent this, apart from wrapping the entire content in an extra div which is wasteful and weird? Seems really odd behaviour.

Using the download from today from the official site V3.

**Comment by fancyapps** [comment]
Hi,

You have to use some wrapper around all blocks. E.g.:

<div id="awesome_modal">
    <div>some content</div>
    <div>more content</div>
</div>
