### ISSUE TITLE
clickOutside not working

### ISSUE THREAD

**Issue by cvharris** [fancyapps/fancybox#1586]
I'm trying to set `clickOutside` to prevent the overlay from triggering the close, but nothing seems to work globally for all my fancyboxes

```
$.fancybox.defaults.clickOutside = false
```

```
$('[data-fancybox]').fancybox({
	clickOutside: false
})
```

Am I missing something here? Not even changing their default behavior works.

**Comment by fancyapps** [comment]
Hi,

This demo - https://codepen.io/anon/pen/EvEpQe - should help to understand the difference between `clickOutside`, `clickSlide` and `clickContent` options.

![firefox_screenshot_2017-08-21t08-28-19 195z](https://user-images.githubusercontent.com/1055589/29510513-b29a627c-8664-11e7-81bb-6d2722a5270e.png)

fancyBox v3 is designed to act like slider/carousel and this slider matches window dimensions by default, but you can resize if needed. So, in this example:

- `clickOutside` - when user clicks outside the slider (red area);
- `clickSlide` - when user clicks on the slide (blue area);
- `clickContent` - in this demo, the image.

**Comment by vhugogarcia** [comment]
This issue still persists. Even setting the option to false the user can close the modal window. 

Is there a workaround or a potential fix to this bug?

**Comment by fancyapps** [comment]
@vhugogarcia There is nothing to fix as there are no issues whatsoever.

**Comment by jonbeddoes-avast** [comment]
@fancyapps I can confirm there does appear to be an issue with setting clickOutside, at least with the iframe lightbox type. It doesn't seem to matter where the preference is set (e.g. as as default, inside opts or inside iframe, it never gets fired). Furthermore, a search of the code would suggest it's not actually hooked up to anything? What are we missing? https://github.com/fancyapps/fancybox/search?utf8=%E2%9C%93&q=clickOutside&type=

**Comment by jonbeddoes-avast** [comment]
@fancyapps here is the code sample:

`$.fancybox.open({
								src  : 'https://www.lightbox.com/',
								type : 'iframe',
								opts : {
									toolbar  : false,
									smallBtn : false,
									**clickOutside: false,**
									iframe : {
										preload : false,
										css : {
											width : '500px',
											height: '300px',
										} // css
									} // iframe
								} // opts
							});`

**Comment by fancyapps** [comment]
@jonbeddoes-avast 

Did you read my first comment? You are probably looking for `clickSlide` option:
https://codepen.io/anon/pen/YrJjmo?editors=1010

And you will find the code handling click event here - https://github.com/fancyapps/fancybox/blob/master/src/js/guestures.js#L855

**Comment by jonbeddoes-avast** [comment]
@fancyapps - I tried clickSlide and it indeed worked, thank you. I'm not really sure why though as the red area is clearly outside the lightbox? With an iframe type I wouldn't exactly describe the blue area as the background of the lightbox, if that makes sense? The new issue is now I can click outside the window and drag the modal, and if I let go at the same time then I am able to effectively gesture the lightbox away, which is not what I intended.

**Comment by fancyapps** [comment]
@jonbeddoes-avast You see, fancyBox v3 is actually like a big slider that covers whole screen. So, by default, you can only see one slide (blue area). But, if you wish, you can resize this sliding area (thus making red area visible) and therefore there is a need for two separate click types - when clicks on the slide and when outside.

Why don't you just disable touch events?
