### ISSUE TITLE
Add jQuery Version 3.2.1 [Documentation]

### ISSUE THREAD

**Issue by makakken** [fancyapps/fancybox#1587]
ADD JQUERY VERSION 3.2.1 to the documentation page please.

i've really had trouble of the image-positioning using **jquery 3.1.1**
would have been really nice if the documentation would explicitly say that you have to user jquery 3.2.1. it would have saved me hours.

Ok, it's in the code samples, but nowhere in the setup section you find another hint. so if you're not a copy and paste person you will probably not see it.

**Comment by fancyapps** [comment]
Hi,

Thanks for suggestion and sorry about that. I have included a note to the docs - http://fancyapps.com/fancybox/3/docs/#introduction
