### ISSUE TITLE
thumbnails on mobile

### ISSUE THREAD

**Issue by yangkennyk** [fancyapps/fancybox#1588]
I know that the thumbnails on mobile are not included in v3. I'm trying to create a workaround and cannot seem to figure it out.

the problem is that clicking on thumbnails does not work with touch events, only when it's a click. I've been digging through the source and cannot seem to figure out how to disable that feature.

I basically just want to enable thumbnails on mobile because there are a lot of photos in the gallery and I want to imitate the thumbnail gallery feature in v2 of fancybox.

any ideas?

**Comment by fancyapps** [comment]
Hi,

Right now, thumbs icon is just hidden using CSS. If you wish, you can remove this limitation here - https://github.com/fancyapps/fancybox/blob/master/src/css/thumbs.css#L12

In next releases, there will be an option to enable/disable thumbs on small screens.

**Comment by yangkennyk** [comment]
the thumbnails do not work with touch events though right now. when you tap the thumbnails even with them showing, nothing happens. they only respond to click events.

**Comment by fancyapps** [comment]
Hi,

They are now enabled by default on mobile devices (starting from v3.2.0).

**Comment by nebrot** [comment]
How is it now possible to show the thumbails on start only on desktop, but not for mobile-devices?

Our current script:

```
$().fancybox(
{
	selector: "[data-fancybox]",
	infobar: true,
	thumbs:
	{
		autoStart: true
	}
});
```

**Comment by fancyapps** [comment]
You can either use different options depending on your conditions (something like `$().fancybox( myConfig );`) or use built-in `mobile` option:

```JS
thumbs : {
    autoStart: true
},
mobile : {
    thumbs : {
        autoStart: false
    }
}
```

**Comment by nebrot** [comment]
Works like a charm, thank you!
