### ISSUE TITLE
Caption should not overlap

### ISSUE THREAD

**Issue by dermansi** [fancyapps/fancybox#1590]
Hey there,

Is it possible that the image respects caption height and adjusts accordingly? I don't want the caption to overlap the image. 

Thanks in advance

**Comment by fancyapps** [comment]
Hi,

Sorry, this is not (yet) implemented in v3 to reduce complexity. You can, for example, increase bottom margin to create more free space for the caption.

**Comment by Webdude737** [comment]
This is definitely something we need as well.

**Comment by acwolff** [comment]
I strongly support this Feature request,

**Comment by fancyapps** [comment]
This feature has been implemented in v3.5 by simply adjusting bottom margin to match caption height.

**Comment by acwolff** [comment]
Difficult: the total caption heigth depends on the length of the caption, it could be 2 or more lines!

**Comment by seewishnew** [comment]
How about limiting the caption height and implementing a scrollbar for the caption when there might be an overlap of image and caption?

**Comment by emage** [comment]
Caption height cannot be a fixed value as we do translation so it varies base on the language.
