### ISSUE TITLE
Wordpress integration

### ISSUE THREAD

**Issue by Mojocom** [fancyapps/fancybox#1594]
Hi,

Thank you for your great work ! Just a quick question. I would like to implement Fancybox 3 in wordpress. With the v2, caption were ok (using alt attribute) but now, they disappear. How can we fix that ?

$("a[href$='.jpg'], a[href$='.png'], a[href$='.jpeg'], a[href$='.gif']").attr('data-fancybox', 'img').fancybox();
$('[data-fancybox="img"]').fancybox({
	helpers: {
    	overlay: { locked: false },
  },
}
);

Thank you for your help !

Regards

**Comment by fancyapps** [comment]
Hi,

It is very easy. You can find some additional demos at FAQ section.

```JS
$( '[data-fancybox]' ).fancybox({
  caption : function( instance, item ) {
    return $(this).find('img').attr('alt');
  }
});
```

Demo - https://codepen.io/anon/pen/BdPbwb?editors=1010

**Comment by Mojocom** [comment]
Thanks a lot, it works perfectly!!

Another question. We have custom post type with multiple image using ACF plugin to present hotel room. We would like to use fancybox 3 to create gallery for each type by clicking on one thumbnail. Is it possible to use fancbox for that ?

Regards

**Comment by kloneets** [comment]
As it is ACF, you are writing your own markup for display those images (I'm guessing it is repeater field with image field inside). So - you can display link with first image and add all other images as only links with same "rel" and "class" but without content/without displaying them. So - you will get one image for clicking and links to other images.

**Comment by Mojocom** [comment]
Great, seems to work, juste have now a problem with the caption which is not wording correctly with the alt attribute of the image in wordpress back office.

a href="<?php echo $img_01 ?>" data-fancybox="images-<?php echo $postid ?>">
                                <div class="img-room">
                                    <img src="<?php echo $img_01 ?>" alt="<?php the_title()?>" class="img-responsive" />
                                    <div class="hover"><i class="icon icon-photo"></i></div>
                                </div>
                            </a>
                            <a class="hide" href="<?php echo $img_02 ?>" data-fancybox="images-<?php echo $postid ?>" title="Test"></a>
                            <a class="hide" href="<?php echo $img_03 ?>" data-fancybox="images-<?php echo $postid ?>"></a>
                            <a class="hide" href="<?php echo $img_04 ?>" data-fancybox="images-<?php echo $postid ?>"></a>

Is that correct ?
