### ISSUE TITLE
Styles for ajax window

### ISSUE THREAD

**Issue by kilnimir** [fancyapps/fancybox#1595]
in ajax window i had few tags like

```
<div></div>
<script></script>
<script></script>
<script></script>

```
and we had blank window with close button for each script tag
i change .fancybox-slide>* to .fancybox-slide>:not(script) in css file, but there are still close buttons in script tags.

**Comment by fancyapps** [comment]
Hi,

Try last update (v3.1.25).

**Comment by aldoexpert** [comment]
I still get bad style and I use the latest version
in fancybox3 I found many bad style
this my screenshot
https://prnt.sc/gq69hs

**Comment by fancyapps** [comment]
@aldoexpert try not to use bad style.
