### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't.newPoints[1].x')

### ISSUE THREAD

**Issue by xcopy** [fancyapps/fancybox#1598]
Hey,

I'm getting errors from Sentry:

**TypeError**
undefined is not an object (evaluating 't.newPoints[1].x')

Exception:

... in **onZoom** at line ...
```
{snip} tageOfImageAtPinchPointY,m=(t.newPoints[0].x+t.newPoints[1].x)/2-n(e).scrollLeft(),v=(t.newPoints[0].y+t.newPoints[1].y)/2-n(e).scrollTop(), {snip}
```

... in **ontouchmove** at line ...
```
{snip} ing?t.onSwipe():t.isPanning?t.onPan():t.isZooming&&t.onZoom()}},c.prototype.onSwipe=function(){var t,a=this,o=a.isSwiping,s=a.sliderStartPos {snip}
```

but, don't know how to resolve it.

**Device:** iPhone
**Browser:** Mobile Safari 10
**OS:** iOS 10.x

**Comment by fancyapps** [comment]
Hi,

Thanks, but how did you get these messages? I can not reproduce. Anyway, I`ll add additional checks.

**Comment by xcopy** [comment]
@fancyapps, what you mean how?

Obviously when someone try to zoom in/out image. Please pay attention to device, browser & OS info (only iPhone, Mobile Safari, iOS).

**Comment by fancyapps** [comment]
I asked this, because I debug the code on iPhone by connecting to Mac. And Safari console does not show any message.

btw, are you using the latest fancyBox (currently v3.1.20)?

**Comment by xcopy** [comment]
Yeah, we use `v3.1.20`.

Try to imitate slow connection (as option).
