### ISSUE TITLE
Callbacks onChange

### ISSUE THREAD

**Issue by Solomon2014** [fancyapps/fancybox#1599]
Hello, i need detect when slide change or when prev/next clicked, how i do it? I dont found it in documentation. Thx.

**Comment by fancyapps** [comment]
Hi,

You are probably looking for `beforeShow` event.

See http://fancyapps.com/fancybox/3/docs/#events

**Comment by ffd8** [comment]
I needed this exact functionality to run custom JS on elements (input tags) within the caption everytime a slide is changed. The main list of callbacks (under API Events) in the docu, came closest with `beforeload/afterLoad` – however those only fired the first time content is shown. To get an event fired EVERY time a slide changes, learned from #2048 that the callback I needed was `clickContent`. I had imagined something more generic like `slideChange` (luckily keyboard navigation also fires that `click`) I suggest adding it to the top of the list of API Event's, as they appear to be in order of frequency. 

(ps.. amaazing library!)
