### ISSUE TITLE
Fancybox prevents clicking into canvas

### ISSUE THREAD

**Issue by noodle71** [fancyapps/fancybox#1600]
Within file guestures.js, there's a function named isClickable.

This function prevents clicks when fancybox content is a canvas element. 

You can't get canvas click listeners using

```
$.isFunction( $el.get(0).onclick )
```

You have to add canvas within the list of possible options to get it to work:
```
$el.is('a,button,input,select,textarea,canvas')
```

**Comment by fancyapps** [comment]
Hi,

Well, I am not sure that everyone would want to make canvas element clickable. Could you just simply disable touch guestures?

**Comment by MovehMakeh** [comment]
Did you possibly mean like the ability to click and draw inside a canvas? Because I am having a similar issue.

**Comment by fancyapps** [comment]
Hi,

With the latest update (v3.1.25), simply add `data-selectable="true"` to your canvas element to make it clickable.
