### ISSUE TITLE
Toolbar/captions/nav hidden after delay?

### ISSUE THREAD

**Issue by andyiwest** [fancyapps/fancybox#1605]
I've searched through the docs but cannot find a way to disable this

After 2-3 seconds of inactivity, the following gets removed from the fancybox class
fancybox-show-toolbar
fancybox-show-nav
fancybox-show-caption

How can I prevent this from happening? I always want them all showing

**Comment by andyiwest** [comment]
On slideshow mode, only the first slide has the above 3 classes, the rest just scroll through with only images shown

**Comment by fancyapps** [comment]
Hi,

By default, toolbar, caption and navigation elements are hidden after 4s of inactivity. This is useful when playing slideshow.

You can disable this by using "idleTime" option (set `idleTime: false`).

**Comment by andyiwest** [comment]
Late reply, but cheers mate
