### ISSUE TITLE
experience issues with image zooming on iphone7

### ISSUE THREAD

**Issue by iVolume** [fancyapps/fancybox#1606]
Hello! I found the issue with image zooming on iphone7 in Safari ( may be other browsers too, i'm not sure ). When i said zooming i mean expanding by fingers. I got the latest jQuery. And i was trying to disable following properies touch: { vertical: false, momentum: false } but it's don't make any effect. Any thoughts about it?

**Comment by fancyapps** [comment]
Hi,

By `isssues` you mean some issue while zooming or the issue is that you can not disable zoom gestures (there is not option for that, yet)?

**Comment by iVolume** [comment]
Hey, 

i was mean the safari problem - "Safari web content quit unexpectedly" and webpage has reloaded after this. But i found out that this problem is not related with the fancybox and appears when you increase the content too much. This is the problem of iphone7 and their owners so i guess you could close this issue. And many thanks for the quick response!

**Comment by fancyapps** [comment]
Hi,

I have experienced this issue when trying to open too large images. I do not recommend using pictures whose dimensions exceed screen dimensions more than 1.5 times.
