### ISSUE TITLE
Initial size is no calculated correctly

### ISSUE THREAD

**Issue by sharpdevel** [fancyapps/fancybox#1607]
Hi everybody,

I just added fancybox 3 to my website youmoto.com. It works perfectly except one flew. 

I have img-tags wrapped in a-tags decorated with (data-fancybox="group"). When I click the first image the fancy box gallery viewer opens and wraps the image with an <div fancybox-image-wrap......></div>. The size of this div is somehow calculated and then set as the style of that div. However the size is calculated wrong for the first image. Its way to big an flows to the lower right of the screen.

The issue vanishes when navigating from one to another picture.

First picture shows the initial view
Second image the view after a click on a picture in the page (but it stays that way for just a second)
Third image shows the end state

Live version can be viewed here: http://www.youmoto.com/Vehicles/Details/754b1b5e-013e-4302-9ad2-215ace066bd4

![1](https://user-images.githubusercontent.com/10990167/29899843-261c9b94-8dee-11e7-9460-b66ab844ce00.png)
![2](https://user-images.githubusercontent.com/10990167/29899845-261dcfe6-8dee-11e7-8387-4d92ab710196.png)
![3](https://user-images.githubusercontent.com/10990167/29899846-2623c45a-8dee-11e7-948d-403f677cd178.png)

**Comment by kloneets** [comment]
Try to upgrade jQuery to latest version.

**Comment by sharpdevel** [comment]
Thanks a lot. That did the trick :-)

Did not mention a new jquery version since there is no new nuget package :-O

What's the difference between 3.1.1 and 3.2.1 that breaks it?

**Comment by kloneets** [comment]
I think, it was this bug https://github.com/jquery/jquery/issues/3193

**Comment by fancyapps** [comment]
Yes, @kloneets is right, some jQuery versions have a bug that affects calculations. Therefore there is a red warning here - http://fancyapps.com/fancybox/3/docs/#introduction about this :)
