### ISSUE TITLE
Problem when dynamically adding new pictures using jQuery

### ISSUE THREAD

**Issue by B0rner** [fancyapps/fancybox#1608]
When new pictures are added to an existing group using jquery (for example if they are loaded form an JSON API), it seams, that fancybox does not notice the new items and is not applied on the new pictures.

Here is an example, where new pictures are added after 3 seconds.

https://codepen.io/anon/pen/QMzmxx

**Comment by fancyapps** [comment]
Hi,

I`m sorry, I have made a silly mistake. Thanks for reporting and your demo is very useful.

**Comment by fancyapps** [comment]
This should be fixed in v3.1.21

**Comment by B0rner** [comment]
Gerat, that's it. Thank you for patching fancybox "same-day".
Do you know, why this current version 3.1.22 is not available on bower?

**Comment by fancyapps** [comment]
@B0rner I`ll make couple of patches and then will tag a new release. It will we available afterwards (including CDN).
