### ISSUE TITLE
Template and custom layout

### ISSUE THREAD

**Issue by Mojocom** [fancyapps/fancybox#1610]
Hi,

I would like to use two templates in my website : one for the gallery and one for product presentation with columns as shown on the demo. How can we achieve that ? Is there any tuto/doc to help as we are not "specialist" ?

Thanks

**Comment by fancyapps** [comment]
Hi,

You simply initialize fancyBox with different options for each gallery. You can use `baseTpl` if you want to have completely different layout or simply use `baseClass` and then use CSS to set different style.

**Comment by Mojocom** [comment]
Ok thanks. And how can I use ACF field inside baseTpl to obtain something like :
`'<div class="fancybox-caption"><?php the_field('example') ?></div>' +`

**Comment by fancyapps** [comment]
Well, if you want to pass some PHP variable, then you, probably, have to put your JS code inside your PHP template file, somewhere before `</body>` tag.

**Comment by Mojocom** [comment]
Is it possible to call a div as you did on the product demo ?

`$('[data-fancybox]').fancybox({
		baseTpl	:
		'<div class="fancybox-container fancybox-custom-layout" role="dialog" tabindex="-1">' +
			'<div class="fancybox-bg"></div>' +
			'<div class="fancybox-inner">' +
				'<div class="fancybox-infobar">' +
					'<button data-fancybox-prev title="{{PREV}}" class="fancybox-button fancybox-button--left"></button>' +
					'<div class="fancybox-infobar__body">' +
						'<span data-fancybox-index></span>&nbsp;/&nbsp;<span data-fancybox-count></span>' +
					'</div>' +
					'<button data-fancybox-next title="{{NEXT}}" class="fancybox-button fancybox-button--right"></button>' +
				'</div>' +
				'<div class="fancybox-toolbar">' +
					'{{BUTTONS}}' +
				'</div>' +
				'<div class="fancybox-navigation">' +
					'<button data-fancybox-prev title="{{PREV}}" class="fancybox-arrow fancybox-arrow--left" />' +
					'<button data-fancybox-next title="{{NEXT}}" class="fancybox-arrow fancybox-arrow--right" />' +
				'</div>' +
				'<div class="fancybox-stage"></div>' +
				'<div class="fancybox-caption-wrap">' +
					'<div class="fancybox-caption"></div>' +
					'<div class="quick-view-aside"></div>' +
				'</div>' +
			'</div>' +
		'</div>',
		onInit : function( instance ) {
			var $element = instance.group[ instance.currIndex ].opts.$orig;
			var form_id  = $element.data('qw-form');

			instance.$refs.container.find('.quick-view-aside').append(

                // In this example, this element contains the form
                $( '#' + form_id ).clone( true ).removeClass('hidden')
            );

        },
		toolbar:true,
		infobar:true,
        caption: function(instance, item) {
            return $(this).find('img').attr('alt');
        }
		
    });`

**Comment by fancyapps** [comment]
By ` call a div ` you mean to open inline element, e.g., some hidden div?

And what is the issue of this code? Have you created all elements correectly? In this sample, `onInit` method looks for clicked link and that link should have an attribute named `data-qw-form`. That attribute should contain an id of some hidden element.

**Comment by Mojocom** [comment]
I found my error, just forget the data-qw-form element !
Thanks again for your help !

**Comment by Mojocom** [comment]
One last question !

We have custom post type for which we would like to use a specific template. $('[data-fancybox="room-ID"]').fancybox({

Is it possible for fancybox to recognize all the items without create one for each id ?

**Comment by fancyapps** [comment]
You can simply use jQuery "attributeStartsWith" selector - https://api.jquery.com/attribute-starts-with-selector/

Something like `$( 'input[data-fancybox^="room-"]' ).fancybox(..)`

**Comment by Mojocom** [comment]
Thanks a lot, it works ! I know have one last problem with a date picker (pickadate.js) which is not working in fancybox. Calendar appears but value don't go in the input but can't figure out why (example on http://www.hotel-tremplin.com/hotel/nos-chambres/#room-1460-1) ?

**Comment by fancyapps** [comment]
Maybe you should initialize this datepicker after opening fancyBox (within beforeShow or afterShow callback).

**Comment by Mojocom** [comment]
Thank you for the answer. I already tried afterShow but it doesn't works. IS that correct ?

afterShow : function( instance ) {
			var $element = instance.group[ instance.currIndex ].opts.$orig;
			var form_id  = $element.data('qw-form');
			instance.$refs.container.find('.quick-view-aside').append(
                // In this example, this element contains the form
                $( '#' + form_id ).clone( true ).removeClass('hidden')
            );

        },

**Comment by fancyapps** [comment]
Well, it could be something like this:

```JS
afterShow : function( instance ) {
  var $element = instance.group[ instance.currIndex ].opts.$orig;
  var form_id  = $element.data('qw-form');
  
  var $form = $( '#' + form_id ).clone( true ).removeClass('hidden');
  
  instance.$refs.container.find('.quick-view-aside').append( $form );
  
  $form.find('.datepicker').pickadate();

},
```

**Comment by Mojocom** [comment]
Does not make the trick unfortunately :( Still have the problem
