### ISSUE TITLE
Fancybox semi-breaks unrelated JS?

### ISSUE THREAD

**Issue by EndeavourAccuracy** [fancyapps/fancybox#1613]
At [this CodePen](https://codepen.io/mynimi/pen/iKuHG), when "Search" is clicked once, an overlay with input field shows up.

When I add Fancybox to the aforementioned CodePen, one has to click twice for the overlay to show up.
This modified behavior can be replicated (and tested) as follows:
1. Visit the CodePen page.
2. At the top right of the page, use Settings -> JavaScript to add an additional external JavaScript under jQuery:
`//cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.20/jquery.fancybox.js`
(I have also tested this locally with the latest 3.1.23.)
3. Click "Close" if you haven't already.
4. You now have to click "Search" twice to get the overlay.

**NOTE:** Every time you want to test this, you have to redo the above steps. The reason is that the first click on "Search" adds an anchor #search in the URL. This then 'fixes' the search overlay and any additional clicks will make the overlay show up as intended.

My question: why does Fancybox semi-break the seemingly unrelated overlay JavaScript?

**Comment by fancyapps** [comment]
Hi,

There are two solutions to this issue:

1. Add this line to disable hash module:

    `$.fancybox.defaults.hash = false;`

    Demo -  https://codepen.io/anon/pen/GvzaoY

2. Change id of your "search" element. Demo - https://codepen.io/anon/pen/wqNbWb

You are right about the cause. fancyBox watches "hashchange" event and triggers click event on matching element, e.g. changing hash to "#search" will trigger click event to `<a href="#search"></a>` element to open `<div id="search">..</div>` element into fancyBox. 

Therefore your overlay opens and immediately closes.

**Comment by EndeavourAccuracy** [comment]
Thanks for the (quick) reply.
