### ISSUE TITLE
error with jquery-toast-plugin

### ISSUE THREAD

**Issue by bolechen** [fancyapps/fancybox#1614]
when i use fancybox 3 with jquery.toast plugins (https://github.com/kamranahmedse/jquery-toast-plugin)
is have error msg in console
`"undefined is not an object (evaluating 'i.opts')"`

debug link: https://codepen.io/bolechen/pen/YxgRvK

**Comment by fancyapps** [comment]
Hi,

Very interesting issue. There are two reasons this message appears:

1) This toast plugin is not following good practices of coding and is triggering events without namespacing them;

2) fancyBox does not expect that other scripts might be poorly written :)

I`ll add some additional checks to overcome this issue.

**Comment by fancyapps** [comment]
The last commit contains a fix.
