### ISSUE TITLE
Feature request: add an entire directory of images instead of having to list individually

### ISSUE THREAD

**Issue by mike-u** [fancyapps/fancybox#1615]
First of all I really like Fancybox and I'm very thankful for it. However I don't think I'm the only one who has a separate directory of images for fancybox to display, and it's a little tedious writing out `"<a data-fancybox="gallery" href="assets/img/fancyboxphotos/image.jpg"></a>"` many times. I wish I could just call "href="assets/img/fancyboxphotos" once and have it autopopulate. Maybe this is already possible and I'm just too daft to see it?

**Comment by kloneets** [comment]
Fancybox cannot know what is placed on your server. It is client side script, so fancybox cannot implement this feature without server-side scripting. Servers can differ both in technologies and persmissions, so I think this feature will never be implemented.

**Comment by fancyapps** [comment]
Hi, @mike-u!

That is what server-side languages like PHP are meant for. fancyBox is written in JavaScript and is executed in a browser.

So, I suggest to replace this work by few lines of PHP/Ruby/whatever you prefer.
