### ISSUE TITLE
Ignore Fancybox Trigger 

### ISSUE THREAD

**Issue by quantenparallaxum** [fancyapps/fancybox#1617]
Hey,
I would love to have the possibility to embed images in my webpage which do not open/trigger fancybox but are present in the gallery if fancybox was opened by clicking on another image. 
Is there some sort of data attribute or how can I achieve this behaviour?

**Comment by fancyapps** [comment]
Hi,

There is currently no such option out of the box. Anyway, you can create your own click event and then  display fancyBox using `$.fancybox.open( [ your collection of objects ] );`
