### ISSUE TITLE
how to target data-src=""

### ISSUE THREAD

**Issue by neuropass** [fancyapps/fancybox#1620]
Hi,

many lazy loading techniques require to replace the src="" with a loading.gif or 20x20 placeholder while adding the data-src="" with the real image path.

This fails the fancybox to load the right image.

How can I change this behavior and have fancybox to load the data-src instead of the src?
I hope this makes sense.

Thanks in advance.

**Comment by fancyapps** [comment]
Hi,

What you mean by " load the data-src instead of the src", the script already looks for `data-src` attribute. See this demo - https://codepen.io/anon/pen/boEwwo?editors=1000

Anyway, you can always create your own click event and start fancyBox using `$.fancybox.open()`
