### ISSUE TITLE
Moving the fancyBox pop up

### ISSUE THREAD

**Issue by MovehMakeh** [fancyapps/fancybox#1621]
Hello,

I want to be able to have a canvas that you can draw on inside my fancyBox, but it's not useable as when you click and try to draw...it just moves the fancyBox and closes this.

Is there a way to disable this so I can functionally use the canvas?

Thanks!

**Comment by MovehMakeh** [comment]
So I disabled touch gestures in my code, yet I can still pull the fancyBox around.

**Comment by MovehMakeh** [comment]
Still having this problem....is anyone available to assist me a bit?

**Comment by fancyapps** [comment]
Hi,

With the last update (v3.1.25) it is now possible to add `data-selectable="true"` to make any element clickable.

**Comment by MovehMakeh** [comment]
Cool, when will v3.1.25be available over the CDN?

**Comment by fancyapps** [comment]
Sorry, I forgot to inform here that it is already available - https://cdnjs.com/libraries/fancybox
