### ISSUE TITLE
Pictures in gallery of the preview are duplicated

### ISSUE THREAD

**Issue by andryshok** [fancyapps/fancybox#1622]
Pictures in gallery of the preview are duplicated, See the screenshots.
![1](https://user-images.githubusercontent.com/10627665/30247845-042ce996-9625-11e7-81f7-c38822ecd9d6.jpg)
![2](https://user-images.githubusercontent.com/10627665/30247847-08df76fc-9625-11e7-8746-0e7b6e9c9d1e.jpg)

**Comment by fancyapps** [comment]
Hi,

Looks like you are combining fancyBox with carousel script and that script creates duplicated (probably to enable looping) and therefore fancyBox does what is does - creates gallery from all existing links.

**Comment by andryshok** [comment]
Yes, and it has appeared. Excuse and thanks for the help.

**Comment by fancyapps** [comment]
Well, I would suggest to either hide thumbnails (so user would not notice duplicates) or create custom click event and call fancyBox from within using `$.fancybox.open()`.

**Comment by Mielnik** [comment]
If you use a slick script, add: ` infinite: false`

Example:
`$('.images').slick({
        dots: true,
        arrows: true,
        lazyLoad: 'ondemand',
        infinite: false,
    });`
