### ISSUE TITLE
Fancybox generates multiple close buttons instead of one

### ISSUE THREAD

**Issue by gwbonline** [fancyapps/fancybox#1623]
I use Fancybox3 to open a AJAX windows. The script generates four close buttons. One to actually close the window. And three extra buttons using my sitemap link and two other links that are no part of the AJAX window content. What causes this behavior?

**Comment by fancyapps** [comment]
Hi,

You probably have multiple elements, simply create some wrapping element.

**Comment by gwbonline** [comment]
What do you mean by that? It's just one line of Fancybox code to open an AJAX window. You can see an example at: http://beta.degeintrappers.nl/vereniging/foto-s

click 'Dansgala Lingewaard (januari 2017)' to open the AJAX window

**Comment by fancyapps** [comment]
I was thinking of their content returned by ajax. So, your ajax request returns something like this:

```HTML
<div>..</div>
<link>..</link>
<meta></meta>
```
and simply add wrapping element around them, something like this:

```HTML
<div class="modal-body">
    <div>..</div>
    <link>..</link>
    <meta></meta>
</div>
```

**Comment by gwbonline** [comment]
I tried this solution and it doesn't help. There are still three extra close buttons. Why is Fancybox using the canonical link and the sitemap url from the head section? As test content I used your AJAX example content in my own template. I'm sorry for occupying you with this but I need some more help with this.

**Comment by fancyapps** [comment]
Have you tried this solution on the page you provided earlier? I see no changes. I am wondering why you are adding these sitemap and other tags, maybe your CMS does this automatically?

**Comment by gwbonline** [comment]
I removed it because it didn't work. Now I added it again for you to see. Yes, my cms does add the sitemap link and the canonical link. I can disable those links if they weren't important.

**Comment by gwbonline** [comment]
I even want to pay you some money to help me out with this. I tried the wrapper and maybe I’m still doing something wrong.

Van: Jānis Skarnelis<mailto:notifications@github.com>
Verzonden: zondag 10 september 2017 19:54
Aan: fancyapps/fancybox<mailto:fancybox@noreply.github.com>
CC: gwbonline<mailto:info@willembosma.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [fancyapps/fancybox] Fancybox generates multiple close buttons instead of one (#1623)


Have you tried this solution on the page you provided earlier? I see no changes. I am wondering why you are adding these sitemap and other tags, maybe your CMS does this automatically?

**Comment by gwbonline** [comment]
A wrapping element around the content that is shown in the AJAX window with class modal-body didn’t do anything. I still have three unnecessary close buttons. What am I missing here?

**Comment by fancyapps** [comment]
See my 2nd comment, I do not know what else to add. Please, remove these unnecessary elements or wrap ALL of your content into some wrapping element.

**Comment by gwbonline** [comment]
I understand the purpose of the wrapping element. But how does Fancybox know to take the content in that wrapper?

**Comment by fancyapps** [comment]
fancyBox simply creates ajax request and places received content into the slide. Then it appends close button (from "smallBtn" template) using jQuery`s `appendTo` method. The side-affect of this method is that if target is collection of multiple elements, content is appended to each of them. 

Well, OK, I`ll change the logic's a bit to get rid of this issue.

**Comment by gwbonline** [comment]
Thanks! Then I can keep using Fancybox. I’ve used it since the first version.
