### ISSUE TITLE
Possible to modify package.json main to point to unminified js?

### ISSUE THREAD

**Issue by outofcontrol** [fancyapps/fancybox#1624]
package.json main is currently:

    "main": "./dist/jquery.fancybox.min.js",

I'd imagine many folks using yarn/npm are minifying JS themselves. Would it make more sense to change main to instead be:

    "main": "./dist/jquery.fancybox.js",

This change avoids corruption when double minifying jquery.fancybox.min.js.

**Comment by fancyapps** [comment]
Hi,

Good point. I`ll change that.

**Comment by outofcontrol** [comment]
Super, thank you. This also resolves closed issue #1554

**Comment by fancyapps** [comment]
The last commit contains this change.
