### ISSUE TITLE
Youtube not working

### ISSUE THREAD

**Issue by onmarketing** [fancyapps/fancybox#1625]
Hi,

I have purchased FancyBox 3 licences. Youtube is not working, does anyone know about it see screenshot.

![capture](https://user-images.githubusercontent.com/29661125/30341259-4d6b895e-97ed-11e7-9c63-7070e3cad0b9.PNG)

Here coding:

`<a href="https://www.youtube.com/embed/V2txTmVvXeQ?rel=0&showinfo=0" data-fancybox class="play-btn fa fa-play"></a>`

Thanks,

Shaun.

**Comment by fancyapps** [comment]
Hi,

This link probably is not recognized, try using `https://www.youtube.com/watch?v=V2txTmVvXeQ`

**Comment by fancyapps** [comment]
Since it works fine for me - https://codepen.io/anon/pen/BwapXG?editors=1000 - and you have not given link to live page, I do not know what else to suggest.
