### ISSUE TITLE
How to set fancybox gallery slider delete button?

### ISSUE THREAD

**Issue by Sathiyamm** [fancyapps/fancybox#1626]
How to set/create delete button in fancybox gallery slider toolbar using jquery ? Please send references or examples?
Reference: http://fancyapps.com/fancybox/#examples

**Comment by fancyapps** [comment]
Hi,

If you refer to creating button in the toolbar, here are couple of examples:

- Add zoom icon - https://codepen.io/anon/pen/boGPZx
- Download button - https://codepen.io/fancyapps/pen/JJPYLL (from docs/faq section)
