### ISSUE TITLE
fancybox-slide--complete in Safari 9.1.1?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1628]
Hey,

I'm running the confirm box that rotates and fades in that you had in one of your demos a while ago. I just noticed that it doesn't work in older versions of Safari. It seems like it never reaches the .fancybox-slide--complete state where it should go to full opacity and finished rotation. Any ideas?

```
.fancy-confirm {
    border-radius: 3px;
    box-shadow: 0 7px 8px -4px rgba(0, 0, 0, 0.2), 0 13px 19px 2px rgba(0, 0, 0, 0.14), 0 5px 24px 4px rgba(0, 0, 0, 0.12);
    max-width: 550px;
    opacity: 0;
    padding: 50px !important;
    transform: translate(30%) translateZ(600px) rotate(10deg);
    transition: all 0.3s ease 0s;
}
.fancybox-slide--complete .fancy-confirm {
    opacity: 1;
    transform: translate(0%) translateZ(0px) rotate(0deg);
}
```

**Comment by fancyapps** [comment]
Hi,

What version of Safari are you using and are you using fancyBox v3.1+?

**Comment by seabasss** [comment]
Safari 9.1.1 and FB 3.1.15

I just upgraded to 3.1.24 and it seems to work! But all the backgrounds got lighter (small fix I assume), the animation of the confirm boxes are now super slow (maybe also easy fix) and every time I close a fancybox it fades out and gives a "hard snap" at the end. Before it just beautifully faded out to nothing.

Any ideas about any of those things? The only thing I did was replace the js and css code to the newest FB version.

Thanks!

**Comment by fancyapps** [comment]
Could you try this approach - https://codepen.io/anon/pen/GMJRON ?

**Comment by seabasss** [comment]
Seems to be working, and I figured out the background opacity!

Now, just if you have any ideas on the harder fades? I can make a video with how it looked like in .15 vs .24 if it helps?

**Comment by fancyapps** [comment]
Ok, if you don`t mind taking time.

**Comment by seabasss** [comment]
Maybe not the best example, but the first part shows .24 and the second time the white box disappears is .15. Look how it snaps in the first one while the second one just dissolves.

https://www.dropbox.com/s/b2p099ynx6dfewx/FB%20snap.mov?dl=0

**Comment by seabasss** [comment]
My code:

`	$.fn.loadFancyBox = function() {
		$("[data-fancybox]").fancybox({
			loop: false,
			opacity: 'auto',
			margin: [0, 0],
			gutter: 30,
			infobar: false,
			toolbar: false,
			slideShow: false,
			fullScreen: false,
			thumbs: false,
			closeBtn: false,
			autoFocus: false,
			smallBtn: false,
			clickOutside: false,
			clickSlide: false,
			touch: false,
			keyboard: false,
			beforeLoad: function(instance, slide) {
				$('#powerTip').hide();
			},
			beforeClose: function(instance, slide) {
				$(this).disposeVideo();
			}
		});`

**Comment by fancyapps** [comment]
Hmm.... but what about the demos from my previous post, are they working fine for you?

**Comment by seabasss** [comment]
Yes, yes, sorry that fixed the confirm box issue. But all my other fancyboxes got less pretty fade outs. New topic, sorry.

**Comment by fancyapps** [comment]
Are you changing opacity using custom CSS for other boxes? If so, can you remove that?

**Comment by seabasss** [comment]
Turned out I was running this. Where do I set that now? I want a darker background in .24

```
.fancybox-bg {
    background: #111111;
    opacity: 0.95 !important;
}
```

**Comment by fancyapps** [comment]
You can simply change opacity for the background like this:

```CSS
.fancybox-is-open .fancybox-bg {
    opacity: 0.87;
}
```

**Comment by seabasss** [comment]
Once again extremely helpful. Thanks!!
