### ISSUE TITLE
Clicks are blocked in v3.1.24?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1629]
Hi again,

I noticed a new thing in v3.1.24. I'm using [jQuery UI Datepicker](https://jqueryui.com/datepicker/), [Select2](https://select2.org/) and some other plug-ins and usually the datepickers and selectboxes closes when you click outside of them. In v3.1.24 all of them stays open. Is there anything in facybox that is blocking mouse clicks on certain elements or something? Similar to what happened [here](https://github.com/fancyapps/fancybox/issues/1450).

Thanks!

**Comment by seabasss** [comment]
If I remove this line it start working again `mousedown.fb.touch`

What is that part doing? Am I good without it or will something else stop working?

Thank you!

**Comment by fancyapps** [comment]
Hi,

Please, check the last update - v3.1.25

**Comment by seabasss** [comment]
Thank you! That fixed it, but the new css messed up my whole design. I changed `.fancybox-slide>div` back to `.fancybox-slide>*` and that seems to work better. I'll click around and see if anything else changed.

Thanks!

**Comment by fancyapps** [comment]
This change was made to fix issues when ajax response returns some additional elements like `<script>` or `<style>`. Previously, this CSS selector made all elements visible.
