### ISSUE TITLE
After open scroll to link

### ISSUE THREAD

**Issue by motyl1337** [fancyapps/fancybox#1630]
Hey,
I have got following problem, after install fancybox3 and customize I was try to do mine fancybox html modal.
After open fancybox scroll me to the link in modal. I do not know, is it a problem or bug ?
Maybe you have got it some issue for it.
Example:
https://codepen.io/anon/pen/QqbOGM (Chrome)
If you remove the link, fancybox is great.
If someone have any solution i will be greatfull.

**Comment by fancyapps** [comment]
Hi,

You can clearly see that your link gets focused, therefore browser scrolls the parent element to make it visible.

You can disable auto-focus by setting `autoFocus:false`
