### ISSUE TITLE
Zooming not working correctly

### ISSUE THREAD

**Issue by serkyen** [fancyapps/fancybox#1631]
When I click on an image in a gallery, it opens it up way too large. Then if I click on it to zoom out, it goes way too small. However, if I simply resize the browser or go to the next image, the image is the correct size. So there seems to be an issue with zooming. Please see what I mean [here](https://www.yenersway.com/tutorials/cake-toppers/sugar-horse-and-carriage-centerpiece/).

Scroll down to the Member's Projects section and click on one of the small thumbnails.

I am using the following implementation...

```
<script type="text/javascript">
	jQuery("[data-fancybox]").fancybox({
		// Options will go here
	});
</script>
```

**Comment by fancyapps** [comment]
Hi,

Please, update jQuery to the latest.

**Comment by serkyen** [comment]
Done...working now :)
Thanks!
