### ISSUE TITLE
Grouping will not work without using data-fancybox (almost fixed)

### ISSUE THREAD

**Issue by Graphicfort** [fancyapps/fancybox#1632]
Grouping will not work in this case
<pre>
&lta href="Link to the image" data-lightbox="group">image 1&lt/a>
&lta href="Link to the image" data-lightbox="group">image 2&lt/a>
</pre>

Grouping will work in this case (using data-fancybox)
<pre>
&lta href="Link to the image" data-fancybox="group">image 1&lt/a>
&lta href="Link to the image" data-fancybox="group">image 2&lt/a>
</pre>

To fix it:

1- By adding a new default (**groupAttr**):
EX:
<pre>
$('[data-lightbox]').fancybox({
    groupAttr: 'data-lightbox'
});
</pre>

2- change:
<pre>value = $(target).attr( 'data-fancybox' ) || '',</pre>
to:
<pre>
groupAttrVar = e.data.options.groupAttr || 'data-fancybox',
value = $(target).attr( groupAttrVar ) || '',
</pre>

3- change:
<pre>
items = items.length ? items.filter( '[data-fancybox="' + value + '"]' ) : $( '[data-fancybox="' + value + '"]' );
</pre>
to:
<pre>
items = items.length ? items.filter( '[' + groupAttrVar + '="' + value + '"]' ) : $( '[' + groupAttrVar + '="' + value + '"]' );
</pre>

still didn't figure out how to fix these:
1- <pre>$D.on( 'click.fb-start', '[data-fancybox]', _run );</pre>
2- <pre>$el = $( "[data-fancybox='" + $.escapeSelector( url.gallery ) + "']" ).eq( url.index - 1 );</pre>

**Comment by fancyapps** [comment]
Hi,

Why do you need something to be "fixed"? If you wish, you can simply create click event on your elements and then start fancyBox using `$.fancybox.open()`.

**Comment by jtojnar** [comment]
That would mean replicating not insignificant part of Fancybox code. Since Fancybox can already create groups, it does not make sense to write the code again just to be able to use a different attribute name.
