### ISSUE TITLE
json + srcset

### ISSUE THREAD

**Issue by neredu** [fancyapps/fancybox#1634]
Hi Jānis,
first of all your app is awesome, the third version is just amazing !!! Thank you very much for this magic app!

Please could you answer on my question.
I am trying to open a json data from ajax request, everything works good, however when I tried to send the 'srcset' data I didn't notice any difference like in your codepan example here: https://codepen.io/fancyapps/pen/YQKKYx?editors=1000

Then I decided to send this info in decoded json format manually via console , before doing that I resized the screen size of my monitor to test if the smallest image will be loaded like it was on codepan. I sent this code and had no luck.

$.fancybox.open([
  { src: "https://placeholdit.imgix.net/~text?txtsize=33&txt=1_medium_1200%C3%97800&w=1200&h=720",
  type: "image",
  opts: [{srcset: "https://placeholdit.imgix.net/~text?txtsize=33&txt=1_large_1600%C3%97800&w=1600&h=960 1600w, https://placeholdit.imgix.net/~text?txtsize=33&txt=1_medium_1200%C3%97800&w=1200&h=720 1200w, https://placeholdit.imgix.net/~text?txtsize=33&txt=1_small_640%C3%97427&w=640&h=384 640w", width: "1200", height: "720"}]
  }
],{
loop: false,
});

a piece of my php code:

$data[] = ['src' => 'https://placeholdit.imgix.net/~text?txtsize=33&txt=1_medium_1200%C3%97800&w=1200&h=720','type' => 'image','opts' => ['srcset' => 'https://placeholdit.imgix.net/~text?txtsize=33&txt=1_large_1600%C3%97800&w=1600&h=960 1600w, https://placeholdit.imgix.net/~text?txtsize=33&txt=1_medium_1200%C3%97800&w=1200&h=720 1200w, https://placeholdit.imgix.net/~text?txtsize=33&txt=1_small_640%C3%97427&w=640&h=384 640w', 'width' => '1200', 'height' => '720']];

Am I doing something wrong or we cannot use 'srcset' option via ajax+json ? Also I am not sure can I send via json the 'width' and 'height' data like I did ? 

Thank you in advance for your answers.

**Comment by fancyapps** [comment]
Hi,

The thing about "srcset" is that it is quite hard to test it properly, especially when using Chrome on desktop. While the script generates correct html code according to the specs, browsers sometimes load other source that you might expect. For example, browsers sometimes ignore srcset rules and load image from cache. From my experience, FireFox and mobile browsers work more predictably.

**Comment by neredu** [comment]
Jānis, thank you for the answer !
I will continue testing, if have the right results I will inform the community here
