### ISSUE TITLE
How to close when click overlay on mobile

### ISSUE THREAD

**Issue by Mrli2016** [fancyapps/fancybox#1635]
I want to close the Popup when I click the content or outside, but it not work on the Android and iOS. (fancybox v3.1.20)

**Comment by fancyapps** [comment]
Hi,

You can use `mobile` option to change actions when user clicks on mobile device, this is the default value:

```JS
mobile : {
    clickSlide : function( current, event ) {
        return current.type === 'image' ? 'toggleControls' : "close";
    }
}
```

**Comment by Mrli2016** [comment]
Thanks, it is very nice!  I'm sorry not be carefully to read your document.
