### ISSUE TITLE
FancyBox next and prev Button not working properly

### ISSUE THREAD

**Issue by Sathiyamm** [fancyapps/fancybox#1636]
In fancy box.. I have 6 images, When i click the next botton in the 1st image it move to the 3rd image from that it moves to 5th image then 6th. when i click the previous button from 6th image it moves to 4th and then 2nd and then 1st.. how to fix it?

**Comment by fancyapps** [comment]
Hi,

What do you mean by " it move to the 3rd image from that it moves to 5th image", maybe this is the order you have in your html?

![2ab4-8926-47fd-8623-f9896262c2ee](https://user-images.githubusercontent.com/1055589/30596404-a66f584a-9d5c-11e7-88d1-e2985f44e262.jpg)

**Comment by Sathiyamm** [comment]
please refer the video : https://www.screencast.com/t/YlsPuX0U6

**Comment by fancyapps** [comment]
Images are arranged in the same order as they are found in the dom, e.g., what your selector, for example, `$('[data-fancybox]')` returns. Most likely your slider creates the html in that order.

**Comment by Sathiyamm** [comment]
can you please tell me how to override it?

I am used fancybox code:

 $(".fancy_box").fancybox({
            openEffect: 'none',
            closeEffect: 'none',
        });

**Comment by Sathiyamm** [comment]
these two functions are looping two times even when i click the button one times itself


next: function (duration) {
            return this.jumpTo( this.currPos + 1, duration );
        },
 previous : function( duration ) {
            return this.jumpTo( this.currPos - 1, duration );
        },

**Comment by fancyapps** [comment]
What slider are you using? I do not see any issue with Slick (https://codepen.io/fancyapps/pen/gWvorB) or Swiper (https://codepen.io/fancyapps/pen/eWVyVg).

**Comment by nebrot** [comment]
How to disable the duplicated items in swiper? When you add `infobar: true` and `thumbs: true` in your example you see 10 images instead of 4.

**Comment by fancyapps** [comment]
I realized just now that both of these sliders apply a handy classnames that you can use to exclude clones. So, for swiper, you have to use:

```JS
$().fancybox({
  selector : '.swiper-slide:not(.swiper-slide-duplicate)',
  hash     : false
});

```

**Comment by nebrot** [comment]
Thank you for this quick and helpful answer, now it works!
