### ISSUE TITLE
Updating npm to 3.1.25

### ISSUE THREAD

**Issue by ugrupp** [fancyapps/fancybox#1637]
Hey, installing fancybox from npm gives me version 3.1.20.
https://www.npmjs.com/package/@fancyapps/fancybox: "3.1.20 is the latest of 2 releases"

However, the current version seems to be 3.1.25.

How can I get 3.1.25, since it has some nice bugfixes which I need?

Great module though, I love it!

**Comment by fancyapps** [comment]
Hi,

I wanted to wait a bit for a feedback to see if everything is OK before tagging a new release, but here you go - https://github.com/fancyapps/fancybox/releases 

npm and cdn should update in couple of hours.
