### ISSUE TITLE
display issue on older/slow computers

### ISSUE THREAD

**Issue by PoHs0ul** [fancyapps/fancybox#1638]
Hi there

Recently I updated fancybox from version 2 to 3, but my customer called me, that the pictures on his website sometimes don't show up on his old computer with IE11. On my computer everything was fine, but the problem showed when I tested it on a windows 10 virtual machine with IE11. So it seems to happen only on a slow IE11. (Other Browsers seem to be fine.)
After some testing I found out that the image doesn't show because the transform, width and height properties on the div "fancybox-image-wrap" don't get set.
I'd be happy, if you could take a look at it, because not everyone has a fast computer/internet and I don't want to go back to fancybox 2.

**Comment by fancyapps** [comment]
Hi,

Sorry, but I am very skeptical that slowness of the computer could produce such issue. Works fine on very slow Android tabled (the slowest machine I could find) and there is no issue (other than a big lag) when simulating 20x slowdown using Chrome. Also, it is not clear from your description if you can reproduce this issue or it occurs only sometimes.

Anyway, make sure you are using the latest jQuery and fancyBox versions.

**Comment by PoHs0ul** [comment]
Sorry if it wasn't clear. I could reproduce it on browserstack, windows 10 and IE11. And I am using the latest versions of JQuery and fancyBox else I would first have updated those ^^

**Comment by fancyapps** [comment]
Do you experience the same issue when viewing demos on the homepage -
 http://fancyapps.com/fancybox/3/ ?
Have you changed Document mode from 7 (default) to higher? 

I am using Windows 10 and I see no issue whatsoever.

**Comment by PoHs0ul** [comment]
I could reproduce it on the first demo on your site. https://puu.sh/xFcrU/1193ad171d.png

**Comment by fancyapps** [comment]
Hmm, but what about the default demo of the image gallery (from "Showcase" section)?

**Comment by PoHs0ul** [comment]
Couldn't reproduce it there. I would guess it is, because it already knows the proportions of the images or because it doesn't have enough images to reproduce it.
For me it seems like it stumbles, because it doesn't have the proportions of the unloaded image, when it wants to set the size.

**Comment by fancyapps** [comment]
@PoHs0ul Sorry, I just now discovered that there is indeed an issue with IE11. It should be fixed in the last commit.
