### ISSUE TITLE
"Back" button is unable to press for closing AJAX modal

### ISSUE THREAD

**Issue by iBars** [fancyapps/fancybox#1640]
I use AJAX modals when click on any house picure. But I can't close that modal by clicking browser "Back" button. My customer want to enable this feature for site visitors

**Comment by fancyapps** [comment]
Hi,

But ... this is how it works. Steps to reproduce:

1) Open http://fancyapps.com/fancybox/3/
2) Find and click "Ajax request" for ajax demo
3) Click "Back" button, it should close

So, is this not working for you?

**Comment by iBars** [comment]
Yes. Site is doma-nk.ru (click on any house image)

![image](https://user-images.githubusercontent.com/3519015/30688971-4099187c-9ec8-11e7-8c22-47895240a3d9.png)

**Comment by fancyapps** [comment]
I hope you are aware that it is not possible to bind on "Back button" click event. The workaround is to use hashes and manipulate with browser history entries. Since you have not set hash values (by adding, for example, `data-fancybox="ajax"`), hash module does not do anything.
