### ISSUE TITLE
Fancybox3 Ajax Content with script/style tag

### ISSUE THREAD

**Issue by aldoexpert** [fancyapps/fancybox#1641]
If you use the fancybox3 for load content ajax and in that content have script or style tag will show the script
that because the fancybox3 style have the background white for all tag in div, so you can give
<style>
.fancybox-slide script,
.fancybox-slide style { display: none; }
</style>
in your template or append to fancybox3 style for hidden script/style tag
Thanks

**Comment by fancyapps** [comment]
Hi,

Are you sure you are using the latest version?
