### ISSUE TITLE
fancybox 3 not working with IE and it's working with other browser

### ISSUE THREAD

**Issue by anujiuee** [fancyapps/fancybox#1642]
i used fancybox 3 for my project and i have IE 11 ,code is like that--

<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js"></script>

//this method called when i hit some buttons

	function bamsOpener() {

        var captionButtons = <% if( (processor==0 ||processor==3) && amexFolder.size()!=0){ %> '<button style="padding:10px; margin:5px;" onclick="amexOpener()">AMEX</button>'<% } %>  <% if(discoverFolder.size()!=0 && processor==0 && amexFolder.size()!=0){ %>+ <% } %>
            <% if( (processor==0 ||processor==2) && discoverFolder.size()!=0){%> '<button style="padding:10px; margin:5px;" onclick="discoverOpener()">Discover</button>'<% } %>   <% if(bamsFolder.size()!=0 && processor==0 && discoverFolder.size()!=0){ %>+ <% } %>
            <% if((processor==0 || processor==1) && bamsFolder.size()!=0){ %>'<button style="padding:10px; margin:5px;" onclick="bamsOpener()">BAMS</button>'<% } %>

$.fancybox.close();

 var srcArray = ['data/bams/1.pdf', 'data/bams/2.pdf']
        

var array = [];
for (var index = 0; index < srcArray.length; index++) {
array.push({src  : srcArray[index], type : 'iframe', opts : { caption : captionButtons},openEffect:'none',closeEffect:'none',iframe:{preload: false}});
}
$.fancybox.open(array, {
loop : true
});

}

**Comment by fancyapps** [comment]
None of this makes sense. I do not see any issue using IE11/IE10.

**Comment by anujiuee** [comment]
this above code really not working in IE 11 , except IE it's working in every other browser.

**Comment by fancyapps** [comment]
https://github.com/fancyapps/fancybox#bugs-and-feature-requests
