### ISSUE TITLE
fancybox3 doubles other HTML elements in the source code

### ISSUE THREAD

**Issue by d003232** [fancyapps/fancybox#1643]
There is a strange thing on my website http://ferienhaus-schwarzwald-todtnauberg.de/ using fancybox3 version 3.1.25

After I click on a picture it will be shown in the fancybox3. Very well, Everything ist perfect. 

BUUT. If I do that several times and after that take a look into the chrome debugger my elements for the oncanvas menu have been doubled (directly after the BODY tag)!

Here two pictures. One before clicking on a picture shown with fancybox3. One after cklicking 4 times on a picture using fancybox3:
https://www.dropbox.com/sh/gk7cf4506a9ops3/AAAa-GEwaW__ev7Z6en66ILOa?dl=0

**Comment by d003232** [comment]
One more strange thing. Clicking on a picture of the fancybox3 slider i can see that between the fancybox IMG tag all the source code of the WRAPPER tag from the parent page is loaded??? 

See also the picture here:
https://www.dropbox.com/sh/gk7cf4506a9ops3/AAAa-GEwaW__ev7Z6en66ILOa?dl=0

Anyone out there who knows whats the reason for that?

**Comment by fancyapps** [comment]
Hi,

Could you provide a link to working demo?

**Comment by d003232** [comment]
It's http://ferienhaus-schwarzwald-todtnauberg.de/

just click a picture from the slider or a single picture there. The main page.

**Comment by fancyapps** [comment]
Your page returns this message:

`<p>Your request has been mapped to a website which does not yet contain any published pages.</p>
 `

**Comment by d003232** [comment]
Seems that you are landing on the english branch of the page. I fixed that. Should work now.

**Comment by fancyapps** [comment]
1) I see images, but they are not clickable; turns out, it is just one large image.
2) I see "Still on work. Please go to the german version." message, but the link goes to the same page.
3) You are using very outdated version of jQuery (jQuery v1.11.3)

**Comment by d003232** [comment]
Ups. Sorry for that. The promlen is on the german main page. I was not aware that my cms will direct you to the english branch automaticly. 

The german page url is http://ferienhaus-schwarzwald-todtnauberg.de/index.html

**Comment by d003232** [comment]
I will fix the outdated jQuery thing this evening and try to reproduce the error after that.

**Comment by fancyapps** [comment]
Turns out that this issue is caused by MooTools, I can reproduce this by simply adding mootools.js source code to the page - https://codepen.io/fancyapps/pen/WjVXyx?editors=1010

I would suggest you to get rid of it and to use only jQuery. It is actually a bad practice to mix multiple JS libraries.
