### ISSUE TITLE
data-caption is not updating

### ISSUE THREAD

**Issue by AugustBurnsRed** [fancyapps/fancybox#1644]
Hi, im trying to use fancybox 3.1.25 with a gallery that i have made in vuejs. All the data is loaded at the start and the pagination is made inside vue. On the first page the data-caption for each images are fine. However on other pages the captions are still the one from the first page. If i don't click on a image on the first page but on the second, then the caption from page 3-4 etc.. are the one from page 2.

My fancybox code is very basic without any option
`<a :href="image.link" data-fancybox="gallery" :data-caption="image.text">`

If i have something rendered like that...

page1:
`<a href="img1.jpg" data-fancybox="gallery" data-caption="<h1>Img1</h1>" >`

page2:
`<a href="img2.jpg" data-fancybox="gallery" data-caption="<h1>Img2</h1>" >`

If i click on img1 then img2, the img2 is gonna appear with the title of img1

So how can i make this work? thanks!

**Comment by fancyapps** [comment]
Hi,

Any demo (preferably on Codepen or jsfiddle) would be useful.

**Comment by AugustBurnsRed** [comment]
Sorry, i just made one you can look at it: https://jsfiddle.net/6bcj549u/8/

Click on: image 1, page 2, image 2 and then you will see that the caption is the one from image 1. If you click on page 2 and image 2 without clicking on the first image, the second caption is going to be fine.

**Comment by fancyapps** [comment]
This issue seems to be caused by the fact that both Vue.js and jQuery caches some values. Try for yourself, click on links and see what `$('[data-fancybox]').data('caption')` returns. 

The solution would be to use native methods for accessing `data` values:

```JS
$('[data-fancybox="gallery"]').fancybox({
  caption : function(instance, item) {
    return this.dataset.caption || '';
  }
});
```

Demo - https://jsfiddle.net/ntdnomrt/

**Comment by AugustBurnsRed** [comment]
Hi, it's working in the demo however in my real code the images are loaded in ajax and it's not working. The `$('[data-fancybox="gallery"]').fancybox`... does not seems to detect the images.

So is there a way to wake this work with dynamic elements?

thanks!

**Comment by fancyapps** [comment]
Another way to initialize is like this (snippet from documentation):

```JS
$().fancybox({
  selector : '[data-fancybox="images"]',
  loop     : true
});
```

**Comment by AugustBurnsRed** [comment]
Thanks it's working great now. If anyone has the same problem you can do it like this: 

`$().fancybox({
    selector : '[data-fancybox="gallery"]',
    loop     : true,
    caption : function(instance, item) {
      return this.dataset.caption || '';
    }
  });`
