### ISSUE TITLE
Bug when css {} left blank

### ISSUE THREAD

**Issue by Codepwned2** [fancyapps/fancybox#1645]
One of my applications had 4 different 'modes' setup for different needs. I accidentally left css {} in the configuration options for one and it had an seemingly random behavior. 

Sometimes the modal window would open like expected where it auto scales. 

// YAY!
&div class="fancybox-content" style="width: 1146px; height: 390px;"&

Other times it does this
// WTF?
&div class="fancybox-content" style="width: 0; height: 390px;"&

It is important to note that the behavior was consistent for the same content. I'm not sure what in the content was impacting it as there were no unusual differences in content that typically impact javascript. No rogue single/double quotes. Both had the same number of commas. It was pretty perplexing.

This occurred in IE 11, Edge, Chrome, Firefox and Safari.

**Comment by fancyapps** [comment]
Hi,

Sorry, I could not reproduce this. Any demo would help (you can use Codepen or jsfiddle).

**Comment by Codepwned2** [comment]
Unfortunately it's part of an internal system so I can't. As I said, this was inconsistent so on a page with a list of 200+ items, about 40% of them exhibited the behavior with the following configuration

function openiFrame(url){
	$.fancybox.open({
		transitionEffect: 'fade',
		type: 'iframe',
		smallBtn: true,
		iframe : {
			// Iframe template
			tpl : '<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen allowtransparency="true" src="'+url+'"></iframe>',
	
			// Preload iframe before displaying it
			// This allows to calculate iframe content width and height
			// (note: Due to "Same Origin Policy", you can't get cross domain data).
			preload : true,
	
			// Custom CSS styling for iframe wrapping element
			// You can use this to set custom iframe dimensions
			css : {},
	
			// Iframe tag attributes
			attr : {
				scrolling : 'auto'
			}
	
		}
	})
}

Removing the css : {} stopped the behavior in all instances. I've added the source code of the opened iFrames that were reproduceable 100% of the time. 

[iframecode - consistently would open 0 width.txt](https://github.com/fancyapps/fancybox/files/1333368/iframecode.-.consistently.would.open.0.width.txt)
[iframecode - no issues.txt](https://github.com/fancyapps/fancybox/files/1333369/iframecode.-.no.issues.txt)

**Comment by fancyapps** [comment]
It is not clear from your comments if -
1) issue occurs "when css {} left blank"
2) issue occurs when "Removing the css : {} "
3) issue occurs on specific file 

As none this is reproducible, I do not see what could be done.

**Comment by Codepwned2** [comment]
I have a 100% reproduce able bug involving Chrome and IE. This issue does NOT occur in the latest version of Firefox. 

Using the following javascript configuration, open an iframe window repeatedly. In Chrome 30% of the time a blank X opens. 
`function openiFrame(url){
			$.fancybox.open({
				transitionEffect: 'fade',
				type: 'iframe',
				smallBtn: true,
				iframe : {
					// Iframe template
					tpl : '<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen allowtransparency="true" src="'+url+'"></iframe>',
			
					// Preload iframe before displaying it
					// This allows to calculate iframe content width and height
					// (note: Due to "Same Origin Policy", you can't get cross domain data).
					preload : true,
			
					// Iframe tag attributes
					attr : {
						scrolling : 'auto'
					}
			
				},
				btnTpl : {
					// This small close button will be appended to your html/inline/ajax content by default,
					// if "smallBtn" option is not set to false
					smallBtn   : '<button data-fancybox-close class="fancybox-close-small" title="{{CLOSE}}"></button>'
				}
			})
		}`

By simple adding the CSS configuration the issue goes completely away
`function openiFrame(url){
			$.fancybox.open({
				transitionEffect: 'fade',
				type: 'iframe',
				smallBtn: true,
				iframe : {
					css : {width:'80%',margin:'0'},
					// Iframe template
					tpl : '<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen allowtransparency="true" src="'+url+'"></iframe>',
			
					// Preload iframe before displaying it
					// This allows to calculate iframe content width and height
					// (note: Due to "Same Origin Policy", you can't get cross domain data).
					preload : true,
			
					// Iframe tag attributes
					attr : {
						scrolling : 'auto'
					}
			
				},
				btnTpl : {
					// This small close button will be appended to your html/inline/ajax content by default,
					// if "smallBtn" option is not set to false
					smallBtn   : '<button data-fancybox-close class="fancybox-close-small" title="{{CLOSE}}"></button>'
				}
			})
		}`

This leads me to believe there is an bug with how Javascript is generating the height and width. There could be many causes including not waiting until the iframe has loaded to set height and width automatically. 

I've created a screencast here so you can see. 
https://screencast-o-matic.com/watch/cbQu2PIvS0

**Comment by fancyapps** [comment]
Could you try the latest version from GitHub (v3.1.26)?

**Comment by Codepwned2** [comment]
I'll check out asap but it may be Monday before I reply. Thanks so much for all your hard work!

**Comment by Codepwned2** [comment]
Success!

Latest versions of Firefox, Chrome, Safari and Edge no longer have this behavior that was easily replicated before. If I may ask, how did you resolve it?

**Comment by fancyapps** [comment]
I just added some additional checks.

**Comment by micronetyazilim** [comment]
dfsdfsddsfss
