### ISSUE TITLE
ios 11 input field issue

### ISSUE THREAD

**Issue by kopito901** [fancyapps/fancybox#1646]
Hi,

This problem only on ios11. When u open modal window with form not at top of site and try to click on any input your cursor will be not in input

**Comment by fancyapps** [comment]
Seems that folks at Apple really do not know how to fix input fields correctly. Each iOS version brings new surprises. This time, it will not be possible to avoid ugly hack by setting `position: fixed` to `body` element.

**Comment by Aquanin** [comment]
I have a similar problem, I have an iframe in a fancybox window that has a form.  I can click on the input field and as soon as the keyboard pops up i cannot click the submit button.  I tried setting position: fixed on the body of the parent page and it fixes it but then I can't scroll that page.  Any solution to that?

**Comment by kopito901** [comment]
Now im trying to add css styles when fancybox show and delete this styles after close, but this doing with small delay and this looks very bad. Thinking about any other solution.

**Comment by kamah82** [comment]
I'm having the same issue. Is there some available wordaround here?

**Comment by fancyapps** [comment]
The workaround will be included in the next commit.

**Comment by nouphaltklm** [comment]
Please provide us with the workaround or atleast a hint. :(

**Comment by fancyapps** [comment]
Hello, everyone!

I want to apologize for the delay. I got sick recently and I could not finish everything as I had planned. And, what's more, next week I will be on my vocation. 

In the meantime, you can try the first beta of v3.2.0 - 
https://fancyapps.com/fancybox/3/fancybox/3.2/

The major change in v3.2 will be new directory structure and custom font for icons.  No JS API changes.

I will take a fresh look after returning and will publish afterwards. 

Thanks!

**Comment by Aquanin** [comment]
Thank for the beta, the issue, however, is the same for me.  I click in an input field and can type, but then cannot click submit.  The cursor seems to be way down the page.

**Comment by chrissun** [comment]
Following

**Comment by Aquanin** [comment]
I take that back, I may have had a caching issue.  It is working on iOS 11.1 beta 5 now for me.

**Comment by fancyapps** [comment]
Hello, again!

So, I returned from vocation, took a fresh look and did not like it, did not like it at all. I changed my mind about using custom font for icons and inline svg icons will be used instead. 

So, please, take a look here - https://codepen.io/fancyapps/full/WZmGmw/

**Comment by fancyapps** [comment]
v3.2.0 is now out and contains iOS hack.
