### ISSUE TITLE
Add documentation for disabling slide drag

### ISSUE THREAD

**Issue by odahcam** [fancyapps/fancybox#1647]
Its very hard to figure out that you need to set `touch: false` to disable the slide dragging. I'm developing for desktops and doing this was the last thing that I thought be the  solution. 🤔 

Just a comment before the touch key on Options section in docs would be nice.

In my scenario, I'm loading HTLM content trought fancyBox's AJAX method to display a form, and I wanted this form to be selectable, and I needed to disable drag for this and, the touch option key was not that intuitive for me. 😅

**Comment by fancyapps** [comment]
Hi,

The "Inline HTML" demo already shows how to disable touch, see #3 https://codepen.io/fancyapps/pen/NjXbXw
I kinda hoped that this would be sufficient, but probably it is not :) So, alright, I`ll add a comment about that.

**Comment by odahcam** [comment]
I took it from the [Datepicker](https://codepen.io/fancyapps/pen/QqLXaz) demo. 😅 

Thanks.

**Comment by fancyapps** [comment]
btw, I have added new FAQ entry about this - http://fancyapps.com/fancybox/3/docs/#faq-5
