### ISSUE TITLE
Customize inner slide template

### ISSUE THREAD

**Issue by odahcam** [fancyapps/fancybox#1649]
It would be usefull for creating custom slide themes.

I don't think fancyBox style is bad, but in a company I work, they have a pattern and I need to follow this pattern strictly and, by having the possibility to customize the inner stage content, I could make a better use of features like caption.

Also it would be usefull for implementing a Bootstrap theme, where the modal has 3 sections of content, the header, the body and the footer.

Please, let me know if removing the slide padding and creating the inner content by hand is a better approach, 'cause acctually I only miss the caption feature.

**Comment by fancyapps** [comment]
Sorry, I have no idea what do you mean by "inner slide template". If you mean some structure around inline content, then you can create that using callbacks.

**Comment by odahcam** [comment]
Sorry, I mean that block:
![image](https://user-images.githubusercontent.com/3942006/30964534-1e85bb86-a428-11e7-9ef4-e5d19bd2f9b6.png)

**Comment by fancyapps** [comment]
The idea of v3 is have everything clean and simple. Therefore the script is not creating any additional layer around your content so you can easily control everything using CSS - dimensions, margin, padding, centering, etc. Any wrapping element would make it impossible or would create unnecessary complexity (like in previous versions).

**Comment by odahcam** [comment]
Awesome.
