### ISSUE TITLE
Random slides missing in IE11

### ISSUE THREAD

**Issue by soulbloom** [fancyapps/fancybox#1653]
While all slides in a collection are displayed as expected on initial opening of an IE11 browser session, when the browser window is closed and reopened, random slides in the series are not displayed. The missing slides will occur whether navigating the images via prev/next controls or via the image thumbnails. This only happens in subsequent browser sessions, to the initial session, only in IE11.

This behavior is consistently reproduceable in native IE11 browsing sessions on both Windows 7 and Windows 10 desktops.

The issue can be observed on the FancyApps Customized layout demo, here: http://fancyapps.com/fancybox/3/#cl-group-5

**Comment by fancyapps** [comment]
Hi,

Thanks for reporting! I`ll look into this.
