### ISSUE TITLE
How do you make images NOT fit the screen? (Especially in a mobile browser)

### ISSUE THREAD

**Issue by amodoke** [fancyapps/fancybox#1654]
In fancybox version 2, we had an option for images to NOT fit to the screen (fittoview:false?). This allowed users to pinch and zoom images on their mobile).

In version 3 documentation, I don't see any reference to this.

Is it possible? How?

I am opening images in fancybox using the standard code on the docs page:

`<a href="image.jpg" data-fancybox="images" data-caption="My caption">
`

I DO NOT want the images to fit the screen. Becomes impossible to view details when on mobile.

Thanks in advance. :)

**Comment by fancyapps** [comment]
I`m sorry, but have even tried using v3 on mobile device?

**Comment by amodoke** [comment]
YES.

I AM using version 3. I even said in my question:

_**In version 3 documentation, I don't see any reference to this.**_

So again, can autofit be set to false **in version 3** for images? And how?

**Comment by fancyapps** [comment]
But you also said "This allowed users to pinch and zoom images on their mobile" ... and this makes no sense. Are we on the same page? You are using v3 from http://fancyapps.com/fancybox/3/ and you are not able to zoom/pinch images on the mobile device?

**Comment by amodoke** [comment]
We are on the same page. I mentioned the "pinch and zoom" **_was_** available in VERSION 2.

Let me make it very clear now: Forget version 2... Right now...

**I AM USING VERSION 3.**

And no, by default I am not able to pinch and zoom in on an image IN VERSION 3. Image in the fancybox is fixed to the width of the mobile's browser.

So how do I allow users to pinch and zoom an image when on mobile, in VERSION 3?

I am using this code to open an image (as per your docs for VERSION 3):
`<a href="image.jpg" data-fancybox="images" data-caption="My caption">
`

**Comment by fancyapps** [comment]
So, you say "how do I allow users to pinch and zoom an image when on mobile, in VERSION 3"?

Have you even opened the homepage? Did you really not see this video - http://fancybox.web/1.mp4 - screencast of iPhone? Or you do not know how to use the gestures like double tap on the phone?

**Comment by amodoke** [comment]
Yes, I've seen that video... and yes I know how double tap works.

It was NOT working earlier **by default**. But I saw your code on https://codepen.io/anon/pen/boGPZx and have implemented a version of it on my site, seems to be working for now.

Will let you know if it breaks or something...
