### ISSUE TITLE
fanycbox-3 helpers overlay locked

### ISSUE THREAD

**Issue by CharbelJ** [fancyapps/fancybox#1655]
I'm using fancybox-3.1.25 but there is still a missing option used in fancybox-2.1.5 which prevents the website from shifting to the right/left whenever the fancybox is opened in a page that has a scrollbar-y

I hope to have this option available soon.
Thank you

helpers : {
        overlay : {
            locked: false
        }
    }

**Comment by fancyapps** [comment]
Hi,

But why are you asking for option that "prevents the website from shifting" - there should be no sifting, because the script removes scrollbar, but compensates that by adjusting margin for body element.

If you experience some elements jumping, then see http://fancyapps.com/fancybox/3/docs/#faq-1

**Comment by CharbelJ** [comment]
Yes exactly its removing the scrollbar and then when afterClose(), it just shifts everything to the right, that only happens if the current page has a lot of data, which result in a scrollbar-y.

previously I used to use  
helpers : {
    overlay : {
       locked: false
     }
}

**Comment by fancyapps** [comment]
But do you really see any shifting when viewing demos on the homepage http://fancyapps.com/fancybox/3/ ?

**Comment by CharbelJ** [comment]
Oh wow! It looks more than perfect!
Would you be able to demonstrate how I would be able to do that on a body tag

**Comment by fancyapps** [comment]
What do you mean by "to do that on a body tag" ? The script creates something like this:

```CSS
.compensate-for-scrollbar, .fancybox-enabled body {
    margin-right: 16.799999999999955px;
}
```

this value is the width of the scrollbar (it varies across browsers).

**Comment by CharbelJ** [comment]
I have added it, but still the scrollbar is being removed/ the whole page shifts to the right :/

**Comment by fancyapps** [comment]
But what and why do you do? Show your page/demo!

**Comment by CharbelJ** [comment]
I just figured another trick around!
Thank  you for the support!

**Comment by egorlero** [comment]
CharbelJ, can u help me to resolve problem like yours?

**Comment by CharbelJ** [comment]
Yes sure!
Place the following code at the top of your css file.

html,body{
  overflow-y: auto !important;
}
