### ISSUE TITLE
Fail to close Articmodal when we add fancybox on site

### ISSUE THREAD

**Issue by Gesparo** [fancyapps/fancybox#1656]
Hello.

When i add Articmodal and fancybox on page, i get a problem with closing articmodal window. 
It happens when i press close button and fancybox receives the called event "beforeClose"

![2017-09-30_11-29-52](https://user-images.githubusercontent.com/9802906/31043291-c370a9e8-a5d2-11e7-9eac-c05cdfe3e4d6.png)

And fancybox doesn't receive variables instance and current.

![2017-09-30_11-11-55](https://user-images.githubusercontent.com/9802906/31043293-c6c279fa-a5d2-11e7-83f8-ee30d71b95e1.png)

So, if we will check this variables on "undefined", it will help to solve the problem

```javascript
'beforeClose.fb' : function( e, instance, current ) {
          var gallery, origHash;

          if (timerID) {
            clearTimeout(timerID);
          }

          // here that fix
          if (!current || !instance) {
            return;
          }

          if (current.opts.hash === false) {
            return;
          }

          // ...
        }
```

I think, fancybox mustn't use 'beforeClose' on another plugins, but it is the fastest solution.

**Comment by fancyapps** [comment]
Hi,

1) Why would you use additional modal script on the same page? fancyBox supports multiple instances (you can open more than one modal window at the same time), therefore there is no need for another one.

2) Articmodal is not following general good practices of coding. To avoid naming conflicts, it is safer to namespace events (see https://api.jquery.com/event.namespace/ ).
