### ISSUE TITLE
SmallBtn not being added with data-type image

### ISSUE THREAD

**Issue by yepecece** [fancyapps/fancybox#1657]
When using an image as data-type and setting up the smallBtn and disabling the toolbar, no close button is added.

You can see an example here: https://codepen.io/ybdigital/pen/zEEvba

Thanks

**Comment by fancyapps** [comment]
Hi,

This is how fancyBox works for now. You see, image scaling is done using CSS transform property and therefore any html element around it would scale, too. That would look really weird. But, on the other hand, this method has the best performance.

**Comment by yepecece** [comment]
Thanks for your feedback. I was able to insert it with an AfterLoad function and show it only when fancy box finishes the CSS transform transition. thanks
