### ISSUE TITLE
Unable to trigger a click on an existing fancybox in DOM

### ISSUE THREAD

**Issue by jonbeddoes-avast** [fancyapps/fancybox#1659]
This is a great plugin, but I couldn't see from the documentation how to call the open() function on an already existing element in the DOM. I tried using jQuery's 'click' and 'trigger' functions but this doesn't seem to work. The documentation shows how to use open(), but with inline options. It is strange this isn't covered anywhere?

**Comment by fancyapps** [comment]
Hi,

`open()` method is for starting fancyBox immediately. For example:

`$.fancybox.open( $('#inline') );`

or

```
$.fancybox.open({
   src : '#inline'
});
```

But, if you have attached fancyBox to some links, then you can trigger click event to start fancyBox:

`$('[data-fancybox="test"]').eq(0).trigger('click');`

**Comment by jonbeddoes-avast** [comment]
@fancyapps thanks for your quick response! Granted I didn't investigate too thoroughly, but the trigger 'click' was not working for me. Could it be something to do with the fact the href of the element is just 'javascript:;' ?

**Comment by fancyapps** [comment]
You see, if you add `data-fancybox` attribute or call `$('.your_selector').fancybox()` then you are attaching a click handler to these elements. And that click handler gets clicked element, find group elements, etc, and then calls `open()` method.  So, by triggering click event you just executing that click handler (if it exists, obviously).

**Comment by jonbeddoes-avast** [comment]
@fancyapps ok thanks for the info. I'll try and put together a simple demo to see if I can recreate the issue. It might be something simple, but it looked like $('fb-elem').trigger('click'); was not able to fire  a FancyBox with an iframe, and no error was shown.

**Comment by fancyapps** [comment]
Just double check if you have initialized fancyBox on that element. E.g., it hould either have `data-fancybox` attribute or you have used correct selector for ` $('fb-elem').fancybox()`
