### ISSUE TITLE
Using a div instead of anchor

### ISSUE THREAD

**Issue by sasoriza** [fancyapps/fancybox#1662]
With fancybox 2 I was able to define a data-fancybox-href for any element which allowed me to use it on non-anchors. With fancybox 3 this will result in the clicked image being removed after fancybox has opened it. How can I use fancybox on non-anchor elements?

**Comment by fancyapps** [comment]
Hi,

How to trigger from any element? Easily:

```HTML
<div data-fancybox data-src="https://farm4.staticflickr.com/3953/15594397982_477385f90d_b_d.jpg">
    Click me
</div>
```

Demo - https://codepen.io/anon/pen/mBqwWz?editors=1000

But what about this part:

> With fancybox 3 this will result in the clicked image being removed after fancybox has opened it

No idea what do you mean by that.

**Comment by sasoriza** [comment]
Working like a charm, thanks!
I am using a small image to open a bigger version of that image and with my old version, the clicked image would always disappear.

**Comment by fancyapps** [comment]
If you had given the demo or at least some snippet, then I would have given an answer, but I will just repeat - I have no idea what do you mean by that.

**Comment by sasoriza** [comment]
This is basically code for v2 where only the library has been exchanged with v3:
http://jsfiddle.net/g9pWa/6/

**Comment by fancyapps** [comment]
Have you tried like this?

```HTML
<div data-fancybox data-src="https://farm4.staticflickr.com/3953/15594397982_477385f90d_b_d.jpg">
    <img src="https://farm4.staticflickr.com/3953/15594397982_477385f90d_m_d.jpg" />
</div>
```


https://codepen.io/anon/pen/eGyzMd?editors=1100

**Comment by sasoriza** [comment]
That's pretty much what I ended up using. Thanks again! :)
