### ISSUE TITLE
Сlick (tap) outside photos

### ISSUE THREAD

**Issue by Artemeey** [fancyapps/fancybox#1663]
When clicking outside of the photo, the gallery closes.
When I tap outside the photo - the gallery doesn't close, there's a bug.

http://prntscr.com/gt343s

**Comment by fancyapps** [comment]
Hi,

There is an option `clickSlide` that indicates action to be taken when user clicks in that area. And for mobile devices, this can be customized using `mobile` option. So, use it like this:

```JS
mobile : {
    clickSlide : 'close'
}
```
