### ISSUE TITLE
Masterslider and fancybox 3 ? 

### ISSUE THREAD

**Issue by SotechPl** [fancyapps/fancybox#1665]
Hello. Can You Help me conect Fancybox and Masterslider script?

I have problem with find right index. 
When i change main/current foto in MasterSlider gallery, fancybox (i think so) change sorting and index does not match.

**Comment by fancyapps** [comment]
Hi,

If you would provide a demo on Codepen, that would be extremely helpful.

Maybe try finding correct selector, see examples for Slick https://codepen.io/fancyapps/pen/gWvorB and Swiper https://codepen.io/fancyapps/pen/eWVyVg

**Comment by grupoactialia** [comment]
**HTML:**

`<div class="master-slider ms-skin-default" id="masterslider">
    <div class="ms-slide">
       <img src="/assets/plugins/masterslider/style/blank.gif" data-src="/image.jpg" />
       <a href="/image.jpg" class="ms-lightbox"></a>
    </div>
    ...
</div>`

**JS:**

`var slider = new MasterSlider();
slider.setup('masterslider', {
  width: 1170,
  height: 650,
  loop: true
});

slider.control('lightbox');

$().fancybox({
  selector: '.ms-lightbox',
  hash: false,
  backFocus: false
});`

**Comment by Mufaddalik** [comment]
Just one correct as we are using fancy box replace 
`slider.control('lightbox') ` to `slider.control('fancybox') `
It will work flawlessly
