### ISSUE TITLE
Scale to Fit on Zoomed-in Mobile Layout

### ISSUE THREAD

**Issue by neymue** [fancyapps/fancybox#1666]
Hi,

I'm working on a mobile version of a web layout using fancybox. It's working fine sofar, but my issue is when you first zoom-in on the layout, then open fancybox, the image is scaled and missplaced (as if it's relative to the zoomed-in width of the layout not the device-width, although the toolbar/caption/container appears fine relative to the 100% device-width). If you pinch in/out then the image goes into the correct place of the container, so I'm wondering how to force this behaviour automatically on the opening of fancybox?

I've tried using instance.scaleToFit(); in the afterLoad function, but it caused several functionality bug, like swiping stopped working.

Any help would be appreciated.

**Comment by fancyapps** [comment]
Hi,

Unfortunately, that`s the nature of mobile browsers.
