### ISSUE TITLE
Fancybox 3 scroll content not working

### ISSUE THREAD

**Issue by bhumiradixweb** [fancyapps/fancybox#1667]
```
.fancybox-slide--image {
    overflow: visible;
}
```

Because of above code, if want to scroll content is not working. Is there any helper for scoll in fancybox 3?

**Comment by bhumiradixweb** [comment]
why it is closed without any reply?

**Comment by fancyapps** [comment]
Your question makes absolutely no sense.

**Comment by bhumiradixweb** [comment]
but why? Some time you want to display scroll if image is large and not fit into screen. I want to scroll my image. Why can't i display vertical scrollbar?

**Comment by fancyapps** [comment]
Then why did you not ask so? Something like - "How to make images scrollable" would make more sense. 

Anyway, fancyBox was not designed for this. The simplest solution would be to display image as `inline` or `html` content. For example:

```JS
$('.fancybox').on('click', function() {
  
  $.fancybox.open({
   type : 'html',
   src  : '<div><img src="' + this.href + '" /></div>' 
  });
  
  return false;
});
```

Demo - https://codepen.io/anon/pen/xXYyqB?editors=1010

**Comment by bhumiradixweb** [comment]
Oh...wrong question...misinterpretation...btw I want to use type: 'image' but with scroll,is it possible?

**Comment by fancyapps** [comment]
No, it is completely contrary to the main features - zooming, dragging and swiping. It is like you are asking to put a ketchup on the cake.

**Comment by bhumiradixweb** [comment]
This is just requirement. It may be contrary but what if I disable zooming, dragging and swiping. Also, In fancybox < 3 has an option to setup scroll, right?
