### ISSUE TITLE
OnLoad Site

### ISSUE THREAD

**Issue by zerocool1910** [fancyapps/fancybox#1668]
Hello,

I have a simple gallery like this.

```HTML
<a href="photo1.jpg" data-fancybox="images">
	<img src="photo1.jpg" alt="" />
</a>
<a href="photo2.jpg" data-fancybox="images">
	<img src="photo2.jpg" alt="" />
</a>
```

I just two question
1. I dont want to show my gallery (hidden gallery)
2. I want to start de gallery onload my web page. Just like JQuery Document Ready or ONLOAD the Body.

Thanks!

**Comment by fancyapps** [comment]
1) Then hide.

2) Something like this:

    `$('[data-fancybox="images"]').eq(0).trigger('click');`

    Demo - https://codepen.io/anon/pen/YrayEQ?editors=1010

**Comment by zerocool1910** [comment]
Thanks, works perfectly!.
