### ISSUE TITLE
How to detect when we reach the last slide?

### ISSUE THREAD

**Issue by coldpumpkin** [fancyapps/fancybox#1670]
Is it possible to detect when we reach the last slide of the group? In previous versions I'd do it like so:
```
        afterShow: function() {
            if(this.index  == this.group.length - 1){
                alert('I am the last item of the gallery');
            }
        },
```
But it's not working anymore. Or, and preferably, display a default image in the end of groups (like an image saying "Go back to load more content").

**Comment by fancyapps** [comment]
Hi,

Here is an example of how to add one extra slide - https://codepen.io/fancyapps/pen/ggwmbb

**Comment by coldpumpkin** [comment]
Thank you, works great! Also, is there a way to do some jQuery whenever the user reaches the last image? Can't find the callback for that.

**Comment by fancyapps** [comment]
This is how you can check if reached last item:

```JS
afterShow: function(instance, current) {
    if (current.index  ===  instance.group.length - 1) {
      alert('I am the last item of the gallery');
    }
  }
```

and the rest is up to you :)

**Comment by coldpumpkin** [comment]
Thank you! Can you please check my edit? Thanks =)
