### ISSUE TITLE
How to implement video in InternetExpolrer without download

### ISSUE THREAD

**Issue by techaditya** [fancyapps/fancybox#1671]
i face a problem in Internet Explorer that instead of playing the MP4 video , it says me to download it .
But my requirement is to play on browser instead of download.
![imgpsh_fullsize](https://user-images.githubusercontent.com/25634844/31373443-abc22c44-adb7-11e7-89c4-199368e27ebd.png)

**Comment by fancyapps** [comment]
It depends on how you are trying to display it. See this demo - https://codepen.io/anon/pen/eGrRZQ - works fine.

**Comment by Nageshwar** [comment]
It works perfect 

Thank You very much for the fast response
Happy Coding :)

**Comment by techaditya** [comment]
Thank you for your fast reply.
But i face a issue in Internet Explorer in different resolution and responsive mode in Internet Explorer.
no control over the video control button in different resolution and responsive mode.

**Comment by kloneets** [comment]
Video controls is on IE side not fancybox. And I guess, your video is somehow corrupted. At least I have got same errors in my projects, when video is encoded with wrong encoder/options.

**Comment by fancyapps** [comment]
Yes, @kloneets is right. Also, it is a bad idea to edit local files and open them directly in the browser. You have to use some webserver for proper development or you will encounter multiple issues (like iframes, ajax not working).
