### ISSUE TITLE
Zoom opening animation forces the image to resize first before zooming

### ISSUE THREAD

**Issue by shermendev** [fancyapps/fancybox#1675]
If I open an image and then try to zoom it by clicking on it, instead of zooming the image resizes from decimal to integer number in height and width. If I click it again it zooms normally. 

The bug only appears if I leave the default "animationEffect : 'zoom'", if I change it to fade, zoom works normally after the first click.

Hope you could take a look at it,
Thanks

**Comment by shermendev** [comment]
This hack solved my problem           
` $(document).on('afterShow.fb', function() { $.fancybox.getInstance().update() }) `

**Comment by fancyapps** [comment]
Just do not use jQuery v3.0 and v3.1, these versions have a bug affecting calculations.

**Comment by shermendev** [comment]
I use v3.2.1

**Comment by fancyapps** [comment]
Then I have no clue.

**Comment by intransitorio** [comment]
@shermendev your hack saved my life
