### ISSUE TITLE
Fancybox 3 with angular-drag-and-drop-lists

### ISSUE THREAD

**Issue by timrate** [fancyapps/fancybox#1676]
I'm having an issue combining fancybox 3 with https://www.npmjs.com/package/angular-drag-and-drop-lists. It seems to be fancybox thats failing which is why I've opted to post here. Plus I've got a commercial license (which I can provide on request)

I'm attempting to use fancybox to pop up windows to edit child objects from a table:

`<table class="centered bordered striped">
                <thead>
                    <tr>

                        <th>Select</th>
                        <th>Edit Applied Rule/Exception</th>
                        <th>Rule</th>
                        <th>Exception</th>
                        <th>Test</th>
                        <th>Type</th>

                    </tr>
                </thead>

                <tbody dnd-list="dialingCategorySequences" class="dialingCatrgory">
                    <tr ng-repeat="sequence in dialingCategorySequences" dnd-draggable="sequence" dnd-moved="dialingCategorySequences.splice($index,1)"
                        dnd-effect-allowed="move" dnd-selected="models.selected = sequence" ng-class="{'selected':models.selected === sequence }">
                        <td>
                            <input type="checkbox" id="checkbox_{{sequence.dialingCatSequence}}" value="{{DC.id}}/{{sequence.dialingCatSequence}}" />
                            <label for="checkbox_{{sequence.dialingCatSequence}}"></label> </td>
                        <td><a data-fancybox data-type="iframe" ng-href="DialingCategorySequenceEdit.html?dialingCategoryID={{sequence.fkDialingCatId}}&sequenceID={{sequence.dialingCatSequence}}"
                                href="javascript:;">Edit</a></td>
                        <td><a data-fancybox data-type="iframe" ng-href="../Rules/RulesEdit.html?RuleNumber={{sequence.fkRulesId}}"
                                href="javascript:;" >{{sequence.RuleName}}</a></td>
                        <td><a data-fancybox data-type="iframe" ng-href="../Exceptions/ExceptionsEdit.html?ExceptionNumber={{sequence.fkExceptionsId}}"
                                href="javascript:;">{{sequence.ExceptionName}}</a></td>
                        <td><a data-fancybox data-type="iframe" ng-href="../Timezone/TimezoneEdit.html?id=1"
                            href="javascript:;" data-type="iframe">blahblah</a></td>
                                
                        <td>{{ sequence.type }}</td>
                    </tr>
                </tbody>`

The links all work but just redirect the browser to the page vs opening it in an iframe as intended. If I remove the angular-drag-and-drop-lists code like so:
`<table class="centered bordered striped">
                <thead>
                    <tr>

                        <th>Select</th>
                        <th>Edit Applied Rule/Exception</th>
                        <th>Rule</th>
                        <th>Exception</th>
                        <th>Test</th>
                        <th>Type</th>

                    </tr>
                </thead>

                <tbody dnd-list="dialingCategorySequences" class="dialingCatrgory">
                    <tr>
                        <td>
                            <input type="checkbox" id="checkbox_{{sequence.dialingCatSequence}}" value="{{DC.id}}/{{sequence.dialingCatSequence}}" />
                            <label for="checkbox_{{sequence.dialingCatSequence}}"></label> </td>
                        <td><a data-fancybox data-type="iframe" ng-href="DialingCategorySequenceEdit.html?dialingCategoryID={{sequence.fkDialingCatId}}&sequenceID={{sequence.dialingCatSequence}}"
                                href="javascript:;">Edit</a></td>
                        <td><a data-fancybox data-type="iframe" ng-href="../Rules/RulesEdit.html?RuleNumber={{sequence.fkRulesId}}"
                                href="javascript:;" >{{sequence.RuleName}}</a></td>
                        <td><a data-fancybox data-type="iframe" ng-href="../Exceptions/ExceptionsEdit.html?ExceptionNumber={{sequence.fkExceptionsId}}"
                                href="javascript:;">{{sequence.ExceptionName}}</a></td>
                        <td><a data-fancybox data-type="iframe" ng-href="../Timezone/TimezoneEdit.html?id=1"
                            href="javascript:;" data-type="iframe">blahblah</a></td>
                                
                        <td>{{ sequence.type }}</td>
                    </tr>
                </tbody>`

Fancy box works. Is there any way I can work around this issue? I'm not getting any errors in the console, and I'm using fancybox with angular elsewhere so I know thats not the issue. Any help is appreciated.

**Comment by fancyapps** [comment]
You have answered to your own question - "If I remove the angular-drag-and-drop-lists .. Fancy box works" - you just have to find out how to re-enable click events.

**Comment by timrate** [comment]
Can you expand a bit? I was hoping for a little more insight as to why fancybox wasn't launching while angular drag and drop is being used, or another way to call fancybox so it would work from within there.

**Comment by fancyapps** [comment]
You can see here - https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L2946 - that jQuery plugin is just a tiny part of the whole code. It just attaches click handler to selected elements. That click handler later calls "$.fancybox.open()" where actual magic happens. 

So, I assume that your drag-drop library caches click events and prevents from bubbling up, therefore breaking other scripts. 

After quick look at docs - https://www.npmjs.com/package/angular-drag-and-drop-lists- I guess that the simplest solution would be to add `dnd-disable-if` attribute on these links to disable dragging.

**Comment by timrate** [comment]
I unfortunately need to be able to drag the rows around to reorder the list which is what I'm able to do with the table. 

I'm having some luck using an old version of fancybox 2.1.4
    
and calling it from an angular function in ng-click. I couldn't get it to work with the latest version of fancybox though. ($.fancybox is not a function) This may work for me since there are only a couple pages that need to combine these libraries. Currently I'm just needing to work through css with that version.

` $scope.open = function (url) {
        console.log("clicked! fancybox should open:" + url)
        $.fancybox({
            href: url,
            type: 'iframe',
            margin: 30,
            padding: 7,
            scrolling: false,
            width: '100%',
            height: '100%',
            openEffect: 'fade',
            closeEffect: 'fade',
            fitToView: true,
            closeBtn: true,
            closeClick: false
        })
    }
`

This may be my workaround though I'd rather be able to use the same version of fancybox throughout the app.

**Comment by fancyapps** [comment]
That`s great! Check the new API - http://fancyapps.com/fancybox/3/docs/#api - and use it like this:

```JS
$.fancybox({
    src  : url, 
    type : 'iframe',
    opts : {}
});
```
