### ISSUE TITLE
Validation breaks setBigImage in IE with jQuery 1.12

### ISSUE THREAD

**Issue by cepheiVV** [fancyapps/fancybox#1678]
Is there any good reason to validate the image, after it has just been created?
https://github.com/fancyapps/fancybox/blob/master/dist/jquery.fancybox.js#L1720

This validation breaks the fullscreen in my setup, because IE seems to set an error on that image.
 - IE 11
 - Fancybox 3.1.28
 - jQuery 1.12

(It is working with jQuery 3)

**Comment by kloneets** [comment]
In fancybox dependencies it states: `jQuery 3+ is preferred, but fancyBox works with jQuery 1.9.1+ and jQuery 2+.`
So: jQuery 1.12 is not supported.

**Comment by cepheiVV** [comment]
well ok. but it doesn't answer why there is that validation on line 1720.
The question is if that validation is necessary.
After all the my setip above works without that validation.

**Comment by kloneets** [comment]
It is not validated on image creation. Those all are events, so, validation is performed on event: `load` -> when image is loaded and `error` -> on some kind of error. Update jQuery and check if problem still exists.

**Comment by cepheiVV** [comment]
Alright. As said; it works fine with recent jQuery version. 
The only issue with jQuery 1.12 and IE was that one validation check.

**Comment by fancyapps** [comment]
Hi,

Try the latest version (v3.2.0).
