### ISSUE TITLE
TransitionEffect 'slide' and IE11

### ISSUE THREAD

**Issue by mbc9** [fancyapps/fancybox#1679]
fancybox.open(gallery_array, { loop: true, transitionEffect : "slide" })

The slide effect works on all common browsers EXCEPT IE11, where it appears to simply replace the image. I know from experience that IE11 always seems to need some adjustments to get transformations working the same as other browsers.

Using:
https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css
https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js

**Comment by fancyapps** [comment]
Hi,

Could you, please, try the latest version? It works fine for me, but ie11 is a mystery, it sometimes struggles on some computers (maybe it depends on win version, not sure).

**Comment by VeAleks** [comment]
i detected this issue in the windows10 - IE11 only
the last version is don't help and your site have a same problem http://prntscr.com/kwo94k
can you fix this issue?
