### ISSUE TITLE
how to : use fancybox with infinit scroll plugin

### ISSUE THREAD

**Issue by vincent3569** [fancyapps/fancybox#1683]
Hi
I wish to use fancybox jQuery plugin with [infinit-scroll jQuery plugin](https://github.com/metafizzy/infinite-scroll).
fancybox works fine on the first page of pictures but doesn't show images appended with infinit-scroll.

have you any idea how to configure fancybox and infinit-scroll calls to works all together ?

**Comment by fancyapps** [comment]
Hi,

See http://fancyapps.com/fancybox/3/docs/#usage and use it like this:

```JS
$().fancybox({
  selector : '[data-fancybox="images"]',
  // other options 
});
```

**Comment by vincent3569** [comment]
sorry, but it doesn't work.

I use fancybox like this:

`$(document).ready( function() {
	$().fancybox({
	    selector : '[data-fancybox="images"]',
		loop : true,
		// other options
	});
});`

and somewhere else, I use infinit-scroll like that:

`var $container = $('.image-wrap');
var $pageLoadStatus = $('.page-load-status');
var $viewMoreButton = $('.view-more');

$(document).ready( function() {

	$container.infiniteScroll({
		path : '.infinit-next-page',
		append : '.image-thumb',
		hideNav : '.infinit-pagination',
		status : '.page-load-status',
		loadOnScroll : false,
	});

	$container.on( 'append.infiniteScroll', function( event, response, path, newElements ) {
		var $newElems = $(newElements).css({ opacity: 0 });
		$newElems.imagesLoaded( function() {
			$('.flag_thumbnail').removeAttr('style');
			$newElems.animate({ opacity: 1 });
		});
	});

	$viewMoreButton.on( 'click', function() {
		$container.infiniteScroll('loadNextPage');
		$container.infiniteScroll('option', {
			loadOnScroll : true,
		});
		$viewMoreButton.remove();
	});

	$container.on( 'last.infiniteScroll', function( event, response, path ) {
		$pageLoadStatus.animate({ opacity: 0 }, 5000);
	});

});`

but fancybax works fine for images initaly loaded, doesn't show images loaded by infinit-scroll behavoir

you may have a look on this [test site](http://test.vincentbourganel.fr/20170505-voyage-new-york-city/)

**Comment by fancyapps** [comment]
Please, upgrade to the latest version.

**Comment by vincent3569** [comment]
works fine with 3.1.28 build.
really thanks for your help!!
