### ISSUE TITLE
Disable Fancybox3 with Javascript using Groups

### ISSUE THREAD

**Issue by sullivan8** [fancyapps/fancybox#1684]
First of all, thank you very much for this appreciated plugin!
Using iPhone7 with iOS11, I still/or again encounter scrolling issue, also in the ajax demo of your website. Is there any workaround? 
I've been trying to disable FB3 in device mode as a workaround, but I cannot achieve this with required grouping function:

data-fancybox="post" auto-initiates the fb3 without any javascript. If I use a custom class, it won't work with multiple slides as a group (or there is no attribute any more, rel doesn't work).

**Comment by fancyapps** [comment]
Hi, Thanks!

I have created a workaround for iOS issues and it will be included in the next commit. I am planning to release new version in the beginning of the next week.

To disable auto-initializing, remove `data-fancybox` attributes or unbind click event - `$(document).off( 'click.fb-start' );`;

**Comment by sullivan8** [comment]
great! when I remove data-fancybox, the navigation to the next slide doesn't work any more. Are there other possibilities to group them without data-fancybox?

**Comment by fancyapps** [comment]
No. Simply set `data-fancybox` for grouping and use any selector for setting custom options.

**Comment by sullivan8** [comment]
It's initiated with 
`$("[data-fancybox]").fancybox({`

The elements have
`data-fancybox="post"`

and to disable with
`$("[data-fancybox]").off( 'click.fb-start' );` doesn't help. If I avoid data-fancybox, it'll work but it's not in a group.
