### ISSUE TITLE
Caption Placement

### ISSUE THREAD

**Issue by Webdude737** [fancyapps/fancybox#1687]
I am unable to move the caption to below the image (instead of above the thumbnails (horizontal thumbnail version  https://codepen.io/fancyapps/pen/PjYPMw )?

I tried to change tpl by placing fancybox-caption-wrap into fancybox-stage div, but it looks like the code is injecting the other divs for the image (fancybox-slide), so I am not sure how to place the caption div inside of the image div so that the caption is immediately underneath the image (as opposed to immediately above the thumbnails.

**Comment by fancyapps** [comment]
Hi,

Sorry, fancyBox v3 is just not designed for this.

Duplicate of #1590
