### ISSUE TITLE
Iframe & dynamic height

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1689]
Hi.
What is the best solution so that iframe height is calculated based on iframe content? Also in some cases content height is adjusting, for example: in content you have login and thank you page (redirect) which height is different.

Kind regards.

**Comment by fancyapps** [comment]
Hi,

This is done "automagically" and you do not need to do anything special for that to happen.

Of course, your pages need to be on same domain, etc (https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy)

**Comment by xApep** [comment]
Hm hm. Just can't figure out why height is not fitted. 

![image](https://user-images.githubusercontent.com/1315340/34935497-671819b4-f9de-11e7-9e64-c456bb1a93ac.png)

In iframe I don't have any css.
Anchor link which trigger iframe:

> <a href="somelink.html" data-type="iframe" class="btn_inquiryPopupWidget">link</a>

js init

>         $(".btn_inquiryPopupWidget.size_2").fancybox({
>             baseClass : 'inquiryPopupWidget size_2',
>             closeClickOutside   : false,
>             iframe : {
>                 preload         : false,
>                 scrolling       : 'yes'
>             },
>             fullScreen          : false,
>             closeBtn            : false,
>             toolbar             : false,
>             infobar             : false,
>             smallBtn            : true
>         });

Im using v3.2.10

Thanks!
