### ISSUE TITLE
Image disappears after Fancybox opens

### ISSUE THREAD

**Issue by dhechler** [fancyapps/fancybox#169]
I have fancybox 2.0.5 installed and running on http://dhechler.sgg.websitestat.us/food/10/demo-post-8/ 
The issue for me (tested in many browsers) is that the original image inside the post disappears when the image opens in fancybox. When inspecting the element, then clicking on the picture, I can see the image be stripped out of the DOM all together.

**Comment by qsang888** [comment]
In addition, the href attribute on the a tag must be specified ( such as, <a href="image.jpg"></a>)

**Comment by harveydobson** [comment]
I get that this needs to be applied on the link element. But why is this the case? 

The light-box works perfectly otherwise, surely this should be configurable as to whether you want this as desired functionality or not?
