### ISSUE TITLE
Fancybox conflicting with other jquery theme files

### ISSUE THREAD

**Issue by abhimodi07** [fancyapps/fancybox#1690]
Hi, fancybox is working perfectly fine but it interrupts other jquery files which result in menu malfunctioning( drop-down menu stops working). On debugging I found the following things in chrome: https://www.putmeonline.net/themes.php

Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4
    at bootstrap.min.js:6
    at bootstrap.min.js:6

plugins.js:29 Uncaught TypeError: $(...).affix is not a function
    at plugins.js:29
    at plugins.js:113

whmcs.js:11 Uncaught TypeError: jQuery(...).popover is not a function
    at HTMLDocument.<anonymous> (whmcs.js:11)
    at Function.ready (jquery.min.js:29)
    at HTMLDocument.u (jquery.min.js:37)

The moment i remove fancybox jquery.min.js from header. fancybox lightbox stops working.

Please help me how to resolve the issue. Anyways thanks for the awesome Fancybox.

**Comment by fancyapps** [comment]
Hi,

1) Sorry, fancyBox v1 (and v2, too) is not supported.

2) Some of your scripts (most likely one of your wp plugins) generates additional <script> tags and one of them includes jQery v1.4 and that is why you see that messages in the console.

**Comment by kloneets** [comment]
Wordpress by default imports old jquery with migration plugin. In most cases it is not necessary in frontend but backend depends on it. If you are logged in, then admin bar in frontend needs it also. (wordpress is evil). So you need to remove those unnecessary jquery imports or organise them right with wordpress hooks. 
You can start by reading this: https://stackoverflow.com/questions/18421404/how-do-i-stop-wordpress-loading-jquery-and-jquery-migrate

For example, you can replace old jquery with new one only for frontend.
