### ISSUE TITLE
Payment in Polish currency [fancybox3]

### ISSUE THREAD

**Issue by Jacqbus** [fancyapps/fancybox#1691]
Hi.
There's no other possibility to contact with you, so i decided to open this "issue".

Commercial extended licence costs $119 but when i change my country to Poland, it costs about 531PLN so $147.8 after conversion at the current exchange rate. So my question is it's some kind of bug, your constant exchange rate or it's just more expensive license for people from Poland?

**Comment by fancyapps** [comment]
Hi,

Most likely it is the final price after the VAT is added. If you gave a VAT ID, then you can enter it while making payment and the VAT will be not charged (it is done automatically by FastSpring).

Sorry for confusion, I`ll add a note about that.
