### ISSUE TITLE
Loop slides?

### ISSUE THREAD

**Issue by oelbaganwg** [fancyapps/fancybox#1692]
Is there anyway to loop slides to just bring back the first slide when you get to the end. So you can simply continuously go through slides even though they repeat.

**Comment by fancyapps** [comment]
Yes, there is an option `loop` for that, for example:

```JS
$( '[data-fancybox="images"]').fancybox({
	loop : true
});
```

https://codepen.io/anon/pen/BwMaYv?editors=1010
