### ISSUE TITLE
Fancybox 3 scrolling background

### ISSUE THREAD

**Issue by egorlero** [fancyapps/fancybox#1693]
Hello! 

At the beginning I want to say thank u for your huge job with fancybox:) 

I have iPhone 6 with iOS 10.3, safari browser and my issue is when my pop up window is open for example with Vimeo video inside, i swipe up and the background start scrolling. When I close the window background back to the start position before I press the link.

I repeat this situation on your website. 

For better understanding I attach the video. Link below:)

https://youtu.be/SQUpK8fWYHw

How can I fix this? Thx for your answer:)

**Comment by fancyapps** [comment]
Hi,

Sadly, if there would be some nice way to fix this, it would already be already done. The only workaround is to make body element fixed position. But this has ugly side-affect: address bar enlarges after changing body position. This is why I did not implement this from the beginning. But, sadly, latest iOS brings another issues, therefore I have no other choice. 

See this - https://github.com/fancyapps/fancybox/issues/1646 - and try next beta https://fancyapps.com/fancybox/3/fancybox/3.2/
