### ISSUE TITLE
Jumping Backgrounds (body)

### ISSUE THREAD

**Issue by mpsn** [fancyapps/fancybox#1694]
When a background on the body is set it "jumps" on opening fancybox (with and without  CSS cover). Putting the background on a DIV inside the body works in Chrome but in Firefox the jumping remains. Chrome and Firefox seem to handle the overflow of the HTML-tag differently. Deactivating overflow: hidden for .fancybox-enabled eliminates the jumping but then of course the scrollbar is visible and working.

An example can be found at (just updated to current version):
http://www.zen-karate-goettingen.de/impressionen/index.html

**Comment by fancyapps** [comment]
Hi,

Long story short, the easiest solution would be for you to change background image sizing from:

`background-size: cover;`

to:

`background-size: 100vw;`

**Comment by mpsn** [comment]
Thank you for the fast answer! But unfortunately that still does not solve the problem in Firefox.

**Comment by fancyapps** [comment]
Looks like that you would need to remove `center top` position from background property.

**Comment by mpsn** [comment]
Thanks a lot! That was the solution...
