### ISSUE TITLE
Position buttons relative to image

### ISSUE THREAD

**Issue by W1zzardTPU** [fancyapps/fancybox#1697]
It seems impossible to position the prev/next buttons flush next to the displayed image, because .fancybox-stage uses position: absolute, covering the whole viewport.

Any ideas how this could be adressed?

I'm looking to reproduce the behaviour of:
https://www.techpowerup.com/238072/asus-rog-strix-1070-ti-turbo-graphics-cards-pictured
(we currently use colorbox with custom css)

- buttons directly to the left and right of the image
- button clickable area extends over  the displayed image to make prev/next clicking easier

**Comment by W1zzardTPU** [comment]
afterShow: function( instance, current ) {
  			$('.fancybox-arrow--left').appendTo('.fancybox-slide--current > div');
  			$('.fancybox-arrow--right').appendTo('.fancybox-slide--current > div');
  		},

seems a bit like hack..

**Comment by fancyapps** [comment]
Hi,

Sorry, this is currently not possible in v3 and there is (somewhere) already a feature request for that.

Anyway, why do you think that this would improve something? Would it not then be easier to use navigation buttons at the top, like this:
https://codepen.io/anon/pen/yPypVb

**Comment by W1zzardTPU** [comment]
I would think navigation buttons on the sides, near the image are easier to see/use than ones near the edge of the screen. Especially on high-res, when the image is significantly smaller than the viewport.

**Comment by zone1creative** [comment]
Is it possible to do this in fancybox 3 yet?
