### ISSUE TITLE
[BUG] Loading spinner position not horizontal centered

### ISSUE THREAD

**Issue by Patta** [fancyapps/fancybox#1699]
It seems that the loading spinner `.fancybox-slide > .fancybox-loading` is not 100% horinzontal centered. I think it comes from `.fancybox-slide>div{padding:24px;}`.

`.fancybox-slide > .fancybox-loading{margin-left:-37px;}` fixed this temporarly.

**Comment by fancyapps** [comment]
Hi,

Thanks for noticing (it was pushed bottom/right by border-width).
