### ISSUE TITLE
Problems getting images to recognize they are in the same gallery. 

### ISSUE THREAD

**Issue by thedonquixotic** [fancyapps/fancybox#1700]
I'm using fancybox to put lightboxes on my Wordpress website. So far I have it working great for a custom gallery post type I made for multimedia masonry layout. 

The issue I'm having is having it properly apply to galleries inserted into a post through the default Wordpress gallery functionality. 

I've tried the suggestions here: https://wordpress.stackexchange.com/questions/45005/how-do-i-add-class-fancybox-to-the-default-gallery/181728#181728

And while they do work in applying fancybox to individual gallery items, fancybox does not appear to be recognizing they they are meant to be all in the same gallery. 

So I run: `jQuery(".gallery-icon a").fancybox().attr('rel', 'wp-gallery-fancybox');` and I get working lightboxes for all the images but no navigation buttons etc to switch between items in the gallery. 

If I run:
```
 jQuery('.gallery').each(function (g) {
    jQuery('a', this).attr('rel', function (i, attr) {
         return attr + ' gallery-' + g;
    });
});`
```

Then I get separate gallery rel names for each gallery inserted into the most but again, each image is treated individually rather than as part of a group gallery. 

Any ideas what I'm doing wrong? 

**EDIT:**

![image](https://user-images.githubusercontent.com/9451726/31963096-375be02a-b8c5-11e7-9d83-2e59afd71810.png)

Maybe this response from the console when I run the script manually in the console gives a clue?

I also tried using the arrow keys to see if maybe it was grouping them as a gallery, it just wasn't showing the UI, but using the arrow keys confirms that it's treating each individual picture as it's own gallery despite the fact that they're all sharing the same rel. 

I do notice that on my other fancybox custom masonry post gallery I made a couple of months ago, that it defines the grouping of a gallery not by "data-fancybox=gallery" instead of the "rel=gallery" that results from the JS script I found in the stack exchange responses. 

As those responses are from 2013, I'm guessing something changed where instead of rel it's now data-fancybox instead? I haven't quite gotten deep enough into my studies to really understand how the data metadata js stuff works in web dev but I think I have an idea of something I could try.  I'll post if it works.

**Comment by thedonquixotic** [comment]
BINGO! That worked! So I changed the script from  `jQuery(".gallery-icon a").fancybox().attr('rel', 'gallery');` to ` jQuery(".gallery-icon a").fancybox().attr('data-fancybox', 'gallery');`

**Comment by fancyapps** [comment]
Hi,

Yes, you are right, fancyBox now uses `data-fancybox` attribute for grouping (because `rel` is actually mean to be used for different purposes).
