### ISSUE TITLE
Using this in beforeLoad returns two instances

### ISSUE THREAD

**Issue by buzzfizz** [fancyapps/fancybox#1701]
Hi I want to get the current image while scrolling through the image gallery. When I use this in beforeLoad while opening the first image, the console returns 2 objects. If I slide next this returns the object after the current object. Makes sense? This only happens when using images. Youtube videos works fine.

Currently using Fancybox 3 with jQuery 1.9 since I am developing for Wordpress.

Thanks!

**Comment by fancyapps** [comment]
Hi,

fancyBox preloads and creates 3 slides by default, so that user can nicely see next/prev image while dragging/swiping. This event is fired for each of them and this is how you can check when current image starts loading:

```JS
$('[data-fancybox="images"]').fancybox({
  beforeLoad : function(instance, slide) {
    console.info( slide.index === instance.currIndex );
  }
})
```
https://codepen.io/anon/pen/JOoyYZ?editors=1010
