### ISSUE TITLE
clicks insight captions area does not work 

### ISSUE THREAD

**Issue by B0rner** [fancyapps/fancybox#1702]
Hey,

I'm using fancybox 3.1.20 for an image gallery and I'm trying to place a 'download-button' at the caption field, so that the user can download additional information about the picture or download the picture itself.
The problem is, that fancybox seams to disallow clicks or click events insight the caption area.

Please take a look at this example: https://codepen.io/anon/pen/WXeePe
It is not possible to trigger the download insight the caption.

**Comment by B0rner** [comment]
and.. by the way: fancybox seams to change the layout of the button. In the example above, the reference button outsight the fancybox caption looks different than the button insight the fancybox caption. This means, that an "cooperate design" is not available insight the caption area.

**Comment by fancyapps** [comment]
Hi,

You can re-enable click events using CSS:

```CSS
.fancybox-caption-wrap {
    pointer-events: all;
}
```

They are re-enabled for `a,button,select` elements by default.

btw, I'm now experimenting with different CSS - https://fancyapps.com/fancybox/3/fancybox/3.2/

**Comment by B0rner** [comment]
Hey,

unfortunately adding this css does not result in an reactivation of an button insight the caption.
Please take a look here: https://codepen.io/anon/pen/NwGWNz

Well, I'm not hard-wired with the Fancybox 3.1 world, if the 3.2 version fixes the problems.
If your 3.2.0 is in beta: does it mean, there is an feature freeze and API-freeze? So i could an would test the software for you. Probably there is no documentation of the new handling, right?

**Comment by fancyapps** [comment]
Hi,

Buttons work fine, but you are binding click event on non-existing elements. You could, for example, use event delegation, like so:

`$('body').on('click', 'button', function(){ alert('download started....')});`
