### ISSUE TITLE
ajax datatype issue

### ISSUE THREAD

**Issue by mdss-single** [fancyapps/fancybox#1703]
Hi.
I have some trouble with ajax loaded file.
I call fancybox manually
```
			$.fancybox.open({
				src  : 'map/'+code+'.html',
				type : 'ajax',
			});
```
And datatype of loaded document XML. How can I set html datatype?

**Comment by fancyapps** [comment]
Hi,

You can use option ajax.settings to customize settings for ajax request (http://api.jquery.com/jquery.ajax/), for example:

```JS
$.fancybox.open({
  src  : 'map/'+code+'.html',
  type : 'ajax',
  ajax : {
    settings : {
      dataType : 'xml'
    }
  }
});
```
