### ISSUE TITLE
Trigger fancybox on page load with hash doesn't work properly

### ISSUE THREAD

**Issue by coldpumpkin** [fancyapps/fancybox#1705]
HTML:
```
<div id="photos">
    <div class="column">
        <a href ="photo1.jpg" data-group="misc" id="photos"><img src="photo1.jpg"></a>
        <a href ="photo2.jpg" data-group="misc"></a>
        <a href ="photo3.jpg" data-group="misc"></a>
    </div>
</div>
```

JS:
```
var fancyboxHash = window.location.hash;
if(fancyboxHash) {
    $(fancyboxHash).trigger('click');
}

$('#photos .column').fancybox({
    thumbs : {
        autoStart : true
    },
    beforeShow: function(instance, slide) {
        var miscid = $(slide.opts.$orig).attr('id')
        if (miscid) {
            window.location.hash = miscid;
        }        
    },
    beforeClose: function(instance, slide) {
        window.location.hash = "";
    }        
});
```

With this code, whenever someone enters http://mysite.com#photos it will load fancybox with photo1 but it will ignore the settings I have in the "#photos .column" call I have, it just loads the default fancybox settings I assume, because technically it's clicking "#photos" and not "#photos .column"-something. Does that make sense?

How can I make it work properly?

Thanks in advance

**Comment by fancyapps** [comment]
Hi,

Probably because your click event code will execute before you are applying custom option using `fancybox()`.

**Comment by coldpumpkin** [comment]
Sometimes I get scared of how stupid I can get ¯\_(ツ)_/¯ 

Thanks Janis!
