### ISSUE TITLE
Vertical swipe

### ISSUE THREAD

**Issue by polygonator** [fancyapps/fancybox#1706]
Hello,
I have problem on android device in chrome
when I pass my finger up fancybox close, but I see gray overlay on my page
I if i open it again I can't click on close button sometimes

this screen after close popup
https://pp.userapi.com/c841428/v841428888/34b77/q3L6elZWo1M.jpg

site url https://polygonator.github.io/services

Thank you

**Comment by fancyapps** [comment]
1) What android/chrome version do you have?
2) What do you mean by "when I pass my finger up fancybox close, but I see gray overlay on my page".

Anyway, I do not see any issue.

**Comment by oleg-tgn** [comment]
Sorry for my english

I swipe to top pop up, it close, and after that i see gray overlay on screen

Android 5.1
Chrome 55
https://pp.userapi.com/c824203/v824203490/a9f1/3Md3gcTtOVE.jpg
