### ISSUE TITLE
[API] $lastFocus error - it's body

### ISSUE THREAD

**Issue by iBars** [fancyapps/fancybox#1707]
I use this code to write in fancybox form field (named "wtf")
`<input type="hidden" name="wtf" value="">`

Data-attribute "wtf" of button via fancybox was called. For example:

`<button type="button" data-fancybox data-wtf="Form of callback request was called last time">Request callback</button>`

Which must do that:

`<input type="hidden" name="wtf" value="Form of callback request was called last time">`

My code:

```
jQuery('[data-fancybox]').fancybox({
	afterShow: function(instance, current) {
		console.log(instance.$lastFocus['0']);
		console.log(instance);
		if (current.type == 'inline') {
			var formWTF = jQuery(current.src + ' form input[name="wtf"]');
			if (formWTF.length) formWTF.val(instance.$lastFocus['0'].dataset.wtf || '');
		}
	}
});
```

**Comment by iBars** [comment]
It's work on [this site](http://carton-systems.ru) [1], but not work on [this](http://doma-nk.ru/kupite-srub-dlya-bani-v-novokuzneczke-nedorogo.html) [2]

![image](https://user-images.githubusercontent.com/3519015/32250196-9668b566-be9c-11e7-86ed-11b35073b4b3.png)

**Comment by fancyapps** [comment]
Hi,

`$lastFocus` stores last active element (`document.activeElement`). If you want to get clicked element, then use `current.opts.$orig`
