### ISSUE TITLE
Fancybox - title on top and caption on bottom

### ISSUE THREAD

**Issue by REPTILEHAUS** [fancyapps/fancybox#1708]
Im trying to replicate this slider setup, they have a title on top and a caption on the bottom
https://www.pentagram.com/work/platform15?rel=discipline&rel-id=1#20109

I cant seem to work this in no matter what I try as fancbox sets the sizes of the images and also positions everything absolutely, when I start moving things around using baseTPL and setting relative classes it doesnt seem to stack nicely.. i remember in fancybox 2 you had the option of placing the title inside or outside, Is there any kind of way to achieve this with FB3 ?

**Comment by fancyapps** [comment]
Hi,

Just increase top margin and/or push down `fancybox-stage` element using CSS to give space for title. Then use some callback to update title area, add some styling for caption, background, etc and that's it, very simple :)

**Comment by REPTILEHAUS** [comment]
Literally just figured it out with    margin : [100, 100] and beforeshow ;) cheers
