### ISSUE TITLE
Identical iframe size but one shows scrollbars

### ISSUE THREAD

**Issue by mrwrighty** [fancyapps/fancybox#1709]
I am using the iFrame option to show content. Both pages use an 800 x 500 Panel and the Fancybox is set to 850 x 600.

One page shows perfectly centred, but the second page displays and the fancy box shows scrollbars as the content appears to be too big. The page showing the scrollbars is a copy of the page that doesn't show the scrollbars so the content size is identical.
![no-scroll](https://user-images.githubusercontent.com/6585298/32324358-08e5f320-bfc3-11e7-89a5-8022865a8623.PNG)
![scroll](https://user-images.githubusercontent.com/6585298/32324359-090417d8-bfc3-11e7-9a1c-ac47e8593554.PNG)

**Comment by fancyapps** [comment]
Hi,

Sorry, it is not possible to help you without seeing live page or at least some demo.

**Comment by mrwrighty** [comment]
My site requires a login for access. I am happy to set up a user for you to check the site, but cannot publish it publicly, am I able to PM you with the details.

**Comment by fancyapps** [comment]
If you wish, you can either use https://gitter.im/fancyapps/fancybox or send DM https://twitter.com/thefancyapps

**Comment by mrwrighty** [comment]
Have DM'd on Twitter, many thanks

**Comment by fancyapps** [comment]
First, you are using tables for creating borders and space around content? Seriously? I remember it was a thing in the 90`s, but, oh, come on!

Second, I have no idea why do you think that your content will be 800px wide, it never will, you have to take into account the width of the other table cells + are you aware that `<body>` tag has default margin values?

**Comment by mrwrighty** [comment]
I don't see whats wrong with tables necessarily, if using div's for layout most will use css to style like 
.table { display: table; }
.row { display: table-row; }
.cell { display: table-cell; }

Tables are by far the easiest in Visual Studio and have never had issues with them.

**Comment by fancyapps** [comment]
Tables are fine when they are used appropriately. In your case it was like this:

| body left margin | left cell | main content, width=800px | right cell | right body margin | 

there is no way that this would fit inside 800px wide container without scrollbars.
