### ISSUE TITLE
Uncaught Error: fancyBox already initialized  with ajax 

### ISSUE THREAD

**Issue by hubekraven** [fancyapps/fancybox#1710]
hi,

I am trying to use fancybox 3 to open contents that are from an html file.  the content is opened in a fanxybox iframe by a click in a button. But I can not close the frame when clicking the close button (x on the corner of the frame) . I am having the following error :  jquery-3.2.1.min.js:2 Uncaught Error: fancyBox already initialized
here is the code I have:

```JS
function open_form(source){
            $.fancybox.open({
                src : source,
                type : 'ajax',
                live:false,
                modal: false,
                closeBtn:false,
                opts : {
                    iframe : {
                        scrolling : 'auto',
                        preload: false,
                        css : { width : '500px',
                                height:'200px',
                         }
                    },
                    modal: false,
                    buttons: ["close"],
                    afterLoad : function( instance, current ) {
                         console.log(current);
                     }
                }   
            })
}
```

another question is how do I control the size of the frame when using ajax, as the css overwrite does not seem to affect my actual frame?

thanks for returning

**Comment by fancyapps** [comment]
Hi,

1) So, fix this error.
2) Use CSS

**Comment by hubekraven** [comment]
I not sure that I understand what you mean by "So, fix this error"
What I am tryng to undestand is why is this error raised when there? why would  query-3.2.1.min.js: initialize the fancybox?
also what do you mean by use CSS?

**Comment by fancyapps** [comment]
1) Since you have not provided a link to live page or any demo, I can only guess that your ajax response returns <script> tags and then you are having multiple fancyBox instances on the page and therefore you get this message.

2) Sorry, I`m puzzled, do I really need to teach you how to use CSS?
