### ISSUE TITLE
cannot Update content afterShow 

### ISSUE THREAD

**Issue by Nageshwar** [fancyapps/fancybox#1713]
Hello Everyone,

I am trying to update one content let say [COURSE TITLE] (screenshot attached). 

please tell me the better way to do that.

Thanks
![course](https://user-images.githubusercontent.com/3288042/32434849-403316c4-c305-11e7-9665-68166ead6077.png)

**Comment by fancyapps** [comment]
Hi,

You just have to replace contents of the current slide. For example:

```JS
$('.test-templating').fancybox({
  afterLoad : function(instance, current) {
    current.$content = $( current.$content.prop('outerHTML').replace( '\{\{TITLE\}\}', current.opts.$orig.data('course') ) );
    current.$slide.empty().append( current.$content );
  }
});
```

Demo:
https://codepen.io/anon/pen/eezMVj?editors=1010

**Comment by Nageshwar** [comment]
Thanks for you reply but I am not able to get the **current.$content.prop('outerHTML')** because I am using type Iframe. can you suggest me for I frame how can i achieve that?

**Comment by fancyapps** [comment]
If you are using iframe, then it would be best to pass some variable using link and then generate appropriate contents of the page. 

Otherwise, you could use some empty element and then update it within callback.

**Comment by Nageshwar** [comment]
Ok thanks , I was actually working with **then it would be best to pass some variable using link ** this idea but thought to ask if there is any better way.

Thanks
