### ISSUE TITLE
Question on Effect used

### ISSUE THREAD

**Issue by frasertulsa** [fancyapps/fancybox#1714]
I'm looking to figure out how -- fancybox could have been used for the effect used on www.mylarshades.com  on the home page, there is a slider that, after 2 seconds or so, a shade/comes down and is basically a transluscent overlay that is animated from top to bottom.   Was this done with Fancybox or does anyone know how this effect was created?

Thanks
John.

**Comment by mjcampagna** [comment]
Not Fancybox. Looks like they're using something called Revolution Slider. Whether that effect is a part of the slider, or something extra they've coded, you will need to figure out on your own. Good luck.

**Comment by fancyapps** [comment]
@mjcampagna do not be so harsh, anything is possible with fancyBox! Yes, even vertical animation, because you can define effects using CSS transitions, see this demo - 

https://codepen.io/anon/pen/JORWrd

**Comment by mjcampagna** [comment]
Was I harsh? That was not my intention. Sorry.
-- 

--
Matthew Campagna
The Turning Gate | http://theturninggate.net
Photographers Plugins and Resources

**Comment by frasertulsa** [comment]
Thanks all for the responses!  I sure wish I knew how to code or know where
to start.    John.

________________

View a Short Video message from John
<https://www.useloom.com/embed/3ae5a6a1c3c74eadbb0adce43428cc16>
*John Fraser, **Street View | Trusted Photographer*

*  Websites | Local Branding | Google Maps Trusted Photographer | 360º
Virtual Tours*
www.MountainHomeMarketing.com
*870-495-2800 Mobile*
*800-775-0619 Office xt 102*


*Claim Your Local Business Listing Free here
<http://www.seodle.com/tulsapanorama/how-to-setup-a-google-business-listing-and-verify-your-business.html>.*See
a Video of a Virtual Tour <https://youtu.be/KulJOlCOS8Y> we did for a local
business

*Our Other Websites*
www.Seodle.com   www.OarkImagery.com <http://www.oarkimagery.com>
www.TulsaPanorama.com <http://www.seodle.com/tulsapanorama/index.html>
