### ISSUE TITLE
item.type === undefined

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1716]
Thanks for the 3.2 release. I've spent the day toying with it, and it's pretty excellent. I've maybe found an issue, though. Following along with the captions example in your FAQ:

if ( item.type === 'image' ) ...

item.type is returning 'undefined'.

I've used this check previously with success, so the problem seems to be new in this version.

**Comment by fancyapps** [comment]
Hi,

Thanks, but I do not see any issue - https://codepen.io/anon/pen/mqrWEO?editors=1010

Could you give some more details?

**Comment by mjcampagna** [comment]
I think because I'm not specifying 'data-type="image"'. Does this not auto-detect any longer?

**Comment by fancyapps** [comment]
No, that part has not been changed. And in that demo, only first link has that attribute.

**Comment by mjcampagna** [comment]
When I remove it, though, that item does log 'undefined'. The others log correctly, though, so that's interesting.

**Comment by mjcampagna** [comment]
I've emailed you a link to my pen.

**Comment by fancyapps** [comment]
Oh, sorry, I remember now. I made a small change that I forgot about and that is probably affecting you. This is related to the issue that it was previously not possible to determine if fancyBox has successfully guessed the content type or not, because it always used `image` type as fallback. 
And it was removed.. hmm I am now thinking if that was good idea or not...

**Comment by mjcampagna** [comment]
Hm. Maybe check the src extension?

.jpg || .JPG === 'image'
.html === 'iframe'
else 'undefined'

... or something?

**Comment by fancyapps** [comment]
The script is already doing that, but there is no way to tell what you want to do with links like `https://source.unsplash.com/LFoaYq3gmc4` 

I am now thinking about creating new option, something like `defaultType:'image'`, that would solve both issues (you will be able to set to `undefined` or smth like that for unknown links) and some people actually prefer `iframe` as default type.

**Comment by mjcampagna** [comment]
That’s a good idea!
-- 

--
Matthew Campagna
The Turning Gate | http://theturninggate.net
Photographers Plugins and Resources

**Comment by fancyapps** [comment]
Actually, I have implemented this in the last commit, so, it should be fine now.

**Comment by mjcampagna** [comment]
It works beautifully. Thanks!
