### ISSUE TITLE
Video zoomed in mobile view

### ISSUE THREAD

**Issue by boonyao1122** [fancyapps/fancybox#1717]
![unknown](https://user-images.githubusercontent.com/19177931/32485689-461e159a-c3df-11e7-9b26-3beccd922420.jpeg)

Hello, I have problem with pop up iframe youtube in mobile and need you guys help.
Image above displayed the outcome of popup youtube video in mobile and as you can see the there's scaling issue. Can anyone tell me what i've done wrong and please correct me. Appreciate your time, thank you.

MY CODE,
`p.various(class='fancybox.iframe') !{ --IFRAME CODE--}`

`  $(document).ready(function() {
    	$(".various").fancybox({
    		maxWidth	: 1080,
    		maxHeight	: 1060,
    		fitToView	: false,
    		width		: 500,
    		height		: 400,
    		autoSize	: false,
    		closeClick	: false,
    		openEffect	: 'none',
    		closeEffect	: 'none'
    	});
    });`

**Comment by fancyapps** [comment]
Hi,

Sorry, but v2 is not supported, consider upgrading to v3.

Anyway, how are you creating your links and could you give a sample link? There should be no issue with scaling if you are using embedded links or they are recognized and converted automatically.

**Comment by boonyao1122** [comment]
Hi appreciate for your reply, i solved the issue already. the problem is i set the width and height inside iframe, which is wrong. thank you.
