### ISSUE TITLE
Upgrade to 3.1.25 broke app, image zooms off-screen.

### ISSUE THREAD

**Issue by docfresh** [fancyapps/fancybox#1718]
After upgrading from 3.0.47 to 3.1.25, FancyBox stopped working in our WiseJ application. Instead of zooming and centering the image, the image "zoomed" into the upper-right corner of the screen, and then off-screen. If we can find additional details we will post them here.

**Comment by docfresh** [comment]
https://fixity.io/?cid=1&issue=7  , click the image.  That is running v3.1.25.

**Comment by docfresh** [comment]
Now that I look at it, I may have a mismatch between the CSS version and javascript version.

**Comment by fancyapps** [comment]
Are you sure to updated both files - JS and CSS?

**Comment by docfresh** [comment]
That was the issue. Thanks. Feel free to delete this.
