### ISSUE TITLE
Getting error in query.fancybox.min.js

### ISSUE THREAD

**Issue by mrwrighty** [fancyapps/fancybox#1720]
After going full screen with a gallery, then closing the fancybox by clicking the background this error occurs.
JavaScript runtime error: Object doesn't support property or method 'trigger'

**Comment by fancyapps** [comment]
Hi,

What version are you using? I suspect it is a bit outdated.

**Comment by mrwrighty** [comment]
OK, just updated to the latest version and have the same problem, doesn't matter if I target the fancybox.min.js or just the fancybox.js.

I think the issue might be related to something else and may be you could offer some advice.

I have a link to open an fancybox iFrame that shows images in a gallery. Each image in the gallery will also open in a fancybox. So effectively I have a Fancybox overlay on the iFrame which in turn is already a fancybox content.

It is at this point that is I go full screen with the gallery content and click the background to close the fullscreen that the error occurs. I would much prefer to load the gallery from a single button perhaps without showing the iFrame gallery first do you have any suggestions.

**Comment by mrwrighty** [comment]
I may have answered my own problem, I have found your hidden div example in the Advanced demo on your page. I will give this ago.

**Comment by fancyapps** [comment]
btw, what do you mean by `iFrame`? Do you really have an iframed page or is it inline or ajax (like here - http://fancyapps.com/fancybox/3/#ajax)?

**Comment by mrwrighty** [comment]
Sorry changed to Ajax content and all ok now.
