### ISSUE TITLE
Compensate for scrollbar causes jumping at zoom!=100%

### ISSUE THREAD

**Issue by W1zzardTPU** [fancyapps/fancybox#1722]
The added margin seems fixed and independent of the zoom level in the browser, which causes jumping of various severity when zoomed in / out

**Comment by fancyapps** [comment]
If you are referring to the site you mentioned previously, then you simply have to use some wrapping element for your content and use that for horizontal centering instead of using <body> tag for that.

**Comment by fancyapps** [comment]
If you are referring to the site you mentioned previously, then you simply have to use some wrapping element for your content and use that for horizontal centering instead of using <body> tag for that.

**Comment by fancyapps** [comment]
If you are referring to the site you mentioned previously, then you simply have to use some wrapping element for your content and use that for horizontal centering instead of using <body> tag for that.

**Comment by fancyapps** [comment]
If you are referring to the site you mentioned previously, then you simply have to use some wrapping element for your content and use that for horizontal centering instead of using <body> tag for that.

**Comment by fancyapps** [comment]
If you are referring to the site you mentioned previously, then you simply have to use some wrapping element for your content and use that for horizontal centering instead of using <body> tag for that.

**Comment by W1zzardTPU** [comment]
Nope, your homepage with the showcases. Chrome, zoom in or out a lot to more clearly see the effect, then open the lightbox

**Comment by fancyapps** [comment]
You see, scrollbar-width changes while changing zoom level, but fancyBox caches this value on the first run. Therefore you can see some shifting after you open/close for the first time, zoom page and open 2nd time.
I am not sure if this is something to be concern about :/

**Comment by W1zzardTPU** [comment]
Confirmed, thanks for clarifying. I was changing zoom level without page reload. I agree, this is a non-issue then.
