### ISSUE TITLE
Instances not working in fancybox3

### ISSUE THREAD

**Issue by danlupascu** [fancyapps/fancybox#1723]
Hello. It seems that instances are not working or I am doing something wrong.

Here is a link with an example: https://codepen.io/danlupascu/pen/yPVGYp

To reproduce the issue:
1. Click on "Click Me" button
2. Close the box.
3. Click again on the "Click Me" button.

You will see that the second time the box is not opening. I used an instance to open the box in multiple ways and none of them work.

`1. instance.jumpTo(0);`
`2. instance.activate();`
`3. $.fancybox.getInstance('jumpTo', 1);`
`4. $.fancybox.getInstance().jumpTo(0);`

None of them seems to work. And I even get an error for the last one that says "$.fancybox.getInstance(...).jumpTo is not a function" .

I took the methods from the docs: [http://fancyapps.com/fancybox/3/docs/](docs)

**Comment by fancyapps** [comment]
Hi,

fancyBox works a bit differently. So, when fancybox starts, a new instance is created, but it is gets destroyed after closing - dom elements, events are removed, etc.

Therefore your code does nothing and you get these messages :)

**Comment by danlupascu** [comment]
Thank you for the answer. Now I see that I have to open a box every time with some index.

By the way, great plugin!!! Thank you.
