### ISSUE TITLE
data-lightbox attribute

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1724]
Hi.
On anchor link we have attribute data-lightbox="lb544" for image gallery.

If I init fancybox with following code nothing happens.

```
    $('[data-lightbox]').fancybox({
            thumbs : {
                autoStart : true
            },
            buttons : [
                'thumbs',
                'close'
            ]
        });
```

Any solution? Thanks

**Comment by fancyapps** [comment]
Hi,

You would need to change selector from `[data-lightbox]` to `[data-lightbox="lb544"]`.

I am surprised that you were expecting your code to work, maybe documentation was not clear? Here you can see an example how to apply options to one group - https://codepen.io/anon/pen/yPgJeY?editors=1010

**Comment by xApep** [comment]
My question was because this worked perfectly on fancybox2.

Tnx for help.

**Comment by xApep** [comment]
Hi. Sorry, but just can't figure out.

I have <a href="..." data-fancybox="gal_110"> in image gallery.

in js I have this:
`    if ( $.isFunction($.fn.fancybox) ) {
        $('[data-fancybox]').fancybox({
            thumbs : {
                autoStart : true
            },
            buttons : [
                'thumbs',
                'close'
            ]
        });
    }`
but this isn't working properly. The value / number in data-fancybox attribute are dynamic, because it groups gallery, so I can't init on exact selector. Any advice how to deal with this?

Thanks.

**Comment by xApep** [comment]
Sorry. I had a older version...new one works fine.
