### ISSUE TITLE
Target custom class in baseTpl

### ISSUE THREAD

**Issue by buzzfizz** [fancyapps/fancybox#1725]
Hi, I have created a custom base template like so:

`                baseTpl	:
                    '<div class="fancybox-container" role="dialog" tabindex="-1">' +
                        '<div class="fancybox-bg"></div>' +
                        '<div class="fancybox-inner">' +
                            '<div class="fancybox-infobar">' +
                                '<span data-fancybox-index></span>&nbsp;/&nbsp;<span data-fancybox-count></span>' +
                            '</div>' +
                            '<div class="fancybox-toolbar">{{buttons}}</div>' +
                            '<div class="fancybox-navigation">{{arrows}}</div>' +
                            '<div class="fancybox-stage"></div>' +
                            '<div class="fancybox-social">' +
                                '<button class="sharefb" title="Share FaceBook" data-share="hello"></button>' +
                                '<button class="sharetwt" title="Share Twitter" data-share="hello"></button>' +
                            '</div>' +
                        '</div>' +
                    '</div>',`

How do I target the custom class sharefb? As I want to dynamically change the data-share attribute.

Thank you!

**Comment by mjcampagna** [comment]
Something like this should get the job done.

````js
$(document).on({
	'beforeShow.fb' : function(e, instance, item, firstRun) {
		var shareBtn = instance.$refs.container.find('button.sharefb');
		shareBtn.attr('data-share', item.src);
	},
});
````

**Comment by mjcampagna** [comment]
If you only need to add buttons to the existing template, though, then you should just markup the buttons without changing the entire baseTpl.

````js
$.fancybox.defaults.btnTpl.myButton = '<button>...</button>';
````

In case you haven't seen it, have a look at item #3 in the FAQ.
http://fancyapps.com/fancybox/3/docs/#faq
