### ISSUE TITLE
Open thumbnails on start automatically

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1726]
Would be nice to add a new option - loop back to the first image - make it loops back to the first picture when you get to the end (the last one picture).

**Comment by fancyapps** [comment]
Do you really mean this one?

```JS
// Enable infinite gallery navigation
loop : false
```

Literally, the first option http://fancyapps.com/fancybox/3/docs/#options

**Comment by Eldenroot** [comment]
Ooooops, I am sorry - I really checked the options twice.

**Comment by Eldenroot** [comment]
@fancyapps - just one more question - I wanna show thumbnails panel default on start (on image open) - same as you have here: https://codepen.io/fancyapps/pen/WZmGmw - so I changed false to true here:
`thumbs : {
            autoStart   : true,                 // Display thumbnails on opening
            hideOnClose : true,                  // Hide thumbnail grid when closing animation starts
            parentEl    : '.fancybox-container'  // Container is injected into this element
        },`
Anyway it is not working, thumbnail panel is not opened automatically on start :( everything else is working what I changed in js file (infinity navigation, buttons, etc.). Thank you very much.

**Comment by fancyapps** [comment]
What do you mean by "what I changed in js file", do you really edit fancybox.js file? Hmm, I did not though that anyone would want to do that :)

**Comment by Eldenroot** [comment]
I only changed from false to true in the code sent above.

It is the easiest way for me, just one change and everything else leave
default.

**Comment by mjcampagna** [comment]
@Eldenroot You should really just init Fancybox in the page, rather than changing the JS file. Pasted this somewhere into your page.

````js
$('[data-fancybox]').fancybox({
  thumbs : {
    autoStart   : false,
    hideOnClose : true
  },
});
````

Normally, you'd want that in the footer. But I can see you have this snippet setting up your images:

````js
$(document).ready(function() {
  | $('.post_body img').each(function() {
  | var currentImage = $(this);
  |  
  | if (currentImage.hasClass('smilie') == false && currentImage.parent().is('a') == false) {
  | currentImage.wrap("<a target='_blank' data-fancybox data-type='image' href='" + currentImage.attr("src") + "'</a>");
  | }
  | });
  | });
 ```` 
So, you can perhaps get away with merging the two, e.g.

````js
$(document).ready(function() {

	$('.post_body img').each(function() {
		var currentImage = $(this);
		if (currentImage.hasClass('smilie') == false && currentImage.parent().is('a') == false) {
			currentImage.wrap("<a target='_blank' data-fancybox data-type='image' href='" + currentImage.attr("src") + "'</a>");
		}
  });

	$('[data-fancybox]').fancybox({
	  thumbs : {
	    autoStart   : false,
	    hideOnClose : true
	  },
	});

});
````
You can then also add any other options you want to the initialization, 'animationEffect' for example:

````js
$('[data-fancybox]').fancybox({
  animationEffect : 'fade',
  thumbs : {
    autoStart   : false,
    hideOnClose : true
  },
});
````

**Comment by Eldenroot** [comment]
Thank you very much!

**Comment by Eldenroot** [comment]
Is there any way how to enable "zoom" and "download" buttons without removing "//" from js too? Thank you very much!

@mjcampagna @fancyapps

**Comment by fancyapps** [comment]
What do you mean by 

> without removing "//" from js too

? This is how you can customize buttons: 

```JS
$('[data-fancybox="images"]').fancybox({
  thumbs : {
    autoStart : true
  },
  buttons : [
    'zoom',
    'download',
    'close'
  ]
});
```

https://codepen.io/anon/pen/yPZVRY?editors=1010

**Comment by Eldenroot** [comment]
Thank you, do you accept i18n translations? 

I am a JS noob, I need to add translation for my users, can I add own translations this way you mentioned above? Thank you very much for your time and support!

**Comment by fancyapps** [comment]
See example here - https://github.com/fancyapps/fancybox/issues/1753

**Comment by Eldenroot** [comment]
@fancyapps - thats great!

I merged all my fancybox code together, should be fine :)

`
$(document).ready(function() {

	$('.post_body img').each(function() {
		var currentImage = $(this);
		if (currentImage.hasClass('smilie') == false && currentImage.parent().is('a') == false) {
			currentImage.wrap("<a target='_blank' data-fancybox data-type='image' href='" + currentImage.attr("src") + "'</a>");
		}
  });
	$.fancybox.defaults.lang = 'cs';
	$.fancybox.defaults.i18n.cs = {
		CLOSE : 'Zavřít',
		NEXT : 'Další',
		PREV : 'Předchozí',
		ERROR : '<center><b>Zobrazovat a stahovat přílohy mohou pouze zaregistrovaní uživatelé, prosím přihlašte se!</b><br /><h6>V případě, že problém přetrvává, tak je požadovaný obsah pravděpodobně nedostupný. Prosím, zkuste to později.</h6><b><a href="member.php?action=login">>>> PŘIHLÁSIT/ZAREGISTROVAT SE <<<</a></b></center>',
		PLAY_START : 'Spustit prezentaci',
		PLAY_STOP : 'Pozastavit prezentaci',
		FULL_SCREEN : 'Celá obrazovka',
		THUMBS : 'Náhledy',
		DOWNLOAD : 'Stáhnout',
		SHARE : 'Sdílet',
		ZOOM : 'Přiblížit'
};
	$('[data-fancybox]').fancybox({
		loop : true,
		
		thumbs : {
	    autoStart   : true,
	    hideOnClose : true
	  },
		
		buttons : [
			'slideShow',
			'fullScreen',
			'thumbs',
			'share',
			'zoom',
			'download',
			'close'
  ]
	});
});
`
