### ISSUE TITLE
Add "Zoom" button by default (same as you added "download" button)

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1728]
I am sorry, I am a newbie - how can I add a zoom button to fancybox? I checked your documentation and demo - https://codepen.io/fancyapps/pen/LOZdmK - but I dont know where to add these custom templates and js stuff.

Maybe, is possible to add it by you into fanxybox same as the download button and commented it out?

**Comment by fancyapps** [comment]
I`m sorry, I added this button recently, but forgot to include this css snippet:

.fancybox-button--zoom svg path {
	fill: transparent;
}

therefore icon if filled out with the color. This will be included in the next commit, but you can preview it here - https://codepen.io/fancyapps/pen/WZmGmw

**Comment by Eldenroot** [comment]
Thank you very much!
