### ISSUE TITLE
Thumbnails image are blurred and cropped

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1729]
![image](https://user-images.githubusercontent.com/778890/32626011-5673ba98-c58e-11e7-8bd7-93bbd0a95223.png)

Hi,
will be possible somehow add "better" thumbnails? Because they are quite unusable in some cases - see the image above. Thank you, I really like FancyBox!

**Comment by fancyapps** [comment]
Hi,

Wow, how did you manage to get that? Please, show some demo.

**Comment by Eldenroot** [comment]
I use your FancyBox on my community forum (MyBB) - I used this tutorial: https://tkacz.pro/mybb-fancybox-thumbnails/ 

I will try to somehow create a demo, but I am a really newbie :(

**Comment by fancyapps** [comment]
Could you just give a link to your forum? I suspect that some CSS on your page might cause the issue, I can not image any other reason.

**Comment by Eldenroot** [comment]
@fancyapps - of course, is there any way how can I send you a credentials (username and password)?

**Comment by Eldenroot** [comment]
@fancyapps - nevermind - here it is: https://www.carcassonneforum.cz/thread-1532-post-10818.html#pid10818

Thank you in advance!

**Comment by fancyapps** [comment]
Oh, I see, your thumbnails are so tiny that they are stretched out. I`ll tweak the code.

**Comment by Eldenroot** [comment]
@fancyapps - great, I am looking forward! Thank you!

**Comment by Eldenroot** [comment]
@fancyapps - thank you very much, great support! Keep good work!
