### ISSUE TITLE
Add option to disable adding of compensate-for-scrollbar

### ISSUE THREAD

**Issue by W1zzardTPU** [fancyapps/fancybox#1731]
Please add an option to disable adding of compensate-for-scrollbar, would be more elegant than removing the added style on init

**Comment by fancyapps** [comment]
And why you would need that?

**Comment by W1zzardTPU** [comment]
Because it tends to break layout on some sites (and people might not know how/want to wrap their content in a div)

**Comment by W1zzardTPU** [comment]
Now you got me thinking, wouldn't it be possible that fancybox adds the wrapper div when opened?

**Comment by fancyapps** [comment]
Well, you could use `onInit` callback to add a wrapper and `afterClose` to remove.

**Comment by W1zzardTPU** [comment]
Good idea, works now. Thanks!

**Comment by fancyapps** [comment]
Although it would be best if you would not mess with the `body` element, there is an option `hideScrollbar` that you can use to disable scrolling. Use on your own risk.

**Comment by ygoe** [comment]
As far as I can tell, it's not me messing with the body element in this case but fancybox. I'm just reverting the added margin value to make it work properly. So whatever that setting intends to fix, it breaks it instead. You may investigate this on the website: https://fitnessstudio-friends.de (there's a zoomable image at the bottom of the home page)

**Comment by fancyapps** [comment]
fancybox removes scrollbar from the `body` element (by applying `overflow:hidden` rule) and then adds right-margin to compensate for that. It works fine as you can see on homepage and any demo.

But you have forced vertical scrollbar for `html` element on your page using this CSS rule:

```CSS
html {
    overflow-y: scroll;
}
```

and by doing that you have broken the previously described logic. So, you can either leave it as it is now (with all your extra CSS rules) or simply set:

```JS
$.fancybox.defaults.hideScrollbar = false;
```

**Comment by Ajkula91** [comment]
// Hide browser vertical scrollbars; use at your own risk
    hideScrollbar: true,

Can you explain what means "use at your own risk"? What is the worst thing that can happen?
I like to put "hideScrollbar: false", without it the gallery moves a bit when zooming happens because of scrollbar disappearing at that moment.

Thank you.


@fancyapps

**Comment by fancyapps** [comment]
@Ajkula91 It seems to work fine for images, but you might see double vertical scrollbar when viewing html content.
