### ISSUE TITLE
how to inline iframe for embed videos? responsive

### ISSUE THREAD

**Issue by ellemaker** [fancyapps/fancybox#1732]
```
<a href="#con1" data-caption="..." data-fancybox>show</a>
<div id="con1" style="display:none">
<iframe src="...."></iframe>
</div>
```

**Comment by fancyapps** [comment]
Hi,

The script is not setting inline CSS properties (like width/height), therefore you can freely use CSS to control content dimensions. So, set 100% width/height for your iframe and then adjust `#con1` dimensions to your liking.
