### ISSUE TITLE
FancyBox 3: turn off video when FancyBox is closed (on Firefox and Safari)

### ISSUE THREAD

**Issue by ccbrand** [fancyapps/fancybox#1733]
Hi,

I've been having trouble turning off videos that are played in a FancyBox (on Firefox and Safari).

I have html type content in my Fancyboxes. All FancyBoxes are part of a group. I use the following code to turn off the videos when a FancyBox is closed:

jQuery(document).ready(function($) {
    // Stop video in Fancybox when modal is closed
    $('[data-fancybox="group1"]').fancybox({
    	afterClose: function() {
    		 jwplayer().stop(true);
    	}
    });
});

It works fine for the first FancyBox (https://catherinebrand.ch/design-viral/#group1-1), but not the following (https://catherinebrand.ch/design-viral/#group1-2).

Could you please tell me what's wrong with the code?
Many thanks in advance,
Catherine

**Comment by fancyapps** [comment]
Hi,

You are in the right direction, your code is almost perfect, but the problem is with this line:

 `jwplayer().stop(true);` 

as it does nothing, the player is not stopping. 

I am sorry, I am not familiar with `jwplayer`, maybe try something like this:

`jwplayer("jwppp-video-411").stop()`

**Comment by ccbrand** [comment]
Many thanks for your help!
This works perfectly :)
Best,
Catherine
