### ISSUE TITLE
Zoom first animation lag on transition end

### ISSUE THREAD

**Issue by wtorsi** [fancyapps/fancybox#1735]
The image do zoom in more than needed after start.
This happens because you are using sizes of already scaled image in transitionEnd event callback.
Defining vars 
```
width = $el.width() 
height = $el.height()
```
before definition of the event do the trick.

This code snippet I cut from dist not minified file.

```
                 if ( $.isPlainObject( to ) ) {

                    if ( to.scaleX !== undefined && to.scaleY !== undefined ) {
                        $el.css( 'transition-duration', '0ms' );

                        to.width  = Math.round( $el.width()  * to.scaleX ); //here is the problem
                        to.height = Math.round( $el.height() * to.scaleY ); //

                        to.scaleX = 1;
                        to.scaleY = 1;

                        $.fancybox.setTranslate( $el, to );
                    }

                } else if ( leaveAnimationName !== true ) {
                    $el.removeClass( to );
                }
```

Here is the example 
![image](https://user-images.githubusercontent.com/2115840/32940677-643687bc-cb94-11e7-8e8d-a091298daf39.png)

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not see an issue here. Can you provide working demo for this?

Also, are you using the latest jQuery? (jQuery v3.0x and v3.1.x have some issues)

**Comment by wtorsi** [comment]
Yes, here is  the demo 
http://airpano.spothost.ru/ru/album/venetsiia/mosaic/99

jquery v3.1.1

**Comment by fancyapps** [comment]
Please, upgrade jQuery to the latest, see https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/ and https://github.com/jquery/jquery/issues/3193

**Comment by wtorsi** [comment]
Yes, I think the same..
jQuery 3.2 solves the problem
