### ISSUE TITLE
Multiple Extension and Gallery images arrow

### ISSUE THREAD

**Issue by bhumiradixweb** [fancyapps/fancybox#1737]
Hello,

Here is the example, I have images with multiple extensions(jpg,png,gif etc) and same videos(jpg,png,gif) which are listed in a single row,

For example,

1    Test.jpg( Also in png, gif) 
2    Image2.png ( Also in jpg, gif)
3.  Test.mp4 (Also in flv, ogv)

Now, want to display arrow to show images one by one with extension and by row also. So needed two arrows?

How it is possible in fancybox?

**Comment by fancyapps** [comment]
Hi,

If you need to have 2 dimensional gallery, then, sorry, it is not possible out of the box. fancyBox was not designed for this and I never thought that someone might need such feature, you are the first person ever who is asking about something like that.

If I really should have something like this, I would create one big gallery, that would contain all items, and I would create custom click event for arrows (and would create additional arrows). And then, when clicked on arrows, I would determine index of the next item based on some condition (maybe look for next item having same/different slideClass option) and then would change gallery item using `$.fancybox.getInstance().jumpTo( index )` method.
