### ISSUE TITLE
TypeError: e.fancybox.getInstance is not a function

### ISSUE THREAD

**Issue by andywarren** [fancyapps/fancybox#1739]
I'm trying to use the latest version from Github, which appears to be 3.2.8 from the dist js code comments. I'm including this in a WordPress install. I have removed the bundled v1.xx jQuery from the WordPress install and added a newer version (v2.2.4) that is compatible with Fancybox 3. No matter what I do I get `TypeError: e.fancybox.getInstance is not a function` as a console error, and Fancybox does not function.

If I click my inline content trigger element I then get `TypeError: s is undefined` as a console error.

This is my HTML, and it is present in the source with the shortcode rendering:
```
<div style="display: none;" id="email-us-modal">
	<?php echo do_shortcode('[gravityform id="1" title="false" description="false" ajax="true"]'); ?>
</div>
```

This is my inline content trigger:
`<a data-fancybox data-src="#email-us-modal" href="#">Trigger the fancyBox</a>`

I also tried using what the examples on the Fancybox website have in the href:
`<a data-fancybox data-src="#email-us-modal" href="javascript:;">Trigger the fancyBox</a>`

**Comment by fancyapps** [comment]
Hi,

Most likely you have different versions of fancybox on the same page. It is not possible to tell excatly without seeing live page/demo.

**Comment by andywarren** [comment]
Do you have a private contact form or something that I can send you the URL on?

**Comment by fancyapps** [comment]
You can send DM - https://twitter.com/thefancyapps or chat - https://gitter.im/fancyapps/fancybox

**Comment by andywarren** [comment]
Thanks, sent via Twitter DM.

**Comment by andywarren** [comment]
Actually, it looks like you are correct. In the parent theme I see code for Fancybox 2.1.5.

**Comment by fancyapps** [comment]
Yes, just as I suspected, you can use this in the console to see the version - 

`jQuery.fancybox.version`

and it returns "2.1.5"

**Comment by aquatec9256** [comment]
How yo prevent this? If we prevent from theme so themes modules won't works and also can't from plugin
