### ISSUE TITLE
Fullscreen Flash content breaks fancyBox in Firefox, Opera and Safari

### ISSUE THREAD

**Issue by smares** [fancyapps/fancyBox#174]
If I load a video within fancyBox and toggle fullscreen, the Flash content appears fullscreen for the fraction of a second, then disappears and fancyBox shows an empty content. This problem occurs with Firefox, Opera and Safari, but not with Internet Explorer and Chrome.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
