### ISSUE TITLE
Add text under caption in popup

### ISSUE THREAD

**Issue by Anatal** [fancyapps/fancybox#1741]
How?
Only data-caption and how can I add text under the caption in popup?
Also, how can I make the popup with the old look from fancybox version 1+2.
Thanks

**Comment by fancyapps** [comment]
Hi,

If you miss the old look, here is the snippet of redesigning - https://codepen.io/fancyapps/full/GOWpJG/

I could not understand about text placement, if you mean under the image (like in previous versions), then it is not currently possible (at least, not out of the box; you could try adding using callbacks). 

But if you really mean under the caption, then ... create caption in two lines? Caption can contain any html code.
