### ISSUE TITLE
Trying to get video to load in Fancybox, performance issues with Inline. Maybe AJAX?

### ISSUE THREAD

**Issue by thedonquixotic** [fancyapps/fancybox#1742]
Hi, 

Thank you for the great lightbox application! It works great. 

I've used it to build a wordpress multimedia gallery. The support for iframe, images, etc have been super useful. 

I'm trying to get mp4s to run with fancybox and I'm having some trouble. As per this issue https://github.com/fancyapps/fancybox/issues/901 it seems that Fancybox does not support local play of video. 

Instead it is suggested to use the inline html method. 

The problem is that I have a gallery of 20 10second videos that autoplay and are on loop. Using the inline html method I have to load each of these videos for the preview AND load them a second time as the hidden element. 

I was hoping that I could perhaps use AJAX to only pull up the videos that are clicked on in the gallery but the most straightforward interpretation of that, as seen by my fork below does not work, and I'm curious what I'm missing?

https://codepen.io/thedonquixotic/pen/Kyxqor?editors=1100

**Comment by thedonquixotic** [comment]
Okay digging back into the API, I see the suggestion is actually not to use the inline HTML solution but to use the javascript open call. I'm going to try prototyping this inside of my php loop and see if it causes massive slowdown and performance issues like the inline html stuff is. 

Also, as it's reliant on javascript, and as that javascript is needs to be dynamic (since my galleries can have up to infinite number of videos added, and each one will need to have a different ID tag), I'm going to see what I can do with running the javascript inside of a script tag inside the PHP so that it can pull a variable from the database and use that to dynamically iter on each different video in the gallery

**Comment by thedonquixotic** [comment]
Okay so I got it working and performance is great so far using the manual JS open function. Which basically amounted to me copy pasting this codepen. Thanks! https://codepen.io/fancyapps/pen/xPOLVb?editors=1010

**Comment by fancyapps** [comment]
Hi,

mp4 seems to have quite good browser support these days (https://caniuse.com/#feat=mpeg4). I think I`ll add basic support. 

As alternative, you can create `<video>` elements like this - https://codepen.io/anon/pen/eeLNwQ?editors=1100 I am not sure I understand what do you mean by " I have to load each of these videos for the preview AND load them a second time as the hidden element.".

**Comment by fancyapps** [comment]
Here you go, latest commit contains HTML5 video support, see your updated demo - https://codepen.io/anon/pen/dZqqge?editors=1100

**Comment by thedonquixotic** [comment]
Excellent, sounds good.
