### ISSUE TITLE
How to prevent bubble event

### ISSUE THREAD

**Issue by alien3d** [fancyapps/fancybox#1744]
I have a  
```
    <table>
    <tr>
   <td onclick="runThis()">
   <a data-fancybox="gallery">
   <img /></a></td></table>
```

When i remove runThis method, the fancybox work nicely as intent, but when i put runThis which have redirection.fancybox appear in second  and redirect to other page.

**Comment by fancyapps** [comment]
Hi,

Actually, in your example, `runThis()` click event will be called first, before fancybox will receive click event.

You can easily check it like this:

```JS
function runThis(e) {
 
  console.info( e.target );
  
  e.stopPropagation();
  e.preventDefault();
}
``` 

This will prevent executing of fancyBox, see in action - https://codepen.io/anon/pen/BmOvKq?editors=1010

So, you actually have to check where user has clicked and then choose the action, for example:

```JS
function runThis(e) {
  
  if ( $( e.target ).is( 'img' ) ) {
    alert( 'DO NOT redirect' );
    
  } else {
    alert('GO!');
  }
  
}
```

Demo - https://codepen.io/anon/pen/zPJyaZ?editors=1010

**Comment by alien3d** [comment]
thank you for fast respond
