### ISSUE TITLE
Disappearing images

### ISSUE THREAD

**Issue by mintymatt** [fancyapps/fancybox#1746]
When an image is clicked, it disappears upon opening fancybox. Then when closing fancybox, the image is moved back to its original DOM position. Is it possible to have an option to **clone** the selected element when loaded into fancybox, so as to not effect the the source image itself?

Ultimately looking for a solution which won't cause images to visually disappear in the background.

[https://jsfiddle.net/4ht2rt4c/7/](https://jsfiddle.net/4ht2rt4c/7/)

**Comment by fancyapps** [comment]
Hi,

You code just does not follow general principle of how fancyBox works. The script expects that you select elements and those elements should contain attributes indicating content source and type.

If you can not modify the layout, then you can start fancyBox programmatically, example (using v3):

```JS
$('.post-image').on('click', function() {
  
  $.fancybox.open({
    src  : $(this).find('img').attr('src'),
    type : 'image',
    buttons : ['close']
  });
  
});
```

Demo - https://codepen.io/anon/pen/aVRvBr
