### ISSUE TITLE
Anonymizer issue

### ISSUE THREAD

**Issue by mcnesium** [fancyapps/fancybox#1747]
Sorry for opening a new issue, but I can't reopen #1113, maybe you can merge.

I did some research: the [old fancybox page](https://fancyapps.com/fancybox/#examples) runs v2.1.7 and when I edit one of the image links and add `https://nullrefer.com/?http…` to the `href` attribute in the devtools, this error message appears:
> The requested content can not be loaded. Please try again later

But on the [new fancybox page](https://fancyapps.com/fancybox/3/) this does not happen. Instead, the expected image pops up.

Why is that? Whats the difference? I checked this in both Firefox 57 and Chromium 62

Maybe you can give some advice [over here](https://github.com/SSilence/selfoss/issues/612)

**Comment by fancyapps** [comment]
Hi,

Nothing has changed, it is not working. 

Look, you can open links by changing links, for example: https://nullrefer.com/?https://developer.mozilla.org/static/img/mdn-logo-sm.png

But it just does not work for images, for example, try:

`<img src="https://nullrefer.com/?https://developer.mozilla.org/static/img/mdn-logo-sm.png" />
`

Demo - https://codepen.io/anon/pen/ooaKvx 

If you could make it somehow work for images, then fancyBox would work, too.

**Comment by mcnesium** [comment]
You're right, it still does not. This must have been either some caching thing over here, that made me think it does. Sorry about the noise.

**Comment by jtojnar** [comment]
Changing the href is not enough to break it because the new demo page also uses srcset. If you change it there it will break too.
