### ISSUE TITLE
update composer informations

### ISSUE THREAD

**Issue by MissAnna123** [fancyapps/fancybox#1748]
Hi,
theres a little probleme with composer installation : 
- on this page : the link of github is false : https://packagist.org/packages/fancyapps/fancybox#3.0.x-dev
- it's not realy a javascript package as we look on packagist, but a jquery package.

- we can not do a "composer require @fancyboxapps/fancybox"

xxxxxxx\composer>composer require @fancyapps/fancybox

  [InvalidArgumentException]
  Could not find package @fancyapps/fancybox at any version for your minimum-
  stability (stable). Check the package spelling or your minimum-stability

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest]
 [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|
--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<
packages>]...

**Comment by fancyapps** [comment]
Hi,

There is currently no official package on packagist.

Package named `fancyapps/fancybox` seems to be linked to other repository (github.com/ange187/fancyBox) and it is a fork of v2.
