### ISSUE TITLE
"Small" close button does not apper

### ISSUE THREAD

**Issue by jarred-cz** [fancyapps/fancybox#1749]
Small close button does not apper for content loaded via AJAX, when first tag is `<main>`.
With `<div>` everything is OK.

Does not work:
`<main><p>Content loaded via AJAX</p></main>`

Does work:
`<div><p>Content loaded via AJAX</p></div>`

This is not such problem, I am just curious why  `<main>` tag is problematic?

**Comment by fancyapps** [comment]
Hi,

You see, this button needs to be placed somewhere, but fancyBox does not create a wrapping element around your content (to make easier to position and do resizing). Therefore the script adds this buttons to your content. Initially, it was appended to the first element, but that caused problems for people when ajax response contained additional tags like `<meta>`, `<link>`, etc. Therefore it was decided to append only to first `<div>` element.

**Comment by jarred-cz** [comment]
thank you for explanation!
