### ISSUE TITLE
unable to disable thumbs on mobile devices

### ISSUE THREAD

**Issue by vincent3569** [fancyapps/fancybox#1750]
hi

I currently use fancybox 3.1.28.
with this release, thumbs are not displayed on mobile devices.

I try to implement fancybox 3.2.5
with this release, thumbs are displayed on mobile devices.

something changes between this 2 releases?
is there a way (by css or by option) to disable thumbs on mobile devices with fancybox 3.2.5?

**Comment by fancyapps** [comment]
Hi,

Previously, thumbs were hidden using CSS if screen width was smaller than 800px, but, taking into account the feedback, this restriction was removed. 

You can either hide them for mobile devices using mobile/thumbs option, e.g, :

```JS
mobile : {
        thumbs : false
}
```

or create your own CSS rule to hide. 

Or you could just set different buttons (using `buttons` option) for mobile devices, excluding `thumbs`.
