### ISSUE TITLE
baseClass ignored if wildcard is used to call fancybox

### ISSUE THREAD

**Issue by danny-englander** [fancyapps/fancybox#1751]
If I use a prefix wildcard to call fancybox:

```
$('[data-fancybox="^image-set"]').fancybox({
```
... my custom `baseClass` is not picked up. 

You can see an example here:
https://codepen.io/danny_englander/pen/pdqJjz

If you change:

```
$('[data-fancybox="^image-set"]').fancybox({` 
```
to 
```
$('[data-fancybox="image-set-1"]').fancybox({
```
...then the custom `baseClass` is then picked up in the rendered HTML but then of course it only works for the first image set. I am not sure if this is intended or a bug? 

My use case for using the prefix wildcard `^` is that I might have a few different sets of images on the page but I just want to call fancybox once.

**Comment by fancyapps** [comment]
Hi,

You just have to use correct selector, or default values will be used. Replace

`$('[data-fancybox="^image-set"]').fancybox(..)`

with

`$('[data-fancybox^="image-set"]').fancybox(..)`

**Comment by danny-englander** [comment]
oh yes, perfect, thanks!
