### ISSUE TITLE
Filtering fancy gallery dynamicly

### ISSUE THREAD

**Issue by rakbu** [fancyapps/fancybox#1755]
Hi sorry for my bad english i will try to did my best, i need help

im trying to the filtering image gallery with data-fancybox. And i did, its working twice but its not working third when i click to li.
there is my code:
https://gist.github.com/rakbu/cc32268fe12c11f184dba54aaf61d218

**Comment by fancyapps** [comment]
Hi,

Sorry, I don't really have time for this right now. Maybe someone would give it a try, but I doubt about that, maybe better try asking at stackoverflow. 

Here is a sample of content filtering, maybe it helps - https://codepen.io/fancyapps/pen/zPBEdz

**Comment by rakbu** [comment]
Thank you.

**Comment by lfalipou** [comment]
@fancyapps 
In a video gallery created with Fancybox, is it possible to create several filters that you can be combined?

For example:
- filter 1: duration (< 2mn, 2 to 5 mn, > 5mn)
- filter 2: topic ([topic 1], [topic 2], [topic 3]).

Also, can we sort videos whether they are filtered or not?

Thanks a lot for your answer,

--
Laurent

**Comment by fancyapps** [comment]
@lfalipou It is, of course, possible, but you have to implement that by yourself, that is out of the scope of this project.
