### ISSUE TITLE
fancybox 3

### ISSUE THREAD

**Issue by Tuseef** [fancyapps/fancybox#1757]
hi!
this is tuseef i'm using fancybox 3 

and when I'm using the second time image take an extra zoom

<a href"https://cdn.shopify.com/s/files/1/0383/9645/products/montague-capulet-bag.jpg?v=1477399502" class="facnybox big-img">  
<img src="https://cdn.shopify.com/s/files/1/0383/9645/products/montague-capulet-bag.jpg?v=1477399502"alt="1st image description"/>
</a>

<script>
 $('.big-img').fancybox({

});

	
</script>

![image](https://user-images.githubusercontent.com/34184153/33514467-3d4bb62a-d776-11e7-86e3-f26232ac1050.png)

**Comment by fancyapps** [comment]
Hi,

The comment is quite unclear, but I suspect that you are using jQuery 3.0.x or 3.1.x.
So, please, upgrade to the latest.

**Comment by Tuseef** [comment]
thanku its clear
