### ISSUE TITLE
Disable mouse scroll if there is only one image

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1758]
Is possible to disable mouse scroll if there is only one image in gallery? Thank you for your feedback

**Comment by fancyapps** [comment]
Hi,

Sorry, silly mistake, next commit will contain a fix. 

Thanks for reporting!

**Comment by Eldenroot** [comment]
@fancyapps - great, thank you!

**Comment by Eldenroot** [comment]
I havent tested your latest version, so did you add this please?

**Comment by fancyapps** [comment]
I think it was fixed a long time ago :) btw, you can fork any codepen demo to make quick test.
