### ISSUE TITLE
Fancybox, showing wrong number of pictures,

### ISSUE THREAD

**Issue by Karim988** [fancyapps/fancybox#1759]
1st picture,
![1](https://user-images.githubusercontent.com/21034533/33515953-c3071c36-d772-11e7-89ed-29f40eab70ac.PNG)

2nd picture,
![12](https://user-images.githubusercontent.com/21034533/33515955-cb333354-d772-11e7-94f9-a0a5b4fc7cd5.PNG)
why it shows 11 pictures, while it supposed to show only three pictures according to the code?

**Comment by fancyapps** [comment]
Hi,

The common problem with sliders is that they clone items and therefore you have to adjust selector to exclude clones, for example:

```JS
$().fancybox({
  selector : '.owl-item:not(.cloned) > a',
  hash   : false
});
```

Demo - https://codepen.io/fancyapps/pen/mqvOoz?editors=1010

You might need to upgrade to the latest version.

**Comment by Karim988** [comment]
Hello @fancyapps, thanks for your fast response, 

When I used this jQuery code, it hides all the items.

**Comment by fancyapps** [comment]
Did you adjust selector to match your html structure?

**Comment by Karim988** [comment]
Sorry, but how to did that?

**Comment by fancyapps** [comment]
:D maybe try changing `selector` to `'.owl-item:not(.cloned) a',`

btw, do you really need two nesting elements? You could just add `data-fancybox` and `data-src` attributes to your `<div class="holder">` elements (in that case, selector would be `'.owl-item:not(.cloned) .doler',`). 

Anyway, I am using owlcarousel v2 here, I do not know what version you are using, maybe different versions use different class names. But this is how you can use it with any slider, for example, Slick - https://codepen.io/fancyapps/pen/pdbrjx
