### ISSUE TITLE
Error box is opened within gallery

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1760]
Hi,

I am not sure if it is wanted or not... when you open an image and the "error box" is shown, it is opened within the gallery (you can see caption, buttons, etc.).

In past (I believe it was fine in the first version of v3.2) the popup error box was opened, and the rest was hidden. 

I am sorry for my English, quite difficult to describe this "bug"? I am enclosing a screenshot below.

![image](https://user-images.githubusercontent.com/778890/33515999-3df0376e-d76b-11e7-9e98-795da8d8efc5.png)

**Comment by fancyapps** [comment]
This is how v3 works from the beginning and I do not see any issue here. You can swipe to next/prev image and you can see description so you have at least some hint of what that image should be.
