### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by TiCaillou** [fancyapps/fancybox#1764]
Hi, I want to open a fancybox iframe with https://www.openstreetmap.org/ but don't work ! I prefered osm instead of google maps. It's possible ? Thank you.
I modified media.js to adding a matcher but dont't work.
`osm:`
`matcher: /openstreetmap\.org\/(.*)?/i,`
`type: 'iframe',`
`url: '//www.openstreetmap.org/$1'`

**Comment by fancyapps** [comment]
Hi, 

It is not possible to embed OpenStreetMap directly into the page, but you could use http://leafletjs.com/ and display it instead, see this demo - https://codepen.io/anon/pen/qVvPjN

Another solution would be like this:

1) Open the map you wish to embed, for example: https://www.openstreetmap.org/#map=14/40.7139/-74.0071
2) Click "Share" button on the right, then choose "HTML" tab.
3) Here you will find HTML code containing iframe tag - copy "src" value and use it as "href" or "data-src" value for your link, see demo - https://codepen.io/anon/pen/gXEGLX

**Comment by TiCaillou** [comment]
don't work with Firefox 57.0.1 (64 bits) but with Chrome it's OK.

**Comment by TiCaillou** [comment]
OK I found ! The plugin Adguard Blocker filtered the site openstreetmap. I configured this plugin and now i have a complete menu.
