### ISSUE TITLE
Error trying to use TabContainer in ASP.NET and Ajax content call

### ISSUE THREAD

**Issue by mrwrighty** [fancyapps/fancybox#1765]
HI

I'm having issues implementing a TabContainer in an Ajax src Fancybox 3. I'm thinking their is a conflict between AjaxToolKit and the Ajax used to display the content.

There error is JavaScript runtime error: Sys.InvalidOperationException: Component 'TabContainer1' was not found.

Is they a way around this issue.

Many Thanks.

**Comment by fancyapps** [comment]
Hi,

Sorry, but that error message does not seem to be related to fancybox.

**Comment by mrwrighty** [comment]
But if I load the page in the conventional manner it displays correctly, as soon as I call it as an Ajax src file into a fancybox the error occurs. I'm calling from a menu defined in the MasterPage:-

<a compensate-for-scrollbar data-fancybox data-type="ajax"  data-src="usermanager.aspx" href="javascript:;">Manage Users</a>

usermanager.aspx contains the TabContainer

**Comment by fancyapps** [comment]
I`m not familiar with .net and I can only guess that you might need to use callbacks (`afterLoad` or maybe `afterShow`) to initialize something.

**Comment by mrwrighty** [comment]
The only way I could find to fix this issue was to set data-type to iFrame rather than ajax. This works as intended, so assuming there is a clash between ajax and the asp.net ajax ToolkitScriptManager.
