### ISSUE TITLE
CSS class for share popup links

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1766]
Hi @fancyapps - there is same issue with css class in share popup window. Links need to use own (stronger) css for color. They should be white, but there are blue.

![image](https://user-images.githubusercontent.com/778890/33566620-d91407fa-d920-11e7-984a-793296d471d0.png)

Related to:
https://github.com/fancyapps/fancybox/issues/1727

EDIT: Is possible to select the whole url when you click on it (url below the share buttons)?

**Comment by fancyapps** [comment]
I wish you would just remove your `a:link` css rule :) But OK, I`ll take a look.

**Comment by Eldenroot** [comment]
Thank you. It was fine before share feature rework IIRC.
