### ISSUE TITLE
How to init several images groups from javascript? (fancybox 3)

### ISSUE THREAD

**Issue by Worka** [fancyapps/fancybox#1775]
Hi! How to init several images groups from javascript?

Variant _data-fancybox = "number1"_ does not suit me, it is necessary to start from javascript.

```
<div>
    <a href="url" data-group="number1" class="fancybox"><img src="preview" /></a>
    <a href="url" data-group="number1" class="fancybox"><img src="preview" /></a>
</div>
<div>
    <a href="url" data-group="number2" class="fancybox"><img src="preview" /></a>
    <a href="url" data-group="number2" class="fancybox"><img src="preview" /></a>
</div>
...
...
...
```

And, how do I initialize another group, which will be added with ajax-request?

Thanks in advance for the answer.

**Comment by fancyapps** [comment]
Hi,

You can add `data-fancybox` attribute to your links, and then use any selector to set custom options, for example, `$('.fancybox').fancybox();`

Demo - https://codepen.io/anon/pen/ZvYENq?editors=1010

**Comment by Worka** [comment]
Thank you very much, but I found the answer myself, after I asked the question :))))

I needed something else that worked with dynamic loading of images. I found the answer in previous issues :)

```
$(document).on('click', 'a.fancybox', function () {
            var collection = $('a.fancybox');

            $.fancybox.open(collection.data('type', 'image'), {
                clickOutside: 'close',
                clickSlide: 'close',
                touch: true,
                buttons: [
                    'close'
                ],
                loop: true
            }, collection.index(this));

            return false;
        });
```

**Comment by fancyapps** [comment]
Or you could simply initialize like this:

```JS
$().fancybox({
  selector : '.fancybox',
  thumbs : {
    autoStart : true
  },
  buttons : [
    'zoom',
    'close'
  ]
});
```

Demo - https://codepen.io/anon/pen/KZwwVB?editors=1010

**Comment by Worka** [comment]
Ou, great. Thank you very much.

**Comment by Worka** [comment]
Sorry, why "$().fancybox()", rather than "$(document).fancybox()" or "$('body').fancybox()"

**Comment by fancyapps** [comment]
You see, jQuery deprecated and recently removed this handy feature - https://api.jquery.com/selector/ - that allowed to get selector passed to jQuery(). Previously, it was possible to create delegated event handlers automatically (like v2 used to do). 

So, there were two possible workaround to this issue -  create new option like `delegate : 'a'` (similarly to other scripts) or use this funny syntax where you pass selector by yourself (since the script can not read it automatically; and in this case, it does not matter what you pass inside $(), because it will be ignored).

**Comment by Worka** [comment]
Thank you

**Comment by Worka** [comment]
Can I ask one more question. It is related to another task.

I load new fancybox from a link inside an already open fancybox. 

I do this:

```
$(document).on('click', 'a.fancybox-ajax', function () {
    $.fancybox.close();
    $.fancybox.open({
        src: $(this).data('src'),
        type: 'ajax'
    });
});
```

Is there a better option?

Thank you!

**Comment by fancyapps** [comment]
If you want to prevent opening on top of the currently open modal, then, sorry, this is currently the only option. This eliminates potential mess that could occur if the script would automatically try to close previously open modal, but something would prevent (for example, beforeClose callback could prevent closing).

**Comment by Worka** [comment]
I understand. Thank you! 👍
