### ISSUE TITLE
Allow Single Quotes for Items in data-option

### ISSUE THREAD

**Issue by FastieSystems** [fancyapps/fancybox#1778]
I realize that the typical value for the data-option attribute is a JSON string. JSON defines only double quotes for strings.

While the HTML spec allows the values for attributes to be enclosed in either double or single quotes, my infrastructure injects only double quotes. Thus my system will generate this:

`data-option="{ "loop" : true }"`

and that results in an HTML error. I could change my system to use single quotes for attributes but unfortunately code that uses my infrastructure knows that double quotes will be used and acts accordingly.

Therefore, I would like fancyBox to accept a modified JSON in which strings may be delimited with single quotes:

`data-option="{ 'loop' : true }"`

**Comment by fancyapps** [comment]
Hi,

I feel your pain, but this is a standard JSON syntax - http://json.org/ 

fancyBox is not parsing these attributes manually, but is using jQuery's .data() method https://api.jquery.com/data/ and this method follows the standard. And browsers have implemented this too, for example, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

As alternative, try setting `data-loop="true"` - this works for options that have non-object values (e.g., you would still need to use json for `iframe` option)

**Comment by FastieSystems** [comment]
Thanks. It's the answer I expected; I didn't really think fancyBox was parsing.

May I suggest that you add a note on https://fancyapps.com/fancybox/3/docs/#options at "Custom options for each element individually..." to make that clear? From reading the site, I thought all options had to be contained in data-options.
