### ISSUE TITLE
slideshow speed

### ISSUE THREAD

**Issue by dj4n90** [fancyapps/fancybox#1780]
fancyBox v3.2.10

line 279 changed speed from 4000 to 1000 but no difference.

`
           slideShow : {
           autoStart : false,
           speed     : 1000 //speed     : 4000
           },
`

line 4265 changed speed from 4000 to 1000 and it works
line 4265 overrules line 279,

`
           slideShow : {
           autoStart : false,
            speed     : 1000 //speed     : 3000
           }
`

**Comment by fancyapps** [comment]
Hi,

Sorry, but I do not understand your comment. Are you trying to modify default values by editing JS file? You should not do that. You can, for example, change defaults like this:

`$.fancybox.defaults.slideShow.speed = 500;`

Then you can easily upgrade your js file without the need to find and edit it manually each time.
