### ISSUE TITLE
IOS pop-up trouble

### ISSUE THREAD

**Issue by yop-ti** [fancyapps/fancybox#1781]
hello.
please see attached video.
the pop-up is not on the center of the screen/
ios 6.1.6; 7; 8.4.1; 10.3.3 (on video) tested
fancybox 3 latest

https://yadi.sk/i/OaDnhF_y3QmxZE

**Comment by fancyapps** [comment]
Hi,

Most likely your content is more than 100% wide and it probably has margins, therefore it is pushed down. 

fancyBox uses inline-block technique for vertical centering (https://www.smashingmagazine.com/2013/08/absolute-horizontal-vertical-centering-css/#Inline-Block) and while it is the best one for "centering in the unknown", it is not perfect.  In fact, I recently spend few days to find the best possible solution, and after countless tests I did not find a better solution.
