### ISSUE TITLE
Adding additional data elements into baseTpl

### ISSUE THREAD

**Issue by danny-englander** [fancyapps/fancybox#1783]
I am attempting to add an additional data element to show up in the Lightbox by adding my own `baseTpl` code in which I try to pull in a data element called `data-attribution`. 

```
'<div class="fancybox-attribution">' + $(this).data("attribution") + '</div>' +
```
... but when I inspect the code, it just shows up as `undefined`

see: https://codepen.io/danny_englander/pen/NXrvXq

... so I am not sure what I am doing wrong. Thanks.

**Comment by fancyapps** [comment]
Hi,

Value for `baseTpl` key is just a string, you can not use `$(this)` here. Why did you assume it would work, are you using similar syntax for other jQuery plugins or you just hoped it would work? :)

So, you just need to create some element and update it's contents using callbacks:

```JS
beforeShow: function(instance, current) {
    instance.$refs.container.find('.fancybox-attribution').html( current.opts.$orig.attr('data-attribution') )
}
```

Demo - https://codepen.io/anon/pen/vpKWmZ

**Comment by danny-englander** [comment]
Ahh, I see! yeah I was just hoping it work within `baseTpl` as I was struggling how to get the attribution in the right spot where the markup is but you've solved it with `beforeShow`. Thanks so much!
