### ISSUE TITLE
No iframe on Apple tablet devices.

### ISSUE THREAD

**Issue by infatum1** [fancyapps/fancybox#1786]
Just checked [the site](http://chemistry.thats.im/) on Apple iPad Air and no iframe appears on it. Just a blank screen in both Chrome and default Safari browser. Any ideas? 

Android devices work fine.

**Comment by fancyapps** [comment]
Any ideas why <iframe src="http://chemistry.thats.im/" /> gives a blank page?

**Comment by infatum1** [comment]
I have and svg file used as an image in <img>. The image itself has map areas, whereas every map area element corresponds to a specific webpage supposedly to be opened via an iframe with the help of fancybox. 

`<img src="experimantal/Table.svg" width="1550" height="auto" usemap="#Map" border="0" /><br /><hr />
  </a>
  <map name="Map" id="Map">
<area shape="rect" coords="457,669,539,751" data-fancybox data-type="iframe" href="elements/Pr.php"/>`
