### ISSUE TITLE
Long iframe problems - positioning offscreen

### ISSUE THREAD

**Issue by wjens** [fancyapps/fancybox#1787]
I have basically the same problem as
https://github.com/fancyapps/fancybox/issues/679

Since that issue is from 2013, I was hoping there was a better approach to the problem under the latest version. I don't know if CORS is a potential solution but I imagined a scenario where fancybox within the iframe attempts to load fancybox within it's parent (if present) and thus allowed the parent fancybox to work in the context of the visible browser window instead of the entire iframe.

If that's not possible, what could be done to have the image display closer to the element responsible for showing the fancybox? This way at least my image could load where it's visible instead of potentially loading offscreen.

**Comment by Patta** [comment]
+1

**Comment by Patta** [comment]
@wjens I currently had the same issue. I adjusted the fancybox position with css and js to the offset.top of the clicked link/element in the iframe.

css/sass (iframe):
```
// remove fancybox-slide:before height
.fancybox-slide:before
  height: 0

// optional: adjust other styles to fit in parent UI
- remove background color of .fancybox-is-open .fancybox-bg
- darken border-color of .fancybox-slide>.fancybox-loading
- add box-shadow to .fancybox-content and .fancybox-image-wrap
```

js (iframe page footer):
```
$(function(){			
  $('a[data-fancybox],a[rel^="fancybox"]').on('click', function(){
    var linkOffset = $(this).offset();

    // adjust fancybox-loader position
    // add top position to fanbcybox-loader with value from clicked link offset.top
    var instance = $.fancybox.getInstance();
    instance.showLoading();
    $('.fancybox-loading').css('top', linkOffset.top);

    // adjust fancybox-content position
    // add top position to fanbcybox-content with value from clicked link offset.top and subtrated with half fancybox height
    $(document).on('afterLoad.fb', function(){
      var fancyboxContent = $('.fancybox-content');
      var fancyboxContentHeight = parseInt($('.fancybox-content').css('height'));
      fancyboxContent.css('top', linkOffset.top - (fancyboxContentHeight / 2));
    });
  });
});
```

https://fancyapps.com/fancybox/3/docs/#api

**Comment by fancyapps** [comment]
Well, I do not know what else to add... Maybe try adjusting position of `fancybox-container` element to suit your needs.
