### ISSUE TITLE
The name (title) for the opened iframe

### ISSUE THREAD

**Issue by ghekakilla** [fancyapps/fancybox#1788]
Hello, I'm using fancybox 3, but I ran into the problem, I can not either understand how to display the name in the opened iframe. Nowhere about this information have not found
.
I do so.

`<a data-fancybox data-type="iframe" title="name iframe" data-src="depositphotos_25226481-Video-audio-and-multimedia-buttons-set.jpg" href="javascript:;">
    External page
  </a>`

`
$("[data-fancybox]").fancybox({
	toolbar  : false,
  	smallBtn : true,
	autoSize: true,
	helpers	: {
			title	: {
				show_title: true,
				type : "inside"
			},
			buttons	: {}
		},	
	iframe : {
		css : {
		}
		
	},
});

`

What am I not so prescribed?

**Comment by fancyapps** [comment]
Hi,

You can set any attribute for iframe element using iframe.attr option, e.g.:

```
iframe : { 
    attr : {
        title : 'myTitle'
    } 
}

```

**Comment by ghekakilla** [comment]
Does not work, here's an example link. [пример]codepen.io/gheka/pen/ypgGeG(url)

**Comment by fancyapps** [comment]
Please, do not make duplicates, I already answered on SO that your example works. Most likely I do not understand what do you mean by "how to display the name in the opened iframe" - what name, where? Sorry, I do not have magical power to read your mind.
