### ISSUE TITLE
<iframe> not working on Apple tablets

### ISSUE THREAD

**Issue by infatum1** [fancyapps/fancybox#1789]
I have and svg file used as an image [on a site](http://chemistry.thats.im) . The image itself has map areas, whereas every map area element corresponds to a specific webpage supposedly to be opened via an iframe with the help of fancybox.

Code:
`<img src="experimantal/Table.svg" width="1550" height="auto" usemap="#Map" border="0" /><br /><hr /> </a> <map name="Map" id="Map"> <area shape="rect" coords="457,669,539,751" data-fancybox data-type="iframe" href="elements/Pr.php"/>`

*edit. Interestingly enough, the older version of fancybox 2.1.5 works well on Apple tablets. For example, [this page](http://chemistry.thats.im/index_eng_art_comic.php) has `class="fancybox"` for images.

*edit. On Apple tablet the screen just shows the background image, but the page looks cut off from the top. On Android devices everything shows fine. Can you please look into it?

**Comment by fancyapps** [comment]
Why do you have these CSS rules, they are breaking "ios hack":

```
body {
    position: relative;
    z-index: auto;
    left: auto;
    top: auto;
    right: auto;
    bottom: auto;
    clip: rect(auto,auto,auto,auto);
}
```

**Comment by infatum1** [comment]
This was used to auto position the content, i.e. centering. Since I have another centering option, I can remove it, which I did.

Now, with that removed, the page [in the background zooms in when I click an element.](https://photos.app.goo.gl/J1KRN7WCAZKpEQXf2) After closing the iframe page the user has to zoom back out to get the full view. A minor nuisance, but nonetheless.
