### ISSUE TITLE
fancybox-content too big with image from google storage

### ISSUE THREAD

**Issue by wachalala** [fancyapps/fancybox#1790]
Hello,

Thank you for the work you've done !
I just have a little issue with image from google storage.
My Fancybox is really too big when the image is from google storage.

Here is an exemple :
![image](https://user-images.githubusercontent.com/34910892/34406635-7809f9d6-ebba-11e7-9271-c9df0a47734e.png)

Any tips for the issue ?

Thank you :)

**Comment by wachalala** [comment]
Just found the solution.
For the people who'll need it :

Your google image is like that :
http://lh3.googleusercontent.com/9_cV91XXXXXXXXXX

Just add that at the end of the href link : ?.jpg
http://lh3.googleusercontent.com/9_cV91XXXXXXXXXX?.jpg

So fancybox can determine the height / width of the image :)

**Comment by kloneets** [comment]
Or you could add `data-type="image"`, so fancybox would know it is image.

**Comment by fancyapps** [comment]
Or you could upgrade to latest version where default content type is "image".
