### ISSUE TITLE
.fancybox-close-small:after Grunt Invalid US-ASCII character "\xC3"

### ISSUE THREAD

**Issue by geoffthibeau** [fancyapps/fancybox#1792]
```
.fancybox-close-small:after {
  content: '×';
```

The existing CSS code throws an error in my Grunt's compass task. I change the extension of your CSS file to SCSS to concatenate into a project stylesheet.

Simply updating the `content` to the unicode number equivalent allows the task to complete properly.

```
.fancybox-close-small:after {
  content: '\00D7'; /* Unicode value for multiplication sign */
```

Using package.json `devDependencies`:
```
"grunt": "~0.4.5",
"grunt-contrib-compass": "~1.0.3",
```

**Comment by fancyapps** [comment]
Hi,

Do not worry, starting from the next release, this small close button will be created using SVG, you can preview it here - https://codepen.io/fancyapps/full/VyLOJX/ (see "Data attributes" example).
