### ISSUE TITLE
Fancybox3 disable caption

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1794]
Hi.
Is there any way to disable caption? I know that in previous version you could disable (i think) helpers { title: false}.

Tnx.

**Comment by fancyapps** [comment]
Hi,

I wonder why would you want to do that, but you could, for example, use `caption` method that returns empty string, e.g.,  `caption: function() { return ''; }`

Demo - https://codepen.io/anon/pen/mppjQB?editors=1010

**Comment by xApep** [comment]
Thanks!
