### ISSUE TITLE
Mixed Group

### ISSUE THREAD

**Issue by steveindzine** [fancyapps/fancybox#1796]
Hi there,
I have a gallery with images and videos, and can successfully group the images to each other, and the video to each other. I have been using this code to make the video respect the aspect ratio: https://codepen.io/fancyapps/pen/dNzaQq

The trouble is I now want to have all the images and videos grouped together, but keep the videos using the aspec ratio code. If I use the aspect ratio code on the images they get messed up.

How can I adapt the aspect ratio code to ignore images?

Cheers,

Steve

**Comment by fancyapps** [comment]
Hi,

I think it would be easier to wait a bit for the next version (preview - https://codepen.io/fancyapps/full/gopGNq/) where aspect ratio for videos will be built-in.

**Comment by steveindzine** [comment]
That looks good to me. Is there an ETA on the next version?

**Comment by fancyapps** [comment]
I don't have an exact ETA, sorry!

**Comment by steveindzine** [comment]
I guess I will have to be patient :)
