### ISSUE TITLE
Zoom efect doesn't work

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1798]
Hi.
Is it possible that on latest version zoom effect isn't working on images/gallery?

>     if ( $.isFunction($.fn.fancybox) ) {
>         $('.fancybox_gallery').fancybox({
>             thumbs : {
>                 autoStart : true
>             },
>             buttons : [
>                 'zoom',
>                 'close'
>             ],
>             animationEffect     : 'zoom'
>         });
>     }

> a class="fancybox_gallery" data-fancybox="gallery" href="test.jpg"

**Comment by fancyapps** [comment]
Hi,

Make sure you are not using jQuery v3.0.x or v3.1.x (other versions work fine).

**Comment by cvaize** [comment]
The zoom effect doesn't work if there is another element on top of the element, how to fix it?
![image](https://user-images.githubusercontent.com/26907947/59594316-0ec67400-910d-11e9-87e7-d34946e2ef7f.png)
![image](https://user-images.githubusercontent.com/26907947/59594440-459c8a00-910d-11e9-8d4f-b6f2290dddb5.png)

**Comment by fancyapps** [comment]
@cvaize See #2281

**Comment by cvaize** [comment]
Does not work even if you remove `<div class="product__thumb__lupe"></div>` from the tag `<a></a>`.
![image](https://user-images.githubusercontent.com/26907947/59594703-c5c2ef80-910d-11e9-8ba6-371a6c8fb81b.png)
![image](https://user-images.githubusercontent.com/26907947/59594727-d5423880-910d-11e9-9b62-cf5c7323caa7.png)

**Comment by cvaize** [comment]
@fancyapps Thank you! I think it should be specified in the documentation marked "Warning!!!!"
