### ISSUE TITLE
One image with loop option on

### ISSUE THREAD

**Issue by syshut** [fancyapps/fancybox#1800]
Hi,
when loop option is set to ture, and there is one image in the web page, I scroll my mouse down or up, the only image will loop infinitely.

When there is only one image, the navigation arrows disappear, and I cannot drag the image left or right to view the next image, but the mouse wheel can make the image scroll, it seems a little bit wirld.

How about disable loop when there is only one image?

**Comment by fancyapps** [comment]
Hi, I can not reproduce this, so this probably has been fixed in some previous commit.
