### ISSUE TITLE
Delegate selector

### ISSUE THREAD

**Issue by darkoromanov** [fancyapps/fancybox#1802]
It would be great if we could have the a delegate selector, exactly how it works for MagnificPopup (http://dimsemenov.com/plugins/magnific-popup/documentation.html#options search for "delegate" in page).

This way we could dynamically group images, like in this demo https://www.final-tiles-gallery.com/gallery-with-filters

**Comment by darkoromanov** [comment]
Ehi, just tried now, it's already dynamic :)

**Comment by fancyapps** [comment]
Hi,

fancyBox uses simpler approach using `selector` option where you can put anything, for example:

```JS
$().fancybox({
  selector : '.something:visible > a',
});
```

**Comment by darkoromanov** [comment]
cool, however I'm not using the "selector" option and it works the same way. This is well designed piece of software, I'm going to purchase a license.
