### ISSUE TITLE
Do not open some IMG in Fancybox - is possible?

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1803]
Hi,
is possible to ignore specified images from opening in FancyBox? Thank you!

**Comment by Eldenroot** [comment]
Right now I use this:
`<script type="text/javascript">
$(document).ready(function() {

	$('.post_body img').each(function() {
		var currentImage = $(this);
		if (currentImage.hasClass('smilie') == false && currentImage.parent().is('a') == false) {
			currentImage.wrap("<a target='_blank' data-fancybox data-type='image' href='" + currentImage.attr("src") + "'</a>");
		}
  });
	$.fancybox.defaults.lang = 'cs';
	$.fancybox.defaults.i18n.cs = {
		CLOSE : 'Zavřít',
		NEXT : 'Další',
		PREV : 'Předchozí',
		ERROR : '<center><b>Zobrazovat a stahovat přílohy mohou pouze zaregistrovaní uživatelé, prosím přihlašte se!</b><br /><h6>V případě, že problém přetrvává, tak je požadovaný obsah pravděpodobně nedostupný. Prosím, zkuste to později.</h6><b><a href="member.php?action=login">>>> PŘIHLÁSIT/ZAREGISTROVAT SE <<<</a></b></center>',
		PLAY_START : 'Spustit prezentaci',
		PLAY_STOP : 'Pozastavit prezentaci',
		FULL_SCREEN : 'Celá obrazovka',
		THUMBS : 'Náhledy',
		DOWNLOAD : 'Stáhnout',
		SHARE : 'Sdílet',
		ZOOM : 'Přiblížit'
};
	$('[data-fancybox]').fancybox({
		loop : true,
		
		thumbs : {
	    autoStart   : false,
	    hideOnClose : true
	  },
		
		buttons : [
			'slideShow',
			'fullScreen',
			'thumbs',
			'share',
			'zoom',
			'download',
			'close'
  ]
	});
});
</script>`

Is possible to extend this for specific id=""? I am a newbie, thank you!

**Comment by fancyapps** [comment]
Hi,

It would be simpler to not apply fancyBox to some elements, e.g.:

```
$().fancybox({
  selector : '.something:not(.special) > a',
});
```
