### ISSUE TITLE
afterLoad & current (fancyBox v3.0.47)

### ISSUE THREAD

**Issue by Webtransformer** [fancyapps/fancybox#1805]
Hi,
I am having troubles to append a custom caption to the "fancybox-placeholder" div.
Sadly I am forced to use v3.0.47 (I can´t update).
In the afterLoad event 3 objects are loading. I dont know how to check against the current one.
Everytime its adding my caption 3 times.
I rendered instance, slide, current in the console but could find a match to compare them.
Can you please give me a hint?
`			afterLoad: function (instance, slide, current) {
				console.log("instance", instance);
				console.log("slide", slide);
				console.log("current", current);
				if (??? === ???) {
				}
			}`

**Comment by fancyapps** [comment]
Hi,

Check instance variables (e.g. `$.fancybox.getInstance()` or first parameter ofcallback), you can find lot of useful stuff here, for example, `currIndex`.

So, you can check if that slide is the "current one" using `if ( slide.index === instance.currIndex ) { .. }`

**Comment by Webtransformer** [comment]
Thanks!
