### ISSUE TITLE
triggerFromUrl() clicks elements not associated with fancyBox

### ISSUE THREAD

**Issue by Stadly** [fancyapps/fancybox#1806]
`triggerFromUrl()` is run on page load and whenever the fragment part (`#`) of the url changes. This function attempts to open the fancyBox element matching the fragment value. First, it tries to find an element with a matching `data-fancybox` attribute. If this does not succeed, it chooses the element having an `id` matching the fragment value of the url. Then a `click` event is triggered on this element to open it.

This is a great idea, but when the element is selected based on the `id`, the `click` event might be triggered on elements not associated with fancyBox, resulting in unexpected and undesired behavior.

### HTML
```
<details>
  <summary id="more">Read more</summary>
  <p>Here are lots of details</p>
</details>
```

### JavaScript
    $(document.location.hash).parents("details").addBack("details").attr("open", true);

A webpage uses javascript to open `details` elements on page load, if they contain the element matching the url fragment. If fancyBox is added to this page, and the page is loaded with the fragment `#more`, the `details` element will first be opened by the code above, but then fancyBox will trigger a `click` event on the `<summary>` element, causing it to be closed again.

I like the feature that fancyBox can open fancyBox elements based on the fragment part of the url, but I don't think fancyBox should trigger `click` events on elements not associated with fancyBox, such as in the example above.

**Comment by Stadly** [comment]
This issue could even impose a security threat, kind of similar to Cross-Site Request Forgery.

```
<form>
  <input id="submit" type="submit" value="Confirm">
</form>
```

If someone sent a link with the `#submit` url fragment, the form would be submitted on page load.

I think that it would be better if `triggerFromUrl()` opened the fancyBox element without triggering a `click` event.

**Comment by fancyapps** [comment]
Thanks for the feedback. If anyone has a better idea how to implement hash change, then, please, do not hesitate and share.

**Comment by Stadly** [comment]
Could you post links to the other discussions, please? I might have some ideas, but it would be nice to see what's already been talked about.

**Comment by fancyapps** [comment]
Well, you can post here, these GitHub "issues" are like a (messy) chat anyway.

**Comment by Stadly** [comment]
I have gone through all the GitHub issues that seemed relevant, but haven't found anything concerning this discussion, so I suppose the other places where this issue has been discussed is not on GitHub. Still, if it's online, please feel free to add the links here.

I suggest that we keep this issue open for several reasons:

1. Avoid duplicates when people don't find the issue since it is closed.
2. Maybe someone looking through the open issues some day might have a great idea and want to contribute.
3. It actully is an open issue ;)

What about adding a label "Help needed" or something?

**Comment by fancyapps** [comment]
I like your enthusiasm, but it's rarely found :) 

And, about this issue - if you wonder why the script is triggering click event, the reason is quite simple - to enable hash navigation when calling fancyBox programmatically. For example, you can create an element like this:

```HTML
<a id="myhash" href="javascript:;">Click me</a>
```
and then attach click event:

```JS
<script>
    $("#myhash").on('click', function() {

        $.fancybox.open([
            {
                src  : '1.jpg',
                opts : {
                    caption : 'First caption'
                }
            },
            {
                src  : '2.jpg',
                opts : {
                    caption : 'Second caption'
                }
            }
            ], {
                loop : false,
                hash : "myhash"
        });
    });
</script>
```
So, the only solution I could think of is to make this feature optional. The harder part would probably be to figure out the name for such option :)

**Comment by Stadly** [comment]
Thanks, that's clarifying. Sorry for the delayed answer. Had to think a bit ;)

When calling fancyBox programmatically, it wouldn't be much extra work to bind the opening of the fancyBox to a `hashchange`. This will remove the need for triggering a `click` event.

```html
<a id="open-myhash" href="javascript:;">Click me</a>
<script>
    var myhashFancybox = function() {
        $.fancybox.open([
            {
                src  : '1.jpg',
                opts : {
                    caption : 'First caption'
                }
            },
            {
                src  : '2.jpg',
                opts : {
                    caption : 'Second caption'
                }
            }
            ], {
                loop : false,
                hash : 'myhash'
        });
    };

    $("#open-myhash").on('click', myhashFancybox);
    $.fancybox.bindHash('myhash', myhashFancybox);
</script>
```

And then, in the fancyBox core,  we have something like

```javascript
$.fancybox.boundHashes = {};

$.fancybox.bindHash = function ( hash, callback ) {
    $.fancybox.boundHashes [ hash ] = callback;
}

$(window).on('hashchange', function() {
    if ( $.fancybox.boundHashes [ document.location.hash ] !== undefined ) {
        $.fancybox.boundHashes [ document.location.hash ]();
    }
});
```

When calling fancyBox non-programmatically, I think it should be quite easy to make everything work without binding hashes or triggering clicks, so I won't go into details on that now. What do you think?

**Comment by Stadly** [comment]
Friendly ping :)

**Comment by fancyapps** [comment]
Thanks for your comment. I am now thinking that it would be best to just drop that feature. While this seemed to be cool feature at first, I am not sure that significant number of users are using that. Also, it is actually quite trivial for user to start fancyBox manually on hash change.

**Comment by fancyapps** [comment]
btw, I just now realized that it could be solved simply  by triggering `click.fb-start` eventn instead of `click`. I wonder how I did not notice that before :astonished:

**Comment by Stadly** [comment]
Haha! Awesome if it's that simple :D
