### ISSUE TITLE
when clicking every image single image is showing

### ISSUE THREAD

**Issue by krishnapreejith** [fancyapps/fancybox#1807]
When I connect to the database to display images from the database when clicking every image only the first image is displaying. Please review my code and help me

						
									
				<?php
							$qry="select * from colors where prod_name='$prodname'";
							$ex=mysqli_query($con,$qry);
							if(mysqli_num_rows($ex)>0)
							{
								while($row=mysqli_fetch_assoc($ex))
								{
									echo "<li><a data-fancybox='group' href='#prod_popup'><span class='imgwrap'><img src='admin/".$row['clrimg']."' style='height:100px;width:100px;'><span><span class='title'>".$row['clr_name']."</span></a></li>";
									?>
				
				 
				<div id="prod_popup" class="popupWrapper">
				<?php
				$clr=$row['clr_name'];
					$query= "select products.prod_name,products.type,products.sur_finish,products.size,colors.clr_name,colors.clrimg from products inner join colors on products.prod_name = colors.prod_name and colors.clr_name='$clr'";
					$exe=mysqli_query($con,$query);
					if(mysqli_num_rows($exe)>0)
							{
								while($rw=mysqli_fetch_assoc($exe))
								{
									echo "<div class='popupHeader'><h2>".$rw['prod_name']."</h2>
									<h3>".$rw['clr_name']."</h3>
									</div>
									<div class='row popupDetails'>
										<div class='col-sm-4'>
											<img src='images/about.png'>
										</div>
										<div class='col-sm-8'>
										<hr>
											<div class='fieldWrap'>
												<div class='labelWrap'>Type</div>
												<div class='labelDetails'>
													Glazed Porcelain
												</div>
											</div>
											<div class='fieldWrap'>
												<div class='labelWrap'>Type</div>
												<div class='labelDetails'>
													Glazed Porcelain
												</div>
											</div>
											<div class='fieldWrap'>
												<div class='labelWrap'>Type</div>
												<div class='labelDetails'>
													Glazed Porcelain
												</div>
											</div>
											<div class='fieldWrap'>
												<div class='labelWrap'>Type</div>
												<div class='labelDetails'>
													Glazed Porcelain
												</div>
											</div>
										</div>
									</div>";
								}
								
							}
				?>
					
				</div>
				
				
							<?php	}
							}
						?>

**Comment by fancyapps** [comment]
Wow, it has been a long time since I have seen such poorly written PHP code.

Anyway, you should give HTML output or (even better) a link to live demo, because it is not possible to determine the cause just from this snippet.

**Comment by krishnapreejith** [comment]
Thanks for your time, Anyway I fixed it. I'm sorry to say I didn't get what u said about poorly written PHP Code. Could you please tell my why did you say it, because I have not a better professional experience on coding. I just code what I studied earlier.

**Comment by fancyapps** [comment]
I wonder what and where you have studied, because you have written code that is very hard to read and  maintain. But what is more important - it is a very insecure.

First rule you have to learn before even starting coding is to "never trust user/data!". For example, you have `<h2>".$rw['prod_name']."</h2>` - what if `$rw['prod_name']` contains html code?  Or, what if `$row['clr_name']` contains malicious characters? Like this: 

![fa7c5b5f326e3c4a6cc9db19e7edbaf0-xkcd-bobby-tables](https://user-images.githubusercontent.com/1055589/35391703-18166444-01e8-11e8-8de2-e7f729565ae9.png)

**Comment by krishnapreejith** [comment]
Then how could i fetch the data from databsase

**Comment by fancyapps** [comment]
Use any decent framework, for example, https://laravel.com/

**Comment by krishnapreejith** [comment]
Then you said the framework is more reliable and secure than core PHP. Isn't it?

**Comment by fancyapps** [comment]
Just google something like "how to write secure php code", I am sure you will find some interesting articles/tutorials.
