### ISSUE TITLE
Youtube Videos not shows (iframe forced at display : none)

### ISSUE THREAD

**Issue by RomActive** [fancyapps/fancybox#1808]
Hi there,

I'm trying to display youtube videos on this website : 
http://dev.romain-cotton.fr/loic/agence-communication/portfolio/publicite-volkswagen/
(click the blue link or the last image).

The video lauch (you can hear the sound), but there is no images...
Here is FancyBox V3.1.20, but I also tried V.3.2.10 (latest) : same issue

Do you have any idea ?
Note : I use .less file, compiled into css (maybe something about CSS ?)
Note 2 : It seams that the iframe is forced at "display:none"

Thanks :)

**Comment by fancyapps** [comment]
Hi,

Works fine for me. I do not know if you have somehow solved your issue or what...

**Comment by RomActive** [comment]
Hi,

Not working for me on desktop (but on mobile, it's OK).
Which browser used ? (Chrome 63 here).
Verry strange... :(

**Comment by fancyapps** [comment]
I tried on Chrome/Firefox/Edge/IE11 and works fine. 

Have you checked developer tools console, maybe there is a clue.

**Comment by RomActive** [comment]
Hi,
Still nothing. Nothing in the console either (see my print screen).
![fancybox](https://user-images.githubusercontent.com/35597765/35275687-d8988480-0040-11e8-9a9d-91779fed02cc.JPG)

Which version of jQuery is recommanded please ? And with which version of FancyBox ?
_I tjink i'll start all over again..._ :)

Thanks again.

**Comment by fancyapps** [comment]
Hmm, I even tried on Macbook and it worked fine. Are youtube videos loading fine for you, for example, here - https://codepen.io/fancyapps/pen/zPBEBN?editors=1000 ? Maybe try setting iframe : { preload : false } and maybe set animationEffect and transitionEffect to false, too, to see if helps.

It is always best to use the latest version of any software.
