### ISSUE TITLE
Hide Thumbnails on Mobile - Q

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [fancyapps/fancybox#1810]
Hi. I saw this issue https://github.com/fancyapps/fancybox/issues/1588

This should work only on mobile devices (Test on mobile - works fine) -  or also on desktop browser resize (to mobile breakpoint)?

Codepen:
https://codepen.io/ezra_siton/pen/YYBJxB

**Comment by fancyapps** [comment]
Hi,

This hides on mobile devices. Previously, thumbnails were hidden using CSS media queries on small screens, but it was removed. If you wish, you can add these rules by yourself (e.g., you just would need to hide ".fancybox-thumbs" element and override position for ".fancybox-show-thumbs .fancybox-inner").

Basically, do not be afraid to write custom CSS that overrides defaults. fancyBox is designed so you can (and should) do so to customize the layout.

**Comment by Ezra-Siton-UIX** [comment]
Thanks. Very useful option
