### ISSUE TITLE
Two invalid CSS properties

### ISSUE THREAD

**Issue by LanKing** [fancyapps/fancybox#1811]
https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ffancyapps.com%2Ffancybox%2F3%2Ffancybox%2Fjquery.fancybox.min.css%3Fv%3D1516652731&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

set units in px.

**Comment by fancyapps** [comment]
These units are not px, see
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width
https://css-tricks.com/almanac/properties/s/stroke-width/

**Comment by LanKing** [comment]
Ok, but css validator shows errors about it.
