### ISSUE TITLE
One button - whole gallery

### ISSUE THREAD

**Issue by rocko2** [fancyapps/fancybox#1812]
Searching and browsing,... can't find.

Is there a possibility to have for example just one button, and when you click on it, to load in overlay the whole gallery.
I'm thinking to have dynamic url on the button and to load dynamic gallery in iframe in overlay.

So I would actually have a file like iframe-gallery.php in which I would generate images, upon gallery Id parameter from button url, when clicked.

Idea is to be able to open particular gallery without laying out all images, just to have one button, and also not to generate all the images in parent page.

Just to have one button, with whom I could open whichever gallery, depending on single parameter, like ID of gallery.

**Comment by fancyapps** [comment]
Hi,

It sound like you would just need to create custom click event and from there you would load your php file that would return array of gallery items and just do $.fancybox.open( [ array of your images ] );

**Comment by rocko2** [comment]
Uh, ok will try that. Thanks!!
