### ISSUE TITLE
Google maps marker not showing up

### ISSUE THREAD

**Issue by Egretta** [fancyapps/fancybox#1813]
map itself showing up, but marker doesn't. i'm using fancybox 3.2.5. [the place on a map](https://www.google.ee/maps/place/Hostel+Siiram/@60.2118739,24.314299,17z/data=!3m1!4b1!4m5!3m4!1s0x468deb54d9001c39:0xc4da07532dfbf5e5!8m2!3d60.2118713!4d24.3164877)

my code:

`<a data-fancybox href="https://www.google.ee/maps/place/Hostel+Siiram/@60.2118713,24.3164877,15z/data=!4m5!3m4!1s0x0:0xc4da07532dfbf5e5!8m2!3d60.2118713!4d24.3164877">Map</a>`

**Comment by fancyapps** [comment]
Hi,

To put a simple marker on Google map, you would need to use different syntax, examples:

```HTML
<a data-fancybox href="https://www.google.com/maps/search/Hostel+Siiram/">Marker #1</a>

<a data-fancybox href="https://www.google.com/maps/search/?api=1&query=Hostel+Siiram/">Marker #2</a>
```

Demo - https://codepen.io/anon/pen/eyoVJJ?editors=1000
