### ISSUE TITLE
Feature request: Disable "F" key from toggling fullscreen

### ISSUE THREAD

**Issue by noahkuhn** [fancyapps/fancybox#1814]
I am loading a good deal of content into a fancy box "inline" element. I'd like to be able to allow people to use the browser standard "command+F" to search the text for keywords, however Fancybox overrides the "F" key and I can't see a way to disable that in the settings. If that exists, please advise, otherwise please consider this request to have control over this behavior. Seems heavy-handed to totally take over the F key. Thanks!

**Comment by noahkuhn** [comment]
Follow up: it appears that adding the undocumented "fullScreen : false" to the options disables the Full Screen capability entirely, which is fine for me. Might be nice to make it a little more flexible though. Thanks.

**Comment by fancyapps** [comment]
Hi,

Thanks, good point. I`ll add additional check if ctrl/alt/shift key is pressed too.

**Comment by fancyapps** [comment]
That check has been implemented in one of the previous versions.
