### ISSUE TITLE
touch: false not working when opts: {} specified

### ISSUE THREAD

**Issue by flosb** [fancyapps/fancybox#1815]
Hey,
I'm running into a weird issue - when specifying aftershow function in the opts parameter, touch: false no longer works.
I narrowed it down to a super simple example here: https://codepen.io/anon/pen/QaemOW
Any ideea what might be wrong?

**Comment by Th3C0D3R** [comment]
`opts : {
        touch : false
      }
`
try this one because you use fancybox.open()

**Comment by flosb** [comment]
thanks for your help Th3C0D3R :+1:

**Comment by fancyapps** [comment]
Yeah, that works fine:

```JS
$.fancybox.open({
    src  : '#pop360_content',
    type : 'inline',
    opts : {
        touch : false
    }
});
```

https://codepen.io/anon/pen/yvVyeM
