### ISSUE TITLE
Feature request: blurred background, download button, mousewheel scroll

### ISSUE THREAD

**Issue by gwbonline** [fancyapps/fancybox#1816]
I'm an enthusiastic user of Fancybox3. From older versions, I was used to use the mouse wheel to navigate forward or backwards in a series of pictures. I added the option like it is from the documentation and it doesn't work (example over here: http://www.degeintrappers.nl/vereniging/foto-s#ajax-6 ). Secondly I was wondering if it is possible to introduce a blurred background when viewing a modal window or when I view images. And last (but not least), is there a download button possible when viewing an image from an AJAX window and without the menu bar at the top?

**Comment by fancyapps** [comment]
Hi,

1) Latest versions have built-in support for mouse wheel.
2) You can, but you would need to place all content into some separate wrapping element. Then you would use CSS filter() on that element. Demo - https://codepen.io/anon/pen/rJMEgw
3) What do you mean by "Ajax window"?

**Comment by gwbonline** [comment]
I did find the option for scrolling with the mouse wheel and I enabled it. But it doesn't work. What do I need to do more to make it work?

With AJAX windows I meant a modal window without the menu bar at the top. In my case it is for viewing images and I like it more than the demo with a menu bar. The menu bar has a download button. Is it possible to have that download button 'on' the image when viewed? I like a button in the corner of the image. Or a text link.

**Comment by fancyapps** [comment]
Sorry, but I just do not understan you. 

1) It is enabled by default and `wheel` option is used to disable. Open http://fancyapps.com/fancybox/3/#gallery-1 and then try using mouse wheel, does this not work for you?

2) Could you give a screenshot or a sketch about what you have imagined? If you are wondering how to add custom button to the toolbar, then here is an example - https://codepen.io/fancyapps/pen/MOEXmJ

**Comment by gwbonline** [comment]
1. I enabled it on the following page (http://www.degeintrappers.nl/fotoserie#ajax-1). It is the setting in jquery.fancybox.js, right? This is set to 'auto'.

2. See screenshot below. In the left bottom corner I have put in a download button. This could also be a text link. I do not have the menu bar with this (see live link mentioned above) and I don't want the menu bar. I just need a download button or link on the actual image.

**Comment by fancyapps** [comment]
OK, now it is clear. You are using older version where wheel support was not added. Try upgrading to the latest. 

You can use this demo as an example of how to append something over the image - https://codepen.io/fancyapps/pen/GOWpJG In this demo, there is custom close button, but you, obviously, can put anything.
