### ISSUE TITLE
Feature Request: Slide in thumbnail sidebar and more

### ISSUE THREAD

**Issue by justDeek** [fancyapps/fancybox#1817]
Currently, when you click on the thumbnail icon to preview all linked pictures, it opens it immediately which looks a bit harsh and sudden. A smooth transition (maybe even with options to set the animation type like linear, ease-in-out, maybe some bounce-effect, ...) should help to not break the flow and look more pleasing.

I haven't looked into v3 yet, so there might already be such functionality in it, but judging by the demos it always seems a bit out of place to have all these smooth transitions between images and then the thumbnail sidebar opens so suddenly and shoves the rest away.

Additionally it might look better with a transparent/blurry background instead of a solid color and if possible, it would be great if you can let the site-visitor decide, from where the thumbnail preview slides in (maybe 4 little icons at the bottom that represent each side).

**Comment by fancyapps** [comment]
Hi,

Thanks for your thoughts. I actually have experimented with transitions etc, but it seemed to work better as it is now. You should also take into account that user can toggle thumbs while image is zooming/sliding.

Anyway, if anyone wants to add animations, it is possible using a bit of CSS.
