### ISSUE TITLE
caption appearing and staying while hovering over image

### ISSUE THREAD

**Issue by raphaelreift** [fancyapps/fancybox#1818]
Hello everyone,

I've recently started coding and I've been stuck trying the following:

I'd like to make the captions (the caption-container) appear, when the user hovers over an image. Since I'm new to Javascript (well, to coding as a whole) I couldn't figure out how to make it work. I should be able to use the hover function to do that, but I don't know how...
So to rephrase it: When the user hovers over the image (mouseenter) the caption should appear and when the user hovers over an other image, the caption should change (I've defined the caption via "data-caption" for every image). 

Can anybody help me?
If something is unclear, please ask. I'm new to this whole world (coding, Github, etc...)

Thanks a lot for your help!

Greetings,
Raphael Reift

Ps: My hunch is, that by replacing the the toggleContent (for the caption-container) with the hover function, it should work somehow...

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not think this is great idea. How will user know if there is a caption or not, it would be annoying to move mouse around just to check. 

Another issue - what does "hover" mean? E.g., when user clicks thumbnail, large image appears, but user has not moved mouse - should caption be visible or not? 

What if user does not mouse at all? And mobile device users?
