### ISSUE TITLE
Iframe and group

### ISSUE THREAD

**Issue by fredericlam** [fancyapps/fancybox#1823]
Hi 

sorry if this has been already asked, but I'm struggling trying to configure fancybox with iframe, opening several urls and let the user navigate with "prev/next" button as if urls were grouped as a gallery. 

Ex 

`
<a href="URL1" class="fancybox" rel="grouping">Link 1</a>
<a href="URL2" class="fancybox" rel="grouping">Link 2</a>
<a href="URL3" class="fancybox" rel="grouping">Link 3</a>
<a href="URL4" class="fancybox" rel="grouping">Link 4</a>
`

But I can't see any "prev/next" button. 

Also, I tried as they were youtube videos, adding "fancybox.iframe" class but unsuccessfully. 

Is it feasible or I'm facing a non-working feature ?

Thanks

**Comment by fancyapps** [comment]
Hi,

If  you are using fancyBox3, then grouping for iframes works the same as for any other link, by adding same value for `data-fancybox` attribute (for example, `data-fancybox="group"`)
