### ISSUE TITLE
Ohh!Please fix this problem in the next version.

### ISSUE THREAD

**Issue by zhangzicao** [fancyapps/fancybox#1824]
@fancyapps The problem is still exist in the lastest version,v3.2.5.
In the hash mode,when I click the close button or pull down the photo to close the fancybox,the page's url is updated by replace,that make a problem : I have to back at least 2 times to come back to the last page.
Fancybox is the best gallery plugin in every I had used,I hope my issue can make it better.Thanks for your contribution.

**Comment by fancyapps** [comment]
Thanks, I`m looking into that.

**Comment by challLS** [comment]
We are having the same problem, 2 back clicks required whenever a visitor opens the Fancybox. I submitted this to our IT team and they found this post. Hopefully, you will be able to resolve this. Best regards.

**Comment by exhang** [comment]
We are having the same problem, the only thing bad in fancybox

**Comment by sasoriza** [comment]
+1

**Comment by matthendrix** [comment]
+1

**Comment by fancyapps** [comment]
The latest version (v3.3.0) contains improvements related to this issue.
