### ISSUE TITLE
Fullscreen popup message

### ISSUE THREAD

**Issue by merravid** [fancyapps/fancybox#1829]
I've configured fancybox to autostart full screen mode on small screens. This works well however on Chrome on Android I get a popup message saying "Scroll from top and press back button to exit full screen", each and every time I start the gallery. As you can imagine, this is a nuisance.

I understand this is a Chrome "feature", but is there any way to avoid this popup?

**Comment by fancyapps** [comment]
Hi,

This is a security feature and can not be avoided. 

> Due to security reasons you can not force a user into full-screen mode. The user has to activate full-screen mode through some sort of interaction with your web site, say by clicking a “Full-screen” button, and even then some browsers will display a message asking for confirmation that you (the user) really do want to enter full-screen mode.

(From https://michaelwhyte.ca/blog/html5-fullscreen-api)
