### ISSUE TITLE
Internationalization : French

### ISSUE THREAD

**Issue by boisellea** [fancyapps/fancybox#1830]
Hi,

Here is the French translation I use. You might want to add it to your list.

`'fr': {
                                            CLOSE: 'Fermer',
                                            NEXT: 'Suivant',
                                            PREV: 'Précédent',
                                            ERROR: 'Le contenu demandé ne peut être chargé. <br/> Veuillez réessayer plus tard.',
                                            PLAY_START: 'Démarrer le diaporama',
                                            PLAY_STOP: 'Pause',
                                            FULL_SCREEN: 'Plein écran',
                                            THUMBS: 'Vignettes',
                                            DOWNLOAD: 'Télécharger',
                                            SHARE: 'Partager',
                                            ZOOM: 'Zoom'
                                        }`

**Comment by fancyapps** [comment]
Hi,

Thanks!
