### ISSUE TITLE
Fancybox 3: Focus last image viewed and scroll page.

### ISSUE THREAD

**Issue by ieraora** [fancyapps/fancybox#1832]
Hallo, 
at this link https://codepen.io/ieraora/pen/QQpZgp I have, with Fancybox2, a focus to last image viewed and scroll page to same image.
I tested this with Fancybox3, but it don't work. How can I do? What are errors? 
Thank you.

**Comment by fancyapps** [comment]
Hi,

Change `class="fancybox-thumbs fancybox"  rel="gallery1"` to `data-fancybox="gallery1"` and
set `backFocus : false`. This is how you can access current link - `$(current.opts.$orig)`

https://codepen.io/anon/pen/mXWopw?editors=1010

**Comment by ieraora** [comment]
Thank You Jānis, Very well.
