### ISSUE TITLE
Display Fancybox3 with large content (width)

### ISSUE THREAD

**Issue by Maarco73** [fancyapps/fancybox#1833]
I have an issue with fancybox3. If you have a bigger content width,  e.g. 2500px, the display of the box proceeds not as normal. To see this  fancybox you will have to scroll down.

Here is my code:
```
<div>
  <a data-fancybox data-src="#hidden-content" href="javascript:;">
	  Trigger the fancyBox width 500px;
  </a>
  <br>
  <a data-fancybox data-src="#hidden-content2" href="javascript:;">
	  Trigger the fancyBox width 2500px;
  </a>
</div>
          
<div style="display: none;" id="hidden-content">
	<h2>Hello</h2>
  <div style="width: 500px;">
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. 
  </div>
</div>

<div style="display: none;" id="hidden-content2">
	<h2>Hello</h2>
  <div style="width: 2500px;">
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, 
  </div>
</div>
```
The older fancybox version shows scrollbars inside the fancybox. How can I correct this?

**Comment by fancyapps** [comment]
Hi,

I already gave answer on SO, but basically, the easiest solution is to make your content scrollable, like this:

```
#hidden-content2 {
  max-width: calc(100% - 80px);
}
```

but I would suggest to add another wrapper around your extra wide content and make it scrollable instead of the parent element, like so - https://codepen.io/anon/pen/RQVoOP

**Comment by Maarco73** [comment]
It works! Thank you for your support!
