### ISSUE TITLE
Fancybox not centered? Align left

### ISSUE THREAD

**Issue by nienic** [fancyapps/fancybox#1836]
I'm trying to align fancybox to left.
First I tried to change margin option like this:
`  margin : [44, 480, 44, 0],`
I had what I wanted but only on my screen resolution. On smaller screen it was diffrent.

Is there a way to align to left and set margin from the edges of screen?

**Comment by fancyapps** [comment]
Hi,

It is not possible to answer this question, because there can be multiple scenarios with various answers.

For example, you could use CSS, like this:

```CSS
.fancybox-stage {
  right: 480px;
}
```

**Comment by nienic** [comment]
Hi,
thanks for answer.
Scenario is simple.
Default fancybox is like this 
![now](https://user-images.githubusercontent.com/7283356/36123616-94d3ae9c-104d-11e8-880c-a9ec268175c1.png)

And I want to align image to the left.
![align](https://user-images.githubusercontent.com/7283356/36123640-a4e21576-104d-11e8-85d9-75a9d9a6e916.png)

**Comment by fancyapps** [comment]
Sorry, there is no option for custom alignment and there are no plans for that. You can realign and resize the layout using CSS.

btw, 'margin` option will be dropped in v3.3.
