### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Bert-de-Jong** [fancyapps/fancybox#1837]
The [License](https://github.com/fancyapps/fancybox/blob/master/README.md#license) section of README.md says

> fancyBox is licensed under the GPLv3 license for all open source applications. A commercial license is required for all commercial applications (including sites, themes and apps you plan to sell).

This is impossible. GPLv3 licensed code can _always_ be used in a commercial context, even for monetary gain. You can't put restrictions on its use. Even if a user would (change and) re-distribute, they can do so in a commercial context, although they would have to share the code on the same license terms. You certainly can't limit web access to GPLv3 software ("sites") in a commercial context; in fact, the host wouldn't even need to re-distribute; that's what the [Affero GPL](https://en.wikipedia.org/wiki/Affero_General_Public_License) is for. You could contact the [SFLC](https://www.softwarefreedom.org/about/contact/) to verify this, if you're in doubt. You can multi-license fancybox in a way MySQL is doing, by making two additions (e.g. a Community Edition and a Enterprise Edition), but you can _not_ restrict commercial use of a GPLv3 licensed edition of the code.

**Comment by fancyapps** [comment]
Hi,

Thanks for your insights. I hope you understand that this project is not run by some software giant to make enormous profit. By purchasing the licenses you are supporting development of this project.
In the spirit of open source software, dual licensing was chosen, but, since this brings more confusion than gain, GPL licensing will be dropped.

**Comment by Bert-de-Jong** [comment]
Perhaps it's wise to not act too hastily, and consider alternatives to dropping GPL support. Dropping GPL support will likely result in fancyBox being [forked](https://en.wikipedia.org/wiki/Fork_(software_development)) to keep it FOSS, which would likely mean people will move away from fancyBox, similar to how users are moving - have moved - from OpenOffice.org (Oracle) to LibreOffice (TDF). There are good ways to multi-license software, you just need two or more editions. The main point is, you can not restrict commercial use of a single, GPLv3 licensed edition.

**Comment by Bert-de-Jong** [comment]
There's no need to rush to find a good solution for this, of course. However, this may eventually require some kind of action on your part. One thing you could do is move back to the Creative Commons (CC BY-NC 3.0) license you used for previous releases of fancyBox. Another is to stick with GPLv3 but use two or more editions, with the commercial edition(s) having unique/additional features or unique/additional customer support. By the way, the [License](https://github.com/fancyapps/fancybox#license) section of README.md still has "Read more about fancyBox license" linked to the 2.x page.
