### ISSUE TITLE
trapFocus disables tab focus inside modal (ajax-loaded)

### ISSUE THREAD

**Issue by overtune** [fancyapps/fancybox#1838]
If trapFocus is set to true (default) and you load an page with ajax. The links on that page can be tabbed to (focused) the first time. But if you keep pressing tab so it focus all other elements, the next time only the close button will be focused and not the content in the modal.

If trapFocus is set to false this circular tabbing works as expected.
Is this a bug or just how it is?

I've created two codepens to illustrate the problem:

WITH trapFocus (open the modal and keep pressing tab, first round it will focus the links inside the modal, but when you have tabbed through every other element and focus returns to the modal, it will not focus on the links).
https://codepen.io/overtune/full/bLRZvR/

WITHOUT trapFocus
https://codepen.io/overtune/full/ddRrZb/

**Comment by fancyapps** [comment]
Hi,

This should be fixed some time ago - https://codepen.io/fancyapps/full/vzXRBm/ (sorry for late response).
