### ISSUE TITLE
'destroy' not documented

### ISSUE THREAD

**Issue by jamiewade** [fancyapps/fancybox#1839]
As per the comment on [this issue](https://github.com/fancyapps/fancybox/issues/1831), you can run `$.fancybox.destroy();` to disable Fancybox.

However this is not mentioned in the [documentation](https://fancyapps.com/fancybox/3/docs/) (from what I can see, anyway).

**Comment by fancyapps** [comment]
And it is actually the same as `$('document').off( "click.fb-start" )`.
