### ISSUE TITLE
Update Docs Programmatic Example To Include Thumbs

### ISSUE THREAD

**Issue by Enchiridion** [fancyapps/fancybox#1840]
Under the API section of the docs, could you update the programmatic example to show how to set the thumbnail image?  I had to check the source to see if it was even possible, would save others time.

```
$.fancybox.open([
	{
		src  : '1_b.jpg',
		opts : {
			thumb   : '1_b_thumb.jpg',
			caption : 'First caption'
		}
	},
	{
		src  : '2_b.jpg',
		opts : {
			thumb   : '2_b_thumb.jpg',
			caption : 'Second caption'
		}
	}
], {
	loop : false
});
```

**Comment by fancyapps** [comment]
Hi,

Thanks for the suggestion. I have updated that example.
