### ISSUE TITLE
Bootstrap Vue Modal not displaying images

### ISSUE THREAD

**Issue by edgarscr** [fancyapps/fancybox#1842]
Hello im trying to display the image preview and not work just sending me to image url. 

i have the images inside a Modal

![image](https://user-images.githubusercontent.com/33737821/36225058-e1cbccae-119f-11e8-98df-9e701e5257da.png)

im using [VueJS](https://vuejs.org/) + [Vuetable 2](https://github.com/ratiw/vuetable-2) + [Bootstrap Vue Modal ](https://bootstrap-vue.js.org/docs/components/modal/)

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not know how to help. Works fine without using VueJS + Vuetable 2 + Bootstrap Vue Modal.
