### ISSUE TITLE
Share Button/Modal Doesn't Work Correctly In Fullscreen

### ISSUE THREAD

**Issue by Enchiridion** [fancyapps/fancybox#1843]
I found that if you're viewing the modal in full screen mode, then click the Share button, the share modal isn't visible (since it wasn't the element that was fullscreen'd).  It also prevents the Close button from working (you can click it, but it does nothing).  I have to click a blank area to trigger the main modal to exit fullscreen mode and close, however the share modal is still visible.

Solutions could be:
* Disable the Share button when entering fullscreen mode
* Open the share modal within the fullscreen'd element
* Switch the active fullscreen element to the share dialog, then switch back when it is closed

**Comment by fancyapps** [comment]
Hi. This should be fixed in the last version.
