### ISSUE TITLE
Can I mix video, image and HTML content?

### ISSUE THREAD

**Issue by Toccamonium** [fancyapps/fancybox#1847]
Hi, I want to build a gallery with different types of content, like images, video or an HTML piece with an local mp4 file. Is this possible?

**Comment by fancyapps** [comment]
Hi, Yes, why not

**Comment by SarahTrees** [comment]
Is there an working example?

**Comment by acwolff** [comment]
See [this test album](https://andrewolff.jalbum.net/Vecht_SaharaN_FB/), which is a combination of images and videos.

It is made with the [jAlbum program](https://jalbum.net/en/software) where [my FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) is used.
