### ISSUE TITLE
srcset broken on 3.2.5 & 3.2.10? 

### ISSUE THREAD

**Issue by damondok** [fancyapps/fancybox#1848]
I'm using npm to install fancybox "npm -i @fancyapps/fancybox", it retrieves the latest tagged version 3.2.5.

"data-srcset" works differently with that version as expected. Instead of adding the whole srcset to the slide image, it retrieves the approriate source for the current viewport size and adds that as src. It's the same behavior with 3.2.10.

Another issue is the download button. It always adds the currently used src instead of the largest available one. Is there a way to override the download src so I can implement a workaround?

img Tag with 3.2.5 and 3.2.10 (srcset is missing)
`<img class="fancybox-image" src="https://placeholdit.imgix.net/~text?txtsize=33&amp;txt=2_large_1600%C3%97800&amp;w=1600&amp;h=960">`

Here's a [Demo](https://codepen.io/anon/pen/XZZGgX). It's basically your srcset Demo but with 3.2.5 instead of 3.2.11. If you inspect the img in an open fancybox, srcset is missing. 

It's working as expected though in your [https://codepen.io/fancyapps/pen/gXMxJj](Demo) which uses 3.2.11. img Tag with 3.2.11
`<img class="fancybox-image" src="https://placeholdit.imgix.net/~text?txtsize=33&amp;txt=1_large_1600%C3%97800&amp;w=1600&amp;h=960" sizes="100vw" srcset="https://placeholdit.imgix.net/~text?txtsize=33&amp;txt=1_large_1600%C3%97800&amp;w=1600&amp;h=960 1600w,
						       https://placeholdit.imgix.net/~text?txtsize=33&amp;txt=1_medium_1200%C3%97800&amp;w=1200&amp;h=720 1200w,
			             https://placeholdit.imgix.net/~text?txtsize=33&amp;txt=1_small_640%C3%97427&amp;w=640&amp;h=384 640w">`

When will you make 3.2.11 available? Is the above behavior actually intended?

**Comment by fancyapps** [comment]
Hi,

What do you mean by "broken"? Are you aware that testing "srcset" is quite ... tricky? For example, browser might decide to show cached version instead of the one you might expect. Also, this varies across browsers. The script is creating html structure according to specs, but the rest is up to the browser.

**Comment by damondok** [comment]
I thought "broken" was a bit far fetched too so I switched to "unexpected", I just forgot to change the title ;-)

I'm aware that testing srcset can be quite tricky. I'm not talking about issues how the browser seems to handle the srcsets though but around my observation, that **srcset works differently in your latest version 3.2.5 than you demonstrate in your srcset Demos**: 

- [srcset Demo 3.2.11](https://codepen.io/fancyapps/pen/gXMxJj)
- [srcset Demo 3.0.47](https://codepen.io/fancyapps/pen/bqbpbO) > linked in issue #1203 

In those demos the `<img />` tag inside of `<div class="fancybox-image-wrap">` actually has a `srcset` attribute. 

In 3.2.5 **the srcset attribute is missing on the `<img />` tag** inside of `<div class="fancybox-image-wrap">`. There's only a `src` attribute. Check this behavior at this[Demo](https://codepen.io/anon/pen/XZZGgX) which is a copy of your 3.2.11 Demo but with 3.2.5. It seems like fancybox decides which src to use from the srcset which works according your description in #1203: "The script is parsing "srcset" value anyway. It chooses the right initial src value, otherwise the browser (that supports "srcset") might download two files (one from "src" and one from "srcset")." **Fancybox just forgoes adding the srcset as well.**

I debugged your code a bit and discovered that you set the srcset here (core.js line 1778)
```
if ( slide.opts.image.srcset ) {
  $img.attr( 'sizes', '100vw' ).attr( 'srcset', slide.opts.image.srcset );
}
```

slide.opts.image.srcset is undefined though. slide.opts.srcset contains the correct srcset. If i change your code to this, srcset works as expected.

```
if ( slide.opts.srcset ) {
  $img.attr( 'sizes', '100vw' ).attr( 'srcset', slide.opts.srcset );
}
```

Hope I was clear enough this time. Love fancybox btw, it's by far the best lightbox plugin out there and I really checked them all.

**Comment by fancyapps** [comment]
Thanks :) 

Well, it is hard for me to comment older versions, because I am now working on v3.3 and I already have (some time ago) made some changes that are related to srcset. Maybe you could try that out - https://codepen.io/fancyapps/pen/VyLOJX?editors=1010

**Comment by damondok** [comment]
Alright. I'll just wait for the update then.

As 3.2.5 is the latest official version I thought it be worth mentioning that srcset attributes are not correctly added to the images but I guess that will work again with the next release ;-)
