### ISSUE TITLE
Iframes Gallery with Watermark on a corner

### ISSUE THREAD

**Issue by piratamovil** [fancyapps/fancybox#1853]
I saw that there is a way to put a text as a watermark, but I wondering how to put a watermark image, in the corner of an iframes gallery.

Is it possible ?, can you help me?
Thanks in advance!

**Comment by fancyapps** [comment]
Hi,

It could be something like this - https://codepen.io/anon/pen/NyOwLd

**Comment by piratamovil** [comment]
Although the code works very well for images, I have a problem with watermark in videos, it is placed over the video player and it does not let me use the controls of it (volume, full screen, etc.), how can I fix this problem ?

**Comment by fancyapps** [comment]
You could add `pointer-events: none;` to make it clickable.

**Comment by piratamovil** [comment]
Great, is working perfectly now.
Thank you very much for your help, I love Fancybox!
