### ISSUE TITLE
Vertical mouse scroll images

### ISSUE THREAD

**Issue by ZacharyElkins** [fancyapps/fancybox#1854]
Hi,

I am wondering if there has been an update to this, or if it is in any way possible now or in the future.

I have images which are large in height that would be best to be scrolled with a mouse wheel when viewing on a desktop.

The closest solutions I found where:
#1667 and #1833 

I'm concerned that these solutions mess with the draggability on mobile.

**Comment by fancyapps** [comment]
Hi,

Sorry, there is no option for that yet. This is planned for v3.4.
