### ISSUE TITLE
JQuery UI bug in outerWidth (Height) for scrolling thumb list

### ISSUE THREAD

**Issue by leozelion** [fancyapps/fancybox#1856]
Hahah! 😅 While I wrote, I already found the solution, and then figured out what the problem is.

I've found bug in `outerWidth()` and `outerHeight()` with no arguments, when JQuery library using with in JQuery UI 1.8.[2,18,20] (and maybe some else). This method work as setter and return jquery object instead of number. This stops working the normal behavior `FancyThumbs.focus()`, when the thumbs list does not fit in the screen, and focusing on the next thumb that extends beyond the window does not scroll list to make current thumb visible.

Simple solution - migrate to JQuery UI 1.9 and above. Hard solution - adding the argument `false` in each outerWidth|Height empty methods (false is default flag).

**Comment by fancyapps** [comment]
I wonder if jQuery UI has any relation to `outerWidth()` and `outerHeight()` methods, because they are part of jQuery core.

**Comment by leozelion** [comment]
@fancyapps Yes, but in old versions of the UI this methods is overwritten by the UI:
```
a.fn["outer" + d] = function(b, c) {
        if (typeof b != "number")
           return g["outer" + d].call(this, b);
        return this.each(function() {
            a(this).css(f, h(this, b, !0, c) + "px")
        })
    }
```
So you can warn users with a legacy libraries, like me)
