### ISSUE TITLE
How to disable share button globally?

### ISSUE THREAD

**Issue by alan-zhang-** [fancyapps/fancybox#1861]
Hi, 

I use it in my whole site, but how to disable the share button globally.

Thanks.

**Comment by patrickskyer** [comment]
Override the style as

.fancybox-button—share{
     display: none;
}

**Comment by fancyapps** [comment]
Hi,

There are two solutions -

1) Compile your custom fancybox.js file excluding modules you do not need;

2) Change default `buttons` option to you likening, for example:

    ```JS
    $.fancybox.defaults.buttons = ['close'];`
    ```
