### ISSUE TITLE
Custom download button for iFrame

### ISSUE THREAD

**Issue by MarkoD** [fancyapps/fancybox#1867]
Hi, I'm using the latest release (v3.2.5) for a mixed gallery (photos and HTML5 videos). Since the current version doesn't fully support the HTML5 video element, I'm using a workaround via inline HTML pointing to a hidden div containing the video.

I've disabled the right click (via "protect": true) and control the video via mouse clicks. Fancybox hides the download button for the video slide. Is there a way to override it and make the button visible in the toolbar so that when a user clicks it, he will dowload the video? I'm trying to mimick the video's right-click context menu which has a "Download video" in most browsers, using the download button in the context menu.

Thanks for any suggestions!

**Comment by MarkoD** [comment]
Found a workaround by manually setting the download button's `href` and forcing it to reappear via `afterShow` trigger:

```javascript
$(document).on("afterShow.fb", function(e, instance, slide) {
  var $container = instance.$refs.container;
  var url = slide.opts.$orig.attr('href');

  if (instance.current.type === 'inline' && url) $container.find('[data-fancybox-download]').attr('href', url).show();
});
```

**Comment by toptalo** [comment]
With `data-` attribute example:
```javascript
afterShow: function (event, instance) {
    var download = instance.opts.$orig.data('fancybox-download');

    if (download) {
        var $container = event.$refs.container;
        $container.find('[data-fancybox-download]').attr('href', download);
    }
}
```

**Comment by fancyapps** [comment]
Hi,

It would be much simpler to create your own buttons, for example:

```JS
$.fancybox.defaults.btnTpl.download2 = $.fancybox.defaults.btnTpl.download.replace('data-fancybox-download', '');

$('[data-fancybox="gallery"]').fancybox({
	buttons : [
		'download2',
		'close'
	],
	beforeShow : function(instance, slide) {
		instance.$refs.container.find('.fancybox-button--download').attr('href', slide.src);
	}
});
```

https://codepen.io/anon/pen/jvJGdY?editors=1010

**Comment by misurex** [comment]
Sorry for hijacking this post, but I had the same question, and the @fancyapps's answer was working for me. But I also need another thing, to change the URL of the current video, for one in hi res. Actually, I need to remove one node in the url. I tried (to remove /video_medium from the url) this code, but it isn't working.

beforeShow : function(instance, slide) {
       var src =  slide.src.replace('/video_medium', '');
       instance.$refs.container.find('.fancybox-button--download').attr('href', slide.src);
  }

Please advise. Thank you.
