### ISSUE TITLE
Migration to new fancybox 3.1

### ISSUE THREAD

**Issue by murderaven** [fancyapps/fancybox#1868]
Hello,

I've using older fancybox for my project, but I want to migrate it to new fancybox. I was change css and js files but its doesnt work. Here is my fancybox caller;

```
				$('.btn').fancybox({
					autoSize : true,
					type     : 'iframe',
					href     : '../index.php',
				});
```

**Comment by fancyapps** [comment]
Hi,

Sorry, this does not seem to work in the current version, but I have made a small update and it will be working in the next version.

In meantime, you can simply add `data-src` and `data-type="iframe"` attributes to your links to make them work.
