### ISSUE TITLE
Bug: Google Maps: Invalid URL with parameter like hl=en (after rendered)

### ISSUE THREAD

**Issue by l2aelba** [fancyapps/fancybox#1870]
Someone copied urls with parameters like **hl=en**
and they would get **'X-Frame-Options' to 'sameorigin'** problems and **invalid urls**

**Given url:** https://www.google.com/maps/@52.2111123,2.9237542,6.61z?hl=en
**iFrame src:** https://maps.google.com/?ll=52.2111123,2.9237542&z=6?hl=en&output=embed
**iFrame src:** https://maps.google.com/?ll=52.2111123,2.9237542&z=6&hl=en&output=embed
You see **?hl=en** in middle ? This is valid, it should be **&hl=en**

**Demo:** https://codepen.io/anon/pen/OvJGYx?editors=1100

**Comment by fancyapps** [comment]
Hi. This should be fixed in the last version.

**Comment by l2aelba** [comment]
@fancyapps Thanks, its fixed https://codepen.io/anon/pen/bvzrPm?editors=1100
