### ISSUE TITLE
Overlay disappears too fast on mobile when tapped after timeout

### ISSUE THREAD

**Issue by pronobis** [fancyapps/fancybox#1871]
I have idle time set to 3. On a desktop everything works as expected, however, on mobile, when the overlay disappears after 3s, tapping on the image shows it only for about 0.5s instead of full 3s. Any workarounds?

**Comment by fancyapps** [comment]
I re-read your comment 3 times and could not figure out what is your issue.

**Comment by pronobis** [comment]
Ok, it might be easier with an example.
- Please go to the following page with a mobile device (chrome on Android)
https://www.pronobis.pro/projects/deep_generative_model/
- Click on any image in "Highlights"
- Wait 3s until the caption overlay disappears
- Click on the image to show the overlay again

Now, instead of 3s, the overlay disappears after 0.5s

**Comment by fancyapps** [comment]
Actually, `idleTime` is disabled on mobile devices by default. Have you enabled it or maybe your phone is not recognized as mobile device?

**Comment by pronobis** [comment]
This occurs no matter what I set in     

```
mobile : {
      idleTime : 3,
}
```
and even when no idleTime is specified for mobile.
