### ISSUE TITLE
FancyBox 3.2.5 - Thumbnail images disappear

### ISSUE THREAD

**Issue by Cyb10101** [fancyapps/fancybox#1872]
Hi, the images that are loaded with the FancyBox 3.2.5 disappear and are no longer displayed.

https://youtube.com/watch?v=42K4so6eXi0
https://jsbin.com/metonif/edit?html,js,output

Regards, Cyb10101

**Comment by Cyb10101** [comment]
Damn! Yesterday must be a bad day...
That is the mistake: <a src=""> change into <a href="">
If you no longer need the ticket, just close it.

**Comment by fancyapps** [comment]
Or use `data-src` attribute.
