### ISSUE TITLE
How to close parent fancybox?

### ISSUE THREAD

**Issue by mikkpokk** [fancyapps/fancybox#1873]
Hello

I have "Login" button which opens ajax content using fancybox whenever you click on it. Dialog opens with inputs and "Reset password" link.

**Problem:** However, when I click to "reset password" link it opens new fancybox and old one is still opened behind.

Tried to use this callback inside beforeLoad method but that will close every fancybox before show (even current one).

`parent.jQuery.fancybox.getInstance().close();`

Fancybox version: 3.2.5

**Comment by mjcampagna** [comment]
Untested, just an idea. Maybe try adding different baseClass values to each, then use that close to target the fancybox you want to close?

**Comment by mikkpokk** [comment]
I ended up with unofficial solution, not the cleanest but at least dynamic and working.

![image](https://user-images.githubusercontent.com/14272312/37255918-2982025a-255c-11e8-807b-5429632e4843.png)
