### ISSUE TITLE
Videos are not displayed

### ISSUE THREAD

**Issue by hexerich** [fancyapps/fancybox#1876]
When i create the html markup for video like

```
<div class="imageGallery" id="pSlider1000000245">
    <a data-type="video" data-fancybox="protoSliderGroup1000000245" data-src="big_buck_bunny.mp4">
	<img src="big_buck_bunny.mp4.png>
   </a>
</div>
```

fancybox opens with the video player, but the video is not displayed with the message "not supported format"
the reason seams to be the 'type="undefined" in the generated html.
like in 

`<video controls=""><source src="big_buck_bunny.mp4" type="undefined">Your browser doesn't support HTML5 video</video>`

the opts.videoFormat dedection is only be done when no type is present, jquery.fancybox.js line 705.

`if ( !type && src ) 
`

when I remove the 'data-type="video"'
 the video is displayed but outside of the screen.
in the browser inspector I noticed the rule ".fancybox-slide::before" that creates an element with height 100%. when removing the 100% the video is displayed correctly. 

![grafik](https://user-images.githubusercontent.com/19497178/37356158-a70fc024-26e5-11e8-9e8d-5f9f4fb5e9d1.png)

**Comment by fancyapps** [comment]
Hi,

Just wait for the next release ( here is a preview - https://codepen.io/fancyapps/pen/gopGNq ).

btw, by removing that line you are effectively disabling vertical centering.

**Comment by hexerich** [comment]
Thanks for the answer.
my video was wider than the screen. With your hint, I needed to add a max-width: 100% to prevent the video from wrapping into the next line.

![grafik](https://user-images.githubusercontent.com/19497178/37360520-d38a43a8-26f0-11e8-9af0-053ed1411c5a.png)

I do not know if this is also already handled in the next release. But just in case that not.
thanks

**Comment by fancyapps** [comment]
Sadly, this will be (mostly) unchanged. I really, really wanted to get rid of this stuff (see https://css-tricks.com/centering-in-the-unknown/ for how it works) and I have spend a lot of time looking for the best solution. While flex/grid seems promising, but  .. it is still not perfectly possible to center vertically in the unknown. See https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container

**Comment by hexerich** [comment]
with this additional rule
```
.fancybox-slide > video {
  max-width: 100%;
}
```
