### ISSUE TITLE
Inputs are not editable when slider is open

### ISSUE THREAD

**Issue by Vohidjon** [fancyapps/fancybox#1877]
I have a custom sidebar visible even when slider is open. However, inputs in this sidebar cannot be edited when opening the slider

**Comment by fancyapps** [comment]
I`m not sure if you are using fancyBox or not.

**Comment by Vohidjon** [comment]
Yes, I am using FancyBox. I have a div (sidebar) on the right side of the screen. I have set the z-index of this div higher than that of FancyBox, so it is visible even the fancybox is open.

However, the plugin seems to disable inputs in some way when opening the slider.
Sorry, if was not clear before.

**Comment by fancyapps** [comment]
I guess you would need to disable focus trapping, try setting `trapFocus: false`.

**Comment by Vohidjon** [comment]
That did help. Thanks.
