### ISSUE TITLE
YouTube start time. t= vs start=

### ISSUE THREAD

**Issue by noahkuhn** [fancyapps/fancybox#1878]
I was struggling getting YouTube videos to start at a specified time. When you copy a YouTube video from their site, you end up with one of the following formats:

https://youtu.be/ur6vOA2cF6w?t=25
https://youtu.be/ur6vOA2cF6w?t=25s

or expanded into: 

https://www.youtube.com/watch?v=ur6vOA2cF6w&t=25
https://www.youtube.com/watch?v=ur6vOA2cF6w&t=25s

Based on another issue here in GitHub, I discovered that YouTube embeds actually use **start** as the parameter to designate a start time, not **t**

It would be nice if FancyBox had some logic to convert a **t=25** into **start=25** from a straight YouTube URL. Not sure why YouTube is using two different parameters to accomplish the same thing.

**Comment by fancyapps** [comment]
Hi,

This is actually quite interesting. I think that `?start=` parameter is integer (e.g., seconds) and `?t=` is in time format, for example, `?t=14m39s`.

What is strange,  `?t=` parameter does not work as expected, see this demo - https://codepen.io/anon/pen/vRKyXv?editors=1000 the last link starts at 14min and not 14m39s :/

**Comment by fancyapps** [comment]
This should work now; see https://codepen.io/anon/pen/mxapNK?editors=1000
