### ISSUE TITLE
Change url after opened image

### ISSUE THREAD

**Issue by kleinpetr** [fancyapps/fancybox#1879]
Hello,

if I open the image via fancybox, my url is changed to domain.tld/#gallery..  and if I close then url changed back. But my application works with pushState and popState and this failing my programic logic. 

How can I use fancybox without changing url ?

Thanks for help.

**Comment by fancyapps** [comment]
Hi,

You can either build your own fancybox.js file excluding hash module or simply disable it, like this:

```JS
$.fancybox.defaults.hash = false;
```

**Comment by kleinpetr** [comment]
Thanks so much !
