### ISSUE TITLE
body {-webkit-transform: translateZ(0)} and position: fixed

### ISSUE THREAD

**Issue by BestiaTeam** [fancyapps/fancybox#1880]
Hi, everyone!
We found the one problem with the fancybox overlay.
**JSFiddle**: https://jsfiddle.net/uowbgyjo/4/

**Case**:
- `body{-webkit-transform: translateZ(0); height: 4000px;}` 
- `a{display: block; top: 3000px; position: absolute;  width: 100%;}`

**Expected**:
Fancybox is displayed in the center.
![image](https://user-images.githubusercontent.com/26712896/37643375-5303c902-2c31-11e8-996e-cc10f70748c6.png)

**Result**: 
After clicking on the link, fancybox is displayed incorrectly.
![image](https://user-images.githubusercontent.com/26712896/37643357-47bf2e9c-2c31-11e8-9b37-6ce74d4aeb14.png)

Can you solve this problem? if we can't change this property of the body.
Very thanks!

**Comment by fancyapps** [comment]
Hi,

By adding `transform: translateZ(0);` to the `body` element you are effectively breaking all fixed positioned elements. The simplest solution would be to remove or to disable that property -

```CSS
body.fancybox-active {
    transform: none;
}
```

Or you will need to reposition fancyBox by yourself.
