### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by ifx-cw** [fancyapps/fancybox#1882]
Hello!

I did not find a contact option on the website, so I'm trying it this way:
The website says that the "Extended license is to allow you to build websites for your clients without purchasing a new license for each project". It also says that "By purchasing ONE "Extended Commercial license", you are allowed to include fancyBox in ONE product".

We're developing Typo3-based websites for our customers and use our own base template which we always adjust to our customers' needs. As I understand the terms, this should be covered by the purchase of one Extended license - I just wanted to make sure that I'm getting this right.
Can you confirm that the Extended license covers our needs?

**Comment by fancyapps** [comment]
Hi,

Yes, that would cover your needs. You can contact on https://twitter.com/thefancyapps or https://gitter.im/fancyapps/fancybox

Thanks!
