### ISSUE TITLE
can not replace buttons

### ISSUE THREAD

**Issue by hiasl** [fancyapps/fancybox#1883]
Hi,
I'm working with the newest version of fancybox 3.2 (agency license) and I can not replace the buttons as described in the docs.

This is what I'm doing via JS:
```
    $('[data-fancybox]').fancybox({
        baseTpl: {
            btnTpl: {
                arrowLeft : '<button data-fancybox-prev class="fancybox-button fancybox-button--arrow_left" title="{{PREV}}">' +
                'LEFT' +
                '</button>',

                arrowRight : '<button data-fancybox-next class="fancybox-button fancybox-button--arrow_right" title="{{NEXT}}">' +
                'RIGHT' +
                '</button>'
            }
        }
    });
```

This is causing the following JS error in console: u.baseTpl.replace is not a function

Thanks,
Matthias

**Comment by fancyapps** [comment]
Hi,

You have a slight syntax error :) `baseTpl` option should be string and is used to create base html structure.

**Comment by hiasl** [comment]
embarrassing ... sorry for that. but BIG thank you.
