### ISSUE TITLE
How can I reposition / resize the image

### ISSUE THREAD

**Issue by hiasl** [fancyapps/fancybox#1884]
Hi,
our art director wants us to place the image in the fancybox only in the left half of the screen and have the caption in the right half.

Can I do this via CSS? I did not find out how: I would have thought that there is some kind of stage div, where the image is pasted / fit into with correct ratio.

Thanks,
Matthias

**Comment by fancyapps** [comment]
Hi,

Yes, of course it is possible. And you are right about the stage div, you can move and resize it using CSS and the content will adapt. Something like this - https://codepen.io/anon/pen/EEWMRw
If you would have provided some sketch, I would probably have designed it to match.

**Comment by fancyapps** [comment]
And here is a more complete example - https://codepen.io/fancyapps/pen/xWqNZK
