### ISSUE TITLE
v3 Margins and Zooming (renewal)

### ISSUE THREAD

**Issue by madeckel** [fancyapps/fancybox#1885]
I refer to https://github.com/fancyapps/fancybox/issues/1179, sorry, I don't know if I should comment to this closed issue, so I opened a new one.

I also would prefer to have a margin (same value for top bottom left right) also when an image is zoomed in. But at the current version there's no longer a "fancybox-slider-wrap" class. I tried out several modifications but I wasn't successful, I only get margins on top and left. How would it work at the current version?

**Comment by fancyapps** [comment]
Hi,

If you want to resize / reposition the area where content is placed, then you can easily do that using CSS, for example:

```CSS
.fancybox-stage {
    top: 50px;
    bottom: 50px;
}
```

anyway, any visual guide (sketch or screenshot) would make it easier to help to answer questions like this.

**Comment by madeckel** [comment]
Thank you a lot for your fast answer but I intend another behavior: The window area should be used completely but around the image (if it's bigger than the window and scaleToActual) there should be a margin. An example of use could be a box-shadow around the images (that should not be cut like it would be with your suggested solution).

So it would be great if it would be possible to have the same margin behavior for scaleToActual like it is at scaleToFit. At the standard view scaleToFit a box-shadow isn't cut.

**Comment by fancyapps** [comment]
There is simply no other way to reposition the content. Just play with the CSS.
