### ISSUE TITLE
Zoom button disappears, but does not reappear

### ISSUE THREAD

**Issue by MarkoD** [fancyapps/fancybox#1886]
When a non-image slide is displayed, the zoom button gets hidden. However, when moving to a image slide, the button stays hidden and does not reappear.

A simple fix is to include something like:
`$container.find('[data-fancybox-zoom]').show();`

... after this line:
https://github.com/fancyapps/fancybox/blob/687451cc55d96705c65f512d1ffaafeb46dc8931/src/js/core.js#L2685

Of course, the fix should check if 'zoom' is actually enabled or not.

**Comment by fancyapps** [comment]
Thanks for reporting!

**Comment by fancyapps** [comment]
This has been improved in the last commit.
