### ISSUE TITLE
'afterShow' not triggered when clicking on thumbnail of the current slide

### ISSUE THREAD

**Issue by MarkoD** [fancyapps/fancybox#1887]
When thumbnails are enabled and shown, after clicking on the thumbnail of the current slide, the 'afterShow' event does not get triggered (eventhough a 'beforeShow' event does).

Moreover, the animation gets played eventhough the slide doesn't change.

A fix would be either to:
- not do anything at all (no animation, no events fired),
- or fire both an 'beforeShow' and 'afterShow' event.

**Comment by fancyapps** [comment]
Hi,

Thanks for noticing and reporting 👍 This will be fixed in the next commit (`afterShow` event will be fired)

**Comment by MarkoD** [comment]
One more thing - ```beforeShow``` and ```afterShow``` also get fired when the default "Share" dialog is shown. Also, ```beforeClose``` is fired when closing the dialog. Is this the desired behaviour?

**Comment by fancyapps** [comment]
Share dialog is just another instance of fancybox, therefore it will fire all callbacks as usual.
