### ISSUE TITLE
How to exclude certain images from the gallery?

### ISSUE THREAD

**Issue by moecantplay** [fancyapps/fancybox#1889]
Hi,
Is there even such a feature to exclude certain images from the `data-fancybox="gallery"` ?
If there is, how can I achieve this?

**Comment by fancyapps** [comment]
Hi,

You can do this by removing or changing value for `data-fancybox` attribute.

**Comment by moecantplay** [comment]
I actually do not have any value on the images which I do not wish to include..
Am I possibly missing something ?

**Comment by fancyapps** [comment]
Sorry, I do not understand. You either add empty `data-fancybox` value to automagically attach click event start starts fancybox. If you dd the same value, for example, `data-fancybox="gallery"`, then those elements will be "grouped".
