### ISSUE TITLE
Navigation has no transition 

### ISSUE THREAD

**Issue by madeckel** [fancyapps/fancybox#1890]
The switch ".fancybox-show-toolbar .fancybox-toolbar" has a transition but ".fancybox-show-nav .fancybox-navigation" not. So that at the opening of the Fancybox the toolbar is shown smooth but the navigation not smooth. Or after the idle time the toolbar disappears smooth, the navigation not.

Is this a bug or is there a reason?

Additional hint: at the closed https://github.com/fancyapps/fancybox/issues/1885 I have one more question.

**Comment by madeckel** [comment]
I guess I found out the reason why

.fancybox-navigation {
  display: none; }
.fancybox-show-nav .fancybox-navigation {
  display: block; }

has no transition with opacity and visibility like the toolbar has. I wouldn't work at IE11/Edge because the buttons have absolute position (https://lukeappleton.wordpress.com/2015/03/03/opacity-ie11-and-css-animation/).

A solution could be to address the buttons:

.fancybox-navigation .fancybox-button  {
  opacity: 0;
  visibility: hidden;
  transition: opacity .25s, visibility 0s linear .25s;
}
.fancybox-show-nav .fancybox-navigation .fancybox-button {
  opacity: 1;
  visibility: visible;
  transition: opacity .25s, visibility 0s,
}

**Comment by fancyapps** [comment]
I actually can not remember why navigation elements were excluded from the rest of the elements that have transition. But they are now fading along with others.
