### ISSUE TITLE
How to give a height to the iframe popup?

### ISSUE THREAD

**Issue by d003232** [fancyapps/fancybox#1894]
I'm calling a link to display it as an iframe popup. The lower part of the iframe is covered with the 'title' informations. How can I add a parameter to the link to add some additonal space to the end of the iframe popup.

Because I'm using a CMS system I can't add some JS to that page. I can just edit the html code of the <a> link.  The parameter data-fancybox-height="640" seems not to work.

Thats how I call it:
<a class="fancybox fancybox.iframe" title="thats the text witch covers the bottom part of the iframe content" href="{{link_url::34}}"> 

<img width="960" alt="screenshot 2018-03-26 13 14 19" src="https://user-images.githubusercontent.com/13165419/37903371-eb3ac926-30f7-11e8-8516-d66f96aadd19.png">

**Comment by fancyapps** [comment]
Hi,

From the screenshot it looks like you are using fancybox v2, but data attributes are supported starting from v3. I would suggest to change title type or show/hide title on mouse over.

And sorry, v2 is not supported any more.
