### ISSUE TITLE
Change ".attributes['data-caption'].value" and refresh without manual close/open image

### ISSUE THREAD

**Issue by buthus** [fancyapps/fancybox#1895]
Good morning,
I want to modify the data-caption content when the image is displayed. I created the example:
[https://codepen.io/buthus/full/LdzMLj](https://codepen.io/buthus/full/LdzMLj)
When you click on the "Demo" button, a line is added on image n°1 but you must close and open the image so that the line is visible in the data-caption.
Is it possible to refresh the contents of the data caption without closing and opening each time?
Thank you

**Comment by fancyapps** [comment]
Hi,

It is actually quite simple:


```JS
var fb = $.fancybox.getInstance();

  if ( fb ) {
    fb.current.opts.caption = sTextNew;

    fb.updateControls();
  }

```

Demo - https://codepen.io/anon/pen/RMjwzZ

**Comment by buthus** [comment]
Thank you! It's working perfectly.
