### ISSUE TITLE
Next image dont works when images uploaded by infinite-scroll

### ISSUE THREAD

**Issue by necromind** [fancyapps/fancybox#1897]
I use fancybox 3 and infinite sctoll. All works fine when i scroll all images down. But if i open 1 image and will press next buttons items that loaded by $infScroll.infiniteScroll('loadNextPage'); are on page, but at the end of current page next images will not open by next button. If close current popup and open again a can go next again before next page. Why dinamically added items not works by next button?

```javascript
$('.gallery').fancybox({
  selector : ".img-box",
...
,
  afterShow: function(instance, item){
      if (item.index  >=  instance.group.length - 10) {
        $infScroll.infiniteScroll('loadNextPage');
     }
  }
});
```

**Comment by fancyapps** [comment]
Please, do not make duplicates here and on SO. 

Adding/removing items from the page would not automatically affect currently open fancybox gallery. You would need to update gallery manually -

```JS
// Call `createGroup` with collection of fresh links 
$.fancybox.getInstance().createGroup( $('.img-box')  );

// Update controls
$.fancybox.getInstance().updateControls();
```
