### ISSUE TITLE
Multiple links for one image/video

### ISSUE THREAD

**Issue by TommySchurzmannEllerhold** [fancyapps/fancybox#1899]
Is it possible to have multiple links for the same video/image?

When i try to create multiple links with the same 'href', fancybox also create two thumbnails (for each link) in the lightbox, but i only want to have one thumbnail.

`<a href="image123.jpg" data-fancybox="video">Link1</a>`
`<a href="image123.jpg" data-fancybox="video">Link2</a>`

https://codepen.io/anon/pen/rdJZgN?editors=1100

**Comment by fancyapps** [comment]
This will be possible starting from v3.3, see the last example here - https://codepen.io/fancyapps/pen/VyLOJX?editors=1010

**Comment by stephiescastle** [comment]
can data-trigger open the gallery starting on a specific slide?

**Comment by stephiescastle** [comment]
Ah.. and I just found the answer here: https://fancyapps.com/fancybox/3/docs/
`data-index` is the way for those that have the same q
