### ISSUE TITLE
Fancybox "margin" option

### ISSUE THREAD

**Issue by on6qd** [fancyapps/fancybox#1900]
The doc states that the "margin" option is ignored for viewports smaller than 800px

_"Space around image, ignored if zoomed-in or viewport width is smaller than 800px"_

However, margin is used on devices with a smaller viewport.

See website www.joaosantos.be for an example.

**Comment by fancyapps** [comment]
Try setting `mobile: { margin : 0 }`

btw, "margin" option will be dropped starting from v3.3.
