### ISSUE TITLE
Keyboard navigation for zoom

### ISSUE THREAD

**Issue by madeckel** [fancyapps/fancybox#1901]
I would like to suggest to have keyboard navigation also for zoom in/out and an option not just "keyboard : true," but also for choosing if and what keys are used for next/close/zoom etc.  In Fancybox 2 it was possible I think.

**Comment by fancyapps** [comment]
Hi,

Yes, it was possible, but that was totally an overkill. Well, if enough people would ask for this, then it might be brought back, but, since you are the first person who mentions this (in more than a year), I highly doubt...
