### ISSUE TITLE
Alternate share URL for videos (or inline content)

### ISSUE THREAD

**Issue by MarkoD** [fancyapps/fancybox#1904]
Using v3.3, In case of the hidden ```<video>``` element, is it possible to override the URL used in the share dialog? Because the URL it uses by default is just the anchor link:

```#myVideo```

Is it possible to use the source URL of the ```<video>``` element, such as:

```https://www.html5rocks.com/en/tutorials/video/basics/Chrome_ImF.mp4```

Link to CodePen: https://codepen.io/anon/pen/oqPezE?editors=1010

Note: Hash module is disabled.

**Comment by fancyapps** [comment]
Hi,

Please, upgrade to the latest (v3.3.1; cdnjs will update in a moment) and then use like this:

$('[data-fancybox]').fancybox({
  buttons : ['share', 'close'],
  hash : false,
  share : {
    url : function( instance, item ) {
      if (item.type === 'inline' && item.contentType === 'video') {
        return item.$content.find('source:first').attr('src');
      }
      
      return item.src;
    }
  }
});


Demo - https://codepen.io/fancyapps/pen/BrOqmQ?editors=1010

**Comment by MarkoD** [comment]
Great, thanks for the prompt response!

**Comment by MarkoD** [comment]
Thanks for the quick response! I've downloaded the latest .js and .css files from ```master``` and when I try it, I get an error in the debug console when I click on the share button:

```TypeError: current.opts.share.tpl is undefined (jquery.fancybox.js, line 4868, col 5)```

**Comment by fancyapps** [comment]
And I am quite surprised about that. As you can see, it works fine on codepen and I even created a quick demo on jsfiddle - https://jsfiddle.net/x6koauxs/1/
So, the question is - what is so different on your page that is causing this issue?

**Comment by MarkoD** [comment]
I've found the issue - I'm overriding the default settings via:

```javascript
$.fancybox.defaults.share = {
    url : function( instance, item ) {
      if (item.type === "inline" && item.contentType === "video") return item.$content.find("source:first").attr("src");
      else return item.src;
    }
};
```
It seems that's the problem. Everything works if you omit this code: https://codepen.io/anon/pen/jzvgaP?editors=1010

I've debugged the code and the custom ```url``` function gets called and returns the correct value, so I've figured I don't have a typo and have initialized fancybox correctly.

**Comment by fancyapps** [comment]
Oh, I see. You have to extend defaults, like this - 

```JS
  $.extend(true, $.fancybox.defaults, {
    share: {
      url: function(instance, item) {
        if (item.type === "inline" && item.contentType === "video") {
          return item.$content.find("source:first").attr("src");
        }

        return item.src;
      }
    }
  });
```

(or you would break any option that contains multiple values)

**Comment by MarkoD** [comment]
Thank you very much, it works now! I'm no JQuery expert, so when I set the default settings, all multi-option values I omit will get broken or cancelled?

**Comment by fancyapps** [comment]
This is actually not related to jQuery. 

For example, when you have object 
`var defaults = { share : { url : 'aaa', tpl : 'bbb' } }`
and you set 
`defaults.share = { url : 'ccc' }` 
then you replace share object with the new one and, obviously, you loose
`defaults.share.tpl`

**Comment by MarkoD** [comment]
That makes sense, thanks and keep up the great work!
