### ISSUE TITLE
Disable closing if variable is set?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1906]
I want to disable the ability to close the fancybox if a variable is set to true. How can I do that?

I need it because I have a form field that the user can fill out, and on blur I check if it's filled out correctly. If the user clicks on the fancybox background to close the fancybox it's to late to give an error message. I guess a simple `if( $('#form-field').is(":focus") ) { // disable closing }` could work somewhere?

Thanks!

///Edit On a second thought I guess the focus will be lost by the time the fancybox background/close button has been clicked. Hmm. Ideas?

**Comment by seabasss** [comment]
Ok, I figured out one solution, but how can I make it prettier?

If my input check returns false:
`$('#input').closest('.fancybox-container').addClass('disable-close');`

`beforeClose: function(instance, slide) {
	if( $('.disable-close').length ) { return false; }
}`

**Comment by fancyapps** [comment]
You are correct about using `beforeClose` callback - returning `false` will prevent closing. 

How to make it prettier? Well, you could do something like this - 

1) Create somewhere a method for validation, like -

```JS
var isFormValid( $form ) {
   return check_something ? true : false;
} 
```

2) Then use `beforeClose` callback like this:

```JS
beforeClose: function(instance, slide) {
    return isFormValid( slide.$content ); // slide.$content will be your inline element
}
```
