### ISSUE TITLE
Fancybox with call Infinite scroll

### ISSUE THREAD

**Issue by ieraora** [fancyapps/fancybox#1914]
Hi Jānis, In this example https://codepen.io/ieraora/pen/wmQOxr I have [Infinite scroll](https://infinite-scroll.com/) with Fancybox. The "first page" has 18 images. If I start Fancybox before launch the second page, fancybox stop at the 18° image. It's a way to call infinite scroll, and than continue view the other images in fancybox?
Thank you.

**Comment by fancyapps** [comment]
Hi.

See https://fancyapps.com/fancybox/3/docs/#usage there you will find example about using `selector` option.
