### ISSUE TITLE
Buttons are too large

### ISSUE THREAD

**Issue by ygoe** [fancyapps/fancybox#1915]
The button labels in the zoom view are larger than the highlight area when hovering the buttons with the mouse cursor. That looks weird. They're really large anyway.

![fancybox-buttons](https://user-images.githubusercontent.com/868315/38769582-86b83020-4005-11e8-90a2-362c8a957191.png)

Version 3.3.5, Firefox 59, Windows 10

**Comment by ygoe** [comment]
Suggested fix:

Add this to your CSS:

```
.fancybox-button
{
    min-width: 0;
}
```

**Comment by fancyapps** [comment]
I assume that you have some CSS conflict on your page and since you have not provided link to your page, I am not able to help you.
