### ISSUE TITLE
next & prev arrows are gigantic

### ISSUE THREAD

**Issue by lljooo** [fancyapps/fancybox#1916]
I just tried Fancybox today, so I'm not used to it. But I can't get the next/prev arrows in a normal size - they're actually crazy big. After several hours I still haven't figured out what I'm doing wrong.

This is what it looks like:

https://byjohan.se/Bootstrap/metal-sculptures-pure.html

Thanks in advance,

//Johan

**Comment by fancyapps** [comment]
Hi,

You have forgotten to include CSS file.

**Comment by lljooo** [comment]
Ah, thanks! I renamed it a few hours ago and never remembered to change it back. Again, thanks :)
