### ISSUE TITLE
Multiple Galleries

### ISSUE THREAD

**Issue by kenanc50** [fancyapps/fancybox#1919]
I would like to have more than 1 thumbnail that lead to different galleries (that are not displayed on the page) within each thumbnail. 

Is this possible?

**Comment by fancyapps** [comment]
Hi,

There is a demo (fom the docs) that contains an example - https://codepen.io/fancyapps/pen/BOoGvQ?editors=1000 (basically, you can just put the rest of the images in the hidden container).
