### ISSUE TITLE
Fullscreen shows up on unsupported devices, when the template is customized

### ISSUE THREAD

**Issue by stanvass** [fancyapps/fancybox#1920]
The full-screen button shows up on unsupported devices, when the template is customized. This happens because of this code most likely:

```
  // If browser does not have Full Screen API, then simply unset default button template and stop
  if (!fn) {
    if ($ && $.fancybox) {
      $.fancybox.defaults.btnTpl.fullScreen = false;
    }

    return;
  }
```

Instead of detecting full-screen when rendering, or setting a flag, this code unsets the default template. But if you customize the template, then the default is not considered, and the button always gets rendered.

**Comment by fancyapps** [comment]
Hi,

This has been fixed in the latest version (v3.4.1). Thanks!
