### ISSUE TITLE
Arrow buttons not vertically centered

### ISSUE THREAD

**Issue by stanvass** [fancyapps/fancybox#1921]
The arrow buttons are not vertically centered. This is because they're positioned with "top: 50%", without taking into account their height (positioning is from the top edge of the object). So with height 38px, to center them, the CSS should say "top: calc(50% - 38px / 2);"

**Comment by fancyapps** [comment]
Hi,

The idea was that arrows are centered between toolbar and bottom of the page. But I have taken into account your suggestion and updated the css.
