### ISSUE TITLE
Blurry SVG icons due to non-1:1 vector art mapping

### ISSUE THREAD

**Issue by stanvass** [fancyapps/fancybox#1922]
All the icons appear blurry on desktop devices (which have 1:1 physical to logical ratio, so blurry rendering is especially visible). 

This happens because while all icons have a viewport of 40px/40px but they're rendered on top at 24px/24px in the toolbar, and I think 22px for the arrows.  The art should be remastered for the exact logical pixel rendering size and the viewports should match.

**Comment by fancyapps** [comment]
I do not think that SVG works this way.

**Comment by stanvass** [comment]
@fancyapps I replaced the code locally so the viewport is 24px (in CSS and HTML etc.) and I get pixel perfect results, and your default out-of-the-box icons are blurry on any desktop you can try it on.

When you say "I do not thing that SVG works this way" I'm not sure what you're referring to. But the simple result is: your icons are blurry; after the fix I proposed up there, the icons are not blurry.

**Comment by stanvass** [comment]
@fancyapps Here's an image demonstrating the difference: https://imgur.com/vT00uYW

Notice on straight horizontal/vertical lines, mine (on right) are pixel perfect, no dark/blurry lines. Yours (left) always have fuzzy edges.

Also notice your arrow buttons are not vertically centered, which is another issue I reported separately (and fixed locally).

**Comment by fancyapps** [comment]
Thanks for your effort. Ty changing a) browser zoom settings; b) display scaling (for example, I prefer 125%) - does it look OK? When I was working on the redesign, I could not found perfect solution to make icons look sharp on all possible cases.

**Comment by stanvass** [comment]
The secret to making them sharp on desktops is what I said: make the viewport size (in SVG) match the display size (in CSS) and design by snapping to pixels (say in Illustrator you have a very convenient option for it). I redesigned the icons for myself using my own advice for a site, and it looks sharp on desktop now (at 100% scale). Of course if you zoom in/out on your desktop, it won't be pixel perfect, but most commonly people see sites at 100%. And on mobiles it's always sharp as they have a very high res display anyway.
