### ISSUE TITLE
Keyboard "Enter" closes fancybox instead of submitting <form>

### ISSUE THREAD

**Issue by RiccardoB** [fancyapps/fancybox#1925]
I’m inserting a form in fancybox (3.3.5) using the type "html", but when I have the focus on a form element and click the keyboard "Enter", the fancybox closes itself instead of submitting the form (I checked the onSubmit event).

I don’t want to fully disable the keyboard actions because other actions like "Esc" are useful in my case; is it possible to customize fancybox keyboard actions?

**Comment by RiccardoB** [comment]
I solved my issue directly adding the `type="button"` to the Fancybox close button in `jquery.fancybox.min.js`, by the way I won’t send a pull because I actually don’t know if this could break something else.

**Comment by fancyapps** [comment]
Hi,

Looks like this has been fixed some time ago. Sorry about that.
