### ISSUE TITLE
Explain please the changes in the latest version (question)

### ISSUE THREAD

**Issue by 7iomka** [fancyapps/fancybox#1926]
Hello!
On all touch devices at the moment on the body element is not hung overflow: hidden, in this regard, the user can still scroll the body of the site while in the content of the modal window. However, after it is closed, the page scrolls until its previous state.
Is this behavior ok? I think this is done for reasons of cross-browser compatibility (including for iOS-devices with their problems with fixed positioning)?
I have updated to the latest version and am experiencing a number of problems with innovations that can not be read anywhere.
For example: `.fancybox-slide: before `- why this pseudo-element is given
   ```
 display: inline-block;
    height: 100%;
```
?
And the first child of the element with the class ` fancybox-slide fancybox-slide-html fancybox-slide-current fancybox-slide-complete` specifies an inline style property display: `inline-block`? First of all, this requires that all my content be located inside another wrapper if I want something like flex / inline-flex (without using `!important`, of course).
On one of the breakpoints, I observe a behavior in which a pseudo-element does not fit with a child, so that the content of my modal window is 100% below the entire height of the screen.
Maybe I'm doing something wrong?
Thanks!

**Comment by fancyapps** [comment]
Hi,

Are you sure you are using the latest version?

That code is for vertical centering, there is still no better solution for that (including flexbox).

**Comment by 7iomka** [comment]
@fancyapps , Yes: 
`"@fancyapps/fancybox": "^3.3.5"`
What do you say about the scrolling issue? The situation is observed in the official demo on codepen.
