### ISSUE TITLE
Add watermark to all images with specified ID or class

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1929]
Hi, si possible to add a watermark into all images that contains specific ID or class opened via FancyBox? Thank you very much!

**Comment by fancyapps** [comment]
Hi,

See this demo - https://codepen.io/fancyapps/pen/wmXOqN - watermark image is applied using CSS for slides that have corresponding class name.

**Comment by fancyapps** [comment]
There is no special section for tutorials, but documentation contains a number of demos - https://fancyapps.com/fancybox/3/docs/#images

**Comment by Eldenroot** [comment]
Maybe would be nice to make something like: other useful tutorials and add links for these... because your Fancybox is just perfect! :) Thank you!

**Comment by Eldenroot** [comment]
I am getting a hard times to add my watermark image (100x200px) only to the right bottom corner :( I tried position property but without any success. If you will have a minute, could you please help me? Thank you

**Comment by fancyapps** [comment]
Hard times? But why? `background-position: bottom right;` should do that, example:

https://codepen.io/anon/pen/pVKXBa

**Comment by Eldenroot** [comment]
@fancyapps - you are a genius, thank you very much. Just last thing - where to put code for preload image? I use this in my page - pastebin - https://pastebin.com/k4Qi3VcB

Thank you very much for great support!

**Comment by Eldenroot** [comment]
Unfortunately not working, watermark is not added :( afterLoad is not firing :(

**Comment by fancyapps** [comment]
Well, make sure you use valid selector, e.g, if you write `$('.something').fancybox(...)` then check if `$('.something')` returns your elements. If not, then defaults will be applied.

**Comment by Eldenroot** [comment]
@fancyapps - I dont get it srry. Still cannot figure it out.

I use this code on my webpage:
https://pastebin.com/nWnS3veZ

Where to exactly place and how it should look like when I wanna apply this to $('[data-fancybox="images watermark"]').fancybox({ - thank you!

**Comment by fancyapps** [comment]
Did you check if `$('[data-fancybox="images watermark"]')` returns anything? I suspect that it would return 0 items, because you have a space there.

**Comment by Eldenroot** [comment]
I use this CSS for watermarks

`/** FancyBox CSS code, úprava rozložení prohlížeče **/
.fancybox-caption {
	text-align: left !important;
}

/** FancyBox - vodotisk - watermark **/
.fancybox-slide.watermark .fancybox-spaceball {
	background-image: url('/wiki/watermark_forum.png');
	background-size: 300px 70px;
	background-position: bottom right;
	background-repeat: no-repeat;
	opacity: 0.50;
}

/** FancyBox - vodotisk - hide while scaling (zooming in/out) **/
.fancybox-is-scaling .fancybox-spaceball {
	background-image: none !important;
}`

**Comment by acwolff** [comment]
With my [jAlbum Fancybox skin](https://jalbum.net/en/skins/skin/FancyBox) you can show a watermark without any programming as you can see in [this example album](https://andrewolff.jalbum.net/FancyBoxWeb/).

**Comment by Eldenroot** [comment]
I wanna use stock FancyBox because I like it and I have been using it since the fist version :) I just need to someone Js skilled who can help me to get it work, thank you!

**Comment by fancyapps** [comment]
@Eldenroot I really do not know what to say... I asked you two questions and you did not answer to any of them. Also, I really have no idea why you (and other people) post (partial) source code - it is totally useless.

**Comment by Eldenroot** [comment]
@fancyapps - please dont be rude, I just kindly asked for a small help from your side - I have no other issues, just this one (I have tried a lot of approaches but without any success). Anyway, I will try to find out the solution during this weekend, thank you for your input and I am sorry for my question :(

**Comment by fancyapps** [comment]
Oh, man, if you would have given a link to your page or some demo, I believe I would have provided an answer in no time.

**Comment by acwolff** [comment]
@fancyapps I think you mean me with your remark “ (and other people)”, so I am sorry top for my remark.

I did sent you an e-mail, but I am not sure I used the correct e-mail adres.

**Comment by Eldenroot** [comment]
I use this code, it works fine when I use it on Codepen:
https://codepen.io/anon/pen/NexQGa

When I combine all my JS together and use 2 classes for FancyBox - it works fine too:
https://codepen.io/anon/pen/WLrVpM

However when I use it on my site (when I add afterload), FancyBox works but my custom setting is not loaded. Without afterload works fine, code is identical :(

**Comment by fancyapps** [comment]
The code looks OK and it works on codepen, so .. there must be some difference. Without seeing your page, where I could inspect your issue, I can only think of two possible causes:

1) You forgot to include your code inside `$(document).ready(function() { });` 
2) You have some JS error on your page (any JS error can break something else)

Or maybe you forgot to add `data-fancybox="watermark"` to your links?

I hope you understand that I just can not give you proper answer, it is just not possible.

**Comment by Eldenroot** [comment]
1) nope, it is included
2) no JS errors

Even translations added in my custom setting are not loaded (afterload code added, without afterload works fine). I will try to debug i and let you know during tommorow. There must be a typo in my code or I am missing something.
