### ISSUE TITLE
Label doesn't work

### ISSUE THREAD

**Issue by TAVENIER-Gabriel** [fancyapps/fancybox#1937]
Hello, 

thanks for fancybox, it's really good script.
I have a little problem, I put a form in a fancybox and the labels doesn't work anymore. If the form is outside of the fancybox labels works fine.
The labels are for input radio button. Labels for input text works great !

Have you a idea ?

PS : Excuse my english, I am French...

**Comment by fancyapps** [comment]
Hi.

I guess you need to disable touch events, so, either add `data-selectable="true"` to your form elements or add `data-touch="false"` to your links (this will completely disable touch events).

**Comment by TAVENIER-Gabriel** [comment]
Thanks for your answer.

I tried to add `data-selectable="true"` on my label -> `<label for="mister" data-selectable="true">` but it doesn't work. I also tried to add `data-touch="false"` on my link -> `<a href="" data-fancybox data-src="#popin-recall" data-touch="false">` with no success.

**Comment by fancyapps** [comment]
I wish you would create a simple demo, then I could easily see your issue and could promptly help. You can fork any demo on codepen (there are a plenty of demos on docs) or create using jsfiddle.

**Comment by TAVENIER-Gabriel** [comment]
In fact  I have 2 forms in my page with same id on my radio button.
If I fork a codepen demo it works ! [codepen](https://codepen.io/Gaby22/pen/WJPaGG)
But If I do the same thing in my web page it does'nt work ! I can't select radio with the label and if I select a radio on the first form it will be selected too an the second form... [my page](http://divers.korriganedpanvrid.fr/test-fancybox/)
I don't understand why it works on codepen and not on my page.

**Comment by fancyapps** [comment]
Labels for perfectly fine. 

The problem in your example is that you have two forms on the same page and those forms have elements having identical "id" values, e.g.,, you have two 

`<input type="radio" id="monsieur" name="civilite" value="monsieur" />` 

elements on your page. Therefore browser does not know what label to select and .. does nothing.
