### ISSUE TITLE
Option to copy img attributes to thumbnails

### ISSUE THREAD

**Issue by kieliszek85** [fancyapps/fancybox#1939]
It would be really nice, if fancy copies other img attributes (not only src).
It would allow using lazy loading scripts for cases where not all images are loaded (visible at screen at the moment) and web user wants to show thumbnails in fancy.
For example we have fancy images, that are not visible at the moment:
<a ... rel=fancybox>
<img src="/loading.gif" data-src/data-original="/some-image.jpg" />
</a>
User opens fancy by clicking other img (which is visible) and then he clicks button to show thumbs from the gallery.
In thumbnails only src attrbiute is copied and then user see just "loading" thumbnails with no data to actually load them.

**Comment by fancyapps** [comment]
Hi,

Sorry, I tried, but could not understand your comment. Are you looking for alternative way to set thumbnail source? Then use `data-thumb` attribute. See https://codepen.io/fancyapps/pen/VyLOJX?editors=1000
