### ISSUE TITLE
iframe popups without scrollbars have too much padding at bottom

### ISSUE THREAD

**Issue by acabal** [fancyapps/fancyBox#194]
Using the Fancybox source from 2012-03-21, If I open up a Fancybox popup with an iframe that isn't big enough for scrollbars, the height of the iframe is set too large.  The result is extra padding in the bottom border: the correct padding for the popup border set in the options, plus the extra padding added to the iframe height.  

I traced the problem to line 877 in the code, where + 12 is added to the height of the iframe.  Maybe this is to compensate for horizontal scrollbars, but when they aren't present, it adds too much height and looks weird.  If I change it to + 2 instead of + 12, the problem seems to go away without any immediately noticeable side-effects.  (Setting it to + 0 seems to cut off a few pixels of the iframe for some reason.)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
