### ISSUE TITLE
Full width zoom for very tall images

### ISSUE THREAD

**Issue by tsarevpp** [fancyapps/fancybox#1943]
Hello, I want to implement fancybox with my admin system and I have some documents (mostly about 2 pages) that are stacked and saved as tall images. I want to display them with fancybox and to be able to zoom them to full width. There isn't an option to do this currently. The zoom for me shows 3/4 of the image width when i zoom in. Is there a way to do this or maybe this could be a future in the next release? :) 
Thanks!

**Comment by fancyapps** [comment]
Duplicate of #1343

**Comment by tsarevpp** [comment]
@fancyapps Did you read the whole post? The image is not properly zoomed.

**Comment by fancyapps** [comment]
Hmm, sorry, could you provide some demo?
