### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by AntonLev89** [fancyapps/fancybox#1945]
Hey. If I buy a commercial license and will develop products with your plugin. After the completion of the work - I will give the project to the customer. QUESTION - whether the customer should buy your license - so that he can use the site ordered from me? Or he will need to buy a license only if he wants to upgrade the version?

**Comment by fancyapps** [comment]
Hi,

There is no need for your customer to purchase another license, except when upgrading to next major version (e.g., from v3 to v4).
