### ISSUE TITLE
Edge Browser, IE Browser, loading issue?

### ISSUE THREAD

**Issue by sun4all** [fancyapps/fancybox#1946]
Hi, folks. I am testing "fancybox 3" on a Win10 - offline, used a 2.5 version before.
Fancybox 3 tested with Chrome, Firefox, Edge and IE. I have thumbnails, grouped with 
data-fancybox="my_name_whatever", and by clicking them, they (should) open in fancybox. In Edge and IE, after the second image, clicked with the "forward"-button, I see the message "The requested content cannot be loaded. Please try again later." This does not happen with Chrome and Firefox for Windows, working properly. My old 2.5 version of "fancybox" works fine with Chrome, Firefox, IE and Edge, regarding this issue.

**Comment by fancyapps** [comment]
Hi,

I do not see any issue.
