### ISSUE TITLE
youtube-nocookie.com not used

### ISSUE THREAD

**Issue by vollyimnetz** [fancyapps/fancybox#1949]
Hi, i use facebox 3 to display youtube videos.
Cause of the current hype about privacy my customers want to use the www.youtube-nocookie.com domain for youtube videos. But fancybox will always open the page with www.youtube.com

How to fix?

https://codepen.io/anon/pen/ZRGpje

**Comment by grimmcreative** [comment]
Just have a look at the fancybox.media.js file. There you will find:

`url  : '//www.youtube.com/embed/$3'`

change it to nocookie domain.

**Comment by vollyimnetz** [comment]
Its ok for me to change the source for one project.

But if one use webpack/gulp (any other build tool), or have some more pages, then there is a need to have this in the settings or to autorecocnize the domain.

**Comment by vollyimnetz** [comment]
Perfect, thank you very much.

**Comment by Patta** [comment]
@grimmcreative it's not working. the url is just added to the iframe src as a parameter.

**Comment by fancyapps** [comment]
The correct syntax would be like this - 

```JS
$('[data-fancybox]').fancybox({
  media : {
    youtube : {
      url: "//www.youtube-nocookie.com/embed/$4"
    }
  }
});
```

Demo - https://codepen.io/anon/pen/vryWRV?editors=1010

`media` option is used to pass options to `media` module and `youtube` option is just a shortcut to quickly change url parameters.

**Comment by fancyapps** [comment]
Use this on your own responsibility! According to whois.net, this domain belongs to some marketing agency. If you are concerned about privacy and security (and you should be), I would not recommend to embed code from unknown 3rd party site.

**Comment by Patta** [comment]
@fancyapps Thanks. I added a PR for this, but after your help you can close it :)

**Comment by vollyimnetz** [comment]
If you are on youtube and try to get the embed for a videos, you can click the checkbox for extended privacy. Youtube will then change the domain for the embed to https://www.youtube-nocookie.com - so i think, at least for Youtube its the official way.

**Comment by fancyapps** [comment]
Thanks, I really did not know that. It is strange that there is zero information on the internet about this feature.

**Comment by nebrot** [comment]
@fancyapps The above syntax-example is working. Is it also possible to set **defaults** for youtube-url? It's not working with:
`$.fancybox.defaults.media.youtube.url = "https://www.youtube-nocookie.com/embed/$4";`
OR
`$.fancybox.defaults.youtube.url = "https://www.youtube-nocookie.com/embed/$4";`

This error is triggered:
`TypeError: $.fancybox.defaults.media.youtube is undefined`

**Comment by fancyapps** [comment]
@nebrot It is currently, not possible. Thanks for the idea, it will be implemented in the next update.

**Comment by fancyapps** [comment]
@nebrot 

btw, it would work like this:

`$.fancybox.defaults.media.youtube = { url : "https://www.youtube-nocookie.com/embed/$4" }`

https://codepen.io/anon/pen/QBXNxJ?editors=1010

**Comment by nebrot** [comment]
@fancyapps Yes, this works. Thx!
