### ISSUE TITLE
Animations/Transitions not working on fancybox 3.3.5 and internet explorer (tested on ie 11)

### ISSUE THREAD

**Issue by ivoduarte** [fancyapps/fancybox#1950]
Hi

I´ve noticed that animations/transitions are not working on internet explorer (works well in chrome, edge and Firefox), i´ve tried several options with no success. I´m using the lastest version of fancybox (3.3.5) and also the latest version of jquery (3.3.1), i´m allways testing it on the webserver. I´ve noticed that with data-type="iframe" animations work (lack of some functionality for images), but not with images.

Is there anything that can be done to solve this problem?

Thanks

Ivo Duarte

**Comment by MarkoD** [comment]
I've tried the same setup and animations work okay. Could you provide a JSFiddle or Codepen example?

**Comment by ivoduarte** [comment]
Hi MakroD

Thanks for your interest in answering my question, you can simply go to the developers page https://fancyapps.com/fancybox/3/ and try those images there, on browsers like edge, chrome, firefox they work well, the zoom in and and zoom out works, and also if you drag the images left or right they do a smooth transition, but with internet explorer (IE 11) they simply don´t zoom in nor out, and the transitions when you drag images left or right look awful.

This codepen exemple using Fancybox 3.0.47 works well even on internet explorer https://codepen.io/kushelbek/pen/QvGexw

This one https://codepen.io/fancyapps/pen/MOEXmJ using 3.2.11 does not work well in IE 11, it zooms in but does not zoom out and the transitions are awful, but works well in the other browsers mentioned.

Best regards,

Ivo Duarte

**Comment by ivoduarte** [comment]
Hi

Hummmmm interesting, looks like it has something to do with IE´s version, i´m using IE 11.48.17134.0 Update Version 11.0.65 (KB4103768) on 2 different machines and nor the animations  nor the transitions work well on IE, the windows 10 build is 1803. The odd thing is that Fancybox 3.0.47 works well in this version of IE, to sum it up, it looks like there is a problem with Fancibox versions 3.1x and above and this version of IE. It must have been some new implementation on Fancybox that does not work well in this version of IE.

the problem is finding what is causing the problem??? (maybe the developer could help us sort it out!!!)

Thanks again for your interest

Ivo Duarte

**Comment by fancyapps** [comment]
I would love to help, but the problem is that I can not reproduce this issue, works fine on all machines I have :confused:

**Comment by MarkoD** [comment]
I've also tried IE 11.0.9600.19002, update versions 11.0.60 (KB4103768), which is the latest version for Windows 7, and everything works okay.

Maybe it has to do something with video drivers? Try switching your IE between HW and SW rendering?

**Comment by ivoduarte** [comment]
Hi Jānis

Excellent work you have here, don´t get me wrong in any way, i´m just trying to sort this out, I've made a video with the issue, i´ll put here the we-transfer link, it´s only 50Mb, so that you guys can take a look, if and when you can of course, here it is -> https://we.tl/kPhblJ6x4C

As MarkoD suggested I've already tried disabled and enabled hardware acceleration/redering in IE before with no success in any case.

Thanks again,

Ivo Duarte

**Comment by MarkoD** [comment]
I'm no expert in CSS, so the only thing I would suggest is to compare the working fancybox.css vs the newest fancybox.css and hopefully you'll figure something out.

**Comment by fancyapps** [comment]
Oh, wow, I am so sorry, all this time I looked at my test website and it works fine, but yes, I can clearly see this issue on codepen demo. I'll take a look to see what is causing this.

**Comment by ivoduarte** [comment]
I´m no expert either, i´m just trying to figure this out, but it is extremely difficult without knowing what to look for. Before asking the question here I've already researched the web for the issue with no success, I also tried to compare both scripts, but they are just to big for me to figure it out, I did not try to compare the CSS files, maybe the issue resides there, i´ll give it a try. Thanks for the suggestion.

I´ve also tried all animations/transitions, they all have the same problem, they simply don´t work in IE 11 (my version), by the way i´m testing it with version 3.3.5 of Fancybox and Jquery 3.3.1 as stated before.

Thanks for your availability and excellent work Jãnis, if you need anything from me, just ask.

Best regards,

Ivo Duarte

**Comment by ivoduarte** [comment]
Hello just to give you update on this thread, it just occurred to me that if it works with iframe type why doesn´t it also work with images, it turns out to be an option of overflow: visible; on this part of the CSS...

`.fancybox-slide--image .fancybox-content {
  -webkit-animation-timing-function: cubic-bezier(0.5, 0, 0.14, 1);
  animation-timing-function: cubic-bezier(0.5, 0, 0.14, 1);
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  background: transparent;
  background-repeat: no-repeat;
  background-size: 100% 100%;
  left: 0;
  margin: 0;
  max-width: none;
**/*overflow: visible;*/**
  padding: 0;
  position: absolute;
  top: 0;
  -webkit-transform-origin: top left;
  -ms-transform-origin: top left;
  transform-origin: top left;
  transition-property: opacity, -webkit-transform;
  transition-property: transform, opacity;
  transition-property: transform, opacity, -webkit-transform;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  z-index: 99995; }`

You just have to remove comment it and it will work on all browsers (at least in the ones I mentioned above)

Best regards,

Ivo Duarte
