### ISSUE TITLE
parent parameters DOES NOT work

### ISSUE THREAD

**Issue by NuclearMachine** [fancyapps/fancybox#1952]
I have a div with a #main-content id. It always sets to body even though it has "#main-content" as a parent parameter

```
$(".fancybox").fancybox({
    parent: "#main-content" 
});
```

**Comment by fancyapps** [comment]
Hi,

Try using `parentEl` option.

**Comment by NuclearMachine** [comment]
your correct. I was checking the old documents (http://fancyapps.com/fancybox/#docs) for version 2. Didn't help that stack-overflow recommended to use parent. Thanks.
