### ISSUE TITLE
Remove controls for self-hosted mp4 video

### ISSUE THREAD

**Issue by SoldierCorp** [fancyapps/fancybox#1953]
Hi,

I am using the plugin to show a video from my own server and it's working but I need to remove the controls and with loop true but the configuration I an using it's not working, do you know why?

This is the html

    <a class="how__video" data-fancybox href="/assets/videos/my-video.mp4">
        <img class="how__video--play">
    </a>

This is the js

      $('[data-fancybox]').fancybox({
          loop: true,
          buttons: [
            "fullscreen",
            "close"
          ],
          video: {
            controls: 0
          }
        });

**Comment by MarkoD** [comment]
The ```loop``` function is not for looping videos, but the whole presentation. Likewise, the ```controls``` option is not valid for videos in the fancybox config and has no effect.

You can achieve what you want with an inline ```<video>``` element, here's a CodePen I've modified that does what you want: https://codepen.io/anon/pen/QxGKvv?editors=1010

**Comment by fancyapps** [comment]
Hi,

There is now a `video` option that you can use to customize template for html5 videos, defaults:

```JS
video: {
  tpl:
    '<video class="fancybox-video" controls controlsList="nodownload">' +
    '<source src="{{src}}" type="{{format}}" />' +
    "Your browser doesn't support HTML5 video" +
    "</video>",
  format: "", // custom video format
  autoStart: true
}
```

**Comment by MoraSasan** [comment]
Hi,
Thank you for this great work.

I am just wondering where this should go? Is this is a CSS? or JS?
Can you share an example?

Also, is there any way to remove _controls_ without specifying any single videos in src?

Thanks!
