### ISSUE TITLE
Arrow position over image

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1956]
Hi. Is there an option to set arrow position over image?

An example:
![image](https://user-images.githubusercontent.com/1315340/41109203-b2be95ec-6a76-11e8-8085-fb20ffc135be.png)

**Comment by fancyapps** [comment]
Hi,

There is no such option, but if you miss traditional design, then take a look at this demo - https://codepen.io/fancyapps/full/BrxwqO
