### ISSUE TITLE
Thumbnails blank if image filename has a space in it

### ISSUE THREAD

**Issue by JizzyBob** [fancyapps/fancybox#1957]
Having recently purchased and in testing the overall solution, I've found a little bug relating to thumbnails and filenames with spaces.  I know - don't have filenames with spaces, but user uploaded content etc etc.

The thumbnail sidebar fails to show an image with a space in the title, simply due to the fact that the thumbnails in the sidebar are being rendered as css background-images, which cannot tolerate spaces.

A quick replace of spaces with %20 when writing out the "background-image: url( )" should do the trick.

Thanks for the solution.  You've saved me a bunch of time!

**Comment by fancyapps** [comment]
Hi,

This should be taken care of on the server side. If you are, for example, using PHP, then you have to encode your links using this function - http://php.net/manual/en/function.rawurlencode.php

**Comment by JizzyBob** [comment]
Indeed, and the product I'm working on has already been updated to prevent spaces in images.
I still think it's worth addressing this within your code though, for the sake of belt and braces, so that someone else's un-escaped filenames don't manifest as a visual bug in your solution.
But of course, your code your call.

Thanks again.
