### ISSUE TITLE
Scrollbar width issue

### ISSUE THREAD

**Issue by Nic787** [fancyapps/fancybox#1958]
Hi,

When activating fancybox, it removes the scrollbar. That's a good idea, but since my width 100% depend of the scrollbar, when removing it, all my pictures are moving to take the new 100% width. Just annoying to see my page jump like that. Do you have any idea how to fixe that other than keeping the scrollbar?

Thank you

**Comment by fancyapps** [comment]
Hi,

If this does not help - https://fancyapps.com/fancybox/3/docs/#faq-1 - then try setting 

`$.fancybox.defaults.hideScrollbar = false;`

**Comment by Nic787** [comment]
Thank you, but it doesn't jump my fixed element. It make my image jump which are inline-block elements.

**Comment by fancyapps** [comment]
I guess that one of the parent elements is 100% wide and adding `compensate-for-scrollbar` classname would fix that issue. Since you did not provide any demo, I can only guess... (your comments do not help at at all; it does not matter if your elements are inline-block elements, block, rock or whatever).

**Comment by Nic787** [comment]
[project.zip](https://github.com/fancyapps/fancybox/files/2084837/project.zip)
Here is my project. Just open album page (you can find my page) and my js file is js/scripts.js and the little code you said me to add is at the end before the commented area (was testing stuff).

**Comment by acwolff** [comment]
@Nic787 you can make that project too with the [jAlbum FancyBox skin:](https://jalbum.net/en/skins/skin/FancyBox) see https://andrewolff.jalbum.net/Nicolas_Duclos_FB/
