### ISSUE TITLE
data trigger conflicts?

### ISSUE THREAD

**Issue by InkedCurtis** [fancyapps/fancybox#1962]
I'm currently using a custom file input ([Jasny FileInput](http://www.jasny.net/bootstrap/javascript/#fileinput-usage)) that needs the following:
```html
<div class="fileinput-preview fuzone" data-trigger="fileinput">
```

However this is opening a FancyBox Modal that says `[object Object]` what's the workaround?

**Comment by reveton** [comment]
Type this to your file
```
jQuery( document ).ready(function() {
    jQuery(document).off("click.fb-start", "[data-trigger]");
});
```

**Comment by reveton** [comment]
or $ instead jQuery

**Comment by fancyapps** [comment]
Hi,

I have taken into account your suggestions and renamed `data-trigger` attribute to `data-fancybox-trigger`. Thanks.
