### ISSUE TITLE
Clicking "next" too fast breaks inline box

### ISSUE THREAD

**Issue by tailoredanthony** [fancyapps/fancybox#1966]
Hi,

I have a page with some inline content I use for fancybox 3.3.5.  I set up the links like this:
`<a href="#" data-fancybox="groupname" data-type="inline" data-src="#box-1">Open Box 1</a>`

And set up the box content like this:
`<div style="display:none" id="box-1">...content...</div>`

It works, and I can click "next, next" to go through them.  I enabled Loop so it keeps going around.

However, if I go too fast (click next too fast, or hold down the arrow key), pretty soon the boxes stop loading.  I just see "The requested content cannot be loaded.  Please try again later." and have to refresh the page for it to work again.

I used the DOM inspector tool to see what happens to my boxes.  It seems like the first run through it removes the `id` attributes, and then as it loops it removes the element entirely.

If I disable the loop and hold down the arrow key, I see that the `id` attributes are removed, but they come back again once I release the arrow key.  I guess that with loop enabled, it starts over without restoring the IDs and thats when things break.

I hope that's helpful.  I'm not able to go through the code to see where/why this happens.

**Comment by fancyapps** [comment]
Hi,

This should be fixed in the latest version.

**Comment by fancyapps** [comment]
If you are using content type "inline", e.g., displaying existing dom element from the page, then you are not supposed to delete/replace that dom element or you will break the functionality. 

In your case, I do not see the reason for you to display some element from the page, you could simply add click event for each link that starts fancybox using API, e.g., `$.fancybox.open()`

**Comment by timdmackey** [comment]
Whoops, sorry I opened another issue on this because I saw that it was closed—I  didn't think anyone would see it!

**Comment by timdmackey** [comment]
Is there a suggested way to use javascript templating? My example is fairly trimmed down, but in reality I have a large number of products on a page, and I want to generate some moderately complex html for the lightbox without having to output the html for every one. My plan was to use a lodash template and provide each product's data as json data. That's where the inline element comes in—it's where I'm getting the json data from.

**Comment by timdmackey** [comment]
also, I'm modifying `slide.$content`, which i thought was a clone of the original DOM element, not a reference?

**Comment by fancyapps** [comment]
Here is a simple template system - https://codepen.io/anon/pen/zeOEdB?editors=1010

Yes, `slide.$content` is a reference to original DOM element for 'inline' content. 

In future, it is planned to extend functionality of `html` content type so that you could add `data-type="html"` and it would clone element instead of moving.

**Comment by timdmackey** [comment]
Ah, well that explains a lot of weird behavior I was experiencing! I definitely attempted to check that the element was being cloned, but I obviously misread things.

Thanks for the example, that is very helpful. I see the solution now that you were hinting at, which is to add all of the slides to a javascript array and then have my links open that fancybox instance with an index.

Thanks!
