### ISSUE TITLE
Separating attributes from grouping using data- ?

### ISSUE THREAD

**Issue by soupking** [fancyapps/fancybox#1967]
Hey everybody,

I've got a situation where I have a gallery of a 300x250, 160x600 and a 728x90 size banner.

I'm using data-fancybox to assign attributes to the 300x250 such as size. But I use data-fancybox to group assign slide/click through a gallery. But since they're a different size I can't group them.

How do I assign each unit it's own data-fancybox details/attributes and still group assign them with <- -> etc. without having to assign them all the same 300x250 data- ?

If anybody could help me sort this out I'd be ecstatic. 

Thanks for reading!

**Comment by fancyapps** [comment]
Hi,

You can set custom options individually - using `data-options` attribute or data attribute for each property like `data-width`.

See last example here - https://fancyapps.com/fancybox/3/docs/#options

**Comment by soupking** [comment]
Ah, excellent. Thank you!
