### ISSUE TITLE
JSFiddle Difficult to Download Samples to Examine

### ISSUE THREAD

**Issue by soupking** [fancyapps/fancybox#1970]
CodePen is really easy to download code bundles. For JSFiddle, I copy the code and use my own FB & Jquery JS referencing and cannot for the life of me get this basic tag/script to work from JSfiddle:

http://jsfiddle.net/T6NKD/

Does anybody have this 1-thumb gallery demo in a zip? I have managed to build out my entire portfolio using FancyBox but cannot get any JSFiddle to my desktop no matter how hard I try.

**Comment by soupking** [comment]
Nevermind, found a CodePen, thanks!

**Comment by soupking** [comment]
Also, there's no date in JSFiddle so I'm not quite sure if I'm examining 2.0 or 3.0 examples online.

**Comment by fancyapps** [comment]
That jsfiddle sample uses v2 and if you are looking for standalone demo, then there is one for v2 - http://fancyapps.com/fancybox/demo/

If you are wondering why your code does not work after copying it directly from JSFiddle, then the answer is quite simple - you are (most likely) hotlinking js and css files from fancybox homepage. And that is not allowed :) Therefore either download files on your server or use csdn - https://cdnjs.com/libraries/fancybox

**Comment by soupking** [comment]
Ah! That would explain things. Thank you for clarifying. :)
