### ISSUE TITLE
When I simulated the cell phone flip in chrome, the browser prompts this.

### ISSUE THREAD

**Issue by ghost** [fancyapps/fancybox#1972]
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
``` 
![2018-06-14 17-14-20](https://user-images.githubusercontent.com/39984533/41403088-9b1233c4-6ff6-11e8-9bd0-64af8a7fb342.png)

**Comment by fancyapps** [comment]
Hi,

Well, adding  `touch-action: manipulation` to `.fancybox-container` seems to resolve this warning.

**Comment by fancyapps** [comment]
Seems to be working fine with the latest version.
