### ISSUE TITLE
How to add an extra custom button?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#1973]
I need for my [jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) a button to show the location of the photo in Google Maps and perhaps another button to show the EXIF data of the photo.

The preferred position is on the info bar in the upper left corner, but is is also OK if the button(s) are added to the other buttons in the upper right corner.

What is the easiest way to implement extra buttons?
For each extra button I like to give as parameters, the svg button image and the javascript function to execute if the button is clicked.

Is there an easy way to implement this?
If not could that be added as a new feature?

**Comment by fancyapps** [comment]
See https://fancyapps.com/fancybox/3/docs/#faq-3

**Comment by acwolff** [comment]
Thanks for your fast response!

I had already a svg icon for my button and was confused by the svg codeblock in your example.

After some trails I could use the next code to implement my svg icon:
```
// Create templates for buttons
$.fancybox.defaults.btnTpl.exif = '<button data-fancybox-exif class="fancybox-button fancybox-button--exif" title="Show/Hide EXIF data (camera settings)">' +
'<img src="res/exif.svg"  class="roundbutton"  alt="Show/Hide EXIF data (camera settings)" title="Show/Hide EXIF data (camera settings)" onClick="javascript:toggleExif()">'  +
  '</button>';

 $('[data-fancybox="images"]').fancybox({
    buttons : [
    'zoom',
    'slideShow',
    'exif',
    'thumbs',
    'close'
  ]
}); 
```
See [here](https://andrewolff.jalbum.net/FB_JustifiedGallery/) for an album made with this extra button to show the camera information in the caption area.

Maybe this type of implementation is also usefully for other users of your library.

Thanks for sharing your awesome library!
