### ISSUE TITLE
Issue / Help Request for Flickr Videos

### ISSUE THREAD

**Issue by sayontan** [fancyapps/fancybox#1978]
Hi,
I am the author of a WordPress plugin called [Photonic](https://wordpress.org/plugins/photonic/). As a part of the plugin I keep adding support for popular lightbox scripts, and I already support the previous two versions of Fancybox. 

I was looking to add support for the Fancybox3 for the next version of the plugin, while adding support for videos to the plugin. Overall the script runs very smoothly and integrates well with a variety of scenarios. However I have been running up against issues when I try to play a video from Flickr (the plugin supports videos from Google, SmugMug and Zenfolio - those work fine). The issue with the Flickr videos is that they come from the server with a different type of "Content Disposition", which prompts to download the file instead of playing it, if directly accessed from a browser. Flickr returns two types of URLs - one without an explicitly defined "type" (e.g. https://www.flickr.com/photos/sayontan/42529984021/play/orig/978e3deb0f/), and the other linking to a Flash file (e.g. https://www.flickr.com/apps/video/stewart.swf?v=384028786&photo_id=42529984021&photo_secret=a0624d0a48). No matter which one I use, I cannot get the video to play. 

Here are the things I tried:

* I tried setting "data-type='video'" for both cases
* I tried setting "data-type='iframe'" for both cases

Should I be looking to play the SWF file via an inline element instead?

**Comment by fancyapps** [comment]
Hi,

Right now, media module is quite simple, it parses links to create embeddable code. I think that oEmbed API (https://oembed.com/) would be needed to correctly embed content from flickr. 

If you wish, you could try to implement flickr support by yourself, there is a `objectNeedsType` callback that you could use to determine if link is pointing to flickr and to set custom content if needed (see https://github.com/fancyapps/fancybox/blob/master/src/js/media.js#L110 for sample).

**Comment by sayontan** [comment]
I got around this by creating an inline element with the video embedded, and it seems to work fine. So I am closing this.

**Comment by sayontan** [comment]
@acwolff - Sure. Take a look at the documentation for inline elements: https://fancyapps.com/fancybox/3/docs/#inline. All I did is that in the "hidden-content" div I put in the markup for a video:

`<video controls preload="none"><source src="http://link-to-video" type="video/mp4">Your browser does not support HTML5 videos.</video>`

That's all.

**Comment by acwolff** [comment]
@sayontan I tried this, in the thumbs gallery:

    <a data-fancybox="S" data-src="#hidden-content" href="javascript:;" data-caption= ''>
      <img src="thumbs/www.flickr.com-813.jpg" width="110" height="80"
     alt="Flickr video" title="5: www.flickr.com-813<br>" />
      <div class="caption">Flickr video</div>
    </a>

and as hidden element:

      <div style="display: none;" id="hidden-content">
       <video controls preload="none"><source 
    src="https://www.flickr.com/photos/warmandpowerful/5953412756" type="video/mp4">Your browser does not support HTML5 videos.</video>
    </div>

What do I wrongly?

**Comment by sayontan** [comment]
I didn't use the `data-src` attribute at all. Instead I set `href` to point to the hidden content, in a manner similar to this:

```
<a data-fancybox="S" href="#hidden-content" data-caption= ''>
  <img src="thumbs/www.flickr.com-965.jpg" width="110" height="80"
 alt="Flickr video" title="5: www.flickr.com-965<br>" />
  <div class="caption">Flickr video</div>
</a>
```

Almost all lightbox scripts I have seen support this sort of syntax for handling inline content, including previous iterations of Fancybox. See the "inline" examples [here](http://fancybox.net/) for Fancybox 1 and [here](http://fancyapps.com/fancybox/) for Fancybox 2.

**Comment by acwolff** [comment]
Well I tried your hint:

    <a data-fancybox="S" href="#hidden-content" data-caption= ''>
      <img src="thumbs/flickr.com-965.jpg" width="110" height="80" alt="Flickr video" title="5: flickr.com-965.jpg<br>" />
      <div class="caption">Flickr video</div>
    </a>

    <div style="display: none;" id="hidden-content">
    <video controls preload="none"><source src="https://www.flickr.com/photos/warmandpowerful/5953412756" type="video/mp4">Your browser does not support HTML5 videos.</video>
    </div>

    <script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

But it is still not working, see here: https://andrewolff.jalbum.net/TestVideos_FB/indexFlickr.html

**Comment by sayontan** [comment]
The link you have pasted in your video source is not for the video (i.e. it doesn't point to the MP4 file). Rather it is for the page containing the video (i.e. the HTML page with the MP4 file). That is causing you issues, I believe: you are trying to include an HTML link as a source for a video file, which is not correct.

**Comment by acwolff** [comment]
Well if I had the mp4 file, I don't need a hidden inline div, that is standard fancyBox, see my 2nd thumb:

    <a data-fancybox="S" href= "slides/IMG_0877.mp4" id="1" data-caption= 'iPhone video file'>
      <img src="thumbs/IMG_0877.jpg" width="110" height="80" alt="iPhone video file" title="2: IMG_0877<br>" />
      <div class="caption">iPhone video file</div>
    </a>

But I can't get the mp4 file!

If you go to a Flickr page like https://www.flickr.com/photos/warmandpowerful/5953412756

I can only click the Share button in the lower right corner and copy the Embed code:

    <a data-flickr-embed="true"  href="https://www.flickr.com/photos/warmandpowerful/5953412756" title="Ballet"><img src="https://farm7.staticflickr.com/6124/5953412756_547efc9a5c_z.jpg" width="640" height="360" alt="Ballet"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

You see here no mp4 file, just a link to the embeddede video page:
href="https://www.flickr.com/photos/warmandpowerful/5953412756"

You see the same with YouTube  and Vimeo videos, but these are standard supported by fancyBox and are processed by code like this:

    <a data-fancybox="S" href="https://www.youtube.com/embed/QbULyApj9Sw" id="5" data-caption= '<strong>Texel: rondje over het eiland en langs het strand - YouTube</strong><br>YouTube video'>
      <img src="thumbs/www.youtube.com-363.jpg" width="110" height="80" alt="YouTube video" title="6: www.youtube.com-363<br>" />
      <div class="caption">YouTube video</div>
    </a>

So I still wonder how you handle Flickr video.

Could you please give a link / code to one of your Flick video pages?

**Comment by sayontan** [comment]
Well, at this point the questions on this thread are not relevant any more to what I had posted as a support request. Your questions are centered more around how to do something with Flickr rather than Fancybox. 

But regardless:

> But I can't get the mp4 file!
> 
> If you go to a Flickr page like https://www.flickr.com/photos/warmandpowerful/5953412756
> 
> I can only click the Share button in the lower right corner and copy the Embed code:
> 

You can right-click on the video and "Inspect" it in Chrome to get the video source. But if you try to open that link in a new tab, it will prompt you to download the image, which is the problem I posted originally regarding the `Content Disposition`.

There is a potential problem with trying to fetch the URL in the above manner, though, and that is the fact that behind the scenes Flickr, being a CDN, might use a different server for serving the image, at which point your link will become invalid.

The right way to fetch the URL for Flickr is to use Flickr's API method, https://www.flickr.com/services/api/explore/flickr.photos.getSizes. You can pass your photo id "5953412756" and fetch the sizes there. For the HD version of your video this is the URL: https://www.flickr.com/photos/warmandpowerful/5953412756/play/hd/547efc9a5c/. This link will stay constant even if Flickr serves the image from a different server.

**Comment by sayontan** [comment]
> Could you please give a link / code to one of your Flick video pages?

Regarding a working version of my code, my demo page doesn't use Fancybox, but it uses Swipebox: https://aquoid.com/plugins/photonic/flickr/flickr-photos/#videos. The same inline video concept is used there.

My entire plugin's source code is available [from WordPress](https://wordpress.org/plugins/photonic/#developers), but I don't believe you will be able to go through that - it is far too complex for your requirement.
