### ISSUE TITLE
How to stop the slideshow?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#1979]
I have in my albums an extra button to view the location of the image in Google Maps, see [here](https://andrewolff.jalbum.net/FB_JustifiedGallery/) for an example.

If I run a slideshow and the viewer clicks the ‘Show location’ button, the Google Maps page is opened.
But I just hide the fancyBox container, so the slideshow continues. If I close the Google Maps window, the fancyBox window is again showed, but I don’t see the originaliteit image.

Before I open the Google Maps window I have to pause the slideshow. So my questions are:

How can I see that a slideshow is active?
How can I pause a slideshow?

**Comment by ivoduarte** [comment]
Hello

I guess you just have to use the example on the JS, when you press that extra button...

// Example of usage:
// $.fancybox.getInstance().SlideShow.start()

Instead of .start use .stop...

Best Regards,

Ivo Duarte

**Comment by acwolff** [comment]
Hi Ivo,

thanks for your hint, I tested it and it works fine!

Best regards,

André Wolff
