### ISSUE TITLE
Iframe without JS

### ISSUE THREAD

**Issue by marcohanke** [fancyapps/fancybox#1981]
Is it possible to use iFrame Code like this:
`<a data-fancybox data-type="iframe" data-src="http://codepen.io/fancyapps/full/jyEGGG/" href="http://codepen.io/fancyapps/full/jyEGGG/">
`
Otherwise the Link won't work without JS which is bad especially for things like privacy statements.

Or is there another Opinion?

**Comment by fancyapps** [comment]
The answer is - yes, you can.
