### ISSUE TITLE
Videos are interrupted in a slide-show

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#1983]
If I have an album with both videos and images like in [this test album](https://andrewolff.jalbum.net/FancyBoxVideoTest/) and I start the slide-show with a short playing time for example 3s, videos with a longer playing time are interrupted before the movie is finished.

An easy solution would-be to pause the slideshow if a video is encountered and to forbid autoplay of video’s. The viewer decides in that case to play the video and start the slideshow immediately or after hè is ready viewing the mooie.

Is this possible?

**Comment by acwolff** [comment]
Well I got no reply, so I had to invent a solution.
I use now this code:

    var FancyBoxIsOpen = false;
    var FancyBoxInstance = $.fancybox.getInstance();
    var slideType = '';  // 'image' 'iframe' 'video' 
    var mp4Video= false;
    var slideshowWasOn= false;

    function initFancyBox() {
     $('[data-fancybox="S"]').fancybox({
        onInit : function() {
    		FancyBoxIsOpen = true;
    		FancyBoxInstance = $.fancybox.getInstance();
        },
        beforeShow : function() {    
		        slide_index= this.index;
    		slideType = this.contentType;
    		mp4Video= ((this.contentType === 'video') && (this.type === 'video'));
    		if (slideType === 'video') {
                        slideshowWasOn = FancyBoxInstance.SlideShow.isActive;
                        if (slideshowWasOn) FancyBoxInstance.SlideShow.toggle();
    		}
        },
        afterShow: function() {
    		var obj=this.$content.find('video');
    		if (slideType === 'video') {
    			obj.on('ended', function() {
    				if (slideshowWasOn) FancyBoxInstance.SlideShow.toggle();
    				FancyBoxInstance.next(100);
    			});
    		}
        },

To see it in action open [this test album](https://andrewolff.jalbum.net/TestVideos_FB1/) and click the Play button (2nd button in the upper left corner). 
This album has been made with [my jAlbum FancyBox skin](https://jalbum.net/nl/skins/skin/FancyBox).

**Comment by acwolff** [comment]
Is this implemented in version 3.4?

**Comment by fancyapps** [comment]
Hi,

Slideshow now waits for html5 video to end (starting from v3.4.1)

**Comment by acwolff** [comment]
Nice, but what about YouTube and Vimea videos?

**Comment by fancyapps** [comment]
Unfortunately, it is not so simple. You would need to use appropriate API for each of the vendor. For example, YT - https://developers.google.com/youtube/iframe_api_reference

**Comment by acwolff** [comment]
Well, I use now with version 3.4 this code:

     $('[data-fancybox="S"]').fancybox({
    	onInit : function() {
    		FancyBoxInstance = $.fancybox.getInstance();
        },
        beforeShow : function() {
    		slide_index= this.index;
    		slideType = this.contentType;	
    		if (slideType === 'video') {
    			slideshowWasOn = FancyBoxInstance.SlideShow.isActive;
    			if (slideshowWasOn) FancyBoxInstance.SlideShow.stop();
    		}
        },
    	afterShow: function() {
    		var obj=this.$content.find('video');
    		if (slideType === 'video') {
    			obj.on('ended', function() {
    				if (slideshowWasOn) FancyBoxInstance.SlideShow.start();
    			});
    		}
        },
    	slideShow: {
            autoStart: false,
            speed: viewtime
    	},
    	onSlideShowChange : function(instance, current, active) {
    		if ( active ) {
    			instance.next();
   		}
    	},	
        buttons : ['slideShow','close']
    }); 

and this works faitly well as you can see in this album: https://andrewolff.jalbum.net/TestVideos_FB1/

**Comment by acwolff** [comment]
I did test with version 3.4.1 this code:

     $('[data-fancybox="S"]').fancybox({
    	onInit : function() {
    		FancyBoxInstance = $.fancybox.getInstance();
        },
       beforeShow : function() {
    		slide_index= this.index;
    		slideType = this.contentType;	
        },
    	slideShow: {
            autoStart: false,
            speed: viewtime
    	},
    	onSlideShowChange : function(instance, current, active) {
    		if ( active ) {
    			instance.next();
    	}
    	},	
        buttons : ['slideShow','close']
    }); 
This works only correctly if you use mp4 video files, but I can't use this code because YouTube and Vimeo files are now interrupted before the video is ready as you can see in this album: https://andrewolff.jalbum.net/TestVideos_FB2/

So unfortunately I have to use the old code as given in my previous reply.

**Comment by fancyapps** [comment]
I really did not want to boost file size by including this functionality, but after some thinking I decided to include. You can preview it here - https://codepen.io/fancyapps/pen/JayEMa?editors=1010

Actually, the gallery always moves to next item after video ends, I have not yet decided to make it optional or not.

**Comment by acwolff** [comment]
This looks great!
Available in the next version?
If the slideshow is on, it is logical that the gallery moved to the next item if thevideo ends!
No need Tomane that an option I think.
