### ISSUE TITLE
trapFocus appears to be no working

### ISSUE THREAD

**Issue by shanholmes** [fancyapps/fancybox#1984]
Hi,
The trapFocus functionality no longer appears to be working.
See the images demo here - https://fancyapps.com/fancybox/3/
Note, you are able to tab through the whole page with the modal open.
Thanks

**Comment by Jpwaldstein** [comment]
This is causing ADA requirement issues since you can get to the content behind the modal.

**Comment by pizzle1983** [comment]
Once the focus is in a dialog I can see shift+tab seems to trap focus OK (staying on the close button), but I can forward tab out of the dialog. https://codepen.io/pizzle1983/pen/NBNeLP

**Comment by fancyapps** [comment]
Hi,

This should be improved in the latest release (https://codepen.io/anon/pen/KxgQvR)

**Comment by pizzle1983** [comment]
@fancyapps it looks as though the order of the close button has been updated to be focused on last - but you can still tab out of the dialog. Shift+tab still works and traps focus though.

**Comment by fancyapps** [comment]
But what do you mean by "tab out of the dialog"? Of course you can tab out, focus trapping will just prevent focusing on other elements on the page, but as far as I know, it is not possible to prevent to focus on browser elements (like address bar), but, if you keep pessing, then focus will come back on the modal :)

**Comment by pizzle1983** [comment]
Hi @fancyapps , for things like modal dialogs you generally don't want users to be able to tab out of the dialog and through all the other page elements behind the dialog. 

A platform I work on recently had a large accessibility audit done where modals not receiving focus upon open and also not trapping focus was raised in the audit.

In these instances, having the focus trapped within the modal would mean the focus just takes into account the focusable elements within the modal. If a user presses tab on the last focusable element of the modal, the focus then returns back to the first focusable element of the modal (for example), or just stays on the last element. Same goes for shift+tab on the first focusable element of the modal. So you just loop around the focusable elements in the modal.

https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex#modals_and_keyboard_traps

As long as the user has a way out of the modal (via the close button), it's satisfying the other part of the wcag guidelines and not breaking 2.1.2

https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C243#no-keyboard-trap

Hope this helps for more info. This is also just how I'm interpreting the fancybox 'trapFocus' attribute - it may be that you want it to behave differently.

**Comment by fancyapps** [comment]
I understand you. Will it be OK if it would work like this - https://codepen.io/anon/pen/KxgQvR ? E.g., pressing tab goes cyclic inside modal, but shift+tab currently stop at the first element.

**Comment by pizzle1983** [comment]
It's completely your choice how you do it (if you want to do it at all), I really appreciate you've taken time to look at this.

Accessibility is one of those things that more and more people are asking about (even if they don't really know what they're asking for). The more you can be seen to making an effort towards accessibility the more attractive fancybox will be!

**Comment by fancyapps** [comment]
OK, I think I finally managed to implement true focus trap, check out that demo - https://codepen.io/anon/pen/KxgQvR

**Comment by shanholmes** [comment]
That looks good!

**Comment by fancyapps** [comment]
FYI, This update has been included in the latest version - v3.4.1
