### ISSUE TITLE
dailymotion support

### ISSUE THREAD

**Issue by cadeyrn** [fancyapps/fancybox#1989]
Fancybox 3 already supports YouTube and Vimeo as video providers. Any chance that DailyMotion can also be supported?

Thank you for the great lightbox script!

**Comment by fancyapps** [comment]
Hi,

Actually, built-in support for Dailymotion and Metacafe was removed only recently, because these sites are not relevant nowadays. If there would be enough requests, then they might be brought back, but you are the first one asking about this...

**Comment by cadeyrn** [comment]
Thank you for your answer. I have to accept your decision but to give you some context why I asked for DailyMotion support:

I work for a web development and marketing agency which creates websites for their customers in the tourism sector (hotels) with the open source e-commerce CMS Pimcore (https://pimcore.com/en). According to Pimcore's website it's used by over 80,000 companies. Pimcore comes with DailyMotion support and there is no way to disable the support for DailyMotion. This means I have to provide a good video experience not only for YouTube, Vimeo and local hosted but also for DailyMotion because the customers can select DailyMotion in the video content element and they expect a good experience for all options they can use. In current customer projects we implement the video content element with fancybox for YouTube, Vimeo and local hosted videos and it would be great to offer the same experience for DailyMotion, too. We can do something different for DailyMotion, but the same experience for all option would be the perfect solution, of course.

**Comment by fancyapps** [comment]
This is how you can bring back support for dailymotion -

```JS
$.fancybox.defaults.media.dailymotion = {
	matcher : /dailymotion.com\/video\/(.*)\/?(.*)/,
	params : {
		additionalInfos : 0,
		autoStart : 1
	},
	type : 'iframe',
	url  : '//www.dailymotion.com/embed/video/$1'
};
```

**Comment by ibasaw** [comment]
for now, to work you must write this instead:

`matcher : /dailymotion.com\/embed\/video\/(.*)\/?(.*)/,`
