### ISSUE TITLE
Start / Stop slideshow by a click and with the space bar

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#1990]
It would-be be nice if the slideshow could started / stopped by clicking in the image and by using the space bar on a keyboard.

Could you add this feature please?

**Comment by fancyapps** [comment]
Space bar is already toggling slideshow. If you wish to toggle via javascript, then you can do that like this - `$.fancybox.getInstance().SlideShow.toggle()` (you can execute this within `clickContent`, too)

**Comment by acwolff** [comment]
@fancyapps Thanks for your hint, that just what I was looking for!

I use now this code:

        clickContent:  function() {
    			FancyBoxInstance.SlideShow.toggle();
    			return false;
        },

and that works fine, see this example album: https://andrewolff.jalbum.net/FancyBoxWeb/

Thank you for your fantastic  light-box script !!
