### ISSUE TITLE
More than One fancybox get created.

### ISSUE THREAD

**Issue by ashishaggarwal1** [fancyapps/fancybox#1995]
I am showing Image Gallery after the search functionality, I am showing search results in the page and updating the search data based on the search user is doing.

At first search, the FancyBox works fine, but at the second search 2 Fancybox gets created, similarly at third search 3 fancy box gets created. The issue is the old fancy box is not getting deleted on the page until the whole page is refreshed.

**Comment by acwolff** [comment]
I think you should give a link to your gallery and explain with code what you are doing, otherwise noboddy can help you!

**Comment by fancyapps** [comment]
Close previously open fancyboxes using `$.fancybox.close()` before opening a new one.

**Comment by ashishaggarwal1** [comment]
fancybox.getInstance().close() works and removes all the previous instances, but the other links on the page stop working because of it. Pagination of the search on the same page does not work.

**Comment by fancyapps** [comment]
@ashishaggarwal1 I hope you understand that no one else has an idea what are you talking about and 2) your snippet closes only the current instance and only if that exists, and if not, you will get error message and further execution of js might be interrupted.
