### ISSUE TITLE
Internationalization on Custom Buttons Not Working

### ISSUE THREAD

**Issue by carraragiovanni** [fancyapps/fancybox#1996]
I created custom buttons, and am trying to modify the default text for diffferent languages. However, the selectors that work for other buttons ("ZOOM", "PLAY_START", etc.) do not work for custom buttons.

![screen shot 2018-07-10 at 10 50 23 am](https://user-images.githubusercontent.com/32495419/42499605-7e88bbd6-842f-11e8-8218-d78ba54da5de.png)
![screen shot 2018-07-10 at 10 52 46 am](https://user-images.githubusercontent.com/32495419/42499607-7ed71bb4-842f-11e8-95ef-93d5ffb22902.png)

```javascript
$.fancybox.defaults.btnTpl.FB = '<button data-fancybox-fb class="fancybox-button fancybox-button--fb" title="Facebook">' +
    '<img src="images/fb.svg" alt="" srcset="">'
'</button>';
```

```javascript
lang: "it",
        i18n: {
            it: {
                CLOSE: "Chiudi",
                NEXT: "Prossima",
                PREV: "Precendente",
                ERROR: "La foto richiesta non puo essere caricate. <br/> Rirpova un'altra volta.",
                PLAY_START: "Comincia slideshow",
                PLAY_STOP: "Pausa slideshow",
                FULL_SCREEN: "Schermo intero",
                THUMBS: "Miniature",
                DOWNLOAD: "Scarica",
                SHARE: "Condividi",
                ZOOM: "Zooma",
                FB: "Banana"
           }
        }
```

**Comment by fancyapps** [comment]
Simply replace `title="Facebook"` with `title="{{FB}}"`
