### ISSUE TITLE
Preventing direct mp4 video link preloading?

### ISSUE THREAD

**Issue by techyowl** [fancyapps/fancybox#1997]
I'm trying to use the direct video link where you specify the href as a url to an mp4 and it seems to download the whole video in browser preloading it and all I want it to do is stream directly from the url. is there any way to not have the videos preload?

**Comment by fancyapps** [comment]
The script creates `<video>` element, but the rest is up to you and the browser. Maybe this helps - https://stackoverflow.com/questions/10328401/html5-how-to-stream-large-mp4-files
