### ISSUE TITLE
How to add more info to the infobar

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#1998]
I like to add extra fields, like the file name and the title,  to the info bar.
Could you please give a hint how I can do that?

**Comment by fancyapps** [comment]
Hi,

Sorry for late reply.

1) You can access toolbar dom element from anywhere in the code to do some manipulation if needed - `$.fancybox.getInstance().$refs.toolbar`
2) You can use `baseTpl` option to customize toolbar area;
3) You can create custom button inside `btnTpl` and it is not required for your button to be .. button, you can place any html here;

**Comment by acwolff** [comment]
Yes, that works:

    beforeShow : function() {
		FancyBoxInstance.$refs.infobar.text('');  // erase counter if not used
		FancyBoxInstance.$refs.infobar.append('File: ' + imgFile)

Thanks!

**Comment by fancyapps** [comment]
btw, you are not required to use that element. You can easily create your own block of content that you can put anywhere you need. You can create either directly inside `baseTpl` or using callback (`onInit`)

**Comment by acwolff** [comment]
I use now this code:

    beforeShow : function() {
		slide_index= this.index;
		FancyBoxInstance.$refs.infobar.text('');	  
		FancyBoxInstance.$refs.infobar.append('<span data-fancybox-index></span> / <span data-fancybox-count></span> '); 
		FancyBoxInstance.$refs.infobar.append(infoFn[slide_index]); 


This works OK as you can see in [this album](https://andrewolff.jalbum.net/FB_JustifiedGallery/).

Manny thanks for your help!
