### ISSUE TITLE
Share-layer (social-buttons) - stuck/frozen image underneath

### ISSUE THREAD

**Issue by sun4all** [fancyapps/fancybox#2000]
Hi!
Thank's again for fancybox 3, I really think it is superior to the 2.x versions, especially the css-transitions really look good! Regarding the share-layer with the "social-buttons": 
If I have an image opened with fancybox - that is underneath the transparent background of the "share-layer", it somehow "freezes" there. I use a centered layout for my website and it really looks weird (while the social-buttons-layer is active) resizing the browser-window, because of the stuck pic below, that does not move or resize, while everything else moves, stays centered (and scales). I do use a laptop and a second monitor (resolution 2440 px - width). The strange phenomenon is not obvious until you resize the browser window, which you probably do not on a small screen. "Leaving/closing the share-layer", the image underneath centers/scales again - correctly. Because I do not often use the social-buttons, it's not really important to me, but it looks like the "freeze"-feature belongs somewhere else, suited for a different purpose.
Best Regards, sun4all
![fancybox-social-buttons](https://user-images.githubusercontent.com/39736048/42664381-c18442c2-863a-11e8-8cf7-f51b0d0ca223.jpg)

**Comment by fancyapps** [comment]
Hi,

That is actually done intentionally (to avoid resizing on too many elements for better performance) and I think users would not notice this anyway.
