### ISSUE TITLE
Viewport scrolling messed up after exiting Fancybox on mobile

### ISSUE THREAD

**Issue by torkiol** [fancyapps/fancybox#2002]
Hi,

I tried to use Fancybox in a simple mobile view (Kendo Ui mobile) that has navbar, title and scrollable view with images. It all works perfect except when Fancybox is closed. Somehow it messes up the scrollable view so that it goes to the top of the page behind the navbar. I noticed also that it always scrolls it to the image, which was initially clicked to open Fancybox. I remember that in older versions of Fancybox on exit it scrolled the view to the top, which was a bit annoying. So I wonder does Fancybox actually now try to scroll the view back to where it started? Is there any way to prevent that scrolling on exit?

Regards,
OlegT

**Comment by fancyapps** [comment]
Hi,

The script puts focus back on the trigger element unless this feature is disabled using `backFocus` option. But, starting from the next version, window position will be maintained to avoid jumping.

**Comment by fancyapps** [comment]
CLosing, because `backFocus` should solve this issue; also, the latest version tries to avoid jumping by saving window position and sets back after focusing on trigger element.
