### ISSUE TITLE
Custom button not working in Firefox vs 61

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2003]
I use 3 custom buttons, coded with next templates:

    $.fancybox.defaults.btnTpl.gmaps = '<button data-fancybox-gmaps class="fancybox-button fancybox-button--gmaps">' +
    '<img src="res/google-maps_FB.svg" id= "gmaps" alt="Show location in Google Maps" title="Show location in Google Maps" onClick="javascript:showLocation()">'  +
      '</button>';

    $.fancybox.defaults.btnTpl.facebook = '<button data-fancybox-facebook class="fancybox-button fancybox-button--facebook" >' +
    '<img src="res/facebook_FB.svg"  alt="Share on Facebook" title="Share on Facebook" onClick="javascript:fbShareSlide()">'  +
      '</button>';

    $.fancybox.defaults.btnTpl.exif = '<button data-fancybox-exif class="fancybox-button fancybox-button--exif" >' +
    '<img src="res/exif_FB.svg"  alt="Show/Hide EXIF data (camera settings)" title="Show/Hide EXIF data (camera settings)" onClick="javascript:toggleExif()">'  +
      '</button>';

Clicking on these buttons is working fine in under Windows 10 with Chrome and Edge and on iOS with Safari and Firefox, see this album:
https://andrewolff.jalbum.net/Sprengenberg/
Click on the first thumbnail and you see the fancyBox toolbar, where buttons 3, 4 and 5 are these custom buttons.

However with Firefox vs 61 on a Windows 10 PC the click function on these 3 buttons is not working.

Who knows how to solve this?

**Comment by acwolff** [comment]
Looks like #1930, but the code 

    .fancybox-container {
        -webkit-transform-style: preserve-3d;
    }

does not solve this problem!

**Comment by MarkoD** [comment]
IE 11 (on Win 7) also does not work.

**Comment by acwolff** [comment]
I could solve this problem by moving the onClick code one level up:

      $.fancybox.defaults.btnTpl.gmaps = '<button data-fancybox-gmaps class="fancybox-button fancybox-button--gmaps" onClick="javascript:showLocation()">' +
    '<img src="res/google-maps_FB.svg" id= "gmaps" alt="Show location in Google Maps" title="Show location in Google Maps" >'  +
      '</button>';
