### ISSUE TITLE
How can I add custom class to Fancybox container

### ISSUE THREAD

**Issue by sushmak02** [fancyapps/fancybox#2004]
Hi,
Is it possible to pass a custom class to `fancybox-container`? How can I do this?

**Comment by IsaacClem** [comment]
I believe there is an option for this. 

`baseClass: ""` 

Check [the documentation](https://fancyapps.com/fancybox/3/docs/#options) for more info :)

**Comment by nadoaa** [comment]
How can I add multiple classes to `fancybox-container` using `baseClass: ""`?

**Comment by fancyapps** [comment]
The value can contain `One or more space-separated classes`, see  https://api.jquery.com/addClass/
