### ISSUE TITLE
Same strange slide-show effects

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2008]
For my jAlbum [FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) I tested an embedded slide-show made with the fancyBox library.

I Initialize fancyBox with next code, where enableSlideShow = true: 

    function initFancyBox() {
     $('[data-fancybox="S"]').fancybox({
        onInit : function() {
    		FancyBoxInstance = $.fancybox.getInstance();
        },
    	clickContent:  function() {
    		if (enableSlideShow) {
    			FancyBoxInstance.SlideShow.toggle();
    			return false;
    		} else {
    			return "next";
    		}
        },
      mobile : {
        clickContent :  function() {
    		if (enableSlideShow) {
    			FancyBoxInstance.SlideShow.toggle();
    			return false;
    		} else {
    			return "next";
    		}
    	}
     },
        loop: true,
        infobar: false,
        slideShow: {
            autoStart: false,
            speed: viewtime
        },
        transitionEffect: transeffect,
        transitionDuration: transtime,
    	toolbar: false,
    	arrows:  false
    }); 
    }

Next I start the slide-show with:

    $('a[data-fancybox="S"]').first().trigger('click');
    FancyBoxInstance.SlideShow.toggle();

You see this slide-show here: https://www.andrewolff.nl/FotoSerie/AlgarveSlideShow/FancyBox/

Notice that the slide-show starts automatically, all slides come from the right side except if all slides have been displayed, in that case comes the first slide from the left, but the slide-show continues as expected, because loop= true.

However if I show that slide-show in an iframe as you see here: https://www.andrewolff.nl/TestAlbum/EmbeddedAlbums/FancyBox/ there are more strange effects:
1. The slide-show does not start automatically, you have to start it by clicking in the image.
2. If all slides have been displayed the first slide from again from the left, but the slide-show stops, although parameter loop= true.

I can get an automatic slide-show start by removing the two  clickContent functions, but in that case the user can't stop and restart the slide-show.

**Comment by fancyapps** [comment]
Hi,

I am quite sure this issue is related to #2022
