### ISSUE TITLE
How to prevent an autostart of videos?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2009]
Ii [this video test album](https://andrewolff.jalbum.net/TestVideos_FB1/) for [my jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) all videos do start automatically on a PC, which seems to be the default behavior of  fancyBox 3. 

How can I prevent this?
I like that the viewer decides whether he likes to play of skip a video in an album.

For the slideshow you have an 'autoStart' parameter, don't you think it is a good idea to add such a parameter for videos?

Edit:
I discovered that this:

	youtube : {
		autoplay : 0
    },
    vimeo : {
		autoplay : 0
    },
	mp4 : {
		autoplay : 0
    },
stops the autoplay of youtube and vimeo videos, but not the autostart of local mp4 file videos.
What is the correct name to be used to prevent also the autostart of mp4 video files?

**Comment by acwolff** [comment]
I found this solution:

    var FancyBoxIsOpen = false;
    var FancyBoxInstance = $.fancybox.getInstance();
    var slideType = '';  // 'image' 'iframe' 'video' 
    var mp4Video= false;
    var slideshowWasOn= false;

    function initFancyBox() {
     $('[data-fancybox="S"]').fancybox({
        onInit : function() {
    		FancyBoxIsOpen = true;
    		FancyBoxInstance = $.fancybox.getInstance();
        },
        beforeShow : function() {    
		        slide_index= this.index;
    		slideType = this.contentType;
    		mp4Video= ((this.contentType === 'video') && (this.type === 'video'));
    		if (slideType === 'video') {
                        slideshowWasOn = FancyBoxInstance.SlideShow.isActive;
                        if (slideshowWasOn) FancyBoxInstance.SlideShow.toggle();
    		}
        },
	youtube : {
		autoplay : 0
	},
	vimeo : {
		autoplay : 0
	}
        afterShow: function() {
    		var obj=this.$content.find('video');
		        if (mp4Video) setTimeout(function() { obj.trigger('pause'); }, 100);
    		if (slideType === 'video') {  // see also #1983
    			obj.on('ended', function() {
    				if (slideshowWasOn) FancyBoxInstance.SlideShow.toggle();
    				FancyBoxInstance.next(100);
    			});
    		}
        },
To see it in action open [this test album](https://andrewolff.jalbum.net/TestVideos_FB/) and click the Play button (2nd button in the upper left corner). or click on the first thumbnail.
This album has been made with [my jAlbum FancyBox skin](https://jalbum.net/nl/skins/skin/FancyBox).

This solution works, but I think it could easier be solved in jquery.fancybox.min.js

Please introduce in the next vesion someting like:

    video: {
        autoStart: true  // or false
    }

**Comment by fancyapps** [comment]
There is now a `video` option that you can use to customize html5 video template, format and autoplay. Default value:

```JS
video: {
  tpl:
    '<video class="fancybox-video" controls controlsList="nodownload">' +
    '<source src="{{src}}" type="{{format}}" />' +
    "Your browser doesn't support HTML5 video" +
    "</video>",
  format: "", // custom video format
  autoStart: true
}
```

https://codepen.io/anon/pen/dqpJxB?editors=1010

**Comment by acwolff** [comment]
@fancyapps  does this work too for YouTube and Vimeo videos?

**Comment by gutdingwillweilehaben** [comment]
@fancyapps 
Is there a way to autoplay Vimeo videos?

**Comment by fancyapps** [comment]
@gutdingwillweilehaben https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
