### ISSUE TITLE
width of iframe returns to default when using Opts:{}

### ISSUE THREAD

**Issue by AqaMahdi** [fancyapps/fancybox#2010]
hi. When i'm using Opts:{} in fancybox3, the width of iframe returns to 100%.
How can i fix that ? 
` window.parent.$.fancybox.open({
                        type: 'iframe',
                        src: 'http;//www.zx.com',
                        opts: {
                            buttons: false,
                            smallBtn: false
                        },
                        iframe: {
                            preload: false,
                            css: {
                                width: '500px',
                                height: '400px'
                            },
                            attr: {
                                scrolling: "auto"
                            }
                        }
                    });`

**Comment by fancyapps** [comment]
Hi,

You have used `opts` option, but `iframe` is not there, e.g, format your code like this: 

```JS
$('#test').click(function() {

    $.fancybox.open({
        type: 'iframe',
        src: 'https://codepen.io/jobs/',
        opts: {
            buttons: false,
            smallBtn: false,
            iframe: {
                preload: false,
                css: {
                    width: '500px',
                    height: '400px'
                },
                attr: {
                    scrolling: "auto"
                }
            }
        }
    }, );
});
```
