### ISSUE TITLE
Remove caption strip if the caption is empty

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2013]
If a caption is defined for an image, it is displayed in a strip at the bottom of the page.
However if the caption field is empty, the strip is still displayed and may cover part of the image.

**Comment by acwolff** [comment]
This is a mistake an empty caption shows no strip

**Comment by acwolff** [comment]
It is not a mistake, I see the caption strip also if the caption is empty, see this example: https://andrewolff.jalbum.net/FB_Carousel/

**Comment by sun4all** [comment]
Hi, acwolff!
In your "common.css" seems to be the css-code for the fancybox-caption.
I would suggest to get rid of that 1 px-line for now, until something better ... In your css-file "comment-out" (or delete) the part with "border-bottom:1px ..." 
like this /*    */
example: 
`.fancybox-caption::after{
/*border-bottom:1px solid rgba(255,255,255,0.3);*/
}`
Greetings, 
sun4all

**Comment by acwolff** [comment]
Thanks sun4all, this makes it better, but you see still a black empty strip if there is no comment.

**Comment by sun4all** [comment]
This is a "background-image" that paints a dark shadow.
"comment-out" ->
.fancybox-caption::before{
 /*
background-image: url(data:image/png;base64,iVBORw0KGgoAAAoZj3JUzWB+cOz4G48B and so on ... 
 background-repeat: repeat-x;
background-size: contain;
  */
  }
the caption has 3 style-options in the css:
.fancybox-caption{}
.fancybox-caption::before{}
.fancbox-caption::after{}
For myself I do not use ".fancybox-caption::before{}" and ".fancybox-caption::after{}" and use something simple like this, where 50px - or how much ever - is the distance to the bottom ...

.fancybox-caption{bottom:50px;left:0;right:0;padding-left:20px;padding-right:20px;width:100%;display:flex;justify-content:center;font-size:0.9em;color:#bbb;}
Greetings,sun4all

**Comment by acwolff** [comment]
Sorry, it is all my fault: in my album https://andrewolff.jalbum.net/FB_Carousel/ there is a hidden contents with the EXIF data in the caption. To see it, click the camera icon in the tool-bar.

If data-caption= '' the strip is absent as you can see in this album: https://andrewolff.jalbum.net/FancyBoxWeb/
Click on the 5th thumb to see a non empty caption.
