### ISSUE TITLE
Markup issue with fancybox element and close button

### ISSUE THREAD

**Issue by AdamWillard** [fancyapps/fancybox#2014]
When changing the targeted fancybox element to an article tag the close button no longer displays. See codepen link below for example.

https://codepen.io/anon/pen/WKpVbR?page=1&

**Comment by fancyapps** [comment]
Hi,

This will be fixed in the upcoming release, you can preview it here - https://codepen.io/anon/pen/KBONBx?editors=1000

**Comment by fancyapps** [comment]
Works fine with the latest version - https://codepen.io/anon/pen/pOEpXd?editors=1000
