### ISSUE TITLE
data-trigger loses options/captions

### ISSUE THREAD

**Issue by IsaacClem** [fancyapps/fancybox#2015]
I have fancybox set up for a number of images and am using the data-trigger attribute to link identical images to the gallery. Clicking on the first few images I can see captions correctly set up and options such as `clickSlide  : false` are being applied correctly.

However, on clicking on an image with the data-trigger attribute, the caption is not visible and all the default options are set.

Is there a way to use data-trigger to act identically to data-fancybox?

**Comment by fancyapps** [comment]
Hi,

It should work fine with the latest version - https://codepen.io/fancyapps/pen/YOyRKR?editors=1010
