### ISSUE TITLE
Video not playing from FancyBox3 in IE

### ISSUE THREAD

**Issue by mrwrighty** [fancyapps/fancybox#2017]
Have an odd issue.

Using Chrome, Safari, IE and Edge images view as expected. For videos though, I have a problem.

In Chrome and Safari, videos (MP4 from iPhone) play as expected, but in IE and Edge, the videos will not play and show the error "The requested content cannot be loaded. Please Try again" but if I paste the URL to the video directly in to IE or Edge, the video is there and plays correctly.

URL format is:

`<a href='https://<URL>/1030/images/1030_23-7-2018_1346/vid1.mp4' data-fancybox='142' data-caption='Additional Video'><img src='https://<URL>/1030/images/1030_23-7-2018_1346/vid1_thm.jpg' alt='Additional Video' width='24px' /></a>`

data-fancybox='142' defines all images in a gallery including videos.

I have hidden the actual URL for privacy.

Any thoughts please.

**Comment by acwolff** [comment]
You see that problem only if you try to play the videos locally on your PC.
The problem is gone if you upload the album.

See my [jAlbum FancyBox](https://jalbum.net/nl/skins/skin/FancyBox) video test album: https://andrewolff.jalbum.net/FancyBoxVideoTest/

**Comment by mrwrighty** [comment]
No that is not correct, the problem is from my hosted server. the url is a properly formed https:// url to my content. I have had a look at your pages and cannot see any difference in the content format or <A> tag that might cause the issue.

**Comment by acwolff** [comment]
Well I tested my album under Windows 10 with Edge and it runs fine,
I use the same structure as you use I think,
My e-mail address is on my website: 
https://www.andrewolff.nl/

**Comment by mrwrighty** [comment]
Hi Thanks for the offer. I believe I have now fixed the issue. I had originally downloaded the FancyBox scripts to my local machine and published with the site, but managed to fix the issue by linking to the source files. I'm guessing an update may have fixed the issue that was newer than the version I had installed.
