### ISSUE TITLE
Can fancybox3  Autoplay YouTube Videos onload or pre-queued VideoID onload ?

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2018]
Hi: Before Google started to change the audio / video playback functionality, I used to send a post method to a php page and with it, load a YouTube video playback automatically.

Can this be possible with Fancybox3 ?  Have you been able to re-enable this feature?

e.g.   https://mydomain.com/fancybox3/?videoID=xxxxxxxxxxxx&autoplay=true

Hope you can help me with this feature.

**Comment by fancyapps** [comment]
Hi,

Sorry, I just do not understand your comment at all.
