### ISSUE TITLE
Globally Disabling Scrollbars for iFrames?

### ISSUE THREAD

**Issue by soupking** [fancyapps/fancybox#2020]
Is there an easy way to disable scrollbars from iFrames?

I've been adding:
<style>
		body {
				overflow: hidden;
		}
</style>

To each iFrame forever. Is there a way or place I can add this to the main page so I don't have to do this for every iFrame file loaded?

If anybody knows I'd be stoked to know how. Thanks!

**Comment by fancyapps** [comment]
Hi,

It is not possible to change CSS for iframed page, but you can change iframe tag attributes, for example:

```JS
$.fancybox.defaults.iframe.attr.scrolling = "no";
```

**Comment by soupking** [comment]
Ah! Thank you Janis. I have like 40 iFrames a page. This is a Godsend in
one line. Thanks a bunch!
