### ISSUE TITLE
when fancybox was called from any element  inside  position:sticky element - after closing it - page jump to top

### ISSUE THREAD

**Issue by e11e11e** [fancyapps/fancybox#2024]
Hi! Thank you for Fancybox! Sorry for my english.

I spent a lot of time trying to localize one bug and i did it:
When fancybox was called from any element  inside element with css "position:sticky"  then after closing fancybox the page jumps to top...

Example: i have a sidebar, which is position:sticky, inside srollbar i have a link with attached js with calling fancybox ajax.
If i click the link inside sidebar, after closing fancybox, the page jump to top.
If i remove link from sidebar and place to another place, when click it  - everything is fine.

I think its because fancybox calculates position of triggered element, and in case of position:sticky something goes wrong...

**Comment by fancyapps** [comment]
Hi,

Maybe try setting `backFocus:false`. The script is not calculating and is not scrolling anything, but places focus back on the trigger element.

**Comment by e11e11e** [comment]
OMG Thank you so much! Its work!
