### ISSUE TITLE
Use the empty caption space for the image

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2027]
If you display an image without a caption, like [this image](https://andrewolff.jalbum.net/FB_JustifiedGallery/#S-4 ) there is an unused empty space at the bottom of the view-port.

Could you please make it possible to use that empty space for the picture, so make the picture large until it reaches the bottom of the view-port. This is specially important for small devices like an iPhone, see also attached screen-shots. See [here](https://andrewolff.jalbum.net/PS_JustifiedGallery/#&gid=1&pid=5) how this is handled by the PhotoSwipe lightbox.

So change this:

![current](https://user-images.githubusercontent.com/8150784/43677060-3c576830-97fc-11e8-82cc-ef92ecdc4942.PNG)

Into this:

![proposed](https://user-images.githubusercontent.com/8150784/43677059-3c3d94b4-97fc-11e8-9af3-919abef0c7b4.PNG)

**Comment by fancyapps** [comment]
Hi,

Spacing around image can be controlled using CSS (padding), the default value is:

```CSS
.fancybox-slide--image {
    padding: 44px 0;
}
```

So, you can, for example, use media queries to remove space around images on mobile devices. Or use a callback to add custom classname for slides not having caption and then create CSS rule that targets them:

JS

```JS
$('[data-fancybox="images"]').fancybox({
  beforeLoad: function(instance, current) {
    if (!current.opts.caption) {
        current.opts.slideClass += ' no-caption';
    }
  }
});
``` 

CSS 

```CSS
.fancybox-slide--image.no-caption {
  padding: 0;
}
```

Demo - https://codepen.io/anon/pen/qyvQWY

**Comment by acwolff** [comment]
Thanks you very much for your help!

I did implement this in my [jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox), see [this example album](https://andrewolff.jalbum.net/FB_JustifiedGallery/), but independent of there is a caption yes or no. In [this example album](https://andrewolff.jalbum.net/FB_JustifiedGallery/) it is only applied for a screen heigth < 400 px.

**Comment by acwolff** [comment]
@fancyapps I see that there is also a property preventCaptionOverlap which does a similar thing as you proposed above.
What is the difference between the two solutions?
If I set preventCaptionOverlap: true, my images take the full height on a PC, but on my iPad there is an empty spece above the image with the same height as the toobar.
Why this diffrenece between the two device types?

**Comment by fancyapps** [comment]
`preventCaptionOverlap` works by adjusting content bottom margin to match caption height; it is disabled by default on mobile devices - https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L352

**Comment by acwolff** [comment]
Well I did some tests, but whether I set preventCaptionOverlap  true or false: I get never an overlapping caption on my iPad, I see it only working on my PC
