### ISSUE TITLE
Project on hold?!

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#2028]
Hi @fancyapps - no update or reply from you for a very long time. Is this project on hold? I hope all is fine, keep good work!

**Comment by fancyapps** [comment]
Hi,

Do not worry, work is continuing on this project. It is just not easy to keep up with all support and to work on the current version while also brainstorming/experimenting for the next version (there are so many ideas and feature requests and so many new things to learn and try (react, for example) and it is not easy task to combine everything together).

Thanks for asking :)

**Comment by Eldenroot** [comment]
Thank you for your reply! I am looking forward to see next version ;)
