### ISSUE TITLE
Image text

### ISSUE THREAD

**Issue by Mou113** [fancyapps/fancybox#2030]
Is it possible to display an image text under the images in gallery mode ?
![2018-08-09_1501](https://user-images.githubusercontent.com/42242158/43900443-3d1e1d80-9be5-11e8-96b2-afddc2ca6e74.png)

**Comment by fancyapps** [comment]
Hi,

Sorry, there is currently no option for that. I believe there is already a feature request for that.

**Comment by acwolff** [comment]
It depends on which gallery software you use.

With my [jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) it is possible to select a gallery type with a variable # thumbnails per row and use descriptions under the thumbnails.
See [this example album](https://andrewolff.jalbum.net/FB_VarThumbsPerRow/).
