### ISSUE TITLE
How i can close fancybox without animation?

### ISSUE THREAD

**Issue by lukas-pierce** [fancyapps/fancybox#2031]
Its usefull for SPA on back click

**Comment by fancyapps** [comment]
Hi,

It is not clear what are you asking for. If you wish to immediately close current instance using API, then you can do that like this:

```JS
$.fancybox.getInstance("close", null, 0);
```

I have no idea what do you mean by "SPA on back click". Some kind of water recreation? 😅

**Comment by lukas-pierce** [comment]
Thanks for your answer. I'll try this letter. SPA - Single Page Application. Back click - browser history go back. For example, I have a opened fancybox modal on the page, and when I will go back I need force programatically close this modal without animation
