### ISSUE TITLE
How to start the slideshow with the next slide?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2033]
If I am ready viewing the current image, I click the Play button to start/continue the slideshow.
However in the current implementation the current image is still displayed until the selected play (speed)  time is passed.
I prefer that clicking the Play button starts with the next image.

Is that possible?

**Comment by fancyapps** [comment]
Hi,

Starting from the next release, it would be possible like this:

```JS
$('[data-fancybox="images"]').fancybox({
  buttons : ['slideShow', 'close'],
  onSlideShowChange : function(instance, current, active) {
    if ( active ) {
      instance.next();
    }
  }
});
```

https://codepen.io/anon/pen/xJvRZe?editors=1010

**Comment by acwolff** [comment]
Yes, that is great! Thanks a lot!

In which time frame do you expect to release the new version: days, weeks or months?

**Comment by fancyapps** [comment]
It is expected to be released next tuesday :) Tuesdays are good days for that kind of work :)

**Comment by acwolff** [comment]
OK then I will do a next release on a Tuesday after your release!

BTW I tried this with the current version:

    function onSlideClicked() {
    	$.fancybox.getInstance().SlideShow.toggle();
		if ( $.fancybox.getInstance().isActive ) {
      		$.fancybox.getInstance().next();
    	}
    	$.fancybox.getInstance().toggleControls();
    	return false;	
    }
but that does not work!

**Comment by fancyapps** [comment]
I guess you have to replace

`$.fancybox.getInstance().isActive`

with

`$.fancybox.getInstance().SlideShow.isActive`

**Comment by fancyapps** [comment]
But what is not working? I think the code does what it is told to do, but that probably is not what you want :)

I would suggest you to take a break and then make a fresh start.

**Comment by acwolff** [comment]
If you click on the first thumbnail in [this gallery](https://andrewolff.jalbum.net/FancyBoxWeb2/) FancyBox opens, but it goes immediately to the last slide. You see a multiple next() action I think!

**Comment by fancyapps** [comment]
Yes, that click slide event is executed multiple times during opening phase and therefore your code executes next() multiple times.

So, I'm closing this, because latest version has `onSlideShowChange` callback and you can use it like in my first snippet. But the rest is indeed related to that other issue.
