### ISSUE TITLE
Support WEBM

### ISSUE THREAD

**Issue by novakja** [fancyapps/fancybox#2037]
Fancybox 3.3.5, Windows 10 1803, all browsers (FF, Chrome, Edge, IE)

1)
```
<a data-fancybox data-width="640" data-height="360" href="video.mp4">Direct link to MP4 video</a>
```
Works fine

2)
```
<a data-fancybox data-width="640" data-height="360" href="video.webm">Direct link to WEBM video</a>
```
Fancybox 3.3.5 Shows error message: The requested content cannot be loaded. 
Fancybox 3.0 works

3)
```
<a data-fancybox href="#myVideo">HTML5 video element 1</a>
<video width="640" height="360" controls id="myVideo" style="display:none;">
    <source src="video.webm" type="video/webm">
</video>
```
Works fine

**Comment by fancyapps** [comment]
Hi,

Keep in mind that WebM video format is currently not widely supported - https://caniuse.com/#feat=webm

**Comment by novakja** [comment]
So why for webm extension not display error message: The requested content cannot be loaded
and IE11 and Safari without webm support normally open the video and show: Invalid source

**Comment by fancyapps** [comment]
Because `webm` was not included in the list of supported formats; it will be included in the next release.

**Comment by novakja** [comment]
OK, thank you

**Comment by fancyapps** [comment]
It has been included in the latest commit, but, as you can see - https://codepen.io/anon/pen/mGEYJE?editors=1000 - some browsers might not recognize that video format (you can check that here, too - https://www.webmfiles.org/demo-files/ )
