### ISSUE TITLE
Vidyard Video Not Playing in Fancybox Iframe for Chrome 

### ISSUE THREAD

**Issue by amans26** [fancyapps/fancybox#2038]
Hi
Earlier it is working for all the browser. But currently i have notice that vidyard video stopped load in iframe of fanybox for chorme.
Here is the link of site you can play video in home page and check with other browser
http://altislifereact.staging.wpengine.com

**Comment by fancyapps** [comment]
Hi,

Unfortunately, sometimes Chrome does not fire onload event for iframes. 

In your case, I would recommend to disable iframe preloading (enabled by default), the easiest way would be to add `data-iframe='{"preload":false}'` to your link, demo -

https://codepen.io/anon/pen/XPJWvJ?editors=1000

**Comment by amans26** [comment]
You are awesome :)

Thank u so much sir.

Regards,
Aman Sharma
