### ISSUE TITLE
How can a bullet layer appear without clicking?

### ISSUE THREAD

**Issue by 596121109** [fancyapps/fancybox#2039]

**Comment by fancyapps** [comment]
What do you mean by "bullet layer"?

**Comment by 596121109** [comment]
html

**Comment by 596121109** [comment]
Ordinary HTML elements

**Comment by fancyapps** [comment]
Sorry, not the slightest idea what are you asking for.

**Comment by 596121109** [comment]
I mean, I can pop up a HTML element without clicking.

**Comment by fancyapps** [comment]
If you are asking about starting fancybox programmatically, then see API section from docs - https://fancyapps.com/fancybox/3/docs/#api
