### ISSUE TITLE
LESS support

### ISSUE THREAD

**Issue by marcoraddatz** [fancyapps/fancybox#204]
It would be nice to have a LESS and / or SASS file where you can create the CSS from. This would make development much easier.

As as example: I use fancyBox with Twitter Bootstrap. The z-Index of fancyBox is too low for the z-Index of Bootstrap. If that would be a variable, it could be set easily via a config file.

http://lesscss.org/

**Comment by dennis-f** [comment]
I totally second that topic!!

**Comment by SalahAdDin** [comment]
:+1:  for sass support in bower fancy release :D

**Comment by SalahAdDin** [comment]
I do this for sass support: https://gist.github.com/SalahAdDin/0c52f262aae5f78c7137
:+1:

**Comment by christianmagill** [comment]
Please add Sass support. It would be awesome to set configurations such as asset path without altering the component.

**Comment by SalahAdDin** [comment]
I can't, i have problem with github.

**Comment by fancyapps** [comment]
Hi,

If there will be some CSS preprocessor, then it probably would be Sass - #1372
