### ISSUE TITLE
Bug, duplicate modal when clicking on content

### ISSUE THREAD

**Issue by makissm21** [fancyapps/fancybox#2046]
Hello!
When clicking in the content area, there is a duplication of windows, tell me this is a bug or something I'm not doing right?
link https://jsfiddle.net/m9v7p0yx/1/
Thank you in advance for your help!

**Comment by fancyapps** [comment]
Hi,

Your code is so wrong that I don't even know where to start...

Please, read docs and study some some demos (for example, https://codepen.io/fancyapps/pen/BOoGvQ?editors=1000 )

**Comment by makissm21** [comment]
You do not have any examples for inline gallery and button click, can you tell me how to do it correctly?

**Comment by fancyapps** [comment]
It would be something like this - https://jsfiddle.net/32dzqmjv/ 

Basically, do not add `data-fancybox` to inline elements, because adding that attribute automatically attaches click event that starts fancybox (therefore you experienced some weird stuff in your demo)

**Comment by makissm21** [comment]
Thank you very much, you really helped me!!!
