### ISSUE TITLE
Use global jQuery

### ISSUE THREAD

**Issue by godforger** [fancyapps/fancybox#2050]
https://github.com/fancyapps/fancybox/blob/e11639e672f358927a83636539eb8a0d48cc88a8/src/js/core.js#L3182

Maybe you can swap window.jQuery and jQuery, because it causes a problem.  I want to by default i can use fancybox with my jQuery as module from npm, a not from window.

**Comment by fancyapps** [comment]
This update has been included in the latest version - v3.4.1
