### ISSUE TITLE
Set buttons dynamically not working

### ISSUE THREAD

**Issue by projct1** [fancyapps/fancybox#2051]
Hi)

```javascript
$('fancybox3').fancybox({
    beforeLoad(instance, slide) {
        if ($app.isModerator) {
            slide.opts.buttons = slide.opts.buttons.push('download');
            //or slide.opts.buttons = 'download';
        }
    }
});
```
As result only 3 default buttons will be displaying =(

**Comment by fancyapps** [comment]
Hi,

You are expecting too much :)) Buttons are not dynamically tied to some js object. 
A simple solution - do it the other way, create and display all buttons for everyone, but hide the unnecessary button using callback.

**Comment by projct1** [comment]
You mean this?
```javascript
$('fancybox3').fancybox({
    buttons: [
        'zoom',
        'slideShow',
        'fullScreen',
        'download',
        'thumbs',
        'close'
    ],
    beforeLoad(instance, slide) {
        if ($app.isModerator) {
            $('.fancybox-button--download', instance.$refs.toolbar).hide();
        }
    }
});
```

**Comment by fancyapps** [comment]
Yes, something like that, maybe it would be better to use `onInit` callback.

**Comment by projct1** [comment]
Ok, thanks =)
Tell me plz, how i can prevent automatically bind fancybox on `data-fancybox` elements after `require('fancybox')`?

**Comment by projct1** [comment]
And why `beforeLoad` runs 2 times 😕?
http://skrinshoter.ru/s/010918/gN12jNXP

**Comment by fancyapps** [comment]
1) Either do not add that attribute or call `$.fancybox.destroy()`

2) Most likely you have 2 gallery items. Next/prev items are preloaded and callback is fired for each one.

**Comment by projct1** [comment]
Ok, thanks man 😃
