### ISSUE TITLE
Use A fancybox Plugin With Vue.js

### ISSUE THREAD

**Issue by threetown** [fancyapps/fancybox#2052]
>when I use vue loops items,  but fancybox clone items!

[my demo](https://jsfiddle.net/ttflowerboys/56gdhsw8/15/)

### 1. html
>I loops the list with vue `v-for ` directive and config fancybox options，like this:
```html
<ul class="mapv_data_list">
  <li v-for="children in mapvResource.data" :title="children.name"
      data-fancybox="gallery"
      data-type="iframe"
      :href="children.url"
      :data-caption="children.name">
    <div class="thumb"><img :src="children.thumb" :alt="children.name"></div>
    <div class="title"><h2>{{children.name}}</h2></div>
    <div class="meta">
      <span class="count">{{children.num}}条数据</span>
      <span class="time">{{children.time}}</span>
    </div>
  </li>
</ul>
```

### 2. render
![image](https://user-images.githubusercontent.com/12680441/45026455-e59e9080-b070-11e8-9b48-01452bf99240.png)

#### important: **total items is 8, but fancybox clone items!**

![image](https://user-images.githubusercontent.com/12680441/45026409-c7d12b80-b070-11e8-815e-72982ffb3a93.png)

last, I really can't stand my poor English!

**Comment by fancyapps** [comment]
Hi,

fancybox is not cloning anything, but is displaying all existing elements. Looks like you have to initialize the script using `selector` option, see https://fancyapps.com/fancybox/3/docs/#initialize-with-javascript

**Comment by KaitoXion** [comment]
hi, i did like to ask; how can I import FancyBox to use in Vue.js? (am using Visual Studio Basic as the tool)

here is my assumetion:

```
import Fancyapp from '@fancyapp'
Vue.use(Fancyapp)
```

is this correct? 
or maybe I should @import all the css file at <style> tag section of my app.
which leave me wondering; what about the .js files -_-..

sorry; am new.
