### ISSUE TITLE
How to set scroll bar displayed?

### ISSUE THREAD

**Issue by baiduing** [fancyapps/fancybox#2053]
Hi. How to set scroll bar displayed? For example like this page:
https://yeziting.com/505.html

![sc](https://user-images.githubusercontent.com/42987357/45066536-6b622080-b0f1-11e8-8696-a43ff2b7630d.jpg)

Thank you.

**Comment by fancyapps** [comment]
Hi, There is an option `hideScrollbar` fro that:

`$.fancybox.defaults.hideScrollbar = false;`
