### ISSUE TITLE
Borders around navigation buttons

### ISSUE THREAD

**Issue by muenic** [fancyapps/fancybox#2054]
Hi there,

great script, It works like a charm and it's ready for my website BUT there's a strange issue I can't figure out.
There are borders (?) around the navigation buttons (arrows and navigation buttons in the top right corner) and I have absolutely no idea why. Apparently  I'm the only one, I've checked resolved issues on Github, original files, files from other sites using this script, changed css and js files and used untouched original files again and they're still visible. I even checked my other css files for same class names or errors - nothing. 
I hope someone has a clue. I've attached screenshots.
Thanks for any help.

Edit says: Forgot to mention that this "feature" is visible on desktop using actual Firefox & Chrome and on tablet Android 7 and mobile Android 6 (both Firefox).
 
![file1](https://user-images.githubusercontent.com/43009710/45108165-1c8da880-b13c-11e8-925a-366f6135a505.jpg)
![file2](https://user-images.githubusercontent.com/43009710/45108166-1ef00280-b13c-11e8-9bfe-cf28088b3fb7.jpg)
![file3](https://user-images.githubusercontent.com/43009710/45108168-21eaf300-b13c-11e8-8673-7d3ade655c0d.jpg)

**Comment by fancyapps** [comment]
Hi,

I guess you have some CSS conflict on your site, but it is not possible to tell without seeing your page or some live demo. Can you use developer tools to inspect these elements and to see what CSS rule creates those borders?

**Comment by muenic** [comment]
Thank you for the quick answer :-)
Developer tools was my favorite tool today...it is the class "fancybox-button fancybox-button--arrow_left"  resp. "arrow_right". I've changed everything, added border: 0 to all the button classes and even tried border: 5 to see if anything happens. Nothing at all. Obviously it isn't a real border...
I even gave the div attribute in the js file (btnTpl) a class name just in case there's a general div attribute definition somewhere on my page (double-checked, it isn't). Never had any trouble with css stuff till now....
Here are two pages where's the script at work (with and without thumbs button). Original jquery.fancybox.min.js & jquery.fancybox.min.css are installed. 
https://www.cb500.net/tmp/de/CB500/Wo-ist-was#images-1
https://www.cb500.net/tmp/de/CB500/Geschichte/Farbcodes#gallery-1

**Comment by fancyapps** [comment]
Just as I suspected, that is a shadow created by this rule:

```CSS
button,
input[type=submit],
input[type=button],
input[type=reset] {
    box-shadow: 1px 1px 2px #C5C5C5;
    -moz-box-shadow: 1px 1px 2px #C5C5C5;
    /* -webkit-box-shadow: 1px 1px 2px #C5C5C5; */
    -o-box-shadow: 1px 1px 2px #C5C5C5;
}
```

so, either remove or override.

**Comment by muenic** [comment]
That's it! Thanks a lot, you saved my day.
