### ISSUE TITLE
Documentation re: "data-fancybox-trigger" vs "data-trigger"

### ISSUE THREAD

**Issue by noahkuhn** [fancyapps/fancybox#2055]
In this section of the docs, you reference using "data-fancybox-trigger" to trigger a gallery from an element outside the gallery itself. This doesn't seem to work, but "data-trigger" does. Please update docs when you have a chance. Thanks for an awesome tool.

**Comment by noahkuhn** [comment]
For what it's worth, this is related to the "inline" method

This is the main link that starts the gallery.

`<a data-fancybox="partners" data-src="#partner-name" href="javascript:;">`

This works to trigger it:

`<a data-trigger="partners" data-src="partner-name" href="javascript:;">`

This does not:

`<a data-fancybox-trigger="partners" data-src="partner-name" href="javascript:;">`

**Comment by fancyapps** [comment]
Hi,

Maybe you have missed https://github.com/fancyapps/fancybox/releases

See https://codepen.io/fancyapps/pen/YOyRKR?editors=1010

**Comment by noahkuhn** [comment]
Damn, right you are, sorry for the noise...
