### ISSUE TITLE
When sliding through fancy box slides in the lightbox, after closing jumping in slick slider

### ISSUE THREAD

**Issue by carasmo** [fancyapps/fancybox#2058]
In version 3.3.2 this does not happen. Works as expected.

In the latest version, I click on an image in my slick-slider instance, the image opens in in Fancybox, I click or swipe through the images inside Fancybox, then I close the lightbox and the slider pops to that image with a nasty jump and it does not change the actual indicator in the slider (why would it) of the slide that I'm on so it's very annoying. Jumping to the image in the slick slider should not happen after I close FancyBox.

**Comment by fancyapps** [comment]
Hi,

What do you mean by "jumping"? The only issue I can think of if that sometimes zoom-out animation goes to hidden slide, therefore it is advised to not use zoom animation when combining with slider scripts, see this demo - https://codepen.io/fancyapps/pen/jvbEgo?editors=1010

**Comment by carasmo** [comment]
**Thank you!** Yes, I had Zoom on there. I switched back to the latest version and the Pen was **extremely** helpful for using infinite  on the slider and not having clones too.

Since I'm using the fancy box on a link, this worked. The one in the pen made the layout inside Fancybox weird looking:

I'm also using the an id at the end of the slider class, so this works great:

```
		//* Slider Fancy Box
		//* Ref: https://codepen.io/fancyapps/pen/jvbEgo?editors=1010

		var selector = '.slick-slide:not(.slick-cloned) a';

		// Skip cloned elements
		$("[data-fancybox^=slider-gallery-]").fancybox({
  			selector : selector,
			hash: false,
  			backFocus : false,
  			animationEffect : "fade",
				thumbs: {
				autoStart: true
             },
             buttons: [
                 'slideShow',
                 'fullScreen',
                 'thumbs',
                 'close'
             ]
		} );

		// Attach custom click event on cloned elements, 
		// trigger click event on corresponding link
		$(document).on('click', '.slick-cloned', function(e) {
  		$(selector)
    		.eq( ( $(this).attr("data-slick-index") || 0) % $(selector).length )
    		.trigger("click.fb-start", { $trigger: $(this) });
  			return false;
		} );

```
