### ISSUE TITLE
How to disable close button in inline type if exist my data-fancybox-close button inside content?

### ISSUE THREAD

**Issue by 7iomka** [fancyapps/fancybox#2060]
How to disable close button in inline type if exist my data-fancybox-close button inside content?
I'm upgraded to the latest version of fancybox, and I have problem with two close buttons: 1 - new automatically added by plugin (not difference with smallbtn or default), and my custom button inside source of inline target content.
In previous versions of the plugin, if the button was inside the inline content, the button from the plug-in was not added. How can I disable the default close button now? I do not want to go through the types of modals on my site, for this I have to programmatically initialize them, while now I have initialization through the date attributes.
Also I do not want to set modal: true, because this behavior does not correspond to normal behavior when a click outside the modal closes it.

Thanks.

**Comment by 7iomka** [comment]
In addition to this, another child element was added, the styles of which should now be removed - .fancybox-content

**Comment by fancyapps** [comment]
Hi,

It could be something like this:

```JS
afterLoad: function(instance, current) {
	if (current.$content.find('.fancybox-close-small').length) {
		current.opts.smallBtn = false;
	}
}
```

**Comment by 7iomka** [comment]
@fancyapps , Please, Be kind to spend more time than to give an answer that does not work.
current.$content.children() don't contain .fancybox-close-small, appended by fancybox, and condition `current.$content.find('.fancybox-close-small').length` never return true!
and again, the above pseudocode example requires initialization through.
And the question of this issue, in addition to the problem itself - why did the plugin stop making this sampling independently and this is not said anywhere else?

**Comment by fancyapps** [comment]
As you can see in this demo - https://codepen.io/anon/pen/JaLErY?editors=1010 - that answer does work.

Html code of the close button can be customized, you use `btnTpl.smallBtn` option to literally append any html content to your content, for example, multiple buttons. And you can make any element to act as a close buttons (by adding `data-fancybox-close` attribute). Therefore it cannot be determined automatically weather to append that small btn or not. 

Another trick would be to add `data-small-btn="false"` (along with `data-toolbar="false"`) to your trigger element to prevent appending close button.

**Comment by 7iomka** [comment]
@fancyapps, thanks! Now it is clear why this functionality was left to the user's discretion. I'll add this add-in to the default settings in my build.
