### ISSUE TITLE
With loop: false, some navigation buttons should be removed.

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2062]
I have an album with 3 images, [see here](https://andrewolff.jalbum.net/ExtendedCommentModal_FB/). Close the opening window and next click on the 3th thumbnail. FancyBox opens and shows a 'Next' navigation button. However if you click that button, you get no reaction, because parameter loop is false.

I think that button should in this case be removed, or clicking the button should close the Light-box.

The same holds for the 'Previous' button on the fist slide image.

**Comment by fancyapps** [comment]
Hi,

I perfectly understand your question, but this is done intentionally. Imagine if those navigation buttons would disappear. If you would open a gallery of multiple items and would keep pressing on the next button quite fast, then at the end of the gallery you most likely would accidently click on the black overlay thus closing the lightbox. This would be quite annoying (especially on mobile), therefore these buttons stay disabled as clicking them would do nothing.

Anyway, you can use CSS to hide it completely (just check when arrows has `disabled` attribute), if you wish. Keep in mind, if you hide them using `visibility: hidden;` then user might click in that area and wonder why nothing is happening (it would be expected that lightbox would close).

**Comment by acwolff** [comment]
Well I don't agree with you, but of course I respect your decision.

I think it is not a bad idea, that if you at the last slide a next click of a fast clicker closes the light box.

I did implement it now in my own code:

        beforeShow : function() {
    		slide_index= this.index;
    		if (slide_index === nrofImages-1) { $('.fancybox-navigation .fancybox-button--arrow_right').hide()} else { $('.fancybox-navigation .fancybox-button--arrow_right').show()}; 
    		if (slide_index === 0) { $('.fancybox-navigation .fancybox-button--arrow_left').hide()} else { $('.fancybox-navigation .fancybox-button--arrow_left').show()}; 
        },

You see the result [here](https://andrewolff.jalbum.net/ExtendedCommentModal_FB/).
