### ISSUE TITLE
Height Calculation sometimes wrong

### ISSUE THREAD

**Issue by DanielReif** [fancyapps/fancybox#2063]
When i use the following code i get on some screen resolutions a bigger iframe then the body size is. So i get the white bottom bar like in the screenshot (red marked). All classes are only for the color or bootstrap 4.1 standard.

> <body class="dialog">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-7 col-lg-7">
                <table class="table mt-3">
                    <tbody>
                        <tr>
                            <td>Kreditor-Nr.</td>
                            <td>000000</td>
                        </tr>
                        <tr>
                            <td>Firmierung</td>
                            <td>Musterfirma Muster & Firma GmbH</td>
                        </tr>
                        <tr>
                            <td>Firmierung 2</td>
                            <td>Musterfirma Muster & Firma GmbH</td>
                        </tr>
                        <tr>
                            <td>Strasse</td>
                            <td>Musterstrasse 999</td>
                        </tr>
                        <tr>
                            <td>Ort</td>
                            <td>D - 00000 Musterhausen</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-sm-5 col-lg-5 dialog-footer">
                <h1>Mustermann, Max</h1>
                <table class="table mt-3">
                    <tbody>
                        <tr>
                            <td><img src="/system/icons/call.svg" alt="SVG mit img Tag laden" width="25" height="25" ></td>
                            <td>+49 0000 00-0000</td>
                        </tr>
                        <tr><td></td></tr>
                        <tr>
                            <td><img src="/system/icons/mail-send.svg" alt="SVG mit img Tag laden" width="25" height="25" ></td>
                            <td>max.mustermann@dennree.de</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

![fancybox bug](https://user-images.githubusercontent.com/36186128/45422179-c1097080-b68f-11e8-8402-dac948c3d698.PNG)

**Comment by fancyapps** [comment]
Hi,

I appreciate that you included some html code and even image, but .. that is completely useless. It is just not possible to help you without seeing a live demo.

**Comment by DanielReif** [comment]
Hi,
thx for the fast reply. Here is a full working example.

[Test.zip](https://github.com/fancyapps/fancybox/files/2375114/Test.zip)

Index.html = Site wich is calling the Fancybox
iframe.html = The Content for the iframe
style.css = All Styles

**Comment by fancyapps** [comment]
Interestingly, it took me a long time to find a case where that blank space appears, but then I found out (you have to resize browser to specific with) and then I quickly found the reason - you have this CSS code:

```CSS
.fancybox-content {
  max-width: 50%;
 }
```

+ you have responsive layout and that combination interferes with the logic of the height calculation. I updated the code and your issue should be fixed in the next release.

**Comment by fancyapps** [comment]
Well, it sure works fine for me now, I tried really hard to recreate that issue, but works fine.

If everything goes fine, it will be released this week.

**Comment by fancyapps** [comment]
The latest version (v3.4.2) should fix this issue.
