### ISSUE TITLE
How to get the navigation buttons into an in-line gallery div?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2064]
To do some experiments with in-line gallery's, I modified the example https://jsfiddle.net/32dzqmjv/.

You see my modified example [here](https://www.andrewolff.nl/testFB/). All code is on the main page.

Could you please tell me how I get the navigation buttons inside the (moved) galley?

And the same question for the tool-bar buttons.

**Comment by fancyapps** [comment]
Hi,

There is no option for that as the script was not designed for that. Actually, I am always surprised when I see that people create galleries of inline elements.

But, you can easily create your own "inline toolbar", something like this:

```JS
var inlineToolbar = '<div class="fancybox-inline-toolbar">' +
        $.fancybox.defaults.btnTpl.arrowLeft +
        $.fancybox.defaults.btnTpl.arrowRight +
        $.fancybox.defaults.btnTpl.close +
    '</div>';

$.fancybox.open( $('.inline-gallery'), {
    btnTpl : {
        smallBtn : inlineToolbar,
    }
});
```

Here is a quick and dirty demo - https://jsfiddle.net/uq8wsd9m/

**Comment by acwolff** [comment]
That is not a dirty, but an excellent demo!

I used it to modify my example, see [here](https://www.andrewolff.nl/testFB/index2.html)

Thanks for your help!

**Comment by acwolff** [comment]
Actually, there is a much more simple method to get a smaller in-line gallery:

If I add to [this full window gallery](https://andrewolff.jalbum.net/FB_Carousel_Inline/) this CSS code:

    .fancybox-container {
    	left: 10px;
    	top: 10px;
    	overflow: auto;
    	position: absolute;
    	height: 300px;
    	width: 500px;
     }

I get [this smaller moved gallery](https://andrewolff.jalbum.net/FB_Carousel_Inline2/).

The only problem is that the Slide-show is no longer working.
How do I get the Slide-show working with this code?

**Comment by fancyapps** [comment]
Uh, you know, one thing led to another and in the end, that broke slideshow.. But that will be fixed in the next update - https://codepen.io/anon/pen/ZMoyxw (will be released either at the end of the week or at the beginning of next week).

Looks like I did not understand what you were thinking by "in-line gallery" at the start. While it is possible to create a simple, floating gallery or to open inside some container, it is not fully supported, this will be one of the main feature of v4 :) (btw, you might want to set `closeExisting:false` to prevent stacking multiple modals)

**Comment by acwolff** [comment]
Nice!

I noticed that the slideshow works with this code:

      .fancybox-container {
      	overflow: auto;
        	position: absolute;
        	height: 300px;
        	width: 500px;
         }

**Comment by acwolff** [comment]
Well you said “While it is possible to create a simple, floating gallery or to open inside some container”
 That is exactly what I am looking for. I like to embed a gallery in a web page, if possible in a div of my choice.
The best implementation I could find was [this page](https://andrewolff.jalbum.net/FB_Carousel_Inline2/#S-2) which contains this code:

    <style>
    .fancybox-container {
    	height: 300px;
    	width: 100%;
    	margin-top: 300px;	
     }
    .headertext {
    	height: 300px;
    	border: thin solid #000;
    }
    .footertext {
    	height: 300px;
    	border: thin solid #000;
    	margin-top: 300px;
    }
    </style>
    </head>
    <body>
    <div class="headertext">
    <p>Text above the album</p>
    </div>
    <div class="footertext">
       <p>Text below the album</p>
    </div>
    <div id="indexDiv"> // contains the gallery thumbnails

But this is not responsive in the vertical direction.
Do you know a better way to implement this?

 It would be ideal if I could defined the container for the gallery somewhere on my page:
 
		<div class="fancybox-container">
			>
		</div>

**Comment by acwolff** [comment]
Great! That is exactly what I had in mind!!

Is this possible with the current version or in the next version?

**Comment by fancyapps** [comment]
I think it is possible since beginning of v3.

**Comment by acwolff** [comment]
Your example code did help me to implement in [my FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) web pages with an embedded FancyBox lightbox, see [here for an example](https://andrewolff.jalbum.net/FB_Carousel_Inline/)

Once again thank you very much for your help!
