### ISSUE TITLE
Bug? Dom added in the future shows a bug

### ISSUE THREAD

**Issue by seasolzombie** [fancyapps/fancybox#2065]
Fancybox shows that the type is html, not image!

**Comment by seasolzombie** [comment]
Fancybox  shows that the type is html, not image!

**Comment by seasolzombie** [comment]
Fancybox shows that the type is html, not image!

**Comment by fancyapps** [comment]
Hi,

No, it is not supported and, sorry, is not planned, because this is not how normally images are created/stored.

If your link would return a valid image, then it would work fine.
