### ISSUE TITLE
How to define my own colors for the fancybox-infobar?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2067]
I add contents to the info bar with this code:

        beforeShow : function() {
    		slide_index= this.index;
    		FancyBoxInstance.$refs.infobar.text('');		  
    		FancyBoxInstance.$refs.infobar.append('<span data-fancybox-index></span> / <span data-fancybox-count></span> ');		  
    		FancyBoxInstance.$refs.infobar.append(infoFn[slide_index]); 
        },

and use my own colors with this  code:

    .fancybox-infobar {
      background-color: rgba(51,255,51,1.0);
      color: #000000;
    	font-family: 'Courgette', serif;
    	font-size:30px;

But I don't see my colors appear in the infobar, the colors are iunverted I think.

How can I prevent this and use my own colors?

**Comment by fancyapps** [comment]
Hi,

You can set `mix-blend-mode: normal` to override color inverting, demo:

https://codepen.io/anon/pen/zJLqgR?editors=1100

**Comment by acwolff** [comment]
Thanks for your fast response.

I use now this:

    .fancybox-infobar {
      background-color: rgba(51,255,51,1.0);
      color: #000000;
    	font-family: 'Courgette', serif;
    	font-size:30px;
      -webkit-font-smoothing: subpixel-antialiased;
      height: 44px;
      mix-blend-mode: normal;

but tht does not solve the problem, see [here](https://andrewolff.jalbum.net/Yvonne_Borgers/#S-1)

**Comment by fancyapps** [comment]
Because you actually have -

```CSS
  mix-blend-mode: normal;
  left: 0;
  line-height: 44px;
  min-width: 44px;
  mix-blend-mode: difference;
```
See? You have the same rule here twice.

**Comment by acwolff** [comment]
Sorry, my fault!

Thanks for your help, it works now.
