### ISSUE TITLE
returning false in beforeLoad()

### ISSUE THREAD

**Issue by lozeone** [fancyapps/fancybox#2069]
in version 3.0 I was able to return false in beoreLoad() which would prevent the content from loading into the slide. I've upgraded to 3.4 and this no longer seems to work.

How can I achieve this in 3.4?

**Comment by lozeone** [comment]
So, i edited line 1590 from `self.trigger("beforeLoad", slide) `
to
`if(self.trigger("beforeLoad", slide) === false){
        return;
      }`
and it seems to do what I'm looking for. Would you consider adding this in the next release?  
thanks

**Comment by fancyapps** [comment]
Hi,

Why would you want to prevent loading content into the slide? The slide would appear blank.

**Comment by lozeone** [comment]
I had been using it to just display the fancybox background and loading animation.  Here is a sample of what I was doing. https://codepen.io/lozeone/pen/PdxdQZ

but with this version the slide loads even if the source is false. With earlier versions this worked.

**Comment by fancyapps** [comment]
In that case, I would recommend to do it the other way - simply display loading icon while waiting for content to load, for example:


```JS
var fb = $.fancybox.open('<div class="fancybox-loading"></div>', {
  smallBtn: false,
  touch: false,
  focus: false,
  keyboard: false,
  slideShow: false,
  fullScreen: false,
  autoFocus: false,
  modal: true,
});

// Set content
setTimeout(function() {

  fb.setContent(fb.current, '<div style="max-width:400px;padding:22px;"><h2>Hello!</h2><p>Maecenas sodales a elit in sodales. Nulla facilisi. Integer porta nisi vel leo viverra volutpat.</p><p><button data-fancybox-close>Close me</button></p></div>');

}, 1000);

```

https://codepen.io/anon/pen/qMQzeY

**Comment by lozeone** [comment]
I'm a dumbass. I did not realize it was as simple as that.
Thank you!
