### ISSUE TITLE
fancybox 2 is very slow cf. fancybox 1.3

### ISSUE THREAD

**Issue by h3xdec** [fancyapps/fancyBox#207]
I noticed that fade transitions in fancybox 2 are fading entire image holder whereas in fancybox 1 it was only fading the content (placeholder just got resized). i'm not sure if this is the reason for major slowdown, but fancybox 2 is very laggy on transitions. has anyone else experienced this issue?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
