### ISSUE TITLE
Different galleries with selector not working since version 3.4.0, now all images are in one gallery

### ISSUE THREAD

**Issue by nebrot** [fancyapps/fancybox#2070]
Since version 3.4.0 a config like "selector: "[data-fancybox]" for galleries doesn't work anymore, all images are now in one gallery instead of the defined.

Working example with 3.3.5: https://codepen.io/anon/pen/zJyvLZ
Not working example with 3.4.1: https://codepen.io/anon/pen/wERKpO

**Comment by fancyapps** [comment]
Hi,

Yes, that is how it works now.

**Comment by nebrot** [comment]
Ok..there was no hint in changelog. What do you suggest without changing html-markup?

**Comment by fancyapps** [comment]
Hmm, sorry about that, I had updated docs, but somehow forgot to mention in changelog :/

So, you have multiple galleries and you really need to use `selector` option? 

The easiest way would be to simply twak default, like so:

```JS
$.fancybox.defaults = $.extend(true, $.fancybox.defaults, {
  lang: 'de',
  hash: false,
  loop: true,
  transitionEffect : "slide",
  infobar: true,
  thumbs:
  {
    autoStart: true
  },
  mobile:
  {
    thumbs:
    {
      autoStart: false
    }
  },
  buttons : [
    "slideShow",
    "fullScreen",
    "thumbs",
    //"share",
    //"download",
    "zoom",
    "close"
  ]
});
```

https://codepen.io/anon/pen/rZoxXZ?editors=1010

**Comment by nebrot** [comment]
This looks good, thank you so much 👍
