### ISSUE TITLE
Internet Explorer can't load big image

### ISSUE THREAD

**Issue by dermansi** [fancyapps/fancybox#2071]
Hey,

first of all great work. We really enjoy using fancybox.

We are currently having an issue regarding IE (we need it to work in IE10 and IE11). Fancybox can't load the big image, It always shows "The requested content cannot be loaded. Please try again later."

We figured out that if we remove the following in jquery.fancybox.js on line 1773 everything is working fine:
.one("error", function() {
   self.setError(slide);
})

When we remove the error handling the picture will get shown. Why is it called in the first place?

Do you mind looking into that or can you give me a hint what might be wrong on our side?

Kind regards
dermansi

**Comment by fancyapps** [comment]
Hi,

How big image is a "big image"? Maybe you can give a sample image?

**Comment by dermansi** [comment]
Thanks for your fast response.

I just meant the normal sized image which gets loader after the user clicked on the thumbnail. The images aren't that big, like 1280x700px and compressed. 

After I removed the stated error code the images were loading without problems, so it can't be that.

**Comment by fancyapps** [comment]
If you refer to animation/transition issue, then the latest version (v3.4.2) should fix this issue.
