### ISSUE TITLE
on $.fancybox.open, how can I resize the image to fullscreen

### ISSUE THREAD

**Issue by muhammadizzat** [fancyapps/fancybox#2074]
How can I on open my image list, resize it to full screen or just bigger than the ".fancybox-image-wrap" div allow me to, this is the setting I have right now

```
$.fancybox.open(image_list,{
                loop: false,
                toolbar: false,
                protect: false,
                infobar: false,
                arrows: true,
                fullScreen: {
                    autoStart: true
                },
                clickContent: false,
 });
```

I've tried messing with the class 
```
div.fancybox-inner {
            width: auto !important;
            height: auto !important;
            /* Center */
            margin-left: auto !important;
            margin-top: auto !important;
            margin-right: auto;
            margin-bottom: auto;
}
```

This somewhat solve my problem, but now it mess up with the position of my caption, Any help is much appreaciated thanks

**Comment by acwolff** [comment]
This is possible with [my jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) if you click, after opening the webpage the 3th Full screen button from the left, see [this example album](https://andrewolff.jalbum.net/FB_JustifiedGallery/).

**Comment by fancyapps** [comment]
Sorry, but I could not understand your issue/question.

- If you wish to open/zoom to full size (not resized to fit into viewport), then this is currently not possible and there is already a feature request for that.

- If you wish to start in full-screen, then you can set `fullScreen: { autoStart : true } `
