### ISSUE TITLE
Click outside or click slide not working on mobile devices

### ISSUE THREAD

**Issue by anitr** [fancyapps/fancybox#2078]
Hi, first, thank you for your amazing app.

I would like to disable close anywhere, except on click to 'x' - close button inside popup. So, I added following options:

jQuery('#element').fancybox({
            trapFocus: true,
            clickSlide: false,
            clickOutside: false,
            autoDimensions: false,
            touch: false
});

It is working on desktop, but not on mobile devices. If I click outside popup on mobile devices, it closes the popup - but it shouldn't. Do you know why? Is this an issue or do I have to set other options?

I use fancyBox v3.2.1.

Thank you

**Comment by fancyapps** [comment]
Hi,

Please, upgrade to the latest version to see if that helps. If not, then, please, provide some more details (a demo would be awesome), because modal should close by default.

**Comment by acwolff** [comment]
Add:
 
       mobile: {
         clickSlide: false;
       },

**Comment by fancyapps** [comment]
HI,

Yes, @acwolff is right, `mobile` option contains some options That will be used when mobile device is detected, see https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L345

**Comment by Safulislam** [comment]
### This is the solution that worked for me using Fancybox 3.5.7 modifying the mobile section of the original source code in the mobile section:

 mobile: {
		clickContent: function (t, e) {
			return "image" === t.type && "close";
		},
		clickSlide: function (t, e) {
			return "image" === t.type && "close";
		},
	},
