### ISSUE TITLE
Uncaught TypeError: e.fancybox.getInstance is not a function

### ISSUE THREAD

**Issue by czdefault** [fancyapps/fancybox#2080]
I was just brought in to fix this site once it was brought over to HTTPS, This used to be functioning (2 months ago, when i added it to the site), but now i'm getting this error and am at a loss since it's using your assets at https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.js asset. Site is www.gotimetraining.com if you need any other reference. Any assistance in this would be great. Thanks!

**Comment by fancyapps** [comment]
Hi,

1) Your page shows "Sorry, your request cannot be accepted." message on first start, you might want to check your cache plugin.

2) Paste this in the console `$.fancybox.version` - it returns "2.1.5". So, that means you have mixed two versions of fancybox on your site and that creates a conflict.
