### ISSUE TITLE
Inline method does not show html, just id.

### ISSUE THREAD

**Issue by HillbillyGeek** [fancyapps/fancybox#2087]
I am integrating Fancybox into my CMS; other modes work just fine, but having trouble with the inline method.
when I use: data-type="html" , I just get the text of the id in the modal box;
when I remove data type I get the error message:
"The requested content cannot be loaded. Please try again later."
Below is my code; is there a mistake I am not catching?

```
<a data-fancybox="Files" data-src="#<?php echo $myfile ?>F" data-type="html" data-caption="<?php echo $myfile ?>" href=" javascript:;" data-animation-duration="700"> <img src="grafix/icons/link.png" class="float-left" /></a>
<div style="display: none;" id="<?php echo $myfile ?>F">
  <p>Hello! Select, copy and paste the text below to link to this file. </p>
  <span data-selectable="true">rfolder/<?php echo $cat ?>/<?php echo $id ?>/uploads/<?php echo $myfile ?></span>
</div>
```

**Comment by fancyapps** [comment]
Hi,

Simply remove `data-type="html"` or replace by `data-type="inline"` - https://codepen.io/anon/pen/WaQqVL?editors=1100

If you set `html` type, then value of `src` will be used as the content; it is intended to be used when starting fancybox programmatically.

**Comment by HillbillyGeek** [comment]
Thanks.
Unfortunately, I tried this, and still get “content not available”
I will keep looking at this. I am running this on my local server, and have run it on my production server, in case it’s a php version issue, but both environments do it...

**Comment by fancyapps** [comment]
I hope you understand that you have to use valid ID attribute for your HTML element and it is not a good idea to use  `<?php echo $myfile ?>` as an ID, it could produce some unexpected surprises.

**Comment by HillbillyGeek** [comment]
These <?php echo $myfile ?>  produce the unique filenames that are contained in one folder, such as mygif.gif and my_document.doc…
OK, wait: these are all selected by an array key: I changed that id generator to simply <?php echo $i ?>, and it works!
I guess the javascript is picky about dashes and dots and stuff.
Thanks for the quick help!
