### ISSUE TITLE
Video not working correctly with autoplay

### ISSUE THREAD

**Issue by beetle120** [fancyapps/fancybox#2090]
I have added 2 images and a video to a fancybox as seen at:
https://codepen.io/beetle120/pen/vVGJEx

It doesn't autostart the slideshow when it should, when you trigger the slideshow by clicking the next image button it loops around correctly for the first 2 video plays. On the 3rd loop it skips the 1st image and fails to load the video. Tested in Firefox and Chrome.

**Comment by fancyapps** [comment]
Hi, Thanks for reporting! I'll take a look.

**Comment by fancyapps** [comment]
This has been fixed in the latest commit, demo - https://codepen.io/anon/pen/VEjqoz

**Comment by beetle120** [comment]
All working. Thank you for fixing the issue.

**Comment by acwolff** [comment]
@fancyapps you use in your demoi https://codepen.io/anon/pen/VEjqoz a property fitToView whichI can't find in your documentation, so my questions are:

1. What does the property fitToView
2. Is there somewhere a list of all possible properties?

**Comment by fancyapps** [comment]
@acwolff There is no such option (https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L27), that must have left from the original demo created by other person who most likely ported code from v2.

**Comment by acwolff** [comment]
Thanks for your fast response and the list of possible options!
