### ISSUE TITLE
Migrating from 2 issues

### ISSUE THREAD

**Issue by Flatlinezor** [fancyapps/fancybox#2091]
Hello!

I realize my v2 is customized to death and there will be many things I cannot replicate in v3.

I have an image tagger that initializes over the fancybox-image opened and i could place through this.tpl an ID for the fancybox-image class so it places in it through beforeLoad js methods.

However, I cannot seem to find the basetpl fancybox-image area, can you please let me know how can i achieve this from v2?

this.tpl.image='<img class="fancybox-image" src="{href}" alt="" /><div style="position:absolute;"id="image-m-container"></div>',

Secondly, I can't seem to have 2 captions/titles as I could with v2. One at the top, and one at the bottom... Still no solution for this? :(

**Comment by fancyapps** [comment]
Hi,

While there are some similarities, v2 and v3 are completely different products. Therefore it would be best to take a fresh start when upgrading to never.

If you want to customize the content, then check out this demo - https://codepen.io/fancyapps/pen/ePYNZo

While I do understand why you ask for 2 titles/captions, in my opinion, that design is outdated and 1) would look weird while swiping/zooming the image. 2) you should take into account that users use different devices and long captions would potentially make content to scale to tiny size. 

v3 allows greater customization, so, be creative and maybe try something different (like https://codepen.io/fancyapps/full/pxovaa).
