### ISSUE TITLE
convert fancybox 2.1.5 ajax request to fancybox 3+

### ISSUE THREAD

**Issue by floatingFaez** [fancyapps/fancybox#2094]
Hello Sir. 
i am using fancybox 2.1.5 an write a code for ajax request which was

```JS
$(document).on('click', '.quickview', function(e) {
                    e.preventDefault();
                    var pid = $(this).attr('data-id');
                    $.fancybox({
                        href : expss0417_ajax,
                        ajax: {
                            data: {
                                action: 'expss0417_product_quickview',
                                pid: pid
                            }
                        },
                        type : 'ajax',
                        helpers : {
                            overlay: {
                                locked: true,
                                fixed: true
                            }
                        },
                        tpl: {
                            error    : '<p class="fancybox-error">' + request_error + '</p>',
                            closeBtn : '<a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a>',
                            next     : '<a title="Next" class="fancybox-nav fancybox-next" href="javascript:;"><span></span></a>',
                            prev     : '<a title="Previous" class="fancybox-nav fancybox-prev" href="javascript:;"><span></span></a>'
                        },
                        autoSize: true,
                        autoWidth : true,
           });
                return false;
});
```

which was running good in this version, But now  i want to convert this code into fancybox v3+, when use this code in v3+ i saw an error message in my console which was

> Uncaught TypeError: $.fancybox is not a function
>     at HTMLButtonElement.<anonymous> (scripts.js?ver=1.0.0:532)
>     at HTMLDocument.dispatch (jquery.min.js?ver=3.1.1:2)
>     at HTMLDocument.y.handle (jquery.min.js?ver=3.1.1:2)

but i include jquery v 3.1.1 and fancybox v3.5.2 properly in my project.

i see the documentation there was no clear instruction in ajax section.
so please help me how i convert this code from v2.1.5 to v3.5.2

**Comment by fancyapps** [comment]
Hi,

Actually, it doesn't really matter if you are using ajax, iframe, inline or ther type:
 
1) You have to use `$.fancybox.open()` method instead of `$.fancybox({..})`;
2) Use `src` option to specify the source.

Keep in mind that v2 and v3 are quite different, there are just some similarities, most of options you have used in that snipped do not exist in v3.

**Comment by floatingFaez** [comment]
Ok I discover the solution which is

                  $.fancybox.open({
                        src  : expss_obj.ajax_url,
                        type : 'ajax',
                        opts : {
                            ajax: {
                                settings: {
                                    data: {
                                        action: 'expss0417_product_quickview',
                                        pid:pid
                                    }
                                }
                            },
                            animationEffect: "zoom-in-out",
                            hideScrollbar: true,
                            afterShow : function( instance, current ) {
                                setTimeout(function() {
                                   
                                }, 200);
                            }
                        }
                    });

But now i want to know that is "onUpdate" callback available in the version v3? whis was present v2

**Comment by fancyapps** [comment]
There is also  `onUpdate` callback available, if needed.

**Comment by floatingFaez** [comment]
Ok than its great, but i didn't find this option in documentation option section. Thanks for support

**Comment by fancyapps** [comment]
Well, It (and some other callbacks) was originally meant for internal use, but you can use it anyway.
