### ISSUE TITLE
How to pop up youtube video using JavaScript

### ISSUE THREAD

**Issue by alan-zhang-** [fancyapps/fancybox#2095]
Hi, given a video link of youtube, how to pop up it using JavaScript.

**Comment by alan-zhang-** [comment]
I'm version 3. License already purchased.

**Comment by fancyapps** [comment]
Hi,

if you were thinking of how to programmatically start fancybox and display youtube video, then you can do that like this:

```JS
$.fancybox.open({
    src: 'https://www.youtube.com/watch?v=2mDPgVWG_Y8', 
    caption : '<h5>staysee</h5>'
});
```
