### ISSUE TITLE
Margin-bottom fancybox-content div not editable

### ISSUE THREAD

**Issue by gwbonline** [fancyapps/fancybox#2098]
I'm struggling with the margin-bottom from the fancybox-content div. The script puts in an margin-bottom automatically and in my case this is 6px. I want to increase this.  Tried several ways. Via css and also in the javascript file with settings for Fancybox. Nothing worked. Is there an easy way to do this and am I overlooking it?

I'm using the newest version of Fancybox.

**Comment by fancyapps** [comment]
Hi,

Spacing around content is controlled by CSS padding value, so, for example, for html content it would be like this:

```CSS
.fancybox-slide--html {
    padding: 50px;
}
```
