### ISSUE TITLE
Defining a group without having to update HTML

### ISSUE THREAD

**Issue by jsheffers** [fancyapps/fancybox#2099]
I'm using jQuery to loop through the current page to look for galleries.  They are coming from a CMS, so they only contain a link with an href from the the thumbnail image to a larger image.  I have no way of defining attributes or rel on the links themselves, so I'm wondering if there is still a way to group these with any Fancybox options.   Here is an example of what I'm trying to do.

```
$('.c-image-gallery').each(function(e) {
   $(this).find('a').fancybox();
});
```
This works fine except the images aren't grouped.   The problem arises when I have multiple galleries on the page, I don't want all of the gallery images showing up in one big fancybox.   Thoughts on this?  Am I missing something?

**Comment by fancyapps** [comment]
Hi,

Simply add `data-fancybox` attribute, for example: `$(".imglist a").attr('data-fancybox', 'gallery');`

https://codepen.io/anon/pen/aRaoYQ?editors=1010
