### ISSUE TITLE
How to get element that triggered fancybox?

### ISSUE THREAD

**Issue by bluediamondgrowers** [fancyapps/fancybox#2100]
With the removal of `$lastFocus`, I can't find a way (that doesn't rely on `setTimeout`) to get a reference to the element which triggered the opening of fancybox.  I saw this issue https://github.com/fancyapps/fancybox/issues/1707 however `opts.$orig` is never set for me and `document.activeElement` is always the body.  I need to get the element during onInit or onActivate at the latest.  I looked through the source and unfortunately `instance.$trigger = $target;` is set after `fancybox.open()`.

The HTML is basically this: `<a href="full.jpg" data-fancybox><img src="thumb.jpg"></a>`

**Comment by fancyapps** [comment]
Hi,

Yes, you are right, you can use `instance.$trigger` to get element that triggered fancybox, but, if you need to have that before that reference is created, you can use `instance.group[ instance.currIndex ].opts.$orig` trick, for example:

```JS
$('[data-fancybox="images"]').fancybox({
  onInit: function(instance) {
    instance.group[ instance.currIndex ].opts.$orig.css('visibility', 'hidden');
  },
  afterClose: function(instance) {
    instance.$trigger.css('visibility', 'visible');
  }
});
```

https://codepen.io/anon/pen/aRRpwx?editors=1010

**Comment by bluediamondgrowers** [comment]
Works great, thanks!
