### ISSUE TITLE
Fancybox download source other than displayed image

### ISSUE THREAD

**Issue by AndyZH76** [fancyapps/fancybox#2101]
Can someone explain, how to set up the download link in fancybox3 in that way, that it will not download the displayed image, but another image (e.g. a zipped hi res version of the displayed image)? Any help here? 

I know there must be something with 'afterload' and a "download attribute"...but I don't know how to set this up. 

Thx for any help.

**Comment by acwolff** [comment]
With my  [jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) you can download as an option the original image, see [this example album](https://andrewolff.jalbum.net/FancyBoxWeb/)
