### ISSUE TITLE
Prevent duplicate thumbnails

### ISSUE THREAD

**Issue by tommyEllerhold** [fancyapps/fancybox#2102]
I have a main image and a gallery, which both have the same fancybox groupname. Additionally the main image is also part of the gallery. When I open the fancybox, there are duplicate thumbnails (one for the main image & one for the gallery image).

So is there a way to prevent duplicate thumbnails?

**Comment by fancyapps** [comment]
Hi,

Actually, fancybox is designed to handle situations like this. Check out the docs - https://fancyapps.com/fancybox/3/docs/#usage (look for "Sometimes you have multiple links pointing to the same source... ") - and this demo - https://codepen.io/fancyapps/pen/VGoRqO?editors=1010
