### ISSUE TITLE
CSS.min or all other files?

### ISSUE THREAD

**Issue by toplisek** [fancyapps/fancybox#2104]
I have seen many helpers as CSS:
fancybox-core
fancybox-fullscreen
fancybox-share
etc.
Is this needed beside CSS.min or should be avoided?
Need help.

**Comment by fancyapps** [comment]
Hi,

The project contains of the core and some (optional) modules; each module has own js and optionally css file. Then gulp is used to concatenate all CSS files into one `jquery.fancybox.css` file and later minified into `jquery.fancybox.min.css`. 

So, you simply use `jquery.fancybox.min.css` file or include files you need.

**Comment by toplisek** [comment]
Regarding JS it is the same and we use just min. as I understand?

**Comment by fancyapps** [comment]
Yes, of course, the same goes for js files.
