### ISSUE TITLE
Fancybox API: YouTube + Autoplay

### ISSUE THREAD

**Issue by meneldil** [fancyapps/fancybox#2105]
Hello,

I can't automatically play a YouTube video when opening the popup with API.

Here is my code:
```
$.fancybox.open({
	src: 'https://www.youtube.com/watch?v=_sI_Ps7JSEk',
	youtube : {
		autoplay: 1,
	},
});
```

Do you know why it doesn't work?

**Comment by fancyapps** [comment]
Hi,

Your snippet works fine for me, therefore I guess you are using Chrome and you have encountered autoplay policy restrictions, see  https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by meneldil** [comment]
You've seen it right, I used Chrome.
Everything is explained then, thank you very much!
