### ISSUE TITLE
Fancybox 3.5 doesn't work with Youtube video

### ISSUE THREAD

**Issue by gitkiselev** [fancyapps/fancybox#2106]
Hello! I tried connect youtube with fancybox 3.5. But video doesn't play in window.
Could you help with it?

**Comment by fancyapps** [comment]
Hi,

It works - https://fancyapps.com/fancybox/3/#video

Just follow the demos - https://fancyapps.com/fancybox/3/docs/#video

**Comment by gitkiselev** [comment]
If you try relocate code to html page and repeat, It won't work. I tried many times. But in codepen all work.
Could you help with it?

**Comment by acwolff** [comment]
It works too outside codepen, see [here](
https://andrewolff.jalbum.net/FancyBoxVideoTest).
Why don’t you give a link to your webpage/

**Comment by fancyapps** [comment]
It is just not possible to help you without seeing what you tried. Maybe you forget to include jquery, maybe you did not include fancybox js file correctly, who knows...

**Comment by gitkiselev** [comment]
When I relocate code from html to codepen it works. Jquery fancybox and their styles I connected.
I checked.
