### ISSUE TITLE
Deep linking to open modal with inline html content

### ISSUE THREAD

**Issue by Sorcutt** [fancyapps/fancybox#2108]
Hi,

It seems like the default behavior for this plugin is to generate a unique URL to each opened lightbox element by adding the ID to the end of the URL, and this allows people to access the opened lightbox element later. This isn't happening for me. I'm using fancybox to lightbox inline HTML content, and I really need the ability to deep link to the opened content. Can someone advise?

**Comment by fancyapps** [comment]
Hi,

Actually, it's simple. If you, for example, add `data-fancybox="hello"` attribute to your link, then this value (`#hello`) will be used to set current URL hash. 

And that works the other way, too. For example, if you open https://fancyapps.com/fancybox/3/#hello then the script looks for corresponding link and starts fancybox.

**Comment by Sorcutt** [comment]
Ah, thanks so much!!
