### ISSUE TITLE
applying an overlay color and opacity at onClick

### ISSUE THREAD

**Issue by halukkaramete** [fancyapps/fancybox#2109]
Is it possible to apply an overlay color and opacity at onClick and change that from click to click as desired?

I tried these but it did not work. 

html:

```HTML
        [a href="002.png" data-fancybox="gallery" data-caption="Al-Raheem"]
		[img src="002.png" style='max-width:150px' alt="" onClick='setFancy("background: antiquewhite;opacity: 1;")'/]
	[/a]
```

javascript:

```JS
	function setFancy($style){
                  ## attempt 1
		$combo = ".fancybox-is-open .fancybox-bg";
		$($combo).attr("style", $style);		

                  ## attempt 2
		// $( ".fancybox-bg" ).css( "background", "pink" ); // even thiss does not work 

	}
```

**Comment by fancyapps** [comment]
Hi,

You will not be able to change any style using inline click event, because that click will be executed before fancybox starts.

So, you could simply define your custom colors using data attributes and then use a callback to apply, example:

```JS
$('[data-fancybox="images"]').fancybox({
  onInit : function(instance) {
    // Change color on start
    var color = instance.group[instance.currIndex].opts.$orig.data('color');

    if (color) {
      instance.$refs.bg.css('background-color', color);
    }
  }, 
  beforeShow : function(instance, current) {
    // Change color when navigating the gallery
    var color = current.opts.$orig.data('color') || '';

     instance.$refs.bg.css('background-color', color);
  }
})

```
demo: https://codepen.io/anon/pen/qQdgYr

**Comment by halukkaramete** [comment]
Janis,

Your code which works like a charm at the codepen, does not apply the
styles in my implementation. I've looked and looked but can't see the darn
thing that is causing the failure. The problem is there is no js errors.
It's not a cache issue neither. I'm perplexed.
Iframe CSS you supplied also does not take effect.
Plus I'm dealing with a jerky behavior when opening and closing on the main
window. But that's for me to figure it out.

Would it be possible to quikcly take a look why your code does not kick in
in my implementation below?

<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="
https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.2/dist/jquery.fancybox.min.css
" />
<script src="
https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.2/dist/jquery.fancybox.min.js
"></script>
<style>

    .fancybox-slide--iframe {
        padding: 0 44px;
    }

</style>

<script>
// this is your code as is
        $('[data-fancybox="images"]').fancybox({
            onInit : function(instance) {
                // Change color on start
                var color = instance.group[instance.currIndex].opts.$orig.
data('color');
                alert('111' + color); // I just added this to see if this
guy ever runs!
                if (color) {
                instance.$refs.bg.css('background-color', color);
                }
            },
            beforeShow : function(instance, current) {
                // Change color when navigating the gallery
                var color = current.opts.$orig.data('color') || '';
                alert('222' + color);
                instance.$refs.bg.css('background-color', color);
            }
        })


        function openFrame($url){

            $.fancybox.open({
                src : $url,
                type : 'iframe',
                opts : {
                    afterShow : function( instance, current ) {
                        console.info( 'done!' );
                    }
                }
            });

        }
</script>


And as to the HTML I can got this:

<a href="_LOCAL_/001.png" data-fancybox="images" data-caption="Al-Rahman"
data-color="antiquewhite">
<img src="_LOCAL_/001.png" style='max-width:150px' alt="" />
</a>

<a href="_LOCAL_/002.png" data-fancybox="images" data-caption="Al-Raheem"
data-color="yellow">
<img src="_LOCAL_/002.png" style='max-width:150px' alt="" />
</a>

<hr>


<button onClick="$.fancybox.open('<div class=message><h2>Hello!</h2><p>You
are awesome!</p></div>');">open light box</button>

<hr>

<button onClick="openFrame('https://www.islamicity.org/ps')">open phonetic
search</button>

In action, it is in here:
https://www.islamicity.org/covers/99-names-of-Allah/
Scroll down all the way to the end where it says FANCY BOX IMAGES in red.

**Comment by fancyapps** [comment]
About your issue with the code - the reason is simple, you have placed js code before html, therefore either move js code to the bottom of the page or wrap the code inside `$(document).ready()`.

About the page shifting - I am not sure what causes this, but, if you remove `.cbp-spmenu-push` class from `body` element, then it works fine. I think it is because this class adds transition to every css property, but fancybox adds margin-right to compensate missing vertical scroll-bar. So, either try to fix that transition or maybe disable auto-hiding of page scrollbar (by setting `$.fancybox.defaults.hideScrollbar = false;`)

**Comment by halukkaramete** [comment]
You have made my day. Thank you so much my friend! It rocks now:
https://www.islamicity.org/covers/99-names-of-Allah/
