### ISSUE TITLE
is it possible to set the iframes' height to be say 100% and keep the X visible at all times?

### ISSUE THREAD

**Issue by halukkaramete** [fancyapps/fancybox#2110]
Hello, I noticed that the iframes open at an on-the-fly-determined height.  

I'd like to make them open at 100% in height. the default width is already great. 

I tried styling fancy-content class at the inspector and it has worked to my taste. But, when I added that instruction into the custom css as "height:100% important;" for that class, it made iframes happy but images sorry as the regular images got stretched out. So clearly, I'm doing it wrong. 

What is the trick to make the iframes ( and only iframes, not other inline content please ) to max out in height as much as possible? ( BTW when I say 100%, it is like 100%. it is OK to leave a visual margin just like you do it with the default width... )  

Also for usability, is it possible to keep that closer "X" at the top right? VISIBLE at all times as opposed to a hover.  Some users may just miss it even on the desktop if they are only using the keyboard. 

Thank you

**Comment by fancyapps** [comment]
Hi,

To disable iframe auto-height, set this option:

```JS
iframe : {
	preload : false
}
```

To remove top/bottom spacing, so that iframes can stretch to 100vh and to leave space for close button:

```CSS
.fancybox-slide--iframe {
  padding: 0 44px;
}
```
