### ISSUE TITLE
Looking for Fancybox v3.5 Customized Layout Demo in Codepen

### ISSUE THREAD

**Issue by mmoser-markl** [fancyapps/fancybox#2111]
I'm looking for the Customized Layout Demo that is currently in Fancybox 3 front page in Codepen.

here's the link:
https://www.fancyapps.com/fancybox/3/#cl-group-1

The nearest one I can find in Codepen is from v3.2 but it's not the same as the one on the front page:
https://codepen.io/fancyapps/pen/zPZeKb

Is there a demo for this?

**Comment by fancyapps** [comment]
Hi,

Here is that example on codepen - https://codepen.io/anon/pen/ZmWQPr

btw, if you have another ideas for some cool layout/design, then I can help with that.

**Comment by acwolff** [comment]
The text on the right panel does not change if I select another image.
Please show how to display there the caption of the images.

**Comment by fancyapps** [comment]
Did you take a look at the js code? Just remove `caption` option or replace with something else.

**Comment by acwolff** [comment]
Thanks, this looks good, I will try to implement this in my [FancyBox skin](
https://jalbum.net/en/skins/skin/FancyBox).

**Comment by acwolff** [comment]
I have one problem:

If I change the width in css code .fancybox-custom-layout .fancybox-caption to 512px or 50%, the arrow comes in the comment area.  (side panel).

How can I prevent this?

**Comment by mmoser-markl** [comment]
> Hi,
> 
> Here is that example on codepen - https://codepen.io/anon/pen/ZmWQPr
> 
> btw, if you have another ideas for some cool layout/design, then I can help with that.

Thank you. This is exactly what I'm looking for. Just one more additional and I'm done:

Is it possible to make a separate caption for every individual images? I understand that the caption on the right "interiors, exteriors, and the humans that inhabit them." doesn't change but can I add another one on top on the images (image of mountains, image of trees, image of coffee, etc.) and it changes when the images are changes.

So there's a one whole caption for the gallery that is fixed and captions for every images in that gallery.

**Comment by fancyapps** [comment]
It could be like this - https://codepen.io/anon/pen/MzyMjR - but it is not clear where exactly you want to add that tile.

**Comment by acwolff** [comment]
I implemented now a side window of 20% with this extra code:

    var widthSidePanel = 0;
    var widhImageStage =  0;
    var widhImageStagepx = '';
    var widthSidePanelpx = '';
    var widthSidePanelPercent = 20;

     $('[data-fancybox="S"]').fancybox({
        beforeShow : function() {
     		if (this.opts.caption.length === 0) {
    			$(".fancybox-custom-layout .fancybox-stage").css('width','100%');
     		} else {
    			widthSidePanel =  widthSidePanelPercent*window.innerWidth/100;
    		    widhImageStage= window.innerWidth - widthSidePanel - 44;
    			widhImageStagepx= widhImageStage.toString() + 'px';
    			widthSidePanelpx= widthSidePanel.toString() + 'px';
    			$(".fancybox-custom-layout .fancybox-stage").css('width',widhImageStagepx);
    			$(".fancybox-custom-layout .fancybox-caption").css('width',widthSidePanelpx);
    		};

This works fine as you can see in [my sample album](https://andrewolff.jalbum.net/ExtendedCommentSidePanel/)

However I have a problem: if I change the width of the window, the width of the side panel does not change, you see the efect only if you go to the next slide.

So my question is:

How can I force a window refresh (update) so that the code is executed after each resize?

**Comment by fancyapps** [comment]
Well, there is a `onUpdate` callback; and no one stops you from adding your own callback on window resize event.

**Comment by acwolff** [comment]
Thanks, I use now window resize and that solves the problem,  as you can see in [my sample album](https://andrewolff.jalbum.net/ExtendedCommentSidePanel/)

**Comment by fancyapps** [comment]
Seems to work fine. Anyway, 1) you can call `update` on instance object, for example `$.fancybox.getInstance().update()`, to refresh image size and position; 2) you have JS error on your page - `Uncaught ReferenceError: closeIndex is not defined` - any JS error can potentially cause problems

**Comment by acwolff** [comment]
Great!!

I removed the error and implemented your refresh code. It works now fine as you can see [here](https://andrewolff.jalbum.net/ExtendedCommentSidePanel/0 and [here](https://andrewolff.jalbum.net/ExtendedCommentSidePanelZigZag/).

Thanks for your quick help and your awesome library!
