### ISSUE TITLE
Why Ajax autoplays video and $.cookie not working

### ISSUE THREAD

**Issue by ShinJii89** [fancyapps/fancybox#2112]
Hi,
I have fancybox 3.5.2, in my links I have 

`data-fancybox data-type="ajax" data-src="url" href="javascript:;"`

Those links have video player Video.js (5.20.5) - fancybox autoplays videos, why? I have turned off this feature in player... so why fancybox click this or something after loading page? 

I also have in this pages loaded via ajax a library https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js - it's not working via fancybox - why? What should I do? there's error with $.cookie variable.

All these 2 issues doesn't exist when I go to page without fancybox.

**Comment by fancyapps** [comment]
Hi,

Set `video: { autoStart : false }`  to stop automatically playing html5 video.

Since you did not provide a link that demonstrates your second issue, I have no idea how to help you.

**Comment by ShinJii89** [comment]
It doesn't work after add autostart: false... it plays in the background but player is "freezed" only sound....can you check these 2 issues? 

For example here: https://strefadb.pl/filmy-kinowe/dragon-ball_01_legenda-shenlonga.html

I created account: fancybox password: fancybox

Click on orange link "VIP (bez reklam)" to load fancybox.

**Comment by fancyapps** [comment]
I do not see any problem, except the fact that your ajax request returns full source code of the page (all meta tags, scripts (so you have, for example) two jquery copies on your page), etc)
