### ISSUE TITLE
Share buttons window is too large for a mobile phone and 2 links are not working

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2116]
The Share window with the Share buttons is not responsive, it is too large to be used on my iPhone 5, see below.

The Share link to Facebook and Pinterest do not display the correct image as I explained already in issue #1974

Please correct this in the next version.

![1](https://user-images.githubusercontent.com/8150784/48306095-033b1b00-e536-11e8-904e-e9a1d86ad7f2.png)
![2](https://user-images.githubusercontent.com/8150784/48306096-07673880-e536-11e8-919f-1faa522b7fb0.png)

**Comment by fancyapps** [comment]
Everything works fine.
