### ISSUE TITLE
Combining multiple instance fancybox via open

### ISSUE THREAD

**Issue by mmativ** [fancyapps/fancybox#2117]
Hello, im trying to find a way to combine this multiple instance of fancybox. I have a pen for reference https://codepen.io/anon/pen/zMoOPW, if you look on that pen i have 4 galleries with 2 images per item, there's a way that i can navigate from gallery 1 to gallery 2?

**Comment by fancyapps** [comment]
Hi,

The simplest solution would be to display all images in one gallery and to set start index depending on which link was clicked - https://codepen.io/anon/pen/oQYNQx?editors=1010

If you want to have some kind of two-dimensional navigation, then there is no build-in functionality for that. You could create some additional navigation elements that would close current gallery and immediately open other, but I am not sure if that would satisfy your needs.
