### ISSUE TITLE
Larger arrows?

### ISSUE THREAD

**Issue by aolko** [fancyapps/fancybox#2120]
How do i painlessly resize next and previous arrow buttons? The styles are a bit wierd.

**Comment by fancyapps** [comment]
Hi,

Well, it is easy to say "Larger arrows?", but that could mean anything - larger icon, button or clicking area. So, what exactly are you looking for? 

The styles might seem to be a bit weird due to fact that "padding area" around button makes it easier to click (especially on mobile devices), but at the same time it does not cover whole content (like traditional lightbox-style scripts do).

**Comment by aolko** [comment]
larger button + slightly larger icon, not only because of the padding area, but because overall button sizes styles are wierd

**Comment by fancyapps** [comment]
Simply play with padding values. The idea is that clickable area is 70x100, the button is 38x38 and it is also pushed to right edge. For example, to increase button size to 48x48, set:

```CSS
.fancybox-navigation .fancybox-button {
  padding: 26px 6px 26px 16px;
}
```

https://codepen.io/anon/pen/VVWqOv?editors=1100

**Comment by acwolff** [comment]
Thanks for your hint!

I tried this code:

     $('[data-fancybox="S"]').fancybox({
     	idleTime: false,
    	onInit: function(instance) {
          var fancyBoxButtonpx = '44px';  // normal
    	  switch(roundButtonHeight) {
    	    case '50':  // largest
    				fancyBoxButtonpx = '63px';
    				break;
    	    case '42':  // large
    				fancyBoxButtonpx = '53px';
    				break;
       	    case '28':  // small
    				fancyBoxButtonpx = '35px'; ;
    				break;
    	    case '20':  // smallest
   				fancyBoxButtonpx = '25px';;
   				break;
       	  }
              $('.fancybox-button').css('width',fancyBoxButtonpx).css('height',fancyBoxButtonpx);

See [this test album](https://andrewolff.jalbum.net/Vecht_SaharaN_FB2/).

If you select in the viewer settings window Buttons size: largest, the toolbar buttons are indeed larger except for the thumbnails buitton.
But the navigation buttons are mutilated by this jQuery function.
