### ISSUE TITLE
How to change to size of the tool-bar and arrow buttons with css?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2123]
In albums made with [my jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) the viewer can select larger or smaller  buttons in the Viewer settings window. To see it, click the settings button in the upper right corner of [this example album](https://andrewolff.jalbum.net/FB_JustifiedGallery/) and select Button size: largest and next close that window.

This works OK on my thumbnails page, but not in the light-box.

So please give me a hint how I can adapt the size  of the tool-bar and arrow buttons in the light-box with jquery css code.

**Comment by fancyapps** [comment]
Simply set CSS `width`/`height` for `.fancybox-button` elements, as for navigation arrows see #2120
