### ISSUE TITLE
1px gap at bottom due to rounding issue?

### ISSUE THREAD

**Issue by winzig** [fancyapps/fancybox#2124]
In this screenshot you can see a 1px line being added to the bottom of an iframe being loaded by fancy box. It took me a while to realize what's happening. The video ratio is 1920:1080 (0.5625). At my browser size, the width of the iframe being shown here is 1192px, and if you multiply that by 0.5625 you get 670.5. Fancybox renders the iframe at 671px, rounding up. Video.js appears to be rounding down to 670px, thus a 1px gap. 

<img width="1264" alt="screen shot 2018-11-16 at 5 37 49 pm" src="https://user-images.githubusercontent.com/127062/48654997-af618380-e9c6-11e8-9514-462b73cab7e5.png">

Any recommendations for how to workaround this issue? Is there a way to control which way fancy box rounds it's ratio calculations, or should I focus on trying to adjust video.js to round differently?

**Comment by fancyapps** [comment]
Hi,

Actually, I believe that fancybox does math correctly, because height should be rounded up to avoid scrollbars. In your case, the best solution would be to simply make background transparent, for example:

```
.fancybox-slide--iframe .fancybox-content {
	background: transparent;
}
```

Also, did you manage to make videojs responsive? I could not make it work after a few tries.

**Comment by winzig** [comment]
@fancyapps Thank you, this works!

To answer your question: I think so. :trollface: 

Below is a sample of what my iframe content page returns for videos to be embedded into a fancy box view. I set the aspectRatio based on the width/height data stored for each video.

```
<video id="video-player-f1dmeitcq4gupxq0b43x4sa6u1" preload="none" data-setup='{ "responsive": true, "html5": { "hls": { "overrideNative": true } }, "aspectRatio": "1920:1080", "playbackRates": [1, 1.5, 2] }' class="vjs-tech" poster="/file/f1dmeitcq4gupxq0b43x4sa6u1/lg" tabindex="-1">
    <source src="/file/f1dmeitcq4gupxq0b43x4sa6u1/hls" type="application/x-mpegURL">
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank" class="vjs-hidden" hidden="hidden">supports HTML5 video</a>.</p>
</video>
```
