### ISSUE TITLE
Scrollable Ajax content jumps to the middle after opening on mobile device.

### ISSUE THREAD

**Issue by vanduzled** [fancyapps/fancybox#2125]
I have a fancy box link that opens an Ajax content that is longer than the viewport on mobile (iPhone 8) and after opening the fancybox, the content jumps in the middle instead of staying on the top. 

The close button [X] also seems not to be fixed to the top right. It moves with the content while scrolled before staying again to the top right. 

**Note:**
When you inspect it on chrome with the 'toggle device toolbar', the problem doesn't show up. Although it used to before. What I did was I made the height of .fancybox-container and .bleed to _auto_ instead of _100%_ and it doesn't show up anymore. However, on actual mobile device, it still does. As a matter of fact, the outcome that I want is that of the chrome on desktop when you toggle it to mobile. 

**How to recreate the issue:** open on mobile device, click on the card (the fancybox)
**Expected:** content should stay on top unless scrolled. Close button should stay fixed on top right.
**Current state:** content jumps to the middle. Close button moves.
**Device:** iPhone 8 
**Browser:** Safari, Chrome, Firefox, 
**Framework:** Foundation 8 for sites
**Other scripts:** Flickity on the Fancybox content

Please see the site here:
http://theworkplacepm.com/xyz/#fil-a-1

Edit: I realize that it also happens on desktop. I'm using a 13 inches laptop and on this page (http://theworkplacepm.com/xyz/#fil-d-2), the content jumps to the middle also.

**Comment by vanduzled** [comment]
I found the issue. It's anchoring to the .customnav. Hiding it in CSS solves the problem. But, it's also anchoring to .withcarousel which I cannot hide because it's where the carousel is. Now I don't know why it's making the page drop. 

Visit the link below on mobile: 

http://theworkplacepm.com/xyz/#fil-c

**Comment by fancyapps** [comment]
Hi,

Most likely this is caused by "auto focus" feature, to disable this, set `autoFocus: false`.

**Comment by vanduzled** [comment]
> Hi,
> 
> Most likely this is caused by "auto focus" feature, to disable this, set `autoFocus: false`.

It is that. Thanks!
