### ISSUE TITLE
Loading different image sizes depending on viewport size?

### ISSUE THREAD

**Issue by Toccamonium** [fancyapps/fancybox#2127]
Hi,
Fancybox 3 offers a lot of cool possibilities, thx.

Right now I'm trying to optimize my website for mobile. When I click the thumbnails on my smartphone, I always will get the same size as images, which is defined in the link. That means also with bad mobile connection, visitors have to load a lot of kB. Is there a methode, which allows to load different image sizes depending on the view port size?

Thx!

**Comment by Patta** [comment]
@Toccamonium I don't think it's possible with fancybox. Responsive images in href isn't possible i think. Maybe you could do some magic before fancybox load the file in href. Maybe lazysizes can help.

**Comment by fancyapps** [comment]
Hi,

Fancybox v3 supports `srcset` to load different image depending on the screen size, dheck docs - https://fancyapps.com/fancybox/3/docs/#images and this demo - https://codepen.io/fancyapps/pen/LJwvzY?editors=1000

Keep in mind that browsers handle `srcset` differently and sometimes unpredictable, therefore v4 will support "responsiveness" differently.
