### ISSUE TITLE
Fancybox pop displays does not display content starting from the top 

### ISSUE THREAD

**Issue by parasktm** [fancyapps/fancybox#2129]
I've embedded fancybox pop up in a button. At first click, it works perfectly; the content begins at the starting point (top). However when i scroll the content to lower levels and close then when i click the button (same or another one in the same page), the popup content doesn't start from the beginning. It starts from some lower level, may be the level I clicked close button on previous popup. Have anyone experienced such problem. Can you suggest what should i do?

**Comment by fancyapps** [comment]
Hi,

If you are displaying inline content, the script moves it to the right place in DOM and puts back after closing the modal. So, any changes user has made to the content (including scrolling) are not discarded. If you wish, you can use callbacks (`afterLoad`, for example) to ... tweak something to your likening.
