### ISSUE TITLE
Version 3.5.2 youtube fullscreen not available in chrome

### ISSUE THREAD

**Issue by jackpi2018** [fancyapps/fancybox#2132]
Hi. i have an issue about the fancybox in version 3.5.2. Youtube fullscreen button not available when browsing in Chrome. (but in Firefox, Edge, IE it works). It works in the fancybox demo page (https://fancyapps.com/fancybox/3/).
However when i do it locally it cannot work.
I have tried the older version which is 3.4.1 it works locally in Chrome.  After version 3.4.2 it start not working in Chrome.

**Comment by fancyapps** [comment]
Hi,

Do not test video/iframes/ajax locally, you have to use web server to get full functionality due to browser security policies.

**Comment by jackpi2018** [comment]
Hi I have try it on the web server but it has the same issue at chrome as well.
Below is the code I test in the web server. Anything I miss out?
`<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Test Fancy Box</title>
	
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.css">
</head>
<body>

    <a href="https://source.unsplash.com/IvfoDk30JnI/1500x1000" data-fancybox="ty" data-caption="&lt;b&gt;Single photo&lt;/b&gt;&lt;br /&gt;Caption can contain &lt;em&gt;any&lt;/em&gt; HTML elements">
        <img src="https://source.unsplash.com/IvfoDk30JnI/240x160" />
    </a>
    
    <a href="https://source.unsplash.com/0JYgd2QuMfw/1500x1000" data-fancybox="ty" data-caption="This image has a simple caption">
        <img src="https://source.unsplash.com/0JYgd2QuMfw/240x160" />
    </a>
    
    <a href="https://source.unsplash.com/xAgvgQpYsf4/1500x1000" data-fancybox="ty">
        <img src="https://source.unsplash.com/xAgvgQpYsf4/240x160" />
    </a>
    <a data-fancybox="ty" href="https://www.youtube.com/watch?v=_sI_Ps7JSEk">
        <img class="card-img-top img-fluid" src="http://img.youtube.com/vi/_sI_Ps7JSEk/mqdefault.jpg" />
    </a>
    </p>

	
	<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.js"></script>
</body>
</html>`

**Comment by fancyapps** [comment]
After some experimenting, I discovered that Google has recently made some changes (they are quite famous about their privacy policies) and now they do not allow full-screen for embeds that are using `src="//www.youtube.com...`  or `src="//www.youtube-nocookie.com...`. I think this is because they are now forcing https for youtube and the web (https://developers.google.com/web/updates/2016/10/avoid-not-secure-warn). 

So, changing embeds to `src="https://www.youtube.com` seems to fix this issue and this will be included in the next update. Thanks for bringing this up.

**Comment by jackpi2018** [comment]
ok thanks. may i know any alternative solution for current latest version(3.5.2)?

**Comment by jackpi2018** [comment]
thank you so much. It works.

**Comment by jackpi2018** [comment]
Where should i put this command? is this a global functions apply to all videos?

**Comment by jackpi2018** [comment]
ok. thank you so much. it works.

**Comment by ozgunmustafa** [comment]
$.fancybox.defaults.media.youtube = { url : 'https://www.youtube-nocookie.com/embed/pCZqcp-jZhw' };
this code not working. I see this message " Video unavaliable"

**Comment by fancyapps** [comment]
Your code is strange, check docs on how to use API.

**Comment by acwolff** [comment]
On my website the full screen button works fine with Chrome, as youy can see here:
https://www.andrewolff.nl/FotoSerie/Algarve/Videos/index.html
