### ISSUE TITLE
How to add a vertical scrollbar?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2135]
In [this jAlbum FancyBox album](https://andrewolff.jalbum.net/ExtendedComment_FB/) I added the possibility to show a very large caption in the light-box. To see it, click on the first image and next on the 'More info' link.

If you do this on a small device like an iPhone, you can't read the whole description, because you can't scroll the text.

So my request is:

Please give a hint how I can add temporarily a vertical scroll bar so that I can also scroll the text on an iPhone.

**Comment by fancyapps** [comment]
Hi,

Something like this should do the trick:

```CSS
.fancybox-caption {
	max-height: 50vh;
	overflow: auto;
}
```

I think I'll add include this snippet in the css.

**Comment by acwolff** [comment]
Yes that works fantastically !!
You are a genius thank you very much!

[My jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) has now 4 methods to display large descriptions, see the last 4 albums in [this survey of possibilities](https://andrewolff.jalbum.net/FB_Samples_AA/).
