### ISSUE TITLE
disable scrollbars

### ISSUE THREAD

**Issue by jiggy1965** [fancyapps/fancybox#2136]
I've been using this to get rid of any scrollbars when I load iframes in Fancyboxes.

`$('[data-fancybox]').fancybox({
    toolbar: false,
    smallBtn: true,
    iframe: {
        scrolling: 'no',
        padding: 0,
        preload: false
    }
})`

When I click a Fancybox link, there are indeed no scrollbars, but for a millisecond while the iframe loads those scrollbars are visible and then disappear. How do I completely disable any scrollbars on loaded iframes?

**Comment by fancyapps** [comment]
Sorry, I could not reproduce this.

**Comment by jiggy1965** [comment]
You can see a sample here:
https://bannersetje.nl/voorbeeld/previewer2019/index.html
In both Safari and Chrome when you open up the Fancybox for a millisecond the scrollbars are visible.

**Comment by fancyapps** [comment]
No wonder I was not able to reproduce this issue, replace


```JS
$('[data-fancybox]').fancybox({
    toolbar: false,
    smallBtn: true,
    iframe: {
        scrolling: 'no',
        padding: 0,
        preload: false
    }
});
```

with

```JS
$('[data-fancybox]').fancybox({
  toolbar: false,
  smallBtn: true,
  iframe: {
    attr: { scrolling: 'no'},
    css : { padding: 0, background: '#009999' },
    preload: false
  }
});
```
