### ISSUE TITLE
Bug with Bootstrap V4 Grid Layout?

### ISSUE THREAD

**Issue by zwantE** [fancyapps/fancybox#2138]
Hey,

i want use the Bootstrap grid layout in an inline overlay elemnt.

But the container - row - col doesnt have the width of it :/

here is a fiddle -> https://jsfiddle.net/zwantE/ujwLd18n/1/

In earlier Versions it works it fine :/

**Comment by fancyapps** [comment]
Hi,

In your demo, you are displaying ` id="hidden-content"` element. That element has no css `width` value and adapts content width by default. If you want to have it 100% width, then you have to add corresponding css rule. 

If you want to remove gap around your element, then set `padding:0` to parent element (­`.fancybox-slide--html`).
