### ISSUE TITLE
More Transition effects between slides

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2139]
The FancyBox library offers already a nice set of transition effects, but I see still opportunities to make it even better.

So please could you think about 3D transition effects like [this book effect](http://samples.jalbum.net/ProjectorBlogpost/Book/#img=rawpixel-800841-unsplash.jpg) and [this cube effect](http://samples.jalbum.net/ProjectorBlogpost/Cube/#img=rawpixel-800841-unsplash.jpg), may be you can implement this in the next release?

More new transition effects [here](https://jalbum.net/blog/entry/the-slideshow-must-go-on).

**Comment by fancyapps** [comment]
Hi,

Well, different people have different taste. In my opinion, these are terrible examples. 

There is already a feature request for "ken burns" effect which I think is pretty nice, but it is not possible to implement that into current code without heavy rewrite. Therefore it will be implemented in v4 and maybe it will be also possible to add other effects like book/cube, too.

**Comment by acwolff** [comment]
Thanks in advance!
