### ISSUE TITLE
Suggestions for the new release

### ISSUE THREAD

**Issue by Merg1255** [fancyapps/fancyBox#214]
Hi Janis! Thanks for this great plugin :)
Here's are a few things I'd like to suggest for the next version, than can be quickly implemented:
1. Allow option to set background for class `.fancybox-outer` together with `.fancybox-opened .fancybox-outer`. This way you'll be able to set custom background colors, ie black or white.
2. Allow for `.fancybox-opened .fancybox-outer` custom box-shadow. (so it could be set through the object)
3. Mousewheel scroll: Could you also add horizontal effect for mousewheel?
4. Allow to set the text inside the photo to cover the full width of the window. ie in the demo single images, the last image with a text inside the box could have the background fill the entire image area, not just a square box.
5. Allow .fancybox-outer to set specific border-radius.
6. Add hover effect for button helpers, to appear dynamic.
7. Allow `.fancybox-overlay` opacity to be set without having to specify helpers object.
8. Add a message with custom duration when clicking on a gallery image to notify the user that he can use the mousewheel (that's for the case where there aren't set any arrows)
9. IE8 right arrow has something like a border, as in here: http://i44.tinypic.com/2a4xocl.png
10. Messages like "Next" should only display when mouse hover is close to the arrow, http://i44.tinypic.com/2a4xocl.png
11. Options to hide messages like "next" with arrows.
12. Allow custom loader icon.
13. Allow option for custom click handler inside the image (alternative option to nextClick: true)
14. documentation: add one more row with the default values for each option, and more examples. ie an example for wrapcss.

We're choosing a suitable plugin this week, fancybox looks great so paching most of the above would be nice! :)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
