### ISSUE TITLE
Click on .fancybox-close-small

### ISSUE THREAD

**Issue by Rishat7c** [fancyapps/fancybox#2140]
When I clicked on the `fancybox-close-small` button, I wanted to remove some content on the page.

I wanted to do this on jquery
```Javascript
     $(document) .on('click', '.fancybox-close-small', function () {
         $('#hidden-contacts').empty();
         // others moment ...
     });
```
But it didn't work. because fancybox works faster, and jquery does not have time to work. Tell me how you can solve this problem.

**Comment by fancyapps** [comment]
Hi,

You could, for example, disable that button completely by setting `smallBtn: false` and then use your own close button element (tip: you can make any element to act as a close button by adding `data-fancybox-close` attribute). Or maybe change html code of that button to something else (using `btnTpl : { smallBtn : 'your custom html code' }`) and then set custom click event for that.

Another solution would be to use `beforeClose` callback - you can use it to do your stuff before closing and you could prevent closing (by returning `false`) if needed. (tip: `beforeClose` callback receives click event, so you can check where user has clicked).
