### ISSUE TITLE
Make zoom mobile possible

### ISSUE THREAD

**Issue by jiggy1965** [fancyapps/fancybox#2142]
On mobile I can't zoom into my page with Fancyboxes when one is opened as that closes the Fancybox again. Is  there some option to disable that I can can close a box by tapping the close button or the surface around it, but not when I zoom on the web page on mobile?

So when I open a box on my web page and wish to zoom in to see it clearer on mobile, I can't cause that will make the box automatically close again. It should only close the normal way by tapping the space around the box or the close button. But not when I try to zoom in into an opened box.

**Comment by fancyapps** [comment]
Hi,

It is not cleat what do you mean by "zoom" and your comment is just incomprehensible. 

Pinch-to-zoom is enabled by default for images.

**Comment by jiggy1965** [comment]
I thought I was pretty clear about it :-)
Have a look at below page on your smartphone.
https://bannersetje.nl/voorbeeld/previewer2019/index.html
You can pinch-to-zoom of course. But don't do that just yet and tap one of those 'bekijk' buttons in order to open a Fancybox with an iframe. Then try to pinch-to-zoom. You will fail as it won't zoom in into that iframe Fancybox anymore. Also you can't swipe the page around to get the iframe into view when needed. It will most likely just close the iframe Fancybox again.

So is there some option to have the iframe Fancybox opened but make it still possible to pinch-zo-zoom and the pan the page?

**Comment by fancyapps** [comment]
Oh, I see, simply set `touch:false` to disable touch actions.
