### ISSUE TITLE
Ability to cancel the display of fancybox via the callbacks

### ISSUE THREAD

**Issue by brendon** [fancyapps/fancybox#2145]
I have a use case where users supply the link that fancybox will attempt to display. I'm checking if the `contentType` is `html` in the `afterLoad` callback, and if so, I just redirect the browser to that link (as it might not load nicely in an iframe etc...).

It doesn't look like there is currently a way to cancel the display of a slide / close the fancybox interface from the callbacks. Would you be interested in adding this as an option? There's a couple of scenarios:

- Allow cancelling the fancybox display routine if the first slide to load doesn't meet our requirements. Maybe add a new callback `afterLoadFirst`?
- Allow closing the fancybox interface if a slide doesn't meet our requirements (from afterLoad).

The second one isn't a need of mine, but the first would be handy.

**Comment by fancyapps** [comment]
Hi,

If I understand you correctly, you are trying to do it like this:

user clicks -> fancybox starts -> you check content -> decide to display content or not

But I would suggest you to do it the other way around:

user clicks -> you check content (inside your custom click handler) -> you decide to start fancybox (using `$.fancybox.open()`) or not.

**Comment by brendon** [comment]
Thanks @fancyapps, yes that would work except we'd have to re-implement your code around detecting the content type of the link etc... In my case, I wanted to cancel loading the interface if the contentType came out as 'html'. I'd be redirecting the user to the new page in that case. My workaround was just to change the content of the slide to 'Redirecting...' so that they didn't potentially see the default error message while waiting for the redirect. Preferably I'd like to be able to just not show the fancybox interface and redirect.

**Comment by fancyapps** [comment]
Sorry, it is currently not possible to cancel starting the fancybox. So, I can see two options:

1) Change content, for example:

```JS
afterLoad : function(instance, current) {

  if (current.type === 'html' && !current.processed) {
    // Avoid infinite loop
    current.processed = true;

    // Change content
    instance.setContent(current, '<p>Redirecting...</p>');

    // Do your stuff
    // ...
  }
}
```

2) Hide interface while doing your stuff:

```JS
onInit : function(instance) {
  instance.$refs.container.hide();

  // Do your stuff
  // ...
}
```

**Comment by brendon** [comment]
Thanks @fancyapps, your first example is actually what I ended up coming up with and it works well :)

**Comment by brendon** [comment]
Just to follow this up. I found it was better to check for `slide.$slide.hasClass('fancybox-slide--error')` rather than `current.type === 'html'` because that could lead to false positives when we really do want to show inline html :)
