### ISSUE TITLE
Caption overlaps bottom video-controls since version 3.5.3

### ISSUE THREAD

**Issue by nebrot** [fancyapps/fancybox#2147]
Because of the padding-change in https://github.com/fancyapps/fancybox/commit/5f7dd4726714c2d97d48efd8824d0eb50899f7c1#diff-fc88bef47b5845f6c51c59c284eaaef8R421 , the buttons like fullscreen in bottom controlbar of YouTube and other videos are not fully usable/clickable anymore.

Example: https://codepen.io/fancyapps/full/GXVLyr

Chrome 71
Firefox 63
Fancybox 3.5.3

![fb-caption-video](https://user-images.githubusercontent.com/6941112/49791424-c333a780-fd30-11e8-8043-93b26462987e.png)

**Comment by fancyapps** [comment]
Thanks, I'll take a look.
