### ISSUE TITLE
iPad: Darkened background overlay disappears when videos begin playing

### ISSUE THREAD

**Issue by PaulParker** [fancyapps/fancybox#2148]
We're seeing some videos cause the darkened background overlay to disappear after the video begins playing. We're using video.js to play the video. It doesn't happen for all videos, and it seems to only happen on iPad.

Device/browser: iOS 12/iPad, Safari
Fancybox version: v3.5.3

Failure screenshot:
![image](https://user-images.githubusercontent.com/3614950/49823977-ca10e900-fd35-11e8-9303-ca0d3188a34a.png)

Non-failure screenshot (once video stops playing, the darkened background comes back).
![image](https://user-images.githubusercontent.com/3614950/49824006-e14fd680-fd35-11e8-98a0-c23da637999f.png)

**Comment by fancyapps** [comment]
Hi,

Could you, please, create a live demo or provide a link to your page where this issue could be inspected?
