### ISSUE TITLE
Groups no longer working?

### ISSUE THREAD

**Issue by W1zzardTPU** [fancyapps/fancybox#2149]
https://codepen.io/fancyapps/pen/wEVOPa

That's from the official documentation and goes straight through all 8 pics instead of having two separate galleries

**Comment by nebrot** [comment]
In the example they have all the same attribute data-fancybox="images", so they are all part of this one gallery. Change some of the items it for example to data-fancybox="images2", then you have two different galleries.

**Comment by W1zzardTPU** [comment]
You are right, my bad
