### ISSUE TITLE
Caption is not cleared in version 3.5.4

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2150]
If the first slide has a caption and the following slides don'n have a caption, the caption of the first slide is displayed under the 2nd and next slide. See here for an example: https://codepen.io/acwolff/pen/ebpoeq

**Comment by acwolff** [comment]
Thanks for your quick fix, I can confirm that it works now correctly in version 3.5.5

However I have still problems with this css code:

    @supports (padding: max(0px)) {
    .fancybox-caption {
            padding: 75px max(44px, env(safe-area-inset-right)) max(25px, env(safe-area-inset-bottom)) max(44px, env(safe-area-inset-left));
        }
    }

With that code I get on an iPhoneXR:
![problem](https://user-images.githubusercontent.com/8150784/49936084-47259500-fed3-11e8-87c5-6400b4e75c78.PNG)

To get it correct I changed it into:

    @supports (padding: max(0px)) {
        .fancybox-caption {
            padding: 12px max(44px, env(safe-area-inset-right)) max(12px, env(safe-area-inset-bottom)) max(44px, env(safe-area-inset-left));
        }
   }

In that case I see this:
![ok](https://user-images.githubusercontent.com/8150784/49936154-7d631480-fed3-11e8-8648-884d78cbbbe8.PNG)

**Comment by fancyapps** [comment]
That is how it works now - the top space allows to have a nice background gradient (in default design). Previously, that effect was archived using pseudo element, but the problem is that pseudo elements scroll, if element is scrollable, therefore caption now has inner element for actual content and outer element has background.

**Comment by acwolff** [comment]
Well I think your solution is not working correctly:

With your solution I see on a PC:

<img width="462" alt="pc-gradientl" src="https://user-images.githubusercontent.com/8150784/49992072-4e0be080-ff83-11e8-8a2d-a73de80af29c.PNG">

and on an iPhone XR:
![iphonefbsolution](https://user-images.githubusercontent.com/8150784/49992093-5ebc5680-ff83-11e8-98a0-adf9368f1283.PNG)

Wy should I see a different view on a mobile phone?

With my solution 

    @pjdelport supports (padding: max(0px)) {
        .fancybox-caption { /* AW */
            padding: 12px max(44px, env(safe-area-inset-right)) max(12px, env(safe-area-inset-bottom)) max(44px, env(safe-area-inset-left));
        }
    }
I get on the iPhone the same view as opn a PC:

![iphonemysolution](https://user-images.githubusercontent.com/8150784/49992295-e6a26080-ff83-11e8-9db7-cececfe0150b.PNG)
