### ISSUE TITLE
Swipes over the caption is no longer working in version 3.5.5

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2151]
Open this album: https://andrewolff.jalbum.net/ExtendedCommentDirectVisible_FB/ and click on the Library image.

Next swipe on a mobile device like an iPad over the caption. The next image is not displayed.

This was working fine fine with version 3.5.3, see:https://andrewolff.jalbum.net/ExtendedCommentDirectVisible_3.5.3/

**Comment by fancyapps** [comment]
That is expected behavior.

**Comment by acwolff** [comment]
Why is the expected behavior in version 3.5.5 different from version 3.5.3. ??

**Comment by acwolff** [comment]
It is no longer working due to the introduction of
.fancybox-caption__body

If I  remove that CSS code, swiping over the caption works again.

**Comment by acwolff** [comment]
Yes this problem has been solved in version 3.5.6, thanks youvery much!

Unfortunely issue #2152 has not been solved.
