### ISSUE TITLE
Scrolling comment in a side panel no longer works in version 3.5.5

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2152]
In [this album](https://andrewolff.jalbum.net/ExtendedCommentSidePanel/) I use side panels to show long comments.
If you click the first image you see a side panel with a scrollbar. If I use that scroll bar, the light-box is now closed. This was working fine in version 3.5.3.

Please help me to let this work again in this version 3.5.5

**Comment by fancyapps** [comment]
Could you try the latest update?

**Comment by acwolff** [comment]
Yes I tried the last update, see [here](https://andrewolff.jalbum.net/ExtendedCommentSidePanel/), but unfortunately, scrolling the text in a side panel is not possible. I use the code proposed by you in one of your Codepen examples.

**Comment by acwolff** [comment]
I have it working now in Codepen:
https://codepen.io/acwolff/pen/qLZOLv
