### ISSUE TITLE
The added padding for iPhones with notch, introduced in v3.5.3 breaks compiling with sass

### ISSUE THREAD

**Issue by tomfischerNL** [fancyapps/fancybox#2153]
**Describe the bug**
The added padding for iPhones with notch, introduced in v3.5.3 breaks compiling with sass. Working with Webpack and compiling a sass file where the @fancyapps/fancybox/dist/jquery.fancybox is imported, fails after version 3.5.3.

>    padding: 75px max(44px, env(safe-area-inset-right)) max(25px, env(safe-area-inset-bottom)) 
>    max(44px, env(safe-area-inset-left));
>                      
>    env(safe-area-inset-right)" is not a number for `max'
>    in /node_modules/@fancyapps/fancybox/dist/jquery.fancybox.css (line 485, column 23)"

'max(44px, env(safe-area-inset-right)', 

**To Reproduce**

1. Install webpack
2. Compile with sass and use the import:  @import './node_modules/@fancyapps/fancybox/dist/jquery.fancybox';
3. See error (shown above) 

**Additional context**
The possible fix: Use unquote method like described here:
https://github.com/sass/sass/issues/2378#issuecomment-367490840

To get the following (working) code. 

```
@supports (padding: max(0px)) {
    .fancybox-caption {
        padding: 75px unquote('max(44px, env(safe-area-inset-right))') unquote('max(25px, env(safe-area-inset-bottom))') unquote('max(44px, env(safe-area-inset-left))');
    }
}

@supports (padding: max(0px)) {
    .fancybox-caption {
        padding-left: unquote('max(12px, env(safe-area-inset-left))');
        padding-right: unquote('max(12px, env(safe-area-inset-right))');
    }
}
```

**Comment by fancyapps** [comment]
Hi,

Well, the authors or WebKit introduced  

> new CSS function, env(), and a set of four pre-defined environment variables 

more than year ago - https://webkit.org/blog/7929/designing-websites-for-iphone-x/

Sadly, it was not enough time for developers of saas to figure out how to incorporate them. What is worse - saas replaces `@supports(padding: max(0px)) {` with `@supports(padding: 0px) {` and I do not know how to overcome this...

**Comment by stratboy** [comment]
Me too, using codeki app, I do not compile anymore..
So, implement the unquote fix by default?

**Comment by n-rodriguez** [comment]
https://semver.org/

**Comment by wateengoedidee** [comment]
> Hi,
> 
> Well, the authors or WebKit introduced
> 
> > new CSS function, env(), and a set of four pre-defined environment variables
> 
> more than a year ago - https://webkit.org/blog/7929/designing-websites-for-iphone-x/
> 
> Sadly, it was not enough time for developers of saas to figure out how to incorporate them. What is worse - saas replaces `@supports(padding: max(0px)) {` with `@supports(padding: 0px) {` and I do not know how to overcome this...

Maybe implement the unquote fix by default indeed? ;)

**Comment by hadl** [comment]
Defining functions locally as a workaround works pretty good:
https://github.com/sass/sass/issues/2378#issuecomment-433868712

**Comment by stratboy** [comment]
How about implementing the unquote fix by default?

**Comment by brooksco** [comment]
Can the unquote fix be implemented?

**Comment by fancyapps** [comment]
Just do not throw all .css files to SASS processor, it just does not make any sense.
