### ISSUE TITLE
Resizing iframes for portrait (tall) content

### ISSUE THREAD

**Issue by winzig** [fancyapps/fancybox#2157]
The docs state:

> If you have not disabled iframe preloading (using preload option), the script will atempt to calculate content dimensions and will adjust width/height of <iframe> to fit with content in it.

Is there documentation somewhere that explains how it goes about doing this? We're using fancy box to show mixed media, including iframes that contain responsive video players. They look great with landscape (wide) videos, but for tall videos they tend to stretch way off screen. 

Is there a way to put something in the embed content to signal to fancybox what height/weight and/or aspect ratio to use? (We don't know this info on the link side.)

**Comment by fancyapps** [comment]
Hi,

The script calculates width/height of `body` element - https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L2031

It was not designed to support responsive videos inside iframe. Why would you want to do that?

**Comment by winzig** [comment]
Because the videos we're looking to are of all different aspect ratios?

**Comment by fancyapps** [comment]
But you can display youtube/vimeo/html5 videos out of the box and they will resize correctly.

**Comment by winzig** [comment]
I'll take another look at this option. We already have existing pages designed specifically for embedding, so we were trying to have fancybox just use those.

**Comment by fancyapps** [comment]
Then I would suggest you to calculate video width/height on page load / window resize and then execute  `parent.jQuery.fancybox.getInstance().update();`

**Comment by winzig** [comment]
@fancyapps Once I know the width/height I want my iframe to be, where am I setting these values before I call `parent.jQuery.fancybox.getInstance().update();`? I've tried using afterLoad and setting current.width/current.height as shown in the docs, but that doesn't seem to do anything, with or without a call to getInstance().update():

```
{
    afterLoad : function(instance, current) {
        current.width  = newWidth;
        current.height = newHeight;
        // parent.jQuery.fancybox.getInstance().update()
    }
}
```

**Comment by winzig** [comment]
I'm guessing instead of setting current.width and current.height, I really want to set current.$iframe.width/height, and then call update()? Are the docs wrong or am I misunderstanding what [that example](http://fancyapps.com/fancybox/3/docs/#images) is showing how to do?

**Comment by fancyapps** [comment]
In the previous comment, I was thinking that you would do that from within the iframed page. E.g., you would do your calculations, set dimensions for some element (any element - div, video, body - as long as body would have some reasonable dimensions) and then you would update the fancybox, if needed.

If you want to do resizing from within fancybox instance, then you could use `onUpdate` callback.
