### ISSUE TITLE
iframe width problem since 3.4.1

### ISSUE THREAD

**Issue by wnedoe** [fancyapps/fancybox#2158]
I do not know if this is intentional but since 3.4.1. 
the behaviour of  iframe popups has changed and I cant get them to accept the CSS **width** anymore. 

In 3.4.0 it woks as it should in 3.4.1. not.  

.fancybox-slide--iframe .fancybox-content{
	**width  : 500px;**
	height : 600px;
	max-width  : 90%;
	max-height : 90%;
	margin: 0;
}

with fancybox 3.4.0 it works 

with fancybox 3.4.1+ it does not 

other arguments like background-color, max width are used but the widtg is ignored?? 

To make strange things weird:  

The codepen examples of fancybox 3.5.6 work as they should and do not ignore the **width**  
here: 
https://codepen.io/fancyapps/pen/pOMBQx

BUT:
To find out why i put the Codepen code on my website and it does not work either :-( 
the  "width:  400px "  is also ignored   

https://www.terraristik.com/tb/test/test_fancy3.html

WHAT IS WRONG HERE?

**Comment by fancyapps** [comment]
Hi,

Replace `$('.fancybox').fancybox()` with `$('[data-fancybox]').fancybox()` or `$('[data-type="iframe"]').fancybox()`

**Comment by wnedoe** [comment]
Ok THANK YOU 

The "Replace $('.fancybox').fancybox() with $('[data-fancybox]').fancybox()  "  did not work   but now it works as i have understood that preloading has to be false and the script has to be at the end in order to work.  

Before 3.4.1 the script was not needed

**Comment by fancyapps** [comment]
> Before 3.4.1 the script was not needed

I has been working like this since the beginning, but iframe content dimension calculations were improved in v3.4.2 (https://github.com/fancyapps/fancybox/releases/tag/v3.4.2) and most likely that affected you.
