### ISSUE TITLE
$.fancybox.defaults.playSpeed

### ISSUE THREAD

**Issue by halukkaramete** [fancyapps/fancybox#2159]
Hi fancyapps,

I have a question on "$.fancybox.defaults.playSpeed" 

Please take a look at the following URL's view source and see that it's part of the main HTML:
https://www.islamicity.org/covers/99-names-of-allah/
as $.fancybox.defaults.playSpeed = 10000;
However, this does not seem to work as the play speed is still 3 seconds as you can see from the overlay popup:
https://www.islamicity.org/covers/99-names-of-allah/#id-2

(which you can get to by clicking on the calligraphy from the main page ).

Where am I making a mistake?

**Comment by fancyapps** [comment]
Hi,

If I remember correctly, `playSpeed` was used in early versions, because you have to set it like this for a long time:

```JS
slideShow: {
    autoStart: false,
    speed: 3000
}
```

**Comment by halukkaramete** [comment]
Thank you, but this does not seem to work, for me. 
I even changed the core (core.js, min.js, slideshow.js and wherever you used to word "speed" & 3000 ) and then replaced every occurrence of the "3000" in those file with "9998" and then expire the js cache to make sure I get the modified code, running. No luck. The slideshow has a mind of its own to run it at approximately 3000 ms per slide.
