### ISSUE TITLE
How to use custom caption source using data attribute?

### ISSUE THREAD

**Issue by ableslayer** [fancyapps/fancybox#2160]
I'm using Fancybox with Wordpress so I have several images with captions and separate IDs. When Fancybox is loaded, I want links (download options, links to other materials) to appear on the fancybox. But you can't put links right? Because it will conflict with the anchor tag. 

So I want to put the caption source on a separate div using data attribute as its marker. 

Here's a codepen that doesn't work because I'm not sure how to do it.
https://codepen.io/ableslayer/pen/JwNppa

**Comment by fancyapps** [comment]
Hi,

You can put anchors in `data-caption`, but you have to escape html code (using `htmlspecialchars`).
But your snippet could be fixed like this - https://codepen.io/anon/pen/BvRGeY

**Comment by ableslayer** [comment]
Perfect. Thanks!
