### ISSUE TITLE
Refreshing page, config not used

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#2161]
Clicking an image to launch fancybox uses my config. If I then refresh the page, it will open the gallery again, but NOT using my config. How can I ensure that my config gets used on reload? This used to be the case, but in upgrading from 3.2.1 to the current 3.5.6 release, the config is not getting loaded on refresh.

**Comment by mjcampagna** [comment]
Hi, you've closed the issue with no reply. I was hoping to hear something on how this might be resolved.

**Comment by fancyapps** [comment]
Any live demo would help to understand your issue, right now it is not possible to give any answer.

**Comment by mjcampagna** [comment]
Developing locally at the moment. If I deploy, or am able to set up a demo someplace, I'll let you know.
