### ISSUE TITLE
Mixed photo/video gallery creates multiple thumbs for video

### ISSUE THREAD

**Issue by infatum1** [fancyapps/fancybox#2164]
**Describe the bug**
Mixing photos and YouTube video in one gallery, creates multiple thumbnails. 7 thumbs in my particular case. Tried different images and thumbs and it didn't help.

**To Reproduce**
```
<a href="Docs/Vecmaminu_klubs/Vecmaminu_klubins_meteni.jpg" 
     data-fancybox="images-preview" 
     data-thumbs='{"autoStart":true}' </a>
    <img src="Docs/Vecmaminu_klubs/Vecmaminu_klubins_meteni.jpg" class="img_container"/>
 
<div style="display: none;">
  <a href="Docs/Vecmaminu_klubs/Vecmaminu_klubins.jpg" data-fancybox="images-preview" 
     data-thumb="Docs/Vecmaminu_klubs/Vecmaminu_klubins.jpg"></a>

  <a href="Docs/Vecmaminu_klubs/Vecmaminu_klubins_2.JPG" data-fancybox="images-preview" 
     data-thumb="Docs/Vecmaminu_klubs/Vecmaminu_klubins_2.JPG"></a>

  <a href="Docs/Vecmaminu_klubs/Vecmaminu_klubins_3.JPG" data-fancybox="images-preview" 
     data-thumb="Docs/Vecmaminu_klubs/Vecmaminu_klubins_3.JPG"></a>
     
  <a href="Docs/Vecmaminu_klubs/Vecmaminu_klubs_.JPG" data-fancybox="images-preview" 
     data-thumb="Docs/Vecmaminu_klubs/Vecmaminu_klubs_.JPG"</a> 
     
  <a href="https://www.youtube.com/watch?v=OOZW012i9QU" data-fancybox="images-preview" 
     data-caption="Reportāža par vecmāmiņu kluba 10 gadu jubileju"</a> 
   
  <a href="https://www.youtube.com/watch?v=5BCh1viTM-w" data-fancybox="images-preview" 
     data-caption="Pasākums veltīts vecmāmiņu kluba 1-.gadu jubilejai"</a> 
```

**Expected behavior**
One thumbnail per YouTube video.

**Screenshots**
[SS.](https://photos.app.goo.gl/V9AxRdmDmZzYCb7u5)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome [e.g. chrome, safari]
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Additional info (please complete the following information):**
Adding another YouTube video that follows the previous YouTube video creates one thumbnail for the previous video, but still forms 7 thumbnails for the next video.

**Solution**
Adding extra closing anchor tag < / a > solves the issue.

  <a href="your-link" data-fancybox="images-preview" 
     data-caption="Pasākums veltīts vecmāmiņu kluba 1-.gadu jubilejai"< / a >**< / a >**

**Comment by kloneets** [comment]
Your html is not valid. Try
```html
<a href="your-link" data-fancybox="images-preview"
data-caption="Pasākums veltīts vecmāmiņu kluba 1-.gadu jubilejai">
    <img src="Docs/Vecmaminu_klubs/Vecmaminu_klubins_meteni.jpg" class="img_container" />
</a>
```
(notice **>** at the end of <a)

**Comment by infatum1** [comment]
Thanks. Sorted. Couldn't get what **>** closes. And thought to delete it since all other anchors were closed.
