### ISSUE TITLE
transitionEffect not working

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#2166]
Hi,

Here's a test gallery:
http://campagnapictures.com/galleries/test/

transitionEffect: 'rotate' is set, but the slideshow behaves as 'slide' instead. Can you please take a look?

The Fancybox config is in the combined script, linked in the footer of the page source.

Thanks,
Matt

**Comment by fancyapps** [comment]
Hi,

Transition effects are actually created using CSS transitions. Check out these two demos:

1) Your HTML code, your JS code, original CSS - it works - https://codepen.io/anon/pen/oJdvRg
2) Your HTML/JS and your CSS, it does not - https://codepen.io/anon/pen/GPdRRW

So, the question is -how did you manage to do that? Sorry, I do not have time right now to debug your code, maybe you can find the cause by yourself.

**Comment by mjcampagna** [comment]
Okay, I've found this is causing it in my custom CSS:

```css
.fancybox-stage {
  bottom: 44px;
  top: 44px;
}
```

Using this to create some "margin" between the images and the screen edge, but UI components. I'll maybe need to find another way ...
