### ISSUE TITLE
Image gallery loop: true doesn't work

### ISSUE THREAD

**Issue by Timeranger** [fancyapps/fancybox#2168]
Hello, i changed the loop from false to true, but it keep stoping on the last image;

_Html_
`<a data-fancybox="galery" href="https://youtu.be/Z6WqKS9jXJk">
        		<img src="imgs/audience-band-christians-213207.jpg" class="img-thumbnail" /></a>`

_JQuery_

`$('[data-fancybox="gallery"]').fancybox({
	  loop: true,
});`

Even in a host, doesnt work

**Comment by fancyapps** [comment]
1) I think it has been already answered here - https://stackoverflow.com/questions/54119414/fancybox-3-cyclic-loop-navigation-not-working

2) You have syntax error in your JS code
