### ISSUE TITLE
Can you please delete this commit and PR I made?

### ISSUE THREAD

**Issue by IAMtheIAM** [fancyapps/fancybox#2170]
This is bad, I accidentally used my work email and real name for this commit and PR, can you please delete it so I can recommit and submit a PR?

https://github.com/fancyapps/fancybox/commit/59d82d19a0bbb9dc193fdd59324cce75ca99a483
https://github.com/fancyapps/fancybox/pull/2169

Thank you!

**Comment by fancyapps** [comment]
Hi,

Looks like you have already deleted that commit, but it would not be merged anyway. Inline items are moved to the container created by the script and moved back to keep all the changes user has made to the element. For example, user can open hidden form, partially fill, then close and reopen - all the previously added content would still be there. 

On the other hand, if you wish to open html element as clone, you can do it like this:

```HTML
$.fancybox.open({
  src  : $('#your-element').clone(), 
  type : 'html'
}); 
```

I plan to make improvements in v4, you would simply add `data-src="#your-element"` and `data-type="html"` attributes  and it would automatically display that element as clone.

**Comment by IAMtheIAM** [comment]
Thanks, I will try your method.

Can you please delete this commit :https://github.com/fancyapps/fancybox/commit/59d82d19a0bbb9dc193fdd59324cce75ca99a483

I was able to delete the PR but not the commit. It contains personal information on accident.

**Comment by fancyapps** [comment]
I wish GitHub would provide "delete" functionality, but it doesn't. And, to be honest, I have no idea where and why that commit exists.

**Comment by IAMtheIAM** [comment]
I was able to get it removed through github support, thanks.
