### ISSUE TITLE
Uncaught (in promise) TypeError: Document not active

### ISSUE THREAD

**Issue by Wndworks** [fancyapps/fancybox#2171]
I'm using fancybox for an inline html popup and getting this error in the chrome console:

_fancybox.min.js:12 Uncaught (in promise) TypeError: Document not active
    at Object.exit (fancybox.min.js:12)
    at HTMLDocument.beforeClose.fb (fancybox.min.js:12)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLDivElement.<anonymous> (jquery.min.js:4)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.trigger (jquery.min.js:4)
    at p.trigger (fancybox.min.js:11)
exit @ fancybox.min.js:12
beforeClose.fb @ fancybox.min.js:12
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
trigger @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:4
trigger @ fancybox.min.js:11
close @ fancybox.min.js:11
(anonymous) @ fancybox.min.js:11
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3_

I've found other topics from other plugins with the same error since 23 days ago. They say a new chrome update causes the problem.
"Its because a chrome 71 change, its complaining because it cant exit full screen..."

**Comment by fancyapps** [comment]
Hi,

Please, try to improve your comment and add more useful info, comments like this does not give any clue at all.

**Comment by Wndworks** [comment]
@fancyapps 
Thanks for the reply and sorry for the unclear comment. Here a better explanation:

I've installed fancybox and using it with a inline html popup:

`<div id="main-popup" class="popup">
		<p>Popup</p>
	</div>
<a data-fancybox data-src="#main-popup" href="javascript:;">Popup button</a>`

The popup opens correctly when i'm clicking on the popup button. After closing it, an error appears in the console: `Uncaught (in promise) TypeError: Document not active`. This error only appears in the Chrome browser.

I searched on Google for any solutions and saw a couple topics from people with the same error but they are using other jquery plugins (not fancybox). In this topics they say it's because a new update of the Chrome browser (Chrome 71).

Do you know a solution to fix this error?

**Comment by fancyapps** [comment]
Sorry, still no idea how you managed to get that error message.

**Comment by Wndworks** [comment]
Ok.

**Comment by fancyapps** [comment]
Do you get that error message when viewing demos from homepage, too? I am using latest Chrome and I do not remember seeing such message ever.

**Comment by Wndworks** [comment]
That's smart to test indeed ;) No errors on the demo page, so i'll look into my code. Thanks anyway!

**Comment by fancyapps** [comment]
Well, if you would give a link to your page/demo, then I could take a look, I do not know what else to add.

**Comment by Wndworks** [comment]
*facepalm*
I was using an old version of fancybox. Now it works. Thanks!
