### ISSUE TITLE
How to allow to click button/menu on background?

### ISSUE THREAD

**Issue by nethubonline** [fancyapps/fancybox#2172]
Hi all,

I have been using fancybox since 2.1.0. Previously if the fancybox is opened, I can still click button/menu on background, just like this:
https://codepen.io/anon/pen/wRQeKb

I would like to upgrade to fancybox 3, how can I do the same way? Here's a codepen for your ref.
https://codepen.io/anon/pen/ZVmyEW

Thanks a lot.

**Comment by fancyapps** [comment]
Hi,

Actually, v3 acts as a big slider, therefore, if you have not resized sliding area (and you have not done that), then you have to use `clickSlide` option to specify action when user clicks outside the content. See demos:

  - https://codepen.io/anon/pen/KbrZNX - `clickSlide: false` and user can click outside content and nothing happens;
 - https://codepen.io/anon/pen/MZzrJV - `clickOutside: false`, but stage is resized; and you can click grey area to close, but clicking outside (therefore that option is named `clickOutside`) would do nothing.
