### ISSUE TITLE
YUI Compressor issue

### ISSUE THREAD

**Issue by jozef** [fancyapps/fancybox#2173]
**Describe the bug**
yui-compressor fails to process JavaScript code due to "class" reserved keyword being used as property in "var VideoAPILoader".

**To Reproduce**
1. http://refresh-sf.com/
2. paste JS code
3. click YUI Compressor
4. tick "Use YUI Compressor instead of UglifyJS/Clean-CSS. "
5. tick "verbose — Display informational messages and warnings. "
6. click [JavaScript] button (top right to input box)

```
[ERROR] in -
  3634:12:invalid property id
[ERROR] in -
  3634:13:syntax error
```

**Additional context**
renaming 2x properties from "class:" to something like "classx:" works fine for YUI Compressor,
but probably breaks "something somewhere".

**Comment by fancyapps** [comment]
Hi,

1) It is perfectly valid to use smth like `obj.class`, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage
2) JSHint and JSLint are fine with that, too.

So, this is more YUI Compressor issue.
