### ISSUE TITLE
animationEffect zoom doesn't work with pseudo element

### ISSUE THREAD

**Issue by systemshock89** [fancyapps/fancybox#2174]
I have image gallery with pseudo element "before".
Pseudo element positioned in the center image.

In result animationEffect zoom doesn't work.
But animationEffect zoom is work if in element 'before' delete css 'left' or 'top'.

https://codepen.io/john-raiden/pen/magJxV

This bug appeared in version fancybox since 3.5.0.
In version 3.4.2  animationEffect zoom is work.

**Comment by fancyapps** [comment]
Hi,

I am surprised that you are using pseudo elements for images, because that is not valid, see https://developer.mozilla.org/en-US/docs/Web/CSS/::before

> Note: The pseudo-elements generated by ::before and ::after are contained by the element's formatting box, and thus don't apply to replaced elements such as <img>, or to <br> elements.

**Comment by systemshock89** [comment]
Hi
I know.
I used image in pseudo element for simple example.
On the project instead of the image i use icon Font Awesome:

`before {
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
  content: "\f007";
}`

But problem there is in that case

**Comment by fancyapps** [comment]
Add `pointer-events: none;` to your elements that are over the thumbnail image.
