### ISSUE TITLE
Apply inline styles to Fancybox image

### ISSUE THREAD

**Issue by Soren1612** [fancyapps/fancybox#2176]
I have a simple Thumbnail Gallery which links to bigger images opening in Fancybox, nothing special so far.
Some of the thumbnails use inline styles to apply css-filters like greyscale or sepia.
The bigger images however don’t have these inline styles applied of course.
I'm looking for a way to apply inline styles to the bigger image too, my first idea is to add something like a data-style attribute to the link, grab it’s content and apply it to the bigger image, e.g.:
`<a href='bigimage.jpg' data-fancybox data-caption='my caption' data-style='filter: greyscale(0.75)'><img src='thumbnail.jpg' /></a>`

Is it possible to extend fancybox this way? I had a look at fancybox.js but am kind of overstrained to find the right place to add this functionality…
Any ideas?

**Comment by fancyapps** [comment]
Hi,

Do you really need JS instead of using CSS directly like this? -

```JS
.fancybox-image {
  filter: grayscale(80%);
}
```

https://codepen.io/anon/pen/BveQEQ?editors=1100

If you really need to use JS (to use some logic or smth), then you can do it like this:

```JS
$('[data-fancybox]').fancybox({
  afterLoad : function(instance, current) {
    current.$image.attr('style', current.opts.$orig.data().style);
  }
});
```

https://codepen.io/anon/pen/BvepyW
