### ISSUE TITLE
FancyBox - Arrows/Navigation using iframe

### ISSUE THREAD

**Issue by FabianoLothor** [fancyapps/fancybox#2179]
In [This CodePen](https://codepen.io/fancyapps/pen/RYXOeK?editors=1000) I have 3 links.

Which one of them open a iframe using fancybox. Is it possible create a NavArrows between the iframes like the Redmine do it?

**Comment by fancyapps** [comment]
Please, do not make duplicates - https://stackoverflow.com/questions/54260859/fancybox-arrows-navigation-using-iframe/
