### ISSUE TITLE
iPhone ignoring maxheight attribute

### ISSUE THREAD

**Issue by ChilliBongo** [fancyapps/fancyBox#218]
Hi all,

I've just downloaded FancyBox (v2.0.5) to display an overlay form on our website, and overall it works a treat. 

However, I'm having an issue getting it to honour the minheight/maxheight attributes on the iPhone when in landscape orientation. (seems to work fine on Android)

I've managed to temporarily fix the issue by forcing it to use the a greater minheight than I would have liked, but the problem with that approach is that it then means that everyone else (inc desktop users) see a much bigger form than is necessary (I figured this was the lesser of 2 evils in the short term as at least everyone can now use it)

I've put up a demo which you can see here: http://www.chillibongo.com/github.asp

I've had a look on Github to see if I could find an answer, and I've not been able to, but apologies if this has already been solved somewhere and I've missed it.

Any help would be really appreciated.

Thanks
Kieran

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
