### ISSUE TITLE
Lock KEYBOARD default to FALSE for single image instance

### ISSUE THREAD

**Issue by lionel-dieu** [fancyapps/fancybox#2181]
The play/pause button is hidden when the instance contains only 1 image.
Visual arrows on screen are also hidden regardless of the ARROWS-default value for a 1 image-instance.
Is there any means to also dynamically disable the NEXT and PREV though the keyboard (change the default values KEYBOARD : TRUE to KEYBOARD: FALSE dynamically ?) when a single image instance occurs in order to disable senseless scrolling using the keyboard arrows ?
Many thanks.

**Comment by fancyapps** [comment]
Sorry, I’m afraid I don’t follow you.

**Comment by lionel-dieu** [comment]
Please allow me to try and explain.

I'm using Fancybox 3.5 with the default settings 'keyboard: true' and 'arrows: true'.
When running a 'multiple image'-instance of Fancybox, I can scroll to the next or previous image either by clicking the arrows that appear on the right- and left-hand side of the screen, or by entering one of the arrow-keys on the keyboard. No issue so far.
Otherwise, when running a 'single image'-instance of Fancybox, there is no point in scrolling as there is no next nor previous image, so there are no arrows appearing right or left on the screen, which is perfectly logic. 
However, pushing the arrow-keys on the keyboard still results in a scroll-like transition effect returning the same image. I would have liked in this case for the keyboard arrow-keys to be somehow 'disabled'.

Many thanks.

**Comment by fancyapps** [comment]
But ... this is how it works, there is no transition effect when viewing single image.

**Comment by lionel-dieu** [comment]
issue solved after changing 'loop: true' to 'loop: false'...
