### ISSUE TITLE
Safari Bug Scroll to bottom

### ISSUE THREAD

**Issue by BenjaminZekavica** [fancyapps/fancybox#2183]
Hallo I have a question. Now i Use the Ajax attributes function to load 
content into the lightbox. 

But only one Apple devices I have a problem if I want to open a modal. 
It scroll my viewport to the buttom. That problem is always visible if the content is bigger thank my viewport. 

Do you have an fix for me? I hope you can help me. This bug is everwhere in my projects. 
That isn't only on my project.

**Comment by BenjaminZekavica** [comment]
I use the HTML attributes: 
`<a class="veranstaltung-item-wrapper" data-fancybox data-type="ajax" data-src="<?php the_permalink(); ?>" href="javascript:void(0);" data-filter=".veranstaltungs-modal" data-touch="false">`

How can I set the AutoFucus to False?

**Comment by fancyapps** [comment]
You can use `data-auto-focus="false"` attribute.

**Comment by BenjaminZekavica** [comment]
Thank you buddy :) It works

**Comment by BenjaminZekavica** [comment]
Is that possible to set this option by default and if we need it to actived it?

**Comment by fancyapps** [comment]
Just check docs, simply change defaults, for example, `$.fancybox.defaults.autoFocus = false;`
