### ISSUE TITLE
fancybox-stage hides for a moment, and then shows up again - why?

### ISSUE THREAD

**Issue by 7iomka** [fancyapps/fancybox#2185]
**Describe the bug**
Why fancybox-stage hides for a moment (inline style display: none), and then shows up again, if i resized window / or when orientation change?
This cause problems with usage sort of plugins, wich use some resize logic, that not works correctly!
For simple example - swiper (slider);
**To Reproduce**
1. Install swiper on another kind of sliders
2. Put as content of one slide two-columns (flexbox) content, which will become single-column on some breakpoint
3. When fancybox is opened, try to orientation change / resize to go from one breakpoint to another
4. Slider will not update slide sizes correctly. This is due to the fact that the .fancybox-stage is temporarily hidden at the time of resizing (but not all the time, but only a part!!!) and in the case of the swiper slider, its observers do not have time to see this change.

**Expected behavior**
https://cl.ly/6a0aefb13d04

**Actual behavior**
https://cl.ly/6faea46ca43e

**Screenshots**
I provided a demo video above.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**

I fixed that bug (see Expected behavior) or unexpected feature by making .fancybox-stage always visible with
.fancybox-stage { display: block!important; }
But the question is, what is it done for?
Thanks!

**Comment by fancyapps** [comment]
Obviously, there is a reason for this. This fixes issue when browser does not update content immediately after orientation change event. You can use `onUpdate` callback to do something after content is resized.

**Comment by 7iomka** [comment]
> Obviously, there is a reason for this. This fixes issue when browser does not update content immediately after orientation change event. You can use `onUpdate` callback to do something after content is resized.

I understood by the code https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L909
but why is the event `onUpdate` you specified missing in the documentation?
