### ISSUE TITLE
 $.fancybox.close(true) does not close all instances (>2)

### ISSUE THREAD

**Issue by 7iomka** [fancyapps/fancybox#2187]
**Describe the bug**
 $.fancybox.close(true) does not close instances (>2)
I have 3 modals:
1 - Programmatically opened with 
```
$.fancybox.open({
        src: '#action-1',
        type: 'inline',
        opts: {
          touch: false,
          smallBtn: false,
        },
      });
```
2 - inside first modal (`#action-1`) i have button with inline attributes like this
`data-fancybox='', data-src="#quiz-modal", data-options='{"touch": false, "smallBtn": false}'`

3 - modal (`#quiz-modal`) have button trigger to third modal (button with inline attributes like this
`data-fancybox='', data-src="#quiz-modal-submit"`)

I want when the third modal is opened - to close (for example) first modal, but I don’t know how to do it programmatically, and I went into the documentation and read that you can close all modals, and thought that this is a good alternative (the third modal in my case - contains the form, and after submitting it, I want to close all opened modals).
When I try to call `$.fancybox.close(true)`, i have closed 2-nd and 3-rd modals, but first modal (opened programmatically) still opened

**Expected behavior**
All modals are closed.

**Screenshots**
Video demo - tests: https://cl.ly/426704e4ce3d

**Desktop (please complete the following information):**
 - OS: Windows 10 (x64)
 - Browser: Chrome
 - Version: latest

**Comment by fancyapps** [comment]
Hi,

I could not reproduce this issue, it works fine. And, since you did not provide a link to demo where this issue could be inspected, I do not know how to help.

**Comment by 7iomka** [comment]
> Hi,
> 
> I could not reproduce this issue, it works fine. And, since you did not provide a link to demo where this issue could be inspected, I do not know how to help.

if I take off the link to the site where this behavior is observed - will it help you somehow? or should i try to make an analog of inoperability on codeped? Thanks!

**Comment by fancyapps** [comment]
Codepen demo would be preferred.

**Comment by 7iomka** [comment]
> Codepen demo would be preferred.

Thank you for the idea to create a demo!
I found that I did not have a new version but version 3.3.5
In which this bug is present.
But in the new version it is missing)
Somewhere in // was it indicated that there was such a bug?
Demo version with buggy v 3.3.5: https://codepen.io/7iomka/pen/GzWYXO?editors=1010
Demo version with latest version v.3.5.x https://codepen.io/7iomka/pen/pGeQRv?editors=1010

If it is possible, I would like to get advice from you, apart from the comments, please, how can I close only the specific one (1st modal in my case in prodived demo - I maked a button for this inside the 3rd modal)
Thanks for the very fast feedback!

**Comment by fancyapps** [comment]
It is simple, when you start fancybox using `$.fancybox.open()`, then reference to the instance is returned and all instance methods are available. Demo - https://codepen.io/anon/pen/PVpxJV?editors=1010
