### ISSUE TITLE
Closing inline Fancybox on a mobile device on close button click

### ISSUE THREAD

**Issue by fantenra** [fancyapps/fancybox#2188]
Hello
When you try to close the inline fancybox on a mobile device using close btn, it works randomly. I assumed that there is a conflict in touch events, and it interprets them as a drag event. How can I get both a click and a drag to close?
Thanks

**Comment by fancyapps** [comment]
Hi,

So, you are telling me that you open project homepage, open some demo, try to close and it does something random? Sorry, but it is hard to believe.

**Comment by fantenra** [comment]
Yeah, for example, Hidden HTML element demo popup. When you try to close popup window sometimes there isn't any reaction and you have to click close btn more than one time...

**Comment by fancyapps** [comment]
See #2189
