### ISSUE TITLE
Can you select multiple images in fancybox?

### ISSUE THREAD

**Issue by fa7al** [fancyapps/fancybox#2194]
I want to select multiple images in the gallery by clicking on checkboxes on the image thumbnail. Is it possible? I can write code for this, but just wanted to know if fancybox has this functionality. 

For reference, [here](https://codepen.io/Kris-B/pen/RyaLaG) is nanogallery checkboxes.

Also, is there a thumbail toolbar which appears on hover?

**Comment by fancyapps** [comment]
Hi,

1) fancybox is not doing anything with your thumbnails except adding click event, so, if you wan to have some checkboxes, you have to implement that functionality by yourself.

2) There is no built-in option for that. If you wish, you can reposition thumbnails and hide using CSS; and then you can use a callback to bind hover events that would toggle visibility.
