### ISSUE TITLE
Issues with loading FancyBox lightbox from FlexSlider slideshow

### ISSUE THREAD

**Issue by rhaglennydd** [fancyapps/fancybox#2196]
**Describe the bug**
When FancyBox loads upon clicking an image within a FlexSlider slideshow, after you close FancyBox the last FlexSlider slide gets replaced with whatever image FancyBox was on. The slideshow does not advance the dot navigation accordingly, so the order of slides gets messed up.

**To Reproduce**
1. Go to https://codepen.io/will_beaumont/pen/XOzjBK
2. Click a slide.
3. Advance the FancyBox lightbox to a different image.
4. Close FancyBox.
5. The original slide you clicked on gets replaced. Navigate through the slideshow and you'll see the slides are out of order with respect to the dot navigation.

**Expected behavior**
I just want FancyBox to close and go back to the FlexSlider slideshow exactly as it was when I clicked, i.e., the original slide should be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71.0.3578.98

**Smartphone (please complete the following information):**
Did not test on smartphone.

**Comment by fancyapps** [comment]
Hi,

The typical issue with sliders is that fancybox places focus back to the original trigger element, but that that might interfere with slider layout. You can turn of that feature by setting `backFocus: false`.

btw, is there a particular reason why you chose FlexSlider over the others? Here is a more complete demo with other slider - https://fancyapps.com/fancybox/3/docs/#faq-6
