### ISSUE TITLE
Title on top for popup dialogs

### ISSUE THREAD

**Issue by DangerD256** [fancyapps/fancybox#2197]
Currently i can only show caption on bottom but i need dialog title like jQuery UI Dialog:
![image](https://user-images.githubusercontent.com/17032489/52399566-58e77b00-2ac5-11e9-8131-c77ceafba76a.png)
Currently i have this:
![image](https://user-images.githubusercontent.com/17032489/52399632-7caac100-2ac5-11e9-95b5-2086f6609c99.png)
Need something like this:
![image](https://user-images.githubusercontent.com/17032489/52399749-c5627a00-2ac5-11e9-94b0-9e0d052e41e0.png)
or
![image](https://user-images.githubusercontent.com/17032489/52400064-bcbe7380-2ac6-11e9-93d2-810193de8fce.png)

What do you think about it?

**Comment by fancyapps** [comment]
Hi,

Well, there is no built-in option for that, but you have at least 2 choices:

1) Design each modal with title and body elements, like in this demo - https://codepen.io/anon/pen/jdaQmG

2) Use JS to automatically create title element, like this - https://codepen.io/anon/pen/XOzyKB
