### ISSUE TITLE
SVG rect data-type="iframe" does not work on Apple devices.

### ISSUE THREAD

**Issue by infatum1** [fancyapps/fancybox#2199]
**Describe the bug**
If one opens the the following website - http://chemistry.thats.im/index_eng.php on Windows/Android device and clicks on chemical elements in the periodic table, the site loads the associated page in an iframe. The following code is used.

`<rect x="1751" y="53.3" class="st0" width="96.4" height="96.3" data-fancybox data-type="iframe" href="elements/eng/He.php"/>`

The element is hoverable and is pressable. However, as tested on Apple iPad Air 2 - the page does not open in an iframe.

**Comment by fancyapps** [comment]
Hi,

This is limitation of jQuery, see https://stackoverflow.com/questions/14431361/event-delegation-on-svg-elements (e.g., "Delegated events do not work for SVG.").

As a workaround, you can add your own click event for your elements that starts fancybox manually (using $.fancybox.open())

**Comment by infatum1** [comment]
I assume you are talking about 

`$.fancybox.open('<div class="message"><h2>Hello!</h2><p>You are awesome!</p></div>');`

Display iframed page:

`$.fancybox.open({
	src  : 'link-to-your-page.html',
	type : 'iframe',
	opts : {
		afterShow : function( instance, current ) {
			console.info( 'done!' );
		}
	}
});`

Right? Is there a way to set universal src to be "passed" to href link, which in my case would be smth like - `$.fancybox.open('<rect x="1751" y="53.3" class="st0" width="96.4" height="96.3" data-fancybox data-type="iframe" href="elements/eng/He.php"/>'); ` ? 

Or do I have to do 'link-to-your-page.html' to every single existing page in the table?

**Comment by fancyapps** [comment]
Sorry, I have no idea what you understand by "universal src". Like I said, the problem is that this would not work on iOS - 

```
$(document).on("click", ".your-svg-element", function () {
    //  do something
});
```

So, you would need to loop through your items and attach click event individually to start fancybox.

btw, I just now remembered that I stumbled upon this issue some time ago and the workaround was to add this CSS snippet: 

```CSS
svg rect {
    cursor: pointer;
}
```

This would make click event to bubble up and therefore event delegation would work.

**Comment by infatum1** [comment]
`svg rect {
    cursor: pointer;
}`
Nailed it. That's an easier solution than wrapping around 118 elements into javascript. 

By universal src I meant smth like src='*.html', where * would represent any HTML page as opposed to absolute page name, so that it would target and grab any html page, instead of writing every single page.
