### ISSUE TITLE
Not using fancybox, url wants to open as an image

### ISSUE THREAD

**Issue by Ypanesa** [fancyapps/fancybox#2200]
**Describe the bug**
WP Website. I do not have fancybox installed. Cannot open normal links. They get additional code somehow. Cannot create new post or page with links. Happens to all newly created links.

**To Reproduce**
1. Go to http://ffp.gifwelt.info/
2. Click on any link
4. See error. The link wants to open in lightbox

**Expected behavior**
Open new URL

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 65.0.1
Also tested with Chrome

**Comment by fancyapps** [comment]
Hi,

You have installed some other lightbox-type plugin, disable that and it should be fine.

**Comment by Ypanesa** [comment]
Nothing like this

**Comment by fancyapps** [comment]
But did you check your theme? It looks like it - http://ffp.gifwelt.info/wp-content/themes/customizr-pro/assets/front/js/tc-scripts.min.js - contains some sort of lightbox.

**Comment by fancyapps** [comment]
Please, do not create duplicates and, please, try to understand that this issue is not related to fancybox at all.

**Comment by Ypanesa** [comment]
Sorry for the second question. I just feel absolutely helpless.
I use this theme on 6 sites and only on one I do have this problem. What do I have to do now? Get in contact with the theme creator?

**Comment by fancyapps** [comment]
It looks like you are using `customizr-pro` theme and you can get support here - https://presscustomizr.com/support/

**Comment by Ypanesa** [comment]
Thanks so much.
