### ISSUE TITLE
Fading out fades out to opacity:0.1

### ISSUE THREAD

**Issue by thany** [fancyapps/fancybox#2204]
**Describe the bug**
Fading out the fancybox fades it out to opacity 0.1 and then removes it from the DOM. This makes hiding the fancybox feel janky. Our designer immediately noticed, because of course she does.

**To Reproduce**
I'm using this config:
```javascript
{
	width: '100%',
	height: '100%',
	fitToView: false,
	autoSize: false,
	helpers: {
		overlay: {
			locked: true,
			css: {
				background: 'none'
			}
		}
	},

	openSpeed: 2500,
	closeSpeed: 2500,
	openEasing: "linear",
	closeEasing: "linear"
}
```
Speed & easing added to make it easy to see how the transition progresses.

**Expected behavior**
It should fade out from opacity 1.0 to 0.0.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 65

**Additional context**
Fancybox 2.1.5
I can't upgrade the plugin, because our platform is too complicated for that. It's weird I know, but it's just the way it is, for the moment. It's not exactly your average simple little website. So, I need a workaround.

**Comment by thany** [comment]
Just for kicks, I've also set the `closeSpeed` to 25000. In 25 seconds, I can see the opacity creeping from 1.0 down to 0.1 and then the fancybox is immediately removed from the DOM. So apparently somewhere it is set to fadeout to 0.1 instead of 0.0.

**Comment by fancyapps** [comment]
Hi,

Sorry, v2 is no longer supported, but you can freely upgrade to v3. If you have trouble upgrading, please, do not hesitate to ask for help

**Comment by thany** [comment]
Is this issue fixed in v3 fore sure?

**Comment by fancyapps** [comment]
v3 is completely rewritten and works quite differently, open/close animations and slide changes are defined using CSS (https://github.com/fancyapps/fancybox/blob/master/src/css/core.css#L521).
