### ISSUE TITLE
add data-autofocus="false" inline support

### ISSUE THREAD

**Issue by zwantE** [fancyapps/fancybox#2206]
Hey,

i have a few inline Elements with youre awesome fancybox.

In some of them i usw forms für userinput, but when i open this inline-content with fancybox & forms, then it had always autofocus to the first input.

and when an input has a focus, then it isnt possible to close the overlay with the ESC Button...

So how can i disable autofocus for inline-content or make it possible to close them with the esc btn?

**Comment by fancyapps** [comment]
Hi,

If you wish to set options like `autoFocus`, then use following format : `data-auto-focus="false"` 
Demo - https://codepen.io/anon/pen/VRYrBY?editors=1010

But, if you wish to close modal whenever user presses ESC, you could use snippet like this - 

```JS
document.onkeydown = function(evt) {
  var fb;
  
  // 27 is the code for escape
  if ((evt || window.event).keyCode == 27 && (fb =  $.fancybox.getInstance())) {
    fb.close();
  }
};
```

https://codepen.io/anon/pen/VRYrBY?editors=1010

**Comment by zwantE** [comment]
> If you wish to set options like `autoFocus`, then use following format : `data-auto-focus="false"`

this is what i looking for and not found in the docs.... thx guy

**Comment by fancyapps** [comment]
Yeah, sorry about that. FYI, this is how jQuery works https://api.jquery.com/data/#data-html5 and it is based on HTML specs https://html.spec.whatwg.org/multipage/dom.html#dom-dataset
