### ISSUE TITLE
buttons not appearing by default in gallery view (old jquery version)

### ISSUE THREAD

**Issue by coda-apps** [fancyapps/fancybox#2209]
Dear all,

For various compatibility reasons, i am using jQuery 1.7.2 (I know fancybox is said to work from 1.9 and up) 
I am using the following code, but by default the buttons are not appearing (gallery mode) - only zoom/play/close and the arrows are showing, which I assume are the default. 
Is there some kind oif a syntax change that might work with this older version? 

```
$('[data-fancybox="gallery"]').fancybox({
	// Options will go here
	arrows: true,
	toolbar: true,
	buttons: [
    "zoom",
    //"share",
    "slideShow",
    //"fullScreen",
    "download",
    "thumbs",
    "close"
  ]
});
```

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox, up to date 

Thanks!

**Comment by fancyapps** [comment]
Hi,

Actually, your snippet works (somehow) fine -

1) Make sure that your selector returns something;
2) Add missing `addBack` method (e.g., `jQuery.fn.addBack = jQuery.fn.andSelf;`)

Demo - https://codepen.io/fancyapps/pen/PLGrva?editors=1010

**Comment by coda-apps** [comment]
Thank you fore the super quick response!
I see it does work.. i must be doing something wrong... i have narrowed mine down to a barebones page, and i'm still not getting it the download etc buttons: 

```

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	<title>-</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.css" />
	<script src="https://code.jquery.com/jquery-1.7.2.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js"></script>
	<script>
	
$('[data-fancybox="gallery"]').fancybox({
	// Options will go here
	arrows: true,
	toolbar: true,
	buttons: [
    "zoom",
    //"share",
    "slideShow",
    //"fullScreen",
    "download",
    "thumbs",
    "close"
  ]
});

jQuery.fn.addBack = jQuery.fn.andSelf;


console.info( $.fn.jquery );	
	</script>

	<!-- dashboard functions -->

	</head>
	<body>
    <p> <a href="https://images.maariv.co.il/image/upload/f_auto,fl_lossy/t_ArticleControlTransformaionFaceDetect/520385" target="_blank"  data-fancybox="gallery">2019228-120-1.jpg</a><br />
      <a href="https://images.maariv.co.il/image/upload/f_auto,fl_lossy/t_MD_MainArticleFaceDetect/520381" target="_blank"  data-fancybox="gallery">2019228-120-2.jpg</a><br />
    </p>
</body>
</html>
```

**Comment by fancyapps** [comment]
You have to put js code after your HTML or wrap code into `$(document).ready()`

**Comment by coda-apps** [comment]
wow - perfect, thanks so much :-)
