### ISSUE TITLE
problem with iphone 

### ISSUE THREAD

**Issue by gabrielebrev** [fancyapps/fancybox#2211]
Could someone verify the attached html page and help me:
when the link is clicked on an iphone the pdf is opened but it is impossible to scroll it
[associazione.zip](https://github.com/fancyapps/fancybox/files/2946586/associazione.zip)

**Comment by fancyapps** [comment]
Hi,

Sorry, this is a well known webkit issue, see 
https://github.com/fancyapps/fancybox/issues?q=is%3Aissue+ios+pdf https://stackoverflow.com/questions/15854537/make-embedded-pdf-scrollable-in-ipad
