### ISSUE TITLE
overlayOpacity&overlayColor

### ISSUE THREAD

**Issue by i7eo** [fancyapps/fancybox#2212]
in fancybox v3.5, jquery v1.12

overlayOpacity & overlayColor doesn't effected.

```
<a href="#inline2" id="test">test</a>

<div id="inline2" style="display:none">
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	</p>
</div>
```
```
$("#test").fancybox({
    'transitionIn': 'none',
    'transitionOut': 'none',
    'width': 1200,
    'height': 300,
    'overlayColor': '#AFADAD',
    'overlayOpacity': '.6',
    'showCloseButton': false,
});
```

**Comment by fancyapps** [comment]
Hi,

You are using options for v2, but these are not compatible with v3. You have to use CSS for that:

```CSS
.fancybox-bg {
    background: #AFADAD;
}

.fancybox-is-open .fancybox-bg {
    opacity: .6;
}
```

Demo - https://codepen.io/anon/pen/rRwRym 

OR, if you really have to use JS, you can use callbacks to get reference to background element and to change CSS values:

```JS
$('[data-fancybox="images"]').fancybox({
  onInit : function(instance) {
    instance.$refs.bg.css({
      opacity: '.6',
      background : '#AFADAD'
    });
  }
})
```

Demo - https://codepen.io/anon/pen/GeEeWe

**Comment by i7eo** [comment]
> Hi,
> 
> You are using options for v2, but these are not compatible with v3. You have to use CSS for overlay/background color/opacity:
> 
> ```css
> .fancybox-bg {
>     background: #AFADAD;
> }
> 
> .fancybox-is-open .fancybox-bg {
>     opacity: .6;
> }
> ```
> 
> Demo - https://codepen.io/anon/pen/rRwRym
> 
> OR, if you really have to use JS, you can use callbacks to get reference to background element and to change CSS values:
> 
> ```js
> $('[data-fancybox="images"]').fancybox({
>   onInit : function(instance) {
>     instance.$refs.bg.css({
>       opacity: '.6',
>       background : '#AFADAD'
>     });
>   }
> })
> ```
> 
> Demo - https://codepen.io/anon/pen/GeEeWe

alright, thanks
