### ISSUE TITLE
Default zoom for an image?

### ISSUE THREAD

**Issue by ehaft21** [fancyapps/fancybox#2215]
Is it possible to specify the default zoom that an image initially loads at?  So on loading an image, instead of it loading at its normal size, it loads at some predetermined zoom level?

**Comment by fancyapps** [comment]
Hi,

Sorry, there is currently no option for that, but there are already multiple requests for such functionality and that will be implemented in future releases.

**Comment by luchomatic** [comment]
Hi! Any updates on this?

**Comment by kunalkishoresharma** [comment]
Any Update?
