### ISSUE TITLE
Android Webview - Youtube Fullscreen Issue

### ISSUE THREAD

**Issue by RichieMcMullen** [fancyapps/fancybox#2217]
I've created a website with a youtube video feature, using "fancybox" to display the videos. It all works fine on desktop.

The problem I'm having is that I've created a android app for the same website (wrapped inside an android webview). While viewing the website via the app, I can view the video as normal but the fullscreen icon on the video is disabled, I cannot maximise the video to full screen via the app.

Anyone got any ideas on this issue ?

**Comment by fancyapps** [comment]
Hi,

Well, if you refer to full-screen button on video, then that is controlled by YouTube itself. fancybox creates embed code and adds all the necessary attributes like `allowfullscreen` for iframe element, but the rest is up to the YT developers.

**Comment by RichieMcMullen** [comment]
Ok understood. Will look into the Youtube API and see what I can dig out. Thanks again!

**Comment by fancyapps** [comment]
It is planned to completely rewrite video helper/plugin so it uses YT API to create video element instead of creating standard embed code. Maybe it will work better afterwards. But for now - I don't think there's much I can do about that right now.
