### ISSUE TITLE
Open fancybox via button

### ISSUE THREAD

**Issue by Dadko** [fancyapps/fancybox#2221]
How do I open the fancybox gallery via button?

I use this kind of format to create the gallery:

`<a data-fancybox="gallery" href="big_1.jpg"><img src="small_1.jpg"></a>`

I need to open that gallery also when I click on some button or other link, not just the exact image.

**Comment by fancyapps** [comment]
Hi,

To use some element to start existing gallery, fancybox provides a handy `trigger element` feature, check docs - https://fancyapps.com/fancybox/3/docs/#usage - and this demo - https://codepen.io/fancyapps/full/VGoRqO

**Comment by Dadko** [comment]
Thanks!!
