### ISSUE TITLE
Quick Product View Bullet change to thumbnail ? 

### ISSUE THREAD

**Issue by dofay** [fancyapps/fancybox#2222]
i'm learning using full of fancybox feature in my website. i Wanted to making quick product view. Thankfully i'm find this code

https://codepen.io/fancyapps/pen/JvGjwa

What i asking, how i can change the bullet indicator on the pop up from bullet to small image thumbnail? Should i change the jquery of $bullets ?? thank you so much..

**Comment by fancyapps** [comment]
Hi,

Simply replace content of `<li>...</li>` with thumbnail image, something like this:

```JS
    for ( var i = 0; i < instance.group.length; i++ ) {
      var thumb = instance.group[i].opts.thumb || instance.group[i].opts.$thumb.attr('src');
      
      list += '<li><a data-index="' + i + '" href="javascript:;"><img src="' + thumb +'" /></a></li>';
    }
```

Demo - https://codepen.io/anon/pen/rRRLOq?editors=1010

**Comment by dofay** [comment]
Hello, sorry for commenting again. i'm trying using in here https://codepen.io/anon/pen/ywQZOv  but it;s not working? (yes the old code using lightslider, i will change it to fancybox soon for the learning) 

i still don't understand what the error (the page freezing when clicking for pop-up). Sorry and thank you for your help...

**Comment by fancyapps** [comment]
Please, please, learn to debug the code - just hit F12 and look at console tab.

Here is a fixed version - https://codepen.io/anon/pen/gEyWNO?editors=1010

**Comment by dofay** [comment]
omg... i'm sorry. I don't know about console tab beforehand. (Now i'm
already know why after seeing the error ). Again, i'm sorry...

Thank you so much Janis.

Pada tanggal Sel, 26 Mar 2019 pukul 14.07 Jānis Skarnelis <
notifications@github.com> menulis:
