### ISSUE TITLE
Mobile Icon Disappearing

### ISSUE THREAD

**Issue by matreke** [fancyapps/fancybox#2224]
**Describe the bug**
If we use the fancybox in mobile design and drag&drop the image a little bit around the toolbar icons will disappear

**To Reproduce**
1. open fancybox
2. drag&drop or touch the image and move it around
3. icon button (f.e. close) will disappear

**Expected behavior**
button should stay as expected

**Comment by fancyapps** [comment]
Hi,

Could not reproduce this. Maybe your did a tap and default action for that to toggle controls, you can disable that by setting `mobile: { clickContent : false }`
