### ISSUE TITLE
Setting fancybox options after loading images from folder

### ISSUE THREAD

**Issue by n0xx** [fancyapps/fancybox#2225]
Hi, i have a question because i can't figure it out on my own.
Im trying to update options of fancybox after appeding dynamically images from folder.

code for adding pictures:
`var folder = "../img/site/galeria/";
$.ajax({
  url: folder,
  success: function(data) {
$(data).find("a").attr("href", function(i, val) {
if (val.match(/\.(jpe?g|JPE?G|png|PNG|gif|GIF)$/)) {
$("#gallery_list").append( "<li><a href='"+ folder + val +"' data-fancybox='gallery'><img src='"+ folder + val +"'></a></li>" );
}  
});
}
});`

and after that im adding:
`$('[data-fancybox="galeria"]').fancybox({
loop:true,
infobar:false,
toolbar:true,
idleTime: 50000,
buttons: 
[
    "close"
],
});`

but all those options (idle time, buttons etc etc) are ignored.
after all of this im adding
$.fancybox.update()
$.fancybox.updateControls();

but it looks like do nothing (probably im using it wrong)

Could You give me a hint what am I doing wrong ?

//edit ver: fancyBox v3.5.7 and latest jquery

**Comment by fancyapps** [comment]
Hi,

Make sure that, when you execute `$('YOUR-SELECTOR').fancybox()`, your content already exists on the page. Otherwise, default options will be used if you are using `data-fancybox` attributes.

Another typical rookie mistake is to place js code before html code. Either put js code right before `</body>` tag or wrap inside `$(document).ready()`.

**Comment by n0xx** [comment]
Thank's for fast answer, thats why i was trying to run Your script on $(window).load(function() {} but it did not worked, but i have found solution so **if anyone is having trouble with similar to mine issue add fancybox in

`$(window).bind("load", function() {
//here goes code
});`**

You've made a great plugin, thanks for help.

**Comment by fancyapps** [comment]
Thanks. Check out https://learn.jquery.com/using-jquery-core/document-ready/ - I would recommend using `$( document ).ready()`

**Comment by reidsci** [comment]
Those using Angular may find that using JavaScript's  `setTimeout` to be helpful. This would be the case when your images' HTML updating has not yet completed by the time your code was run to set/reset your Fancybox options. A delay afforded by  `setTimeout` can make things happen in the right order.
