### ISSUE TITLE
Zooming Problem

### ISSUE THREAD

**Issue by matreke** [fancyapps/fancybox#2226]
**Describe the bug**
If a picture is opened in mobile version and you zoom to the max and press the left or right arrow button at the same time, you will move to the next image and still have the old image behind the new image in bigger size.

**To Reproduce**
1. open the picture
2. zoom in 
3. press the left or right arrow button while zooming

**Expected behavior**
image should switch and not stay in the new picture frame

**Screenshots**

**Smartphone (please complete the following information):**
- Samsung Galaxy S7 (android 8.0), Huawei p20Pro (android 9.0), iPhone 8Plus (iOS)

**Comment by fancyapps** [comment]
Hi,

Everything works fine for me and you did not provide any link to any live page/demo, so there is nothing I can do.

**Comment by matreke** [comment]
Thank you for your fast reply!

I attached an image to describe the problem:
![Screenshot_20190327_124908_Chrome](https://user-images.githubusercontent.com/48948949/55074157-d4aa8080-508f-11e9-8985-e4cfb630b7b7.jpg)

and the Link to the live page: https://m.barfussgefuehl.de/leguano-chester-Winter-Barfussschuhe-braun.htm

thank you

**Comment by fancyapps** [comment]
Hmm, can you reproduce this on the homepage, too? (e.g., https://fancyapps.com/fancybox/3/)
I looked at your site on iPhone (latest iOS) and it worked fine on both Safari and Chrome...

**Comment by matreke** [comment]
Hi,

yes i could reproduce that too. Just try to use an older device and just tap und zoom around, meanwhile try to tap on the navigation arrows while zooming.
