### ISSUE TITLE
Something wrong with the CSS import in JS using webpack

### ISSUE THREAD

**Issue by Daisuke-sama** [fancyapps/fancybox#2227]
Hi, 
When I include this in head everything works
 `<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
` 
But when I download the lib as node_modules and trying to import in my JS file with this
`import '../../../node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.css';`
or this
`import '@fancyapps/fancybox/dist/jquery.fancybox.min.css';`
And the build with webpack the CSS is not included to the build. Why could it be?

**Comment by fancyapps** [comment]
Hi,

Maybe this is because you are trying to minify already minified CSS file? Then try to import files from /src/css folder. Or maybe you run saas? Then avoid processing css files.
