### ISSUE TITLE
Close Button doesn't work

### ISSUE THREAD

**Issue by maple-park** [fancyapps/fancybox#2230]
It's the first time I try Fancybox 3.5.7 (insteat of v 1.3) in Safari

http://vereine.maple-park.eu/vereine-a-z/vereine-a-b-c/a/arbeitskreis-kunst-akku.html

When I click the close button or beside the image nothing happen. I can't leave the screen.

Thanks JP

**Comment by fancyapps** [comment]
Hi,

Well, you have set `<base href="http://www.vereine-in-muellheim.de/" />`, but your page is `http://vereine.maple-park.eu`. That enables CORS restrictions and it eventually causes other problems.

**Comment by maple-park** [comment]
Thanks a lot. That's the solution.

👍
