### ISSUE TITLE
How can I make it so user can't close Fancybox?

### ISSUE THREAD

**Issue by HeadStudios** [fancyapps/fancybox#2231]
I want to make it like a paywall type of thing - where a user has to enter their email address in order to close the fancybox. So need to disable default closing methods and then be able to close it manually with a function. Thnx

**Comment by fancyapps** [comment]
Hi,

There is a handy `beforeClose` callback just for that; you can prevent closing by returning `false`. 

btw, this callbacks receives additional argument that you can use to check what element user has clicked for closing (you can add `data-fancybox-close` attribute to any element to make it work as close button).

**Comment by HeadStudios** [comment]
Thanks!
