### ISSUE TITLE
YouTube video Autoplay in URL params not work

### ISSUE THREAD

**Issue by Aharito** [fancyapps/fancybox#2235]
**YouTube video Autoplay in URL params not work**
I initialize popup YouTube video via URL params. I use &amp;autoplay=1 in URL, and its not work. (Google Chrome v73, Win 7).

**To Reproduce**
Autoplay parameter not work in Your example too:
1. Go to 'https://codepen.io/fancyapps/pen/NLQmzy?editors=1000'
2. Click on 'YouTube video - hide controls and info' link.
3. See error

**Desktop (please complete the following information):**
 - OS: WIN7
 - Browser Google Chrome 73

**Comment by fancyapps** [comment]
Hi,

You should be aware that browsers nowadays tend to prevent video auto play - https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by Aharito** [comment]
I read the material, got it. Thank you.
