### ISSUE TITLE
Sync/disable Compensate-for-scrollbar with Thumbnail-view as that adds a scrollbar

### ISSUE THREAD

**Issue by whatsnewsisyphus** [fancyapps/fancybox#2238]
Hello,
If you have the thumbnail bar visible with enough thumbnails to have a scrollbar, compensate for scrollbar ends up compensating for a scrollbar that is already there, I don't know what the best way to handle this (potentially requires polling content-length for the thumbnail container to check if it indeed has a scrollbar) but wanted to note it here.

**Comment by fancyapps** [comment]
Hi,

Could you post a screenshot or (better) provide a link to live page/demo? It is not clear from description what situation you have.

**Comment by whatsnewsisyphus** [comment]
Hello y'all. I think this is due to a header that is being resized by js although it's full-width (Astra theme has some things like this that you won't expect) that gets its width from the parent container which gets bumped by the margin, shifting the fixed header to the left.
https://www.dropbox.com/s/rhzy0n61s72a0t2/fancybox__margin-compensation.mov?dl=0

**Comment by fancyapps** [comment]
Hi,

Glad to hear that you managed to solve your issue. As alternative, you can disable scrollbar hiding by setting `$.fancybox.defaults.hideScrollbar = false;`
