### ISSUE TITLE
Strange FancyBox opening on comments anchor

### ISSUE THREAD

**Issue by cbeyer** [fancyapps/fancybox#2241]
**Describe the bug**
Hi, I use FancyBox 3.5.6. It works great, but I discovered a strange bug : when viewing an article with photos, FancyBox opens first photo when clicking on a "#comments" link at the top of the article.

**To Reproduce**
1. Go to https://racingstub.com/articles/18201-detour-de-flandre
2. Click on "20 comm." at the top (link to anchor #comments)
2. The FancyBox opens instead of going to the bottom of the article at the comments

**JS code**
```js
$('a.st-img-fancybox').fancybox({
        image: {
            preload: false
        },
        ajax: {
            preload: false,
            settings: {
                data: null
            }
        },
        hash: false,
        buttons: [
            "zoom",
            "slideShow",
            "fullScreen",
            "thumbs",
            "close"
        ],
        thumbs : {
            autoStart : true
        },
        lang: 'fr',
        i18n: {
            fr: {
                CLOSE: 'Fermer',
                NEXT: 'Prochain',
                PREV: 'Précédent',
                ERROR: '<p class="fancybox-error"><strong>Attention !</strong><br />Problème de chargement.<br/>Veuillez réessayer plus tard.</p>',
                PLAY_START: 'Démarrer le diaporama',
                PLAY_STOP: 'Mettre en pause le diaporama',
                FULL_SCREEN: 'Plein écran',
                THUMBS: 'Vignettes',
                DOWNLOAD: 'Télécharger',
                SHARE: 'Partager',
                ZOOM: 'Zoom'
            }
        },
        caption: function(instance, item) {
            if ($(this).data('id') && $(this).data('type') != 'ajax') {
                return '<strong>' + ($(this).is('[title]') ? $(this).attr('title') : '') + '</strong> <a href="' + $(this).attr('href') + '" class="btn btn-primary btn-sm pull-right">Voir en détails</a>';
            }
            return '';
        },
        afterShow: function(instance, slide) {
            if (slide.opts.$orig.data('id') && slide.opts.$orig.data('type') != 'ajax') {
                fancyboxAfterLoadAjax(slide.opts.$orig);
            }
        }
    });
```

I don't understand this behavior, is it a bug or what I am doing wrong ?

**Comment by fancyapps** [comment]
Hi,

You have `data-fancybox="comments"` on your page, and, since you have not disabled `hash` module, changing hash to `#comments` will start fancybox, as expected.

**Comment by cbeyer** [comment]
Thanks for your answer. In my JS code is 

```js
hash: false,
```

Does this not disable hash module for this FancyBox call ?

**Comment by fancyapps** [comment]
For selected elements only. IF you wish to disable globally, then you have to set `$.fancybox.defaults.hash = false;`. But the simplest solution for your would be to just change `data-fancybox="comments"` to something else.

**Comment by cbeyer** [comment]
I prefer use the "disable globally method" instead of renaming my `data-fancybox` properties, but adding `$.fancybox.defaults.hash = false;` changes nothing :/

**Comment by cbeyer** [comment]
Any help why `$.fancybox.defaults.hash = false;` has no effect ?
