### ISSUE TITLE
Page reloading after opening second image

### ISSUE THREAD

**Issue by iruy** [fancyapps/fancybox#2242]
I have a page with two images, if I follow these steps, my page reload:
- click on image 1
- click outside and close it
- click on image 2
- click outside and close it
====> the page is reloaded

I guess it's someting concerning the page hash so I tried to disable with `$.fancybox.defaults.hash = false;` but nothing changed.. Any idea if this is a bug or I just need to add some option?

thanks

**Comment by fancyapps** [comment]
Hi,

I can not reproduce this and, since you did not provide any valuable information, I am not able to help you.
