### ISSUE TITLE
Retina images are slightly smudged when zooming in and panning on canvas/slide

### ISSUE THREAD

**Issue by edusantosdev** [fancyapps/fancybox#2243]
I'm having a curious problem with my retina images on my website: https://edusantos.me/#substance-2

When zooming in I get @2x images, but they appear slightly blurred. It's as if the image is getting half pixels for its width and height when panning across the canvas.

What's interesting though is that when panning into the edges / corners of the canvas, the image gets back to being super sharp, as if "docking" is forcing the image to get 1:1 pixels.

I'm not sure if this was properly explained, because you really need to look attentively at the images to get the problem. This is very noticeable on horizontal and vertical shapes, or typography that looks smudgy.

As far as I've been able to test this is bug visible on all browsers on macOS.

Thank you!

P.S. Your plugin is amazing, seriously! I've experimented quite a few and so far it's the smoothest, least bug free of them all. I'm probably nit picking here, but solving this bug would make it absolutely perfect! :)

**Comment by edusantosdev** [comment]
I've temporarily changed this snippet (below) of code to 0 so that the image is zoomed in to the top and left corners. This ensures the image is NOT blurry/smudgy initially when you zoom in. Once you start panning the image becomes blurry/smudgy.
![image](https://user-images.githubusercontent.com/1864559/56080877-7525d200-5dfe-11e9-930b-b5a7d6399ecb.png)

To my understanding, there is something about the calculation of image position based on its resized width and height, on canvas, that is causing this. 🤔

**Comment by fancyapps** [comment]
Hi,

Hmm, interestingly, your HTML and JS snippet works fine - https://codepen.io/anon/pen/ZZJRLp?editors=1000 - so, maybe this issue is caused by some of your customization?

**Comment by edusantosdev** [comment]
Hi, thanks for the fast response!

I took a look at your code pen and the problem is actually visible (although it can be quite hard to spot sometimes because the image randomly becomes smudgy or 1:1 while panning).

Here's a screenshot describing what I mean on closer inspection. In this case, after panning, this button got vertically blurry.
![image](https://user-images.githubusercontent.com/1864559/56081281-668de980-5e03-11e9-9826-977ff013b64c.png)

In terms of customisation, the only major customisation I did was in terms of style to the buttons. The JS file is pretty much intact (no code modifications apart from the one I've posted earlier).

My best guesses are that while panning, an extra 1px is being added either horizontally or vertically to the image, causing this issue. But I'm having a hard time pinpointing the source of this strange behaviour.

Thanks again for your patience on this nit picking matter. :)

**Comment by fancyapps** [comment]
Oh, sorry, you were referring to blurriness, but I thought the issue was about incorrect image position after zooming-in. 

Maybe this snippet will work better for you:

```JS
$('.retina-fancybox').fancybox({
  afterLoad : function(instance, current) {
    var pixelRatio = window.devicePixelRatio || 1;

    if ( current.src.indexOf(`@2x`) > -1 ) {
      current.width  = current.width  / 2;
      current.height = current.height / 2;
    }
  }
});
```

**Comment by edusantosdev** [comment]
Thank you! Unfortunately, the issue is still happening.

In the meantime, I've made an experiment. I've set "momentum" to false, and the image doesn't get smudgy after dragging, although now I don't have the inertial animation. 😬

![image](https://user-images.githubusercontent.com/1864559/56081505-03518680-5e06-11e9-85e0-cd7d3aad7d63.png)

But this is only possible if if I set the zoom in position of x, y values to 0 rather than letting it calculate based on cursor position (I think this is what's happening in your code?).

![image](https://user-images.githubusercontent.com/1864559/56081516-2845f980-5e06-11e9-8213-1aefd3a727af.png)

So, what I'm understanding is that there's 2 elements making images blurry:

a) If the zoom-in position of the image is not determined by the position of the mouse cursor, the image is perfectly accurate when you zoom in (if x, y set to 0).

b) If the momentum is set to false, the image won't get blurry.

I think there is something with the zoom-in animation and the calculation of the "final position" after panning happens, that is causing images to get blurry. 🤔

I'm going to keep investigating.

**Comment by edusantosdev** [comment]
I think it must have to do with this code somehow and how the newPos is calculated.

`  Guestures.prototype.endPanning = function () {
    var self = this,
      newOffsetX,
      newOffsetY,
      newPos;

    if (!self.contentLastPos) {
      return;
    }

    if (self.opts.momentum === false || self.dMs > 350) {
      newOffsetX = self.contentLastPos.left;
      newOffsetY = self.contentLastPos.top;
    } else {
      // Continue movement
      newOffsetX = self.contentLastPos.left + self.velocityX * 500;
      newOffsetY = self.contentLastPos.top + self.velocityY * 500;
    }

    newPos = self.limitPosition(newOffsetX, newOffsetY, self.contentStartPos.width, self.contentStartPos.height);

    newPos.width = self.contentStartPos.width;
    newPos.height = self.contentStartPos.height;

    $.fancybox.animate(self.$content, newPos, 366);
  };`

**Comment by edusantosdev** [comment]
Looks like Firefox is not exhibiting this issue after all. 😱

**Comment by fancyapps** [comment]
I'm sorry, but I do not think there is a solution to this problem, because this is how browser renders image when `transform: translate` used on image itself or some parent element. You can easily check it out like this: 1) open your image in new tab; 2) use developer tools to apply `transform: translate(1px, 1px);` to your image; 3) if you take and inspect before/after screenshots you would find, that, for example, letter `l` is originally [ffffff,ffffff], but then it becomes [f9f9f9, ffffff] (I hope you understand what I meant by that). The only solution I can think of would be to switch from `transform: translate` to absolute position and to use top/left values for positioning. But that would degrade the performance :/

**Comment by edusantosdev** [comment]
Thanks so much for looking into this, really!

I think I'm going to have to live with this then. :)
