### ISSUE TITLE
How to play an audio file in the light-box?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2244]
I can play an mp3 audio file with the next code:

    <a data-fancybox="S" href= "bensound-sunny.mp3"  data-type="iframe" data-caption=
      '&quot;Sunny&quot; composed by Benjamin Tissot '>
      <img src="res/audio.png"   width="100" height="100" alt="" 
    title=" &quot;Sunny&quot; composed by Benjamin Tissot " />
    </a>

To see it, click on the 9th thumbnail of [this album](https://andrewolff.jalbum.net/FancyBoxVideoTest/ ).

If I run this album locally, I see the the audio controls immediately (see the left window below), but if I run it on-line from a server, I see initially  no audio controls (see the right window below).
To get the audio controls on-line in the view port, I have to scroll down.

What do I have to add / change to see the audio controls also on-line immediately?

You see this with the Chrome browser: (Left Offline, right Online)

<img width="731" alt="MP3-file" src="https://user-images.githubusercontent.com/8150784/56097192-5fdda000-5ef1-11e9-9e7e-f7b74be03ed1.PNG">

**Comment by shortmort37** [comment]
Can you expand on how you add that to the fancyBox init function?  I can't view the source of the album you cite.

**Comment by acwolff** [comment]
function initFancyBox() starts at line 280 of this module: https://andrewolff.jalbum.net/FancyBoxVideoTest/slidePage.js

Other modulus:
html: https://andrewolff.jalbum.net/FancyBoxVideoTest/index.html

css: https://andrewolff.jalbum.net/FancyBoxVideoTest/res/common.css

js: https://andrewolff.jalbum.net/FancyBoxVideoTest/res/indexPage.js

**Comment by shortmort37** [comment]
Thanks for providing your code.  I'm afraid the complexity of all of it is beyond me.  But, I take it that the important concept is to delay iframe preload.  No obligation to debug my code, but any ideas why this doesn't work?

http://www.59plymouth.net/lightbox/fancybox.html

**Comment by fancyapps** [comment]
@shortmort37 The simplest solution would be like this:

```HTML
<a data-fancybox data-type="video" data-src="http://www.59plymouth.net/lightbox/media/rusty.mp3">
  <img src="http://www.59plymouth.net/lightbox/media/6_thumb.jpg" />
</a>
```

Demo - https://jsfiddle.net/xk6so802/

**Comment by shortmort37** [comment]
Wow.  That was easy!  Just call it a video - no iframe necessary.  What are the chances mp3 could be added as a default MIME type for FancyBox to permit in a gallery, along with jpg, gif, pdf, and mp4?  It's easy enough to add conditional code to insert an additional tag for mp3, but it wouldn't be necessary if FancyBox managed it.  All the same - this was a great hint.  Thanks!

**Comment by fancyapps** [comment]
I was quite sure that no one will want to use fancybox (or any lightbox) to play audio, but looks like there are some cases, therefore it will be reconsidered :)

**Comment by acwolff** [comment]
@fancyapps I added your demo method to my JAlbum FancyBox skin as you can see in this [demo album](https://andrewolff.jalbum.net/SongBook/). If I open the light-box and click the play button, the mp3 file is played with the image visible on a pc and on an iPad, but on an iPhone the image disappears. I see the same with your pen demo. Have youany idea how I can prevent that the image disappears onan iPhone?

**Comment by acwolff** [comment]
@fancyapps I added your demo method to my JAlbum FancyBox skin as you can see in this [demo album](https://andrewolff.jalbum.net/SongBook/). If I open the light-box and click the play button, the mp3 file is played with the image visible on a pc and on an iPad, but on an iPhone the image disappears. I see the same with your pen demo. Have youany idea how I can prevent that the image disappears on an iPhone?

**Comment by fancyapps** [comment]
@acwolff You should address this question to developers of webkit. In case you still do not understand, fancybox just creates DOM structure, the rest is up to the browser (e.g., how it renders video/audio element).
