### ISSUE TITLE
Vimeo URL Matcher needs updating

### ISSUE THREAD

**Issue by btdevdesign** [fancyapps/fancybox#2246]
Hi, I just discovered that v3.5.7 fails to load Vimeo video URLs in the video fancybox (https://fancyapps.com/fancybox/3/docs/#video)

It appears the vimeo regex fails to return the correct URL. 

`Line 3465` of `jquery.fancybox.js`:
```
vimeo: {
      matcher: /^.+vimeo.com\/(.*\/)?([\d]+)(.*)?/,
      params: {
        autoplay: 1,
        hd: 1,
        show_title: 1,
        show_byline: 1,
        show_portrait: 0,
        fullscreen: 1
      },
      paramPlace: 3,
      type: "iframe",
      url: "//player.vimeo.com/video/$2"
 },
```
fails for me with a vimeo URL like `https://vimeo.com/299000000/000d0d0fa0` (not a real URL for this example) but works fine when I use:

```
vimeo: {
      matcher : /(?:vimeo(?:pro)?.com)\/(?:[^\d]+)?(\d+)(?:.*)/,
      params: {
        autoplay: 1,
        hd: 1,
        show_title: 1,
        show_byline: 1,
        show_portrait: 0,
        fullscreen: 1
      },
      paramPlace: 3,
      type: "iframe",
      url  : '//player.vimeo.com/video/$1'
},
```
which I pulled from the very old `jquery.fancybox-media.js`, v1.0.6. It also works with a URL structured like `https://vimeo.com/191947042` for the record.

**Comment by fancyapps** [comment]
Hi,

Could you provide a valid test case for this? E.g., all typical vimeo urls work fine with current URL matcher. The only issue is with custom urls like `https://vimeo.com/something/else`

**Comment by btdevdesign** [comment]
Hey thanks for the reply,

I'm realizing now that the links I have been using are private which is probably why the url format is different. Yes, the ID is for my example is `299000000`. 

However, I think a good case can be made to have Fancybox support Private link formats: Vimeo themselves say that Private links can still be embedded:

> Only people with the private link is a semi-private setting that will make your individual video visible only to people who have the link. ... Hide this video from vimeo.com will make the video unable to be accessed on the Vimeo website (unless you are logged in as yourself), but it still can be embedded on other websites.
[Video privacy, explained on Vimeo](https://vimeo.com/blog/post/video-privacy-explained)

Is it possible to have Fancybox's Vimeo Regex updated to support the private link fomrat? `https://vimeo.com/299000000/000d0d0fa0`

**Comment by fancyapps** [comment]
The fact is, I can not be sure that this would work for others, too. I'm closing this issue since this feature request (for enabling private videos) already exists (somewhere) and that will be implemented after big rewrite to use Vimeo SDK instead of basic embedding.

**Comment by Read1337** [comment]
> Hi, I just discovered that v3.5.7 fails to load Vimeo video URLs in the video fancybox (https://fancyapps.com/fancybox/3/docs/#video)
> 
> It appears the vimeo regex fails to return the correct URL.
> 
> `Line 3465` of `jquery.fancybox.js`:
> 
> ```
> vimeo: {
>       matcher: /^.+vimeo.com\/(.*\/)?([\d]+)(.*)?/,
>       params: {
>         autoplay: 1,
>         hd: 1,
>         show_title: 1,
>         show_byline: 1,
>         show_portrait: 0,
>         fullscreen: 1
>       },
>       paramPlace: 3,
>       type: "iframe",
>       url: "//player.vimeo.com/video/$2"
>  },
> ```
> 
> fails for me with a vimeo URL like `https://vimeo.com/299000000/000d0d0fa0` (not a real URL for this example) but works fine when I use:
> 
> ```
> vimeo: {
>       matcher : /(?:vimeo(?:pro)?.com)\/(?:[^\d]+)?(\d+)(?:.*)/,
>       params: {
>         autoplay: 1,
>         hd: 1,
>         show_title: 1,
>         show_byline: 1,
>         show_portrait: 0,
>         fullscreen: 1
>       },
>       paramPlace: 3,
>       type: "iframe",
>       url  : '//player.vimeo.com/video/$1'
> },
> ```
> 
> which I pulled from the very old `jquery.fancybox-media.js`, v1.0.6. It also works with a URL structured like `https://vimeo.com/191947042` for the record.

This worked for me.
I was trying to use "private" videos on vimeo but they fail to load with normal fancybox js. With these changes I can use the private links.
