### ISSUE TITLE
Arrow buttons on an iPhoneXR are too far-away from the sides

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2248]
I use fancyBox to display bridge club results in iframed pages, see [this page](http://www.bs-almelo.nl/BS-Almelo_uitslagen/#S-4 ).

If I display this page on my iPhoneXR in landscape mode, the arrow buttons are too far-away from the sides:

![BSA_iPhone_Landscape](https://user-images.githubusercontent.com/8150784/56420708-52346b80-629f-11e9-9469-9d4bce3c4134.PNG)

It is OK on a PC:

<img width="592" alt="BSA_PC" src="https://user-images.githubusercontent.com/8150784/56420742-7b54fc00-629f-11e9-9714-cc3ca2335321.PNG">

and on my iPhone in portrait mode:

![BSA_iPhone_Portret](https://user-images.githubusercontent.com/8150784/56420865-16e66c80-62a0-11e9-9551-049c795288d2.PNG)

It becomes better if I remove the next CSS lines:

    left: env(safe-area-inset-left);
    right: env(safe-area-inset-right);

from the fancybox-navigation buttons css code:

![BSA_iPhone_Landscape_NoEnv](https://user-images.githubusercontent.com/8150784/56420833-e0105680-629f-11e9-9e6e-6d120ea0c74c.PNG)

**Comment by fancyapps** [comment]
I do not understand what are these screens, but everything is fine by default and you can adjust to your needs. Just do not forget to make your site to use whole screen (see https://webkit.org/blog/7929/designing-websites-for-iphone-x/)
