### ISSUE TITLE
Retrieving the caption from alt attribute - fancybox v3.5.7

### ISSUE THREAD

**Issue by tomi02** [fancyapps/fancybox#2250]
Hello
Unfortunately, in the latest fancybox v3.5.7 it does not work:
`$('[data-fancybox="images"]').fancybox({ 
  afterLoad : function(instance, current) {
    current.$image.attr('alt', current.opts.$orig.find('img').attr('alt') );
  }
});`
[https://codepen.io/anon/pen/QOBgqz?editors=1010](url)

Instead of adding data-caption = "..." I want to get a description of the photo from the description contained in the alt attribute
`<a data-fancybox="gallery" href="big_1.jpg"> <img src = "small_1.jpg" alt = "..."> </a>`
Please help.

**Comment by fancyapps** [comment]
Hi,

Your snippet works fine, but, if you want to customize caption, see https://fancyapps.com/fancybox/3/docs/#faq-2 and then do something like this:

```JS
$('[data-fancybox="images"]').fancybox({ 
  caption : function( instance, item ) {
		return $(this).find('img').attr('alt');
	}
});
```

https://codepen.io/anon/pen/gyJPYj?editors=1010
