### ISSUE TITLE
Opening Fancybox 3.5.7 gallery via text links ?

### ISSUE THREAD

**Issue by Solmier** [fancyapps/fancybox#2253]
Is there a possibility to open a gallery using a text link without an image like here: http://jsfiddle.net/m8ynV
All that I managed to find unfortunately doesn't work with the latest 3.5.7 version.

**Comment by fancyapps** [comment]
Hi,

1) I really don't understand why people sometimes ask something like - "Is there a possibility to open a gallery using a text link without an image" - it just does not matter what your link contains and it has never been important in any version of fancybox. You put thumbnail image for zooming effect and in other cases it will fade-in (by default).

2) For cases like this, fancybox v3 provides a handy `trigger element` feature, see this demo - https://codepen.io/fancyapps/pen/VGoRqO?editors=1010

**Comment by Solmier** [comment]
Hello, I think it is necessary in those cases when all the images should be hidden and used launch by link.
Everything works fine, thank you.
