### ISSUE TITLE
Disabling History? - fancybox keeps popping on either left or right swipe

### ISSUE THREAD

**Issue by emage** [fancyapps/fancybox#2254]
phone: iphone X
Steps:
1. load my site
2. click on fancybox gallery
3. close fancybox gallery
4. scroll down the page to see more content
5. edge swiping from right or left somehow pulls in the fancybox gallery - not desired. This conflicts with the swipe to see more product on the horizontal scroll or any swipe.

Users was reporting this about our site and it was annoying to them.

Checking history - it shows that each fancybox gallery image shows a URL -- so swiping left or right on IOS simply slides these fancybox gallery image in.

**Comment by fancyapps** [comment]
Hi,

Set `hash:false` (or simply `$.fancybox.defaults.hash = false;`) to disable that feature. Keep in that android users would expect that hiting back button would close fancybox and the only solution to implement that is to create new history entry.
