### ISSUE TITLE
Does fancybox have a zoom controller option?

### ISSUE THREAD

**Issue by aeu** [fancyapps/fancybox#2255]
Hello Fancybox,

Is there functionality to allow a slider or some other type of control via which the user can adjust how much zoom there is?

Thank you.

**Comment by fancyapps** [comment]
Hi,

If you refer to custom zoom levels, then there is currently no such option, but there is already a feature request for that. If you want to create custom zoom button for images, then you can use `scaleToActual()` and `scaleToFit()` methods, for example, `$.fancybox.getInstance().scaleToActual()`
