### ISSUE TITLE
Video doesn't autoplay

### ISSUE THREAD

**Issue by ellemaker** [fancyapps/fancybox#2256]
here is the codepen

https://codepen.io/anon/pen/rgxKQP

**Comment by dariodev** [comment]
Same here. Autoplay works in Firefox, but does not in Chrome. Strange thing is that Fancybox home page example works fine in Chrome. I set Codepen and jsFiddle with the same videos and js versions as the Fancybox home.
https://codepen.io/dariodev/pen/eaZGEM
https://jsfiddle.net/dariodev/rhup5jmo/

**Comment by fancyapps** [comment]
This already has been discussed here on other posts about this topic; See https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by dariodev** [comment]
But examples in your page does autoplay in Chrome! Can you please explain that? :)

**Comment by fancyapps** [comment]
Check link from previous comment and find 

> Autoplay with sound is allowed if:

The script works fine, you can test this by yourself by changing auto-play policies in chrome settings.
