### ISSUE TITLE
fancybox scales to data-width/data-height despite srcset, overzooming

### ISSUE THREAD

**Issue by whatsnewsisyphus** [fancyapps/fancybox#2258]
Hello all, thanks for the work as always.

I have images that look like below when rendered, and with sizes set to 100vw, and so pull the 1280px wide source on this particular computer. However, when I click the zoom button, it scales them 2880px high from the original data-height (I feed it the largest srcset/original size for proportions). With this, it unfortunately tries to scale upto that data-height/width rather than the srcset it loaded. 

*edit even with explicit size removed, the vertical images get over zoomed for some reason?

```
<div class="fancybox-content" style="transform: translate(166px, 44px) scale(1, 1); width: 700.336px; height: 568px;">
	<img class="fancybox-image" src="http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-180x146.jpg" style="display: none;">
	<img class="fancybox-image" src="http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-1280x1038.jpg" sizes="100vw" srcset="http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-180x146.jpg 180w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-240x195.jpg 240w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-360x292.jpg 360w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-480x389.jpg 480w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-720x584.jpg 720w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-960x779.jpg 960w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-888x720.jpg 888w, http://45.32.177.194/wp-content/uploads/2019/05/opera_houses_18-1280x1038.jpg 1280w">
</div>
```

**Comment by fancyapps** [comment]
Hi,

Sorry, but I could not understand your comment. Any live demo would help - https://stackoverflow.com/help/mcve

Also, since srcset is hard to debug (you newer know what and why browser does; it is not consistent across browsers) and to use, it will be removed in future releases and will be replaced with something simpler and more reliable.

**Comment by whatsnewsisyphus** [comment]
This is not about srcset parsing differences,  I tried it on safari, firefox and chrome all.

I think it might have to do with your sizes being set to 82vw for verticals and the way DOM reads width on rendered image elements. You want naturalWidth rather than width in scaleToActual within core.js

https://css-tricks.com/measuring-image-widths-javascript-carefully/

Here's a live demo that I'll keep up temporarily
http://45.32.177.194/works/libraries/

Click a vertical image like [this](http://45.32.177.194/works/libraries/#gallery-20) one and zoom vs a horizontal image like [this](http://45.32.177.194/works/libraries/#gallery-18). You can right click and view image on a separate tab and zoom in that one to see the difference

The horizontal ones zooms to actual pixel size while the vertical ones zoom way too far, going beyond the actual pixel size image, pixelating the image

![Screenshot 2019-05-10 01 21 29](https://user-images.githubusercontent.com/454772/57504324-fff4d200-72c1-11e9-8837-726e0fd77e70.png)

Besides, srcset is the standard that is being used everywhere and is getting more consistent no? It's been out for 5 years now and most major websites use it.

**Comment by fancyapps** [comment]
Look, the script parses srcset for initial source, then loads image, gets width/height and sets same srcset value for image. The rest is up to the browser. And, if you think that srcset support is consistent, then you have not tried to debug it (without fancybox).

**Comment by whatsnewsisyphus** [comment]
I did not say it is consistent, it is a pain in the butt, but it is a decided standard that we should probably learn to deal with. I'm saying that because you have different sizes properties set by the script for images depending on their proportions, that width/height you are getting from them are not the 'natural' dimensions of the source but somehow different, so when you scale up using that number, it zooms in too far.

**Comment by whatsnewsisyphus** [comment]
The DOM reports (at least via JS) the width of the src image as modified by the html sizes property. From the calculation below, you are setting different sizes attributes and so when you read them out in ScaleToActual, you end up reading not the width/height of the source image but that times 100vw/Xvw

Here's a developer tool reading that shows the same result, the actual image size is 1280x1570 but gets reduced to 987x1212 as far as the DOM is concerned.

![Screenshot 2019-05-10 01 42 02](https://user-images.githubusercontent.com/454772/57505066-f0c35380-72c4-11e9-8509-520e3d08afb6.png)


```
if (slide.opts.srcset) {
            sizes = slide.opts.sizes;

            if (!sizes || sizes === "auto") {
              sizes =
                (slide.width / slide.height > 1 && $W.width() / $W.height() > 1 ? "100" : Math.round((slide.width / slide.height) * 100)) +
                "vw";
            }

            $img.attr("sizes", sizes).attr("srcset", slide.opts.srcset);
}
```

**Comment by fancyapps** [comment]
To be honest, I have already replaced `srcset` with another option for the upcoming major version, it will work like this:

```JS
<a href="img/small.jpg" data-responsive='{ 768 : { src : "img/medium.jpg" }, 992 : { src : "img/big.jpg" }'>
  <img src="img/thumb.jpg">
</a>
```
The script will look for corresponding breakpoint (on start and on windows resize) and will load appropriate source. This will deal with all the problems and confusion around srcset option and will be easy to debug.

**Comment by whatsnewsisyphus** [comment]
For app integrations where the srcset is already calculated and used like
WordPress that would be a nightmare to integrate broadly. You could string
parse the data-srcset in a similar manner and use that to load the
appropriate source just the same. Setting sizes to auto solves it too.

**Comment by whatsnewsisyphus** [comment]
Taking out the sizes calculation by making sizes = 100vw fixes this issue simply, but as I noted before, it has to do with how you get the image width from the dom. I hope that you keep the srcset as a legacy option for those who are going to be parsing standard html and perhaps combining with other libraries such as lazysizes.
