### ISSUE TITLE
Hide Thumbnails when Fullscreen On

### ISSUE THREAD

**Issue by whatsnewsisyphus** [fancyapps/fancybox#2259]
Hello,
Is there a way to tag on $.fancybox.getInstance().Thumbs.hide(); and show(); to toggling fullscreen on and off so thumbs are hidden on full screen?

**Comment by fancyapps** [comment]
Hi,

Yes, it is possible, something like this:

```JS
$('[data-fancybox="images"]').fancybox({
  thumbs : {
    autoStart : true
  },
  buttons: ['fullScreen', 'close'],
  onFullscreenChange : function(instance, current, isFullscreen) {
    if (isFullscreen) {
      instance.Thumbs.hide();
    } else {
      instance.Thumbs.show();
    }
  }
})
```

https://codepen.io/anon/pen/xNOGpy?editors=1010
