### ISSUE TITLE
Activate Fancybox in parent from iframe

### ISSUE THREAD

**Issue by HeadStudios** [fancyapps/fancybox#2260]
Hi,
I have a site here:
http://www.orangehomeprices.com.au/
And it has iframe going to page which has the Fancybox here:
https://staging1.appraise.com.au/index_styling.php

What I would like to do is when Fancybox popups it doesn't just contain itself to the iframe but expands outside of it.
https://cl.ly/729fc74b9bba/Image%2525202019-05-11%252520at%2525207.26.48%252520PM.png < iframe contained 

Is this possible with Fancybox and if so what would you reccomend?

Thanks!

**Comment by fancyapps** [comment]
Hi,

It is just a JavaScript, if you want to open fancybox in parent page, you can access it like this:

`window.parent.jQuery.fancybox.open()`.

Keep in mind that you have to include fancybox in parent page and both pages have to be on same domain - https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by thezjy** [comment]
Sorry to continue on this closed issue but what if parent and iframe are not on the same domain?

**Comment by fancyapps** [comment]
Well, everything is the same as for any other JavaScript code. Your could, for example, use https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage to communicate to parent frame.
