### ISSUE TITLE
Custom button for deleting image.

### ISSUE THREAD

**Issue by Solmier** [fancyapps/fancybox#2261]
Hello,

first of all thank you for a really wonderful fancyapp.
I saw your comment for creating a button, but I don’t understand a bit what I have to do next for get it finally work correctly.

```
$.fancybox.defaults.btnTpl.delete =  ;     // some svg button code
$.fancybox.defaults.buttons = ['delete','close'];
$('body').on('click', '[data-fancybox-delete]', function(e) {
var src = $.fancybox.getInstance().current.src;              // full path to image file
var idx = $.fancybox.getInstance().current.opts.$orig;  // ?

var url = ;	                  // some parameters for the request 
var params = ;          // some more parameters for the request 
 
var xhr = new XMLHttpRequest();
xhr.open("GET", url+params, true);           // link to send removal request 
xhr.setRequestHeader("Content-type", "text/html");
 xhr.send();

 function refresh() {             // script refresh after deletion to get actual list
       $.ajax({
        url: "",
         dataType: "text",
         success: function(html) {
           $('#fu').replaceWith($.parseHTML(html));
           setTimeout(refresh,2000);
         }
       });
    }
 refresh();
 location.reload(true);           // page refresh after deletion to get current list images
 });
```

My action delete link looks like this: "www.websitename.com/actions/file_manager_action.php?delete=image.jpg" How can I get the name of the file being viewed and the website address separately in order to form a correct removal request from them ? I do not know what exactly is in var idx, maybe this one can somehow be adjusted to the one I need or maybe there is a better solution for deleting an image with JS tools without using php at all, sorry bur I have almost no experience with JS.

**Comment by fancyapps** [comment]
Hi,

First, I think that you should use some ID instead of file name. You could add custom properties like `data-file-id="123"` for your links and then you could retrieve current ID like this:

`$.fancybox.getInstance().current.opts.$orig.data('file-id')`

Since you are already using jQuery, you could use http://api.jquery.com/jquery.ajax/ to make ajax request. But, to be honest, your workflow looks awkward to me. I would suggest you to either use response of ajax request to update appropriate part of the page (e.g., image list or smth like that), or you could redirect to something like websitename.com/images/delete/123 (and your controller would redirect to /list/). I do not know if you are using some framework or not, but I would suggest to use one, for example, Laravel and use Restful commands like DELETE

**Comment by Solmier** [comment]
The site uses only Smarty template engine. File names or paths to them are not stored in the database, they are only located in the folder, so I cannot add any ID to them.  I have never worked with ajax, so I can’t imagine the procedure, it can take weeks only for this function since I do not have sufficient knowledge, and I am not sure whether it is possible at all in this situation.

Can you help me with getting one variable only with the _name of the file_ being viewed like image.jpg and another only with the _site address_ separately like websitename.com, with them I would be able to make a removal request ?

**Comment by Solmier** [comment]
The previous question is resolved, please let me know this code for adding a button only works in the body tag, how can I use it to the head tag, is it possible or maybe it can be included in some place in the jquery.fancybox.js file ?

**Comment by fancyapps** [comment]
It is just a JavaScript, you can include it anywhere after main fancybox.js file.

**Comment by Solmier** [comment]
I thought so too, so for a long time I could not understand why this was not working. Your code taken from [here](https://fancyapps.com/fancybox/3/docs/#faq-3) also does not work in the head tag, after pressing the button, nothing happens, I asked my friend to check it and he got the same result...

I use the following code `$('#fu').load(document.URL +  ' #fu')` to update appropriate part of the page instead of the the awkward code that I used earlier, after deleting the file it disappears from the list, but how can I restart the fancybox without reloading the page to get the current list in it, is there a reboot function that I could use ?

**Comment by fancyapps** [comment]
There is currently no method available for removing a slide or refreshing current instance. You could quickly close current instance:

`$.fancybox.getInstance().close(true, 0)`) 

and then quickly open another, for example:

`$.fancybox.open( $('[data-fancybox="images"]'), {animationEffect : false} )`

And about your ` I could not understand why this was not working` comment - most likely you attach click event to body before body even exists, right?

**Comment by Solmier** [comment]
Thanks for your link, it looks like you were right about using ready function. I can’t re-open a  fancybox using a call after it is closed, it doesn’t work.
