### ISSUE TITLE
MixitUp and fancybox3 - how to create "all" btn

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [fancyapps/fancybox#2262]
Click on "blue" show only blue images (Works fine).

Any idea how to create this idea:
mixitup - click on <kbd>all</kbd> ==> The lightbox will show `all images` (And not only green-green-green -or- blue-blue-blue).

Some way to group `data-fancybox` for all images when users clicks "all".

https://codepen.io/ezra_siton/pen/JydYqm

> 

> Almost 1K saw this codepen - so maybe the solution will be helpful for other users.

**Comment by fancyapps** [comment]
Hi,

See this demo - https://codepen.io/fancyapps/pen/NLQJQp?editors=1010

**Comment by Ezra-Siton-UIX** [comment]
`  selector : '.mix:visible a',` do the trick! Thanks a lot - awesome solution
