### ISSUE TITLE
How to disable refresh page after close Fancybox gallery?

### ISSUE THREAD

**Issue by vndevil** [fancyapps/fancybox#2263]
Hi,

I want to disable refresh page after close Fancybox gallery. How can I do this??

**Comment by fancyapps** [comment]
Hi,

First, if you want to know how to execute your code after closing fancybox, then you can use `afterClose` callback.

About disabling page refresh - please, use Google or SO (for example, https://stackoverflow.com/questions/2482059/disable-f5-and-browser-refresh-using-javascript) for questions like this

**Comment by vndevil** [comment]
$.fancybox.defaults.hash = false;
Resoled issue :D

**Comment by fancyapps** [comment]
FYI, one of the reasons why hash module exists is that people on Android devices expect that hitting back button would close modal. Since it is not possible to prevent navigating back, the only solution is to create new history entry on start (and navigate one entry back on close).
