### ISSUE TITLE
Zoom effect with small size image 

### ISSUE THREAD

**Issue by vhmehta1** [fancyapps/fancybox#2264]
Hi

I am displaying images with fancybox
- on click of thumbnail displaying large image with some dummy text below it
- on click of large image displaying zoom and removing that dummy text

issue is when there is small image like in the demo page
it just showing effect that image is dropping down only 
no effect of zoom on it, working proper for large images 

can it possible to remove that dropping effect when there is small images are there
and display image in center of screen

First four images are small, and next four images are large
Demo: https://codepen.io/vhmehta1/full/VOmKWP

**Comment by fancyapps** [comment]
Hi,

I could not understand your comment at all and your demo works fine.

**Comment by vhmehta1** [comment]
Hi,

In demo first four images are set to low resolution that is 800x600.
when you zoom those images, it just slide down side instead of stay in center and zoom

Step to generate it:
-> Click on First thumb
-> it will open large image of 800x600 with some dummy text below it
-> Click on large image will hide the dummy text area and image go to down side instead of zooming it.

can it possible to display that image in center and zoom it

**Comment by fancyapps** [comment]
You have customized quite heavily, you have changed layout and modified click event. So, the script does what you told it to do. And, if image is not zooming in, then, ... obviously.... it is too small to be zoomed in. You can check if you can actually zoom by using `isScaledDown` method and if is not, then .. just don't hide your stuff.
