### ISSUE TITLE
Firefox for Android open fancybox on top of page without scrolling to

### ISSUE THREAD

**Issue by whatsnewsisyphus** [fancyapps/fancybox#2267]
I don't know if this is a browser bug as other browsers don't seem to have this issue but in firefox for android (on pixel 3a), fancybox overlays opens on the very top of the page but the browser is not scrolled to position. It will further open multiple fancyboxes if you click other images, and you end up with a stack of many fancybox windows.

http://45.32.177.194/works/libraries/

**Comment by whatsnewsisyphus** [comment]
It had to do with the padding on the parent container, I'm still trying to debug what was going wrong with it but removing custom padding seems to have changed it in places. Doesn't work in main page still http://45.32.177.194

**Comment by fancyapps** [comment]
Hi,

So, this issue can be found only on your page?

**Comment by whatsnewsisyphus** [comment]
Hello, It could be on other pages, Astra is a pretty common theme and that's where the padding is coming from. I'll let you know once I figure out what's bothering firefox

**Comment by fancyapps** [comment]
Obviously, I wanted to know if other sites work fine, for example, https://fancyapps.com/fancybox/3/

**Comment by whatsnewsisyphus** [comment]
Yes, it is not a general blanket bug affecting all configurations, it is a weird interaction with padding of the container.

**Comment by fancyapps** [comment]
What do you mean by "container"?

**Comment by whatsnewsisyphus** [comment]
Container as in the parent item of the gallery grid

**Comment by fancyapps** [comment]
Sorry, but I could not understand your answer - do you experience this issue on your site/theme only or on any site/demo?

**Comment by whatsnewsisyphus** [comment]
Only on my site currently, it might be there on other sites that use the
same wordpress framework(Astra) but I don't have list to check against so I
cannot know. I will investigate further later in the day and let you know
so that you have a record of what is causing it.

*~d*

**Comment by fancyapps** [comment]
Oh, man, I just wanted you to open, for example, project homepage to see if everything works fine there.

**Comment by whatsnewsisyphus** [comment]
I already told you that it works on your demo page fine, I don't know what
is not being communicated.

**Comment by fancyapps** [comment]
fancybox container is positioned using CSS only (e.g., simply using position:fixed; top:0;, etc), therefore I would suggest you to remove all your CSS and then place back step by step to see when things start to go wrong.

**Comment by whatsnewsisyphus** [comment]
If anybody else runs into it, this is a firefox bug of sorts that is due to content overflowing beyond the <html> boundary due to negative margins. Many columns frameworks use negative margins to offset column padding, so if you make modifications to padding you need to match the offset, if you have 15px padding but a -20 margin, that 5px goes beyond the html boundary and firefox draws that and scales the dom beyond the html perimeters, breaking the canvas. Scroll positions get messed up as well, which is probably why the fancybox appears at the top of the page, unanchored from the window rather than the top of / covering the viewport.
