### ISSUE TITLE
Caption overlay image on mobile

### ISSUE THREAD

**Issue by emage** [fancyapps/fancybox#2268]
Reading the closed report - this may be related to it as well, but looking more closely - it seems that only on mobile the `<div class="fancybox-slide fancybox-slide--image fancybox-slide--current fancybox-slide--complete" style="padding-bottom: 134px;">` does not have the `style="padding-bottom"` calculated values.

Desktop show:
`<div class="fancybox-slide fancybox-slide--image fancybox-slide--current fancybox-slide--complete" style="padding-bottom: 134px;">`

Desktop scaled to mobile viewport is ok as well.

Mobile device:
`<div class="fancybox-slide fancybox-slide--current fancybox-slide--image fancybox-slide--complete" style="">`

The style value is missing only on the physical and actual device

**Comment by fancyapps** [comment]
Hi,

Is there any actual issue/question?

**Comment by emage** [comment]
This issue may be that since the mobile is not applying that `padding-bottom` value - the caption is overlaying on top of the image - i think the image is using that `padding-bottom` to push off?

**Comment by fancyapps** [comment]
There is an option `preventCaptionOverlap` for .. well .. to prevent caption overlap 😄 and it is disabled for mobile devices, e.g., defaults have `mobile: { preventCaptionOverlap: false }`. This is done to prevent images to become so small that user can not actually see anything there.
