### ISSUE TITLE
Arrows not appearing on slideshow

### ISSUE THREAD

**Issue by bibliofille** [fancyapps/fancybox#2269]
**Describe the bug**
I have Fancybox implemented on a couple sliders on my site that are also using Flexslider. For each instance, I'm calling the arrows. On two of the sliders, the lightbox shows the arrows, however on one of them, the arrows do not show. 

**To Reproduce**

Visit the following link and click a large image from the slideshow.
[http://c69.282.mwp.accessdomain.com/artists/sanford-biggers-2/](
http://c69.282.mwp.accessdomain.com/artists/sanford-biggers-2/)

**Expected behavior**
Here's an example of a slider that is working as expected: 
[http://c69.282.mwp.accessdomain.com/current-exhibition/](http://c69.282.mwp.accessdomain.com/current-exhibition/)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.12.16
 - Browser Chrome
 - Version 74.0.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fancyapps** [comment]
Hi,

Arrows are displayed if gallery has more than one item. Please, add something like `data-fancybox="gallery"` (you can choose any name you like here) to your images and add `data-src` attributes to indicate the source.
