### ISSUE TITLE
same image request many times in new version Chrome

### ISSUE THREAD

**Issue by vircloud** [fancyapps/fancybox#2270]
**Describe the bug**

Chrome version:  75.0.3770.15, Click the link will re-request the image (or video) from server.

**To Reproduce**
1. HTML source:

```html
<a data-no-instant="true" data-fancybox="gallery" data-type="image" href="/usr/uploads/2019/05/1521173613.gif" class="light-link"><img src="/usr/uploads/2019/05/1521173613.gif" alt="355.gif" title="355.gif" class="lazy lazy2 lazyloading b-lazy"></a>
```

2. Click on '....':

image already loaded, then click <a...>

3. See error:

 same image, click once, load once, click twice, load twice (old version chrome won't).

**Expected behavior**

Should be requested only once to the server, not every click.

**Screenshots**

Chrome:

![Chrome](https://user-images.githubusercontent.com/32838469/58225386-5fd48980-7d54-11e9-99ec-95eeaff48a55.png)

Firefox( work fine):

![Firefox](https://user-images.githubusercontent.com/32838469/58225562-2c462f00-7d55-11e9-99d2-ac3f5e9af4df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.15

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fancyapps** [comment]
This issue is non-existing. Source: trust me.

**Comment by vircloud** [comment]
Hi, I checked the log, see screenshot, the problem does exist.

![2019-05-30_141326](https://user-images.githubusercontent.com/32838469/58612425-24523600-82e5-11e9-979b-b2fbcb289072.png)

This problem is not all browsers will happen, only found in the new version of chrome (>74.0.3729.108)

**Comment by fancyapps** [comment]
Then maybe you have disabled caching. This is not a real issue, because in JS you can not just magically duplicate image to display, for example, in 3 places, you have to create 3 separate img elements and the rest is up to the browser.
