### ISSUE TITLE
Image Carrousel not working (even on CodePen Site)

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2271]
I've tried severals ways to add the following code to make FancyBox LOOP some images, as per your latest version docs, and at the beginning I thought I had something missing on my code, so I checked on CodePen and even there the gallery does NOT loop. It just stops at the last image (e.g. 10/10/

`//  Fancybox SETUP 
	$('[data-fancybox]').fancybox({
		loop: true
	});`

Any pointers?

**Comment by fancyapps** [comment]
Hi,

Hmm, I wonder why you have difficulty performing such simple task -

https://codepen.io/anon/pen/PvQVwB?editors=1010

**Comment by inglesuniversal** [comment]
Hi again, I checked your code and the reason (maybe) why mine is not working....

I am dynamically creating the table as the date is being filled from FireBase, which in a way hide the DOM.

Any alternatives for that?

I can ONLY view them from 1 to 10 after render on the screen.

Regards

**Comment by fancyapps** [comment]
You see, if you add `data-fancybox` attribute to any element, you are attaching click event that starts with default options. If you wish to customize, you can apply custom options like in the demo from previous comment. If your custom options do not apply, then, most likely 1) you are using wrong selector; 2) your element do not exist at the time - in that case, use `selector` selector (see, https://fancyapps.com/fancybox/3/docs/#usage and this demo https://codepen.io/fancyapps/pen/NLQJQp?editors=1010)
