### ISSUE TITLE
How to disable "preload" after iframe has been opened?

### ISSUE THREAD

**Issue by EhabSherif** [fancyapps/fancybox#2272]
Hello,

Is it possible to disable the "preload" feature once the iframe has been showed/loaded? The reason I want to do this is if the iframe has a form inside, once submitted fancybox briefly closes and reopens and a small filcker occurs..

I've tried the following:

`$(document).on("afterLoad.fb", function(e,instance,slide){
instance.opts.iframe.preload = false;
slide.opts.iframe.preload = false;
});`

but it has no effect, the flicker only disappears when I set the "preload" to false in the defaults, but i'd like to keep it for the first time it opens.

Thank You,

**Comment by fancyapps** [comment]
Hi,

If you want to change option for current slide, then you would have to do something like this: `slide.current.opts.iframe.preload = true;`

**Comment by EhabSherif** [comment]
I have tried that indeed as per the code specified above but it still doesn't work, the option gets updated but the instance still preloads on form submission..

**Comment by fancyapps** [comment]
But did you unbind all events?

**Comment by EhabSherif** [comment]
> But did you unbind all events?

I've tried unbinding the events you specified but still same effect

$(document).on("afterShow.fb", function(e,instance,slide){
	slide.opts.iframe.preload = false;
	slide.$slide.off("refresh.fb load.fb error.fb");
});

Is there any other events I should unbind?
Thanks,

**Comment by fancyapps** [comment]
Same what? Tiny flicker? Then submit your form using ajax.

**Comment by EhabSherif** [comment]
> Same what? Tiny flicker? Then submit your form using ajax.
I know AJAX would solve it of course, I was just asking for a method to solve it without it maybe something I was missing..

**Comment by fancyapps** [comment]
Ah, sorry, I see now, try this - `slide.$iframe.unbind()`

**Comment by EhabSherif** [comment]
That did the trick, works great now 👍 Thanks
