### ISSUE TITLE
Page refreshes and "fancyBox already initialized" was raised when using in a React app

### ISSUE THREAD

**Issue by thezjy** [fancyapps/fancybox#2274]
I'm using fancybox 3.5.7 in a React (create-react-app) app and use it as an npm module following the doc: `import '@fancyapps/fancybox'`. The default option is fine with me so I don't initialize with JavaScript. 

Everything works fine until I deploy the app. After closing the lightbox the page refreshes and the console says "fancyBox already initialized". I investigated for a long time and couldn't find the answer.

**Comment by fancyapps** [comment]
Hi,

It is really not possible to give any answer without seeing your page. Maybe disabling hash module would help (for example, `$.fancybox.defaults.hash = false;`), but that is just a shot in the dark.
