### ISSUE TITLE
Is there a way to set the baseClass dynamically from the link tag?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#2275]
How do I set the baseClass from an attribute in the link?

Ex. `<a href="javascript:;" data-src="url" data-fancybox data-type="ajax" data-base-class="my-css-class">Open FancyBox</a>`

**Comment by fancyapps** [comment]
Hi,

Your answer to your own question is correct, see https://codepen.io/anon/pen/eaPEpZ?editors=1000

**Comment by seabasss** [comment]
Thank you! Should this work in v3.1.25 as well? The class does not get added for me :(

**Comment by fancyapps** [comment]
Looks like you have to upgrade, I think it won't be that complicated.

**Comment by seabasss** [comment]
OK, thanks. Can't upgrade right now unfortunately. I'll add some inline css where needed.
