### ISSUE TITLE
onClick Event callback on a link in share template not firing.

### ISSUE THREAD

**Issue by MattiaVorstenbosch** [fancyapps/fancybox#2276]
**Describe the bug**
According to fancybox docs I return a React component as a share template like so:

```
const fancyOptions = url => ({
  infobar: true,
  thumbs: {
    autoStart: true,
    axis: 'x',
  },
  baseClass: 'customBox',
  buttons: ['thumbs', 'share', 'close'],
  share: {
    tpl: renderToString(<SharingPopup url={url} />),
  },
})
```

Which looks like this:
<img width="613" alt="shareTpl" src="https://user-images.githubusercontent.com/33621526/58801243-406a1600-860a-11e9-89b4-04f95e4115e5.png">

Here's the React Component:

```
export default class SharingPopup extends Component {
  constructor(props) {
    super(props);

    this.shareAnalyticsAPI = this.shareAnalyticsAPI.bind(this);
  }

  shareAnalyticsAPI(name, value) {
    // APICall(name, value)....
  }

  render() {
    const { url } = this.props;
    const urlEncoded = encodeURIComponent(url);

    return (
      <div className="fancybox-share">
        <p>
          <a
            href={`https://www.facebook.com/sharer/sharer.php?u=${urlEncoded}`}
            onClick={() => {
              this.shareAnalyticsAPI("facebook", urlEncoded);
            }}
            className="fancybox-share__button fancybox-share__button--fb"
            target="_blank"
            rel="noopener noreferrer"
          >
            <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
              <path d="m287 456v-299c0-21 6-35 35-35h38v-63c-7-1-29-3-55-3-54 0-91 33-91 94v306m143-254h-205v72h196" />
            </svg>
            <span>Facebook</span>
          </a>
        </p>
      </div>
    );
  }
}
```

As you can see I have an onClick event that makes an API Call for tracking user events. No matter what i try, the onClick event never fires. There seems to be a e.stopImmediatePropagation. It's not in my own codebase, but seems to be build in fancybox code? Is this true?

**Expected behavior**
I expect that the onClick event fires.

**Desktop:**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by fancyapps** [comment]
Hi,

I guess this is because of <svg> element, try something like this:

```CSS
a svg {
  pointer-events: none;
}
```

**Comment by MattiaVorstenbosch** [comment]
Hi @fancyapps Wrong guess, the onClick event never fires. This is not because an svg element is blocking the click. It's definitely a deeper issue. The sharing works perfectly fine itself. Just the onClick event itself never happeneds.

**Comment by fancyapps** [comment]
You seem to be experienced developer, but why do you ignore all good practices and do not create "Minimal, Reproducible Example" - https://stackoverflow.com/help/minimal-reproducible-example ? It just works - https://codepen.io/anon/pen/PvLRXN?editors=1000

**Comment by MattiaVorstenbosch** [comment]
You are absolutely right @fancyapps, My apologies. Here's a codesandbox:

https://codesandbox.io/s/stupefied-napier-4bn3o

I'm trying to call the function *shareAnalyticsAPI* via onClick on the facebook button. But it never fires. See console for output, or atleast the absence of the output.

**Comment by fancyapps** [comment]
Oh, I see now. The simplest solution would be to remove `.fancybox-share__button` classname from the button to remove default click handler (added here - https://github.com/fancyapps/fancybox/blob/master/src/js/share.js#L93), but then you will need to replace with your own.

**Comment by MattiaVorstenbosch** [comment]
Sweet, thanks. Will look into it!

**Comment by MattiaVorstenbosch** [comment]
[![Edit stupefied-napier-4bn3o](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-napier-4bn3o?fontsize=14)

After removing the class, nothing changes in functionality. Also the onClick is still not firing.

My guess at this point is something gets lost when I pass share tpl with renderToString.

`  share: {
    tpl: renderToString(<SharingPopup url={url} />)
  }`

**Comment by fancyapps** [comment]
Sorry, but I am not familiar with React and I have no idea what is `renderToString` and what are you actually doing there. Everything works fine as described - https://codepen.io/anon/pen/PvLRXN?editors=1010

**Comment by kloneets** [comment]
@MattiaVorstenbosch, React DOM render to string only sends the initial HTML as a string without any JS. https://stackoverflow.com/questions/36233309/react-js-serverside-rendering-and-event-handlers

**Comment by MattiaVorstenbosch** [comment]
Thanks for clarifying @kloneets . Going to look into it tomorrow!
