### ISSUE TITLE
Update fancybox content for slider and thumbnailview, while fancybox is open

### ISSUE THREAD

**Issue by B0rner** [fancyapps/fancybox#2277]
Hey,

I'm using fancybox 3.3, which is a great tool!
Thank you!

During integrating the fancybox into my application I get the flowing question:

I use the fancybox as an detail-viewer of an image gallery. If I click on a picture, I can slide trough the set of pictures and also see them all as thumbnails. This works great.

But, if the underlying set of pictures changes, fancybox dit not notice this change and still shows the old set of pictures. I have to close the fancybox and reopen again.

The background of my question: my application uses "endless scrolling" for set of pictures.
This means, the users expects, that new pictures are loaded, if he reaches the end of the set.
Currently I  use the "beforeShow" event, when the user slides trough the pictures. If the last picture in the set is reached, the application loads an additional set of pictures. The event works fine and new pictures are added to the underlying set pictures (where fancybox is set of).
But the slider and the thumbnail view does not notice the change of the picture-set.

Also `instance.update()`does not load the new content into the box.

//Edit: also instance.group.length is still the old number of pictures before adding the new set.

Is there API method or something like this to realize an "endless slider" or endless scrolling for the thumbnail part?

**Comment by fancyapps** [comment]
Hi, 

You can use `addContent()` method to add additional content to the instance, for example: `$.fancybox.getInstance().addContent({ src : 'image.jpg', type : 'image'});`

This method was not planned to be public, therefore it is not mentioned in docs, but you can use it anyway. Seems that people find if useful for creating smth like infinite scrolling.

**Comment by B0rner** [comment]
Hey,

thank you for that fast support. Your suggestion works great - expect the following:
I use the "beforeShow" trigger:
If I have an set of 20 pictures -> if the user reached the last picture, a new set of 20 pictures is loading. 
But if the users continue sliding, he sees the following pic numbers: 
20 (load new content) -> 1 (from the old set) -> 22 (from the new set).

It looks like, that on picture 20, the next picture (Number 1) is prepared for showing but its not being updated during the add content.

A workaround is to load the new set earlier, by reaching the picture 19. This works, if the user slides trough the pictures. But it does not work, if the user clicks at the thumbnail view at the last picture, where beforeShow (Picture 19) does not match.

2nd case
If I use an alternative event, like afterLoad, an new set of pictures is loaded if the user is on picture 19 or 20. This si nice for smooth sliding. But, it also loads a new set of pictures, if the user clicks at the thumbnail picture 1, probably because the picture 20 is preloaded at this moment, in the case the user slides back.

Did you have any suggestion, how to handle this?

**Comment by fancyapps** [comment]
To be honest, I could not understand your last comment at all, any demo would be helpful. 

If you call `addContent()` then `updateControls()` will be called automatically after adding new items, therefore all indexes, navigation states, etc should update smoothly, unless, of course, there is a delay while your load method adds new items. 

btw, do you really need infinite scrolling? fancybox only preloads prev/current/next slides, therefore your gallery can safely contain lots of items. If you do not want to create links for each item, then you can, for example, load additional items on start. Anyway, I would suggest using `beforeLoad()` callback.

**Comment by B0rner** [comment]
The problem appears, if you start fancybox with the  loop=true option.
So I  will disable this option as workaround.

https://codepen.io/anon/pen/MdxLwN

>btw, do you really need infinite scrolling?

No, I don't need it, but the users like to have it. ;-)

**Comment by fancyapps** [comment]
If you think about that, then "infinite scrolling" and "infinite looping" are quite contradictory :)

**Comment by B0rner** [comment]
Of curse, that's it. Reading your lines had open my eyes. Absolutely. 
If I combine "Infinite Scrolling" and "Infinite Looping" I should be more careful that I do not create a space-time paradox. ;-)
Thank you.
