### ISSUE TITLE
Removing padding adds a scrollbar?

### ISSUE THREAD

**Issue by LiamDawe** [fancyapps/fancybox#2278]
I'm confused on something, if I remove the padding from "fancybox-content", it seems to add a vertical scrollbar.

I'm not asking for a way to disable it, I know that's easy. I'm asking why one appears if you simply remove padding or reduce padding down a lot?

The overflow doesn't seem to make sense either, the content I am loading in has no extra, it's like the fancybox seems to always add a space at the bottom causing the scrollbar.

See these images below.

With the default overflow:
[Imgur](https://imgur.com/ow7J6UB)

With overflow: auto removed:
[Imgur](https://imgur.com/iRX2FeA)

As you can see, there's no actual overflow content, fancybox just seems to add it in itself.

The problem is, I can't just hide overflow, as sometimes we *might* actually need a scroll.

This is with the latest version.

**Comment by fancyapps** [comment]
Hi,

Sorry, I could not reproduce your issue, everything works fine for me - https://codepen.io/anon/pen/JqzyOo?editors=1100
Please, provide a link to your page or demo so your issue could be inspected.
