### ISSUE TITLE
Animation does a weird jump

### ISSUE THREAD

**Issue by kaspar-allenbach** [fancyapps/fancybox#228]
Hi.

I have a strange problem with Fancybox.

If I cylce trough my Gallery the image fadeIn from the top. When the animation is completed the images jump a little bit back to top.
That looks very annoying.

You can see it here:
http://dekonstruktiv.ch/claub_static/portfolio.html

I tried it under Safari & FF
I can't see the problem. All js are the defaults. No matter what I change the jump exists.

Has anyone a idea what can cause this issue?

thanks a lot.

–– Ah damn. Classic margin error of the parent Element. So easy :(

**Comment by jokero158** [comment]
Hi, I have the same problem, but can not solve it.
http://abdullayevtofik.com/nedvijka/item.html
CLick on the image in slider and You wil see.
Please help
