### ISSUE TITLE
There's no doubt FancyBox is one of the best LightBox Scripts ever made!

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2280]
I'm curious to know if FancyBox 4 is in the making?

The preceding statement, since I would love to get the License and at the same time, the newest features available.

Any update on upcoming releases?

Hugo

**Comment by fancyapps** [comment]
Hi,

Thanks for kind words. I wish I could say more, the work is in progress, but it is hard to tell when it will be ready.
