### ISSUE TITLE
encodeURIComponent and UTF-8 Captions in Firefox

### ISSUE THREAD

**Issue by whatsnewsisyphus** [fancyapps/fancybox#2282]
Image captions get pulled apart to letter + modifiers instead of using correct extended latin characters which introduces spaces and errors. I'm not sure if this has to do with how firefox is parsing data. ü becomes u and two dots, İ becomes I and a dot and so forth.

https://www.ahmetertug.com/works/industrial/#gallery-1

some notes here
https://github.com/owncloud/core/issues/6267#issuecomment-30159152

 I might not be on the right track with the encodeURIComponent but that's all the reference I found in parsing captions.

**Comment by fancyapps** [comment]
Hi,

I do not know why, but your font does not display some characters as supposed. For example, change font to this and it looks fine:

```CSS
.fancybox-caption {
  font-family: Helvetica,Verdana,Arial,sans-serif;
}
```

**Comment by whatsnewsisyphus** [comment]
It's not the font, embedded web fonts are never going to include that wide
a character set to include separate umlauts and accents. You can see that
it works in chrome and safari, Firefox is encoding or decoding differently
instead of using the discrete characters for accented letters.
