### ISSUE TITLE
How do I close the light-box after the last slide has been processed in a slide show?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2283]
I like to close the ligthbox after the last slide has been processed in a slide show.

I tried this:

    onSlideShowChange : function(instance, current, active) {
        if (!active) $.fancybox.close(); }
    },

but this closes fancyBox at the start of the last slide. 
How can I close it after the viewtime for the last slide is over?

This works:

    onSlideShowChange : function(instance, current, active) {
        if (!active && (slide_index === (nrofImages-1)) && stopAfterLastSlide) setTimeout(" $.fancybox.close()",viewtime);

but I think there is a more clever method!

**Comment by fancyapps** [comment]
Hi,

This is such a bad idea, very confusing for users, but if that looks good for you, then use it. I can't imagine a more clever method for you. Just keep in mind that user can start gallery with the last image.

**Comment by acwolff** [comment]
Well, [my FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox ) closes the light-box only if the user sets check-mark 'Stop after the last slide': 

<img width="534" alt="FB_Settings" src="https://user-images.githubusercontent.com/8150784/59264739-133de900-8c44-11e9-966c-d9a107f58741.PNG">

This check-mark is set in [this example album](https://andrewolff.jalbum.net/FB__JustifiedGallery_white/ ).
