### ISSUE TITLE
Invoice

### ISSUE THREAD

**Issue by dariusu** [fancyapps/fancybox#2287]
Hello,

I purchased "Extended Commercial license" although I need an invoice for accounting purposes. I did not receive any e-mail with any information. 

Where can I request an invoice?

**Comment by fancyapps** [comment]
Hi,

Currently, FastSpring ecommerce platform (https://fastspring.com/) is used to handle payments and invoicing. Unfortunately, sometimes their system does not successfully send confirmation emails. So, please, contact info at fancyapps.com (or FastSpring directly - support@fastspring.com) with your details and these emails will be resent. Thanks.
