### ISSUE TITLE
Can I use Fancybox with Vue.js?

### ISSUE THREAD

**Issue by KaitoXion** [fancyapps/fancybox#2289]
How do I use Fancybox in Vue.js?

I installed through:
`npm install @fancyapps/fancybox`

I tested; although I already got the idea that it won't work;
```
import Fancybox from '@fancyapps/fancybox
Vue.use(Fancybox)
```

~~~

so the problem here is, jQuery is not loaded, so my app cannot load with it.

Is there any way I could use it? and possible not having Vue.js app crashing is the future?

**Comment by fancyapps** [comment]
Hi,

fanncybox v3 is just a jQuery plugin, so, you use it just like ANY other jQuery plugin. It is planned that jQuery dependency will be dropped in v4, but it is hard to tell when it will be released.

**Comment by KaitoXion** [comment]
thank you for your kind reply. really appreciate it :)
