### ISSUE TITLE
Bind dynamically added/appended items using jQuery with fancybox?

### ISSUE THREAD

**Issue by mangrio123** [fancyapps/fancybox#2291]
Hi,

Is it possible to bind dynamically appended items with existing instance of fancybox?

Here is the code I am appending
`$('.list-photos-gallery .row').append('<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 photo-gallery-item"><input type="hidden" name="attachments[]" value="'+file.id+'"><div class="mt-card-item gallery_image_wrapper"><div class="mt-card-avatar mt-overlay-1"><img src="' + file.thumb + '" /><div class="mt-overlay"><ul class="mt-info"><li><a class="btn default btn-outline preview" data-fancybox="task-images" href="' + file.thumb + '" data-caption="New Image"><i class="icon-eye"></i></a></li><li><a class="btn default btn-outline delete-gallery-item" href="javascript:;"><i class="icon-trash"></i></a></li></ul></div></div></div></div>');`

I am getting following error on preview click

[http://prntscr.com/o3u0f9](url)

**Comment by fancyapps** [comment]
I am sorry, but it is unclear what are asking for.

1) Assign click event that starts fancybox to dynamically added items - see docs https://fancyapps.com/fancybox/3/docs/#usage for `selector` option.
2) Add items to already open gallery - use `addContent`, example:
`$.fancybox.getInstance().addContent({ src : 'image.jpg', type : 'image'});`
3) If you want to open gallery from other link, see https://codepen.io/fancyapps/pen/VGoRqO?editors=1010
