### ISSUE TITLE
Questions about Commercial License

### ISSUE THREAD

**Issue by y-mochizuki26** [fancyapps/fancybox#2292]
Hello,

Thank you for your wonderful plugin.
My team will use fancybox v3 on our commercial website and purchace commercial license.
We have several questions about the license of fancybox v3.

1.	Does the Single Commercial license cover our use?
Our website is a single domain commercial website. And we are using the fancybox to make our website cool, not developing plugins to sell. 
It seems that Single/Extended Commercial license was called Single/Multi Domain license before. We think the choice of Single/Extended Commercial license in the case of website is based on the number of domains.

2.	If we purchase a commercial license, is it right that only the commercial license is applied to our use and GPL v3 is not? 
The fancybox [license page](https://fancyapps.com/fancybox/3/#license) states that:
> fancybox is licensed under the GPLv3 license for all open source applications. 
> A commercial license is required for all commercial applications (including sites, themes and apps you plan to sell).

In our understanding, fancybox is distributed under the dual license. So GPL v3 license is not applied to if we purchase the commercial license.

3.	Can we make our original modal/lightbox plugin that is not a copy/modification of the fancybox?
There is the following description in the [FAQ]( https://fancyapps.com/fancybox/3/#accordion) on the license page.
> Warning You are not allowed to create a product directly competing with fancybox. For example, you are not allowed to create a premium plugin whose main purpose is to bring modal/lightbox functionality to website.

Does this mean that if we purchase the commercial lisence, you prohibit to create all products to directly compete fancybox regardless of whether the product is based on fancybox or not?

We think you are not intended to prohibit the development of original modal/lightbox functionality plugin. But our legal department says that the description is unclear, so we want to clarify the meaning.

Sincerely,
Mochizuki

**Comment by fancyapps** [comment]
Hi,

1. Yes, that would be sufficient.

2. Yes, that is right.

3. The idea is to protect from cases when someone clones the project, renames, does little (or no) modifications and sells as their own product.

Basically, by purchasing the license you are supporting the continuous development of this project (and project support). And, since there is sometimes confusion about licensing, it is planned to drop GPL licensing.
