### ISSUE TITLE
EXIF data are not read properly for landscaped images (iPhone)

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#2293]
All pictures taken on an iPhone is stored in Landscape and any taken in Portrait has instructions stored in the EXIF data to rotate the image 90 degrees; there is a lot of programs that don't read this EXIF data, hence why the picture remains in Landscape.

When you open an image without FancyBox enabled, it just opens the image into the browser which reads that data. Unfortunately, the FancyBox library doesn't.

Here is an example image
https://cdn.discordapp.com/attachments/592466996575076383/592467314805440532/IMG_1474.jpg

![IMG_1474](https://user-images.githubusercontent.com/778890/60034113-2ae88900-96aa-11e9-8e83-a554dae7abd6.jpg)

**Comment by fancyapps** [comment]
First, I am surprised that you expect that this library will read EXIF data from the file ... knowing that JS is client side. And besides this, there is currently no option for rotating the image, but there is already a feature request for that.
