### ISSUE TITLE
Check if setContent is done?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#2294]
Is there a way to see if setContent is done? I want to set focus on an input once the content is fully loaded. Is there a `.done()` feature or similar?

Not working:
```
$.get(url, function (data) {
	$.fancybox.getInstance().setContent( $.fancybox.getInstance().current, data ).find('input.field').focus();
});
```

**Comment by fancyapps** [comment]
Hi,

First, you have to understand what you actually want.

> Check if setContent is done?

The script provides a plenty of callbacks for various stages -

https://fancyapps.com/fancybox/3/docs/#events

> I want to set focus on an input once the content is fully loaded. 

You have to understand that events are in this order: 

beforeLoad -> afterLoad -> beforeShow -> afterShow

AND, if you have not disabled auto-focus feature by default (by setting `autoFocus:false`), then the script will automatically place focus on first focusable element AFTER `afterShow` event. If you wish to specify the element you wish to be places focus on, then you can add `autofocus` attribute, see this demo - https://codepen.io/anon/pen/dBZbjN?editors=1010

```JS
$('[data-fancybox="test"]').fancybox({
  afterShow: function(instance, current) {
    console.info(`"afterShow" event!`);
    
    // Replace content only once
    if (current.done) {
      return;
    }

    setTimeout(function() {
      current.done = true;

      let data = '<p><input class="field" type="text" value="" /></p><p><input class="field" type="text" value="" autofocus /></p><p><button>OK</button></p>';
      
      instance.setContent( current, data );

    }, 2000)

  }
})

```
