### ISSUE TITLE
$.fancybox.getInstance('close') closes all modals

### ISSUE THREAD

**Issue by J-Design** [fancyapps/fancybox#2295]
For some reason when running getInstance('close') it closes all modals, I though this was suppose to only close the current instance of fancybox?

**Comment by fancyapps** [comment]
Hi,

No, it works as expected. You can easily test this:

```
$.fancybox.open('<div><h1>#1 Test</h1><p>1</p></div>');
$.fancybox.open('<div><h1>#2 Test</h1><p>2</p></div>');

setTimeout(function() {
  $.fancybox.getInstance('close') 
}, 1000);

```
https://codepen.io/anon/pen/wLpWNb?editors=1010

`$.fancybox.close(true)` would close all instances.
