### ISSUE TITLE
Popup slide - my content clicks inside the slide not clickable

### ISSUE THREAD

**Issue by Dei278** [fancyapps/fancybox#2303]
I am using this configuration for fancybox  
 $('[data-fancybox="gallery"]').fancybox({
            animationEffect: "zoom",
            smallBtn: true,
            infobar: false,
            toolbar: false,
            loop: true,
            autoDimensions: false,
            padding: 0,
            height: 650,
            transitionEffect: "slide",
            slideClass:"addTaging",
            buttons : false,
            afterLoad : function(instance, current) {
            },
            afterShow: function( instance, current ) {
                $(".addTaging img").addClass("--syte-taging");
                $('.fancybox-arrow--left').appendTo('.fancybox-slide--current > div');
                $('.fancybox-arrow--right').appendTo('.fancybox-slide--current > div');
            }
        });
    });

for each slide, I have clicks events and they are not clickable, because there is click event that disables and enables the arrows and toolbar,
how can I make my clicks events clickable?

Thanks

**Comment by fancyapps** [comment]
Hi,

Without any live demo, I guess this will be the answer - https://fancyapps.com/fancybox/3/docs/#faq-5
