### ISSUE TITLE
How to combine different media in one gallery

### ISSUE THREAD

**Issue by thatshell** [fancyapps/fancybox#2305]
Trying to combine e.g. images and basic HTML in one gallery. I found this example
https://codepen.io/anon/pen/VoYdKw
but the source javascript code is apparently a different one than the one I downloaded (the one on github). I don't want to use this one, cause I prefer not compressed js file and it just feels more practical to work with the official 3.5 version rather than this. 
So am I right that this createGroup function is not included in the officially released version of fancybox? Why is that and how could I set up this kind of mixed media gallery then? 
THX.

**Comment by fancyapps** [comment]
Hi,

If you want to mix different content types like images, video, html, then ... just do that, there is no limitation, simply add `data-fancybox` attribute with same value for each link.

If you wish to add some extra content to image gallery like in that demo, then use `instance.addContent()` method:

```JS
$('[data-fancybox="images"]').fancybox({
  onInit: function(instance) {
    instance.addContent({
      type : 'html',
      content : '<div style="width:100%;max-width:300px;"><h1>Hello!</h1><a data-fancybox="photo-gallery" href="www.anothersite.com">Click here</a></div>'
    });
  }
})
```

Demo - https://codepen.io/anon/pen/PMwBWe?editors=1010

**Comment by thatshell** [comment]
Thank you! Is it possible to apply a class to the content div instead of using inline style? Using inline style, most attributes are overwritten by the fancybox-content class.

**Comment by fancyapps** [comment]
@thatshell Sorry, I could not understand your comment at all, as always, a live demo would help to understand your question/issue.

**Comment by thatshell** [comment]
I use this code and I am wondering if there is a way to have all these CSS attributes in my stylesheet rather than inside the script. And then I realised that while max-width: 700px is applied to the div, the color and background-color and also the font are not changing.

``<script>
        $('[data-fancybox="images"]').fancybox({
            onInit: function(instance) {
                instance.addContent({
                    type : 'html',
                    content : '<div style="display: none; max-width: 700px; font-family: "Times New Roman", Times, serif; font-size: 20px; background-color: black; color: #00FF00; padding: 20px; padding-bottom: 30px;"><p data-selectable="true">This is the project description</p></div>'
                });
            },
            toolbar  : false,
            smallBtn : true,
            loop: true,
            animationEffect: false,
            infobar: false,
            clickContent: false
        })
    </script>

**Comment by fancyapps** [comment]
I do not see any issue using custom class - https://codepen.io/anon/pen/zgZLeN

**Comment by thatshell** [comment]
Thank you! I got it solved. 

Another question: Using this added content, it appears that the general specifications I made for all my fancyboxes don't apply to the specific one where I append the HTML content:

`   $('[data-fancybox]').fancybox({
            toolbar  : false,
            smallBtn : true,
            loop: true,
            animationEffect: false,
            infobar: false,
            clickContent: false,
        })

        $('[data-fancybox="images"]').fancybox({
            onInit: function(instance) {
                instance.addContent({
                    type : 'html',
                    content : '<div style="max-width: 700px"><p data-selectable="true">This is project</p></div>'
                });
            },
        })
`

**Comment by fancyapps** [comment]
If you did not notice, there is a `Insert code` button in the toolbar above textarea.

**Comment by fancyapps** [comment]
Also, I could not understand your question. Again, a live demo would help (I think I have asked for a live demo a million times already).

**Comment by thatshell** [comment]
Yes, I saw that and used it, but still it loses the line breaks and seems a bit tricky to someone who has never used this forum before. 

> 
> 
> If you did not notice, there is a `Insert code` button in the toolbar above textarea.

**Comment by thatshell** [comment]
> 
> 
> Also, I could not understand your question. Again, a live demo would help (I think I have asked for a live demo a million times already).

You asked once. I will post a live demo once I have set it up. Thank you for being patient with beginners here.

**Comment by fancyapps** [comment]
About formatting. Simply paste already formatted code and press that button (it just adds `````). If I want to fix messy code (like in your comments), I simply copy it, then I open https://codepen.io/pen/, paste code in JS panel, select it and then I press shift+tab to auto-format. 

If you want to create a demo, simply open any existing Codepen demo and press Fork. Then just add your code, save and share the url.

**Comment by thatshell** [comment]
Ok, thank you. This actually helped. 
So there it is: https://codepen.io/anon/pen/GVWYqZ
and, as said, the issue being that the general modifications I made first to apply to all galleries (e.g. use smaller button) don't work for the images gallery when I append the HTML to the gallery.

**Comment by fancyapps** [comment]
Well, everything works as expected. When you call `$().fancybox()`, you are overriding any previously set options with the new ones that are based on defaults.

So, you have multiple options,  you could extend defaults https://codepen.io/anon/pen/eqvPeQ or extend your defaults https://codepen.io/anon/pen/aeJRyr or you could just apply your custom options for anything but use contition statement inside `onInit` method and add extra content when your condition is true.

**Comment by thatshell** [comment]
Okay, great, thanks!
