### ISSUE TITLE
Position the left and right arrows on the image

### ISSUE THREAD

**Issue by aeu** [fancyapps/fancybox#2307]
Hello - I have two questions.

1.  Is there a way to make the left and right arrows be on the image instead of on the left and right edge of the browser.

2. I bought the single license, but it was only after I was done that I realized that I have to buy the multi site license in order to get my question answered - how do I upgrade?

Thanks!

Alfonso.

**Comment by fancyapps** [comment]
Hi,

1. Well, there is no out-of-the-box option for that, but that is possible, see this demo - https://codepen.io/fancyapps/full/ePYNZo

2. Please, contact info at fancyapps dot com

Thanks
