### ISSUE TITLE
Clicking image hides it from page

### ISSUE THREAD

**Issue by danieltj27** [fancyapps/fancybox#2309]
When I click an image in a Fancybox gallery, the images appears in the modal but it gets hidden on the page (where the anchor tag is) and even when closing the modal the image doesn't return. I'm using version 3.5.7.

HTML

```
<a data-fancybox="album" href="http://example.com/image.png">
	<img src="http://example.com/thumbnail.png" />
</a>
```

JS

```
$('[data-fancybox="album"]').fancybox({
	closeExisting: true,
	thumbs: {
		autoStart: true,
		hideOnClose: false
	},
	wheel: "auto",
	clickSlide: "close",
	clickOutside: "close"
});
```

Both the Fancybox CSS and JS files are included properly.

Any ideas?

**Comment by danieltj27** [comment]
Oops.

After some more searching it turns out you need to include a value for the `href` on the anchor element and in prepping the code to post here I didn't realise the variable for the attribute was undefined. Sorry about that.

**Comment by AkgunFatih** [comment]
@danieltj27 show the fix cuz i dont get it
