### ISSUE TITLE
Feature Request: Gallery Preview 

### ISSUE THREAD

**Issue by andyscott12** [fancyapps/fancybox#231]
Is it possible to add a "gallery preview" to the bottom of the page when the slideshow option is being used ? 

Much like featured on this - http://www.tn3gallery.com/ - at the bottom where you can see a slider with each image and skip forward back etc ?

Thanks

**Comment by fancyapps** [comment]
Hi, If you meant thumbnail grid, then this was possible a long time ago.

v3 has built-in thmbnail module and you can customize position, dimensions using CSS, if needed:
http://codepen.io/fancyapps/pen/vgRajd
