### ISSUE TITLE
add lightbox on startup

### ISSUE THREAD

**Issue by DiegoDiazGato** [fancyapps/fancybox#2310]
How do I ...
add lightbox on startup on my site?

I'm using fancybox 3

I would like to open an image (local image) on page launch?

Thanks

**Comment by fancyapps** [comment]
Hi,

First, you have to understand that you have to learn how to start fancybox immediately. If you know how to do that, you can start fancybox on page launch, button click, etc, etc.

Now, there are generally two ways how to immediately start fancybox. The simplest way would be to use API, like this:

$.fancybox.open({
    src: $('#fancybox-modal'),
    type: 'inline'
  });

See this demo - https://codepen.io/anon/pen/oKLpXg?editors=1010

The second way would be to trigger `click` event on trigger element that starts fancybox. E.g., if you have added `data-fancybox` attribute on some element or you have called `$().fancybox()`, then you have attached click event to selected element that starts fancybox. Then it could be as simple as 

`document.getElementById("test").click();`

Demo - https://codepen.io/anon/pen/mNEprR?editors=1010

**Comment by DiegoDiazGato** [comment]
Thanks for the help. I use the following code:
The css
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"/>`

The CDN script:
`<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>`

The inline script:
`<script type="text/javascript">     
		$(document).ready(function() {        
			$("#popup").fancybox().trigger('click');     
		});
		</script>`

And the result is this [https://www.elgatodiego.com/](url)

THANKS, A LOT
