### ISSUE TITLE
Issue with purchase

### ISSUE THREAD

**Issue by chiraggmodi** [fancyapps/fancybox#2311]
I tried to purchase license but each time it failed. I tried all payment methods.

**Comment by fancyapps** [comment]
Hi,

Currently, FastSpring (https://fastspring.com/) is used to handle everything related to payments and invoicing. I'll contact their support to see if they are having some technical issues.

Thanks!

**Comment by chiraggmodi** [comment]
okey, and is there any other way to purchase it? as i have to make my customer website live, and without purchasing, I can't

**Comment by fancyapps** [comment]
Sorry, there are no other ways right now. But you can start using fancybox right now and place an order later.

**Comment by chiraggmodi** [comment]
hi, I am still not able to purchase license.
could you able to provide paypal ID, so I can directly pay there?
also I have tried wire payment but not able to pay via wire transfer as my bank don't allow to pay in foreign currency.

or if you have any other alternative.

**Comment by fancyapps** [comment]
Hi, Please, sent a note to info at fancyapps dot com

**Comment by chiraggmodi** [comment]
sent.
