### ISSUE TITLE
Modal off-center and "dim" background doesn't cover the entire page.

### ISSUE THREAD

**Issue by jelle619** [fancyapps/fancybox#2312]
**Describe the bug**
The modal is not centered and the background (used for the "dim" effect) does not cover the entire page. Some other slight visual glitches here and there.

Fancybox should be written to explicitly set a margin, even zero, for every one of its elements to improve compatibility with a page. In my instance, my page relies on the following CSS code:

```css
body > div {
  margin: 50px 10vw 50px 10vw;
}
```

This code, on the other hand, also seems to break Fancybox. The page being written to rely on this code, it cannot easily be omitted.

**To Reproduce**
1. Import Jquery, Fancybox's CSS and Fancybox's JS by linking to them in the header in that order.
2. Initialise Fancybox using ``$.fancybox.open`` (possibly in combination with ``$(document).ready(function()...);``).
3. Add the CSS ``body > div {margin: 50px 10vw 50px 10vw;}``.
4. Fancybox will not display properly.

**Expected behavior**
Fancybox's modal should be centered and the background should cover the entire page. There should be no visual glitches.

**Screenshots**
![Bug](https://i.postimg.cc/1X7BWntR/Screenshot-from-2019-07-25-10-06-02.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser Firefox
 - Version 68

**Additional context**
Page loaded from a local file.

**Comment by fancyapps** [comment]
Hi,

Sorry, but it is just not possible to predict every CSS for every page on the internet. Also, creating general rules like `body > div { ..}` is just a bad idea.

**Comment by jelle619** [comment]
Indeed, impossible it is, but for a library that's meant to work on as many sites as possible, measures that increase general compatibility should at the very least be considered.

``body > div`` is not bad in and of itself, though. If your page is very coherently and consistently structured, rules like these can save time and make your code easier to understand. It also depends on whether your site uses a lot of JavaScript, in which case you may better lean towards using classes and ids instead.
