### ISSUE TITLE
Image gallery jumps up & to the left 10 px on every image

### ISSUE THREAD

**Issue by thosalbert** [fancyapps/fancybox#2314]
Hi, I'm using a fancybox image gallery, and when i click to show or advance the image, it doesnt work smoothly like on the website example (http://fancybox.net/) . The image displays, but it jumps about 10pixels up and to the left when each image displayed.

Any idea why?

Tom

**Comment by acwolff** [comment]
How can we help you if you do not give a link to your gallery?

**Comment by thosalbert** [comment]
Thanks for responding - Sorry-  it's on an intranet which isn't publicly accessible. 

Just wondering if that issue sounds familiar to anyone or if there's anything I should check first which could save time trying to figure it out.

**Comment by fancyapps** [comment]
Hi,

You see, fancybox v1 was created long time ago when internet was dominated by IE6, therefore it is not optimized for modern webpages. Something like this might help, but you have to experiment to see what works best for you:

```CSS
#fancybox-content {
  box-sizing: border-box;
}
```
