### ISSUE TITLE
How to handle nested links if thumbnail caption contains a link

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2316]
I have a gallery with a link in the caption in the light-box and the same link below the thumbnail which opens this light-box using this html code:

    <a data-fancybox="S" href="https://www.360cities.net/image/panorama-of-kioni"  data-type="iframe"  id="0" data-caption= 'Idem, inline view made on the <a  ref="https://www.360cities.net " >360Cities site</a>'>  

    <div class="box" style = "width:260px">
    <img src="thumbs/www.360cities.net-369.jpg" width="260" height="110" alt="www.360cities.net-369" title=""  /><br>
    <div class="thumbText">Idem, inline view made on the <a ref="https://www.360cities.net">360Cities site</a></div>    
    </div>
    </a>`

You see there are nested links and the third link gives problems: wrong next image.

I think I have seen a solution in the past with data attributes like fancybox-data-href or so, but I can't find it now.

Please give me a hint how to solve this.

**Comment by fancyapps** [comment]
Hi,

Simply avoid using anchor for outer element. You can use any HTML element as trigger element, for example:

```HTML
<div data-fancybox="S" href="https://source.unsplash.com/IvfoDk30JnI/1500x1000"  data-type="iframe"  id="0" data-caption= 'Idem, inline view made on the <a  href="https://www.360cities.net">360Cities site</a>'>  <!-- No problem -->

  <div class="box" style = "width:260px">
    <img src="https://source.unsplash.com/IvfoDk30JnI/260x110" width="260" height="110" alt="www.360cities.net-369" title=""  /><br>
    <div class="thumbText">Idem, inline view made on the <a ref="https://www.360cities.net">360Cities site</a></div>    <!-- Gives problem -->
  </div>

</div>
```

**Comment by acwolff** [comment]
Thanks for your help, it works perfect as you can see in [this album with 360° panoramas](https://andrewolff.jalbum.net/Pan360_FB/ ).
