### ISSUE TITLE
Wrong download button href

### ISSUE THREAD

**Issue by ipodlipnyak** [fancyapps/fancybox#2318]
Download button source wouldn't update on updateControls function call. Instead it would contain link with href="javascript:;"

**Comment by fancyapps** [comment]
Any details would be appertained. Download buttons works fine for me.

**Comment by ipodlipnyak** [comment]
Sorry, my bad. In my current project with jQuery 1.10.2 show() not returning prevObject. As result - chain brocken on end() before href attribute could be updated with actual source value
