### ISSUE TITLE
HTML modal content scrolls to the bottom

### ISSUE THREAD

**Issue by yahia-aboushadi** [fancyapps/fancybox#2320]
On mobile devices, it seems like when I have alot of html content in the modal, the modal automatically scrolls to the bottom. How can I have it so that it always remains at the very top of the modal so the beginning of the content shows? Here is an example: https://www.gia.edu/diamond-education Click on any link that says "See More"

**Comment by fancyapps** [comment]
Hi,

I could not find where to trigger fancybox, but my guess is that you have to simply disable auto-focus feature, because the script places focus on first focusable element and, if you have something (for example, a button) at the bottom of the content, browser will automatically scroll to bring it to the viewport. So, try setting `mobile: { autoFocus : false }`

**Comment by amichel86** [comment]
I have the same problem and disabling auto focus didn't solve the problem unfortunately. There's only text in the modal.

**Comment by fancyapps** [comment]
@amichel86 Since you did not provide a link to live demo, there is nothing we can do to help you.

**Comment by amichel86** [comment]
@fancyapps I realized that if I remove any <div> tags in the modal it works fine now. Would you happen to know why it shifts the modal to the bottom is a <div> tag is present?

**Comment by amichel86** [comment]
@fancyapps here's a live demo, just try on iOS - Click on "menu du jour" at the very top

https://theintegrateur.com/clients/pates/

**Comment by fancyapps** [comment]
I can explain why you are experiencing this issue, but I do not know how exactly did you manage to trigger it.

It is related to vertical centering. fancybox v3 uses inline-block trick for vertical centering and therefore uses blank pseudo element to allocate the space. This is very old and reliable trick and has good browser support, but there is only one minor flaw - if content width exceeds parent width, then browser can decide to place content below pseudo element. You can fix that easily by setting something like `.lb-menu { max-width: 90vw}`.

**Comment by amichel86** [comment]
@fancyapps thank you so much, the max-width fix solved the issue! :)
