### ISSUE TITLE
How can a set index of starting image 

### ISSUE THREAD

**Issue by VAMPIIRE** [fancyapps/fancybox#2321]
Hello,

Is it possible to open a gallery from n-th image? something like this:
```javascript
$().fancybox({
    selector: '#gallery a',
    startIndex: 3
});
```

Or I can do this only by using API.open from this issue: https://github.com/fancyapps/fancybox/issues/1734

**Comment by fancyapps** [comment]
Hi,

Well, typically you would want to start gallery from index of clicked link. If you, however, want to do things differently, you can create your own click event and then start fancybox using API:

`$.fancybox.open( items, opts, index );`

Quick tip, you can pass collection of jQuery objects, too, for example:

`$.fancybox.open( $('[data-fancybox="images"'), {}, 3);`
