### ISSUE TITLE
real puzzle: dynamically loaded html part loads images, but not captions

### ISSUE THREAD

**Issue by hanscees** [fancyapps/fancybox#2322]
Hi,

this is certainly not a bug but an issue I cannot explain: hopefully someone here can.

I have a page with images on which I use fancybox which works fine: here https://www.bomengids.nl/2019/barc/trees-of-barcelona-y.html

When you click on an image it shows image full-screen en notice how there are captions below. Perfect (please disregard styling as I have removed all).

Here is exactly the same page, 
https://www.bomengids.nl/2019/barc/trees-of-barcelona-x.html
except the images [actually bootstrap4 cards with a figure and lightbox-caption] are loaded dynamically with a little javascript bit. The line with data-include loads a second file.
The javascript bit is here: https://www.bomengids.nl/2019/fcss/csi.min.js

On this " dynamic" page fancybox works with the images, but the captions are not loaded. 

If I look into the loaded second page with f12 the lightbox captions seem to be loaded fine
So why doesn't find fancybox the captions? 

Anyway to fix this, or is this mission impossible?

**Comment by fancyapps** [comment]
Hi,

Simply call initializing method after you load caption elements on your page. Otherwise you have to use callbacks to set caption dynamically.
