### ISSUE TITLE
When scaling viewport, fancybox opens outside of screen

### ISSUE THREAD

**Issue by autimagic** [fancyapps/fancybox#2324]
We have a website where viewport scaling is enabled, as this is a feature we want.
Trick is that we are displaying a bunch of images in one page - and most users zooms a little by piching on a mobile device before they tap an image and Fancybox 3 opens.

Issue here is that Fancybox opens its overlay according to the full viewport (scale 1.0) - and now users is having a hard time seeing the image, as pinching in and out only affects the displayed image and not the viewport scale.

I'd like Fancybox to open within the visible area of the browser window - or to reset the viewport scale to 1.0 before opening.

How?

**Comment by fancyapps** [comment]
Hi,

The problem is that, when you scale webpage, you scale everything, including fancybox, because it is part of your page, just like any other html/css code. And there is really nothing you can do about that. Theoretically it could be possible to create a workaround by adjusting scale level, but we have to wait till visualViewport is supported by all major browsers, see https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API

**Comment by acwolff** [comment]
Did you try [this solution](https://stackoverflow.com/questions/22639296/force-mobile-browser-zoom-out-with-javascript/46137189#46137189%5D)?

**Comment by autimagic** [comment]
> The problem is that, when you scale webpage, you scale everything, including fancybox, because it is part of your page, just like any other html/css code. And there is really nothing you can do about that. Theoretically it could be possible to create a workaround by adjusting scale level, but we have to wait till visualViewport is supported by all major browsers, see https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API

I see. Thanks!

> Did you try [this solution](https://stackoverflow.com/questions/22639296/force-mobile-browser-zoom-out-with-javascript/46137189#46137189%5D)?

Yes, but I never got it to work (at all).
Kind of frustrating.

I'll give it a second chance in a few days and get back :-)

**Comment by fancyapps** [comment]
> I'll give it a second chance in a few days and get back :-)

You can forget about that, that worked in previous iOS versions, but Apple decided to ignore meta tags and to allow users to scale page.

**Comment by autimagic** [comment]
I just started rewriting the whole (huge) website to resposive ... Really should have done that ages ago - thanks for getting me started - og thank you for your assistance :-)
