### ISSUE TITLE
jQuery node data doesn't change when node data attribute is changed

### ISSUE THREAD

**Issue by brendon** [fancyapps/fancybox#2326]
**Describe the bug**
My fancybox images are added to the page using Vue.js. The data-caption is changed when the image is 'edited' in-page.

Because of the way fancybox loads a nodes data attributes using the `.data()` method of jQuery, it won't pick up changes to the caption in html.

**To Reproduce**
1. Create a simple image tag with data-fancybox set and data-caption set to something.
2. Click the image to see the fancybox preview. Close the preview.
3. Use property inspector to change the data-caption to something else.
4. Click the image and you'll notice the caption will be still the old caption.

**Expected behavior**
The captions (and potentially other data-attribute driven changes) should change based on the actual node attribute values.

**Potential solution**
Perhaps instead of bringing in all data attributes by calling `.data()`, you could read the necessary attributes directly using `attr('data-caption')`.

**Comment by fancyapps** [comment]
Hi,

Well, true, but, luckily, you can pass `caption` option as an method and customize to your needs, see https://fancyapps.com/fancybox/3/docs/#faq-2 for sample

**Comment by brendon** [comment]
Indeed, this was my workaround:

```coffee script
$(document).on 'click', '[data-fancybox-preview]', (event) ->
  event.preventDefault()
  $.fancybox.open
    src: $(this).attr('href')
    caption: $(this).attr('data-caption')
```

I just thought I'd raise it because it can be an unexpected side-effect of jQuery's `data()` method, and I suspect in this instance it's a side-effect rather than a feature of fancybox. More and more people will probably start to see this given the adoption of front-end frameworks and how they modify the dom in-place.

**Comment by fancyapps** [comment]
Anyway, we will forget about this when jQuery dependency will be dropped (in soon to be released v4).
