### ISSUE TITLE
Scrollbar width wrong after second popup call

### ISSUE THREAD

**Issue by thebazel** [fancyapps/fancybox#2327]
If we open new popup from previous fancybox popup then scrollbar width is set to 0 (because of body overflow is hidden).

1. Open fancybox popup
2. Click link inside current popup that calls new fancybox popup
3. You see that body's margin-right is 0.

Need to set right margin-right property according current body's scrollbar width.

Desktop:
 - Windows
 - Chrome
 - Version 76.0.3809.132

I made hotfix to solve this problem:

Replace on line 573:
`$("body").addClass("fancybox-active");`
with:
`$("body").addClass("fancybox-active").removeClass("compensate-for-scrollbar");`

**Comment by fancyapps** [comment]
Hi,

I could not reproduce this issue - https://jsfiddle.net/a3toynx8/

FYI, "issues" like this without a live demo will be closed without warning. It is very tiring and annoying to create test case for each "issue" to see that there is no issue at all.

**Comment by thebazel** [comment]
https://jsfiddle.net/5obuzte0/1/ - example when previous popup is closed while new is opening. You can see this issue.

**Comment by fancyapps** [comment]
Well, it sure works well for me, I do not see any issue, scrollbar hides and appears as expected. Maybe there is something different in your setup? (I have no idea what it could be...)
