### ISSUE TITLE
Can I add custom class to  the gallery thumbs?

### ISSUE THREAD

**Issue by VAMPIIRE** [fancyapps/fancybox#2328]
Sorry for such a stupid question. Can I add some custom class to the thumbs `<li>` elements? 

I need to add icons using CSS to the thumbnails.
Like if it is a video I need to add a small YouTube video icon if it is a 3D tour video I need to add another icon. It could visually help to separate elements in the gallery. I have a collection with a lot of images (around 40-50), 2-3 videos. So I want to help my users to separate where is images, where are videos, where are 3D tours and so on.

Thanks.

**Comment by acwolff** [comment]
In my [jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox ) the user can optionally add video icons as you can see in [my video demo album](https://andrewolff.jalbum.net/FancyBoxVideoTest/ ).

View the source code of that album to see how it has been implemented.

**Comment by fancyapps** [comment]
Hi,

You could use `onThumbsShow` callback to access thumbnail list, iterate through gallery items and update corresponding thumbnail, for example:

```
$('[data-fancybox="gallery"]').fancybox({
  onThumbsShow : function(instance) {
    var $thumbs = instance.Thumbs.$list.children();

    $.each( instance.group, function( index, item ) {
      if (item.contentType === 'image') {
        $thumbs.eq(index).addClass('thumb-image');
      } else if (item.contentType === 'video') {
        $thumbs.eq(index).addClass('thumb-video');
      }
    });
  }
});
```

Demo - https://jsfiddle.net/e62goc7L/

**Comment by acwolff** [comment]
I don't see this demo working. 
I think onThumbsShow is not executed, see this demo with extra alerts:  https://jsfiddle.net/acwolff/jz5dgpbv/9/

**Comment by fancyapps** [comment]
Do I really have to explain that that is not a complete example, you have to add icons by yourself, it just demonstrates how to "add custom class to the gallery thumbs" (the original question).

**Comment by acwolff** [comment]
Yes but in your demo you changed the  opacity and I see no effect.

**Comment by fancyapps** [comment]
Changing opacity is the effect. And, please, stop wasting my time.

**Comment by VAMPIIRE** [comment]
@fancyapps  and @acwolff  Thanks for your suggestions! 

@fancyapps I've applied your solution and all working good :) Thanks.
