### ISSUE TITLE
Is it allowed to download fancybox core code to my own server?

### ISSUE THREAD

**Issue by whatiswrongwiththis** [fancyapps/fancybox#2329]
Hi,
I would like to purchase Fancybox for my domain. In the download package, the core code (CSS and JS) is not included. Since I would like to use Fancybox within Europe, I need to store all the code on my own server and therefore avoid the link to the CDN server to comply with the GDPR regulations.
Is it allowed to download the core code from the CDN and store it on my own server?
Regards
Jay

**Comment by fancyapps** [comment]
Hi,

Yes, you can download and use all the code, there are no limitations. You can always access the latest code here - https://github.com/fancyapps/fancybox/releases
