### ISSUE TITLE
Please add information to the site about the attribute "data-thumb"

### ISSUE THREAD

**Issue by Indaled** [fancyapps/fancybox#2330]
Hi,
Please add information to the site about the attribute "data-thumb"

I found out about it from https://github.com/fancyapps/fancybox/issues/1903#issuecomment-378659975

although in the documentation I did not find mention of this

**Comment by fancyapps** [comment]
Hi,

Well, you can pass (almost) any option using HTML5 data-* attributes, as mentioned in docs:

> It is also possible to quickly set any option using parameterized name of the selected option, for example, animationEffect would be data-animation-effect

See https://fancyapps.com/fancybox/3/docs/#options
