### ISSUE TITLE
Full Screen Cuts off in Safari

### ISSUE THREAD

**Issue by robertallenbaker** [fancyapps/fancybox#2333]
I'm using a Fancybox popup to display staff members here:

http://crcmi.staging.wpengine.com/crc-staff/
(Click the photos)

It looks good everywhere except in Safari, both on the iPad and iPhone.  There's this white background or something that cuts off the right side of the popup.  I've looked through CSS and I can't seem to find where this is.  Can someone help?

**Comment by fancyapps** [comment]
Hi,

Something is adding `position:fixed;` CSS rule to `body` tag and that causes this issue. So, either get rid of that or add additional `left:0;right:0;`.
