### ISSUE TITLE
How to disable more videos strip from youtube?

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2334]
While using iframe and rel=0 ... I still get the more videos strip from YouTube ... Is there a way to hide it completely?

Regards

**Comment by fancyapps** [comment]
Hi,

Could you show some demo? I tried few videos and "more videos strip" did not show.

**Comment by fancyapps** [comment]
Anyway, there is really no actual control over youtube videos and google can change anything at any time, therefore you should be ready to any suprises.
