### ISSUE TITLE
Scaling pop-up images like 'object-fit: cover'

### ISSUE THREAD

**Issue by phibershinigami** [fancyapps/fancybox#2336]
The size of the photo is automatically reduced if it is larger than the pop-up screen. What I want to do is reduce the photo to 'contain' rather than 'cover'. Nevertheless thanks so much for this legend api.
My img(200x300) : https://ibb.co/HF04zrM
Fancybox(1500x1200) : https://ibb.co/YtQSQCY

Styles about 'fancybox-inner'
`
.fancybox-stage {
  width: 70%;
  background: #fff;
}
`

`.fancybox-inner {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  width: calc(100% - 40px);
  height: calc(100% - 40px);
  max-width: 780px;
  max-height: 780px;
  opacity: 0;
  -webkit-transition: opacity 1s;
  transition: opacity 1s;
}`

JS about 'fancybox'
`animationEffect: "fade",
            animationDuration: 300,
            arrows: true,
            margin: 0,
            gutter: 0,
            hideScrollbar: true,
            touch: {
                vertical: false
            },
            baseTpl: '<div class="fancybox-container" role="dialog" tabindex="-1">' +
                '<div class="fancybox-bg"></div>' +
                '<div class="fancybox-inner">' +
                '<div class="fancybox-stage"></div>' +
                '<div class="fancybox-form-wrap">' +
                '<button data-fancybox-close class="fancybox-button fancybox-button--close" title="{{CLOSE}}">' +
                '<svg viewBox="0 0 40 40">' +
                '<path d="M10,10 L30,30 M30,10 L10,30" />' +
                '</svg>' +
                '</button></div>' +
                '</div>' +
                '</div>',`

**Comment by fancyapps** [comment]
Hi,

Thanks for the feedback, but this feature has already been requested multiple times and will be implemented in the next major release.
