### ISSUE TITLE
Download button - directly download

### ISSUE THREAD

**Issue by phibershinigami** [fancyapps/fancybox#2337]
Clicking on the download button opens the photo in the new tab.
How do I get a direct download when I click the button?

**Comment by fancyapps** [comment]
Hi,

Download button is just a link having `download` attribute. See docs - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download - 

> This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file.

So, the rest is up to you and the browser. If you wish to force to download dialog to appear, then you might have to create download page (using PHP, for example) that will send appropriate HTTP headers.
