### ISSUE TITLE
Gallery without adding images to the page

### ISSUE THREAD

**Issue by LiamDawe** [fancyapps/fancybox#2338]
Something I am confused on here, is how to have a gallery of images without having all the images on the page? The documentation here https://fancyapps.com/fancybox/3/docs/#usage only shows how to use a Gallery with images on the page.

**Comment by fancyapps** [comment]
Hi,

If you have none images on the page, then you can simply use API https://fancyapps.com/fancybox/3/docs/#api to start gallery programmatically. 

If you wish to show one visible image, then you can simply hide others using CSS or you can create empty links, example (see this demo https://codepen.io/fancyapps/pen/EeqJPG?editors=1000): 

```
<a href="https://source.unsplash.com/Ai2TRdvI6gM/1500x1000" data-fancybox="images-preview" 
     data-width="1500" data-height="1000"
     data-thumb="https://source.unsplash.com/Ai2TRdvI6gM/240x160"></a>
```
