### ISSUE TITLE
iOS13 creates iframe scrolling and background lock issues

### ISSUE THREAD

**Issue by beanmatt** [fancyapps/fancybox#2340]
Anyone having trouble once updating to iOS 13?  I am on the latest version of fancy box, everything was working great, then I updated to iOS 13 and a few things are broken:

- scrolling an iframe in fancybox gets stuck towards the bottom of the page where the iOS Safari chrome is.  You have to give it a little extra push to see the bottom of the page.
- once at the bottom of the iframe, if you keep scrolling the background scrolls up, whereas before it was locked.

Works as before on desktop browser.  I know iOS 13 removes the need for webkit-overflow-scrolling:touch, but not sure that's the cause here.

First scroll to bottom of iframe:
![IMG_8820](https://user-images.githubusercontent.com/19357372/65546000-341d0800-dedc-11e9-8e22-e99882ddcc72.PNG)

You have to scroll  bit more to see bottom of iframe contents:
![IMG_8821](https://user-images.githubusercontent.com/19357372/65546009-3aab7f80-dedc-11e9-8fe2-7636f41f8466.PNG)

Further scrolling locks the fancybox overlay and scrolls the background:
![IMG_8822](https://user-images.githubusercontent.com/19357372/65546030-4139f700-dedc-11e9-914d-5c3ecda40f83.PNG)

**Comment by fancyapps** [comment]
Hi,

Well, while my iPhone is updating to iOS 13.1, I can only comment that iOS and scrolling has been problematic for years. I would be happy if you (and others) would find time and focus on real issues, for example, this one https://bugs.webkit.org/show_bug.cgi?id=153852 (it currently has status RESOLVED FIXED, but see last comments, it is not really fixed).

**Comment by beanmatt** [comment]
Was that necessary?  I’ve been using fancybox for nearly a decade, and this is the first time I’ve had a problem like this I couldn’t resolve.  So I came here thinking perhaps others might have the same issue.  If you have nothing to contribute...then don’t.

**Comment by fancyapps** [comment]
1) To me, it seems that there are no changes in iOS 13, scrolling works as crappy as before, e.g., it works fine until body element starts scrolling, which is the real cause of this issue. And there is no good solution for that. You could, for example, set `position:fixed` to `body` element and that would fix all scrolling issues, but that would create others.

2) My point in the previous comment was that if we would more actively push developers of browsers to fix their issues, then they might start doing something about them (instead of waiting for years) and our lives would be much easier (try, for example, googling `ios scrolling issues`, it returns whooping 13 100 000 results). If that somehow offended you, then my apologies.

**Comment by fancyapps** [comment]
And I forgot to mention that this issue might disappear once iOS Safari supports CSS `overscroll-behavior: contain;`, but be have to wait for that - https://bugs.webkit.org/show_bug.cgi?id=176454

**Comment by acwolff** [comment]
@beanmatt I use too the latest fancyBox library and iOS 13, but I don't see this problem in [this iframe test page](https://andrewolff.jalbum.net/Vecht_SaharaN_FB/#S-2) do you see that effect in my test page?

@fancyapps I think scrolling has been improved in iOS 13:
1. The yellow box demo in  https://bugs.webkit.org/show_bug.cgi?id=153852 works now fine I think.
2. [This web-page](https://www.andrewolff.nl/bs-almelo/woensdag-a/competitieP.htm) did not scroll correctly under iOS 12, but it is OK under iOS 13.

**Comment by beanmatt** [comment]
Thanks for your insight, @fancyapps.  I've used the position:fixed hack many times.  My point is that everything was working fine, then when updating to iOS 13 it broke...indicating the issue probably lies with a change in the new OS, and wondered if anyone might be having the same issues.

@acwolff That example link works great.  I have my iframe expanded so it covers the entire screen, no border.  I think the issue might have to do with the iOS "toolbar" at the bottom.  It comes and goes depending on where/how you scroll, which I think causing the positioning to screw up.  Though, as I said, it did work on iOS 12.  Anywho, guess it's just an issue with me and my own personal setup.

Thanks for the feedback!
