### ISSUE TITLE
Change part of the URL to download a HiRes video

### ISSUE THREAD

**Issue by misurex** [fancyapps/fancybox#2341]
I don't know if it's a feature, but I don't know where to put my question. 

I had a question about how to display and use a download button for a video gallery, the @fancyapps's answer was working for me. But I also need another thing, to change the URL of the current video (low res), for one in hi res. Actually, I need to remove one node in the url. I tried (to remove '/video_medium' from the url) this code, but it isn't working.

beforeShow : function(instance, slide) {
**var src = slide.src.replace('/video_medium', '');**
instance.$refs.container.find('.fancybox-button--download').attr('href', slide.src);
}

Please advise. Thank you.

**Comment by fancyapps** [comment]
Hi,

Your code snippet looks fine to me, it should work. Since you did not provide a link to live page/demo, I am not able to help you further.

**Comment by misurex** [comment]
Hi Jānis,
It's an Oracle Apex application, http://basiq.dyndns.org/apex/f?p=110:1
The app opens with 2019 already selected (the other years are not yet
treated), so if you choose Filme from one of the three links, you will see
their thumbnails pointing to the medium films sizes. By hovering the mouse
over the download button, we can see that the url is the same as for those
displayed (10 times smaller than the originals).

The js code that I use, one for the Photos (which is working), and one for
the videos is:

//For photos
$( '[data-fancybox="images"]' ).fancybox({
   caption : function( instance, item ) {
       var caption = $(this).data('caption') || '';
       return ( caption.length ? caption + '<br />' : '' ) + 'Poza <span
data-fancybox-index></span> din <span data-fancybox-count></span>';
    },
    buttons : [
    'download',
    'close'
  ],
  afterShow : function(instance, current) {
       var src =  current.src.replace('/medium', '');

       console.info('current.src: ' + current.src + '; download src: ' +
src);

       $("[data-fancybox-download]").attr('href', src);
  }
});




//For films
$.fancybox.defaults.btnTpl.download2 =
$.fancybox.defaults.btnTpl.download.replace('data-fancybox-download', '');

$( '[data-fancybox="video"]' ).fancybox({
   caption : function( instance, item ) {
       var caption = $(this).data('caption') || '';
       return ( caption.length ? caption + '<br />' : '' ) + 'Film <span
data-fancybox-index></span> din <span data-fancybox-count></span>';
    },
    buttons : [
    'download2',
    'close'
  ],

  beforeShow : function(instance, slide) {
       var src =  slide.src.replace('/video_medium', '');

 instance.$refs.container.find('.fancybox-button--download').attr('href',
slide.src);
  }

});


ps: I already tried afterShow, same result.
Thank you,

Mihai Ioachim
misurex@gmail.com <mihai.ioachim@sia-solutions.ca>

**Comment by fancyapps** [comment]
Your 2nd snippet would not work, because you have created `src` variable, but your have never used it, you have used `slide.src` instead.

**Comment by misurex** [comment]
Ouf, I was blind apparently. Thank you so much. Unfortunately it's not
over. When I click on download, it replace the low res video by the hi res
one ... instead of popping up a window.
Please advise. Thank you Jānis.



Mihai Ioachim
misurex@gmail.com <mihai.ioachim@sia-solutions.ca>

**Comment by fancyapps** [comment]
If by "popping up a window" you meant download window, then you have to create separate download page (using PHP or any other server side code) that sends appropriate HTTP headers. Download link just uses HTML5 download attribute - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download
