### ISSUE TITLE
IE9: "Expected identifier" at "class" property

### ISSUE THREAD

**Issue by ansgarbecker** [fancyapps/fancybox#2342]
**Describe the bug**
MS IE9 on Win7 throws this error and blocks further execution of JS on the whole page.

**To Reproduce**
1. Use Fancybox on some page
2. Navigate with IE9 to it
3. See the error in the developer tools: "Expected identifier, string or number"

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser IE
 - Version 9

Bug is due to "class" being a reserved word probably. When wrapping it in (double)quotes, this is fixed.

There are 2 occurrences of unquoted "class" properties in media.js:
* https://github.com/fancyapps/fancybox/blob/eea1345256ded510ed9fae1e415aec2a7bb9620d/src/js/media.js#L203
* https://github.com/fancyapps/fancybox/blob/eea1345256ded510ed9fae1e415aec2a7bb9620d/src/js/media.js#L210

**Comment by fancyapps** [comment]
Hi,

Sorry, IE 9 is not supported. 

btw, I feel sorry for you if you have to support such old and buggy piece of software.

**Comment by ansgarbecker** [comment]
Sad to hear that. Especially as I see the code is running fine with the additional quotes, so it would be easy to fix. However, thanks for your effort!

**Comment by fancyapps** [comment]
Sad yo hear that someone misses IE9 support, I would love to drop IE11 support, because that would make everything much, much easier.
