### ISSUE TITLE
Swipe on Youtube videos (mobile)

### ISSUE THREAD

**Issue by miwonster** [fancyapps/fancybox#2343]
Hi mates,
There is a gallery mixed up from pictures and Youtube videos. While watching on the gallery on mobile the swipe doesn't work on Youtube window. It works only above and below the entire video window, but doesn't work on itself. Users think if the swipe doesn't work it means the end of the gallery and stop watching the remaining pictures.
Plase help to solve this problem.

```
<li>
    <a href="IMAGE_URL_1" data-fancybox="gallery"><img src="MINI_IMAGE_URL_1" /></a>
</li>
<li>
    <a href="IMAGE_URL_2" data-fancybox="gallery"><img src="MINI_IMAGE_URL_2" /></a>
</li>
<li>
    <a href="https://www.youtube.com/watch?v=YOUTUBE_ID" data-fancybox="gallery"><img src="https://i1.ytimg.com/vi/YOUTUBE_ID/0.jpg" /></a>
</li>
<li>
    <a href="IMAGE_URL_3" data-fancybox="gallery"><img src="MINI_IMAGE_URL_3" /></a>
</li>
<li>
    <a href="IMAGE_URL_4" data-fancybox="gallery"><img src="MINI_IMAGE_URL_4" /></a>
</li>
```

**Comment by fancyapps** [comment]
Hi,

Youtube, Vimeo videos are inside iframe and it is not possible to bind mouse/touch events into iframe.
