### ISSUE TITLE
Multiple modals opens after closing them

### ISSUE THREAD

**Issue by morten409** [fancyapps/fancybox#2344]
Hello and thank you for a wonderful proejct!

I've ran into a smaller problem. I use the following to open **file.php**

`$(document).on('click','.OpenModal',function(e){`
`    e.preventDefault();`
`        $.fancybox.open({`
`            src  : 'popup_exit_editor.php',`
`            type : 'ajax'`
`    });`
`});`

This works fine. The problem accurs when I have to shut it down again, again and again. The thing is that the modal can be opened multiple times on a page. I close the modal with the following:

`		$(document).on('click','.CloseModal',function(e){`
`			$.fancybox.close();`
`		});`

I have also tried `$.fancybox.destroy();`

Whenever I click on the close button and open the modal again - 2 modals will accur. If I open and close the modal 8 times - 8 modals will accur when I click the "open button" again.

I have tried both `$.fancybox.close();` and `$.fancybox.destroy();` in different ways.

Is there a way to completely reset all the current modals?

Thank you.

**Comment by fancyapps** [comment]
Hi,

Could you, please, create codepen/jsfiddle demo that would demonstrate your issue? You could close all modals using `$.fancybox.close(true);`, but I have no idea how you managed to open new one on closing. Maybe you opening selector matches close button?

**Comment by morten409** [comment]
> Hi,
> 
> Could you, please, create codepen/jsfiddle demo that would demonstrate your issue? You could close all modals using `$.fancybox.close(true);`, but I have no idea how you managed to open multiple modals, I've never encountered such a problem.

Thank you for your reply,

I have made a testpage instead if that's okay. I couldn't make the error accur on jsfiddle/codepen.

If you go to: https://gon.dk/test/ you will see what I'm talking about. Thank you very much for your time :)

**Comment by fancyapps** [comment]
But you are attaching the same click event `$(document).on('click','.regret',function(e){...` each time you load your ajax page. Either unbind before binding or reorganize your code so it executes only once.

**Comment by morten409** [comment]
I'm so very sorry. I must have stared blind on the issue. I do apologize. Thank you anyway!
