### ISSUE TITLE
HTTPS protocol missing from the Jquery link.

### ISSUE THREAD

**Issue by tomkf** [fancyapps/fancybox#2345]
In the example provided by the landing page (https://fancyapps.com/fancybox/3/). The https protocol was forgotten for the jQuery script, causing it to break. 

Please provide it as <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> in the example.

**Comment by fancyapps** [comment]
Hi,

Well, `//` actually means to use current protocol:

> If the browser is viewing that current page in through HTTPS, then it’ll request that asset with the HTTPS protocol, otherwise it’ll typically* request it with HTTP. This prevents that awful “This Page Contains Both Secure and Non-Secure Items” error message in IE, keeping all your asset requests within the same protocol.

But I changed that anyway, thanks.
