### ISSUE TITLE
How to hide / show the toolbar with Javascript

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2348]
You are correct @fancyapps I am not viewing photos displayed in fancyBox daily on an iPhone.
So if the fancyBox tool-bar can't be used in landscape mode on an iPhone, it seems logical to hide that tool-bar on an iPhone in landscape mode and show the tool-bar only in portrait mode.

What is the best code to hide or show the tool-bar in Javascript code?.

Edit:

Strange that I did not get an answer, but I found a solution:
If an iPhone is rotated I call this function:

    `function doOnOrientationChange() {
        switch (window.orientation) {
            case -90:
            case 90:
                Landscape = true;
                if (iPhone) $('.fancybox-toolbar').css('display', 'none');
                break;
            default:
                Landscape = false;
                if (iPhone) $('.fancybox-toolbar').css('display', 'block');
                break;
        }
    }`

To see it working open [this page](https://andrewolff.jalbum.net/FB__JustifiedGallery_white/#S-1 ) with an iPhone in portrait mode and rotate it to landscape mode.

**Comment by fancyapps** [comment]
Hi,

Well, there are no JS methods available just for hiding/showing the toolbar, but there are `hideControls/showControls/toggleControls` methods that would change visibility for all controls including caption and you can use them like this:

`$.fancybox.getInstance().toggleControls()`

**Comment by acwolff** [comment]
OK @fancyapps thanks for your explanation and your awfully gallery!
