### ISSUE TITLE
Problem in loading tif files

### ISSUE THREAD

**Issue by jalilzade** [fancyapps/fancybox#2349]
**Describe the bug**
Getting "The requested content cannot be loaded.  Please try again later." error when trying to show tif files inside fancybox. I am getting same error for 10MB or 1MB file.

**To Reproduce**
See [here](https://codepen.io/Jalilzade/pen/VwwYEjV)

**Expected behavior**
show tif file inside fancybox.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [latest]

**Comment by fancyapps** [comment]
Hi,

These are not valid image links. Try, for example, something like:

`<img src="http://test.saidnursiarsivi.org/files/original/a8f9c9c4420537c7df7c26a29f95bc994e24c53d.tif" />`

It does not show an image.
