### ISSUE TITLE
Consecutively triggered modals has been problem

### ISSUE THREAD

**Issue by FKonyali** [fancyapps/fancybox#2350]
This code
`$.fancybox.open('<div id="modal-1"><h1>#1 Test</h1><p>1</p></div>');`
`$.fancybox.open('<div id="modal-2"><h1>#1 Test2</h1><p>1</p></div>');`
`$.fancybox.open('<div id="modal-3"><h1>#1 Test3</h1><p>1</p></div>');`

In this way, 3 modal opens at the beginning. Then I want to close the first modal. 

I use `$.fancybox.getInstance().close();` but closed last modal. I try `$('#modal-1').parents('.fancybox-container').find('[data-fancybox-close]').trigger('click');` but never triggered.   Triggers when I use 'click trigger' for the last slider. But click is not triggered in one and the second modal. So what should I do to turn off the first and second modal?

**Comment by fancyapps** [comment]
Hi,

It is as simple as 

```
let a = $.fancybox.open('<div id="modal-1"><h1>#1 Test</h1><p>1</p></div>');
let b = $.fancybox.open('<div id="modal-2"><h1>#1 Test2</h1><p>1</p></div>');
let c = $.fancybox.open('<div id="modal-3"><h1>#1 Test3</h1><p>1</p></div>');
```

and then

`a.close()`

If you, however, do not have reference to the first instance, it can be also accessed like this:

`$(`.fancybox-container`).eq(0).data(`FancyBox`).close()`
