### ISSUE TITLE
WEBP format fallback

### ISSUE THREAD

**Issue by PR0SAT** [fancyapps/fancybox#2351]
I needed webp to jpg format img fallback.
Could be implemented like this:

`    setBigImage: function (slide) {
      var self = this,
        img = document.createElement("img"),
        $img = $(img);

      slide.$image = $img
        .one("error", function () {
		  // webp image fallback for IE etc.
		  // ======================
		  index = this.src.lastIndexOf('.');
		  ext = this.src.substring(index+1);
		  if (ext === 'webp') {
			  this.src = this.src.replace('.webp','.jpg');
			  slide.src = this.src;
			  slide.thumb = slide.thumb.replace('.webp','.jpg');
			  self.setBigImage(slide);
		  } else
		  // ======================
			self.setError(slide);
        })`

this snippet concerns fancyBox v3.5.7
and is completing the function of jQuery webp fallback:
`$('img').on('error', function() { //dynamic rendering
	if (!this.complete || typeof this.naturalWidth == "undefined" || this.naturalWidth == 0) {
	  index = this.src.lastIndexOf('.');
	  ext = this.src.substring(index+1);
	  if (ext === 'webp')
		  this.src = this.src.replace('.webp','.jpg');
	}

});`

**Comment by fancyapps** [comment]
Hi,

You could just use `beforeLoad` callback to customize image source, like so:

```JS
beforeLoad : function(instance, current) {
    current.src = `https://loremly.com/640x480`;
  }
```

In  your place,  I would check for WebP support on page load (you can find example here https://stackoverflow.com/questions/5573096/detecting-webp-support) and then just replace image source accordingly.
