### ISSUE TITLE
How to prevent that the iOS 13 address tool-bar is shown on an iPhone?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2352]
I downloaded basic pen https://codepen.io/fancyapps/pen/wEVOPa and saved that on my server, see [here](https://www.andrewolff.nl/b/ ).

If I open that album on an iPhone in portrait mode with iOS 13 and next open the light-box and rotate the iPhone in landscape mode, I see always the iOS address tool-bar:
![WithAddressBar](https://user-images.githubusercontent.com/8150784/66712654-0d961280-eda0-11e9-9975-06fac2b62993.PNG)

If I do the same with the demo album on the [fancyapps.com](https://www.fancyapps.com/fancybox/3/) page I see never an address tool-bar:

![WithoutAddressBar](https://user-images.githubusercontent.com/8150784/66712662-269ec380-eda0-11e9-83da-7cc15981ba6f.PNG)

What is the essential difference?
What is the trick to prevent that the  the iOS 13 address tool-bar on an iPhone is shown?
I did not see this difference with older iOS versions.

**Comment by fancyapps** [comment]
Hi,

Try adding meta tags, for example, `<meta name='viewport' content='initial-scale=1, viewport-fit=cover'>`. I have no other explanation as there are no tricks and I do not think there is possibility to force top bar to disappear.

**Comment by acwolff** [comment]
Thanks for your fast response.

I copied meta tags from your demo page:
 &lt;meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover'&gt; but that does not solve the problem.

Is it somewhere possible to download all code of your demo album so that I can test it as a stand alone album on my server?

**Comment by acwolff** [comment]
Very weird, but found this solution:

    $(document).ready(function() {
        window.addEventListener('orientationchange', doOnOrientationChange);
        doOnOrientationChange(); // Initial execution if needed
    });

    function doOnOrientationChange() {
        switch (window.orientation) {
            case -90:
            case 90:
                window.scrollTo(0, 100); // Hide the address bar in lanndscape mode!
               break;
            default:
                // portrait
                break;
        }
    }`

You can test it [here](https://www.andrewolff.nl/bm/ ).
