### ISSUE TITLE
Links | Open in new tab

### ISSUE THREAD

**Issue by phibershinigami** [fancyapps/fancybox#2355]
Clicking on the link opens the fancybox, that's correct.
But when I want to open in the new tab, the link is opened directly.

What I want is like this:

`
<a href ="image.jpg" fake_href ="medias/image_id" data-fancybox="image">
`

If I want to open it in the new tab, it should direct me to another page, not the photo. Is something like this possible?

**Comment by fancyapps** [comment]
Hi,

Yes, you can have different `href` value, simply use `data-src` attribute to set source for fancybox, example:

`<a href="some_page.html" data-fancybox="image" data-src="image.jpg">...</a>`
