### ISSUE TITLE
settings not working

### ISSUE THREAD

**Issue by smallshaw** [fancyapps/fancybox#2356]
Please forgive me if I'm making some kind of noobie mistake, but when I make settings such as the following, they don't seem to show up. Otherwise the gallery works fine.

<script type="text/javascript">
$('[data-fancybox="gallery"]').fancybox({
	thumbs: {
    autoStart: true
  	},
  	arrows: false
});
</script>

	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="../fancybox/dist/jquery.fancybox.min.js"></script>

</body>
</html>

**Comment by fancyapps** [comment]
Hi,

Looks like you have placed your JS code before HTML and therefore your config does not apply. You simply have to either move your JS code to the end of the page (right before </body> tag) or wrap inside `$( document ).ready(function() { });`

**Comment by smallshaw** [comment]
No, I have it at the end of the page, just before the </body> tag as you suggest.

**Comment by fancyapps** [comment]
Well, since you did not provide a link to your page, I give up, there is nothing I can do to help you.

**Comment by smallshaw** [comment]
Oh sorry:

http://saltspringarchives.com/fancybox-aitkens/fancy-gallery8.html

**Comment by fancyapps** [comment]
I have never seen such funny mistake 😄 You have placed your JS code BEFORE jQuery AND fancybox.js file.

**Comment by smallshaw** [comment]
Thanks for your help.
