### ISSUE TITLE
Fancybox trigger image shows up in thumbs

### ISSUE THREAD

**Issue by Cozmoz** [fancyapps/fancybox#2357]
Hi,

I am using Fancybox 3.5.7 and I am having an issue where I am using `data-fancybox-trigger` to launch a gallery and the thumbnail related to the original link is showing up in the gallery thumbs.

Please find a JS Fiddle reproducing the problem below:

https://jsfiddle.net/Cozmoz/75ekv2rf/

**Comment by alixbergeret** [comment]
I guess there's an assumption that if an image triggers a gallery then it's part of the gallery?
For my triggers I use buttons or links, that works fine... or if you really need an image as a trigger, you could use the CSS background property instead?

**Comment by Cozmoz** [comment]
I guess but that would just be covering up the image rather than solving it. Also I would like the container to resize as an image.

**Comment by fancyapps** [comment]
Hi,

Well, it works like this intentionally, the idea is that preview image acts as thumbnail image for the first gallery item, like here - https://codepen.io/fancyapps/pen/VGoRqO?editors=1010

Here is one possible solution for you - https://jsfiddle.net/6xhernuo/

**Comment by Cozmoz** [comment]
Thanks so much for the fix!

**Comment by Cozmoz** [comment]
Hi,

I have implemented this in my real world scenario but the issue is still occurring?

https://marina.greensquare.dev/history/

**Comment by fancyapps** [comment]
Looks like you did not notice that in my demo, I replaced `data-fancybox-trigger` attribute with custom attribute `data-start-fancybox` (you can choose your own name) and then created custom click event (for elements having that attribute) that triggers click event on the first item of the actual gallery.

**Comment by Cozmoz** [comment]
Sorry about that.
