### ISSUE TITLE
How to use the whole vertical view-port height?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2358]
Is it possible to display the image if it is loaded in the light-box in such a way that the whole vertical view-port is used if the image height is >= view-port=height? See [here](https://andrewolff.jalbum.net/Vecht_Stegeren_Justified_Galery/#17) for an example (works only on a PC or iPad).

What code should I use to get that implemented?

**Comment by fancyapps** [comment]
Hi,

There is currency no option for that, but there is already a feature request for that and that will be implemented in the next major version.

**Comment by acwolff** [comment]
Great! Thanks!

If you need a beta tester for your new version, let me know!
