### ISSUE TITLE
show data-caption inside the modal box

### ISSUE THREAD

**Issue by alecos71** [fancyapps/fancybox#2361]
`<a href="/gfx/Avatar_b.png" data-fancybox data-caption="Made with <a href='https://play.google.com/store/apps/details?id=com.mirrorai.app&amp;hl=en' class='link-caption' target='_blank'>Mirror Emoji Keyboard &amp; Sticker Maker</a>"><img src="/gfx/Avatar.png" class="avatar" alt="Avatar"></a>`

How can I get caption like this?

http://fancybox.net/

![FancyBox](https://user-images.githubusercontent.com/9997666/67146825-27978f80-f28f-11e9-975c-7740c36d066e.png)

Actually FancyBox shows the caption outside the image box, how can solve this?

And how can I stylish the url of the caption and the text of the caption using data-caption?

Thanks.

Alessandro

**Comment by fancyapps** [comment]
Hi,

fancybox v1 & v2 are not supported and it is recommended to upgrade to the latest.

**Comment by alecos71** [comment]
I'm using latest!

`<a href="/gfx/Avatar_b.png" data-fancybox data-caption="Made with <a style='color: #FF8C00' href='https://play.google.com/store/apps/details?id=com.mirrorai.app&amp;hl=en' target='_blank'>Mirror Emoji Keyboard &amp; Sticker Maker</a>"><img src="/gfx/Avatar.png" class="avatar" alt="Avatar"></a>`

This code is ok?
