### ISSUE TITLE
issues with fancybox on iOS

### ISSUE THREAD

**Issue by shortmort37** [fancyapps/fancybox#2362]
**Describe the bug**
I have a phpBB board, where I have attachments of these media types:  jpg, gif, pdf, mp4, mp3.  I can add them to a FancyBox gallery, and the behavior is as hoped on a Windows PC, any browser.  But on iOS, the behavior of pdf and mp3 attachments is problematic, using both Chrome and Safari.  Without FancyBox, the rendering of attachments is the same and correct, whether Windows or iOS.

**To Reproduce**
1. On iOS, go to http://59plymouth.net/59test/viewtopic.php?f=20&t=3353
2. The attachments are labeled.  Click on the pdf and the audio.
3. The pdf is a two page document, and is scrollable under Windows.  The first page only is rendered on iOS, with substantial whitespace on the right and bottom.  I am using data-type = "iframe" - changing the type to "pdf" breaks the rendering on both Windows and iOS.
4. As suggested, I am able to render the HTML5 audio player in Windows for the mp3 by assigning data-type="video".  This works under Windows; on iOS, however, the play button does not start the audio.

**Expected behavior**
I am expecting the behavior to be the same on iOS as it is in Windows.

**Screenshots**
I am attaching a screenshot of what I see for the pdf rendering on my iPad.  The rendering is the same on the iPhone.

**Desktop (please complete the following information):**
 - OS: iOS on iPad
 - Browser: Either Chrome or Safari
 - Version: V9.3.5

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS
 - Browser: Either Chrome or Safari
 - Version V13.1.2
![IMG_0202](https://user-images.githubusercontent.com/10282646/67147548-e8a01480-f263-11e9-99db-1de11e70af55.PNG)

**Comment by fancyapps** [comment]
Hi,

You expect too much from this script. The script just creates markup, the rest is up to the browser. For example, for pdf files you have to use something like https://mozilla.github.io/pdf.js/ to parse pdf file into code that browser understands (some have built-in functionality, some not).
