### ISSUE TITLE
horrible and unusable on mobile device

### ISSUE THREAD

**Issue by alecos71** [fancyapps/fancybox#2363]
On mobile device the image is too bigger and go out the visible area of the device when used `<meta name="viewport" content="width=device-width, initial-scale=1">`

1. Open https://www.alecos.it/index_eng.php

2. Click on the picture on left sidebar.

3. You can see that the image is cut and it doesn't fit on the display.

4. Tested on firefox mobile and chrome mobile. On desktop fancy box works fine.

Mobile device Samsung Galaxy S7
Oreo 8
Mozilla firefox 69
Chrome 70
Attached screenshots.

![Screenshot_20191019-213052_Firefox](https://user-images.githubusercontent.com/9997666/67150460-faaba280-f2b7-11e9-8c13-1c335030f92f.jpg)

![Screenshot_20191019-213105_Firefox](https://user-images.githubusercontent.com/9997666/67150568-69d5c680-f2b9-11e9-8b74-2301f60e0ba4.jpg)

**Comment by alecos71** [comment]
On the small images the bigger image is not displayed because the position is out the visible port view

**Comment by alecos71** [comment]
My layout is 1200px.... the qr code on the left sidebar of my website is not displayed because fancy box calculate the center of 1200px and then print out the image on that center. The smartphone is not capable to read the full site in 1200px so shows a minus part of it.

**Comment by fancyapps** [comment]
Works perfectly fine on your non-responsive website.
