### ISSUE TITLE
Destroy FancyBox on Mobile device

### ISSUE THREAD

**Issue by alecos71** [fancyapps/fancybox#2364]
```
$(document).ready(function() {
$('[data-fancybox]').fancybox({
    if ($.fancybox.isMobile) {
      $.fancybox.destroy();
    }
  });
});
```

I'll appreciate any help!

Is not working... why?

**Comment by fancyapps** [comment]
Hi,

First,  let me break down your code - 

```JS
$(document).ready(function() {          // When document is ready..
  $('[data-fancybox]').fancybox({       // .. attach click event to selected items, and,
    if ($.fancybox.isMobile) {          // when user clicks, check if this is mobile device
      $.fancybox.destroy();             // if so, destroy fancybox
    }
  });
});
```
Secondly, what destroy method does - it will just close any open instance and will unbind default click handlers (created here - https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L3381). Fancybox will still work anyway. So, if you have created custom click handlers or you have somewhere used API to start fancybox, it will work anyway. 

So, you just have to use it the other way, like 

```JS
if ($.fancybox.isMobile) {
  $.fancybox.destroy();  
} else {
    $('something').fancybox({ /* ... */ });
}
```

**Comment by alecos71** [comment]
if ($.fancybox.isMobile) {
  $.fancybox.destroy();  
}

Will destroy fancybox on mobile device or not? Or fancybox will continue working on mobile device?
