### ISSUE TITLE
This code is Ok. Im' using latest FancyBox3

### ISSUE THREAD

**Issue by alecos71** [fancyapps/fancybox#2365]
I'm using latest FancyBox 3! (https://github.com/fancyapps/fancybox/archive/master.zip)

`<a href="/gfx/Avatar_b.png" data-fancybox data-caption="Made with <a style='color: #FF8C00' href='https://play.google.com/store/apps/details?id=com.mirrorai.app&amp;hl=en' target='_blank'>Mirror Emoji Keyboard &amp; Sticker Maker</a>"><img src="/gfx/Avatar.png" class="avatar" alt="Avatar"></a>
`

This code is ok?

**Comment by fancyapps** [comment]
Hi,

So, basically, you want to have layout like in the original fancybox? Sorry, there is no option for that. This has been asked multiple times, but the answer is the same - there are too many issues with that layout, therefore you will not see it anywhere - not on fb, twitter, any news/magazine homepage, etc

**Comment by alecos71** [comment]
That do you suggest me?

What is unsupported? At the least

data-fancybox
data-caption

Are supported?

The only unsupported is link in caption?

Thanks
