### ISSUE TITLE
link in data-caption

### ISSUE THREAD

**Issue by alecos71** [fancyapps/fancybox#2368]
I'd like to have links in data-caption like this:

`<a href="/gfx/Avatar_b.png" data-fancybox data-caption="Made with <a style='color: #FF8C00' href='https://play.google.com/store/apps/details?id=com.mirrorai.app&amp;hl=en' target='_blank'>Mirror Emoji Keyboard &amp; Sticker Maker</a>"><img src="/gfx/Avatar.png" class="avatar" alt="Avatar"></a> `

**Comment by acwolff** [comment]
see #2316
