### ISSUE TITLE
callback binds function on fancybox

### ISSUE THREAD

**Issue by Spica2** [fancyapps/fancyBox#237]
I bind a function to the fancybox with a callback like so

``` JavaScript
afterShow: function(){ 
    $('.fancybox-opened').on('leftSwipe', function(){
        $.fancybox.next();
    })
    .on('rightSwipe', function(){
        $.fancybox.prev();
    }); 
},
```

But then the wrapper container doesnt get removed anymore, only the class fancybox-opened gets removed. How to get the container removed again?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
