### ISSUE TITLE
clicking out/closing is changing the thumbnail absolute position 

### ISSUE THREAD

**Issue by mttindustries** [fancyapps/fancybox#2371]
This was working fine for me for quite a while but just today I noticed this bug and I havem't changed anything. I am however linking to the source files through the hosted cdn servers so I wonder if this was caused by a recent update. So far the problem is only in chrome it works fine in firefox. 

So the image I use to activate the lightbox feature we'll call the thumbnail for this post, changes it's position once you close out of the light box. I have coded the thumbnails in a flexbox grid and am using position absolute with some off sets so help centre and crop the image because it uses from zoom transition animations on zoom. 

if I disable position absolute on my thumbnials then it works but then I don't get the desired cropping if the image isn't the right size for the square. 

You can see a live example on my website www.mttwood.com on the instagram feed on the home page. This has always been buggy. I've been redesigning it offline and everything was working fine until I checked it today and suddenly it no longer works anymore.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

![fancyappbug](https://user-images.githubusercontent.com/17806425/67829494-867cc480-fb2b-11e9-9137-1e681abd82e5.jpg)

**Comment by fancyapps** [comment]
Hi,

Your page seems to be working fine. The only thing that could cause some issues is the "placing focus back on the trigger element" feature, you can disable that by setting `backFocus: false`.
