### ISSUE TITLE
Where is variable descr in the Share dialog?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2373]
The documented share tpl contains a line:

` '<a class="fancybox-share__button fancybox-share__button--tw" href="https://twitter.com/intent/tweet?url={{url}}&text={{descr}}">'`

The definition of url is given in this share documentation, but I can't find the variable descr and I see no capion or other description in the twitter share dialog, so descr seems to have no effect.

I tried to add descr as follows:

         share: {
             descr: function(instance, current) { current.opts.$orig.data('caption') },
             url: function(instance, item) {

but that does not work.

So my question is how to add the image caption to the Twitter tweed?

**Comment by acwolff** [comment]
No idea why this is closed without any comment!

**Comment by fancyapps** [comment]
You have already opened multiple issues about share dialog and the answer is the same as always - you can easily create your own share module based on the existing one if provided functionality does not fit you.

**Comment by acwolff** [comment]
I know, I made  in the meantime my own Share window, see [here](https://andrewolff.jalbum.net/FB_FixedShapeThumbs/#S-3).
