### ISSUE TITLE
Can I pass a parameter to the function linked to a new custom button in the toolbar?

### ISSUE THREAD

**Issue by Loboboboboboo** [fancyapps/fancybox#2375]
I've created a custom button in the toolbar as instructed here: 

https://fancyapps.com/fancybox/3/docs/#faq-3

I want to pass the image ID to the click function - can I do this?

Thanks!

**Comment by fancyapps** [comment]
Hi,

There is no need to post your question multiple times, already answered here - https://stackoverflow.com/questions/58680047/fancybox-can-i-pass-a-parameter-to-the-function-linked-to-a-new-custom-button
