### ISSUE TITLE
Problem with rounded border around the light-box images.

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2376]
I added a rounded border and some spacing to my light-box images, see [this album](https://www.andrewolff.nl/FotoSerie/OverigeTochten/Winterswijk/) and  https://codepen.io/acwolff/pen/LKErmJ.

I used this CSS code:

     img.fancybox-image {
        border-width: 5px;
        border-color: rgba(255,255,255,1.0);
        border-style: solid;
        border-radius:  20px;
        padding:  10px;
    }`

This works fine after the light-box has been opened, but if you click a thumbnail to open the light-box, you see for a short moment an ugly thick white border.

How can I prevent this?

BTW You don't see that ugly thick white border if you open the image in full screen mode. To see that open [this album](https://www.andrewolff.nl/FotoSerie/OverigeTochten/Winterswijk/), click on the settings button in the upper right corner and select next 'Use full screen for a picture”: yes'. Close the settings window and click on a thumbnail.

**Comment by fancyapps** [comment]
Hi,

To archive best animation performance, images are scaled (while zooming in/out) using CSS transform property, but the drawback is that everything scales - borders, shadows, etc, etc. And there is currently no possibility to avoid that.

**Comment by acwolff** [comment]
Thanks for your quick answer and your excellent library!

Is there any change that this can be improved in the next version?

**Comment by fancyapps** [comment]
Just disable zooming.
