### ISSUE TITLE
afterLoad callback on iFrames runs before content is actually loaded

### ISSUE THREAD

**Issue by DanielMenjivar** [fancyapps/fancybox#238]
I recently updated http://dmblog.ca/ from fancyBox 2.0.5 to 2.0.6 and noticed that the behavior with loading iFrame content had changed.

It seems that the **afterLoad** callback is triggered _before_ the content is even loaded on the page – you'd expect this callback to be triggered _after_ the markup has been inserted into the DOM, no?  That way you can make any modifications to the new elements if you need to...

The way I ran into this, actually, was when I was looking at [how YouTube videos are loaded on the site](http://dmblog.ca/search/dmyoutube/).  The videos have been loading via fancyBox for quite a while now, and it has worked flawlessly until I updated to 2.0.6.

To give a brief history, I recently had some hard drive issues on my Mac and needed to fresh install Lion.  I decided not to install Flash but installed the [YouTube5 extension for Safari](http://www.verticalforest.com/youtube5-extension/) to still allow me to watch YouTube/Vimeo/Facebook videos without Flash.  Looking at the JS for this extension (using the web inspector in Safari), it adds an event listener to the _beforeLoad_ event to examine the location.href of the element and replaces the markup (iframes, for example) to HTML5 &lt;video&gt; tags where necessary.  This works since most video online is encoded with H.264 anyways.  With fancyBox 2.0.5, all the [videos being loaded via fancyBox on dmblog.ca](http://dmblog.ca/search/dmyoutube/) still worked perfectly using this extension, but with 2.0.6 it wasn't working anymore.

Using 2.0.6, if I disabled the YouTube5 Safari extension, the videos would load fine, but with the extension enabled, you could hear the YouTube videos playing in the background but you'd never actually _see_ them loaded in a fancyBox window.  (Or anywhere on the page for that matter.)  FancyBox got stuck on the loading animation and even calling _hideLoading_ didn't seem to help.  I figured it might have to do with the fact that fancyBox looks for a &lt;body&gt; tag to get the dimensions for the box, but the body tag never actually loads any content since the YouTube5 extension has an event listener attached to _beforeLoad_...

When trying to find a workaround/solution for this, I tried loading an empty iFrame first, and then changing the src attribute to the correct youtube.com value using the **afterLoad** callback.  But since this callback is actually being triggered _before_ the content is loaded (and not after) it didn't work – there was no iFrame loaded on the page yet.  I ended up using the **beforeShow** callback instead, and that works fine, but in the meantime, the **afterLoad** callback still has behavior that should be fixed.

Here's the JavaScript that I'm now using to load [YouTube videos on dmblog.ca](http://dmblog.ca/search/dmyoutube/) in a fancyBox:

``` javascript
// ! Open our YouTube Videos using fancybox
$('.dm-youtube a').fancybox({
    beforeLoad  : function() {
        this.type   = 'iframe',
        this.width  = 854,
        this.height = 480,
        // youtube.ca doesn't actually work, but in order to prevent Safari's YouTube5 extension from replacing this, we use .ca and replace it below
        this.href   = '//www.youtube.ca/embed/' + $(this.element).attr('href').replace('#dm-video-','') + '?rel=0&hd=1&autoplay=1&autohide=1&showinfo=0';
    },
    afterLoad   : function() {
        // track our youtube video plays with google analytics
        _gaq.push(['_trackEvent', 'Media', 'View YouTube Video', $('img',$(this.element)).attr('alt')]);
    },
    beforeShow  : function() {
        // we can't just replace the src of the iframe, because we still want to give YouTube5 a chance to replace our iframe (just not before)
        // and it only works when inserting new elements (not when you change the src)
        var iframe  = $('.fancybox-inner').first(),
            oldhtml = iframe.html(),
            newhtml = oldhtml.replace('youtube.ca','youtube.com');

        iframe.html(newhtml);
    }
});
```

Without the plugin enabled, the HTML markup generated by fancyBox inside of the _fancybox-inner_ div is:

``` html
<iframe class="fancybox-iframe" name="fancybox-frame1336494068534" frameborder="0" hspace="0" scrolling="auto" src="//www.youtube.com/embed/AhafCvth6ZA?rel=0&amp;hd=1&amp;autoplay=1&amp;autohide=1&amp;showinfo=0"></iframe>
```

With the plugin enabled, this gets changed to:

``` html
<div class="youtube5container" style="width: 854px; height: 480px; ">
    <div class="youtube5player" style="width: 853px; height: 480px; ">
        <video src="http://o-o.preferred.rogers-yyz1.v11.lscache4.c.youtube.com/videoplayback?upn=xY5dr4czkXs&amp;sparams=cp%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&amp;fexp=900064%2C919306%2C913539&amp;itag=22&amp;ip=72.0.0.0&amp;signature=8CE4DA81B2FDF4DA8E62D956FDAD6F441B364903.B47708A102A864FBD1A88843C780AECBEFA3C501&amp;sver=3&amp;ratebypass=yes&amp;source=youtube&amp;expire=1336518638&amp;key=yt1&amp;ipbits=8&amp;cp=U0hSS1VMVl9IUkNOMl9NRlpHOnhlTlNaMkluRGdD&amp;id=02169f0afb61e990" width="853" height="480"></video>
        <div class="youtube5top-overlay"></div>
        <div class="youtube5bottom-overlay"></div>
        <div class="youtube5info">
            <div class="youtube5use-original youtube5show-on-waiting">↵ Use original player</div>
            <div class="youtube5title youtube5show-on-waiting"><a href="https://www.youtube.com/watch?v=AhafCvth6ZA">Cuban Friends Quintet</a></div>
            <div class="youtube5author youtube5show-on-waiting">By <a href="https://www.youtube.com/user/danielmenjivar">danielmenjivar</a></div>
            <div class="youtube5formats">
                <div class="youtube5from">YouTube</div>
                <ul>
                    <li class="youtube5current-format"><a href="http://o-o.preferred.rogers-yyz1.v11.lscache4.c.youtube.com/videoplayback?upn=xY5dr4czkXs&amp;sparams=cp%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&amp;fexp=900064%2C919306%2C913539&amp;itag=22&amp;ip=72.0.0.0&amp;signature=8CE4DA81B2FDF4DA8E62D956FDAD6F441B364903.B47708A102A864FBD1A88843C780AECBEFA3C501&amp;sver=3&amp;ratebypass=yes&amp;source=youtube&amp;expire=1336518638&amp;key=yt1&amp;ipbits=8&amp;cp=U0hSS1VMVl9IUkNOMl9NRlpHOnhlTlNaMkluRGdD&amp;id=02169f0afb61e990">720p</a></li>
                    <li><a href="http://o-o.preferred.rogers-yyz1.v13.lscache3.c.youtube.com/videoplayback?upn=xY5dr4czkXs&amp;sparams=cp%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&amp;fexp=900064%2C919306%2C913539&amp;itag=18&amp;ip=72.0.0.0&amp;signature=D37FFF6800973128BF12C08D8BFAF9BF47B190FD.3F995B68BF989478074E9FDA324392D00CAF7968&amp;sver=3&amp;ratebypass=yes&amp;source=youtube&amp;expire=1336518638&amp;key=yt1&amp;ipbits=8&amp;cp=U0hSS1VMVl9IUkNOMl9NRlpHOnhlTlNaMkluRGdD&amp;id=02169f0afb61e990">360p</a></li>
                    <li><a href="http://o-o.preferred.rogers-yyz1.v22.lscache5.c.youtube.com/videoplayback?upn=xY5dr4czkXs&amp;sparams=algorithm%2Cburst%2Ccp%2Cfactor%2Cid%2Cip%2Cipbits%2Citag%2Csource%2Cupn%2Cexpire&amp;fexp=900064%2C919306%2C913539&amp;algorithm=throttle-factor&amp;itag=5&amp;ip=72.0.0.0&amp;burst=40&amp;sver=3&amp;signature=1B6A12CCA23C7F64838AF7D55AB245E50CC13AA3.2413FD05C4C99810E5603BC0538398C133C5EBF4&amp;source=youtube&amp;expire=1336518638&amp;key=yt1&amp;ipbits=8&amp;factor=1.25&amp;cp=U0hSS1VMVl9IUkNOMl9NRlpHOnhlTlNaMkluRGdD&amp;id=02169f0afb61e990">240p FLV</a></li>
                </ul>
            </div>
            <div class="youtube5replay">← Replay</div>
            <div class="youtube5close-overlay">X</div>
        </div>
        <div class="youtube5info-button">i</div>
        <div class="youtube5controls youtube5pause">
            <div class="youtube5play-pause"></div>
            <div class="youtube5time-elapsed">00:05</div>
            <div class="youtube5fullscreen"></div>
            <div class="youtube5volume youtube5high">
                <div class="youtube5volume-indicator"></div>
                <div class="youtube5volume-popup">
                    <div class="youtube5volume-max"></div>
                    <input class="youtube5volume-slider" type="range" min="0" max="100">
                    <div class="youtube5volume-mute"></div>
                </div>
            </div>
            <div class="youtube5time-remaining">-03:08</div>
            <div class="youtube5progress">
                <div class="youtube5loaded" style="width: 179.03963698887804px; "></div>
                <div class="youtube5played" style="width: 28.018px; "></div>
                <input class="youtube5position" type="range" min="0" max="1000">
            </div>
        </div>
    </div>
</div>
```

So what's the problem if I already found a workaround?  Good for me for finding a solution _in the meantime_, but it doesn't change the fact that the **afterLoad** callback is running _before_ content is actually loaded, not _after_ like the name would indicate.  This behavior should be changed, no?

Hope this helps.

DM

**Comment by feeela** [comment]
@fancyapps Why is this issue closed? As of Fancybox 2.1.5 this bug is still valid!

You say that: “The "afterLoad" callback indicates that the content has been loaded”, which is plainly wrong. (See the descriptions above.) _You_ may _think_ that this event is triggered after the content is loaded, but is obviously not, since one can't access the content in the `afterLoad` callback.

It seems very strange to me, that you close an issue without even responding to the facts listed above and without providing a fix or a reason to not fix this this bug.

Please consider to reopen this issue.
