### ISSUE TITLE
Fullscreen resize problem

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2380]
In [this album](https://andrewolff.jalbum.net/FB_FixedShapeThumbs/#S-5) I added a FullScreen button.

This works OK except that the image does not resize if I click the FullScreen button. 
To force a resize I have to go to the next slide and back again.
Also if I go back to normal size, the image is too large and I have to use the Refresh button or F5 to get the correct size.

My question is how can I get this correct?
How can I implement an extra refresh if the FullScreen button is clicked?

Tested on a Windows 10 PC with the latest Chrome and FireFox version.
Also tested on an iPad, but there is no problem: the image is resized correctly.

**Comment by acwolff** [comment]
?? Why is this closed wihout any comment?

**Comment by fancyapps** [comment]
There is no any "Fullscreen resize problem" on any official demo, so why should anyone visit your site to see your highly modified demo? I do not think that anyone will willingly spend their time to debug your code.

**Comment by acwolff** [comment]
But if I can implement a refresh if the FullScreen button is clicked, the problem is solved!

**Comment by fancyapps** [comment]
Please, I beg you, wait for v4...

**Comment by acwolff** [comment]
Of course I am looking forward to your new version.
I can help you to beta test your new version, please let me know.
