### ISSUE TITLE
Can fancybox fix image orientation while displaying images?

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2381]
I've notice that fancybox displays the images on mobile phones the correct way... But if the image was taken with an iphone.... it will be correctly oriented on my phone (whether iPhone or Android) ... but if I open chrome or safari on my Mac, it will appear displayed sideways (landscape mode)... NOTE: this ONLY happens on images shot in portrait mode on my iPhone.

Any ideas or plugin that can be add to the recipe?

**Comment by fancyapps** [comment]
Hi,

The answer is: No.

fancybox, like any other JS script that runs in the browser, does not have access to the file system and can not access image exif info. Therefore you should fix image orientation on the server side.

There is an interesting read I stumbled upon recently - https://justmarkup.com/articles/2019-10-21-image-orientation/ - with code sample on how to fix image orientation using Node, but I am sure you can find similar code snippets for any programming language, if needed.
