### ISSUE TITLE
Index Internationalization

### ISSUE THREAD

**Issue by wdgBernd** [fancyapps/fancybox#2382]
is there a possibility to translate the Index - Part?

```
$( '[data-fancybox="images"]' ).fancybox({
    infobar : false,
    caption : function( instance, item ) {
        var caption = $(this).data('caption') || '';

        return ( caption.length ? caption + '<br />' : '' ) + 'Image <span data-fancybox-index></span> of <span data-fancybox-count></span>';
    }
});
```

So, for German users it has to be like

` return ( caption.length ? caption + '<br />' : '' ) + 'Bild <span data-fancybox-index></span> von <span data-fancybox-count></span>';`

Thanks a bunch!

**Comment by fancyapps** [comment]
Hi,

I do not know what anwser did you expect, but the simplest solution would be smth like this:

```JS
$( '[data-fancybox="images"]' ).fancybox({
    infobar : false,
    caption : function( instance, item ) {
        let caption = $(this).data('caption')  || '';
        let lang = item.opts.lang;
        return `${caption} <div> ${lang === 'de' ? 'Bild' : 'Image'} <span data-fancybox-index></span> ${lang === 'de' ? 'von' : 'of'} <span data-fancybox-count></span></div>`;
    }
});
```

**Comment by wdgBernd** [comment]
Hi,
thank for your fast answer. Sorry for my demand, but i'm not very familiar with JS.
Generally that's exactly, what i'm looking for. But the code doesn´t work. I get only the englisch variant, even though i'm on an german browser.
BTW: How could i test this behaviour?

Many Thanks!

**Comment by wdgBernd** [comment]
Ok, Seems to work. Many thanks!!
Do you know how to test, that the "switch" works correct?
Is there any possibility to switch the language in the browser to force the Switch to "en"?

**Comment by fancyapps** [comment]
Hmm, do you expect that the script will detect and set language automatically based on browser parameters? If so, then, sorry, there is currently no such feature. You will have to set language manually.

To quickly test JS code, open developer tools (hit F12), select Console tab and paste your code.

**Comment by wdgBernd** [comment]
Ah ok, the works so far. If i change the value of lang to "en" i got the englisch Version.
Is there a possibility to change the "lang" Parameter depending on a css-class?
E.g.
If css =".englishVersion" then lang="en"
If css =".germanVersion" then lang="de"
This would solve it....

**Comment by fancyapps** [comment]
Just replace `'de'` with anything you need, but that is up to you. You could, for example, do like this https://stackoverflow.com/questions/949341/how-to-obtain-lang-attribute-in-html-using-javascript

**Comment by wdgBernd** [comment]
ok - solved it:

`if ( $( "body" ).is( ".language--deutsch" ) ) {
 
    $.fancybox.defaults.lang = 'de';
 
}
if ( $( "body" ).is( ".language--englisch" ) ) {
 
    $.fancybox.defaults.lang = 'en';
 
}
`
