### ISSUE TITLE
can we increase zoom in fancybox

### ISSUE THREAD

**Issue by kuldeepkaushik** [fancyapps/fancybox#2385]
Hi 

We are using fancybox on our image galleries . We have shirt images . We need to increase the zoom .

can we achieve this in zoom ?

Any help will be highly appreciated .

Best regards
Kuldeep

**Comment by fancyapps** [comment]
Hi,

Custom zoom levels are currently not supported, that be one of the new features of v4.

Closing this, because this has been asked multiple times and there is already a feature request for that.
