### ISSUE TITLE
Unable to load getUserMedia in iframe in fancybox?

### ISSUE THREAD

**Issue by Nemra1** [fancyapps/fancybox#2387]
Simple i have this href

`<a data-fancybox data-type="iframe" data-src="https://webrtc/room/1" href="javascript:;"><i class="fa fa-video-camera" aria-hidden="true"></i></a>
`in my webpage
https://i.stack.imgur.com/3gWz5.png
and this error showing in chrome console
https://i.stack.imgur.com/6GBqL.png
 am trying the stream url in another iframe and is working perfect..is not working only in fancybox 3

any solution ? Thx for help

**Comment by fancyapps** [comment]
Hi,

Error message is quite self-explaining. Most likely due to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
