### ISSUE TITLE
Can I trigger an extra class when displaying certain images?

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2388]
I have a javascript function which extracts the EXIF data from the images that I upload to my server... As you probably know, iPhone images (if taken on portrait mode) would appear sideways inside an iFrame like the one used in your script.... If I previously stored a flag on a database for those images, how can I trigger a function with FancyBox, to include a css class which rotates the image 90 degrees to the right... I have all that code working flawlessly... I just need from you how to call the class within FancyBox image gallery viewer, so that it calls my function based on the position of the image, which I want to rotate onto the user's device whenever necessary.

Thanks

**Comment by fancyapps** [comment]
Hi,

You could, for example, add custom attribute to your links (like `data-rotate`), then you would use some callback (`beforeLoad`, for example) to read that attribute and then do the rest. See https://fancyapps.com/fancybox/3/docs/#events for samples on how to use callbacks.
