### ISSUE TITLE
Avoid scrolling back to initial position on close

### ISSUE THREAD

**Issue by Thyrvax** [fancyapps/fancybox#2389]
Hello, 

First of all, thanks for this amazing tool you created. 

I'm trying to build a gallery with infinite scrolling. I am using the following event to trigger the scroll from fancybox:  
`beforeShow: function (instance, current) {
                let elem = current.$thumb[0];
                window.scroll({top: getYCenteredPos(elem), left: 0, behavior: 'smooth'});
            },`

It works fine. My issue is than when closing fancybox, the page is scrolled back to it's position before opening fancybox. 

I've tried playing with autoFocus and backFocus but I am not able to prevent the scrollback.

In [the project page ](https://fancyapps.com/fancybox/3/), it looks like some examples have different behavior regarding this point. 

For example, the 'Hidden HTML element' demo and the 'Custom design and open/close animation' demo do not behave in the same way. 

If I open the Hidden HTML element demo and scroll(0,150) is the browser console, I'm scrolled back to initial position on closing Fancybox. 

However, if I do the same with 'Custom design and open/close animation' , it does not scroll me back. 

Is there anyway to achieve this ? 

edit: i've seen that it's been discused before in some issues here, sorry if I am missing an obvious point

Thanks in advance

**Comment by Thyrvax** [comment]
[Here is a fiddle](https://jsfiddle.net/ntp0csvx/) demonstrating the simplified behavior. It's not consistent, sometimes, the page stays where it is, sometimes, it jumps to the image clicked to open Fancybox.

**Comment by edi** [comment]
I'm no member or contributor of this library but still, yes. 

If you're saying that it doesn't happen while working with custom open/close animations, then you can look at the source code for that close animation method.

It's pretty easy to log `window.scrollY` beforeClose and `afterClose` and it becomes obvious scroll is being changed between the two calls.

Now, if you browse the source code a bit, you will notice that the `cleanUp` method [here](**https://github.com/fancyapps/fancybox/blob/b507d317a95b70a0b1be7209d528c4dba3ee0dd0/src/js/core.js#L2853**) is called `beforeClose` and `afterClose`, and that it is wrapped in a variable called `done`, under the `close` method.

Do some console logging and you'll figure out exactly when the scroll reset happens :)
Hope this helped.

**Comment by Thyrvax** [comment]
Thanks for the input, I'll give it a shot by curiosity, but after more research, I think that I am approaching this whole thing in an incorrect way, creating an over-complicated pattern (programmatically scrolling the background page while the user is in the lightbox to load more images, which feels totally wrong)

Moreover, after comparing how it works on different website, it seems that the norm is to let the user go back to the same positon he was before opening a modal. 

I'll still give it a shot to check that it's not a browser issue. Thanks again
