### ISSUE TITLE
Pixelated thumbnails in Edge

### ISSUE THREAD

**Issue by Mirta91** [fancyapps/fancybox#2392]
**The description**
The thumbnails that are being shown in a full-size gallery are very blurry in Microsoft Edge. I know that this is caused by a poor image rendering from the browser. The original sized images are way bigger, and when being resized to a smaller size they become blurry, pixelated. Is there any way to fix this?

**Expected behaviour**
It is expected that the images are shown in Edge, the same way as in Chrome or FF.

**Screenshot**
![pixelated-thumbs-edge](https://user-images.githubusercontent.com/10676463/69830580-80920600-11f3-11ea-911a-135fc49c944f.png)

**Comment by fancyapps** [comment]
Hi,

Maybe play with CSS `image-rendering` rule (https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering), but the best would be to resize your images to match thumbnail dimensions so that you could avoid any resizing. 

I do not think there is anything else that could be done.
