### ISSUE TITLE
Tall videos shown in landscape video wrapper

### ISSUE THREAD

**Issue by edi** [fancyapps/fancybox#2393]
Hei! Let me start by saying that your library is awesome, and I use it for every project.
Though, how do I get portrait videos shown correctly? Check the [screenshot here](https://user-images.githubusercontent.com/7712869/69900217-5bc79b00-1379-11ea-90ef-7537eb6aa92a.png)

Note how a portrait image looks [here](https://user-images.githubusercontent.com/7712869/69900225-7568e280-1379-11ea-965a-5d9bdb0b8647.png), compared to the above video, both being in portrait mode.

Regards!

**Comment by fancyapps** [comment]
Hi,

The solution would be to use `ratio` option, for example, add `data-ratio="0.5625‬"` attribute to your link.

**Comment by edi** [comment]
Any clue how I could calculate this ? Maybe I should take the vids resolution and do some math with it.

Thanks!

**Comment by fancyapps** [comment]
Simply take video resolution and put numeric value of the ratio, e.g., 16/9 would be 1.77, but 9/16 would be 0.5625, and so on.
