### ISSUE TITLE
Fancybox 3 Initialize with JavaScript not working in WordPress Esquise theme

### ISSUE THREAD

**Issue by Farrukhzaman** [fancyapps/fancybox#2394]
I am using jQuery Fancybox3 in Wordpress Esquise theme. Fancybox is working fine when i Initialize with data attributes. But when i intialize with javascript no any option working. Not any conflict in console. Here is my code which i am using in footer.php

    <script>
jQuery(document).ready(function($){
$().fancybox({
    baseClass: "fancybox-custom-layout",
    infobar: false,
    touch: {
      vertical: false
    },
    buttons: ["close", "thumbs", "share"],
    animationEffect: "fade",
    transitionEffect: "fade",
    preventCaptionOverlap: false,
    idleTime: false,
    gutter: 0,
    // Customize caption area
     thumbs : {
        autoStart : true,
    },
    caption: function(instance) {
      return '<p>Ad goes here</p>';
    }
  });
});
</script>
I want to show thumbnails when popup open. Here is the page link where gallery is showing

[Gallery Page](https://ifashionnetwork.com/2019/11/23/self-portrait-spring-summer-2020-collection/?w3tc_note=pgcache_purge_post)

Anybody can help me?

Thanks

**Comment by fancyapps** [comment]
Well, it seems to work fine. 

FYI, the #1 issue with WP is when you are having lots of plugins and some of them include their own version of jQuery. If you include jquery.js after you have included fancybox, then fancybox will be lost, just like any other jQuery plugin.

**Comment by mjcampagna** [comment]
The other problem with WordPress is its system of registering/enqueueing scripts. If you’re putting scripts directly into the footer, you should wrap them in some PHP to ensure they’re firing after jQuery has enqueued. I have code for that, but not close at hand. I’ll try to remember to dig it up later.

**Comment by mjcampagna** [comment]
This is how I do scripts in my Wordpress footer, ensuring they load in the appropriate sequence. Mind the comments; I've put them in just for you.

```php
<?php
  function enqueue_inline_script() {
    // 'scripts' is whatever name/id the enqueue has been assigned, so maybe 'jquery', etc. 
    // some familiarity with or digging into the theme may be required here:
    if (wp_script_is('scripts', 'done')) {
?>
  <script>

      // JavaScript in here ...

  </script>
<?php
    }
  }
  // priority 21 to trigger after wp_enqueue_scripts (20);
  // likewise, you may need to dig into your theme to get the appropriate priority value for your dependency
  add_action('wp_footer', 'enqueue_inline_script', 21);

  wp_footer();
?>
```

**Comment by Farrukhzaman** [comment]
Thanks @mjcampagna. Its working fine for me. Issue is this when popup open and i refresh window then thumbnails show. Not showing first time popup. Look here

https://ifashionnetwork.com/2019/11/23/self-portrait-spring-summer-2020-collection/

Click any image popup appear. then refresh window.

Thanks

**Comment by mjcampagna** [comment]
@Farrukhzaman Your site is very slow to load for me.

Looking at your source code, the Fancybox script is the last to load. Possibly you're attempting to setup your customizations, before Fancybox itself is available. Depending on how things are setup, this may or may not be the issue. I would try to load Fancybox earlier in the enqueue sequence.

**Comment by Farrukhzaman** [comment]
Thanks @mjcampagna . Now popup working fine with custom layout. Please can you tell me one more thing. In custom layout instead of caption can we add Google adsense code?

**Comment by mjcampagna** [comment]
@Farrukhzaman If you write a custom layout component, probably. Using out-of-the-box options, probably not.  For example, Fancybox's thumbnails aren't a part of the core script; they're an extension. You might model your ad-sense extension on it:
https://github.com/fancyapps/fancybox/blob/master/src/js/thumbs.js

**Comment by Farrukhzaman** [comment]
Thanks @mjcampagna . Can you show me any example? Thanks

**Comment by mjcampagna** [comment]
@Farrukhzaman Of adsense, no. But here's a sample gallery with a custom UI that I've built. Click the Image icon in the top-right of the slideshow to open it:
http://theturninggate.net/galleries/01-album-demonstrations/01-classic-grid/

I used the thumbs.js file as a reference for how to build it, and tie it into the Fancybox presentation. So again, that's where I recommend to start.

**Comment by Farrukhzaman** [comment]
@mjcampagna. By using thumbs.js. I can add google adds in my Gallery? Right?
