### ISSUE TITLE
Is this mobile behaviour correct?

### ISSUE THREAD

**Issue by Vinner-dev** [fancyapps/fancybox#2396]
Hi, running version v3.5.6.

On a mobile (android chrome), when the fanybox is active, the buttons (share, ful-screen, close, etc) do not fade out. Instead you can tap the screen once to hide the buttons. You must double-tap the screen to zoom in/out. The buttons will become visible again if you single-tap. Even if you swipe, the butons stay hidden.

Previously (e.g. v3.1.20) the buttons would fade out and you can single-click to zoom, but annoyingly the buttons would return (and then fade) every time you swipe to next image.

I didn't see any reference to this in the change log, so I don't know if it's a side-effect. The thing is, it's really quite nice once you get used to it because the buttons are quite obtrusive on a small screen so it's good to be able to keep them hidden, although it means there are differences between mobile/desktop versions of my site.

Actually, looking further I'm wondering if this is connected with mobile: idleTime?

Is there any documentation for the mobile options?

Cheers

V

**Comment by fancyapps** [comment]
Hi,

It currently works as expected on mobile devices - tap to toggle additional elements and double tap to zoom in/out. When mobile device is detected,  `mobile` option is used to override any other options, see https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L342 for defaults.
