### ISSUE TITLE
Thumbnail Navigation not working in Chrome

### ISSUE THREAD

**Issue by sartinGH** [fancyapps/fancybox#2397]
**Describe the bug**
In Chrome for Mac & PC, when clicking on first and second thumbnails, the relating picture doesn't load. This happens on all of the galleries we've built so far. Works as expected on Edge and Safari.

**To Reproduce**
1. Go to http://www.apcosigns.com/test123/bunge.html
2. Click on any of the pictures to load the gallery.
3. Click on the Thumbnail icon
4. Can navigate throughout the images via the thumbnails EXCEPT for the first and second image in each gallery.

**Desktop (please complete the following information):**
 - OS: Mac & PC
 - Browser Chrome
 - Version: Version 78.0.3904.108 on Mac

**Comment by fancyapps** [comment]
Hi,

I think this is caused by the fact that you are using slim version of jQuery. Could you, please, check if that is the cause of this issue?

**Comment by sartinGH** [comment]
Thank you, @fancyapps . That was indeed the issue!
