### ISSUE TITLE
Scroll problem with the caption in a side-panel

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2404]
I use a customized layout to display the caption in a side-panel, based on the code in https://codepen.io/fancyapps/pen/zPZeKb , see this example: https://andrewolff.jalbum.net/ExtendedCommentSidePanel-2/index.html#S-1 

If I scroll to the end of the long caption and next click the arrow to display the next slide, the scroll bar is not reset to position 0, although I use this code to reset the scroll bar position:

$(".fancybox-custom-layout .fancybox-caption").scrollTop(0);

This is the last line of my function refreshSidePanel(), see https://andrewolff.jalbum.net/ExtendedCommentSidePanel-2/res/indexPage.js

The function refreshSidePanel(), is called in the beforeShow event:

    beforeShow: function(instance, current) {
	slide_index= this.index  + counter + 1;
              description = current.opts.$orig.data('caption');
		emptyCaption= (this.opts.caption.length === 0)
		refreshSidePanel();

see https://andrewolff.jalbum.net/ExtendedCommentSidePanel-2/slidePage.js.

What should I do to reset the scroll-bar if the next slide is displayed?

**Comment by fancyapps** [comment]
Hi,

Please, provide a valid demo on Codepen/jsfiddle without any extra modifications.

**Comment by acwolff** [comment]
The effect is demonstrated here: https://codepen.io/acwolff/full/qLZOLv

**Comment by acwolff** [comment]
Solved by this statement:
  $(".fancybox-custom-layout .fancybox-caption__body").scrollTop(0);
