### ISSUE TITLE
Invalid CSS in jquery.fancybox.css

### ISSUE THREAD

**Issue by tmb-github** [fancyapps/fancybox#2405]
The following blocks of the jquery.fancybox.css contain invalid CSS, as can be verified using https://jigsaw.w3.org/css-validator :

    @supports (padding: max(0px)) {
        .fancybox-caption {
            padding-left: max(12px, env(safe-area-inset-left));
            padding-right: max(12px, env(safe-area-inset-right));
        }
    }
    @supports (padding: max(0px)) {
        .fancybox-caption {
            padding: 75px max(44px, env(safe-area-inset-right)) max(25px, env(safe-area-inset-bottom)) max(44px, env(safe-area-inset-left));
        }
    }

CSS 'padding' does not support the rule as written. Perhaps store the intended values in a CSS variable and employ the variable where the max() computations are currently?

**Comment by fancyapps** [comment]
Hi,

These properties exist since year 2017 when original iPhone X was released - https://webkit.org/blog/7929/designing-websites-for-iphone-x/
