### ISSUE TITLE
Custom Closing Image Icon

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2407]
How do I ...

Create a custom closing image icon that it can be placed depending on the target iframe source content, on either 1 of the four corners of the screen

like this *** class="upperLeft"  "upperRight"  "lowerLeft" "loverRight"

but besides that ... my main goal is to make use of custom PNG images to match the look the the page I will be loading through FancyBox iFrame

.customClosingIconRed {
background-image: url(red-closing-icon.png);
}

.customClosingIconSilver {
background-image: url(silver-closing-icon.png);
}

.customClosingIconGolden {
background-image: url(golden-closing-icon.png);
}

NOW... all of these suggestions could be well eliminated if there is an update on my previous request to have a slideUp or slideDown window with a center image bar on the middle of the screen :)

Look forward to hear from you

Happy New Year 2020!!!

Best regards

**Comment by fancyapps** [comment]
Hi,

But what stops you from creating custom icon? fancybox provides plenty of callbacks and you can use them to accomplish any crazy idea you have.
