### ISSUE TITLE
FancyBox - How to close mp4 video on end

### ISSUE THREAD

**Issue by Craig-jem** [fancyapps/fancybox#2409]
I am using FancyBox for mp4 videos and wish to close the box on end of video

I have looked through FancyBox documentation but could not find anything concrete. I see there are a few threads for youtube videos, however my videos are all local

Am using the following html code below

$('data-src').on('ended',function(){
    $.fancybox.close();
});

html code
`<-- div class="imagebox">
 <-- a data-fancybox data-type="video" data-src="video/myvideo-01.mp4" href="javascript:;">
 <-- img data-u="image" src="img/myvideo-01.png" title="My video" /></a>
<--/div -->`

Any ideas on the code required to close a local mp4 video after the video has been played using FancyBox?

Thanks

**Comment by fancyapps** [comment]
Hi,

It could be, for example, like this:

```JS
$("[data-fancybox]").fancybox({
  afterShow: function(current, slide) {
    slide.$slide.find("video").on("ended", function() {
      $.fancybox.close();
    });
  }
});
```

**Comment by Craig-jem** [comment]
Hi  Jānis

I will try the code and advise if successful or not

Thank you for you time and input
