### ISSUE TITLE
Scroll problem with the caption in a side-panel 

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2410]
I use a customized layout to display the caption in a side-panel, see this codepen: https://codepen.io/acwolff/full/qLZOLv

If I scroll to the end of the long caption and next click the arrow to display the next slide, the scroll bar is not reset to position 0, although I use this code to reset the scroll bar position:

$(".fancybox-custom-layout .fancybox-caption").scrollTop(0);

What should I do to reset the scroll-bar if the next slide is displayed?

**Comment by acwolff** [comment]
Problem solved if you use this statement:

  $(".fancybox-custom-layout .fancybox-caption__body").scrollTop(0);

**Comment by estebandinamarca** [comment]
I have the same problem, but i would like to know Why is this happening?
