### ISSUE TITLE
Slideshow API Parameter has no effect + buggy behavior

### ISSUE THREAD

**Issue by thexmanxyz** [fancyapps/fancybox#2413]
**Describe the bug**
I noticed that there is something wrong with the `slideShow` parameter or I might misinterpreted the parameter as there is no documentation attached on the options reference on the homepage. If I use the following option:

```
 slideShow: {autoStart: true, speed: 10000),
```

Neither the speed of the slideshow is changed nor the slideshow starts automatically on opening an image of the fancyBox. I might confuse here something but I find it worth reporting as I have a strong feeling that it might be a bug. Additionally I noticed that if I set anything within the `slideShow` parameter that the controls on the top right corner are not translated any more (the HTML `title` changes back to the default English labeling). Additionally even if I activate all buttons only 4 of them are shown. Take a look on my screenshot below.

I have all buttons enabled but as soon as I set `autoStart` or `speed` within the `slideShow` parameter the strange behaviour starts. I also noticed that the thumbnail grid stops showing when I attach one of the two above options e.g. setting `thumbs: { autoStart: true },` previously has no effect at all.

**To Reproduce**
1. set `slideShow: {autoStart: true, speed: 10000),` or any other value
2. click on an image to open the overlay
3. check the auto slideshow behaviour, the slideshow speed, the buttons on the right corner, the translation of the button `title` and the thumbnail grid in combination with the `slideShow` setting

**Expected behavior**
The selected buttons should be shown, the translation should work for all button `title` attributes, the thumbnail grid should be shown if previously activated, the slideshow speed should have an effect and the slideshow should start automatically.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17965908/73754430-b22fcc00-4764-11ea-87cd-c6df7b9346f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 73

**Additional context**
I only tested on Desktop with latest FF release version 73. I had no time to verify on different browsers but I'm pretty sure it is not platform related.

**Comment by fancyapps** [comment]
Hi,

Could you, please, create minimal demo on Codepen/jsFiddle/... where this issue could be inspected? That would really help.

**Comment by thexmanxyz** [comment]
Give me a little bit time and I will create a reproducable and inspectable
example. Is there any e-mail adress I can reach out to you? The easiest way
for me to demonstrate is via a joomla test site as I am using the library
within a joomla plugin. I would simply mail you the URL for verification. I
don't want the URL to be public. I hope this ist no issue. Creating an
appropriate fiddle would take me way longer.

Jānis Skarnelis <notifications@github.com> schrieb am Di., 4. Feb. 2020,
18:00:

**Comment by thexmanxyz** [comment]
@fancyapps I'm closing the issue now, it was a stupid mistake I made...sorry...curly bracket vs parenthesis. :-/. My invalid JSON syntax broke the settings...
