### ISSUE TITLE
Multi page documents are not getting scrolled on the safari browser for iOS v13+

### ISSUE THREAD

**Issue by eparirishit** [fancyapps/fancybox#2414]
I am trying to load a multi-page document (word/excel) using iframe on the safari browser for iOS devices (iPad/iPhone) having iOS version 13+. Neither of the vertical or the horizontal scroll is working. 
The same document scrolls very smoothly for iOS version 12 and below.

Could the issue can be due to "-webkit-overflow-scrolling: touch" is disabled? 
[Safari 13 Release Notes](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes)

Is there any fix for this issue? 

**I am using the fancybox v2.1.5**

**Comment by fancyapps** [comment]
Hi,

Sadly, there is no workaround to this webkit bug. If you are trying to display PDF files, then you should use some parser/rendered, for example, https://mozilla.github.io/pdf.js/
