### ISSUE TITLE
Struggling with animationEffect and transitionEffect

### ISSUE THREAD

**Issue by kimaldis** [fancyapps/fancybox#2416]
Try as I might I can't my transition and animation effects to fade.  Durations and other settings are working but transitions and animations are stuck on slide. Any thoughts? See www.aldis.co.uk

			  $.fancybox.defaults.animationEffect = "fade"     
			  $.fancybox.defaults.animationDuration = 1000     

			  $.fancybox.defaults.transitionEffect = "fade"      
			  $.fancybox.defaults.transitionDuration = 2000

**Comment by fancyapps** [comment]
Hi, 

Well, that is very strange, because "fade" is the default transition effect and you have to do some customization to change that. Are you sure you have not initialized fancybox somewhere else, too? Maybe in lazyload script?
