### ISSUE TITLE
Have thumbnails show up when using 'data-thumb' on load

### ISSUE THREAD

**Issue by ZCweb** [fancyapps/fancybox#2417]
How do I ...
I can load thumbnails fine when having a link wrapped around an image. The thumbnails all load fine. They are shown by default. 

Go to 'Angler's Lodge' and see the masonry grid. I am doing the same JS as below.

However when I have thumbnails load using 'data-thumb' this is a different case. The thumbnail navigation is available but it doesn't show the thumbnails by default. You have to click on the square and many users may not know to do this. https://www.gagneconstruction.com/construction-projects-2/ go to Island Getaway and 'view slideshow' button.

I am using this code for the link

`<a class="call-button shortcode-button yellow-hover-white image-slideshow" href="https://www.gagneconstruction.com/wp-content/uploads/projects/island-getaway/001.jpg" data-fancybox="island-getaway" data-thumb="https://www.gagneconstruction.com/wp-content/uploads/projects/island-getaway/thumbs/001.jpg">View Full Slideshow</a>`

Then I hide the other images and load them with 'data-thumb'

`<div class="hide-images" style="width:100%; "><br> <a href="https://www.gagneconstruction.com/wp-content/uploads/projects/island-getaway/003.jpg" data-fancybox="island-getaway" data-thumb="https://www.gagneconstruction.com/wp-content/uploads/projects/island-getaway/thumbs/003.jpg">003</a><br> <a href="https://www.gagneconstruction.com/wp-content/uploads/projects/island-getaway/005.jpg" data-fancybox="island-getaway" data-thumb="https://www.gagneconstruction.com/wp-content/uploads/projects/island-getaway/thumbs/005.jpg">005</a></div>` and many more...

The JS is like this:

```
jQuery(document).ready(function() {
	jQuery('.image-slideshow').fancybox({
		buttons: [
			"zoom",
			"slideShow",
			"fullScreen",
			"thumbs",
			"close"
		],	    
		thumbs : {
			autoStart : true,
			axis: 'x'
		}
	});
	
});
```

Please help with this not sure what is going on. Having thumbnails load like this would be a very powerful feature. Because loading thumbs and hiding with CSS would still load the resources and be bad for page speed. Hoping not to have to pay a developer for assistance (although willing to) and thought this site would be the best forum.

**Comment by fancyapps** [comment]
Hi,

Could you maybe just add this line somewhere -

```JS
jQuery.fancybox.defaults.thumbs.autoStart = true;
```

to make thumbs always load on the start by default? That would be the easiest solution, I somehow had trouble debugging your page.

**Comment by ZCweb** [comment]
Hi I did this and it didn't work

`jQuery(document).ready(function() {
	jQuery.fancybox.defaults.thumbs.autoStart = true;
	jQuery('.image-slideshow').fancybox({
		buttons: [
			"zoom",
			"slideShow",
			"fullScreen",
			"thumbs",
			"close"
		],	    
		thumbs : {
			autoStart : true,
			axis: 'x'
		}
	});
	
});`

I added this to the child theme JS. I can give you access or pay you for your time. I have a similar issue on another project so having this figured out would be very helpful.

**Comment by fancyapps** [comment]
Hi,

You see, if I visit your page, open developer tools and paste that one line in the console input, everything starts working as expected. Therefore I assume that some other code is overriding your options. 

Try replacing 
`jQuery('.image-slideshow').fancybox({`

with 

`jQuery('[data-fancybox="island-getaway"]').fancybox({`
