### ISSUE TITLE
Responsive Fancybox on  page load

### ISSUE THREAD

**Issue by DiegoDiazGato** [fancyapps/fancybox#2418]
How do I make the fancybox on page load responsive? 

On Desktop works fine but on device the image (and fancybox) it's not responsive

You can see it  [here](http://acrip.co/diadelejecutivo/)

This are the styles: `<style>
#consolPopup {
	display: none;
	width: 800px !important;
	margin: 0;
	padding: 0;
}
#consolPopup img {
	width: 100%;
	height: auto;
}
.fancybox-skin {
	padding: 0 !important;
}
.fancybox-content {
	background: none !important;
}
.fancybox-slide--html .fancybox-close-small {
	background-color: yellow;
}
.fancybox-button svg {
	color: black;
}
#popup {
	z-index: 1500px;
}
iframe {
	overflow: hidden;
}
</style>`

And this are the scripts:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script> 
<script type="text/javascript">     
			$(document).ready(function() {        
				$("#popup").fancybox().trigger('click');     
			});
			</script>`

THANKS

**Comment by fancyapps** [comment]
Hi,

Actually, fancybox is responsive by default. If you set your content fixed dimensions (e.g., `width: 800px !important`) that that would most likely break responsiveness on the smaller screens.
