### ISSUE TITLE
Force screen to landscape

### ISSUE THREAD

**Issue by ngocsangyem** [fancyapps/fancybox#2419]
Hi! How to force the screen to landscape after open fancybox?

**Comment by fancyapps** [comment]
Hi,

It depends on the browser - if you could change screen orientation, then there is no reason why you could not do that while opening/closing fancybox (using callbacks). There is an API for that, but the browser support is quite poor - https://caniuse.com/#feat=screen-orientation

**Comment by ngocsangyem** [comment]
Thank you, I will close this issue.
