### ISSUE TITLE
Fancybox with webslide

### ISSUE THREAD

**Issue by ciprianMihalache** [fancyapps/fancybox#2420]
We use https://uxwing.com/webslide/ for our menus.

We start debugging and found out that this peace of css is triggering go to top every time. Is there any changes that you can make on your css so your script won't be affected by this lines

            html {
                overflow: hidden;
                height: 100%;
                -webkit-overflow-scrolling: touch;
            }

            body {
                height: 100%;
                overflow-y: auto;
                overflow-x: hidden;
            }

**Comment by ciprianMihalache** [comment]
/* ================== Mobile Menu Change Brake Point ================== */
@media only screen and (max-width: 991px) {

    /* ================== Mobile Base CSS ================== */
    html {
        overflow: hidden;
        height: 100%;
        -webkit-overflow-scrolling: touch;
    }

    body {
        height: 100%;
        overflow-y: auto;
        overflow-x: hidden;
    }

}

**Comment by fancyapps** [comment]
Hi,

These CSS rules are not created by fancybox.
