### ISSUE TITLE
Changing next & previous image source?

### ISSUE THREAD

**Issue by keden12** [fancyapps/fancybox#2421]
Hey, I am just wondering is there a way of changing the next and previous image sources before they are being clicked? I just need Fancybox to automatically resize the images since when I do it manually after the user clicked the next or the previous button (I need to do it manually), the size won't change and sometimes it gets stretched. Is there a fancybox attribute which would allow me to set the source of the next and previous images so that it will work fine on slideshow and slider? 

```
jQuery(".fancybox-arrow--right").on('click', function () {
			var next = parseInt(index) + 1 + count;
			if(next >= newborns.length)
			{
				console.log("Last Image");
				jQuery(this).prop('disabled', true);
				
			}
            else{
			console.log(next + ' Next');
			var newImg = new Image();
			newImg.src = newborns[next];
			var height = newImg.height;
			var width = newImg.width;
					if (height > width){
					//	jQuery(".fancybox-image").css("height","569px");
					//	jQuery(".fancybox-image").css("width","379px");	
					/*	setTimeout(function(){
						jQuery(".fancybox-image-wrap").css("transform","translate(274px, 44px) scale(1, 1)");	
						},50); 	*/
					} else {
					//		jQuery(".fancybox-image").css("height","569px");
					//		jQuery(".fancybox-image").css("width","853px");	
			/*		setTimeout(function(){						
							jQuery(".fancybox-image-wrap").css("transform","translate(136px, 44px) scale(1, 1)");
						},50); 	*/						
					}
			jQuery(".fancybox-image").attr("src", newborns[next]);			
			count++;
			}	
		});

```

**Comment by fancyapps** [comment]
Hi,

I would strongly advice to approach this differently (keep in mind that next/prev images are preloaded by default). You can use `beforeLoad` callback to change content source.
