### ISSUE TITLE
Fancybox is loading image twice and preloads are loaded every single time

### ISSUE THREAD

**Issue by evapalkova** [fancyapps/fancybox#2423]
Hi, 

I have been working on some websites a long time ago and know I discovered that fancybox is not working properly. I.e. 
1. it loads image twice
2. it preloads images nad after click it preloads all images again 

here are wesites: 
https://zentkova-grybos.com/#pages/2019_diagnosis.html
http://www.evapalkova.com/pages/10_maison_individuelle.html

it is pain in the ass especially for mobile users. Could you please help and tell me how to fix this. 
As for preload, I can simply turn it off. But why is every image loaded twice after click? 

Thank you very much !
Best 
T.

**Comment by fancyapps** [comment]
Hi,

I assume that you are using developer tools to check network activity and and it looks like the images are loading twice, but, in fact, they are not. You could check server logs and there you would see only one request. Then why it shows two requests? Well, that is the nature of HTML/JS and how the script is build. First, <img> is created and that makes first request to appear. Then, when image finishes loading, the script appends that element to the DOM and that makes second request to appear.

**Comment by cmsmith-asc** [comment]
I've checked the server logs and there is actually definitely two requests coming back to the server.  I can confirm this is indeed an issue.
