### ISSUE TITLE
Fancybox trying to fit thumbnail of image in screen

### ISSUE THREAD

**Issue by tonyd238** [fancyapps/fancybox#2429]
What I have: some fancy slider, part of it are hidden out of screen https://prnt.sc/rftf0q 
When i open image that doesn't fit in screen and then close fancybox, it tries to fit image fully in screen, so my markup gets broken https://prnt.sc/rftfz4 https://prnt.sc/rftg93
What can I do? Same issue i found on https://fancyapps.com/fancybox/3/ 
https://prnt.sc/rfth14
https://prnt.sc/rfth7a
https://prnt.sc/rfthem

**Comment by fancyapps** [comment]
Hi,

Sorry, but I am not able to reproduce this issue, I could not quite understand your comment. Any link to live demo/page (or video, perhaps) would help to identify the cause of this issue.

**Comment by tonyd238** [comment]
Hi, here is a video of issue
 2020.01.12-18.47.mp4
<https://drive.google.com/file/d/1IkWL0wEIZKqLYKxDcMR3Ad04PvL8riF7/view?usp=drive_web>


вт, 17 мар. 2020 г. в 18:12, Jānis Skarnelis <notifications@github.com>:

**Comment by tonyd238** [comment]
Sorry, in my previous email i send you wrong video, here is correct one
 2020.03.17-18.45.mp4
<https://drive.google.com/file/d/1OyqUc-1rqguZAgbL8WG7trAa2eRwyXql/view?usp=drive_web>

вт, 17 мар. 2020 г. в 18:48, Костя Балахонов <kostyan20052wot@gmail.com>:

**Comment by fancyapps** [comment]
Oh, it looks like your slider has trouble due to `place focus back after closing fancybox` feature, you can disable that by setting `backFocus: false`.

**Comment by tonyd238** [comment]
Thank you so much for response. After trying your advice i faced with
several new problems, but they was fixed easily. You are nice man, good
luck to you

вт, 17 мар. 2020 г., 19:58 Jānis Skarnelis <notifications@github.com>:
