### ISSUE TITLE
on Close pop: page scroll to top 

### ISSUE THREAD

**Issue by KamranMaqbool** [fancyapps/fancybox#2430]
My issue is when i'am go to bottom of the page then click on my media item then fancy box open but when i close fancybox popup then my page go to top of the page why ???

i'am using this package using npm with ReactJS
i'am also try different technique's that different people's answers but no working for me like 
html.fancybox-lock {
    overflow: visible !important;
} //not worked
i'am also try this link
https://stackoverflow.com/questions/13547007/fancybox2-fancybox-causes-page-to-to-jump-to-the-top

**Comment by fancyapps** [comment]
Hi,

Are you using v2? Then look for solution from that SO post. If you are using newer version, then, please, provide a link to your page where this issue could be inspected, because I do not recall experiencing such issue.
