### ISSUE TITLE
jQuery not defined

### ISSUE THREAD

**Issue by EduardoGommz** [fancyapps/fancybox#2431]
I'm working on a project using Prepros as pug, typescript, scss preprocesor, this is the first time i use Typescript and Prepros allows me to transpile .ts files to javascript , it also allows me to use IMPORTS to include several files into my scripits, the problem comes when i import jquery and after that i import fancybox and when save my file and refresh the browser i open the console and see this error: jQuery is not defined.
The only way that i can make it work is to include fancybox and jquery directly in my html file using the script tag, please help me what can i do to solve this problem?

**Comment by fancyapps** [comment]
Hi,

Sorry, but I just do not know what to recommend for your setup. Maybe look for more general help, like "how to use jQuery plugin with ... ". Basically, you should include jQuery before fancybox.js and, if everything is done correctly, then it just should work fine. 

FYI, fancybox v4 is coming soon as ES6 module, therefore it will be much easier to integrate in any setup, you can preview it there - https://fancyapps.com/next/

**Comment by Jogai** [comment]
You should create a separate file, call it for example import-jquery.js with the following content:

```js
import jquery from "jquery";
export default (window.$ = window.jQuery = jquery);
```
and then:
```js
import "./import-jquery";
require("@fancyapps/fancybox");

(function ($, window) {
    // Code that runs in your function
    $(function () {
        // Code that runs after document loaded
        // do your fancy box stuff here
    });
})(jQuery, window);
```

See https://stackoverflow.com/a/47984928/141243 && https://ultimatecourses.com/blog/what-function-window-document-undefined-iife-really-means
