### ISSUE TITLE
The same picture renders differently when zoomed

### ISSUE THREAD

**Issue by asavchuk** [fancyapps/fancybox#2432]
It seems that Fancybox renders the same image differently in Firefox and Chrome when zoomed. The top is firefox and the bottom is chrome. The image is blurred in chrome. Is there a way to fix that?  This happens at least if the image height is bigger than monitor height. 
[proof](https://i.stack.imgur.com/FHlZJ.jpg)

**Comment by fancyapps** [comment]
Hi,

You could try playing with CSS `image-rendering` property, smth like:

```CSS
img {
  image-rendering: pixelated;
}
```
but I am afraid there is nothing else that could be done, because browser renders image and the result may vary across browser engines.
