### ISSUE TITLE
Typo in Docs Causes an Error

### ISSUE THREAD

**Issue by Pixelous** [fancyapps/fancybox#2434]
There is an extra `;` in docs in base template for layout that causes an error, broken script.

1. Go to https://fancyapps.com/fancybox/3/docs/#options
2. Scroll down to `// Base template for layout`
3. See error `'</div>'; +` after `'<div class="fancybox-caption"><div class=""fancybox-caption__body"></div></div>' +`

So `'</div>'; +` must be replaced with `'</div>' +`

Kind regards

**Comment by fancyapps** [comment]
Hi, Thanks for reporting!
