### ISSUE TITLE
Closing Fancybox overlay crashes any JS on my site

### ISSUE THREAD

**Issue by jowe1** [fancyapps/fancybox#2439]
**Describe the bug**
I have a dropzone and RTE on my site as well as a fancybox to show the images that have been uploaded via dropzone. This works fine until I open an image in the fancybox and close it again. The browser now jumps to the top of the page and somehow reinitializes all js without actually reloading all of it. So the dropzone does not work anymore and the RTE (CKeditor) looks like a normal textarea after closing the overlay.

How can I prevent this from happening? I have already tried:
```
			helpers: {
				overlay: {
					locked: false
				}
			}
```
and I removed all "overflow: hidden" statements from its CSS (I read about that on StackOverflow). But nothing helped.
**To Reproduce**
1. Go to 'https://joachim-wetzel.de/dropzone'
2. Click on 'any image beneath the header'
3. Scroll down to 'nowhere, you are being scrolled up and JS stops working'

Unfortunately the dropzone is blocked behind a login so no trolls can just upload unlimited amounts of files. I could share a test login via PM, though. But you can also see that something is wrong with it when the browser jumps to the top of the page after closing an image overlay.

**Expected behavior**
JS should still work after closing the overlay and browser should stay where the user is at before opening overlays.

**Screenshots**
Before overlay is opened: https://joachim-wetzel.de/fileadmin/user_upload/img/upload/2020-03-22-18-43-39_Screenshot%20from%202020-03-22%2018-42-57.png
After it is closed: https://joachim-wetzel.de/fileadmin/user_upload/img/upload/2020-03-22-18-43-40_Screenshot%20from%202020-03-22%2018-43-09.png
See the RTE not working correctly and also the dropzone's text is gone and it will not work anymore (is unclickable and drag&drop does nothing but open the image in the entire window).

**Desktop (please complete the following information):**
 - OS: all of my OS (Ubuntu 16.04, Windows 10, iPad 4 Mini with iOS11 etc.)
 - Browser Chrome, Firefox (on Ubuntu 16.04 also not working properly, same issues)
 - Version Version 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPad 4 Mini
 - OS: iOS 11.0
 - Browser Chrome
 - Version latest

**Additional context**
Thank you for your time and effort. Great framework as always! It's just a bug with my template or something else I can't figure out on my own. Greetings from Germany. ;)

**Comment by fancyapps** [comment]
Hi,

I think that 99,5% problems, that appear after closing fancybox, is caused by "place focus back to the trigger element" feature and you can disable that by setting "backFocus: false". Could you do apply that? I think that placing back focus is causing the trouble for your parallax.

**Comment by jowe1** [comment]
> I think that 99,5% problems, that appear after closing fancybox, are caused by "place focus back to the trigger element" feature and you can disable that by setting "backFocus: false".

I tried and also added true and false versions of trapFocus and overlay locked, but nothing changed. Also I have excluded the inline JS to a file, now:
https://joachim-wetzel.de/typo3conf/ext/dropzone/Resources/Public/Js/fancyInit.js?1584901206

Is there some way to prevent the normal close function and just code it via jquery + css? So just stop doing whatever fancybox is doing and hide the entire overlay and reopen it once the image is clicked again. So basically: is there a close event listener?

Thank you for your fast reply!

**Comment by fancyapps** [comment]
`helpers` option is from v2, try smth like this:

```JS
$(document).ready(function(){
    $('[data-fancybox="gallery"]').fancybox({
        zoomOpacity: "auto",
        animationEffect: "zoom",
        animationDuration: 366,
        transitionEffect: "slide",
        transitionDuration: 366,
        hideScrollbar: false,
        trapFocus: true,
        backFocus: false,
	hash: false
    });
});
```

**Comment by jowe1** [comment]
What's really funny is that the layout looks completely different on the two sites, even though it is the exact same code:
Broken layout: https://joachim-wetzel.de/fileadmin/user_upload/img/upload/2020-03-22-19-41-33_Screenshot%20from%202020-03-22%2019-40-38.png
Working layout: https://joachim-wetzel.de/fileadmin/user_upload/img/upload/2020-03-22-19-41-47_Screenshot%20from%202020-03-22%2019-41-41.png

Yes, your code now works fine on both sites. Thank you so much! Great and speedy help! <3

**Comment by jowe1** [comment]
Sorry, forgot to close the issue.
