### ISSUE TITLE
how to add a special css class ONLY to certain images

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2445]
I have some images that are incorrectly rotated and stored on my server

I have a .rotate css class which works really nice for that particular case

BUT....

how can I change the rotation of ONLY those images when I view them inside fancybox image gallery?

the same issue with the tiny thumbnails shown on the right of fancybox gallery

See attached image
![Screenshot 2020-04-05_17-44-37-150](https://user-images.githubusercontent.com/15418158/78511852-6c43b400-7765-11ea-9839-5265ca4bd160.png)

**Comment by fancyapps** [comment]
Hi,

Callbacks are designed to allow you to execute your code when needed. See docs for samples or ask more specific question.
