### ISSUE TITLE
customer's license

### ISSUE THREAD

**Issue by qpzerox** [fancyapps/fancybox#2447]
Sorry to bother you again,the previous question i said is not very clearly
I made a static website and **sell to my customer**, which uses fancybox.js, and I have "Extended Commercial license"
Then my customer need to add a program based on the static website,and **sell to his customer**.
do my customer need to purchase a license?

**Comment by fancyapps** [comment]
Hi,

That would be re-selling. So, either your customer has to have Extended license or each of his customers has to have Single license. Thanks.
