### ISSUE TITLE
How do I make it work with auto pagination?

### ISSUE THREAD

**Issue by AT3META** [fancyapps/fancybox#2448]
I am using Fancybox 3.3.3 with OSSN 5.0. It works fine to show the first 10 posts, but once the auto pagination starts all the following posts fail to have fancybox.
The code...
$(document).ready(function(){
            $(".ossn-wall-item .post-contents img").fancybox({
            top: '75px', 
            afterClose: function(){
  			$(".ossn-wall-item .post-contents img").show();
		},
	});
});
Any help is appreciated.

**Comment by fancyapps** [comment]
Hi,

When you write `$(".ossn-wall-item .post-contents img").fancybox()`, you assign click event that starts fancybox to elements that matches your selector. So, if you load new items, they do not have click handler. The solution is to use `selector` option, see https://codepen.io/fancyapps/pen/NLQJQp?editors=1010 for a sample

**Comment by AT3META** [comment]
Hello,
It works! Thank you for your help.
The new code...
$(document).ready(function(){
            $(".ossn-wall-item .post-contents img").fancybox({
            selector : '.ossn-wall-item .post-contents img',
            top: '75px', 
            afterClose: function(){
  			$(".ossn-wall-item .post-contents img").show();
		},
	});
});
