### ISSUE TITLE
Returning false from beforeClose.fb does not prevent closing

### ISSUE THREAD

**Issue by raveren** [fancyapps/fancybox#2454]
Reproduce:
```js
<a href="/" class="fancybox-js">link text</a>
<script>
document.addEventListener('DOMContentLoaded', function () {
    $('.fancybox-js').fancybox()
    $(document).on('beforeClose.fb', () => false)
})
</script>
```

**Comment by fancyapps** [comment]
Hi,

But have you tried to do smth like `$('.fancybox-js').fancybox({'beforeClose' :  ... })`?

**Comment by raveren** [comment]
Hi, Janis, yeah, I worked around the problem before filing the issue. It's still a big bug though.

**Comment by fancyapps** [comment]
Is this a joke? Why do I have to spend time arguing about non-existing issue? It just works. Perfectly.

```HTML
<a href="#test" class="fancybox-js">link text</a>

<div id="test" style="display:none;">
  <h2>
    Hello
  </h2>
  <p>
    This is a simple test
  </p>
</div>
```

```JS
var count = 0;

$('.fancybox-js').fancybox({
  'beforeClose' : function() {
    count++;

    if (count === 1) {
      alert('Try again');
      return false;
    }
  }

})

```

DEMO - https://jsfiddle.net/Lu0seyrz/

**Comment by raveren** [comment]
Documentation:

>  Here is an example of binding to the afterShow event:
>
> 
```
$(document).on('afterShow.fb', function( e, instance, slide ) {
 	// Your code goes here
});
```
> 
> If you wish to prevent closing of the modal (for example, after form submit), you can use beforeClose callback. Simply return false:
> 
```
 beforeClose : function( instance, current, e ) {
 	if ( $('#my-field').val() == '' ) {
 		return false;
 	}
 }
```

Ok, so the config param function `beforeClose` receives parameters in a different order than the `beforeClose.fb` event and one can cancel the closing - the other cannot.

You're right, it's not a bug, just an inconsistency, fair enough, thanks for the response.

**Comment by Raserad** [comment]
I wanna ask you @fancyapps why event returning false:
```
$(document).on('afterShow.fb', function( e, instance, slide ) {
 	return false;
});
```
is not equal to configure returning false:
```
beforeClose : function( instance, current, e ) {
 	return false;
 }
```
 Maybe it is some unlogical?

**Comment by fancyapps** [comment]
@Raserad Because they are two completely different things. One is listener on the document element and the other one is option passed to fancybox. Fancybox simply can not know what other event listeners are returning.
