### ISSUE TITLE
Fullscreen button for vimeo not displaying in Chrome 

### ISSUE THREAD

**Issue by bboy-splendid** [fancyapps/fancybox#2455]
**Describe the bug**
When launching a vimeo video in Chrome Version 81.0.4044.113 the full screen button is not visible. All working fine on other browsers

**To Reproduce**
1. Go to 'http://jakeparish.com/'
2. Click on 'DOP or Editor'
4. Video launches with no fullscreen video.

**Expected behavior**
The video launch with fullscreen button available

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 81

**Comment by fancyapps** [comment]
Hi,

The script is not responsible for video content. As far as I know, vimeo disables/enables some features depending on user lever of if user has changed embed settings.
