### ISSUE TITLE
Need lightbox images to show header and footer with high contrast border 

### ISSUE THREAD

**Issue by JackieGable** [fancyapps/fancybox#2456]
I would like to use the Fancybox Gallery for our corporate websites as the code for the gallery we are currently using is no longer being maintained. 

For accessibility purposes, we need the fancybox lightbox images to have more contrasts. Many of our customers are elderly and prefer the white border around the lightbox images with the title over the image and a footer. Here is a codepen example of what we are looking for: 
 (https://codepen.io/JapperCat/pres/XWmawYR)

I realize that you are working on a major update for the Fancybox. Will this be an option in the newest version? If not, how can we modify the current version so it can do what we need? If this can be done, we plan on buying several commercial licenses for the  Fancybox. Also, we will need it to work with Cloudinary images too.

**Comment by acwolff** [comment]
This is possible with Fancybox 3 see this [test album](https://andrewolff.jalbum.net/Vecht_SaharaN_FB/#S-1).

**Comment by JackieGable** [comment]
Impressive album Andre. Would you mind showing me how to do it?  I can't view the source code. Is there a codepen that will show me how it's done?

**Comment by acwolff** [comment]
You can see now the source code. 

This album is made with the [jAlbum program](https://jalbum.net/en/software/download) and my [FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) which uses the fancyBox library, which allows you to changes colors, fonts etc. and as an option you can disallows the Rigth mouse click and Long tap context menu. The last option is cleared now.
