### ISSUE TITLE
How to prevent that the image overlaps the buttons and infobar?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2457]
I know that there is a property preventCaptionOverlap which prevents that the image overlaps the caption. This works fine.

Is there a similar property which prevents that the image overlaps the buttons and / or the infobar?

**Comment by octopusxl** [comment]
I used the .fancybox-slide--image padding property

**Comment by acwolff** [comment]
@octopusxl could you please give more details how you did this?

**Comment by octopusxl** [comment]
Add padding to push the image away from the buttons, something like this:
```
.fancybox-slide--image {
  padding: 50px;
}
```

**Comment by acwolff** [comment]
Thanks!

I did inspect my code again and it turns out that I did already use something like that:

.fancybox-slide--image {
    overflow: hidden;
    padding: 44px 0;
}
and if the whole screen should be used I add

.fancybox-slide--image.useWholeScreen {
  padding: 0;
}
So all works already fine!
