### ISSUE TITLE
Ajax is not working

### ISSUE THREAD

**Issue by idzczakp** [fancyapps/fancybox#2460]
Hey.
I want to say that AJAX is not working for me.
Even if I use code from your documentation:
```
<a data-fancybox data-type="ajax" data-src="my_page.com/path/to/ajax/" data-filter="#two" href="javascript:;">
	AJAX content
</a>
```

![image](https://user-images.githubusercontent.com/22243361/81290351-35183980-9068-11ea-9c58-10c2450b4edc.png)

even if I do it in this way result is the same:

```
<a id="test" href="javascript:;">
	TEST
</a>
</body>

<script>
$("#test").on('click', function() {

$.fancybox.open({
	src  : '/modules/management/test.php',
	type : 'ajax'
});
});
</script>
```
![image](https://user-images.githubusercontent.com/22243361/81290552-8f18ff00-9068-11ea-9702-a3bad478a3af.png)

But for example, [THIS OPTION](https://codepen.io/fancyapps/pen/qMewWv?editors=1010) works fine.

**Comment by fancyapps** [comment]
Hi,

Did you try to use regular version of jQuery instead of "slim"?

**Comment by idzczakp** [comment]
@fancyapps Hey, that helps! Thank you!
