### ISSUE TITLE
Zoom Not Working

### ISSUE THREAD

**Issue by Pixelous** [fancyapps/fancybox#2462]
Hi,

can you please tell why zoom not working on a big screen?

https://struminphotography.com/portfolio/sanjin-and-gesabel-wedding-in-toronto/

Here is the smaller image https://struminphotography.com/wp-content/uploads/2020/04/STR_1059_new-870x581.jpg and here is the full size image https://struminphotography.com/wp-content/uploads/2020/04/STR_1059_new.jpg

Kind regards

**Comment by fancyapps** [comment]
Hi,

That corresponding link has `data-width="870"` and `data-height="581"` attributes, the script takes uses values to set image max dimensions instead of the actual image size. So, please, remove these attributes or change them to actual dimensions.

**Comment by Pixelous** [comment]
@fancyapps great, thanks! Appreciate your help.

Kind regards
