### ISSUE TITLE
How to rotate the tool-bar 90° in vertical position?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2467]
On an iPhone in full-screen landscape mode the buttons in the tool-bar can't be used, see also [this issue](https://github.com/fancyapps/fancybox/issues/2347 ).
To make it still possible to use the tool-bar buttons in that case, it would be nice if we could use a vertical tool-bar at the right side of the screen.

What should I do to implement that?

Could that be an option in version 4?

**Comment by octopusxl** [comment]
To move the toolbar, edit the .fancybox-toolbar css. 

Check out http://www.fancyapps.com/fancybox/3/#cl-group-1 , in the <head>section with

**Comment by acwolff** [comment]
@octopusxl your link is invalid, please correct this.

**Comment by octopusxl** [comment]
Is it better now?

**Comment by acwolff** [comment]
No, the link is here still not working, but on page  https://fancyapps.com/fancybox/3/ I see a text:

Below is just a small assortment of creative demos.

But there I see no demo to rotate the toolbar.
If you know how to do it, why don’t you give the code here?

**Comment by octopusxl** [comment]
Ah sorry!!  Your link is correct! It's mainly this part:

```
/* Align buttons at the right side  */
    .fancybox-custom-layout .fancybox-toolbar {
        background: #3b3b45;
        bottom: 0;
        left: auto;
        right: 0;
        top: 0;
        width: 44px;
    }
```

**Comment by acwolff** [comment]
It is like a miracle your code works, see [here]( https://andrewolff.jalbum.net/ExtendedCommentSidePanel/#S-1).

Is there a Codepen with this type of code?
Because I like to reverse the buttons: the Close button at the top.

Thank you very much @octopusxl

**Comment by octopusxl** [comment]
No prob, it wasn't my code, it was in the examples. In https://www.fancyapps.com/fancybox/3/examples.js?v=1590918435, you can see how it was customised,

```
		Creative example - Customized layout
	    ====================================

	*/

  $('[data-fancybox="cl-group"]').fancybox({
    baseClass: "fancybox-custom-layout",
    infobar: false,
    touch: {
      vertical: false
    },
    buttons: ["close", "thumbs", "share"],  // This reverses the buttons
    animationEffect: "fade",
    transitionEffect: "fade",
    preventCaptionOverlap: false,
    idleTime: false,
    gutter: 0,
    // Customize caption area
    caption: function(instance) {
      return '<h3>home</h3><p>interiors, exteriors, and the humans that inhabit them.</p><p><a href="https://unsplash.com/collections/curated/162" target="_blank">unsplash.com</a></p>';
    }
  });
```

Hope it helps!

**Comment by acwolff** [comment]
Well the links is (temporarely?) not working, but your example code will help me.

Thanks again for your help!
