### ISSUE TITLE
Slide orientation inconsistent across browsers

### ISSUE THREAD

**Issue by wencywww** [fancyapps/fancybox#2470]
**Describe the bug**
When a slideshow is started, a slide with an EXIF orientation tag is displayed with different rotation depending on the browser used.

**To Reproduce**
1. Go to https://codepen.io/wencywww/full/rNOEVMz
2. Click on the left image (the right one is not a problem)
3. Do this with Chrome/Firefox and you should see the difference

**Expected behavior**
Slide to be displayed vertically oriented (portrait mode)

**Additional context**
The slide in question has a "right-top" EXIF orientation tag.

**Comment by fancyapps** [comment]
Hi,

The script is not reading EXIF info from the file, it should be done at the server side.

**Comment by wencywww** [comment]
Yeah, seems to be a browser-related behavior. Using a simple <img> tag produces the same effect
