### ISSUE TITLE
Math expressions support in captions

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [fancyapps/fancybox#2471]
**Is your feature request related to a problem? Please describe.**
Right now figure captions cannot show mathematical expressions (see, e.g. https://github.com/gcushen/hugo-academic/issues/1706#issuecomment-635627499)

**Describe the solution you'd like**
To have a way to show mathematical expressions, with the help of [MathJax](https://www.mathjax.org/) or [KaTeX](https://katex.org/) for example.

~~**Describe alternatives you've considered**~~

~~**Additional context**~~

**Comment by fancyapps** [comment]
Hi,

You can put any HTML code in the caption, so, if you can put your content on the page, it would work inside caption, too.

**Comment by rodrigoalcarazdelaosa** [comment]
The problem is that these mathematical expressions are being rendered by [MathJax](https://www.mathjax.org), and they are working fine in the caption shown in the body of the text, like here (look at the temperatures, 3ºC and 113ºC):
![image](https://user-images.githubusercontent.com/9049533/83521973-48d88380-a4e0-11ea-944c-78910cab2474.png)
, but when zooming in the figure (lightbox="true"), I get this:
![image](https://user-images.githubusercontent.com/9049533/83522120-7f160300-a4e0-11ea-9aed-53a86ccda6e9.png)
The live version of this is [here](https://rodrigoalcarazdelaosa.me/apuntes-2eso-3eso/materia/#cambios-de-estado).

So [MathJax](https://www.mathjax.org) is working in the figure caption in the body but not when zooming in.

Thanks!

**Comment by fancyapps** [comment]
You see, in your HTML code you have this:

`data-caption="La sustancia comienza en estado sólido, calentándose hasta los $3\thinspace^\circ\mathrm C$, su <strong>temperatura de fusión</strong>. Una vez se ha fundido completamente, sigue calentándose, en estado líquido, hasta los $113\thinspace^\circ\mathrm C$, su <strong>temperatura de ebullición</strong>. A partir de esa temperatura la sustancia se encuentra en estado gaseoso y puede seguir calentándose <em>indefinidamente</em> (a partir de una cierta temperatura, la materia pasa a otro estado conocido como <em>plasma</em> —gas ionizado)."`

And that is what fancybox displays, as expected.

**Comment by fancyapps** [comment]
I would suggest to set caption using one of the samples from here - https://fancyapps.com/fancybox/3/docs/#faq-2 (maybe the last one would be best option for you)

**Comment by rodrigoalcarazdelaosa** [comment]
Thanks. I'm using the [Academic theme](https://sourcethemes.com/academic/docs/writing-markdown-latex/#images) for [Hugo](https://gohugo.io) and the images are included using [this shortcode](https://github.com/gcushen/hugo-academic/blob/master/layouts/shortcodes/figure.html).

From now on I will try to avoid MathJax expressions in figure captions, until I figure out how to properly include them.

Thanks again for your time!
