### ISSUE TITLE
Image with soundtrack not working on an iPhone

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2474]
Sometimes I play a sound in the lightbox like in [this example](https://www.andrewolff.nl/FotoSerie/Vechtdal/Eerde-Sahara/index.htm#S-20).

I do this with code like this:

`<a data-fancybox="S" href=
 ""  data-src="Kikkerrs_16sec.mp3" data-type="video" data-width="1920" data-height="663" 
data-caption= 'Het meertje achter de Besthmener ven'>
<img src="slides/200527-111406_Eerde-Sahara-Pano.jpg"   width="352" height="160" alt="" title=" Het meertje achter de Besthmener ven" />
</a>`

See also the codepen: https://codepen.io/acwolff/pen/GRRoNod

This works fine on a PC and on an iPad, but on an iPhone the screen is black while the track plays.

So my questions are:

1. What should I do to remove that black screen while the track is playing, so that you see the image as is displayed on a PC or iPad.
2. If there is no solution to correct this, how can I remove/skip the track on an iPhone? Is there an event where this can be done?

**Comment by fancyapps** [comment]
Hi,

Fancybox can display any HTML content, the rest is to you and your browser.
