### ISSUE TITLE
Images won't stop stretching. I tried looking in documents, asking on stackoverflow and changing CSS.

### ISSUE THREAD

**Issue by NaZzAtAzEr** [fancyapps/fancybox#2475]
My portrait images stay stretched across the width of the screen.
![image](https://user-images.githubusercontent.com/22560082/84419594-be470100-ac10-11ea-9fcf-2c4c41fde0d2.png)

```
<?php 
// Include database configuration file  
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
// Retrieve images from the database 
$query = $DB->query("SELECT * FROM images ORDER BY uploaded_date DESC"); 
	if(!$query) {
		trigger_error("Invalid query: " . $DB->error);
	}
if($query->num_rows > 0){ 
	while($row = $query->fetch_assoc()){ 
		$imageURL = '../phpgallery/'.$row["path"]; 
?>
	<a href="<?php echo $imageURL; ?>" data-fancybox="gallery" data-caption="<?php echo $row["title"]; ?>" style="background-size:contain">
	<img src="<?php echo $imageURL; ?>" alt="" style="background-size:contain"/>
</a>
<?php } 
} ?>
```
This is my code for displaying the images. The slideshow works at the correct size. I am trying not to do two file sizes for the same image, as the file size is already small

Sorry if this is not the correct place, but I'm losing the plot with this issue 😂

**Comment by fancyapps** [comment]
Hi,

Sorry, but it is not possible to give a proper answer without seeing a live demo.
