### ISSUE TITLE
Hide title tags on anchors (hover)

### ISSUE THREAD

**Issue by amichel86** [fancyapps/fancybox#2476]
How do I hide title tags (Next, Prev, Close) on the different buttons when hovering them? My site is multilingual (on Wordpress) and I don't want to go through the hassle of changing that :)

Thanks!

**Comment by fancyapps** [comment]
Hi,

You can change language using `lang` option and you can use `i18n` to modify or add new values to translations, see defaults here - https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L359
