### ISSUE TITLE
Replace infobar with post title

### ISSUE THREAD

**Issue by oshyne** [fancyapps/fancybox#2478]
Hello Janis and the entire fancybox community,

I need help in replacing the infobar area of the gallery with the post title from my post.

So far, i have overwritten the infobar using "baseTpl:" leaving it empty to accept
the post title but it is not displaying the content passed to it using jquery.

Below is the code i am using:

```
$('[data-fancybox^="gallery"]').fancybox({
    beforeShow : function() {
	$('.fancybox-infobar').find('.gallery-open-title').html();
   },
});
```
The html to load the title from:
```
<div class="gallery-open-title d-none">
    <?php echo the_title() ?>
</div>
```

I will really appreciate every assistance in fixing it or recommendation
for a solution.

Thanks

**Comment by fancyapps** [comment]
Hi,

1) Your code `$('.fancybox-infobar').find('.gallery-open-title').html()` would do nothing, you are missing smth there.

2) A live demo (Codepen/JSFIddle/etc) would help to give a proper answer.

**Comment by oshyne** [comment]
Hello Janis,

Thanks for the quick reply.

I'm sorry for responding late.

This is the codepen link [https://codepen.io/oshyne/pen/WNroNgE](url)
I hope that helps because the website runs on wordpress and it's still locally developed.

The codes in the pen are the PHP and JS codes.

I really appreciate your assistance.

Thanks

**Comment by fancyapps** [comment]
I just do not understand why do you show PHP code, it is totally irrelevant and makes impossible to work with your code. Sorry, but your codepen is useless, please, share your working HTML code (e.g., output of PHP).

Anyway, it is easy to accomplish your request using callbacks, simply add some new attribute to links like `data-title="smth"`, then use callback to read that attribute (using `current.opts.$orig.data(`title`)` and to set it somewhere of your choice.

**Comment by oshyne** [comment]
Hello Janis,

I really appreciate your help and concern so far!

I'm sorry about the PHP code dump.

I just updated the pen with my actual HTML code, I wish
you help me take a look again.

[Link to updated pen](https://codepen.io/oshyne/pen/WNroNgE)

Thanks so much.

**Comment by fancyapps** [comment]
It would be as simple as this:

```JS
beforeShow : function(instace, current) {
    var title = current.opts.$orig.find('h3').text();
    instace.$refs.infobar.html(title);
}
```

**Comment by oshyne** [comment]
Thanks so much Janis.

It worked.
