### ISSUE TITLE
the key was accidentally deleted

### ISSUE THREAD

**Issue by darienko** [fancyapps/fancybox#2482]
How do I ...
Good afternoon. I apologize for contacting in this way. But I did not find another way. The letter with the purchased license was accidentally deleted. Can you send the letter again? Thanks maksdarienko@gmail.com. P / s, can I switch from a license for one project to an extended one? paying a difference in cost. Many paid improvements practice this . 
How can I get to my personal account?

**Comment by fancyapps** [comment]
Hi,

I have contacted you via email. Thanks.
