### ISSUE TITLE
How to use with sticky navbar

### ISSUE THREAD

**Issue by WROIATE** [fancyapps/fancybox#2483]
Hi,
How do I use fancybox with bootstrap4 sticky navbar?
I use bootstrap4 `sticky-top` to make a sticky navbar, but when I use it with fancybox `zoom` animation effect, the close animation will have some problem, the image cover the sticky navbar just like this:

![problem](https://user-images.githubusercontent.com/44677306/85943084-4a229200-b960-11ea-908c-89406c2a1f3c.gif)
What can I do?

**Comment by fancyapps** [comment]
Hi,

Hmm, but what do you propose? To me, it looks like everything works as expected - 1) zoom animation works fine; 2) sticky navbar .. is sticky. 

I guess it would look better if navbar would fade-in while closing. Maybe try to hide navbar when body has `fancybox-active` class name and give opacity transition. Try to experiment by yourself.

**Comment by WROIATE** [comment]
> Hi,
> 
> Hmm, but what do you propose? To me, it looks like everything works as expected - 1) zoom animation works fine; 2) sticky navbar .. is sticky.
> 
> I guess it would look better if navbar would fade-in while closing. Maybe try to hide navbar when body has `fancybox-active` class name and give opacity transition. Try to experiment by yourself.

Yeah, I have done it, thanks
