### ISSUE TITLE
JQuery Easing 

### ISSUE THREAD

**Issue by JimDutton** [fancyapps/fancybox#2485]
Am I correct in thinking the options section at the end of the .js file in version 2 is not in the v. 3 file?  I have been using the JQuery easing options for transitions and don't see any way to incorporate them in v. 3.  If I've missed that info, please point me in the right direction. Thanks.

**Comment by fancyapps** [comment]
Hi,

v3 and v2 are completely different and v3 uces CSS to create animations, see https://github.com/fancyapps/fancybox/blob/master/src/css/core.css#L521
