### ISSUE TITLE
Is it possible to add the function of zooming pictures with the mouse wheel:)

### ISSUE THREAD

**Issue by shilohooo** [fancyapps/fancybox#2487]
I want to zoom my picture by mouse wheel....

**Comment by fancyapps** [comment]
Hi,

There is already a feature-request for that and this will be implemented in v4, you can preview it here - https://fancyapps.com/next/

**Comment by shilohooo** [comment]
thank you very much!
but the version of fancybox I use now is 2.1.5,Can this zoom function be integrated into the previous version?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jānis Skarnelis"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午3:22
收件人:&nbsp;"fancyapps/fancybox"<fancybox@noreply.github.com&gt;;
抄送:&nbsp;"李小雷"<2544729685@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fancyapps/fancybox] Is it possible to add the function of zooming pictures with the mouse wheel:) (#2487)





 
Closed #2487.
