### ISSUE TITLE
Flicker on load of modal box from fancy box using safari and chrome on iOS or iPadOS

### ISSUE THREAD

**Issue by disappeared1** [fancyapps/fancybox#2489]
How can I prevent this flicker from happening with safari and chrome on iPados and ios. I don't see it happening on the demo page. 

Here is a video showing what's happening. (it happens on 1st and 6th and 7th image I click on in the video below)
[https://www.youtube.com/watch?v=WHW1e_AZpyA](https://www.youtube.com/watch?v=WHW1e_AZpyA)

[Here is a jsbin snippet (upper right gives you source).](https://jsbin.com/waneton/5)

**Comment by acwolff** [comment]
Apparantly it dos not happen with images without a cqaption.

**Comment by disappeared1** [comment]
> Apparantly it does not happen with images without a caption.

Actually it happens with or without caption, I just tested this.

**Comment by disappeared1** [comment]
I was able to fix this by just recreating my own css animation and triggering it on the afterShow method. I have no idea why I had to do this.

**Comment by acwolff** [comment]
@disappeared1 please give more detailed code how you solved this.

**Comment by disappeared1** [comment]
### This is how I just rewrote it and it's working now. No flicker on ios chrome or safari devices 

**Added the following css to create the new animation and set the omg to opacity 0**

	.fancybox-slide img { opacity: 0; }

	@keyframes myfancyboxzoom {
		0% {
			opacity: 0;
			transform: scale(0.3);
		}

		to {
			opacity: 1;
			transform: scale(1);
		}
	}
**On the AfterShow method, I set opacity to 1 and set and start the animation**

	afterShow: function(instance, slide) {
		setTimeout(function() {
			$('.fancybox-slide img').css('opacity', 1);
			$('.fancybox-slide img').css({			   
				'animation-name' : 'myfancyboxzoom',
				'animation-duration' : '0.3s',
				'animation-fill-mode' : 'both',
				'animation-timing-function': 'ease-in-out'
			});
		});
	}

**Comment by joseantgv** [comment]
No update on this?

**Comment by disappeared1** [comment]
I guess I forgot to close this. Will close it now. 

See my last comment for a temporary resolution. I have no idea if they fixed this in the latest release.
