### ISSUE TITLE
Loosing position when zoom <1.0

### ISSUE THREAD

**Issue by svangansbeke** [fancyapps/fancyBox#249]
Fancybox (2.0.6 16/04/2012) looses its center position when I add the  zoom css property.

body {
   zoom: 0.9;
   -moz-transform: scale(0.9);
   -webkit-transform: scale(0.9); 
}

Once the statement is added and you zoom out with your browser the fancybox looses its centerposition when you go below 1.0

Regards
Stefan

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
