### ISSUE TITLE
Big images are looking warped in Chrome.

### ISSUE THREAD

**Issue by asavchuk** [fancyapps/fancybox#2491]
According to closed [issue](https://github.com/fancyapps/fancybox/issues/2472) I would add that big images are looking warped when thumbnail clicked in Chrome. And againe it looks great in Firefox. 
There is definitely sometning wrong in this library when it comes to Chrome browser.

**Comment by fancyapps** [comment]
Hi,

Maybe your issue will disappear after upgrading to v4 (you can preview it here - https://fancyapps.com/next/) but there is nothing I can do for v3.
