### ISSUE TITLE
Image behavior with a start gallery button

### ISSUE THREAD

**Issue by vonhaupt01** [fancyapps/fancybox#2495]
Not sure how I can do this. What I want are the images show on a page and when the user clicks on the image, they are taken to the image details page. There will be a button on the page to start the gallery which will loop through all the images on the page. The images are loaded from a database, so the page is dynamic. I was think of having the details image be one link and same image a gallery link that is hidden. 

This webpage shows that behavior: https://www.vonhaupt.com/p83979999

All help will be appreciated...

**Comment by fancyapps** [comment]
And where is the actual question/issue?

**Comment by vonhaupt01** [comment]
Wow, looks like I should look somewhere else. It was evident that I described what I was trying to do and the question was HOW? Oh well, you just close it instead.... great business..

**Comment by fancyapps** [comment]
But what did you expect? Unless I missed something, you described how fancybox works out of the box.

**Comment by vonhaupt01** [comment]
No I didn't. Out of the bx it works great but I need to be able to click on a image and go to a pricing page. Still want a gallery of all the images which they may launch with a button (or some other method). Have not found any examples of that.

**Comment by fancyapps** [comment]
You could 1) create a custom button in the toolbar; 2) Add custom link in caption area; 3) Customize click event using `clickContent` option. Keep in mind that images are zoomed in/out by default and if you change this option, you will loose this functionality.

**Comment by vonhaupt01** [comment]
I looked at this, https://codepen.io/fancyapps/pen/WjVXyx?editors=1000, and it's what I'm going to try and do. On the bottom you start the gallery with an image, I would want a button. The images shown on the page would be clickable to details and the hidden ones would be shown in the gallery popup view. So just need to start it with a button and I may have figured it out.

BTW, this is a paid license

**Comment by vonhaupt01** [comment]
Any idea why this doesn’t work?

 

<button class="open-gallery">Open gallery</button> 

 

<a href="~/Content/TestImages/2-nature.jpg" data-fancybox="gallery" data-caption="Caption #1">

            <img src="~/Content/TestImages/2-nature.jpg" alt="" />

</a>

 

<a href="~/Content/TestImages/4-nature.jpg" data-fancybox="gallery" data-caption="Caption #2">

            <img src="~/Content/TestImages/4-nature.jpg" alt="" />

</a>

 

 

<script type="text/javascript">

 

$(document).ready(function () {

        $('button.open-gallery').click(function () {

            $('a[data-fancybox="gallery"]').first().trigger("click");

        });

    });

 

$('[data-fancybox="gallery"]').fancybox({

        // Options will go here

        protect: true,

        caption: function (instance, item) {

            var caption = $(this).data('caption') || '';

 

            if (item.type === 'image') {

                caption = (caption.length ? caption + '<br />' : '') + '© vonHaupt Photography';

            }

 

            return caption;

        }

    });

 

</script>

 

 

David M Haupt

Creative Vision Photography Workshops, LLC

 <http://www.creativevisionpw.com> www.creativevisionpw.com
