### ISSUE TITLE
data-width and height is not working

### ISSUE THREAD

**Issue by jurgen-74** [fancyapps/fancybox#2502]
Hello friends,

I need to make a transition from an old plugin to Fancybox.
I can't seem to make data-width & height working properly.
I does work when I am still logged in on my wordpress. As soon as I logout it stops working.
Any ideas?
https://www.apologeet.nl/test/

Please tell me if you need more info.

Blessings,
Jurgen

**Comment by fancyapps** [comment]
Hi,

`data-width` and `data-height` attributes are for images only, you can use CSS for iframed content (like video), see docs for samples.

**Comment by jurgen-74** [comment]
There you go, a new day and something new to learn :) Thanks

**Comment by masterofthesith** [comment]
add data-preload="false" then data-width and data-height will start to work.

**Comment by jurgen-74** [comment]
Thank you @masterofthesith 

`<a data-fancybox data-preload="false" data-width="1600" data-height="900" href="https://youtu.be/RcCJBmgFDCk?hd=1&fs=1&autoplay=1">Test</a>`
Still does not work :(

**Comment by masterofthesith** [comment]
> Thank you @masterofthesith
> 
> `<a data-fancybox data-preload="false" data-width="1600" data-height="900" href="https://youtu.be/RcCJBmgFDCk?hd=1&fs=1&autoplay=1">Test</a>`
> Still does not work :(

It is working for me can i see your main fancybox function pls

**Comment by jurgen-74** [comment]
I installed the [Easy FancyBox](https://status301.net/wordpress-plugins/easy-fancybox/) plugin.
Is that what you mean?
https://www.apologeet.nl/en/test-fancy/

**Comment by masterofthesith** [comment]
> I installed the [Easy FancyBox](https://status301.net/wordpress-plugins/easy-fancybox/) plugin.
> Is that what you mean?
> https://www.apologeet.nl/en/test-fancy/

No i mean where is your fancybox fucntion like $("xxx").fancybox({args});

**Comment by jurgen-74** [comment]
As far as I know I didn't have to write a function like that myself. I just installed the plugin. However, in the source of my website I found this:
`<script type='text/javascript'>
var fb_timeout, fb_opts={'overlayShow':true,'hideOnOverlayClick':true,'overlayOpacity':0.8,'overlayColor':'#000','showCloseButton':true,'padding':5,'margin':20,'centerOnScroll':false,'enableEscapeButton':true,'autoScale':true,'speedIn':600,'speedOut':400 };
if(typeof easy_fancybox_handler==='undefined'){
var easy_fancybox_handler=function(){
jQuery('.nofancybox,a.wp-block-file__button,a.pin-it-button,a[href*="pinterest.com/pin/create"],a[href*="facebook.com/share"],a[href*="twitter.com/share"]').addClass('nolightbox');
/* IMG */
var fb_IMG_select='a[href*=".jpg"]:not(.nolightbox,li.nolightbox>a),area[href*=".jpg"]:not(.nolightbox),a[href*=".jpeg"]:not(.nolightbox,li.nolightbox>a),area[href*=".jpeg"]:not(.nolightbox),a[href*=".png"]:not(.nolightbox,li.nolightbox>a),area[href*=".png"]:not(.nolightbox),a[href*=".webp"]:not(.nolightbox,li.nolightbox>a),area[href*=".webp"]:not(.nolightbox)';
jQuery(fb_IMG_select).addClass('fancybox image');
var fb_IMG_sections=jQuery('.gallery,.wp-block-gallery,.tiled-gallery,.wp-block-jetpack-tiled-gallery');
fb_IMG_sections.each(function(){jQuery(this).find(fb_IMG_select).attr('rel','gallery-'+fb_IMG_sections.index(this));});
jQuery('a.fancybox,area.fancybox,li.fancybox a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'transitionIn':'elastic','easingIn':'easeOutBack','transitionOut':'elastic','easingOut':'easeInBack','opacity':false,'hideOnContentClick':false,'titleShow':true,'titlePosition':'over','titleFromAlt':true,'showNavArrows':true,'enableKeyboardNav':true,'cyclic':false}))});
/* Inline */
jQuery('a.fancybox-inline,area.fancybox-inline,li.fancybox-inline a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'inline','autoDimensions':true,'scrolling':'no','easingIn':'easeOutBack','easingOut':'easeInBack','opacity':false,'hideOnContentClick':false,'titleShow':false}))});
/* PDF */
jQuery('a[href*=".pdf"],area[href*=".pdf"],a[href*=".PDF"],area[href*=".PDF"]').not('.nolightbox,li.nolightbox>a').addClass('fancybox-pdf');
jQuery('a.fancybox-pdf,area.fancybox-pdf,li.fancybox-pdf a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'iframe','width':'90%','height':'90%','padding':10,'titleShow':false,'titlePosition':'float','titleFromAlt':true,'autoDimensions':false,'scrolling':'no'}))});
/* SWF */
jQuery('a[href*=".swf"],area[href*=".swf"],a[href*=".SWF"],area[href*=".SWF"]').not('.nolightbox,li.nolightbox>a').addClass('fancybox-swf');
jQuery('a.fancybox-swf,area.fancybox-swf,li.fancybox-swf a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'swf','width':680,'height':495,'titleShow':false,'titlePosition':'float','titleFromAlt':true,'swf':{'wmode':'opaque','allowfullscreen':true}}))});
/* SVG */
jQuery('a[href*=".svg"],area[href*=".svg"],a[href*=".SVG"],area[href*=".SVG"]').not('.nolightbox,li.nolightbox>a').addClass('fancybox-svg');
jQuery('a.fancybox-svg,area.fancybox-svg,li.fancybox-svg a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'svg','width':680,'height':495,'titleShow':false,'titlePosition':'float','titleFromAlt':true,'svg':{'wmode':'opaque','allowfullscreen':true}}))});
/* YouTube */
jQuery('a[href*="youtu.be/"],area[href*="youtu.be/"],a[href*="youtube.com/"],area[href*="youtube.com/"]').filter(function(){return this.href.match(/\/(?:youtu\.be|watch\?|embed\/)/);}).not('.nolightbox,li.nolightbox>a').addClass('fancybox-youtube');
jQuery('a.fancybox-youtube,area.fancybox-youtube,li.fancybox-youtube a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'iframe','width':640,'height':360,'keepRatio':1,'titleShow':true,'titlePosition':'float','titleFromAlt':true,'onStart':function(a,i,o){var splitOn=a[i].href.indexOf("?");var urlParms=(splitOn>-1)?a[i].href.substring(splitOn):"";o.allowfullscreen=(urlParms.indexOf("fs=0")>-1)?false:true;o.href=a[i].href.replace(/https?:\/\/(?:www\.)?youtu(?:\.be\/([^\?]+)\??|be\.com\/watch\?(.*(?=v=))v=([^&]+))(.*)/gi,"https://www.youtube.com/embed/$1$3?$2$4&autoplay=1");}}))});
/* Vimeo */
jQuery('a[href*="vimeo.com/"],area[href*="vimeo.com/"]').filter(function(){return this.href.match(/\/(?:[0-9]+|video\/)/);}).not('.nolightbox,li.nolightbox>a').addClass('fancybox-vimeo');
jQuery('a.fancybox-vimeo,area.fancybox-vimeo,li.fancybox-vimeo a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'iframe','width':500,'height':281,'keepRatio':1,'titleShow':true,'titlePosition':'float','titleFromAlt':true,'onStart':function(a,i,o){var splitOn=a[i].href.indexOf("?");var urlParms=(splitOn>-1)?a[i].href.substring(splitOn):"";o.allowfullscreen=(urlParms.indexOf("fullscreen=0")>-1)?false:true;o.href=a[i].href.replace(/https?:\/\/(?:www\.)?vimeo\.com\/([0-9]+)\??(.*)/gi,"https://player.vimeo.com/video/$1?$2&autoplay=1");}}))});
/* Dailymotion */
jQuery('a[href*="dailymotion.com/"],area[href*="dailymotion.com/"]').filter(function(){return this.href.match(/\/video\//);}).not('.nolightbox,li.nolightbox>a').addClass('fancybox-dailymotion');
jQuery('a.fancybox-dailymotion,area.fancybox-dailymotion,li.fancybox-dailymotion a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'iframe','width':560,'height':315,'keepRatio':1,'titleShow':true,'titlePosition':'float','titleFromAlt':true,'onStart':function(a,i,o){var splitOn=a[i].href.indexOf("?");var urlParms=(splitOn>-1)?a[i].href.substring(splitOn):"";o.allowfullscreen=(urlParms.indexOf("fullscreen=0")>-1)?false:true;o.href=a[i].href.replace(/^https?:\/\/(?:www\.)?dailymotion.com\/video\/([^\?]+)(.*)/gi,"https://www.dailymotion.com/embed/video/$1?$2&autoPlay=1");}}))});
/* iFrame */
jQuery('a.fancybox-iframe,area.fancybox-iframe,li.fancybox-iframe a').each(function(){jQuery(this).fancybox(jQuery.extend({},fb_opts,{'type':'iframe','width':'70%','height':'90%','titleShow':false,'titlePosition':'float','titleFromAlt':true,'allowfullscreen':false}))});};
jQuery('a.fancybox-close').on('click',function(e){e.preventDefault();jQuery.fancybox.close()});
};
var easy_fancybox_auto=function(){setTimeout(function(){jQuery('#fancybox-auto').trigger('click')},1000);};
jQuery(easy_fancybox_handler);jQuery(document).on('post-load',easy_fancybox_handler);
jQuery(easy_fancybox_auto);
</script>`

**Comment by masterofthesith** [comment]
In youtube options there is a setting name "'keepRatio':1". Change it to 'keepRatio': 0 and try again.

**Comment by jurgen-74** [comment]
Thank you, I've tried it, but it did not work. I had to change it in easyfancybox-options.php in my plugin-editor. It did send it to the page but did not make a difference.
