### ISSUE TITLE
Using data-fancybox changes url in browser.

### ISSUE THREAD

**Issue by precision1980** [fancyapps/fancybox#2505]
When I run the following code and use data-fancybox="gallery", it will change the URL in my browser causing and issue. I am using an ajax based website that loads on the page on #/page to a container.  If I use just data-fancybox, there's no issue but the user has to click on each picture.

```
            $('[data-fancybox="images" data-type="iframe"]').fancybox({
                toolbar  : false,
                smallBtn : true,
                iframe : {
                    preload : false
                }
            });
```

**Comment by fancyapps** [comment]
Hi,

You can disable that feature by setting `hash:false`
