### ISSUE TITLE
Caption as plain HTML like in Bootstrap Carousel

### ISSUE THREAD

**Issue by baszero** [fancyapps/fancybox#2521]
Why is Fancybox 3 still using this HTML caption an attribute?
It would be much simpler if Fancybox would accept any ID referencing an HTML `div` on the page where it grabs the HTML content instead of having to encode it.

Any plans to implement this?

**Comment by fancyapps** [comment]
Hi,

You have great control over the caption area, seee https://fancyapps.com/fancybox/3/docs/#faq-2 for some samples.

**Comment by baszero** [comment]
Thanks for the hint, however I was looking for a possibility to tell Fancybox to use hidden HTML divs to use as caption, it's not really elegant and not a recommended way to program HTML within Javascript...
