### ISSUE TITLE
Make it possible to hide the animated red line that appears when you play a side show

### ISSUE THREAD

**Issue by reidsci** [fancyapps/fancybox#2527]
**Is your feature request related to a problem? Please describe.**
An animated red line appears moving at the top of the browser (or screen when in full screen) when the slide show is playing. I find it distracting me from the images that are being displayed.

**Describe the solution you'd like**
A CSS style or JavaScript option that could be set to hide or eliminate that animated red line.

**Comment by acwolff** [comment]
Just add at the end of your css file:

      .fancybox-progress {
        height: 0px; 
      }

**Comment by reidsci** [comment]
That's great, thank you!
