### ISSUE TITLE
How to use thumbs option as data-thumbs

### ISSUE THREAD

**Issue by Niloys7** [fancyapps/fancybox#2534]
How to use thumbs options as data-thumbs?
options: https://prnt.sc/vjgrjq 
if I add value like `data-thumbs=["autoStart:true"]` than it's not open the lightbox thumbs on click the image. and getting this error https://prnt.sc/vjgsxp

**Comment by fancyapps** [comment]
Hi,

That syntax is not supported. I would suggest to simply change defaults, like so (replace with your options/values):

`$.fancybox.defaults.animationEffect = "fade";`
