### ISSUE TITLE
Bug if gallery-name (data-fancybox) is equal to page object with ID and external link to that ID

### ISSUE THREAD

**Issue by ThiloL** [fancyapps/fancybox#2537]
**Describe the bug**
If there is an in page element with ID which is the same as the name (data-fancybox) of an gallery, there is an issue if I link to that page with ...images.php#InsideID.

**Steps to reproduce the behavior**
Create an webpage (images.php) with an fancy box gallery who's data-fancybox ist set to i.e. sample.
Now place an element on that page `<h3 id="sample">Text</h3>`
Now try to navigate to that page with .../images.php#sample (to jump to that h3 element).

**Expected behavior**
Webpage should open and jump (scroll) to the h3 element. But webpage opens and immediatly opens the diashow.

**Screenshots**

**Desktop (please complete the following information):**
latest Chrome browser an windows

**Smartphone (please complete the following information):**
PC

**Additional context**

**Comment by mjcampagna** [comment]
I believe this is a feature, not a bug. It allows browser navigation into a slideshow.

And your workaround is quite simple: use a different name for the data-fancybox gallery.

**Comment by ThiloL** [comment]
One way to configure or disable this would be good.
