### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by thamsrang** [fancyapps/fancybox#2548]
Hi,

I am getting below error
```
jquery.fancybox.js:2231 Uncaught TypeError: $(...).appendTo(...).hide(...).fadeIn is not a function
    at FancyBox.showLoading (jquery.fancybox.js:2231)
    at jquery.fancybox.js:1787
```

```html
   <a href="https://s.com/img1.jpeg" data-fancybox="photos-{{../id}}">
      <img id="photos-{{../id}}-{{@index}}" class="d-block img-fluid" height="200" width="150" src="https://s.com/img1.jpeg" alt="First slide">
   </a>
```
No other configuration or no callback added for fancybox event.

Except
```javascript
$.fancybox.defaults.hash = false;
```

Can you help me fix this ?

**Comment by fancyapps** [comment]
Hi,

Maybe you are using limited version of jQuery, it is not possible to tell without seeing your page.

**Comment by thamsrang** [comment]
I am using `jQuery v3.5.1`. I am using latest one than version mentioned in documentation.

**Comment by fancyapps** [comment]
Like I said, it is not possible to give any proper answer without seeing your live page.

**Comment by thamsrang** [comment]
OK. Thanks.
I have fixed after debugging.
I have used limited feature jQuery version. This is reason for error.
Now I have enabled full version. Works fine. 

Again thanks for kind and quick reply.
