### ISSUE TITLE
inline issues with swiper js

### ISSUE THREAD

**Issue by mttindustries** [fancyapps/fancybox#2549]
Hi,
I'm trying to use an inline fancy-box element and that inline element for an Instagram feed, and it uses fancybox to pop up with the image in one column and the description in the other. And if the post has multiple images then it uses a slide/swiper, at the moment I'm using swiper js and the problem I have is when the fancybox shows up the swiper's navigation in the box doesn't work.  When clicking on the arrows they don't show up the next slide. It does however work across the rest of the website fine just not when using with fancybox. I've tried disabling touch and backFocus : false but still doesn't work.

**Comment by fancyapps** [comment]
Hi,

To deal with issues like this, next generation of this project will contain separate fancybox and carousel components and you will be able to combine them with ease.
