### ISSUE TITLE
Scrollbar in caption with Chrome browser

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2550]
If you open  [this page](https://andrewolff.jalbum.net/FB_MasonryF/#S-1) on a Windows 10 PC, you see in the lower right corner an unnecessary scrollbar.
I see this only with the Chrome browser, it is OK with Firefox and Edge.

I can remove that scrollbar by changing the text 'auto' by 'hidden' in the next fancyBox css code:

    .fancybox-caption__body {
        max-height: 50vh;
        overflow: auto;
        pointer-events: all;
    }

or by lowering the font-size from 20px to 17px or lower.

So my question is:

What problems may I expect if I change overloaw in hidden?

Or is there another way to prevent thia?

**Comment by fancyapps** [comment]
I do not see any issue here.

**Comment by acwolff** [comment]
@fancyapps thanks for your reply.

I see on my Windows 10 system with the chrome browser a small scrollbar:
![scrollBar](https://user-images.githubusercontent.com/8150784/108678824-e9962580-74eb-11eb-9340-b9bdf8ad6f7d.png)
I can prevent it dynamically with this code:

	beforeLoad: function(instance, current) {
            		if (PC) {
               		    if (Chrome && !descriptionInSidePanel) {
                   		$('.fancybox-caption__body').css({ 'overflow': 'hidden' });
                	    }
            		}
as you see [here](https://andrewolff.jalbum.net/FB_Masonry/#S-1), but I don't like this type of solutions!
