### ISSUE TITLE
iframe greather than 1050px?

### ISSUE THREAD

**Issue by wolkenloseswetter** [fancyapps/fancybox#2554]
Hi,

I tried successfully changing the width of the iframe. 

```
.fancybox-slide--iframe .fancybox-content {
    width  : 800px;
    height : 600px;
}
```
But it looks like, it only works for widths smaller than 1050px. Unfortunately, a larger iframe doesn't work. 

An example:

```
.fancybox-slide--iframe .fancybox-content {
    width  : 1300px;
    height : 600px;
}
```
Result: The iframe is only 1050px wide.

Is there a limitation? I didn't find anything in the code.

Thanks!

**Comment by fancyapps** [comment]
Hi,

No, there are no limitations. Seeing a live page or demo would help to identify your issue and give a proper answer.

**Comment by wolkenloseswetter** [comment]
Hi, thank you for your answer. I will searching the issue in my code.
