### ISSUE TITLE
Deformed image if soundtrack is used with Chrome browser

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2556]
I made some kind of Jukebox, see [this album](https://andrewolff.jalbum.net/Jukebox/). This works fine on an iPad and on a Windows PC with Firefox, but the image in the light-box is deformed if the latest Chrome or Edge browser is used.

Any idea how to solve this?

**Comment by fancyapps** [comment]
Your image in the video has different aspect ratio that you have provided.

**Comment by acwolff** [comment]
@fancyapps thanks for your reply!

I am not aware that that I use  the wrong Aspect ratio, take the first image https://andrewolff.jalbum.net/Jukebox/slides/190406-152547_OnzeTuin.jpg that is an image of size 1440x1080 and I use the next code:


    <a data-fancybox="S" href= ""  data-src="bensound-brazilsamba.mp3" data-type="video"
    data-width="1440" data-height="1080" id="0" data-caption= '<p>&#39;Brazil samba&#39;</p>'>
    <div class="box" style = "width:107px">
    <img src="slides/190406-152547_OnzeTuin.jpg" width="107" height="80" alt="190406-152547_OnzeTuin" title="1: 190406-152547_OnzeTuin<br>"  /><br>
    <div class="thumbText"><strong>'Brazil samba'</strong><br></div>
    </div>
    </a>

And remember I have this problem only with Chrome on a PC, it is OK with Firefox and with Safari on an iPad.

But I am sure I copied this code from one of your codepens, but I can't find it back. Do you have sill a codepen example which implements this?
