### ISSUE TITLE
when I click close the behind bootstrap modal also close

### ISSUE THREAD

**Issue by hooman-mirghasemi** [fancyapps/fancybox#2557]
I have a bootstrap modal inside of this modal i have some small images , by clicking on this images fancybox open. when i click on fancy box close button. my behind modal also closed!

$().fancybox({
            selector : '.modal-body a.fancybox',
            thumbs   : {
                autoStart : false,
            },
        });

**Comment by JasonXDDD** [comment]
+1, I have same issue. please give me any solution ...

**Comment by fancyapps** [comment]
Hi,

Sorry, v3 is discontinued and is no longer supported. Please, upgrade to the latest - https://github.com/fancyapps/ui
