### ISSUE TITLE
Video gallery and adding a poster image on video

### ISSUE THREAD

**Issue by robbiegod** [fancyapps/fancybox#2560]
How do I get the poster image to appear of the video to appear in the html5 video tag when my video thumbnail is clicked?

I have a carousel on my site that has about 8 videos in it.

That looks like this:

```
<a rel="gallery-videos" 
      href="javascript: return false;" 
      class="gallery-lighbox" 
      data-fancybox="html5-video" 
      data-width="1280" 
      data-height="720"
      data-src="<?= $gallery_video_url ?>"
      data-poster="<?= $custom_media_image_large ?>"
      data-media-type="video">

        <img src="<?php echo $custom_media_image_thumbnail; ?>" />
        <div class="show-info">
          <div class="text">
            <div class="title-text">
              <p class="name"><?php echo $gallery_item_title; ?></p>
            </div>
          </div>
        </div>
    </a>
```

I'm setting up a fancybox in my javascript file that looks like this:

```
jQuery('.gallery-lighbox').fancybox({
  type: 'video',
  format: "video/mp4",
  // For HTML5 video only
  video: {
    tpl:
      '<video class="fancybox-video" controls controlsList="nodownload" poster="{{poster}}">' +
      '<source src="{{src}}" type="{{format}}" />' +
      'Sorry, your browser doesn\'t support embedded videos, <a href="{{src}}">download</a> and watch with your favorite video player!' +
      "</video>",
    format: "", // custom video format
    autoStart: false
  },
  beforeShow : function( instance, current ) {

    console.log(instance);

    var current_poster = current.opts.video;
    console.log(current_poster.tpl);
    // jQuery(".fancybox-video").attr("poster", current_poster);

  }
});
```

I'm able to use the (instance, current) to get the values inside of the current items, but i am not sure how to manipulate the video template (tpl) code so that i can add the poster image and then have it appear when the thumbnail is clicked.  I'm not sure why it is not accepting data-poster value I already have set in the HTML.

I am using Fancybox v3.4.1 as that is what is included with FV Flowplayer.

**Comment by fancyapps** [comment]
Hi,

Have you tried using `data-thumb` attribute (instead of `data-poster`)? Because thumbnail image is used for the poster.

**Comment by robbiegod** [comment]
I didn't try data-thumb as the poster image is the attribute name on the video that displays the placeholder image.

I don't see data-thumb anywhere in the documentation. I ended up finding a different solution from another thread.

I think you should change it so it uses data-poster value to match what is in the <video> tag.  Also, data-thumb probably holds a small sized image since its the thumbnail afterall.  My videos are 1280x720 and my thumbnails are 320width.  I have a poster image already made so I suppose I could load the poster image into the data-thumb value, but then won't that show and load the big thumbnail in the gallery views?

Here is what I came up with.  I'm using a custom template.  I found in this another answer on here and then just modified to work with what i needed.

`$(document).on('click', '.gallery-lighbox', function(e) {
  e.preventDefault();

  var $this = $(this),
      $links = $('.gallery-lighbox'),
      arr = [];

  $.each($links, function(index, item) {
      var $item = $(item),
          media_type = $item.data('media-type');

      if (media_type == 'video') {
          var poster = $item.data('poster');
          var src = $item.data('src');

          arr.push({
              type: 'video',
              src: src,
              poster: poster,
              video: {
                tpl:
                  '<video class="fancybox-video" autobuffer playsinline controls controlsList="nodownload" poster="'+poster+'">' +
                  '<source src="'+src+'" type="video/mp4" />' +
                  'Sorry, your browser doesn\'t support embedded videos, <a href="'+src+'">download</a> and watch with your favorite video player!' +
                  "</video>",              
                format: "video/mp4", // custom video format
                autoStart: false
              },
          });

      } else {
          arr.push({
              errorTpl: '<div class="fancybox-error"><p>Please add the media type "data-media-type"</p></div>',
          });
      }
  });

  $.fancybox.open(arr, {}, $links.index($this));
});`

**Comment by robbiegod** [comment]
Is there an attribute to enable a video play button centered on desktop?

**Comment by fancyapps** [comment]
1) See my previous comment.
2) What button?

**Comment by robbiegod** [comment]
1. I did see your previous comment. But, i hope you saw my comment.  It doesn't make sense to use data-thumb as the poster image when the attribute on the video html5 tag is poster.  Plus, these images have different purposes.
2. The button I'd like to know if i can enable is when the video appears I have it set so that it is paused by default. I want a play button to display in the middle of the poster image and the user can click it to play the video.  It's similar to what you have on mobile, i just want a big play button on desktop too.

**Comment by fancyapps** [comment]
1. Looks like there is some misunderstanding, I was thinking about adding that attribute to the link, like so - `<a rel="gallery-videos" href="javascript:;" data-src="your_video" dat-thumb="thumbnail_image_that_is_also_used_as_poster">...</a>`. 

2. You see, the script just creates a html markup including `<video` tag, the rest is up to the browser. There is no wrapper around `<video>` element and you can use other tools for that (like videojs).

**Comment by robbiegod** [comment]
1. I understood that.  You wanted me to add data-thumb to the <a> tag.  I get it. I suppose I just disagree with the name of the attribute and I am hoping you can change it so it no longer uses data-thumb and instead uses data-poster for the poster image.   The solution I posted is doing exactly that, but I had to make a custom tpl for it to work.
2. ok, thank you.
