### ISSUE TITLE
Will the next version of fancybox natively support horizontal thumbnails?

### ISSUE THREAD

**Issue by gavin310** [fancyapps/fancybox#2562]
Thanks for the great plugin! We have the extended license and I'm currently using the horizontal thumbnail scroller technique from https://codepen.io/fancyapps/pen/mqBPXN on our client sites. This method just feels a bit hackish and I'd love for horizontal thumbnails to be a standard feature. Are there plans to include a horizontal thumbnail strip in the next version of Fancybox? Approximately when will the next version (or major update) to be available?

**Comment by fancyapps** [comment]
Hi,

Next generation of Fancybox will be build around custom Carousel component and thumbnails will be just another Carousel instance (with all features you would expect from Carousel). It is hard to give an ETA, actually, the code is ready, I am right now working on the homepage.

**Comment by gavin310** [comment]
That's very exciting! If you want us to test it out on our next client website just let me know.
