### ISSUE TITLE
Manipulating JSON data before fancybox loaded

### ISSUE THREAD

**Issue by flyingatm** [fancyapps/fancybox#2568]
I have a json data that comes from server side.

Looks like this:

![image](https://user-images.githubusercontent.com/50561288/113334080-eaf91000-932b-11eb-92d6-504e0605c626.png)

I wanted to convert it to a html data and then show it in fancybox.

I could'nt find a proper way or document to do it then I edited original code and added a new case like this:

in loadSlide() function:

![image](https://user-images.githubusercontent.com/50561288/113334426-59d66900-932c-11eb-8fc9-6b8ba20ae543.png)

and edited my fancybox call function like this:

![image](https://user-images.githubusercontent.com/50561288/113334812-d0736680-932c-11eb-9b0c-12ac46edfbd0.png)

Works without a problem.

But I'm not feeling comfortable with this way. Editing original code always looked too hacky to me.

What's the proper way to do it?

**Comment by fancyapps** [comment]
Hi,

Simply create array of objects where each have `src` attribute, see https://fancyapps.com/fancybox/3/docs/#api_usage

**Comment by flyingatm** [comment]
Hello thank you for your fast response.

The problem is: this is an AJAX request as you can see in the pictures. 

As far as I can see from this document: https://fancyapps.com/fancybox/3/docs/#api_usage

This is for the data that I already pulled off into the client side. But I need to call every slide from a REST API end point with this JSON data and I need to make it with AJAX.

https://fancyapps.com/fancybox/3/docs/#api_usage this document is useful when I pull all slides and create an array with them. But I wanna call only 1 data from REST API end point and call the other ones when I switch them.

And I need to manipulate this JSON data before I inject it to fancybox.

English is not my main Language, I hope I was able to explain my self. :)

**Comment by flyingatm** [comment]
> Hi,
> 
> Simply create array of objects where each have `src` attribute, see https://fancyapps.com/fancybox/3/docs/#api_usage

Edited my reply and added some pictures to it to be more clear. ^_^

**Comment by fancyapps** [comment]
Well, I do not know what other answer you expect, just use API. Maybe display some dummy element like loading icon, do your thing and replace it with your data. Fancybox provides API, the rest is up to you and your imagination.
