### ISSUE TITLE
Ability to set slug for individual image bookmarks?

### ISSUE THREAD

**Issue by garretwilson** [fancyapps/fancybox#2569]
Can I set what slug is used in the URL fragment for individual image bookmarks?

For example the URL for one of your demo images (the "explore" flag) is https://fancyapps.com/fancybox/3/#images-4 . Can I specify the slug of `explore` for this image, so that the URL becomes https://fancyapps.com/fancybox/3/#explore when the image is viewed? (This way the URL will be a consistent, semantic bookmark even when more images are added or the images are reordered.)

**Comment by garretwilson** [comment]
Is this app still being supported? I will gladly pay a license if this has the functionality I need. So many lightbox libraries have some of the features, but have been abandoned and the developer doesn't even respond. I want to give money to someone who has a good lightbox!!

**Comment by fancyapps** [comment]
Hi,

This feature has been already asked multiple times and will be included in the next major release. It will soon be released (hard to give exact ETA). Thanks.

**Comment by garretwilson** [comment]
Instead of an "exact ETA", could you provide at least an "estimated ETA"? Do you think it will be in 2021? (I note it's been over two years since the last release.

Is there any amount we could pay to get this released sooner rather than later?

**Comment by fancyapps** [comment]
It is the same thing as asking Rockstar when will GTA 6 be released. People tend to think that creating a software is like going from point A to point B when if fact it is like walking blindly in the maze full of traps. 

To be honest, the code is ready and I am now just working on the homepage and docs, but I feel exhausted and I think I need to take a small break before releasing.

**Comment by garretwilson** [comment]
I sympathize with the exhaustion. Take care of your well-being first and foremost.

If there's anything the users can contribute to help you rest and get the update out, let us know.

**Comment by garretwilson** [comment]
@fancyapps I hope you're being able to rest physically and mentally and being refreshed.

This issue was closed because you said it was a duplicate. Could you refer me to the actual ticket this is duplicating, because I'd like to subscribe to that issue for status and further discussion.

Otherwise, if this is really not a duplicate of an existing ticket, I'd like to re-open this ticket so that the status can be tracked.
