### ISSUE TITLE
Dynamically add images to gallery while fancybox is open

### ISSUE THREAD

**Issue by miczed** [fancyapps/fancyBox#257]
Hi

I am using fancybox on a website where I have 9 thumbnails of images. They are all in the same fancybox gallery and everything works just fine. Now if the user scrolls to the bottom of the page 9 more images are added dynamically. If this happens before the user opens the fancybox gallery everything works fine and all 18 images are displayed in a fancybox gallery. The thing that I am trying to achieve is that when the user opens the fancybox gallery and clicks on the last image thumbnail, the other images are added dynamically to the fancybox gallery. 

Is it possible to update the array of elements/images fancybox is displaying while fancybox is running? I looked at the fancybox source but couldn't figure out where and how the elements which should appear next are stored.

Thanks for your good work and I hope someone can help me out with this. 
Regards from Switzerland,

Michael

**Comment by m00s** [comment]
+1

**Comment by fancyapps** [comment]
Exampe for v3 - http://codepen.io/fancyapps/pen/ggwmbb

**Comment by lozeone** [comment]
Thanks for that example.  However, I am having an issue with the caption when adding more than one slide to the gallery.

It appears to always be using the last caption for all the new slides.   See my example here:
https://codepen.io/lozeone/pen/MEjrqO

**Comment by fancyapps** [comment]
@lozeone How about this - https://codepen.io/anon/pen/QqKQQx?editors=1010 ?

```JS
$("[data-fancybox]").fancybox({
  loop : false,
  onInit: function( instance ) {

    // first caption
    instance.createGroup({
      type : 'image',
      src  : 'http://lorempixel.com/701/405/',
      opts : {
        caption : "My Caption 1",
      }
    });

    // second caption
    instance.createGroup({
      type : 'image',
      src  : 'http://lorempixel.com/701/405/',  
      opts : {
        caption : "My Caption 2",
      }
    });

  }
});
```

But keep in mind that method "createGroup" probably will be renamed to "addGroupItems" or smth like that, because only now I realized that it can be used to add new gallery items😄

**Comment by lozeone** [comment]
Perfect! Thanks for the quick response!

**Comment by lozeone** [comment]
@fancyapps  Can this be used to add a slide to the beginning of a gallery? 
If you are going to be renaming this method, adding an additional argument for index would be helpful so you could insert a slide anywhere in the gallery.

**Comment by fancyapps** [comment]
That method appends new element to the end of `instance.group` array and you can manipulate with this array according to your preference, for example:

```JS
// remove freshly added object
 var obj = instance.group.pop();
 
// add it to the beginning
instance.group.unshift( obj );
```

But I can not image how it can be useful, for example, see this demo - https://codepen.io/anon/pen/XeNgNJ?editors=1010

order of gallery elements is completely messed up.

**Comment by SlimSavernake** [comment]
```
$("[data-fancybox]").fancybox({
  loop : false,
  onInit: function( instance ) {

    // first caption
    instance.createGroup({
      type : 'image',
      src  : 'http://lorempixel.com/701/405/',
      opts : {
        caption : "My Caption 1",
      }
    });

    // second caption
    instance.createGroup({
      type : 'image',
      src  : 'http://lorempixel.com/701/405/',  
      opts : {
        caption : "My Caption 2",
      }
    });

  }
});
```
whe i use this i have not arrows. only swipe. how to fix?

**Comment by fancyapps** [comment]
Hi,

Try using the latest version (v3.2.0).

**Comment by SlimSavernake** [comment]
Could you help me please. I have thousands images. When i load  4th (for example) image dinamycally i need to load previous and next images with ajax. But my way does not work. Can you show me correct
example of code.

```
$('#images').on('click', '.item', function(event){
    event.preventDefault();
    var photoid = $(this).data('id');

   //4th image
    var items = [{
        src:$(this).data('src')
    }];

    jQuery.fancybox.open(items, {
        idleTime  : false,
        baseClass : 'fancybox-custom-layout',
        margin    : 0,
        infobar   : true,
        thumbs    : {
            hideOnClose : false,
            parentEl    : '.fancybox-outer'
        },
        touch : {
            vertical : false
        },
        onInit : function( instance, slide ) {
            // Create new wrapping element, it is useful for styling
            // and makes easier to position thumbnails
            instance.$refs.inner.wrap( '<div class="fancybox-outer"></div>' );
        },
        afterShow: function( instance, slide ) {
            $.ajax({
                type: 'POST',
                url: '/photo/default/oninit',
                dataType: 'json',
                data: {'id': photoid},
                success: function(data){

                    //ajax response example for left (previous) image:

                    var response = [{
                        src:'/images/photo/0d/10/0d108198f2374bed23387f07a7cbecd5.jpg',
                    }];

                    instance.createGroup(response);

                    var obj = instance.group.pop();

                    instance.group.unshift( obj );

                    instance.jumpTo(1)

                }
            });
        },
    });
});
```

**Comment by jonasva** [comment]
Any update on this? Same issue

**Comment by fancyapps** [comment]
With the latest version, you would simply use `addContent` method - 

`$.fancybox.getInstance().addContent( collection_of_your_fresh_links );`

**Comment by featdd** [comment]
@fancyapps please put this in your documentation, I've tried out a mess till finding this issue...

**Comment by featdd** [comment]
@fancyapps please put this in your documentation, I've tried out a mess till finding this issue...

**Comment by OLSA** [comment]
> $.fancybox.getInstance().addContent( collection_of_your_fresh_links );

Also, in the last version (v3.5.7), after that block, to get thumbnails button inside navbar and/or to get working options _autoStart: true_ need to reinitialize Thumbs:

```
// reinitialize Thumbs
instance.Thumbs.init(instance);

// optional: to get thumbs autoStart
instance.Thumbs.show(); 
```
Or, another example from stackoverflow [here](https://stackoverflow.com/questions/62910189/fancybox-thumbnail-on-ajax).

I didn't find that in documentation. 
Thanks for the nice script!
