### ISSUE TITLE
Fancybox button CSS should be more specific.

### ISSUE THREAD

**Issue by garretwilson** [fancyapps/fancybox#2573]
Fancybox uses a `<dif class="fancybox-container" …` overlay. The navigation buttons each use a semantic HTML `<button>`, which is great. They take the general form `<div class="fancybox-toolbar"><button class="fancybox-button" …`.

The Fancybox CSS for button style looks like this:

```css
.fancybox-button {
    background: rgba(30, 30, 30, .6);
    border: 0;
    border-radius: 0;
    box-shadow: none;
    …
```

Notice that this CSS doesn't mention the HTML `<button>` element. It applies to any element with the `fancybox-button` class. Of course the only elements that have this class in Fancybox is a Fancybox button. So on the surface it would seem that there is no problem.

However this doesn't take into account [CSS specificity rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). If multiple rules apply to the same element, then CSS has some complicated rules about which rule "wins". The (greatly) simplified answer is that the most specific rule wins, and in particular, a type selector (e.g. `button`) is more specific than a class selector (e.g. `.fancybox-button`.

If some overarching CSS framework is styling the `<button>` in general, then the general framework will override Fancybox. But we want Fancybox to override the general framework! So Fancybox needs to be more specific.

This can easily be fixed by including the `button` type selector; that is, `button.fancybox-button` instead of `.fancybox-button`.

```css
button.fancybox-button {
    background: rgba(30, 30, 30, .6);
    border: 0;
    border-radius: 0;
    box-shadow: none;
    …
```

As a workaround I have to basically duplicate the Fancybox button styles in my own stylesheet and update the selectors, which is a drag. Just make the selectors more specific and everything should be good.

**Comment by mjcampagna** [comment]
A fair point. But this conversation easily drifts into the larger sphere of philosophy around style guides. There's a branch of thought in which styling should not be overly specific, most often manifesting as "styling should be applied to classes, and classes to elements; styling should not be applied directly to elements."

Looking at [Fancybox's core CSS](https://github.com/fancyapps/fancybox/blob/master/src/css/core.css), this seems to be the philosophy by which the library is written. There are almost no cases where elements are used specifically. 

In a way, I appreciate this. It makes it very easy for me to customize Fancybox's styling. If Janis were to follow your suggestion, he would need to rewrite his stylesheets entirely to maintain consistency, and would like break a good many existing user implementations in doing so.

**Comment by garretwilson** [comment]
>  There's a branch of thought in which styling should not be overly specific, most often manifesting as "styling should be applied to classes, and classes to elements; styling should not be applied directly to elements."

I understand what you're saying, and I agree to some extent if we're talking about general, semantically neutral elements such as `<div>`. But Fancybox is not following this rule completely because it uses a semantic `<button>` element. Adding a `<button>` element implicitly brings in all the styles (including the default browser and user stylesheets) that are bound to `<button>`.

So if Fancybox wants to simply use styles, then it should use `<div class="fancybox-button">` and we wouldn't have this problem either. Then it can use a `.fancybox-button` selector and not interfere with buttons. But instead it uses a "heavyweight" `<button>` element which brings in styles from everywhere, but only uses a "lightweight" class-based selector to apply its styles.

Lastly I don't think your "branch of thought" should be applied categorically. One should consider the role of the stylesheet being created. Is it the page stylesheet? Is it a framework stylesheet? Is it a plugin-type library stylesheet? In the case of Fancybox, it is the latter: a plugin-type library that is meant to be used _on top of_ or _in addition to_ some base framework. The lightbox buttons are not meant to match the general style of the buttons across site. They are meant for a special purpose, and the whole point of the lightbox is that is provides a certain visual functionality. Thus the buttons shouldn't automatically modify their look to match what the buttons look like on the normal page. In other words, Fancybox should err on the side of more specific styling (although not extreme with `!important` and the like).

**Comment by mjcampagna** [comment]
It's an interactive element, so `button` is absolutely the appropriate choice; to use a `div` there makes no sense at all, if we're talking semantics. Sounds to me like your framework might be throwing its weight around a little too much. I was an early adopter of Fancybox 3, so have been using it for three or four years now, and I've never had any issues whatsoever with its buttons getting into style conflicts.

**Comment by garretwilson** [comment]
> … `button` is absolutely the appropriate choice …

Yes, I agree! Semantically `<button>` is the best choice. To me it follows that when selecting the styles, you would want to similarly say, "Apply this style, not to any old `<button>`, but to buttons that are `fancy-button` class buttons." To me that makes perfect sense. But the current CSS says, "Apply this style to _any_ element that has the `fancy-button` class, whether it's a button or a form or a file upload element." I didn't understand the point of such broad selection even to non-button elements unused by the library.

But I don't want to get hung up on pedantic arguments or personal preferences. Overall this is a very nice library, and from what I've seen the code is small and understandable. This was just a small hiccup for my use case, and I was simply hoping to offer an improvement.

Cheers! I appreciate the work done on Fancybox.

**Comment by fancyapps** [comment]
Hi,

First, I do not understand your issue at all. Class selector weights more that generic element tag.

For example, if I have `<button class="red">Hi</button>` and this CSS:

```CSS
button {
  background: blue;
}

.red {
  background: red;
}
```

What will be background of the button? Answer - https://jsfiddle.net/45utn3kL/

Secondly, it is a good practice to avoid generic element tags for CSS, for example, see https://twitter.com/_jmoller/status/1381323278934028288/photo/2

**Comment by garretwilson** [comment]
> Class selector weights more than generic element tag.

Hmmm... it appears what I stated was incorrect. I think I read list in the the [MDC documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) which has the specificity in reverse order (I was expected most specific to be the first in the list) and didn't notice they said that the "… following list of selector types increases by specificity …". My mistake.

My particular use case is thus more complicated than I presented it, even though the added specificity of having both the element and the class in the selector would help me. But my explanation wasn't correct, and it's probably not worth it to drill down into the specifics here.

> it is a good practice to avoid generic element tags for CSS

I don't know that I agree in all cases, and to me a single twitter post doesn't really tell me if this is the latest recommended best practice by several experts.

But I think it comes down to this being a programming technique preference. You prefer to do it the other way; fine. I can work around the issue or fork the library and redo the styles if I need to. So thanks for reading my request, but feel free to close it if you don't agree with the suggestion.

**Comment by mjcampagna** [comment]
There's plenty of takes on what should be best practices, but do some reading on [BEM](http://getbem.com/introduction/). I don't subscribe to it entirely, but there's a lot of good stuff in its guidelines that can be cherry-picked into your personal best practices. Having explored Fancybox's styles, I think there's more than a little BEM in there.
