### ISSUE TITLE
Homepage jumps when going fullscreen

### ISSUE THREAD

**Issue by michas0602** [fancyapps/fancybox#2574]
Hi, I´ve recognized that when I click an image to fullscreen, parts of my [homepage](https://www.nachtlicht-fotografie.de/portfolio/fraktalbilder/) (header and scroll-breadcrumb) are jumping a bit to the right.
I am almost sure this is caused by the scrollbar somehow.
Is there an elegant way instead of making scrollbar permanent to avoid this jumping when going fullscreen? 
Many thanks in advance and with best regards

Edit:
After some tryouts I am atm playing with a simple

`    .jtpl-header {
        width:100vw;
}`

which seems to do [the job](https://www.nachtlicht-fotografie.de/portfolio/fotografie/) great. The breadcrumb is faded out with velocity and everything looks fine so far. I´ll do more tests later today

**Comment by fancyapps** [comment]
Hi,

See https://fancyapps.com/fancybox/3/docs/#faq-1
