### ISSUE TITLE
Two invocations on the same page

### ISSUE THREAD

**Issue by ron4mac** [fancyapps/fancybox#2577]
I've been banging my head trying to get two programatic calls to FancyBox on the same page to work. I have a page with thumbnails. Links to items are in an array. If you click on a thumbnail, a function is called to start fancybox with the indexed item, certain buttons, and no auto-running slideshow. There is an icon on the page to fire up an auto-running slideshow to display all items.

Initially loading the page, either method works as expected. But if you then close the fancybox and select the other method, it uses the same options as the one previously selected. So ... if you ran a slideshow from the slideshow icon, and then click on a thumbnail, it runs a slideshow (beginning with the selected item). I've peeked at the instance 'opts' and the new values do get set, but fancybox seems to ignore them and do whatever was first selected.

Not sure if this is a bug or if I'm just missing something.

```
    function showSlide (e, iid) {
        e.preventDefault();
        jQuery.fancybox.destroy();
        jQuery.fancybox.open(imagelist, {loop:false, buttons:["zoom","slideShow","fullScreen","close"], slideShow:{autoStart:false, speed:6000}}, iid);
    }
    function slideShow (e) {
        e.preventDefault();
        jQuery.fancybox.destroy();
        jQuery.fancybox.open(imagelist, {loop:false, buttons:["fullScreen","close"], slideShow:{autoStart:true, speed:6000}});
    }
```

**Comment by fancyapps** [comment]
Hi,

Sorry, it is not possible to give any meaningful answer without seeing a live page/demo. Please, create a demo using codepen/jsfiddle/... so your issue could be inspected.

**Comment by ron4mac** [comment]
Here is a demo (I substituted divs for actual thumbnails). You have to reload the page for the alternate fancybox view to work as expected.
[demo](http://rfourm.net/dev/fancybox-master/testing/)

**Comment by fancyapps** [comment]
Have you tried upgrading jQuery to the latest?

**Comment by ron4mac** [comment]
> Have you tried upgrading jQuery to the latest?

I haven't (yet) as my intended use is somewhat limited to 1.12.4.  I will check that.

**Comment by ron4mac** [comment]
Changed my demo to use jquery 3.5.1 and get the same behavior.

**Comment by fancyapps** [comment]
Could you change `$.fancybox.open(imagelist, ` to `$.fancybox.open([...imagelist],`? I guess the reason is that your object is passed by reference.

**Comment by ron4mac** [comment]
Ahhh ... that makes the difference. A bit inconvenient for a large list of items. Any suggestion where I could customize to allow it to work from one referenced list?

**Comment by ron4mac** [comment]
I can probably work it out now that I know the source of the issue.  Thanks ever so much for your fast response and help.

**Comment by ron4mac** [comment]
As a follow up...
Had to use the JSON method to copy the original array of objects.
```
let imgl = JSON.parse(JSON.stringify(imagelist));
jQuery.fancybox.open(imgl, {loop:false, buttons:["fullScreen","close"], slideShow:{autoStart:true, speed:5000}});

```
