### ISSUE TITLE
Whats the difference between afterLoad and afterShow ?

### ISSUE THREAD

**Issue by kgnfth** [fancyapps/fancybox#2579]
i am using fancybox in my nuxt.js app, it works great and its better then vue-cool-lightbox which is based on fancybox
i could not change the html video to plyr.js using it, so i switched to fancybox... 
Anyway i wanted to know what the difference is between

```js
afterLoad() {
  return Plyr.setup('.fancybox-video')
},
```

and

```js
afterShow() {
  return Plyr.setup('.fancybox-video')
},
```

because they bot change the html player to plyr.js 
i am not sure which one should i use ?

i have read the docs but i don't understand

**Comment by fancyapps** [comment]
Hi,

Thanks for choosing Fancybox :) I had never heard of that clone before, it looks like it's pretty popular. 

Anyway, about your question - `afterLoad` is fired right after content is created but right before it is actually disabled, e.g., right before reveal (like `fadeIn`) animation starts. `afterShow` event is fired after revealing animation ends. Obviously, if you have disabled animations, they are fired one after another.

btw, I wanted to ask, why did you choose to use Plyr? Just for styling your videos or are there any particular features you are looking for? The reason why I am asking this, is that I am planning to expand this project with multiple Javascript tools and something about video is on the list of potential candidates.

**Comment by kgnfth** [comment]
@fancyapps

Thx for explaining


> btw, I wanted to ask, why did you choose to use Plyr? Just for styling your videos or are there any particular features you are looking for? The reason why I am asking this, is that I am planning to expand this project with multiple Javascript tools and something about video is on the list of potential candidates.

Yes just for styling my video player and i needed `playback rate` option for my videos :)

**Comment by kgnfth** [comment]
Hmm looks like it does not work when building my app in production
fancybox works fine but video player style wont change

Any idea ?

```js
  mounted() {
    $('[data-fancybox="images"]').fancybox({
      afterLoad() {
        return Plyr.setup('.fancybox-video')
      },
      image: {
        preload: true,
      },
      video: {
        format: 'video/mp4',
        autoStart: false,
      },
      thumbs: {
        autoStart: false,
      },
      buttons: [
        'zoom',
        'slideShow',
        'fullScreen',
        'download',
        'thumbs',
        'close',
      ],
    })
  },
```

**Comment by fancyapps** [comment]
hmm, does console give any clue? Also, I think it should be smth like  `afterLoad : function(instance, current) { new Plyr(current.$content.find('video')); }` (I did not test this snippet)

**Comment by kgnfth** [comment]
> hmm, does console give any clue? Also, I think it should be smth like `afterLoad : function(instance, current) { new Plyr(current.$content.find('video')); }` (I did not test this snippet)

still the same, but when i run this code in browser console then it works
```js
$('[data-fancybox="images"]').fancybox({
      afterLoad: function (instance, current) {
        new Plyr(current.$content.find('video'))
      },
      image: {
        preload: true,
      },
      video: {
        format: 'video/mp4',
        autoStart: false,
      },
      thumbs: {
        autoStart: false,
      },
      buttons: [
        'zoom',
        'slideShow',
        'fullScreen',
        'download',
        'thumbs',
        'close',
      ],
      animationEffect: 'fade',
      transitionEffect: 'fade',
    })
```

### this is how my component looks like

```vue
<template>
  <div>
    <VueJustifiedLayout
      v-slot="{ item, index }"
      :items="data"
      :options="justifiedOptions"
    >
      <div class="bg-white shadow-md dark:bg-gray-800">
        <div class="relative w-full hover:opacity-80">
          <a
            data-fancybox="images"
            :href="getStrapiMedia(item.src)"
            :data-width="item.width"
            :data-height="item.height"
          >
            <blur-hash-lazy-image
              :key="index"
              :src="getStrapiMedia(item.thumb)"
              :blurhash="item.hash"
              :width="item.width"
              :height="item.height"
              @click="imageIndex = index"
            />
            <PhPlay
              v-if="item.type === 'video'"
              class="absolute text-white transform -translate-x-1/2 -translate-y-1/2 cursor-pointer top-2/4 left-2/4"
              size="60"
              weight="light"
              @click="imageIndex = index"
            />
          </a>
        </div>
      </div>
    </VueJustifiedLayout>
  </div>
</template>

<script>
import '@fancyapps/fancybox/dist/jquery.fancybox.min.css'
window.$ = window.jQuery = require('jquery')
const $ = require('jquery')
require('@fancyapps/fancybox')
window.Plyr = require('plyr')
import { getStrapiMedia } from '../utils/medias'

export default {
  props: {
    data: {
      type: Array,
      required: true,
      default() {
        return []
      },
    },
  },
  data() {
    return {
      imageIndex: null,
      justifiedOptions: {
        boxSpacing: 10,
        containerPadding: {
          top: 10,
          right: 0,
          left: 0,
          bottom: 10,
        },
      },
    }
  },
  mounted() {
    $('[data-fancybox="images"]').fancybox({
      afterLoad: function (current) {
        new Plyr(current.$content.find('video'))
      },
      image: {
        preload: true,
      },
      video: {
        format: 'video/mp4',
        autoStart: false,
      },
      thumbs: {
        autoStart: false,
      },
      buttons: [
        'zoom',
        'slideShow',
        'fullScreen',
        'download',
        'thumbs',
        'close',
      ],
      animationEffect: 'fade',
      transitionEffect: 'fade',
    })
  },
  methods: {
    getStrapiMedia,
  },
}
</script>

<style>
:root {
  --plyr-color-main: #c026d3;
}
</style>
```

my app is full static client side, no SSR

**Comment by kgnfth** [comment]
For now i switched to lightgallery.js
