### ISSUE TITLE
Feature request: Playback of OGG and MOV files on both Chrome and Safari (desktop & mobile)

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2580]
Is there a way to implement this feature without converting or live transcoding MOV and OGG files?

Android users support OGG files but not iPhone users

and the opposite

iPhone users can flawlessly play MOV files whereas Android users can't

Is there a work around or feature you can implement?

#STAYSAFE

**Comment by fancyapps** [comment]
Hi,

Converting video streams is out of the scope of this project (basically, it would mean to port FFmpeg to JavaScript).

The simplest solution would be to use `ffmpeg` (.e.g, `ffmpeg -i sourceFile.mov destinationFile.mp4`) to convert your videos to mp4.
