### ISSUE TITLE
Pass data attribute (data-name, data-id, etc) of button to modal

### ISSUE THREAD

**Issue by vijayrana99** [fancyapps/fancybox#2585]
Is it possible to pass data attributes of HTML elements to modal using this plugin? I am trying like below but `instance` doesn't contain any data attributes.

```
$(".view-modal").fancybox({
    afterShow: function (instance, slide) {
        console.log(instance);
    },
});
```

**Comment by fancyapps** [comment]
Hi,

`instance.$trigger` will be reference to clicked element.
