### ISSUE TITLE
When Fancybox V4 is coming out?

### ISSUE THREAD

**Issue by avianion** [fancyapps/fancybox#2589]
@fancyapps You said the code for V4 is done, when will this be released? Is it possible to have early access to the code as its needed for a project which ddeadline is before 8th May.

**Comment by heemza** [comment]
Duplicate #1346 , #2581

**Comment by avianion** [comment]
Sure it's a duplicate, but how about giving an answer?

**Comment by fancyapps** [comment]
Hi,

See https://github.com/fancyapps/fancybox/issues/1346#issuecomment-853844350
