### ISSUE TITLE
SrcSet and webP images

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2591]
I am investigating the use of srcset and the support of webP images with fancyBox 3

I use code like this:

    <a data-fancybox="S" href="slides/RV_150510_1055.jpg" 
    data-srcset="slides/RV_150510_1055-4032w.webp 4032w, slides/RV_150510_1055-3072w.webp 3072w, slides/RV_150510_1055-2048w.webp 2048w, slides/RV_150510_1055-1024w.webp 1024w, slides/RV_150510_1055.jpg 1024w" 
    id="1" data-caption= ''>
    <div class="box" >
    <img srcset="thumbs/RV_150510_1055-853w.webp 853w, thumbs/RV_150510_1055-427w.webp 427w, thumbs/RV_150510_1055.jpg 427w"
    src="thumbs/RV_150510_1055.jpg"width="213" height="160" alt="2: RV_150510_1055" title="2: RV_150510_1055"  /><br>
    <div class="thumbText"></div>
    </div>
    </a>

This works well, see [this album with webP-images and jpg-images](https://www.andrewolff.nl/SrcSets_1024/) and [this album with only jpg-images](https://www.andrewolff.nl/SrcSets_1920_jpg/). but I am not yet convinced about the benefits of using srcset, it is hard to measure improved response times.

But I have 2 questions:

Is the preloading correctly working with srcset? Does the preloading script load the same variant as srcset selects if the next slide button is clicked?

An album with webP images works fine in all modern browsers, but for instance on an iPhone 5S with iOS 10.3,  webP images can't be displayed. As a fall-back the album contains also jpg files, but these are not automatically selected by the browser. 
So my question is: is there an event where I can see that a webP image is not accepted and can I in that event load the correct jpg file?

**Comment by Nimrod-666** [comment]
Hi, srcset should work fine but as a fallback i recommend you to simply check the request header for the webp param. You can then serve a jpeg version or a webp version of the html code. Example for PHP:

`	    if(array_key_exists('HTTP_ACCEPT', $_SERVER)){
	        if(strpos( $_SERVER['HTTP_ACCEPT'], 'image/webp') !== false){
	            return true;
	        } else {
	            return false;
	        }
	    }`

**Comment by acwolff** [comment]
@Nimrod-666  thanks for your reply.

I have no experience with PHP code or any server side code.
Si I don't know where  and how to call your code.

But tells your code whether the current browser can handle WebP images?

So with iOS 10 it should return false and with iOS 14 true?

And with that information I should  modify my code shown above?

**Comment by acwolff** [comment]
I did find  a solution with next code  for use in the document.ready function to get a good working fallback for iOS:
 getDeviceInfo();
    if (iOS && (iOS_version < 14)) {
        $("a").removeAttr("data-srcset");
        $("img").removeAttr("srcset");
    };
With javascript code I fetch the used operating system and IOS version.
