### ISSUE TITLE
Multiple data fancyboxes

### ISSUE THREAD

**Issue by souocare** [fancyapps/fancybox#2592]
Hi. 
I have a question.
In the fancybox, I have this 'data-fancybox="gallery"'.

Is it possible to insert multiple data-fancyboxes like data-fancybox="gallery gallery2" or something like that?

Because I have a personal portfolio site (nothing commercial, only for me), and if I filter the photos to show only a few, it will show all photos when I open the fancy box and scroll. And I have photos in multiple filters.

**Comment by fancyapps** [comment]
Hi,

In your case, it would be best to start fancybox programmatically using API. Simply add click event to your links where you would get all group elements and then call `$.fancybox.open()`.
