### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by michas0602** [fancyapps/fancybox#2593]
Hi,
I am trying around with alt-text for Google indexing since a while, but without success - Google just shows a few of my images, I assume I am doing something wrong.

I´ve using Facybox3 with Slider-Pro, in html initialized with
```
<div class="slider-pro" id="ms-Photos-Locations">
    <div class="sp-slides">
        <!-- Slide 1 -->

        <div class="sp-slide">
            <a href="url/example.jpg"
            data-caption="Berlin"> 
            <img class="sp-image" src="" 
            data-src="url/example.jpg" data-alt="Berlin" /></a>
        </div>
        <!-- Slide 2 -->
...
```

I assume my problems are caused by the usage of data-src for lazyload? However, how do I solve it?

I have 3 different Sliders on my page, all working the same - how do I ensure, that Google 100% find all "alt"-texts for every image (not just the lazyloaded first ones) for every image I have in my Sliders? Does Google recognize 'data-alt' at all or do I have to use just "alt"?

Many thanks for your great work and with best regards,
Michael

**Comment by JacobTaylor-RCC** [comment]
Hi Michael,
I cannot entirely answer your question -- but google does not know what data-alt is. 

That may change in the future, but alt-text for images is always alt="". I would recommend regular alt tag anyway, as it is more accessible (to google and people).

**Comment by fancyapps** [comment]
Hi,

I'm sure @JacobTaylor-RCC is right.
