### ISSUE TITLE
html5video not playing in iOS/iPad safari browser.

### ISSUE THREAD

**Issue by 013459** [fancyapps/fancybox#2604]
**Describe the bug**
Using HTML5 video does not work in iOS/iPad safari browser (video does not play on play/pause icon click).

**To Reproduce**
1. Using the fancyBox v3.5.7 version when I click to show video button, the video was not playing in the iOS/iPad safari browser. In all other browsers like chrome and firefox, it was working.
2. I also checked https://fancyapps.com/docs/ui/fancybox/plugins/html#video in this link, data-source with this path **/img/video.mp4** doesn't play in iOS safari browser whereas youtube and Vimeo were working fine.

**Expected behavior**
HTML5 video should play in iOS/iPad safari browser.

**Screenshots**
https://lh3.googleusercontent.com/fife/AAWUweXHwno6LnnD1WlFlat0w_kLo0EXuXnv9hmjM9SySDjc6WQxAmJryva76NsP-qqP6a1eqm0okJmA4McftDJ3kah9k887ehY7A6YGIzumDbYs3J_gopGi52osHDiqbAHVxS19crw_ByBkiqZqKwO7aSevkK9sroUXrK1DW2WXNfaA6nwOLqIRB_1EOYnoqcHE8f0kEL3LB8HvRDg9OfiK3v-HiyfKLjCkOQSquqkWCo_z-Qrl-hzoudLidJt9KBIabCwXgW4uEtFoAzja3d86u8gm2SsMMZ7QbrQtUaQTdIS-kX-saFpigGqOEqqdlVSe77rbyEckpbKpBBnO4HeAGpvLDmMse_XzbaISf5a4jXtwvtBY8Xedcnu_kMIQfwUEcs7dOwg3BavvGrZUGTs8WVXSi69EZC8-moTsMAm5saObfH90T-_EfyQbGqcxVLUhKFfFPKLbyaC58wFLiYcZwlbHzasBMAb_LBlztDeXjgqo1MoCNcQPcbhXS_59SHhwA0AU4MwHDgpqcxNesNH1CVNFWx8YuvWMIpppDTYSisNHM_GfucSK-rwtqnU1DB7xCo3mYwJJPPAgQFFVWFGsEEzvfEANGCNktBpZYcgEgXH9Ar1iYWI6Wu-TM_o560Wv-IthMDAS3bzOHgv5OyuWLtzm6-U_evrNZu3GI1PUORORkumPBMYGSFzTU71Hfl-BUBOUSd9vKz_7xNYopLvIef04rYiOmvpn3Ok=w750-h1236?authuser=0

**Smartphone (please complete the following information):**
 - Device:  iPhone 6+(12.5.4), iPhone 7(13.3), iPad 8th Gen
 - OS: 12, 13, 14
 - Browser : safari
 - Version 12, 13, 14

**Comment by fancyapps** [comment]
It works fine for me.

**Comment by 013459** [comment]
Did you check in iOS safari 12 or 13 OS that html5video was playing or not?

**Comment by fancyapps** [comment]
1) The latest Fancybox v3 was released two years ago, it was and has been working perfectly fine for everyone. 
2) iOS Safari supports HTML5 video since iOS v3.2 released on 2010. 
3) Fancybox simply creates HTML `<video>` element, the rest is up to you and your browser.

**Comment by 013459** [comment]
I try to check html5video in https://fancyapps.com/docs/ui/fancybox/plugins/html#video this link. Here it is video link you can see the video was not playing. can you please guide me why it is not playing in iOS safari (version)? I am using mp4 video.

https://r1---sn-npoeen7d.googlevideo.com/videoplayback?expire=1626361388&ei=DDLwYMKnMYay4ALTxp-QDQ&ip=2409:4041:d13:e1b2:c11b:700d:b25f:ed9b&id=43e5b016bbf4b239&itag=18&source=picasa&begin=0&requiressl=yes&sc=yes&susc=ph&app=fife&ic=674&mime=video/mp4&vprv=1&prv=1&dur=19.342&lmt=1626351701532728&authuser=0&sparams=expire,ei,ip,id,itag,source,requiressl,susc,app,ic,mime,vprv,prv,dur,lmt&sig=AOq0QJ8wRQIhAIGNquq-mUBCYt0sUZ7f-IsoSftUdmmXn5gj6gwX5_1kAiBc6ImlfNTM26j0F1V9ez5Y5WKL_y4NlDoGMAYTL5ANow==&redirect_counter=1&cm2rm=sn-cvhsd7e&req_id=eb4ab625b8d1a3ee&cms_redirect=yes&mh=2K&mm=34&mn=sn-npoeen7d&ms=ltu&mt=1626353805&mv=m&mvi=1&pl=41&lsparams=mh,mm,mn,ms,mv,mvi,pl,sc&lsig=AG3C_xAwRAIgPZfrvFDLGYbaw8Hw9NCoBYgexO1Rl-sJylR3SP6fxHACIH5caUQ_YOv2XNWWIe5kjC2bQbfvqFHLHpHHU5f0koGx

**Comment by 013459** [comment]
Hello,

Maybe the last video link is not working, sending you again. I try to check html5video in https://fancyapps.com/docs/ui/fancybox/plugins/html#video this link. Below is the video link you can see the video was not playing. can you please guide me on why it is not playing in iOS safari (12.5.3)? I am using mp4 video. 

https://drive.google.com/file/d/1PgXU21rVe8elAVwuQM6CNrcQqGwbKfsm/view?usp=sharing.
