### ISSUE TITLE
"On Safari" Page scrolls back to top when Fancybox (lightbox) is closed

### ISSUE THREAD

**Issue by ayzee** [fancyapps/fancybox#2605]
When I click outside the lightbox or click on the close button, the whole website scrolls back to the top. 

1. Go to 'planwerk,netlify.app'
2. Scroll down to the Gallery section and click any image to open Fancybox( lightbox)
3. Now click on the close button
4. The page will scroll back to the top

The page should not scroll just as it behaves on Chrome and other browsers.

 - Mac (Safari)

 - iPhone (Safari)

If you go to the Gallery section by clicking on the Menu Item. The URL of the website gets appended with "#gallery". With this in the URL, the click on the Fancybox close icon scrolls back to the Gallery section start.

**Comment by fancyapps** [comment]
Hi,

First, your link does not work, therefore your issue could not be inspected. Note that Fancybox v3 is discontinued. Sorry, it is just not humanely possible to work on two completely different versions at the same time and provide full support.

**Comment by ayzee** [comment]
My Bad. I gave the link to the staging server, where things got updated. I was using version 4 nonetheless. Removed Fancy apps and went for a different option as the issue is still there. I can update the link if you want to have a look. Thanks.

**Comment by ayzee** [comment]
> Well, since I can not reproduce this issue, a live demo could help.

I have created a new demo link that has Fancybox 4 and has the same issue on Safari (Mac and iPhone both). Please have a look. It's in the Gallery section just as mentioned above in the Issue.

URL: https://fbdemo.netlify.app/

**Comment by fancyapps** [comment]
It is difficult to find the cause of the problem. There will be a big update in a couple of days, I would be grateful if you could upgrade and then I could come back and check again.
