### ISSUE TITLE
Rating for picture

### ISSUE THREAD

**Issue by BeCeDeR** [fancyapps/fancybox#2606]
How do I ...
1. How can I add a rating (1 to 5) for each photo in the gallery?
2. When I try to click on the rating radio box, the photo (gallery) is closed.
![123](https://user-images.githubusercontent.com/88556022/128553513-77a9f8d9-9c75-4b98-bdf1-75f5e8dc0020.jpg)

**Comment by BeCeDeR** [comment]
Now my (bad) code is

```
<div class="gallery_user-item">
 <div class="gallery_user-item_inner">
<img class="owl-lazy" width="140" height="210" data-src="https://photo.cdn.com/231/1023134-3209974668786312830.jpg" alt="Eriina from Helsinki">
<div class="gallery_user-item_overlay">
<a href="https://photo.cdn.com/231/1023134-3209974668786312830.jpg" class="profile-gallery" title="Lady from Helsinki" data-selectable="true" data-touch="false" data-fancybox="images" data-caption="<div class='abs_center'><form method=post name=FormVote><input type=hidden name=ID value=1001748653><input type=hidden name=pic_num value='не_знаю_значения'> <input type=radio name=vote value=1 onClick='javascript: document.forms['FormVote'].submit()'> 1 <input type=radio name=vote value=2 onClick='javascript: document.forms['FormVote'].submit()'> 2 <input type=radio name=vote value=3 onClick='javascript: document.forms['FormVote'].submit()'> 3 <input type=radio name=vote value=4 onClick='javascript: document.forms['FormVote'].submit()'> 4 <input type=radio name=vote value=5 onClick='javascript: document.forms['FormVote'].submit()'> 5 </form></div>"></a>
</div>
</div>
</div>
```

**Comment by fancyapps** [comment]
Hi,

You simply have to stop bubbling of the click event (https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation).

**Comment by BeCeDeR** [comment]
Thank you for your answer. Could it be more detailed? I am a pensioner, mastering something new for myself, and I still don’t understand some things. Excuse me.

**Comment by mjcampagna** [comment]
> Thank you for your answer.
> 
> 1. Could it be more detailed? I am a pensioner, mastering something new for myself, and I still don’t understand some things. Excuse me.
> 2. Have I placed the photo evaluation block correctly in the data-caption?

Look up event “stopPropagation” on MDN.
