### ISSUE TITLE
Disable zoom (Fancybox4)

### ISSUE THREAD

**Issue by edealfonso** [fancyapps/fancybox#2608]
I find the documentation of Fancybox 4 very complicated for a newbie like me.

How do I disable zoom effect at click on Fancybox 4?

I've tried all these options adding JS after the FancyBox JS with no success:

```
Fancybox.bind("[data-fancybox]", {
  Image: {
    zoom: false,
  },
  clickContent : false,
  click : false,
  zoom: false,
});
```

Please help!
Thank you

**Comment by fancyapps** [comment]
Hi,

This should work to disable zoom animation from the thumbnail:

```js
Fancybox.bind("[data-fancybox]", {
  Image: {
    zoom: false,
  },
});
```

If you wish to disable any animation, add these options:

```js
showClass: false,
hideClass: false,
```

Example: https://fancyapps.com/playground/vi
