### ISSUE TITLE
Option 'mainClass' is not working

### ISSUE THREAD

**Issue by Tephrosis** [fancyapps/fancybox#2609]
**Describe the bug**
mainClass option is not working when using Fancybox with the declarative function.

**To Reproduce**
Just paste this code in the [Fancybox Playground](https://fancyapps.com/playground):

return new Fancybox([{
    src: 'https://getbootstrap.com/docs/5.0/utilities/api/',
    type: 'iframe',
    mainClass: 'mw-lg-50', // Doesn't work
}]);

**Expected behavior**
the 'mainClass' should be added tot the Fancybox container according to [the documentation](https://fancyapps.com/docs/ui/fancybox/options/#mainClass).

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version:  v4.0.0-alpha.4

**Comment by fancyapps** [comment]
Hi,

Option `mainClass` can not be set individually per slide, set it like this:

```JS
return new Fancybox(
  [
    {
      src: 'https://getbootstrap.com/docs/5.0/utilities/api/',
      type: 'iframe'
    }
  ], {
    mainClass: 'mw-lg-50', 
  });
```

**Comment by Tephrosis** [comment]
Thanks a lot for the super fast reply!

**Comment by fancyapps** [comment]
No problem. Sorry about confusion, I'll update docs with more samples and info.
