### ISSUE TITLE
Fancybox 4.0 - Blinking issue when using the show() method

### ISSUE THREAD

**Issue by wastzzz** [fancyapps/fancybox#2610]
**Describe the bug**
Fancybox opens and closes immediately (like a blink). On the second time, it opens normally.

**To Reproduce**
1. Create a button and a div with the content to be shown in the Fancybox
2. Use the Fancybox.show() method in the click() event of the button, with "inline" mode:
Fancybox.show([
                {
                    src: "#fancybox-test",
                    type: "inline",
                },
            ]);

**Expected behavior**
Fancybox opens normally and stays there

**Screenshots**

**Desktop (please complete the following information):**
- Chrome and Safari

**Additional context**

**Comment by wastzzz** [comment]
I understood how to solve the problem.
You cannot have a button with href, or if you do, you must add event.preventDefault():

Example button with href:
<a href="#" id="open-fancybox" class="btn btn-primary">Open Fancybox</a>

Example Javascript:
$('#open-fancybox').click( function(event) {
            event.preventDefault();
            Fancybox.show([
                {
                    src: "#fancybox-test",
                    type: "inline",
                },
            ]);
        });

Example button without href:
<a id="open-fancybox" class="btn btn-primary">Open Fancybox</a>

Example Javascript (you can avoid the preventDefault()):
$('#open-fancybox').click( function(event) {
         
            Fancybox.show([
                {
                    src: "#fancybox-test",
                    type: "inline",
                },
            ]);
        });

**Comment by fancyapps** [comment]
Hi,

It is a bad practice to use `href="#"`, because browser will change document location unless you prevent default action. I recommend using `href="javascript:;"`, or changing to another HTML element, such as a button.
