### ISSUE TITLE
Fancybox 4: Ajax mode won't run Javascript code contained in the returned content

### ISSUE THREAD

**Issue by wastzzz** [fancyapps/fancybox#2611]
**Describe the bug**
When loading content via Ajax in Fancybox 4, any Javascript code inside the returned content doesn't run?

**To Reproduce**
1. Call Fancybox like this:
`Fancybox.show([
                    {
                        src: '/product/edit/556',
                        type: 'ajax',
                    }
                ]);`
2. The HTML returned by the page /product/edit/556 also contains some Javascript code
3. Notice that the Javascript code will not work

**Expected behavior**
Javascript code inside the loaded content should work, as in Fancybox 3.

**Screenshots**

**Desktop (please complete the following information):**
- Chrome and Safari (latest)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fancyapps** [comment]
Hi,

Please, upgrade to the latest.

**Comment by wastzzz** [comment]
Thanks! I’ll try today.
