### ISSUE TITLE
fancybox iframe problem: just a thin line

### ISSUE THREAD

**Issue by stathimexas** [fancyapps/fancybox#2615]
I use the latest version of "FancyBox for WordPress" and have the following html in my post on the latest version of Wordpress:

`<a` data-fancybox data-type="iframe"  href="https://mywebsite.org/wp-content/uploads/albums/test/mysong.mp4">Click to `play</a>`

But when I click on the link, the iframe launches but only a red line appears, which is the color of the frame from the settings. You can see it [here](https://mexas.org/test-alone/).

Please help me.
Thank you so much.

**Comment by fancyapps** [comment]
Hi,

It is because your link has `data-type="iframe"`, please, remove or change to `data-type="video"`.

**Comment by stathimexas** [comment]
Janis, thank you soooo much.
