### ISSUE TITLE
Fancybox 4 Scrolling after close

### ISSUE THREAD

**Issue by gregzawadzki** [fancyapps/fancybox#2616]
How do I disable scrolling of fancybox4. 

When you open fancybox, and scroll site down (link is not in viewport) then after closing Fancybox, it scrolls back to this place.  
I think this is a feture of some sort probably, but I have implemented `$('.gallery').trigger('click')`, which is in footer. After closing gallery, user is scrolled up, so triggered link is in viewport. It must be that way and I'm looking for way to disable this behaviour.

fancyapps/ui/Fancybox v4.0.6

**Comment by seigieu** [comment]
> Hi,
> 
> See https://fancyapps.com/docs/ui/fancybox/options#placeFocusBack

Thank you. I was looking at docs and didn't notice.
