### ISSUE TITLE
how to put facebook like  ,tweeter,g+  button after title in fancybox

### ISSUE THREAD

**Issue by bheeshamteche** [fancyapps/fancyBox#262]
i have an issue in fancy box
i want to make like this for my slideshow= http://www.ithroughmyeye.com/#!portfolio/photostackergallery0=9  
but this page is in flash.

i already made on for my site "www.iwantphotoart.com" >>slideshow
but i want to add facebook like button tweet and g+ button on slide show

this is my code that have i implemented (i have use fancy box  v 2)

function InitSlideShow() {

```
        $('.fancybox-buttons').fancybox({
            openEffect  : 'none',
            closeEffect : 'none',
            prevEffect : 'none',

            nextEffect : 'none',
            playSpeed :2500,

            arrows    : false,
            nextClick : true,
            helpers : {
               thumbs : {

                    width  : 50,
                    height : 50
                          },
                          buttons   : {}
                        },


            afterLoad : function() {
                this.title = 'Image ' + (this.index + 1) + ' of ' + this.group.length + (this.title ? ' - ' + this.title : '');
            }
        });
```

what i can do next for adding these buttons
thanks in advance

**Comment by fancyapps** [comment]
For v3, see samples for customizing caption - http://fancyapps.com/fancybox/3/docs/#faq
