### ISSUE TITLE
How to set images width to adjust proprtionally in thumbnails

### ISSUE THREAD

**Issue by seigieu** [fancyapps/fancybox#2620]
How do I set thumbs after opening gallery to have always same height, but variable width.
I tried to: 
```
ready: (fancybox) => {
    fancybox.Carousel.slides.forEach(function (element, key){
	    console.log(key, element);
	    var elementhtml = document.querySelector('div.carousel__slide[data-index="'+ key +'"]');
	    var image = new Image();
	    image.src = element.thumb;
	    elementhtml.innerHTML = '<img src="'+ element.thumb +'">';
    })
},
```
It works, however when there are more than 8 thumbnails, they start to load and unload. That's where everything gets messy and thumbs are back to div with background. 

It's either to load all thumbnails right from start (can't find option on how to do it) or find some way to replace them also after each thumb loads. I think i tried above code with all other events with no luck.

**Comment by seigieu** [comment]
So there is no easy way to do it, right?

**Comment by fancyapps** [comment]
Hi,

Sorry, custom width per slide is currently not supported for virtual slides by Carousel. It is planned to add this feature, then thumnail width will be able to resize proportionally. Right now, you can only set fixed dimensions using CSS.

**Comment by seigieu** [comment]
Ok. Thank you @fancyapps . If it's planned, it is planned for when? Any ETA? Months/years/eons? :)
(Should I leave this open or close?)

**Comment by seigieu** [comment]
@fancyapps Also. My solution works. Only problem is when we have 8 or more pictures. Only first 8 is loaded. When I go to 2nd, 9th is loaded and so on. When I'm on 9th. then first is unloaded.

What would really help and made it possible to work, would be a callback in API like `afterThumSlideLoaded` but can't pinpoint such one. Tried all and none seems to fire after thumbnail is added/removed. 
Is there such an event?

**Comment by fancyapps** [comment]
You can always create your own plugin. Take a look at https://github.com/fancyapps/ui/blob/main/src/Fancybox/plugins/Thumbs/Thumbs.js - as you can see, it is very simple by design.

**Comment by seigieu** [comment]
Ok. Thank you very much.
