### ISSUE TITLE
Fancybox iframe with text as src

### ISSUE THREAD

**Issue by stathimexas** [fancyapps/fancybox#2621]
Please tell me how I can display an iframe like this, which uses text instead of a page for src.

`  <a
  src="htmlspecialchars('data:text/html,' "<html><body>some html content here</body></html>")"
  data-fancybox
  data-type="iframe"
  data-thumb="https://lipsum.app/id/28/200x150"
> `

Thank you.

**Comment by fancyapps** [comment]
Hi,

`src="htmlspecialchars('data:text/html,' "some html content here")"` <- What is this? What is htmlspecialchars?

You could try using https://en.wikipedia.org/wiki/Data_URI_scheme, keep in mind character limitation (32,768 characters):

```
<a
  href="data:text/html,<p>Some HTML</p>"
  data-fancybox
  data-type="iframe"
>
  Click me
</a>
```
