### ISSUE TITLE
how can i achieve something like this using fancybox v3 

### ISSUE THREAD

**Issue by ehab01** [fancyapps/fancybox#2623]
how i can implement something like this using fancybox v3 

<img width="253" alt="aaaa" src="https://user-images.githubusercontent.com/25533296/141965987-2a7022c6-f512-4aa8-b1eb-84dde052902f.PNG">

**Comment by fancyapps** [comment]
Hi,

Could you, please, ask a more specific question? If you would remove toolbar, use HTML code for caption to create custom layout, then Fancybox will look very similar.
