### ISSUE TITLE
No menu during slideshow, unless at least one image in gallery

### ISSUE THREAD

**Issue by stathimexas** [fancyapps/fancybox#2625]
I have a gallery, using Fancybox4, in which there are only `"html5video"` data types. It looks like this:

`<a href="https://file1.mp3"
data-fancybox="gallery" 
data-caption="file1"
data-download-src="https://file1.mp3"
data-type="html5video">
file1
</a>`

`<a href="https://file2.mp3"
data-fancybox="gallery" 
data-caption="file2"
data-download-src="https://file2.mp3"
data-type="html5video">
file2
</a>`

Unless I add at least one regular, non-html5video image to the list, the menu does not appear during the slideshow.
Do you have a fix for this?
Thank you.

**Comment by fancyapps** [comment]
Hi,

Have you tried `autoEnable` option? https://fancyapps.com/docs/ui/fancybox/plugins/toolbar#autoEnable

(Maybe it should be called `autoDisable`, choosing a name is not easy :)).

**Comment by stathimexas** [comment]
This did it Jānis. Thank you so much.
