### ISSUE TITLE
Gallery pagination and Fancybox - how to show all thumbnails

### ISSUE THREAD

**Issue by LeManhTuong286** [fancyapps/fancybox#2628]
I have a gallery on my site and I use pagination for images expl. 32 images per page. Im using Fancybox which is working great. The problem is that the thumbnails in FancyBox only shows the thumbnails for the curent paginated site. So if you slide through images only with Fancybox than you don't know that there are actualy more images available unless you go bact to the page and click page2.

Is it possible to view all images in fancybox thumbnails.  
Thank you

**Comment by fancyapps** [comment]
Hi,

You see, you have to tell Fancybox what content to display. If you want to view all images, then ... just do it. Either make hidden links for each gallery item or use `Fancybox.show()` method.
