### ISSUE TITLE
Fade effect not fluent

### ISSUE THREAD

**Issue by robfaas** [fancyapps/fancyBox#263]
When using the fade option (all speeds set to 500) in a gallery, I noticed that the fading works fine in Firefox and Chrome, but in IE9 and Safari (Win) the transformation is not fluent, but very shaky; in visible steps.

In all browsers, after click to the next image, at first the shade and title of the current image dissapear, then the fade-out fade-in of the image takes place, and after the next image has faded in, there is a delay of maybe half a second and then title and the shade appear, wich is not very nice to look at.

Also: in the old Fancybox, when there a next image has a different size, the border -including the shade!- resizes smooth. In Fancyapps it just fades with the image. Is it possible to get the -much smoother looking- resize effect in FancyApps?

See: http://www.fotowebmanager.nl/versie26/?lb=1 (FancyApps 2.0.6)
and  http://www.fotowebmanager.nl/versie25/?lb=1 (Fancybox 1.3.4)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
