### ISSUE TITLE
Disabling swipe/drag in Fancybox 4

### ISSUE THREAD

**Issue by nofx77** [fancyapps/fancybox#2630]
Hi guys, im trying desperately to disable the swipe/drag when I open an inline-content.

This my html : 

`<a href="#" data-fancybox="dialog"  data-src="#modal-hightlights" class="button primary hollow small">Edit</a>`

I try : 
`data-options='{"touch" : false}'` dont work
```
Fancybox.bind("[data-fancybox]", {
    touch: false,
    on: {
        reveal: (fancybox, slide) => {
            modalAfterShow(slide.src, slide.$trigger);
        },
    },
});
```
dont work

What I missing?

Thank you!

**Comment by fancyapps** [comment]
Hi,

If you wish to disable "vertical drag to close" feature, then set `dragToClose: false`. If you wish to disable all touch events, then set:

```js
 Fancybox.bind('[data-fancybox]', {
    Carousel: {
      Panzoom: {
        touch: false,
      },
    },
  });
```
