### ISSUE TITLE
Purchase license for a domain

### ISSUE THREAD

**Issue by haianhxanh** [fancyapps/fancybox#2633]
I hope you are well.

I'm writing to you since I couldn't find an answer on your website. We have an e-commerce store and would like to purchase FancyBox's License for that domain. How can we do it and what would be the cost?

**Comment by fancyapps** [comment]
Hi,

Here you can find all the information - https://fancyapps.com/pricing - and here you can purchase license for Fancybox - https://fancyapps.com/checkout/single/
