### ISSUE TITLE
Reset after upload

### ISSUE THREAD

**Issue by VConsulting** [fancyapps/fancybox#2634]
Hello,
How to empty the upload area after the end of the uploads on the server?

Thank you

**Comment by fancyapps** [comment]
Hi,

You seem to have confused this project with something else.

**Comment by VConsulting** [comment]
Hello,

Not at all.

Once the images are sent to the server, I want them to disappear from the thumbnails of the download management area.

```
            $("#fileUpload").fileinput({
                uploadUrl: "{{ route('medias.store') }}",
                uploadAsync: false,
                browseOnZoneClick: true
            }).on('filebatchuploadsuccess', function (event, data) {
$("#fileUpload"). delete, delete thumbnail ???
            ```

**Comment by fancyapps** [comment]
I can not help you, because I have no idea what are you talking about. This GithHub repository is for Fancybox v3 it has nothing to do with file uploads.
