### ISSUE TITLE
showClass, hideClass and animated not working

### ISSUE THREAD

**Issue by raphaelparent** [fancyapps/fancybox#2636]
**Describe the bug**
I'm trying to change the showClass, hideClass and animated settings without success, meaning that the default animation is always visible. Event like "ready" and "close" are working well.

**To Reproduce**
1. Install fancybox v4.0.23 via npm
2. Import the code with `import { Fancybox } from '@fancyapps/ui';`
3. Import the css in SCSS with the following `@import './node_modules/@fancyapps/ui/dist/fancybox.css';`
3. Use the static `bind` method to add some options to a specific selector.

```
document.addEventListener('DOMContentLoaded', function () {
    Fancybox.bind('.media__link', {
        showClass: false,
        hideClass: false,
        animated: false,
        on: {
            ready: (e) => {
                console.log(Fancybox.getInstance());
            }
        }
    });
});
```

**Expected behavior**
The opening and closing of the fancybox is not animated.

**Desktop:**
 - OS: macOS Big Sur 11.6
 - Browser: tested in Chrome Version 97.0.4692.99 and Firefox 96.0.2

**Comment by fancyapps** [comment]
Hi,

I wonder what is causing you misunderstanding, because everything works as expected, demo - https://fancyapps.com/playground/20d 

You did not say what type of content you are having and you did not provide a live demo, so I assume you tried to disable image zooming, right? You have to set `Image: { zoom: false }` for that.

**Comment by fancyapps** [comment]
@raphaelparent Actually, you should use https://github.com/fancyapps/ui repository for the latest Fanybox and you can discuss here - https://github.com/fancyapps/ui/discussions (Sorry, I haven't found time to post migration notification and put this repository in read-only mode).
