### ISSUE TITLE
fancybox 3.5.7 is not compatible with jquery 3.6.0

### ISSUE THREAD

**Issue by rajeshkannavelu** [fancyapps/fancybox#2643]
As part of security concern, I have upgraded jQuery 3.6.0 and facncybox 3.5.7. 
The fancybox popups are not loading and no model popups are working as expected. Then I added jQueryMigrate 3.3.2 even that is also not helping.

Any suggestions or support would be really helpful.

Thanks!

**Comment by fancyapps** [comment]
It works fine, demo - https://jsfiddle.net/6vsb45w0/
