### ISSUE TITLE
Fancybox4 fullscreen on mobile

### ISSUE THREAD

**Issue by stathimexas** [fancyapps/fancybox#2646]
Hi Janis. Is there fullscreen mode on a mobile, such as an iphone?

**Comment by fancyapps** [comment]
Hi,

The script uses Fullscreen API - https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API - to toggle fullscreen mode and automatically disables self (e.g., hides fullscreen toggle button) if that API is not available. Right now, that API is available on iPads and not on iPhones (https://caniuse.com/fullscreen)
