### ISSUE TITLE
placing a close link in the lightboxed frame

### ISSUE THREAD

**Issue by halukkaramete** [fancyapps/fancybox#2648]
We all know what this is.. 
<img width="927" alt="Screen Shot 2022-04-19 at 8 30 44 AM" src="https://user-images.githubusercontent.com/4029735/163926562-2470e7f6-d886-4f08-9a64-b8d8a699a0f1.png">

It just closes the iframed content

What if I want to place a "close button" or a "link" on the iframe content itself as a second way of closing? 
**How do I do that?** 

I copy pasted this into the iframe but that does nothing. 

`<button data-fancybox-close="" class="fancybox-button fancybox-button--close" title="Close"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 10...."></path></svg></button>` 

Where does this get handy? 
On mobile, the thumb could be so much more closer to a properly placed custom close button than the one on the top right corner which I just shared the image of above.

**Comment by fancyapps** [comment]
Hi,

Here is an example for Fancybox v4+ - https://codesandbox.io/s/fancybox-iframe-k4i41?file=/iframe-1.html

```jsx
<button onClick="window.parent.Fancybox.close();">Close</button>
```

For v3, use appropriate API method -
```js
parent.jQuery.fancybox.getInstance().close();
```

https://web.archive.org/web/20210325170940/https://fancyapps.com/fancybox/3/docs/#iframe

**Comment by halukkaramete** [comment]
EXCELLENT.

This reply also opened my eyes as to how to access the parent function from
the lightbox.

parent.myFunction !
