### ISSUE TITLE
placeFocusBack not working on data-fancybox-trigger

### ISSUE THREAD

**Issue by knstyle** [fancyapps/fancybox#2654]
As the title. `placeFocusBack: true` only works on `data-fancybox`
Is there any solution or will this be fixed in the next update?

**Comment by fancyapps** [comment]
Hi,

Could you, please, create a simple demo using any playground (Codepen,Jsfiddle,...)?

**Comment by knstyle** [comment]
Hi, here's the demo https://fancyapps.com/playground/3g6
I changed the 3rd image to `data-fancybox-trigger`
After opening and closing the gallery using keyboards, the focus goes back to the first element of the page.

**Comment by fancyapps** [comment]
Hi,

This has been fixed in v4.0.30. Thanks for the reporting!
