### ISSUE TITLE
 Links events don't work inside a fancybox modal

### ISSUE THREAD

**Issue by joshwedo** [fancyapps/fancybox#2655]
Hi!

I'm having a problem with fancybox version 3.5.7.
I have implemented a modal in the cart page of my store, with product content and links to add to the cart and another to direct to another page. But the links have no action on click. It seems as if pointer-events is disabled.

Can you help me? Thank you!!

**Configuration:**

```
  $(".fancybox").fancybox({
      type: 'iframe',
      'transitionIn'	:	'elastic',
      'transitionOut'	:	'elastic',
      'speedIn'		:	600,
      'speedOut'		:	200,
      'overlayShow'	:	false,
      'touch'		: 	false
  });
```

**Modal:** 

```
<a class="btn-modal" data-fancybox data-src="#modal-prueba" style="display: none;">Text Button</a>
<div id="modal-prueba" class="content-item modal-prueba fancybox" style="display: none;">
	<div class="container">
		<div class="row">
			<div class="info-modal">
				<h3 style="font-size: 38px;margin-bottom: 10px !important;color: #fff;">Title</h3>
				<p style="font-size: 22px;margin-bottom: 0;color: #fff;">Subtitle</p>
				<a href="https://github.com/" style="color: #ffe76f;">Link</a>.
			</div>

                        ...

            </div>
      </div>
</div>
```

**Comment by fancyapps** [comment]
Hi,

Sorry, but it is not possible to help you without seeing a live page/demo. It should work fine.

**Comment by joshwedo** [comment]
I attached the url of the page.

It is on the checkout page, you must first have a product in the cart.

https://farmahogar.com/realizar-pedido/

**Comment by fancyapps** [comment]
The problem is that the way you are using Fancybox is completely wrong. Look at this - 

```js
jQuery("#modal-pequenos-precios").fancybox({'overlayShow': true}).trigger('click').delay(5000);
```

Why on earth you have this weird code. You have to write something like this:

```js
$.fancybox.open({
	src  : '#modal-pequenos-precios',
	type : 'inline',
	opts : {
		//
	}
});
```

Because you tell Fancybox to open an element and, when clicking your element, open it again. Therefore links do not work as you expect.

**Comment by joshwedo** [comment]
Okey.

I generated that line with a trigger function so that the modal opens automatically without the need to click on the button.

What way would I have to be able to do it without this strange code?

**Comment by fancyapps** [comment]
My code snippet shows how to immediately open the modal (e.g., `$.fancybox.open(...)`)
