### ISSUE TITLE
508/ADA Compliance

### ISSUE THREAD

**Issue by crasx** [fancyapps/fancyBox#273]
Is there any plan to make this library accessible?

**Comment by Elizabethandesign** [comment]
Did anyone develop a solution for this? I'd also like to add Aria roles to the navigation. It's not obvious there are keyboard controls to the AT user. The usual approach is using Tab, but tab-ing just navigates through the grayed-out page behind the fancybox.

**Comment by fancyapps** [comment]
v3 has some improvements. Comment, if there is something missing.
