### ISSUE TITLE
What about a Sass-yfied version of your CSS ?

### ISSUE THREAD

**Issue by MoOx** [fancyapps/fancybox#276]
I can work on it, to deliver fancybox as a Sass/Compass plugin via Rubygem. Are you interested in that ?

**Comment by soulcreate** [comment]
why closed?

**Comment by MoOx** [comment]
> MoOx opened this Issue on Jun 11, 2012

2015, still no comment from the owner...

**Comment by soulcreate** [comment]
any alternative?

**Comment by MoOx** [comment]
These days I use React and inline styles, so not really...
