### ISSUE TITLE
can't scroll content on ajax "modal" on mobiles

### ISSUE THREAD

**Issue by matsaukeo** [fancyapps/fancyBox#302]
Hi

Perhaps there is a way to do this but I can't work it out:

I'd like to load another page into the box using ajax. This works OK but the height is the window height and not the height of the content. I can change the height parameter to "auto" but then the width is broken. 

Ideally I'd like the modal window to be 100% of the width of the screen and 100% height of the content of the page it is loading.

Does that make sense? Is this not possible?

Thanks!

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
