### ISSUE TITLE
zooming on Blackberry

### ISSUE THREAD

**Issue by matsaukeo** [fancyapps/fancyBox#303]
Firstly let me say how impressed I am with fancybox2, secondly I know the roadmap says "mobile" as a future feature.

However, I've tested the current fancybox on a responsive website on various dimensions and can't see why I wouldn't use this on mobile. Perhaps it should be disabled for feature phones which might mess things up.

Anyway - the only slight niggle I had was that on the blackberry, if you open a photo in the fancybox and then zoom in, it sort of sticks to the edge/messes up. On IOS and android 2.3.4 it works really well. In fact the zoom is fantastic as the photo opens at full width and then I can zoom in to see bits in detail.

I don't think this is a real show stopper, just something you may want to look at if you do try and make it more mobile friendly. Its the first thing my boss did when I asked him to pay the licence.

I also tried it on windows phone 7 and it worked fairly well - just a small issue with the overlay div only going as high as the viewport width and the stupid address bar over the photo caption (address bar at the bottom on this phone)

Thanks!

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
