### ISSUE TITLE
Flickering on click

### ISSUE THREAD

**Issue by iditude** [fancyapps/fancybox#308]
Hello,

I'm trying to implement fancybox with rich content (i.e. a div with several options and clickable items to move an image).

This rich content requires clicks to animate.

The problem is that everytime a click is pressed, then fancy box flickers in black.

I've created this simple test case... try to click anywhere and see the flickering.

I've tested it on Safari (mac) and IE 8 and 9 with the same result.

``` html
<html>
<head></head>
<body>



<script src="include/fancybox/jquery-1.7.2.min.js"></script>

<link rel="stylesheet" href="include/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
<script type="text/javascript" src="include/fancybox/jquery.fancybox.pack.js"></script>
<link rel="stylesheet" href="include/fancybox/helpers/jquery.fancybox-buttons.css" type="text/css" media="screen" />
<script type="text/javascript" src="include/fancybox/helpers/jquery.fancybox-buttons.js"></script>
<script type="text/javascript" src="include/fancybox/helpers/jquery.fancybox-media.js"></script>

<link rel="stylesheet" href="include/fancybox/helpers/jquery.fancybox-thumbs.css" type="text/css" media="screen" />
<script type="text/javascript" src="include/fancybox/helpers/jquery.fancybox-thumbs.js"></script>



<div class="fancybox2" style="width:500px; height:500px;">
      <a class="fancybox" href="public/examples/image-4.jpg" rel="group" title="my caption4"><img src='public/examples/thumb-4.jpg' width="80" border="0"/></a>

</div>







<script type="text/javascript">
$(document).ready(function() {
    $(".fancybox2").fancybox();
    });
</script>




</body>
</html>

```

Any ideas on how to avoid that behaviour?

Thanks guys

**Comment by TenSketch** [comment]
> Are you looking for something like this http://jsfiddle.net/96eq9/2/ ?

I'm not sure how to implement this in my code done using Hugo:

`<div class="masonry">
            {{range .Resources.Match "gallery/*" -}}
            {{ $image := . }}
            <div class="masonry-item">
                <a data-fancybox="gallery" href="{{.RelPermalink}}" aria-label="{{.Name}}">
                    <img data-src="{{ $image.RelPermalink }}" class="masonry-content lazyload" alt="{{.Name}}">
                </a>
            </div>
            {{- end }}
        </div>`
