### ISSUE TITLE
vertical position is incorrect on ios for long pages

### ISSUE THREAD

**Issue by timotheeg** [fancyapps/fancybox#33]
Hi there, 

I'm trying out fancybox and I am having an issue for ios devices (tested on my ipad2 and iphone 3GS) ... browser specific obviously.

On a long vertical page, the popup box is always positioned as in the viewport was showing the top of the page. Meaning if I am way down the page, I can see the semi-transparent black overlay over everything upon click, but I actually have to scroll back all the way up the page to see the popup box.

This was tested using fancybox 2.0.3 .

On the desktop, I've tested chrome and FF, on linux and osx and had no problem.

Thanks,
Tim.

**Comment by Liverson** [comment]
i got the same issue with fancybox 3.4.0. When i open another fancybox instance (image or iframe) from inside a long fancybox iframe the nested fancybox content is out of sight.

E.g. the whole iframe has 5000px height, the Y-Pos of the trigger-link is 4000px, fancybox is positioning the nested content vertical centered of the whole iframe height, but my current scroll position is in that case 4000px, so i cant see the content.

This only happen on iPhone|iPad, on Android and Desktop-Browsers all is fine. I tried to repositioning afterLoad, but then i got other ugly issues.

Has anyone a working fix?

**Comment by fancyapps** [comment]
@Liverson Works fine for me, so I do not know what to fix.

**Comment by Liverson** [comment]
@fancyaps i don´t know this issue happen to me and i cant find out why. I tested this with a clean test and no individual adjustments.
Anyway meanwhile i changed the call of the parent fancybox to AJAX, now the child fancybox works on iOS as expected.

But i found another small issue: 
when i open fancybox with html-content via AJAX, **sometimes** on iOS you can´t scroll (swipe) the fancybox content. After some debugging if found out this condition prevents from scrolling although there is no current zooming or closing?

// Ignore clicks while zooming or closing
    if (!current || instance.isAnimating || instance.isClosing) {
      e.stopPropagation();
      e.preventDefault();

      return;
    }

After commenting out 
//e.stopPropagation();
//e.preventDefault();

the content can always be scrolled. Other issues did not arise from commenting out, at least I have not noticed any.
