### ISSUE TITLE
Image not opening in viewport but the top of the site on Windows Phone

### ISSUE THREAD

**Issue by elemis** [fancyapps/fancyBox#338]
Hi,

We use fancybox on a template of ours and recently a client mentioned an issue with Windows Phone: 

"I’m having an issue on my Windows Phone browser viewing the fancybox gallery. Its opening the image I click on at the very top of my site."

You can check the mentioned template here: http://themes.iki-bir.com/locusv4/light.html (Please go to the "Portfolio" section to test fancybox)

We've seen that a similar issue was available with Android but it was solved by updating the script to the latest version. But we already use version 2.0.6. 

Can there be a fix for this?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
