### ISSUE TITLE
fancyBox adding css to my page body

### ISSUE THREAD

**Issue by gavsiu** [fancyapps/fancybox#347]
It seems unnecessary and was not in 2.0.6.

fancyBox 2.1.0 adds 'style="margin-right: 17px;"' to my page body when I open an overlay. Everytime I open the overlay, my page in the background squeezes to the left because of the added margin.

I believe it's supposed to be the calculated width of my scrollbar.

**Comment by dilip-pmap** [comment]
I have fancybox Issue  in Ipad regarding footer is not fixed position

I used following code for scrolling in ipad 

@media(max-width:1024px) {
overflow: auto !important
-webkit-overflow-scrolling: touch !importanr
}

Anyone can help me out how to fix my footer in Ipad (Position: fixed)

**Comment by archieDeveloper** [comment]
@fancyapps Hi, I have the same problem with fancybox 3, how can I solve it?

**Comment by fancyapps** [comment]
@archieDeveloper Please, do not comment is old post. And try to be more specific.
