### ISSUE TITLE
form label text remains hidden on pages inside iframe using IE7

### ISSUE THREAD

**Issue by myTinCart** [fancyapps/fancyBox#349]
fancyBox Version: 2.0.6

We have asp.net form that appears inside of an iframe.  The form itself works perfectly, as does the label text for each input field.

However, when this form is loaded as an iframe using fancybox using IE7, the top and bottom-most labels remain hidden.  The form fields appear, but the labels are gone.  refreshing the iframe after it has been launched corrects the issue, but it returns after closing the pop-up and re-opening.

Thus, there appears to be some sort of style conflict with regard to how some labels are displayed.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
