### ISSUE TITLE
Fancybox shifts absolute/fixed positioned elements

### ISSUE THREAD

**Issue by collideous** [fancyapps/fancyBox#360]
Page elements that are positioned to the right either with **position: absolute;** or **position: fixed;** will shift to the right when a Fancybox opens. Possible fix: add the **right-margin** that is applied to the **body** to such elements as well. 

Example: http://jsfiddle.net/hkDnQ/

**Comment by mrlecerf** [comment]
Hi, 
After a week of research, I find a way to fix this issue.
Firstable, you have to find the place where Fancybox add the class .fancybox-margin which add a margin-right : 15px to the element and cause the jump on fixed elements.

In my case it was in a class named .main-navigation

Then, in my CSS, I wrote something like this : 

.main-navigation.fancybox-margin {
	padding-right: 15px;
	}

That's fix the issue for me, maybe it could help.

**Comment by autotheist** [comment]
Thank you for your help. :)

**Comment by amichel86** [comment]
Awesome, the padding-right solution worked for me too (17 now instead of 15) :)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3. About shifting fixed/absolute positioned elements - http://fancyapps.com/fancybox/3/docs/#faq

**Comment by cupok** [comment]
> Hi,
> After a week of research, I find a way to fix this issue.
> Firstable, you have to find the place where Fancybox add the class .fancybox-margin which add a margin-right : 15px to the element and cause the jump on fixed elements.
> 
> In my case it was in a class named .main-navigation
> 
> Then, in my CSS, I wrote something like this :
> 
> .main-navigation.fancybox-margin {
> padding-right: 15px;
> }
> 
> That's fix the issue for me, maybe it could help.

WOW. Its fcking best solution. Thank you!

**Comment by k-majick** [comment]
Easiest solution that worked for me - first add:
```
html {
  overflow-y: scroll;
}
```
and then:
```
.compensate-for-scrollbar {
  margin-right: 0 !important;
}
```
Voila :)

**Comment by wjs500** [comment]
> Easiest solution that worked for me - first add:
> 
> ```
> html {
>   overflow-y: scroll;
> }
> ```
> 
> and then:
> 
> ```
> .compensate-for-scrollbar {
>   margin-right: 0 !important;
> }
> ```
> 
> Voila :)

Easiest and most functional solution IMHO! Thank you!
