### ISSUE TITLE
type can't be detected which leads to silent quit

### ISSUE THREAD

**Issue by spidgorny** [fancyapps/fancyBox#369]
On http://wagner-verlag.de/spielzeug.php?id=203&t=Der_Dativ_ist_dem_Genitiv_sein_Tod fancybox was unable to identify "image" type although "a.fancybox" did exist.

```
jQuery(document).ready(function() {
            jQuery("a.fancybox").fancybox({
                transitionIn: "elastic",
                transitionOut: "elastic"
            });
        });
```

Rather dump patch (I don't know fancybox source, before line 288):

```
            if (element.is('a')) {
                obj.type = 'image';
            }

            href  = opts.href  || obj.href || (isString(element) ? element : null);
            title = opts.title !== undefined ? opts.title : obj.title || '';
```

It was quitting at 858: if (!type) {
without any error message contrary to what documentation says:

Note! If fancyBox will not be able to get content type, error message will be displayed (this is different from previsous versions where 'ajax' was used as default type).

**Comment by fancyapps** [comment]
Hi, good point. But, in my experience, users who face this problem, usually does not know how to use developer tools.
