### ISSUE TITLE
Additional images for each main image?

### ISSUE THREAD

**Issue by petze** [fancyapps/fancybox#373]
I have main main gallery, and I want to cycle through these images as usual with the left/right keys. Each image, however has multiple additional images for which I currently show small thumbnails in a [ul] tag which I added right under the title line. I now just need to be able to replace the main image with the new one when the user clicks on one of the thumbnails and then reload so that the size gets re-adjusted to the dimensions of the new image. Can this easily be done, or is there another way to get this behavior?

As I said I still want to be able to cycle through the 'main' images with left/right, and only display one of these additional images when the user click it.

**Comment by fancyapps** [comment]
I`m sorry, but your scenario seems to bee too complex. 
With v3 you can display new gallery on top of the current one with ease.
