### ISSUE TITLE
overlay not removed after close

### ISSUE THREAD

**Issue by markusweb** [fancyapps/fancybox#385]
i have load fancybox with iframe content  via javascript

```
function aboCheck(url) {
    $.fancybox({ href: url, title : 'Veranstaltungs-Abo', type: 'iframe', height: 700, width:880 });
   return false;
}
```

this is triggered from an select option. everything works so far. the html-page is being loaded.

but when i know klick on the close -button the iframe is being removed, but the main page will not come back. also the esc-key is not working. 

the following div stays:

```
<div class="fancybox-overlay fancybox-overlay-fixed" style="width: auto; height: auto; display: block; opacity: 1;"></div>
```

so i see the main page with the grey overlay but i cant do anything on the page.

i am using the latest version of jquery.fancybox.js

**Comment by digitalhuman** [comment]
I have the same issue now. Overlay is not removed when fancybox closes. Also; the afterClose event is also not fired when using parent.$.fancybox.close(true);

Any idea what this can be? I open fancybox like this:

```
$(".fancybox").fancybox({
        type:       'iframe',
		fitToView	: true,
		width		: '100%',
		height		: '100%',
		autoSize	: false,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none',
        scrolling   : 'auto',
        preload     : true,
        afterClose  : function(e){           
                console.log('Closing fancybox');                            
        },
        beforeClose : function(){            
        },
        afterLoad  : function(){
        },
        afterShow   : function(e){            
        }
    });    
```

**Comment by AkselMJ** [comment]
https://codepen.io/anon/pen/WGVVjq
