### ISSUE TITLE
Opening overlay manually

### ISSUE THREAD

**Issue by c-schwan** [fancyapps/fancybox#396]
He,

after closing the site is jumping back to the top.

Why do you set the body to overflow hidden?

fancybox.showLoading() is not showing the overlay. We need this for eCommerce add to Cart function.

We already tried to put the request to beforeLoad function but that doesn't work.

Thx

**Comment by nreal-mi** [comment]
$.fancybox.helpers.overlay.open({parent: $('body')});
worked for me.
Thanks Guys

**Comment by Erikjhons** [comment]
.fancybox.helpers.overlay.open({parent: $('body')});
Yes, it works very well.
Thanks.

**Comment by aadilhussain** [comment]
.fancybox.helpers.overlay.open({parent: $('body')});
Yes, it works very well.
+1 I am looking for same
