### ISSUE TITLE
how to disable scrolling completely when fancybox is open?

### ISSUE THREAD

**Issue by sweetman-zz** [fancyapps/fancyBox#407]
Hi all,
I have a very long page that uses a mechanism similar to the nikebetterworld parallax effect.
So, it's important to go back to the same portion of the page you visited before opening any fancybox.
The latest version (2.1.1) seems to solve this issue, but only marginally.
In fact, while on most desktop windows browsers it seems to work, there are condition when it doesn't work:

Examples: 
While the fancybox is open the simple mousewheel will not scroll the overlay. But if you click the mousewheel and then drag the mouse up and down, the overlay will scroll.

Using a macbook pro is even simpler to scroll the overlay while it shouldn't: just use two fingers and swipe them from top to bottom or vice versa: the overlay will scroll freely.

So, my question is: is there a way to disable completely the scrolling? I can't find a simple tutorial to integrate such a feature in my page.

Fancybox is the most versatile lightbox alternative and so, kudos to the developer and to this community.

Now powerbooks and touch device are all around and touch gestures will extend their diffusion every day (windows 8 is around the corner).
Hope to see these features fixed in the next fancybox revision or version.

TIA

tony

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
