### ISSUE TITLE
Prev & Next animations cause "problems" in IOS6

### ISSUE THREAD

**Issue by rnicholus** [fancyapps/fancyBox#411]
If I use the default values for `nextEffect` and `prevEffect` in Safari on IOS6, when clicking on the prev or next buttons (or clicking on the image if `nextClick` is set to true), the lightbox jumps around the page a bit and sometimes either lands off-center or is no longer viewable.  Turning off these animations seems to be a workaround.  I am unfortunately using some code that is supposed to detect if the user-agent is running on a mobile platform, so I'm only disabling these animations in this case.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
