### ISSUE TITLE
Ipad Issues ... and a bit more...

### ISSUE THREAD

**Issue by gojo23** [fancyapps/fancyBox#423]
Hi there,
I am having difficulties making the gallery forward and next arrows clickable on the iPad. I've downloaded the latest Fancybox.

I was wondering if you could take a look for me please.
Here's the url:
http://www.spiralpixelthemes.co.uk/flexi/bb/index.html

The gallery is on the carousel....

Also on my laptop when an image is clicked it's shifting my menu over. I'm sure it's something to do with  y-scroll but I cant figure it out!

Any help would be greatly appreciated.
I look forwards to your reply.
Kind regards,
Jo

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
