### ISSUE TITLE
Scroll functionality gone after closing a lightbox

### ISSUE THREAD

**Issue by williamgill** [fancyapps/fancyBox#427]
Hi,
I am using a fairly standard fancybox implementation to display images.
I notice that after closing the lightbox, two strange things happen:
1: the black shadow does not disappear. You have to click one more time on the screen to make the shadow overlay disappear. 
2: once you click again to remove the shadow overlay, the scroll functionality on the page is completely gone. I've tested and confirmed this in Chrome, IE and FF.

Has anyone else seen this issue? Is there a fix?

My script to load fancybox:

//Load Fancybox lightbox
            $(document).ready(function() {
                $(".fancybox").fancybox({
                    openEffect  : 'fade',
                    closeEffect : 'fade'
                });
            });

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
