### ISSUE TITLE
Overlay missing and fancybox not centered in viewport after upgrade to 2.1.3

### ISSUE THREAD

**Issue by mtowers** [fancyapps/fancybox#438]
I upgraded our fancybox today from 2.0.6 (version: 2.0.6 (Tue, 12 Jun 2012) to 2.1.3.  After upgrading, when I open fancybox (ajax), there is no overlay and the box always opens 20 px from the top of the page instead of centering it in the viewport.

I attempted to debug it and it seems that part of the problem may be that the height of the overlay is getting set to 0 but I can't say for sure.

Any ideas?

Thanks!

**Comment by fulopattila122** [comment]
Was this ever reproduced or resolved? I'm just having the same issue (2.1.5)

**Comment by fancyapps** [comment]
Have you updated the css file?

**Comment by fulopattila122** [comment]
No. But I have resolved it by setting explicitly the overlay.locked property:

```
helpers: {
                overlay : {
                    locked: true
                }
            }
```
I don't know what the exact cause was, I was scanning for like 2 hours if any other css rule gets applied but haven't found such thing.
