### ISSUE TITLE
thumbnail helper not compatible with jQuery.noConflict(); !!

### ISSUE THREAD

**Issue by nicmare** [fancyapps/fancybox#44]
links look like this:
javascript:$.fancybox.jumpto(0);

instead of this:
javascript:jQuery.fancybox.jumpto(0);

**Comment by woohling** [comment]
When using webpack, `javascript:jQuery.fancybox.jumpto(0);` jQuery is not defined.  Still haven't found a way to fix this problem, much headache 😥
