### ISSUE TITLE
live option not triggered? (working with jquery.slice)

### ISSUE THREAD

**Issue by Garbanas** [fancyapps/fancyBox#448]
Using:
fancyBox version: 2.1.3
jQuery version 1.7.1
Chrome version 23

I believe this is more of a general problem in how selectors are handled.
After "$.fn.fancybox = function (options) {", Line 1906:
selector is set to ".class-to-container a.slice(1)" (as an example)
In "what = selector.length ? $(selector) : that;" on line 1924, selector.length is always > 0

Please make some tests by yourself, because {live : false} really doesn't seem to be working as it should.

A workaround could be to write
what = (options.live===false || !selector.length) ? that : $(selector);

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
