### ISSUE TITLE
Fancybox should have a lightweight version

### ISSUE THREAD

**Issue by yairEO** [fancyapps/fancyBox#454]
jquery.fancybox.js is almost 50k (!!!!!)

this is a great plugin, but really a 5k down to the bone version would be more appropriate, only the bare minimum

**Comment by fancyapps** [comment]
I`m sorry, but there is nothing much I could do. 50kb might sound a lot (especially. if you remember 90ties :smile: ), but you could use, for example, cdnjs.com. Or building your own version excluding unnecessary modules (if using v3).
Sure, I could write compressed, spaghetti code, but that would be unreadable and unmaintainable.
