### ISSUE TITLE
HD Youtube SWF Video Embed (720p)

### ISSUE THREAD

**Issue by freaktrap** [fancyapps/fancybox#456]
Hello, it appears that the only way to get fancyBox to autoplay an embedded video at 720p by default without enlarging the iframe width/height beyond 720/1280 is to add the 'vq=hd720' command line variable to the request string.

This can be done by default by modifying jquery.fancybox-media.js to add the following after line 97:

```
                    vq          : 'hd720',
```

Perhaps there should be a parameter on fancybox to facilitate this effect.

**Comment by fancyapps** [comment]
Sorry, YouTube embed now uses HTML5 video and looks like it does not accept that parameter.
