### ISSUE TITLE
Parent page scrolls to top when fancybox link clicked

### ISSUE THREAD

**Issue by robetmanski** [fancyapps/fancyBox#457]
Is it possible to prevent the parent page from scrolling back up to the top when you click to activate fancybox? I have a relatively long page with a button to call fancybox approx. half way down and I'd like to leave the page where it is so when the user closes the fancybox the parent page is where they left it.

Edit - this seems to only happen in webkit browsers (Chrome, Safari).

**Comment by ccasalicchio** [comment]
This hack has also resolved it for me... is it possible to include an option for it in the next version?
(fancybox rules though!!!)

**Comment by tojopaul** [comment]
My issue solved .Thanks @filek  👍

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by AncutaDaniel** [comment]
Thank you it works!!! @filek !!

**Comment by muneebbug** [comment]
If anyone still looking for solution then here's what i did. i changed <a></a> to <button></button>.
Hope it helps :)
