### ISSUE TITLE
Problems in IE8

### ISSUE THREAD

**Issue by DrQuery** [fancyapps/fancyBox#462]
Hi

I have a problem with IE8 or adding the following line to the html:

```
<meta http-equiv="xX-UA-Compatible" content="IE=8" />
```

In this case, the opacity in background doesn't work, when there are others jquery plugins that work fine, like for example lightbox and pirobox.

Could you repair this?. Your plugin is the best that i saw on the net.

Thanks!

**Comment by fancyapps** [comment]
Sorry, IE8 is not relevant nowadays.
