### ISSUE TITLE
iOS scrolling issue - AJAX content requires light touch, page moves

### ISSUE THREAD

**Issue by ururk** [fancyapps/fancyBox#469]
On the iPad, horizontal view, looking at the demo page:

http://fancyapps.com/fancybox/#examples

Various Types > Ajax

The content is longer than the fancybox, and no scrollbar appears. In order to scroll the content within the lightbox, you need to be very deliberate for iOS to scroll the text (press, wait, move finger). Additionally, touch+move on the overlay moves the page. I was able to disable the touch+move like so:

``` javascript
    $('body').on("touchmove", '.fancybox-overlay', function(event){
        event.preventDefault();
    }); 
```

but this does not help improve the content's ability to be scrolled.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
