### ISSUE TITLE
Fancybox gallery does not show images when closed and opened again

### ISSUE THREAD

**Issue by Malcr001** [fancyapps/fancyBox#474]
On firefox 17.0.1 (on mac) when I click on an image for the first time fancybox works just fine however when I close fancybox and open it again it just displays the black overlay and no image. This problem happens all the time. 

Looking at the problem on firebug the image still exists however css the class .fancybox-tmp is being applied which has css left: -99999px; top: -99999px; which is pushing the image outside the users viewport.

Please address this problem asap.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
