### ISSUE TITLE
Ajax Won't Work After First Click

### ISSUE THREAD

**Issue by streamofthought** [fancyapps/fancyBox#478]
I have 3 buttons set to display some simple html using fancybox2.  The first loads just fine, but after the first click (sometimes after the 2nd or 3rd), no other fancybox will load.  Here is some really simple code that I am using:

a href="box-icon2.png" class='lightbox'>Algebra</a>
a href="excellence.html" class='lightbox fancybox.ajax'>Calc</a>
a href="excellence.html" class='lightbox fancybox.ajax'>Diff Eq</a>

with an inline script:
script type="text/javascript">
$(function() {
    $('.lightbox').fancybox();
});
/script>

I've checked the other issue listings and 2 others have had the same problem, but theirs was specific to Wordpress.  I tried "live: false" as I've seen in other posts, but no dice.  Any ideas?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
