### ISSUE TITLE
keys argument is not handled properly

### ISSUE THREAD

**Issue by jgehrcke** [fancyapps/fancyBox#482]
I'm using version 2.1.3. With the fancybox argument

```
keys: {close: [27]}
```

the space bar still triggers slideshow play. I expect the `keys` argument to override the defaults entirely. This was already discussed in https://github.com/fancyapps/fancyBox/issues/153.

**Comment by fancyapps** [comment]
Sorry, keys options is removed in v3. If you really wish, you can bind your own.
