### ISSUE TITLE
don't close on FF 18 - win7, but an help...

### ISSUE THREAD

**Issue by gbonline** [fancyapps/fancyBox#484]
Hi, i tried the last versin of fancybox from the site fancyapps, but the examples on the home page won't close when i click on the X when i try on win7-FF18 just updated. 
all work on ubuntu 12.04 and FF18!
so on win7 i've tried the debugger of FF18 and i've taked the picture of my desktop during the debug session. i hope this could be comprensible because it's in italian.
the debugger stop for an exception domException (see on the right) for nt.matchesSelector (see on left) on file jquery.min.js - i invite to try yourself
i hope this help!
![Immagine_exception](https://f.cloud.github.com/assets/3273873/67332/50466314-5efa-11e2-9b0f-5cd56c99b565.png)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
