### ISSUE TITLE
Remove $.browser checks to enable support for jQuery 1.9

### ISSUE THREAD

**Issue by daneah** [fancyapps/fancybox#485]
I realize the documentation suggests linking jQuery 1.8, but for anyone linking to the latest jQuery fancyBox is now broken. jQuery 1.9 removed the $.browser functionality and fancyBox breaks when trying to check if $.browser.msie is true.

**Comment by baszero** [comment]
Is there any solution for the combination Fancybox 1.3.x and jQuery 1.9+ (actually I want 1.11) ? Fancybox 2 is not free of charge anymore... So I want to stick with 1.3.x

**Comment by SalahAdDin** [comment]
But, aren't you using the latest fancybox release version? The 3.0 version branch work for you?
Please, re open this issue.

**Comment by baszero** [comment]
**ALTERNATIVE**: For all people having the same issues with 1.3.4 and jQuery 1.9+: you can switch to a very similar (and 100% equally good and free) alternative: http://dimsemenov.com/plugins/magnific-popup/

I am now using that "lightbox" and it works like a charm with jQuery 1.11 and it is also free.

**Comment by SalahAdDin** [comment]
It's sad that this repository is "dead".

**Comment by baszero** [comment]
It's ok to switch from opensource to a commercial version (see Fancybox 2). But as said, you can very easily switch to Magnific Popup, looks actually a lot more modern out of the box than the Fancybox.
