### ISSUE TITLE
Overlay not appearing in iOS

### ISSUE THREAD

**Issue by sheriffderek** [fancyapps/fancyBox#487]
The overlay is not appearing in iOS. A couple of my recent projects use fancy box and everything works great except the overlay in iOS. Any ideas on this?

Here is an example site. See players and makers links for inline and see the gallery at the bottom for images example.

http://murderdollhouse.com   ( oh and this is my code - incase I have made a mistake. )

```
$('.fancy-inline, .fancy').fancybox({
    padding: 0,

    openEffect : 'fade',
    openSpeed  : 'fast',

    closeSpeed  : 'fast',
    closeClick : true,

    helpers : {
        title : {
        type : 'none'
        },

        overlay : {
            css : {
            'background' : 'rgba(0,0,0,.9)'
            }
        }
    }
});
```

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
