### ISSUE TITLE
Ajax wrong height

### ISSUE THREAD

**Issue by ivoviz** [fancyapps/fancyBox#494]
Hey,

I'm not sure if it's a bug or I'm doing something wrong but.. Here is the code I'm using:

```
$('.more-info').fancybox({
    maxWidth: 560,
    closeClick: false,
    openEffect: 'none',
    closeEffect: 'none'
});
```

It loads the ajax content just fine, no problem with that. The problem is the 'fancybox-inner' div sometimes have incorrect height. I really can't find any way to reproduce it, it's just random... I can click on the first 5 links without problem and then the 6th one is just way too small. But then again, it's random. Also if I reopen one that had wrong height at first it's height is good from that point no matter how many more times I reopen it.

Any suggestions?

Edit: It seems like it's only happening when I have images in the loaded div.

**Comment by fancyapps** [comment]
See #800
