### ISSUE TITLE
keep parent from scrolling

### ISSUE THREAD

**Issue by sweetman-zz** [fancyapps/fancyBox#502]
Hi all,
I'm using Fancybox 2.1.4 and I have several customers that complains because the parent content will scroll when the use two fingers on their notebook touchpad to scroll content.
The same happens when you press the up/down arrows on the keyboard.
The parent doesn't scroll only when you use the mousewheel (only if you don't press the mousewheel button).
Is there a way to IMMOBILIZE the parent content while fancybox is open?
TIA
tony

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
