### ISSUE TITLE
fade effect reveals background

### ISSUE THREAD

**Issue by jami1955** [fancyapps/fancyBox#510]
Simple slideshow, however as one pic fades into the next, the first fades completely revealing the background page before the next is fully there. I'd like no background present at all during the fades. See it here: http://jamiestclair.com/photography/north-germany-landscape-photos/

 Code:
$(document).ready(function() {
            $('.fancybox-buttons').fancybox({
                autoPlay : true,
                openEffect  : 'fade',
                closeEffect : 'fade',
                nextClick   : 'true',
                prevEffect : 'fade',
                nextEffect : 'fade',
                playSpeed : 4000,
                nextSpeed : 700,
                closeBtn  : true,
                helpers : {
                    title : {type : 'inside'},
                    buttons : {}
                },
                afterLoad : function() {this.title = 'Image ' + (this.index + 1) + ' of ' + this.group.length + (this.title ? ' - ' + this.title : '');}
            });

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
