### ISSUE TITLE
Thumbnail Helper - is there a way to position the thumbnails other than at the bottom?

### ISSUE THREAD

**Issue by sbenes** [fancyapps/fancyBox#52]
I was just curious as I did not see any options in the code with a quick glance to position the thumbnails.  Some of the designs we get have thumbnails relative to the box and would be nice if there were options to have the wrapping div either inside or outside of the fancybox container.

Thanks!

**Comment by Konstantinusz** [comment]
```
Hello,
I was wondering if it is hard to make thumbnail helper to be vertical not horizontal? or maybe somebody already made that? lets say on the left or right side. that should be more effective space usage on the widescreens and it will allow to see bigger photos on the screen.
```

Would be the best: image width > height -> horizontal thumbnail div
image width  < height -> vertical thumbnail div (even positionable to the lfet or to the right) and also: 2 columns of thumbails on both sides or only one side.

**Comment by fancyapps** [comment]
You can upgrade to v3 and play with CSS to reposition each block - http://codepen.io/fancyapps/pen/vgRajd/

**Comment by AlexanderMatveev** [comment]
@fancyapps why did you delete my comment? :disappointed: 

Above demos have two UX/UI moments:

On small screen devices thumbs can still be displayed
![screenshot from 2019-01-23 11-47-03](https://user-images.githubusercontent.com/1456669/51594113-c3fd5300-1f04-11e9-9a40-24fea5dad945.png)

Thumbs should be centered horizontally
![screenshot from 2019-01-23 11-46-37](https://user-images.githubusercontent.com/1456669/51594102-bc3dae80-1f04-11e9-821c-15afd29c5eca.png)

**Comment by fancyapps** [comment]
@AlexanderMatveev 

1)Your comment has not been deleted, you posted that in the different issue. 2) If you did not know, you can add your own CSS to customize anything to your taste.

**Comment by AlexanderMatveev** [comment]
1) my mistake, sorry
2) is there any plans to support this as feature?

**Comment by fancyapps** [comment]
Yes, it is planned to rewrite thumbnail helper completely to add nex/prev page buttons, dragging, etc

**Comment by AlexanderMatveev** [comment]
@fancyapps thanks for the response :+1:
