### ISSUE TITLE
FancyBox 2 Dialog Not Displaying on iPad

### ISSUE THREAD

**Issue by chrisalexander55** [fancyapps/fancyBox#536]
Reference page: http://www.doneupsalon.com/test.html.

When clicking Services, About Us, Staff or Terms links in full browsers, no problem. When doing same on iPad 4, overlay appears (screen dims) but dialog never renders. Please examine reference page to inspect behavior and code. This appears to be a bug?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
