### ISSUE TITLE
IFrame and autoSize - not workng.

### ISSUE THREAD

**Issue by RWAP** [fancyapps/fancyBox#538]
I am loading an iframe fancybox with:

```
    $('#popupTimer').fancybox({
        'closeClick' : true,
        'type' : 'iframe',
        'padding'   : 5,
        'beforeLoad' : function(){clearInterval(refresh);return true;},
        'onCancel' : cancelFancybox,
        'afterClose' : closeFancybox
    });
```

The content is loaded and displayed correctly within the fancybox popup.

However there are two issues:
a) The fancybox height is pretty much full screen height !
b) Clicking on the content does not close the fancybox

Am I missing something here?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
