### ISSUE TITLE
Major issue with Android / mobile

### ISSUE THREAD

**Issue by dadapowell** [fancyapps/fancyBox#549]
Fancybox seems to have a problem rendering on Android phones when the content is an iframe: the fancybox loads at the very bottom of the page, often way beyond the page margins. (You can still see the content if you scroll all the way down the page.)

Also, generally, Fancybox seems to have a problem resizing when changing orientation on mobile phones.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
