### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type application/pdf: "http://samplepdf.com/sample.pdf". 

### ISSUE THREAD

**Issue by rkahar** [fancyapps/fancybox#579]
When I click Your 18th Tips & tricks - Open PDF (inside iframe)
Google chrome doesn't show pdf file on inspecting console there is error like following :

Resource interpreted as Document but transferred with MIME type application/pdf: "http://samplepdf.com/sample.pdf". 
Please resolve this problem

![fancybox](https://f.cloud.github.com/assets/4298881/442546/96e981ae-b155-11e2-88c9-c6d9e19ab892.png)

**Comment by vkeziah** [comment]
I do have the same issue with IE even I use preload: false , sometimes it loads but sometimes it stuck , not sure what is the problem , when it stuck I do close iframe and again If I try to open it loads , very strange behavior in IE .

Any Ideas ?

**Comment by jaharkema** [comment]
I get the same behavior as vkeziah in Google Chrome. Sometimes the PDF shows as fit to screen (without a warning), sometimes it's zoomed in to fit the width of the screen (with warning) and sometimes it's a stamp size preview in the top left corner of FancyBox (also with warning).

It'd be great to have some kind of workaround for this issue, without having to rewrite the way my media is server or whatever.

**Comment by useug** [comment]
ss
