### ISSUE TITLE
The fancybox missing function

### ISSUE THREAD

**Issue by alvinhui** [fancyapps/fancyBox#585]
Fancybox version: 2.1.4

1- Allows us to decide whether the scroll bar is needed
I found that in 'beforeShow' function, fancybox add a class to 'body' to hidden scroll bar and add a 'margin-right' to body.
Can you set a parameter, let us decide whether to do so?
In some cases, we need to pop-up box, and allow the user to scroll the content behind.

2- Allow overlay window.
Now, if I use fancybox pop up a window, and then use the open method, the original window disappears, a new window appears.
In some cases, I use fancybox pop up a layout, is a form. The user then fill content, click on 'submit'. if he got errors, I use fancybox to open another layout show the errors.
But user can not back to original window changes what they are filled.

I think fancybox is a very good Plug-in. I use it for all my website projects.
I hope it become more stronger. 
At last, Thanks to the author, you help a lot of developers save their time.

Here is a example website use Fancybox: http://www.thecn.com

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
