### ISSUE TITLE
Add ability to set string padding for .fancybox-skin like '30px 50px'

### ISSUE THREAD

**Issue by mbakirov** [fancyapps/fancybox#597]
It will be great if we could set padding for .fancybox-skin in settings like that: '30px 50px 40px 20px'.

My decision below:

Changes on line 893 of jquery.fancybox.js
<code>if($.type(coming.padding) == 'string') {coming.skin.css('padding', coming.padding);} else if($.type(coming.padding) == 'array') {$.each(["Top", "Right", "Bottom", "Left"], function(i, v) {coming.skin.css('padding' + v, getValue(coming.padding[ i ]));});}</code>

**Comment by extractachris** [comment]
Why is padding set in JavaScript and notin CSS?
