### ISSUE TITLE
overlay-helpers (speedIn and opacity) not working anymore

### ISSUE THREAD

**Issue by nurso** [fancyapps/fancyBox#620]
1) I just upgradet to Fancybox 2.1.4 and now I can´t get the overlay-helpers (speedIn and opacity) get to work (speedOut is still working!).

In the web I just found infos that this helpers will not work anymore, but I found no alternative ways to make the overlay speedIn and the opacity change.

2) The background of the website is shining through when images are fading from one to another, is there an opportunity to make this "fading-proccess" not transparent so that the background will not shine through?

Sorry for my bad english :-)
Best regards
nurso

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
