### ISSUE TITLE
Fancybox fails when page is rendered as XML/XHTML

### ISSUE THREAD

**Issue by tigerhawkvok** [fancyapps/fancybox#623]
Title says it all. Doesn't do a thing. By changing the file extension, for example, from .html to .xht (or by changing the way the server delivers the file) it breaks FancyBox.

**Comment by Spetnik** [comment]
Why is this closed? Fancybox is still not xhtml-compatible.

**Comment by mjcampagna** [comment]
Because it's 2017. Stop using XHTML, get on with HTML5. Else go back to Fancybox 2 if that's the era you want to work in.

**Comment by Spetnik** [comment]
@mjcampagna HTML5 fully supports XML-serialized HTML, or XHTML. It is a current standard and used by many templating systems. It is an active part of the HTML5 standard: https://www.w3.org/TR/html5/the-xhtml-syntax.html

**Comment by fancyapps** [comment]
@Spetnik Sorry, I have no idea what do you mean by "not xhtml-compatible" and you have not given any clue.

I do not see any issue with fancyBox - it creates valid html code that you can customize, if needed. Yes, the script uses HTML5 data attributes, but you can write your own click handler that opens fancyBox manually (using `$.fancybox.open()`).

**Comment by Spetnik** [comment]
@fancyapps Thanks for the response.

When clicking on a fancybox element in a page served as "application/xhtml+xml" (the content-type for XHTML), Chrome gives the error: `Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.`
I am looking at the code now and I have found several instance where the HTML is not XML-compatible (e.g. `<div data-fancybox-next ...` - XML-compatible HTML would be `<div data-fancybox-next="data-fancybox-next" ...`).

I'll create a pull request to fix the issues.
