### ISSUE TITLE
Poor performance for elastic opening effect when using rich inline content

### ISSUE THREAD

**Issue by chapati23** [fancyapps/fancyBox#625]
http://www.goldstoff.co — site is running on heroku, worked a lot on the performance (Sprites, CDN and so forth) but fancybox's animations have just such a big performance impact for me. it's especially bad in safari (OSX 10.8.4 with all Updates running on SSD).

tried joe1chen's pull-request #465 for css3 animations which seemed to improve performance a little bit (unfortunately has no support for elastic animation, though) but it's still bad.

is there a performance-improvement planned/in the works?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
