### ISSUE TITLE
Swiper slider

### ISSUE THREAD

**Issue by onebeat** [fancyapps/fancyBox#633]
hello i am using fancybox to show in iframe local file that loads swiper slider and i am using this on touchscreen device.

If i load file as iframe in fancybox then when i swipe it is sliding very slow but if disable fancybox and open as file then it is ok.

Another problem is that sometimes fancybox doesn't load file as popup it just show file then i need to refresh everything

Any idea ?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
