### ISSUE TITLE
Order of styles and scripts

### ISSUE THREAD

**Issue by clamiax** [fancyapps/fancyBox#634]
See https://github.com/fancyapps/fancyBox/commit/e2248f468dc4b45f5b1ef1776bde958b2b52775d#L7R2017

**Comment by clamiax** [comment]
1) I think you shouldn't mix script and style, to avoid download time. That's the nature of the issue.
2) Not sure what this have to do with the issue; I may miss some point.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
