### ISSUE TITLE
Video and Images in same gallery.

### ISSUE THREAD

**Issue by dplumly** [fancyapps/fancybox#636]
I have been trying to get Fancybox setup for a portfolio site. Is there a way to get video and images in one gallery? This is the HTML:

``` HTML
<li class="three columns">
    <a class="fancybox thumbnail" rel="gallery1" href="various.png" >
        <img src="various.png" title="" /></a>


        <!-- hidden thumbs  -->
        <a class="fancybox" rel="gallery1" href="various.png">
        <img src="#" style="width:0; height: 0; display:none;"/></a>

        <a class="fancybox" rel="gallery1" href="http://www.youtube.com/various">
        <img src="#" style="width:0; height: 0; display:none;"/></a> 

        <a class="fancybox" rel="gallery1" href="various.png"> 
        <img src="#" style="width:0; height: 0; display:none;"/></a>
</li><!--end thumb -->
```

The Javascript I am using is: 

``` Javascript
<script type="text/javascript">
      $(document).ready(function() {
        $(".fancybox").fancybox({
            openEffect : 'elastic',
            openSpeed  :300,

            closeEffect : 'elastic',
            closeSpeed  : 300,

             easingIn : 'easeOutBack',  
             easingOut : 'easeInBack',

            helpers : {
              title : {
                type : 'over'
              }
            }
          });
```

I can get the images to display, but no the video with this Javascript. Any help would be appreciated! Thanks!

**Comment by surferxo3** [comment]
Short and simple answer: http://www.codeproject.com/Tips/729361/Display-images-and-videos-in-a-FancyBox-gallery

**Comment by andyexeter** [comment]
@fancyapps - The fiddle you posted only contains images, no videos. I can't see any reference to "media helper"'s within the fiddle either.

**Comment by fancyapps** [comment]
@andyexeter I have no idea why that demo is missing additiona include. For v2 you had to include this file to make youtube etc videos work automatically - https://github.com/fancyapps/fancybox/blob/2.1/source/helpers/jquery.fancybox-media.js

In v3, this functionality is already included in the code (but you could use gulp to create your own build without this) so you do not need to do any extra steps.

**Comment by surferxo3** [comment]
@Guyz: Do have a look at this repo 'https://github.com/surferxo3/allinonegallery'. Hope it might help you.

--
Cheers

**Comment by acwolff** [comment]
Same problem as #1983

**Comment by BernaDemirkiran** [comment]
@acwolff how can I solve

**Comment by acwolff** [comment]
@BernaDemirkiran I can't, @fancyapps has to do that I think

**Comment by brnaa2005** [comment]
@acwolff  @fancyapps 
the video stops at the end of the video but should continue

**Comment by acwolff** [comment]
@brnaa2005
I don’t understand your comment.

**Comment by brnaa2005** [comment]
hi​
 Slide.zip
<https://drive.google.com/file/d/1jIhwKvcju9aDUcI69j9lsW5tGHYKJuTn/view?usp=drive_web>
​index.html, you need to continue the slide after the video but there is no
solution. Is there any solution

2018-07-02 14:13 GMT+03:00 André Wolff <notifications@github.com>:

**Comment by brnaa2005** [comment]
Please download the file

2018-07-02 14:23 GMT+03:00 Bernaa Demirkiran <bernademirkiran@gmail.com>:

**Comment by acwolff** [comment]
I tried to get your files, but I got an error:
<img width="426" alt="error" src="https://user-images.githubusercontent.com/8150784/42168166-85767e3a-7e10-11e8-9327-b5a979df1371.PNG">
And I have no idea where the download is stored.

Why don't you upload your files to your serever and give me the link to the result?

**Comment by brnaa2005** [comment]
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>OZAN TEKSTİL</title>

<link rel="stylesheet" type="text/css" href="
http://fancyapps.com/fancybox/source/jquery.fancybox.css">
</head>
<body>
<style>
a{
display:none;
}
</style>
<a data-fancybox="gallery1" title="Title of video here" class="various
iframe" href="media/1-test-0.mp4" id="video">
  <video id='myVideo' width="400" controls>
  <source src="media/1-test-0.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
  </video>
    </a>
<a href="media/2-test2.-.png" data-fancybox="gallery1" id="fancy">
<img src="media/2-test2.-.png" alt="" />
</a>
    <a href="media/2-test2-5.png" data-fancybox="gallery1" id="fancy">
<img src="media/2-test2-5.png" alt="" />
</a>


    </a>



<script src="https://code.jquery.com/jquery-1.8.3.min.js"></script>
<script src="http://fancyapps.com/fancybox/source/jquery.fancybox.js
"></script>
<script src="
http://fancyapps.com/fancybox/source/helpers/jquery.fancybox-media.js
"></script>
<script>
function f1(){
  $.fancybox.open({
    src  : '#fancy',
    //type : 'inline',
fullScreen: {
        autoStart: true
    },

slideShow: {
        autoStart: true,
        speed: 30000
    },
loop     : true,
    opts : {
      afterShow : function( instance, current ) {
        console.info('done!');
      }
    }
  });
}
function f2(){
  $.fancybox.open({
    src  : '#video',
    //type : 'inline',
fullScreen: {
        autoStart: true
    },

slideShow: {
        autoStart: true,
        speed: 30000
    },
loop     : true,
    opts : {
      afterClose : function( instance, current ) {

        f1();
      }
    }
  });
}

$("#test").on('click', function() {



});
function onPlayerStateChange(event) {
    if (event.data === 0) {
        // video is finished
        $.fancybox.play(); // resume slide show
    }
}
function test(id){
alert('The End');
document.getElementById(id).addEventListener('ended', function(e) {

        alert('The End');

    });
$("#"+id).bind("ended", function() {
   alert('The End');
});
}
$( document ).ready(function() {
//var video = $("[data-fancybox1]");
//var photo = $("[data-fancybox]");
//f1();
        $.fancybox.open([{
            href: "media/2-test2.-.png",
            title: "image 01",
            type: "image"
        }, {
            href: "media/1-test-0.mp4",
            title: "video 01",
            type: "iframe"
        }, {
            href: "media/2-test2-5.png",
            title: "image 02",
            type: "image"
        }], {
            autoPlay: true,
            playSpeed: 3000,
            helpers: {
                media: {}
            },
            beforeLoad: function () {
                // the coming content is iframe (video)
                // and the slideshow is active/running
                if (this.type == "iframe" && $.fancybox.player.isActive) {
                    $.fancybox.play(); // pause slide show
                } else if (!$.fancybox.player.isActive) {
                    // the slideshow is paused
                    // most likely we advanced gallery using arrows
                    $.fancybox.play(); // resume slideshow
                };
            },
            beforeShow: function () {
                if (this.type == "iframe") {

                    var id = $.fancybox.inner.find('iframe').attr('id');
this.content.find('video').on('ended', function() {
$.fancybox.next();
  });
  console.log(1); /*
                    var player = new YT.Player(id, {
                        events: {
                            onStateChange: onPlayerStateChange
                        }
                    });*/
                };
            },
afterShow: function () {
      // After the show-slide-animation has ended - play the vide in the
current slide
      var id = $.fancybox.inner.find('iframe').attr('id');
  console.log(id);
      if(id != null){
this.content.find('video').on('ended', function() {
$.fancybox.next();
  });
  }

      // Attach the ended callback to trigger the fancybox.next() once the
video has ended.

    },
            margin: [20, 60, 20, 60] // Increase left/right margin
        }); // fancybox

/*
    $("[data-fancybox1]").fancybox({

fullScreen: {
        autoStart: true
    },

slideShow: {
        autoStart: true,
        speed: 30000
    },
loop     : true,
afterShow: function() {
      // After the show-slide-animation has ended - play the vide in the
current slide
      this.content.find('video').trigger('play');

      // Attach the ended callback to trigger the fancybox.next() once the
video has ended.
      this.content.find('video').on('ended', function() {
        $.fancybox.next();
      });
    }
});
$('#fancy').trigger('click');
*/
});

</script>
</body>
</html>














2018-07-02 16:58 GMT+03:00 André Wolff <notifications@github.com>:

**Comment by brnaa2005** [comment]
video end slide must be continued

2018-07-02 17:06 GMT+03:00 Bernaa Demirkiran <bernademirkiran@gmail.com>:

**Comment by brnaa2005** [comment]
Codes in index.html file

2018-07-02 17:08 GMT+03:00 Bernaa Demirkiran <bernademirkiran@gmail.com>:

**Comment by brnaa2005** [comment]
video end slide must be continued . Codes in index.html file

2018-07-02 17:10 GMT+03:00 Bernaa Demirkiran <bernademirkiran@gmail.com>:

**Comment by acwolff** [comment]
@BernaDemirkiran as I said already I can't solve this, @fancyapps has to do that I think

**Comment by brnaa2005** [comment]
@fancyapps how can i reach you?

2018-07-02 22:49 GMT+03:00 André Wolff <notifications@github.com>:
