### ISSUE TITLE
Fancybox 3 beta - beforeShow: function not working anymore? (facebook like button not displayed)

### ISSUE THREAD

**Issue by Niek83** [fancyapps/fancyBox#643]
Hello,

Issue 1
after updating to fancybox 3 beta 1 everything seems to be working properly using my previous script only the <code>beforeShow: Function ()</code> doesn't seem to work anymore. As I cannot see the facebook like button anymore?
Also if I try to implement "disable right click function with beforeShow" it doesn't seem to work either, so I thought it might be a problem with beforeShow function

Request 1
The next and previous buttons are outside the fancybox how do I get them back in?

Request 2
I noticed that the padding around the picture have sharp corners, how can I round them off like in fancybox 2.5.1?

Request 3
I upgraded to the beta version because I really like the new Thumb helper!
this is genius! I do have a small request, Is it possible when the mouse goes over a thumb picture, to zoom in a little bit before you click on it and go to that picture as the thumbs are pretty small?

Here is my script if you need more data please let me know.

<pre><code>
&lt;body&gt;
    &lt;div class="imglist"&gt;
        &lt;a class="gallery" rel="Modern" href="images/architectuur/moderne/Modern001.JPG" title="Foto 1"&gt;&lt;img src="images/architectuur/moderne/Modern001s.jpg" title="Moderne Architectuur" alt=""&gt;&lt;/a&gt;
        &lt;a class="gallery" rel="Symmetrie" href="images/symmetrie/Symmetrie001.JPG" title="Foto 1"&gt;&lt;img src="images/symmetrie/Symmetrie014s.jpg" title="Symmetrie" alt=""&gt;&lt;/a&gt;
        &lt;span style="display:none;" &gt;
            &lt;a class="gallery" rel="Modern" href="images/architectuur/moderne/Modern002.JPG" title="Foto 2"&gt;&lt;/a&gt;
            &lt;a class="gallery" rel="Modern" href="images/architectuur/moderne/Modern003.JPG" title="Foto 3"&gt;&lt;/a&gt;
            &lt;a class="gallery" rel="Modern" href="images/architectuur/moderne/Modern004.JPG" title="Foto 4"&gt;&lt;/a&gt;
            &lt;a class="gallery" rel="Symmetrie" href="images/symmetrie/Symmetrie002.JPG" title="Foto 2"&gt;&lt;/a&gt;
            &lt;a class="gallery" rel="Symmetrie" href="images/symmetrie/Symmetrie003.JPG" title="Foto 3"&gt;&lt;/a&gt;
            &lt;a class="gallery" rel="Symmetrie" href="images/symmetrie/Symmetrie004.JPG" title="Foto 4"&gt;&lt;/a&gt;
        &lt;/span&gt;

        &lt;script type="text/javascript"&gt;
            $(document).ready(function() {

                $("[class='gallery']").fancybox({
                    beforeShow  : function () { if (this.title) { this.title += '&lt;div style="float:right; padding:0;" &gt; &lt;iframe src="//www.facebook.com/plugins/like.php?href=' + this.href + '&amp;layout=button_count&amp;show_faces=true&amp;width=500&amp;action=like&amp;font&amp;colorscheme=light&amp;height=23" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:110px; height:23px;" allowTransparency="true"&gt;&lt;/iframe&gt; &lt;/div&gt;';} },
                    padding     : 5,                
                    caption     : { type : 'inside' },              
                    helpers     : { thumbs : true },
                    openEffect  : 'fade',
                    closeEffect : 'fade',
                    nextEffect  : 'fade',
                    prevEffect  : 'fade'
                }); // fancybox
            }); // ready function
        &lt;/script&gt;
    &lt;/div&gt;
&lt;/body&gt;

</code></pre>

Why is my facebook like button gone? I don't see the problem.. please Help me.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
