### ISSUE TITLE
"The requested content cannot be loaded" error on ajax fancybox

### ISSUE THREAD

**Issue by kbond** [fancyapps/fancybox#655]
I occasionally (it is rare) get error this when trying to load ajax content.  I can't seem to find any pattern.  Any ideas?

Here is my config:

``` js
$('a element').fancybox({
    type:       'ajax',
    maxWidth:   800,
    maxHeight:  600,
    fitToView:  false,
    autoSize:   true,
    closeClick: false,
    openEffect: 'none',
    closeEffect:'none',
    helpers: {
        title: null
    }
});
```

**Comment by EduardJS** [comment]
I'm having the same issue with any video I'm trying to play from within a firebase app.

The only request it's doing is directly towards the video file, and the response status is 200. The file is there, if i open the link in a new tab, it opens just fine. If I replace the fancybox with a video player, again, plays just fine.

Could you explain what type of response is triggering it ?

**Comment by fancyapps** [comment]
@EduardJS Your comment lacks any sense, "Minimal, Complete, and Verifiable example" (https://stackoverflow.com/help/mcve) would help to understand you.

**Comment by EduardJS** [comment]
In the context of reading the first post ( where you asked for the ajax requests ) i've replied saying the request it's doing is just fine. The response status of that request is 200, and still, the video does not play, triggering that error.

Images on the other hand, from the same source ( google cloud storage ) work just fine. I'll try make up an example.

**Comment by fancyapps** [comment]
See https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L1732 - the script just makes ajax request, receives content and places that in appropriate place in DOM. The rest is up to you and your server :)

**Comment by EduardJS** [comment]
Hello! So, it seems that the error pops up ( at least in my case ) on videos only, when you do not have any extension in your filename.

What happens is that given it does not detect the video extension, it assumes it's an image, therefore it cannot display it.

**Comment by fancyapps** [comment]
@EduardJS It is not clear from your comment how you are using fancybox. Are you opening fancybox manually or what? If you use `data-type="ajax"` (or set `type: ajax`) for your links, then the script assumes that you want to make ajax request to retrieve HTML content and error message is displayed only if ajax (e.g.`$.ajax()`)  request fails.

**Comment by EduardJS** [comment]
Hei! No. I use it with react. No additional configuration. Also, it's no issue.
The library assumes you have an extension in your URL ( when you don't have a content-type set ).

https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L716

It's all good now :)

**Comment by fancyapps** [comment]
Yes, that is true, `image` is used as default type when it is not set and can not be guessed. In older versions, default type was `iframe`, but that led to multiple complains when images where loaded into iframe when source was something like `generate.php?id=123`.
