### ISSUE TITLE
Multiple inline content and lock issue when opening fancybox from within fancybox

### ISSUE THREAD

**Issue by JFKDIAZ** [fancyapps/fancyBox#672]
**Case 1** : 

When using multiple `inline` content and one of the inline content is opened from within fancybox via link, the helpers lock functionality is lost  (`fancybox-lock` class is removed from the `html` element.)

Code example : 

HTML

```
  <a class="fancybox01" href="#modal1">Open Modal 1</a>
  <a class="fancybox02" href="#modal2">Open Modal 2</a>

  <div id="modal1">
    <p>Modal box 1 contents</p>
    <a class="fancybox02" href="#modal2">Open Modal 2 from within fancybox</a>
  </div><br/><br/>
  <div id="modal2">
    <p>Modal box 2 contents</p>
    <a class="fancybox01" href="#modal1">Open Modal 1 from within fancybox</a>
  </div>
```

jQuery

```
$(".fancybox01").fancybox();
$(".fancybox02").fancybox();
```

Demo at 
http://www.picssel.com/playground/jquery/multipleInlineContent_lockIssue_2.1.5.html

**Note** inline blocks are always visible for demo purposes.

**Case 2** : 

On the other hand, if we attempt to `trigger` a `click` to one of the selectors bound to fancybox within the `afterClose` callback like 

```
  $(".fancybox02").fancybox({
    afterClose: function () {
      // triggers a click to open Modal 1
      $(".fancybox01").trigger("click");
    }
  });
```

... it triggers this js error `TypeError: this.overlay is null / jquery.fancybox.js /Line 1787`, the open process is aborted and the element never returns to its position in the document flow : 

Demo at : 
http://www.picssel.com/playground/jquery/multipleInlineContent_lockIssue_2.1.5BIS.html

**NOTE** : None of the issues described above existed in previous versions from v2.1.0 to v2.1.4. See demo at : 
http://www.picssel.com/playground/jquery/multipleInlineContent_lockIssue_2.1.4.html

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
