### ISSUE TITLE
Overlay not covering whole site - IE10 / WP8

### ISSUE THREAD

**Issue by vwasteels** [fancyapps/fancyBox#676]
On Windows Phone 8 / IE 10, the overlay appears only on the visible part of the window.

![wp_ss_20130805_0001](https://f.cloud.github.com/assets/1151398/912427/0b658ec2-fe01-11e2-9a84-389abb58c566.jpg)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
