### ISSUE TITLE
FancyBox doesn't work perfectly inside a huge iframe

### ISSUE THREAD

**Issue by pisty** [fancyapps/fancybox#679]
I would like to use FancyBox inside an iframe, like Facebook application, and the iframe height is so big (3-4000 px). My problem is that the FancyBox has a vertical middle alignement, and i see the FancyBox when i scroll down.

I made a demonstration page:
http://webshopexperts.hu/fancybox-test/iframe-test.html

Related stackoverflow issues:
http://stackoverflow.com/questions/10205505/fancy-box-center-within-facebook-iframe-fanpage
http://stackoverflow.com/questions/9936661/how-to-get-fancybox-centered-in-facebook-iframe-app
http://stackoverflow.com/questions/13156000/fancybox-2-1-3-position-within-facebook-custom-tab

I solve the problem with an alternate solution: if the destionation is FacebookPage then i complete the initialization with the 'topRatio: 0.05' part. But i think this isn't a perfect solution, because if the iframe size or content is dinamic then i can't set fixed topRatio.

Please help us to find the perfect solution. (We have a Multi Domain License)

Yours Faithfully,
István Szegedi
Chief Frontend Engineer
ShopRenter.hu

**Comment by pablocossioabastoflor** [comment]
I solved this issue as following:

`function prepareAddMenuItemPopup() {
    $(".addMenuItemLink").fancybox({
        'type' : 'ajax',
        'autoCenter':   false,
        'autoSize' : true,
        'autoResize' : true,
        'closeBtn' : true,
        'scrolling': 'auto',
        'beforeLoad': function () {
                this.topRatio = getFancyBoxCustomTopRatio(this.element);
        }
    });
}

function getFancyBoxCustomTopRatio(element) {
    var body = document.body;
    var html = document.documentElement;
    var height = Math.max( body.scrollHeight, body.offsetHeight,
        html.clientHeight, html.scrollHeight, html.offsetHeight );
    var position = element.offset();
    return ((position.top * 100) / height) / 100;
}`

The popup is opened based on the element you click to fire the fancybox.
I'm not sure if this solves your problem.
