### ISSUE TITLE
FB 2.1.5 poor performance comparing to FB 1.3 (project specific)

### ISSUE THREAD

**Issue by EugenyPavlenko** [fancyapps/fancyBox#681]
Hello!

Using Fancybox for inline content with small amount of HTML performs very bad in a new FB 2.1.5.

It takes almost 1 second after clicking the element and appearing the FB... when old 1.3.x appears almost immediately...

Will attach some screenshots.

Also tried to update jQuery to the latest version - nothing!

![fb_2_1_5_bagperformance](https://f.cloud.github.com/assets/1785921/956118/6d20e76a-0437-11e3-93a6-46171cfe4f04.png)

![fb_1_3_allfine](https://f.cloud.github.com/assets/1785921/956119/6d1e9f82-0437-11e3-8216-88e6ac90ce91.png)

jQuery used in slow performance test:
http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js

7088:   curCSS = function( elem, name, _computed ) {
**7089:     var width, minWidth, maxWidth,**

So, it seems new FB calls "curCSS" so much... but it is OK on your demo site... maybe because DOM is simpler...

Can you advice why new FB is slow? I can run some test, if needed...

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
