### ISSUE TITLE
Viewport/Fancybox 2 issue on iPad mini

### ISSUE THREAD

**Issue by nickvanloocke** [fancyapps/fancyBox#687]
For example you open een image in an Fancybox pop-up. At the moment your iPad is in landscape and you twist it to portrait. Now you will see a glitch/bug.

Result/Bug: the image isn't centered anymore and you can only see a part from the image in the Fancybox.

Notice: this bug is only available when using viewports. 
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

![fancybox](https://f.cloud.github.com/assets/1006229/986399/f7f8460e-08d7-11e3-9566-159f0b23aaaa.png)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
