### ISSUE TITLE
Opening multiple Fancybox galleries via manual links

### ISSUE THREAD

**Issue by JulianLaval** [fancyapps/fancybox#691]
Forgive me for the repost; my query was initially posted on StackOverflow but there have been no answers thus far (http://stackoverflow.com/questions/18423406/opening-multiple-fancybox-galleries-via-manual-links).

I've attempted to convert a solution allowing galleries to be opened manually from a link on the page, in order to apply it to several galleries, but can't get it to function correctly.

What I have is several links with the following attributes:

```
 <a href="#" class="open-album" data-open-id="album-1">Album 1</a>
 <a href="#" class="open-album" data-open-id="album-2">Album 2</a>
```

etc.

These are supposed to apply to their respective Fancybox-enabled albums, for example:

```
 <a href="#" class="image-show" rel="album-1"><img src="#" /></a>
 <a href="#" class="image-show" rel="album-1"><img src="#" /></a>
 <a href="#" class="image-show" rel="album-1"><img src="#" /></a>
```

and

```
 <a href="#" class="image-show" rel="album-2"><img src="#" /></a>
 <a href="#" class="image-show" rel="album-2"><img src="#" /></a>
 <a href="#" class="image-show" rel="album-2"><img src="#" /></a>
```

Fancybox looks for the `.image-show` class, and works fine when the images themselves are clicked.

The following jQuery code is supposed to link the album titles to the 1st image in their respective albums:

```
  $('.open-album').click(function(e) {
     var el, id = $(this.element).data('open-id');
     if(id){
         el = $('.image-show[rel=' + id + ']:eq(0)');
         e.preventDefault();
         el.click();
     }
 }); 
```

As you can see, the goal was to obtain the `data-open-id` from the album title and use it to open the first Fancybox item with the value as its `rel` attribute. Alas, it doesn't work. Any ideas on what could be going wrong? Your help would be much appreciated!

Thanks in advance!

**Comment by smartyme** [comment]
@JulianLaval , I know this is a old post but it save me some time. Thanks!
