### ISSUE TITLE
Don't enclose image filenames in single quotes in CSS url() values as breaks when minified

### ISSUE THREAD

**Issue by chriskeeble** [fancyapps/fancyBox#698]
Although the syntax is valid (single-quote surrounding the image filename) it is unnecessary where no special characters are being used, and the single quotes are causing issues with minification, specifically with the widely used Microsoft Ajax Minifier 4.96 - see issue https://ajaxmin.codeplex.com/workitem/20186)

**Comment by fancyapps** [comment]
v3 does not use any images for interface.
