### ISSUE TITLE
Close button is not showing up even when setting the right options

### ISSUE THREAD

**Issue by ghost** [fancyapps/fancybox#699]
On my site here:

http://akram-abbas.com/developernoman/

The close button just wont show up even when I am passing modal as false and close button as true.

I have only edited the main fancybox code to add some custom transitions.

Here are the two files in question.

My calling code:

http://akram-abbas.com/developernoman/wp-content/plugins/wp-popup/js/wp-popup.js?ver=3.4.1

The fancybox core:

http://akram-abbas.com/developernoman/wp-content/plugins/wp-popup/js/jquery.fancybox.js?ver=3.4.1

**Comment by robert-cruze** [comment]
I'm pretty sure you don't have the "fancybox_sprite.png" in your fancybox folder. This bugged me a lot, but it fixed my issue. :)
