### ISSUE TITLE
preloading gallery images in both directions

### ISSUE THREAD

**Issue by bomali** [fancyapps/fancyBox#703]
Is there an easy modification of the source code so that the option of preloading the gallery images runs in both directions?

Now only the next images are preloaded but it could senseful in some cases if also the previous images are preloaded, so that e.g. if one chooses the number of 3 preloaded images the next 3 and the previous 3 images are preloaded. Then the user can easily go forward or back within the gallery.

**Comment by fancyapps** [comment]
v3 creates previous and next slide, it seems to be sufficient. Preloading too much would cause download speed to drop.
