### ISSUE TITLE
fb v3 Beta1 position issue when viewing actual image size and then scrolling

### ISSUE THREAD

**Issue by cyde** [fancyapps/fancyBox#708]
If you click the "actual image size" button and then scroll around the image, and then go to the previous or next gallery image, the positions for all the rest of the gallery items become weirdly positioned. Only happens after scrolling a bit to any direction. Closing the fancybox window and then opening it again resets the issue.

 For example its very noticeable if I maximize a large landscape image and scroll all the way to the right side and then click on the next button, the next image will be completely on the right side of the viewport.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
