### ISSUE TITLE
Turbolinks + fancyBox on iOS

### ISSUE THREAD

**Issue by allaire** [fancyapps/fancyBox#710]
Hi, fancyBox works flawlessly with Turbolinks on desktop, but on mobile, only the backdrop shows, image never loads.

To fix this issue I had to do somehting like this:

```
  $galleryHolder = $('<div id="gallery-holder"></div>').appendTo(document.body);
  $('.fancybox').fancybox({
    parent: $galleryHolder
  })
```

Any ideas why?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
