### ISSUE TITLE
v3 beta fails in production environment (because it's depending on a hardcoded filename)

### ISSUE THREAD

**Issue by chapati23** [fancyapps/fancyBox#713]
fancybox fails in my production environment because i (like everyone should) concatenate all my javascript-files.

on line 2333 there's a hardcoded dependency on the filename to be exactly "jquery.fancybox.js". this fails because there is no such file if you minify your javascripts. 

error: "Uncaught TypeError: Cannot call method 'match' of undefined "

doesn't seem like a good solution to me to rely on filename-matches.

**Comment by fancyapps** [comment]
v3 has been released recently.
