### ISSUE TITLE
Provide callback for update() method

### ISSUE THREAD

**Issue by chriskeeble** [fancyapps/fancyBox#720]
When calling the update() method e.g. `parent.$.fancybox.update()` it would be very useful to be able to set a callback function.

I'm using the `update()` method to resize iFrame based fancybox dialogs when the dialog forms content dynamically changes (as a result of user interaction) and currently have to use a `setTimeout()` to ensure the fancyBox has finished updating (resizing) before further steps are run.

An alternative would be to provide an `afterUpdate` option.

**Comment by fancyapps** [comment]
The problem is that "afterUpdate" could trigger "onUpdate" leading to endless loop.
