### ISSUE TITLE
Rotating in Firefox on Android not responsiv

### ISSUE THREAD

**Issue by Duologic** [fancyapps/fancyBox#721]
Rotating a mobile device with Firefox 23 on Android does not trigger fancyBox 2.1.5 to make it fit. This results in a not responsive fancyBox.

Example:

![2013-10-10 00 56 01](https://f.cloud.github.com/assets/3349855/1302480/512b677a-3136-11e3-912c-fbc287f2de19.png)

PS: thanks to the dev's for their work on fancyBox

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
