### ISSUE TITLE
v3 beta1 mousewheel direction in IE9 and performance in Chrome

### ISSUE THREAD

**Issue by cyde** [fancyapps/fancyBox#726]
In IE9 the mousewheel will always go to the next gallery item whether you roll it up or down. Works fine with other browsers.

And another browser specific issue is in Chrome the animation performance is really poor with larger images while in every other browser its really smooth. In Chrome the previous image sort of stays visible for too long so it makes a hard cut. 

Also just noticed the Beta 1 version files are dated 10 months old, is there gonna be a Beta 2 version soon or is it close to final? Thanks for all your hard work.

**Comment by fancyapps** [comment]
v3 has been released recently.
