### ISSUE TITLE
Fancybox v2.1.5: Middle Click w/Chrome

### ISSUE THREAD

**Issue by JudgmentDay** [fancyapps/fancyBox#729]
This bug happens on the following conditions:
Chrome only (used Version 30.0.1599.101 m)
Fancybox via Media Helper
Videos only via Media Helper

Even though Fancybox (when active) disables vertical page scrolling by default, browsers that enable middle-click scrolling bypasses it. This is no big deal, but I found out that if you use the middle-click mouse option on Chrome, and use it to scroll up or down on a page while Fancybox is active, the video and close button stays in a fixed position, but the actual shaded lightbox and lightbox container frame (white on default) scrolls with the page. I attached a screenshot.
![101913-screenshot-01](https://f.cloud.github.com/assets/2300501/1366923/0b3db2ba-38f0-11e3-9077-c0d29164a5ed.png)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
