### ISSUE TITLE
Optimized fancybox_sprite@2x.png image

### ISSUE THREAD

**Issue by DyaGa** [fancyapps/fancyBox#730]
Original file `fancybox_sprite@2x.png` - `6553 bytes`

After optimization with pngquant + PNGGauntlent - `2997 bytes`.

![fancybox_sprite@2x.png](https://dl.dropboxusercontent.com/u/13601899/fancybox_sprite%402x.png)

**Comment by fancyapps** [comment]
Thanks for your work. v3 now creates all elements using CSS.
