### ISSUE TITLE
Unable to load YouTube videos on page load from referring page

### ISSUE THREAD

**Issue by justinbhayes** [fancyapps/fancyBox#732]
I need the ability to load multiple YouTube videos on page load from a referring page.

For example, a user clicks on the link for Video 2 from referring page. Then the user is directed to a new page with YouTube video2 loaded on page load.

This is what I'm currently using:

Referring page
`<a href="/video-page.aspx#video1">Video 1</a>`
`<a href="/video-page.aspx#video2">Video 2</a>`
`<a href="/video-page.aspx#video3">Video 3</a>`

Video page
`<script type="text/javascript">`
        `var thisHash = window.location.hash;`
        `$(document).ready(function () {`
            `if (window.location.hash) {`
                `$(thisHash).fancybox().trigger('click');`
            `}`
            `$('.fancylink').fancybox();`
       `});` 
    `</script>` 

`<a id="video1" class="fancylink" href="http://www.youtube.com/watch?v=ABCDEFG">Video 1</a>`
`<a id="video2" class="fancylink" href="http://www.youtube.com/watch?v=BCDEFGA">Video 2</a>`
`<a id="video3" class="fancylink" href="http://www.youtube.com/watch?v=CDEFGAB">Video 3</a>`

This setup works for loading images and other fancybox content, but not YouTube videos.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
