### ISSUE TITLE
iPad Specific Issue

### ISSUE THREAD

**Issue by mawol** [fancyapps/fancyBox#733]
Hi

There seems to be an issue when running a converted iSpring  presentation in a iPad when using the FancyBox2 lightbox. The fancyBox2 light box works fine all other times, e.g. with images.

Go to http://eduschemes.co.uk/our-product.aspx#variety-of-learning_anc-scl and select Web Presentations from the left vertical menu, then choose a presentation. When it opens it does not render correctly (it appears very small in the top left hand corner of the correctly sized lightbox) until the iPad orientation is changed (horizontal to vertical or vice versa).

I've also sent this to iSpring.

Regards

Mark Wolff

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
