### ISSUE TITLE
FancyBox not opening in IE9

### ISSUE THREAD

**Issue by malek1917** [fancyapps/fancyBox#752]
Hello,
On our site: www.uniforms-4u.com, we have an issue with Fancybox not loading at all (it works on Chrome, FF, IE8 and IE10+).
Not sure how to address this!
Any idea would help!
To replicate, just go to the website and click on "customer support" on top left.. A fancybox modal popup should be displayed, but it does not.
Thank you

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
