### ISSUE TITLE
fancy box not working on mobile android at all!!!  PDF shows up blank!

### ISSUE THREAD

**Issue by elizabeth1977** [fancyapps/fancyBox#755]
Hi, fancy box is not working AT ALL on mobile because now my pdfs are popping up EMPTY!  Completely blank.  I installed it because it worked on desktop version of website but then it was live, and I checked on mobile and all pdfs show up BLANK!!  Please help.  This is urgent.  I have an android HTC one phone.  In the default browser for htc one, it shows blank and doesn't even download.  For chrome on the htc one, it shows as blank but it does download!  But most people use the default browser because it is the one with the google search bar on the phone home area and it also allows flash enabled.  So most people can't get it all!!  Please email elizabethshum@gmail.com

**Comment by mvfariajr** [comment]
Did you find the solution for this at all? I have the same problem. Thanks!

**Comment by sohrabzia** [comment]
I am facing the same issue. if any one find the solution please share with us,

**Comment by fancyapps** [comment]
Please, upgrade to version 3.

**Comment by sohrabzia** [comment]
hi, I am using version 3. today only I dowloaded here is codepen  [Here is codepen](http://codepen.io/sohrabzia/pen/KWpXBJ?editors=1000)

**Comment by fancyapps** [comment]
Then I guess the browser on your phone does not support pdf files.

**Comment by sohrabzia** [comment]
I am using chrome devtools on windows 8.1, it works on fullscreen but not on mobile or tablet view. I have tested on nexus 6p. instead if opening pdf in browser iframe it is directly downloading the pdf.

**Comment by fancyapps** [comment]
1) Looks like Chrome does not render pdf files if "device toolbar" is open.
2) The script has no control about how and if the browser handles pdf files.
3) If you really want to broaden pdf rendering support, you could try PDF.js - https://mozilla.github.io/pdf.js/ (I tried https://mozilla.github.io/pdf.js/web/viewer.html on Android device and it really works!)

**Comment by sohrabzia** [comment]
Thanks you so much for awesome plugin and thanks for your response :) keep it up.
