### ISSUE TITLE
Fancybox loads the image twice.

### ISSUE THREAD

**Issue by kcthota** [fancyapps/fancybox#759]
Hi,
Fancybox loads the same image twice: First one loaded by fancybox.js and second call made from jQuery.js.

Body:
&lt;a class="fancyboxPic" href="/api/Picture/157bd7b0-d562-1004-862a-e7be96ab8da7.jpg"&gt;&lt;img class="activityPic" src="/api/Picture/157bd7b0-d562-1004-862a-e7be96ab8da7.jpg"&gt;&lt;/a&gt;

Fancybox initialized as:
$("a.fancyboxPic").fancybox();

Please see the screenshot.
![screen shot 2013-12-01 at 12 18 32 am](https://f.cloud.github.com/assets/2999820/1650118/3e5dadb6-5a61-11e3-95ec-09516a1a6508.png)

**Comment by ethicmatic** [comment]
Can anyone take a look, please? Same issue at http://www.markus.hr/ here. I have added thumb gallery below "Authentic Istrian Cuisine". It loads src twice.

**Comment by fancyapps** [comment]
Why do you think it loads twice? It loads current image and preloads next one.

**Comment by ethicmatic** [comment]
It loads the same image twice.. Have you looked over the site!

**Comment by fancyapps** [comment]
I opened your site, opened developer tools, disabled cache, clicked image, looked at network activity, and got this:

![markus](https://cloud.githubusercontent.com/assets/1055589/25801922/a04d98b4-33f8-11e7-841c-62021fb7742b.jpg)

Maybe you are seeing something I don`t? Because I do not see any issue.

**Comment by ethicmatic** [comment]
I did the same thing. But when I click one next button it shows same image. Can you click on next button, it'll show same image? I have four images there but you'll see eight images.

**Comment by fancyapps** [comment]
Then just re-enable cache and you will see `(from disk cache)` :)

**Comment by ethicmatic** [comment]
Is that the solution? :o

**Comment by fancyapps** [comment]
The script is not storing images anywhere - browsers already have caching mechanism and there is no need to double that functionality.

**Comment by ethicmatic** [comment]
Same thing works fine on another page and for galleries as well. But don't work on home page.. :(
