### ISSUE TITLE
Multilinguality

### ISSUE THREAD

**Issue by baroso** [fancyapps/fancybox#76]
All strings within the script file (like: Close, Next, Previous, ...) should be passed in by variables (defaults) so we can pass in german (or other) language strings!

Thanks
Robert Baminger

**Comment by McPringle** [comment]
What's the state of this feature request? I can't find any information about how to use different languages for the tooltips.

**Comment by SalahAdDin** [comment]
Can you put a full example for do this?

**Comment by fancyapps** [comment]
Hi,

It definitely took a long time, but multilinguality finally will arrive in v3.1. 
So, could someone re-check translations in German? Maybe @exside ?

```JS
i18n : {
    'en' : {
        CLOSE       : 'Close',
        NEXT        : 'Next',
        PREV        : 'Previous',
        ERROR       : 'The requested content cannot be loaded. <br/> Please try again later.',
        PLAY_START  : 'Start slideshow',
        PLAY_STOP   : 'Pause slideshow',
        FULL_SCREEN : 'Full screen',
        THUMBS      : 'Thumbnails'
    },
    'de' : {
        CLOSE       : 'Schließen',
        NEXT        : 'Weiter',
        PREV        : 'Vorig',
        ERROR       : 'Der angeforderte Inhalt kann nicht geladen werden. <br/> Bitte versuchen Sie es später noch einmal.',
        PLAY_START  : 'Diaschau beginnen',
        PLAY_STOP   : 'Diashow anhalten',
        FULL_SCREEN : 'Vollbild',
        THUMBS      : 'Thumbnails'
    }
}
```

**Comment by McPringle** [comment]
Hi @fancyapps 

Thank you very much for your work. I'm native German and suggest following changes:

```
PREV        : 'Zurück',
THUMBS      : 'Vorschaubilder'
```

The other translations are fine!

**Comment by GeronimoCH** [comment]
`i18n : {
    'en' : {
        CLOSE       : 'Close',
        NEXT        : 'Next',
        PREV        : 'Previous',
        ERROR       : 'The requested content cannot be loaded. <br/> Please try again later.',
        PLAY_START  : 'Start slideshow',
        PLAY_STOP   : 'Pause slideshow',
        FULL_SCREEN : 'Full screen',
        THUMBS      : 'Thumbnails'
    },
    'de' : {
        CLOSE       : 'Schließen',
        NEXT        : 'Weiter',
        PREV        : 'Zurück',
        ERROR       : 'Der angeforderte Inhalt kann nicht geladen werden. <br/> Bitte versuchen Sie es später noch einmal.',
        PLAY_START  : 'Diaschau starten',
        PLAY_STOP   : 'Diaschau beenden',
        FULL_SCREEN : 'Vollbild',
        THUMBS      : 'Vorschaubilder'
    }
}`

Some remarks
- 'Schließen' is the way this word is written in Germany; in Switzerland the sharp s ('ß') is not used. We would write 'Schliessen'. That is not problem as long as the translation is in file that can be edited by swiss beeing keen on 'swiss' spelling.
- Next and previous are very handy words in English. An equivalent in German does not really exist unless you say 'Next picture' --> 'Nächstes Bild'. Therefore 'Weiter' and 'Zurück' are better because they specify the direction of your logical movement.
- A German word 'Vorig' does not exist (the correct word would be 'Vorgänger' but that is a bad choice because you would have to be more precise like 'Previous picture' --> 'Vorangehendes Bild').
- 'Diashow anhalten' means the the slide show is interrupted to be continued later.
- Again tumbnails is very handy in English. 'Vorschaubilder' is only correct if you only mean pictures. In case it is also used for videos or documents, the English word 'Thumbnails' is more general.

Thanks for your great work!

**Comment by fancyapps** [comment]
Thanks for your feedback!

You can preview v3.1 here - http://codepen.io/fancyapps/full/LyNXqr/
Next week I`ll start working on documentation and will publish code afterwards.

**Comment by sebascomeau** [comment]
'fr' : {
        CLOSE       : 'Fermer',
        NEXT        : 'Suivante',
        PREV        : 'Pr&eacute;c&eacute;dente',
        ERROR       : 'Le contenu demand&eacute; ne peut pas &ecirc;tre charg&eacute;.<br />Veuillez r&eacute;essayer plus tard.',
        PLAY_START  : 'D&eacute;marrer',
        PLAY_STOP   : 'Pause',
        FULL_SCREEN : 'Plein &eacute;cran',
        THUMBS      : 'Vignettes'
    }

**Comment by SalahAdDin** [comment]
Spanish
```
'en' : {
        CLOSE       : 'Cerrar',
        NEXT        : 'Siguiente',
        PREV        : 'Anterior',
        ERROR       : 'No se puede cargar el contenido solicitado. <br/> Por favor intente de nuevo.',
        PLAY_START  : 'Inicias diapositivas',
        PLAY_STOP   : 'Pausar diapositivas',
        FULL_SCREEN : 'Pantalla completa',
        THUMBS      : 'Miniaturas'
    },
```

**Comment by Listr-Academy** [comment]
Dutch / Nederlands:

`
'nl' : {
        CLOSE       : 'Sluiten',
        NEXT        : 'Volgende',
        PREV        : 'Vorige',
        ERROR       : 'De gevraagde inhoud kan niet worden geladen. <br/> Probeer het later nog een keer.',
        PLAY_START  : 'Start diashow',
        PLAY_STOP   : 'Pauzeer diashow',
        FULL_SCREEN : 'Volledig scherm',
        THUMBS      : 'Miniaturen'
    },
`

**Comment by odahcam** [comment]
Brazilian translation 1:

    i18n : {
        'br' : {
            CLOSE       : 'Fechar',
            NEXT        : 'Próximo',
            PREV        : 'Anterior',
            ERROR       : 'Este conteúdo não pôde ser carregado. <br/> Por favor, tente novamente mais tarde.',
            PLAY_START  : 'Iniciar slideshow',
            PLAY_STOP   : 'Pausar slideshow',
            FULL_SCREEN : 'Full screen',
            THUMBS      : 'Thumbnails'
        },
    }

Brazilian translation 2:

    i18n : {
        'br' : {
            CLOSE       : 'Fechar',
            NEXT        : 'Próximo',
            PREV        : 'Anterior',
            ERROR       : 'O contaúdo requisitado não pôde ser carregado. <br/> Por favor, tente novamente mais tarde.',
            PLAY_START  : 'Iniciar apresentação de slides',
            PLAY_STOP   : 'Parar apresentação de slides',
            FULL_SCREEN : 'Tela cheia',
            THUMBS      : 'Miniaturas'
        },
    }

**Comment by fancyapps** [comment]
Hello, everyone!

Starting from v3.2 there will be two additional buttons ("Download" and "Share") included by default, so I just wanted to inform that you might need to update your translations (if necessary; they can be toggled). 

Also, maybe someone could confirm German translations:

```
DOWNLOAD    : 'Herunterladen',
SHARE       : 'Teilen' 
```

You can preview it here - https://codepen.io/fancyapps/full/WZmGmw/

**Comment by SalahAdDin** [comment]
Spanish
```js
'en' : {
        CLOSE       : 'Cerrar',
        NEXT        : 'Siguiente',
        PREV        : 'Anterior',
        ERROR       : 'No se puede cargar el contenido solicitado. <br/> Por favor intente de nuevo.',
        PLAY_START  : 'Inicias diapositivas',
        PLAY_STOP   : 'Pausar diapositivas',
        FULL_SCREEN : 'Pantalla completa',
        THUMBS      : 'Miniaturas'
DOWNLOAD    : 'Descargar',
SHARE       : 'Compartir'
    },
```
