### ISSUE TITLE
Fancybox on Ipad 3- Scrolling issue (choppiness and lag)

### ISSUE THREAD

**Issue by hugomoss** [fancyapps/fancyBox#761]
Hello I have a site that I built with fancybox,

when I zoom in completely while fancybox is open, and then completely zoom out, then close fancybox.  Scrolling on my html body becomes very laggy and choppy. Every scroll, 3/4's of the scrolled content shows, with 1/4 chopped, then a delay, and then it appears.  I thought it was my content being large, but I have tried non-retina images as well and it becomes an issue only when zooming in while fancybox is open.  I have autosize, resize, and options to false.

Thanks.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
