### ISSUE TITLE
fancybox 1.3.4,jquery 1.10.2  inline not work on second click

### ISSUE THREAD

**Issue by lili21** [fancyapps/fancybox#762]
Here is the code:

```
<a href="#signup">sign up</a>
<div style="display:none">
    <form>......</form>
</div>
$('a').fancybox();
```

It only works on first click. After the fancybox closed,the form element would not go back to the div whick contains it. the form just be removed.Like this:

```
<div style="display:none">
    <div class="fancybox-inline-tmp" style="display:none"></div>
</div>
```

So the next time I click anchor,It just show a small white box with nothing.

It works under the jquery1.4.3(within fancybox package);

**Comment by SubliemeSiem** [comment]
in jquery.fancybox-1.3.4.js, change line 967 content.empty(); to this:
if (currentOpts.type == "inline") {
  content.empty();
}
and it will work again
