### ISSUE TITLE
IE 11: Closing Problem after Refresh

### ISSUE THREAD

**Issue by Andralor** [fancyapps/fancybox#766]
There is a problem in IE 11. Once i open the fancybox and refresh it (iframe) then i can not close it and the size is not adjusted from the content.

//jQuery Code
  $('a.js-fancybox-iframe').fancybox({
    type: 'iframe',
    scrolling : 'visible',
    width:  800,
    height: "auto",
    autoHeight: true
  });

**Comment by jfillbrook** [comment]
@Andralor  Fix works - saved me a lot of time - thanks!

**Comment by raphagood** [comment]
@Andralor muito obrigado, graças a sua contribuição consegui resolver este problema no meu projeto, thank you very much! 

Estou utilizando 
jQuery v1.11.1
Fancybox 2.1.5

Infelizmente a Microsoft tem coisas mais importantes do que resolver BUG´s... de 2013!
