### ISSUE TITLE
Problem with vertical scroll bars and HTML with float:right; content

### ISSUE THREAD

**Issue by RWAP** [fancyapps/fancyBox#768]
I have a web page which has content which is fixed to the right hand side with float:right; margin-right:10px;

The page works fine and extends below the bottom of the screen and therefore a vertical scroll bar is shown as you would expect. 

However, when I click on an image to view it in fancybox, the overlay is 17px wider than the content of my screen (in Firefox) - I guess the overlay is adding on the width of the scrollbar.

As a result once the popup appears, the content on the right hand side of the page moves further to the right....

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
