### ISSUE TITLE
Refreshing current group to include newly loaded images?

### ISSUE THREAD

**Issue by waqasy** [fancyapps/fancyBox#769]
My page automatically adds new images after few intervals.

And when images are opened in fancybox, the fancybox don't switch (when pressing next button) to newly loaded images. I know its because fancybox serves to first loaded group of images. 

I'm seeking for a method to "refresh the current group" for newly added images for fancybox, via using  afterShow: function() {....}

**Comment by fancyapps** [comment]
Each instance has variable "group" that you can manipulate, if needed. Anyway, upgrade to v3, please.
