### ISSUE TITLE
fancybox compatibility issue

### ISSUE THREAD

**Issue by gagan1988** [fancyapps/fancyBox#774]
1. Browser Compatibility Issue:
   If you open the same lightbox in firefox and chrome you will see that in chrome the browser's vertical scrollbar gets hidden where as in ff it is not.
2. Resizing Issue:
   If you resize the window in chrome the lightbox gets resized automatically where as in firefox it is not.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
