### ISSUE TITLE
FancyBox images sliding bug when onbeforeunload event is subscribed on the page

### ISSUE THREAD

**Issue by alex-the-programmer** [fancyapps/fancybox#778]
Hello,

It seems to be a bug when FancyBox fires onbeforeunload event when you slide images by "Next/Previous" buttons that takes place in all the versions of IE.

How to reproduce (the simplest possible official demo based example with the bug as well as the corresponding screenshots, are enclosed):
1. Create a page with the FancyBox (see code below).
2. Subscribe to onbeforeunload event.
3. Open the page in IE 10 (or any of the earlier versions).
4. Click on any of the images to show the FancyBox.
1. Click "Next" or "Previous" button - you will have "Are you sure you want to leave this page" window that is the bug.

This takes place in IE only!

<pre>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;fancyBox - Fancy jQuery Lightbox Alternative | Demonstration&lt;/title&gt;
    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;

    &lt;!-- Add jQuery library --&gt;
    &lt;script type=&quot;text/javascript&quot; src=&quot;../lib/jquery-1.10.2.min.js&quot;&gt;&lt;/script&gt;

    &lt;!-- Add fancyBox main JS and CSS files --&gt;
    &lt;script type=&quot;text/javascript&quot; src=&quot;../source/jquery.fancybox.pack.js?v=2.1.5&quot;&gt;&lt;/script&gt;
    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../source/jquery.fancybox.css?v=2.1.5&quot; media=&quot;screen&quot; /&gt;

    &lt;!--BUG!!!!!! This is what I've added--&gt;
    &lt;script&gt;
        $(function () {
            window.onbeforeunload = function () { return &quot;Hello, World!&quot;; };
        });
    &lt;/script&gt;
    &lt;!-- --&gt;

    &lt;script type=&quot;text/javascript&quot;&gt;
        $(document).ready(function () {
            /*
             *  Simple image gallery. Uses default settings
             */

            $('.fancybox').fancybox();
        });

    &lt;/script&gt;

&lt;/head&gt;
&lt;body&gt;
    &lt;h1&gt;fancyBox&lt;/h1&gt;

    &lt;h3&gt;Simple image gallery&lt;/h3&gt;
    &lt;p&gt;
        &lt;a class=&quot;fancybox&quot; href=&quot;1_b.jpg&quot; data-fancybox-group=&quot;gallery&quot; title=&quot;Lorem ipsum dolor sit amet&quot;&gt;
            &lt;img src=&quot;1_s.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;

        &lt;a class=&quot;fancybox&quot; href=&quot;2_b.jpg&quot; data-fancybox-group=&quot;gallery&quot; title=&quot;Etiam quis mi eu elit temp&quot;&gt;
            &lt;img src=&quot;2_s.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;

        &lt;a class=&quot;fancybox&quot; href=&quot;3_b.jpg&quot; data-fancybox-group=&quot;gallery&quot; title=&quot;Cras neque mi, semper leon&quot;&gt;
            &lt;img src=&quot;3_s.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;

        &lt;a class=&quot;fancybox&quot; href=&quot;4_b.jpg&quot; data-fancybox-group=&quot;gallery&quot; title=&quot;Sed vel sapien vel sem uno&quot;&gt;
            &lt;img src=&quot;4_s.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;
    &lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;

</pre>

![bugdemostep1](https://f.cloud.github.com/assets/6285838/1821812/e49b476e-7141-11e3-9359-f0e8c6f0ebe3.jpg)
![bugdemostep2](https://f.cloud.github.com/assets/6285838/1821816/fab5cd44-7141-11e3-9c1a-e3d37a731dbb.jpg)

**Comment by fancyapps** [comment]
Hi, Sorry for delay. Seems like there is no issue with v3.
