### ISSUE TITLE
Fancybox scroll fix.

### ISSUE THREAD

**Issue by agamemnus** [fancyapps/fancyBox#782]
When opening a new window with Fancybox 2, the styling on the body element may call for a scrollbar(s), inactive scrollbar(s), or no scrollbars. Active scrollbars are not attractive in a modal window. Neither are inactive scrollbars. No scrollbars presents the problem of content re-alignment -- content that is horizontally centered takes into account the scrollbar's thickness. Thus, switching from invisible scrollbars (fancybox open) and visible (fancybox closed) presents a "jumpy content" issue.

I solve the issue with this code, which I offer to the community and Fancybox author at no charge through the MIT license. There are two helper functions and one main function. One of the helper functions get the size of the scrollbar, and the other merges Fancybox settings/functions non-destructively with "merge_subfunctions" set to "true".

There are two limitations in the current code that break the display: (1) if the body's margin is dynamically resized on a timer, or (2) if the margin is expected to not be in pixels. These limitations can be removed with further refinement of the code.

Link:
https://github.com/agamemnus/fancybox_scroll_fix/blob/gh-pages/fancybox_scroll_fix.js

Edit: Ok, so it looks like Fancybox has that a little bit, but it doesn't work with pages that don't initially have a scrollbar.. I think.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by agamemnus** [comment]
Yes sir! :) :+1:
