### ISSUE TITLE
destroy API Method

### ISSUE THREAD

**Issue by szepeviktor** [fancyapps/fancybox#784]
Please add destroy() as an API Method.
Now I call `$(document).unbind('click.fb-start');` when switching to mobile version.
(videos do not need to be lightboxed)

Thank you!

**Comment by NindroidX** [comment]
+1

**Comment by fancyapps** [comment]
I do not why anyone would need this, but it has been implemented lately.

**Comment by szepeviktor** [comment]
For example videos do not need to be lightboxed on mobile.
