### ISSUE TITLE
Fancybox V3 BETA - sprites not displayed correctly in IE8

### ISSUE THREAD

**Issue by suhaenni** [fancyapps/fancyBox#786]
In Fancybox V3 Beta you include the sprites as Base-64-images. This is not working in IE8, the alpha-opacity of the images seems to get not displayed correctly. I suggest it has to do with the problem, that IE8 ist only able to display base-64-images up to 32kb.

![screenshot](https://f.cloud.github.com/assets/6358120/1876629/7a526be0-7915-11e3-8ad0-fb9acf808bf8.jpg)

**Comment by fancyapps** [comment]
Final v3 works completely different.
