### ISSUE TITLE
Scrolling inside container div not working on devices

### ISSUE THREAD

**Issue by ghost** [fancyapps/fancyBox#787]
Hello,

I am trying to scroll on a specific content div when you are on any devices (iOS and Android) but for some reason it is not letting me touch that area and scroll.

Here is the basic idea what I am trying to achieve and make it work for devices (iOS and Android)

http://jsfiddle.net/TUZc7/

Any help would be appreciated.

Thanks

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
