### ISSUE TITLE
Put div with link in fancybox title

### ISSUE THREAD

**Issue by jack-fdrv** [fancyapps/fancyBox#797]
<code>< a class="fancybox" rel="gallery1" href="#" >
< img src="#" alt="" />
< div class="f_content f_hiden">
< p class="f_title">fdrv< /p>
< p class="f_price">30$< /p>
< p class="f_content">bla bla bla< /p>
< a class="f_url" href="#">link< /a>
< /div>
< /a></code>

beforeShow: function(data) {
    this.title = $(this.element).find('.f_content').html();
}

it move out link from a.fancybox.
http://clip2net.com/s/6Gto2V

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3 and there are some examples of customizing caption - http://fancybox.docs/3.0/#faq (#2)
