### ISSUE TITLE
Fancybox V3 Beta: beforeShow

### ISSUE THREAD

**Issue by ernstoarllano** [fancyapps/fancyBox#798]
Anyone else having issues with getting the beforeShow function to work? This bit of code works with the latest stable version, but I can't get it to work with v3. 

<pre>
    <code>
        $(".fancybox").fancybox({       
            nextEffect: "fade",
            prevEffect: "fade",
            helpers: {
                title: {
                    type: "inside"
                }
            },
            beforeShow: function(){ this.title = "my button" }
        });
    </code>
</pre>

**Comment by fancyapps** [comment]
Final v3 is available for some time.
