### ISSUE TITLE
[Q] Preload images within loaded Ajax content before animation?

### ISSUE THREAD

**Issue by nikolajosipovic** [fancyapps/fancyBox#800]
Is there a way to wait for certain elements of the retrieved Ajax content to load before proceeding with the animation?

I am making a Facebook like image gallery viewer. The returned ajax content holds the image and comments.

Would be great to stop the Fancybox animation until the image loads, for a fluid animation.

**Comment by JeromeBreizhtorm** [comment]
+1.
Any solution ?

**Comment by fancyapps** [comment]
Sorry, I think this is a bad idea, because users would have to stare at loading icon for unknown time. Just set width/height using image attributes and let browser do the rest.
