### ISSUE TITLE
Bad behavior on Google Chrome

### ISSUE THREAD

**Issue by Robsterz** [fancyapps/fancyBox#802]
Hi,

I'm using latest version of Google Chrome on Windows, and I have following issues, which can be reproduce on your page:
http://fancyapps.com/fancybox/
1. Just click the first image, so it pops up, and then try to scroll the window, the image will not reposition itself to the center.
2. Resize the window, the image will not resize/reposition itself
3. Now open one of the images from the gallery (to test next/previous using mouse wheel)
   With these settings:
   1920x1080 screen res
   Chrome zoom set to 150%
   browser window maximized
   I'm unable to go prev/next image using the mouse wheel.

I've noticed that sometimes if I make the browser window much smaller, and click the image, then I'm able to use the mouse wheel.

These issues happen only on Google Chrome (IE and FF seems to work fine)

Thanks

**Comment by fancyapps** [comment]
Sorry, I can not reproduce this. Also, try v3.
