### ISSUE TITLE
Firefox does not add fancybox-margin and fancybox-lock classes to the html element

### ISSUE THREAD

**Issue by SiliconMind** [fancyapps/fancyBox#805]
Tested with Firefox 27. Woks fine on IE and Chrome.
Fancybox version affected: 2.1.5 the same that runs on http://fancyapps.com/fancybox

Without these classes there are scrolling issues and view is not "locked" to the slide (user can scroll away from the image).

**Comment by ahmadalfy** [comment]
Can confirm that this is the same case with Safari iOS6

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
