### ISSUE TITLE
Fancybox v3 beta - Doesn't seem to be suport SSL

### ISSUE THREAD

**Issue by arvinsim** [fancyapps/fancyBox#807]
I am using Fancybox v3 beta.

I am using the `data-fancybox-href` attribute to set the url in which fancybox gets the content via ajax.

The problem that I am having is that in an SSL enabled page(https), it doesn't seem to work.

I get this error message

The requested content cannot be loaded. Please try again later.

I tried doing variations to my `data-fancybox-href url`

```
foo/bar/
/foo/bar/
//foo/bar/
https://domain.com/foo/bar/
```

But none of them worked.

Does Fancybox v3 support SSL?

**Comment by fancyapps** [comment]
I do not think that something at the code is not working just because you have ssl. If you can load your page using $.ajax, then the script will be able, too.
