### ISSUE TITLE
Make CSS rendering more efficient by not targeting span/div

### ISSUE THREAD

**Issue by Soundvessel** [fancyapps/fancyBox#810]
Instead of ".fancybox-prev span" etc use classes instead of html selectors so the CSS is instead ".fancybox-prev .fancybox-btn" or better yet ".fancybox-prev fancybox-prev-btn" so you can target the buttons without the added class selector.

During browser rendering selectors in CSS are read right to left which means the current .fancybox-prev span has the browser checkingk every span if it has parent .fancybox-prev Worse for #fancybox-loading div as it is checking every div. By using classes you can directly target it shaves precious milliseconds off browser rendering time and redraws.

Background: https://speakerdeck.com/jonrohan/githubs-css-performance

**Comment by fancyapps** [comment]
Thanks, you are right. I have tried to avoid genera selectors when creating v3.
