### ISSUE TITLE
Scrollbars visible in Firefox

### ISSUE THREAD

**Issue by relish27** [fancyapps/fancyBox#813]
![fancyapps-scroll](https://f.cloud.github.com/assets/534728/2262511/ef26872a-9e5a-11e3-9b03-8d95fc8e791b.jpg)

I have noticed that the scrollbars appear on iframe YouTube videos in Firefox.  Looks fine in Chrome.  You can see in the screenshot above that it happens on the examples section of the Fancyapps page.  Any way to fix this?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
