### ISSUE TITLE
Scrolling is reset with autoResize true on webkit browsers

### ISSUE THREAD

**Issue by MarventusWP** [fancyapps/fancyBox#814]
Hello, there! This is a wonderful tool, which is why I'd like to help out a bit by reporting the following issue:
On latest webkit-powered browsers (Opera 20, Safari 5.1.7, Chrome 33) and when showing images taller than window size, the window position gets reset after scrolling beyond a certain point. Here's my config:
fitToView : false,
minHeight : false,
minWidth : false
The issue does not occur in Firefox (didn't bother with IE) and it goes away when autoResize is set to false.
Thanks!

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
