### ISSUE TITLE
Safari .fancybox-wrap overflow bug

### ISSUE THREAD

**Issue by noslouch** [fancyapps/fancyBox#816]
Hey There,

I'm moving my title outside the `.fancybox-wrap` div, but due to the following transforms being applied to `#fancybox-lock`, the title doesn't display if the title div is position fixed:

```
-webkit-transition : -webkit-transform 0.5s;
-webkit-transform : translateX(0px);
```

See simplified JSbin here: http://jsbin.com/yezov/1/edit

Note I'm only seeing this on OSX Safari, not Chrome or Firefox on same machine. Not sure about other OSs. Also posted to SO here: http://stackoverflow.com/questions/22077093/safari-translatex-and-position-fixed-overflow-bug

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
