### ISSUE TITLE
Opening Fancybox entirely within a paeg div, not body element, and centering content within overlay

### ISSUE THREAD

**Issue by nimmolo** [fancyapps/fancyBox#822]
I'm using Fancybox to show html elements for a sort of step-by-step tutorial as a gallery set. I would like the fancybox and overlay both to appear **entirely within a div on my page** - not within the `body` element. 

You can [see the desired result here by clicking on the options tab at the top.](http://andrewnimmo.com/test/recent-work/posters/)

It's sort of working. I've currently got the Fancybox overlay opening inside my `#main` div as desired, rather than the default behavior of opening inside `body` element.

The crucial step was changing the parent element in the `// Tests that need a body at doc ready` section from `body` to `#main`.

The problem is the first fancybox content does not load properly inside the overlay, because the overlay is appended as a **sibling** of the wrap, within the `#main` div. Subsequent gallery elements are loaded with the `.fancybox-overlay` as the **parent** of `.fancybox-wrap` under `#main`, as expected. It is only the first loaded element that loads improperly.

What's going on?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by rafeeque-cairs** [comment]
You can add an option parentEl to the fancybox options,

Just like parentEl: '.myDivClass'
