### ISSUE TITLE
Thumbnail Helper

### ISSUE THREAD

**Issue by Elborath** [fancyapps/fancyBox#823]
I am very new to JS and JQuery and it's been years since I wrote a website in anything other than a host's package--have gone back to Dreamweaver. So am having to relearn basic html let alone xhtml, CSS and html5! So you're dealing with a newbie! Fancybox rocks and I'm getting my head around the coding BUT nowhere can I find a step by step guide to using the Thumbnail helper! Can anyone help?

**Comment by fancyapps** [comment]
In v3, it is already built-in.
