### ISSUE TITLE
Scroll functionality gone after closing the fancybox in FF

### ISSUE THREAD

**Issue by indrikenens** [fancyapps/fancyBox#824]
Hi, i'm having trouble with the scrolling in FF after closing the fancybox.
I could only reproduce this behaviour in FF, Chrome works fine for me.

I could also reproduce this bug in your own site: http://fancyapps.com/fancybox/
Best seen in the first image of the 'single images' examples, but it also occurs on other images at random.
If you close the lightbox and start scrolling right away, there's no scroll.
If, after vigorously scrolling for a while, you wait a moment, the scroll returns.

I think it's having issues when you start scrolling before the fade out has completed.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
