### ISSUE TITLE
FancyBox iframe breaks responsive layout on IE

### ISSUE THREAD

**Issue by ferrl** [fancyapps/fancyBox#825]
When I open and close the fancybox is like the layout just breaks. I don't know how to explain, but you can test it here: http://primesportfitness.com.br/professores

Just click in one of the photos and close the modal.

![screen shot 2014-03-06 at 23 17 48](https://f.cloud.github.com/assets/1896230/2353344/b6abbfdc-a59e-11e3-9fcf-ffbfb3f139ee.png)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
