### ISSUE TITLE
problem button next and prev in tz portofolio

### ISSUE THREAD

**Issue by tecniconapoletano82** [fancyapps/fancyBox#827]
hello I wanted to compliment you on your fancybox script really nice. I wanted to ask I have created a website in joomla in which I installed a plugin called TZ PORTOFOLIO of templaza which in turn use your script fancy box but have not included the possibility that ligth when you open a box with a picture inside missing forward and back buttons. I wanted to ask you how do I add if you could give me a hand. thank you very much and congratulations again.

**Comment by fancyapps** [comment]
It depends on how your theme has implemented fancyBox.
