### ISSUE TITLE
FancyBox not working in Chrome ll) but it works fine in firefox.

### ISSUE THREAD

**Issue by ManishKatoch** [fancyapps/fancyBox#830]
Hi,

I have implemented fancybox. It is not quite working well on chrome(not at all).

 jquer code :+1:      $(document.body).on('click', '.fancybox-manual-b', function () {
                alert("yes");
                var cid = $(this).data('pk');
                $.fancybox.open({
                    href: '/editormce.aspx?conid=' + cid,
                    autoSize: true,
                    autoDimensions: false,
                    type: 'iframe',
                    'iframe': {
                        preload: false // fixes issue with iframe and IE
                    },
                    padding: 5
                });
            });

c# code:
contentcontrol += "<br/><a  class=\"fancybox-manual-b readMore\" data-name=\"divedit\" data-type=\"textarea\" data-accid=" + ContentOwnerAccID + " data-pk=" + newcontentid + " href =\"javascript:\" id=" + newcontentid + ">Read More..</a>";

**Comment by fancyapps** [comment]
You should provide some working demo, because it just works.
