### ISSUE TITLE
Media plugin treats toJSON function as a media helper when json2 is used with IE7

### ISSUE THREAD

**Issue by gpoole** [fancyapps/fancyBox#833]
It's a very specific combination, but in jquery.fancybox-media.js on line 185 the loop over the F.helpers.media object seems to wind up looking at "toJSON" as a property of F.helpers.media. This seems to be because json2 adds "toJSON" to the Object prototype and all subsequent objects inherit it. When the media helper loops over the properties of F.helpers.media it winds up trying to do the following with "toJSON" as the current item:

``` js
item = opts[ what ];
rez  = url.match( item.matcher );
```

Since item.matcher is undefined when "toJSON" is the current item, url.match returns true due to the way .match works. To demonstrate, the following will return an array:

``` js
"".match(undefined)
```

The ultimate result is that IE7 spits out the following:

```
Unable to get value of the property 'replace': object is null or undefined 
jquery.fancybox-media.js, line 79 character 5
```

To make sure unintended properties are not tested, item.matcher should be confirmed as being defined and having a value before running url.match on it.

**Comment by fancyapps** [comment]
IE7 is not relevant these days.
