### ISSUE TITLE
fancyBox inappropriately adds body scrollbar in some cases

### ISSUE THREAD

**Issue by picobots** [fancyapps/fancyBox#836]
fancyBox is adding a scrollbar to the body of my fullscreen web app when it's open, and it doesn't look particularly good. (My app is designed to take up the full browser window and not have any scrollbars.)

It looks like it's the fancyBox overlay that's causing it; namely this `overflow-y: scroll;` style defined in fancybox.css:

``` css
.fancybox-lock .fancybox-overlay {
    overflow: auto;
    overflow-y: scroll;
}
```

What is the purpose of this style declaration? Removing it doesn't seem to affect anything in my casual testing. I would rather not be forced to show a full body scrollbar when fancyBox is open. Is it safe to remove the style declaration in question, or is that serving some purpose that's not immediately obvious?

See jsfiddle for example:
http://jsfiddle.net/55Fdp/

**Comment by extractachris** [comment]
I have commented-out these lines as well and it appears to be fine in my testing as well.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
