### ISSUE TITLE
CSS Class Fancybox-lock-test prevents scrollbars in Chrome

### ISSUE THREAD

**Issue by tolew1** [fancyapps/fancyBox#840]
I took me forever to find out why my scrollbars would disappear whenever there was scrollable content. This just started happening with Chrome Version 35.0.1897.2 dev-m. The latest version as of now. Once I remove the fancybox-lock-test class the scrollbars came back. I'm not sure why the class does it but that seems to at least get it working again by removing that. 

Fancybox ver 2.1.5

**Comment by MickeyKay** [comment]
I'm running into this same issue, however I'm not seeing any `fancybox-lock-test` class outputting in my markup. I do see it in the Fancybox source, but am not sure how it's affecting the output. I would like scrollbars visible as well, and they aren't appearing in Chrome for me. Can you please advise a bit more specifically on how you solved this issue? Thanks!

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
