### ISSUE TITLE
Fancybox moves around when text dialog comes up on mobile (testing on Android)

### ISSUE THREAD

**Issue by amodoke** [fancyapps/fancyBox#843]
Hi,
I am opening an inline single field (to collect email id's) form in fancybox version 2.

When using it on mobile, the form looks good and responsive, but when I bring up the text dialog to type my email id, fancybox goes crazy and moves out of the viewport.

Closing the text dialog brings it back to the center.

Options I am using:
autoCenter : true,
autoSize    : true,

Mobile: LG Optimus E970 Android 4.1

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
