### ISSUE TITLE
About Fancybox Multi Domain License

### ISSUE THREAD

**Issue by Codestar** [fancyapps/fancybox#847]
Hi,

I am Codestar from ThemeForest. I am planing to purchase FancyBox Multi Domain License 89$

Is it a developer license ? I mean, can i include and use it for unlimited web templates ? no further cost ?

Please reply me, I sent twice email but no reply.
Regards, Codestar

**Comment by mayrem** [comment]
Hi 
Where exactly should the license be deposited?
please help

**Comment by BredoZen** [comment]
> Hi,
> 
> By purchasing ONE Multi Domain License, you are allowed to include fancyBox
> in ONE theme for sale.
> 
> 2014-04-07 17:38 GMT+03:00 Codestar [notifications@github.com](mailto:notifications@github.com):
> 
> > Hi,
> > I am Codestar from ThemeForest. I am planing to purchase FancyBox Multi
> > Domain License 89$
> > Is it a developer license ? I mean, can i include and use it for unlimited
> > web templates ? no further cost ?
> > Please reply me, I sent twice email but no reply.
> > Regards, Codestar
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/[/issues/847](https://github.com/fancyapps/fancybox/issues/847)
> > .
> 
> Janis Skarnelis
> fancyapps.com

Hello
Is this information still relevant?
