### ISSUE TITLE
Fancybox is not support other link  

### ISSUE THREAD

**Issue by daonhut** [fancyapps/fancyBox#851]
Hi! all
I have problem when i using plugin fancybox.
I like to use youtube link from the list of fancybox support the run well.  
list link support Youtube in fancybox:
-          http://www.youtube.com/watch?v=opj24KnzrWo
-          http://www.youtube.com/embed/opj24KnzrWo
-          http://youtu.be/opj24KnzrWo
-      http://www.youtube-nocookie.com/embed/opj24KnzrWo
  however when I use this link : https://www.youtube.com/watch?feature=player_embedded&v=g094dhPVMaY
  the problems encountered.

I checked very carefully before thanks to the help
Help me?

**Comment by daonhut** [comment]
Thank for you, I said try

**Comment by SalahAdDin** [comment]
what is the media helper file?

**Comment by fancyapps** [comment]
v3 is a bit better with parsing youtube urls.
