### ISSUE TITLE
FancyBox conflict with drop down menu on iPhone

### ISSUE THREAD

**Issue by picadilly** [fancyapps/fancyBox#859]
I can't seem to get both the fancy box navigation AND the page drop down menu working together on the iPhone. It seems to be a conflict between these two:
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="../js/jquery-1.7.1.min.js"></script>

I tried reversing the order. Whichever one comes first is the one that works. Never both.
I also tried using 1.10 and 1.9 that came in the lib folder. But that caused the drop down menu on the desktop fail. 

Here's what I have: I'm not a master at this.
 
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="../js/jquery-1.7.1.min.js"></script>
    <script src="../js/superfish.js"></script>
    <script src="../js/jquery.hoverIntent.minified.js"></script>
    <script src="../js/jquery.easing.1.3.js"></script>
    <script src="../js/jquery.mobilemenu.js"></script>
    <script src="../js/script.js"></script>

<script type="text/javascript" src="../fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

<link rel="stylesheet" href="../fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />

<script type="text/javascript" src="../fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

<link rel="stylesheet" href="../fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" type="text/css" media="screen" />

<script type="text/javascript" src="../fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

<script type="text/javascript" src="../fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

<link rel="stylesheet" href="../fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" type="text/css" media="screen" />

<script type="text/javascript" src="../fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $(".fancybox").fancybox({
    nextEffect  : 'fade',
    prevEffect  : 'fade',
    padding     : 3
});
    });
</script>

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
