### ISSUE TITLE
closeBtn mark-up position

### ISSUE THREAD

**Issue by steveriffraff** [fancyapps/fancyBox#863]
Hi there,

I noticed by default the close buttons appears below the main content by default. I was wondering is it possible to appear inside `fancybox-inner`. That way I can use `position: relative` and the content will naturally follow after it?

I did try adding/rearranging it in the jquery.fancybox.js file, inside the HTML template TPL. Which looked a bit like this:

`<div class="fancybox-inner"><a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a></div>[code]`

Which got the button in the right place but it did break the layout and the button wouldn't trigger.

Thanks,
Steve

**Comment by fancyapps** [comment]
If you would upgrade to v3, you could change tpl to change structure completely.
