### ISSUE TITLE
Fancybox bug on zoomed iPhone / mobile

### ISSUE THREAD

**Issue by johnnywhitethe3rd** [fancyapps/fancyBox#864]
Hello,
My mobile site has two columns, as divs.
On the initial load, Fancybox works great.
When I double-tap on an iPhone the screen zooms in so that the text column is full width of the screen.
However in this view, when the Fancybox viewer is brought up it only fills about 80% of the screen, cramps the image to the left and creates a gray area to the right. 
I would think Fancybox viewer would fill the viewing area 100% and scale appropriately, regardless of the zoom level of the page underneath.

( I am using Fancybox v3 Beta)

I've included screenshots of the site on an iPhone - 1. the initial load of the site, 2. the site after double tapping to zoom in on the text, and 3. viewing an image in Fancybox while the site is zoomed in.

![view1-initialload](https://cloud.githubusercontent.com/assets/7595103/2988726/e0bb4c76-dc5c-11e3-97cc-9c79dcbe21c9.jpg)

![view2-zoomedin](https://cloud.githubusercontent.com/assets/7595103/2988729/ef0867be-dc5c-11e3-9c93-d81e7d804a6f.jpg)

![view3-zoomedwfancybox](https://cloud.githubusercontent.com/assets/7595103/2988730/f47248e6-dc5c-11e3-9f50-b851456f887c.jpg)

**Comment by fancyapps** [comment]
Hi, Sadly, mobile browsers do not play well with javascript if page is zoomed. V3 should work better, but it still will be zoomed.
