### ISSUE TITLE
Youtube embeds are not filling iframe?

### ISSUE THREAD

**Issue by POOLEworks** [fancyapps/fancyBox#867]
I have an 800 x 600 window that opens up. On most browsers, the youtube video fills the window.

Working fine in IE9, firefox, safari and chrome. 

IE10 and especially IE11 the video is reduced in size centered in the pop up window. 

Any suggestions to force the video to fill the window?

**Comment by fancyapps** [comment]
Sorry, I have never experienced such issue.
