### ISSUE TITLE
Prevent page reload on content click

### ISSUE THREAD

**Issue by sebastiankricner** [fancyapps/fancyBox#868]
Hello,

it might be very simple, but currently i do not find out how to prevent loading the originating page when closing fancybox by clicking on the content.

I use it with <a><img... combinations. When fancybox opens up the content is clickable and then loads the originating page. I wish to just close fancybox by content click.

Thanks.

**Comment by fancyapps** [comment]
Hi, I have no idea what is causing page reload for you.
