### ISSUE TITLE
Fancybox 2 will not open PDF in Firefox, IE11

### ISSUE THREAD

**Issue by dougkwilson** [fancyapps/fancyBox#870]
http://jsfiddle.net/LP7bq/

Firefox 29.0.1
IE 11.0.9600.17107

The grey overlay appears as does the loading animation.  The PDF is never displayed.  Clicking the gray overlay cancels/closes and the page is visible again.

Works in Chrome 35.0.1916.114

**Comment by fancyapps** [comment]
For full PDF support you would need to use something like https://mozilla.github.io/pdf.js/
