### ISSUE TITLE
Validate form loaded by html type

### ISSUE THREAD

**Issue by returnvoid** [fancyapps/fancyBox#872]
Hi 

I need to validate a form loaded inside by content:'<form>form content</form>' and type:'html'. I'm waiting for afterLoad callback but when I try to get the form this way jQuery('form', content) I get undefined. Is there any way to access the DOM elements inside the fancybox?

thank you

**Comment by fancyapps** [comment]
Just check what arguments are you receiving.

For v3 it would be:

<script type="text/javascript">
	$("[data-fancybox]").fancybox({
		onComplete: function( instance, slide ) {

			// Reference to DOM element of the slide; your elements will be inside it
			// console.info( slide.$slide );

		}
	});
</script>
