### ISSUE TITLE
Need an event to fire only when close is user initiated

### ISSUE THREAD

**Issue by Schepp** [fancyapps/fancybox#88]
I have a situation here where I have a user dashboard opening in a fancybox. From inside that the user can go to a fancybox where he can change passwords. When the user closes that window I want the dahboard to reappear so I defined something like:

``` javascript
'beforeClose': function(){
        dashboard_show();
        return false;
}
```

But now I get problems, when the user makes an error in the change password window and I display yet another fancybox with the error message. Displaying the error message also triggers beforeClose since fancybox #2 is being left. What I would need is a callback that really only triggers, when the user himself initiates a close action (i.e. clicking on the close button or ESC), not when it gets closed programmatically.

**Comment by fancyapps** [comment]
Hi, Sorry for a (very) long delay. V3 eliminates this issue by allowing to display a new modal without closing the current one.

E.g., your scenario would be:

````
Dashboard -> Form -> OK ?   -> Proceed
                  -> Error? -> Display a warning
`````
