### ISSUE TITLE
Oversized gallery images cut off; no scrollbars or scrolling

### ISSUE THREAD

**Issue by darwinDMG** [fancyapps/fancyBox#880]
I'm desperately trying to solve this issue as it's holding up the publishing of my updated website! I use Fancybox for a gallery of my projects, each with a long description underneath. I've set 'fitToView' to 'false' and set a 'maxWidth' to fix a responsive issue on phones; however, the large images and/or the description text are sometimes cut off on smaller screens. The image window will not scroll, nor move at all when the full page is scrolled down -- the content just keeps getting cut off.

The site is here <a href="http://www.weirdsmobile.net/new/brushed/">Weirdsmobile</a>

Click on any image in the Projects to see what is happening; you may need to shrink your browser height to see the error. I've tried so many variations on the code but scrollbars or scrolling will not work.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
