### ISSUE TITLE
missing callback for group gallery

### ISSUE THREAD

**Issue by Fred87** [fancyapps/fancyBox#882]
When I was looking at the docs I thought beforeLoad would only run once when fancyBox opens it's first image, but it actually runs everytime fancyBox loads an image (even inside a group gallery).  http://jsfiddle.net/6jGAs/7/

If that's normal behaviour then we should have 2 extra callbacks that would run when a gallery is displayed - beforeInit and afterInit.

Sorry if I'm missing something but I cannot find a callback that will run only once when I try to open a group gallery.

**Comment by fancyapps** [comment]
Yes, "beforeLoad" is called for each item. V3 has "onInit" callback that is called only once.
