### ISSUE TITLE
Google Maps is opened as a classic link

### ISSUE THREAD

**Issue by Mehdib92** [fancyapps/fancyBox#884]
I tried to use fancybox to open a Google Map in a lightbox but it doesn't work, the link is opened link a classic link. I thing itis because of the new URL that GMaps is generating (https://www.google.fr/maps/place/Paris/@48.8588589,2.3470599,13z/data=!3m1!4b1!4m2!3m1!1s0x47e66e1f06e2b70f:0x40b82c3688c9460)

**Comment by fancyapps** [comment]
Try upgrading to v3, it has google maps support out of the box.
