### ISSUE TITLE
Can't write in text area wraped in Fancy Box in Ipad 

### ISSUE THREAD

**Issue by railsfactory-arunkumar-n** [fancyapps/fancyBox#886]
i'm unable to write text in text area which is warped with the Fancy Box. When i'm touches the text area at the time the virtual key board get hangs.i cant able to get keybord back. also i tried with focus(), which is not working in ipad. 

except ipad, in all other device its working fine only.

**Comment by fancyapps** [comment]
Try upgrading to v3.
