### ISSUE TITLE
FancyBox v3 Beta Google Maps API Offset Position Bug

### ISSUE THREAD

**Issue by Hawaii96815** [fancyapps/fancyBox#891]
I'm opening a Google Maps API file that I created using FancyBox 2.1.5 and it works perfectly. However, when I change to FancyBox v3 Beta, the map doesn't center correctly and it seems the center is moved to the upper left (North West). My link to the Google Maps API file has class="fancybox fancybox.iframe".

The Google Maps API v3 file has Javascript to center the map as follows:

```
var latlng = new google.maps.LatLng(parseFloat(latStr),parseFloat(lngStr));
var myOptions = {
    zoom: zm,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.HYBRID
};
var map = new google.maps.Map(document.getElementById("map_canvas"),myOptions);
```

**Comment by fancyapps** [comment]
Give v3 a try - http://fancyapps.com/fancybox/3/
