### ISSUE TITLE
Fancybox 2.1.5 + Firefox very slow

### ISSUE THREAD

**Issue by kinaz** [fancyapps/fancyBox#892]
Hi,

I have just rolled back to 2.1.4 because 2.1.5 on Firefox and IE was way too slow.
The browser cursor was hanging for seconds before the first image opened.

I couldn't find what the problem is.

**Comment by megahoy** [comment]
have the same problem
fancybox 2.1.5 is very slow on Firefox 50.1.0 (Ubuntu 14.04)
on Google Chrome works perfect

**Comment by fancyapps** [comment]
I suspect the image does not open immediately right after opening the page? Then probably the browser is too busy to load the page...

**Comment by fancyapps** [comment]
Then it is probably is due to "*" selector in the code for repositioning fixed elements. 

You could try to disable "locked" feature (http://jsfiddle.net/XaWZE/) or give a try for v3 (http://fancyapps.com/fancybox/3/ - it is something like "release candidate" right now).

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
