### ISSUE TITLE
Unresponsive on Windows 8 Chrome

### ISSUE THREAD

**Issue by hugofelp** [fancyapps/fancyBox#895]
Fancybox is not responding to window being re-sized on Chrome on Windows 8. The modal doesn't update size or positioning. Tested examples from the docs page (http://fancyapps.com/fancybox/), in two different PCs running Windows 8.1 Enterprise and Chrome 35.0.1916.153 m. Browser has no addons or extensions.

Works as expected on other browsers and same version of Chrome running on Windows 7.

**Comment by fancyapps** [comment]
Works fine on Windows 10, not sure what would be OS specific that could break something.
