### ISSUE TITLE
FancyBox v3 Beta AJAX not working at all?

### ISSUE THREAD

**Issue by suprpp** [fancyapps/fancyBox#898]
I'm using fancyBox3 beta on a site and it's working great (responsive, too).

But I can't get the 'ajax' option to work. I'm trying to load a local URL using ajax, but I always get "The requested content cannot be loaded.". The same code works flawlessly with fancyBox v2.

Any ideas?

**Comment by fancyapps** [comment]
v3 is available for some time.
