### ISSUE TITLE
Area of Image Not Being Maintained in Scaling

### ISSUE THREAD

**Issue by JimDutton** [fancyapps/fancyBox#900]
I just found Fancybox and am very pleased with its features (though I am still looking for a full list of them with explanations).

I am working on making some sites responsive.  Fancybox adjusts well when the browser is made smaller--at least for landscape images.  The ratio of my original images is 600:400 pixels (landscape) and 400:600 (portrait).  When the images display in a maximized browser window the ratio is about 1.45:1 (landscape) and 1:1:45 (portrait)..  The area of each type of photo is the same--and this is the goal.

When I resize the browser to the dimensions of a smartphone, Fancybox appears to set the image width first, then adjust the height of landscape images so that the width is (more or less) 1.45 x the height. That's fine.  But with portrait images, the width is set the same as for landscape, and as a result, the 1.45 ratio means the image is quite tall.  So the ratio of the two is about the same, but the main point is that the area of a portrait image is more than twice the area of a landscape.  This means that portrait images look really out of proportion to landscape ones. To have the two types of image appear similar, portrait images need to be scaled down, so that the width would be less than for landscape--in other words, portrait images would not fill the space horizontally.  

So I'm wondering if there is a setting to have Fancybox scale images so that the area of images would remain proportionally the same.  Thanks for any help.

**Comment by fancyapps** [comment]
Sorry, I could not quite get, could you show some screenshots visualizing your issue?
