### ISSUE TITLE
Whether to support play local MP4 file directly?

### ISSUE THREAD

**Issue by maxmas** [fancyapps/fancyBox#901]
Hi, 
This is a great and wonderful script.
I very love it, it is very useful.
But I encountered a problem, it can not support play MP4 file directly.
If my video is on the server, rather than upload it to youtube.
Would you support it in next update?
Thanks!!

**Comment by fancyapps** [comment]
The problem with html5 video is that there are so much options (like, multiple sources, screenshots, etc) and I can not think of nice and clean API for that. 
Anyway, you can use $.fancybox.open() to display any html, even html5 video.
