### ISSUE TITLE
Adjust jQuery Fancybox' iframe height dynamically according to iframe contents 

### ISSUE THREAD

**Issue by joshme20416** [fancyapps/fancyBox#902]
I am using fancyBox - jQuery Plugin version: 2.1.4 (Thu, 10 Jan 2013) to show the modal pop and in that pop up i  am showing contents through iframe. Now I want to set the height and width of iframe and modal pop according to the height of the contents of the iframe. all heights will be dynamic and it should be responsive also. 

Please help me on this.

**Comment by fancyapps** [comment]
It should be out of the box, if contents of the iframe is accessible.
