### ISSUE TITLE
Fancybox 2.1.5 is not working in Firefox 31.0 with jQuery 2.1.1

### ISSUE THREAD

**Issue by TheFreeman** [fancyapps/fancyBox#908]
Hi,

Fancybox 2.1.5 is not working in Firefox 31.0 with jQuery 2.1.1

<pre>
$.fancybox( 
    "Textmessage bla bla bla bla",
    { 
        autoSize: true, 
        center: true,
        closeBtn: false,
        closeClick: false,
        helpers:    { 
            overlay : { 
                closeClick : false 
            } 
        }
    }
);
</pre>

is working perfectly in Chrome 36.0.1985.143 :-)

how could i resolve this?

kind regards

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by TheFreeman** [comment]
Thank you, it worked. :-)
