### ISSUE TITLE
Landscape-to-portait orientation turn fails on Android when width is set greater than 70%..

### ISSUE THREAD

**Issue by jonascarlbaum** [fancyapps/fancyBox#91]
Scenario:
When I initialize FancyBox 2 with a percentage width greater than 70 and turn the Android-phone from landscape view to portrait view the page stucks in a loop of adjusting the box from landscape to portrait to landscape to portait etc. etc. — the result is a page "jumping" sideways...

Turning the phone back to landscape makes the box correctly adjusted and there is no strange loop, until turning back to portait.

I reallly want the width to be around 80-90% to be able to show a form in an iFrame in a readable way, 70% isn't enough for me.

On other devices, such as iPhone etc. 80% or 90% works just fine, so it seems to be a device-specific issue...

Device information:
Android Phone: HTC Desire S S510e
Android Version: 2.3.5
HTC Sense-version: 3.0

Javascript-setup scenario (left out some logic parts):

  $('.fancybox').each(function() {  
    /_width and height can be passed as querystring parameters in the url_/
    var width = /_check some width logic_/;  
    var height = /_check some height logic_/;

```
$(this).fancybox({  
  'maxWidth'        : width,  
  'maxHeight'      : height,
  'width'                : '90%' /*WORKS IF '70%'*/,
  'height'              : '90%',
  'fitToView'         : false,
  'autoSize'          : false,
  'closeClick'       : false,
  'openEffect'      : 'none',
  'closeEffect'      : 'none',
  'type'                  : 'iframe',
  'afterShow': function() { $("body").css({'overflow': 'hidden'}); }, 
  'afterClose': function() { $("body").css({'overflow': 'visible'}); },
});
```

  });

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
