### ISSUE TITLE
Elastic risizing

### ISSUE THREAD

**Issue by MOWebCreation** [fancyapps/fancyBox#910]
Hello all,

I don't know if the question have been already submitted, I'm sorry if it's the case, I didn't find any solution for solve my problem.

I would like to resize my modal box with an elastic effect (like in "opening" context) after inner update.
I've tried with some options but it don't work... the modal is well resized, but brutally.
This is my code : 

```
$('.fancybox-inner').html(ajax.responseText);
$.fancybox.update({
    openEffect: 'elastic',
    openSpeed: 600
});
```

I've already seen this effect after modal content update... how can say me how to do this with fancybox ??

Thankz by advance for your help !

Mickael

**Comment by sweiguny** [comment]
hello,

i am also interested in the capability to set an animation for fancybox.update().
to be honest: for me, it's kind of a flaw not having an option for an update effect.

br, simon

**Comment by fancyapps** [comment]
With v3, you can set your own animations using CSS.
