### ISSUE TITLE
iOS fancybox overlay over <video> disables close link

### ISSUE THREAD

**Issue by kylane** [fancyapps/fancyBox#914]
Hi guys,

I have a fancybox popup over a HTML5 <video> element - and if the popup appears over the <video> then none of the links (including the close link) aren't usable.

Can you please advise? Thanks! :)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by kylane** [comment]
3 years for a reply huh.. wow..

**Comment by fancyapps** [comment]
You are welcome :)
Sorry, but the requests for support were coming like avalanche (1093 closed issues so far, not to mention direct messages, etc).

About your issue - I still do not know what to comment, I just hope it has solved itself with time (e.g., browsers are improved).
