### ISSUE TITLE
nextEffect:elastic causes horizontal scrollbar appearing on animation

### ISSUE THREAD

**Issue by danyaPostfactum** [fancyapps/fancyBox#916]
To reproduce: resize the window, so it perfectly fits opened image. Press next: slide will be shifted, so overlay div will get overflowed and you will see shortly appeared horizontal scrollbar. It disappears on animation end. This is because of https://github.com/fancyapps/fancyBox/blob/master/source/jquery.fancybox.css#L196

Do we really need overflow: auto?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
