### ISSUE TITLE
Fancybox: disable right click help

### ISSUE THREAD

**Issue by ghost** [fancyapps/fancyBox#917]
I need help with disable right click on fancybox. I can't get it to work. Please help with finding a solution. 

<script type="text/javascript">
    $(document).ready(function(){
        $(".fancybox").fancybox();
    });

    $(".fancybox").fancybox({
        padding : 0
    }); 
</script>   

To disable right click, I have to add this script:

$(".fancybox")
    .attr('rel', 'gallery')
    .fancybox({
        beforeShow: function () {
            /\* Disable right click */
            $.fancybox.wrap.bind("contextmenu", function (e) {
                    return false; 
            });
        }
    });

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3. There is an option "protect" that implements basic image protection.

**Comment by akilpatel** [comment]
Thank you @fancyapps :)
