### ISSUE TITLE
fancybox-media don't works

### ISSUE THREAD

**Issue by SalahAdDin** [fancyapps/fancyBox#923]
Hi men, i like you plugin, now i'm using and a like it.

But, i have a problem.

I'm triying to user your plugin for show videos in a lightbox, but, when i do click in my a tag, he send me for the video, in this case, youtube video, and i don't know why works bad.

I'm trying to use a button for show the lightbox, because when i do click in my vide, this begin to play, when i put only a thumbnail and i do click, don't works anyway.

Then, i try to use a button for show the pop up, like this.
![parapregutnar](https://cloud.githubusercontent.com/assets/5034215/4195436/75562cd0-37bf-11e4-974c-7928adca223b.png)

Is the eye icon, but, if don't work whitout and video and thumnbail, only the text, how works with the button?

Thank you for your help!

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
