### ISSUE TITLE
Thumbnails helper closes fancybox

### ISSUE THREAD

**Issue by vytsci** [fancyapps/fancyBox#926]
Hi, i've found an issue in your fancybox code. Its hard to spot, but manage to do it. On line 1966   D.undelegate(selector, 'click.fb-start').delegate(selector + ":not('.fancybox-item, .fancybox-nav')", 'click.fb-start', run);
Variable 'selector' is a selector from wich fancybox have been called. But if i call fancybox smth like $(this).find('a').fancybox();
That variable 'selector' becomes 'a' and puts fancybox event on whole page 'a' elements.
Good luck :)

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
