### ISSUE TITLE
Scroll Bar not locked on mobile devices

### ISSUE THREAD

**Issue by yuri1992** [fancyapps/fancyBox#927]
when im using fancyBox on mobile devices, i still can move the scroll bar, although css -> .body {overflow:hidden}, you can use "'touchmove', function(e){e.preventDefault()}" or sometings like this to prevent this.

**Comment by Craigy-** [comment]
+1
But "'touchmove', function(e){e.preventDefault()}" blocks scroll inside fancybox too.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
