### ISSUE TITLE
fancybox window blinking

### ISSUE THREAD

**Issue by leandroruel** [fancyapps/fancyBox#928]
i am using fancybox lastest (2.1.5), and after add some more plugins at page, i have a weird issue here, the fancybox window are blinking, i verified chrome console and nothing happens.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by leandroruel** [comment]
thumbs down for late answer after 3 years... and i forgot this issue.

**Comment by fancyapps** [comment]
Since no one else complained about this issue, it got lost among many others (more than 1000 issues closed so far; mostly asking for help or feature requests). 
Have a nice day and try v3! (it is a free upgrade for those who purchased v2).
