### ISSUE TITLE
Images below a certain height cause scrollbars and are not responsive

### ISSUE THREAD

**Issue by sumobi** [fancyapps/fancyBox#929]
Fancybox 2.1.5

See the first image on this page after the main featured image:
http://affiliatewp.com/new-paypal-payouts-add-on-now-available/

When clicked scrollbars appear and the image is not responsive when making the browser window small. All the other images seem to be fine. I've replicated this locally. It seems there's an issues with the height of the image, it needs to be a certain height or it will break.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
