### ISSUE TITLE
Fancybox with embedded vimeo is not loading in IOS 8

### ISSUE THREAD

**Issue by Mossito** [fancyapps/fancyBox#930]
Im a web developer and I have a problem, on ipad air and iphone 5s, IOS 8, vimeo videos should load inside a fancybox, it works perfect in IOS 7, now in IOS 8 can not be displayed.
When you click, the fancybox is not loading, it stays showing the spinning wheel forever, for images everything works good, so the problem is only with vimeo videos. Im using also fancybox-media.js.
My site with all the fancybox vimeo videos is www.toyann.com in case you want to test it, but also happens with the example at the bottom of the site http://fancyapps.com/fancybox/
Thanks for your help in advance.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
