### ISSUE TITLE
Youtube play button doesn't work on mobile devices

### ISSUE THREAD

**Issue by lgobatto** [fancyapps/fancyBox#944]
i found that it's missing the controls and ps params on the youtube iframe src url so in line 100 of fancybox media helper file i added it and now it's working fine.
ps: 'docs',
controls: 1

partial code:
youtube: {
                matcher: /(youtube.com|youtu.be|youtube-nocookie.com)\/(watch\?v=|v\/|u\/|embed\/?)?(videoseries\?list=(._)|[\w-]{11}|\?listType=(._)&list=(._))._/i,
                params: {
                    autoplay: 1,
                    autohide: 1,
                    fs: 1,
                    rel: 0,
                    hd: 1,
                    wmode: 'opaque',
                    enablejsapi: 1,
                    ps: 'docs',
                    controls: 1
                },
                type: 'iframe',
                url: '//www.youtube.com/embed/$3'
            },

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
