### ISSUE TITLE
Fancybox v3 beta crashes in mobile Safari in iOS 8.0.2

### ISSUE THREAD

**Issue by saudepp** [fancyapps/fancyBox#947]
My website uses the image gallery of Fancybox 3 beta. This works just fine, I am using the beta to have swipe functionality for mobile users.

However, since my upgrade to iOS 8 on my iPhone, Safari crashes when the Fancybox 3 image gallery is used, after swiping through a few images. Also touching the left / right arrows to go through the images lets Safari crash. I am currently using iOS 8.02 on an iPhone 5. It appears that Safari running on iOS 7 does not have this issue.

I tried to debug by connecting the iPhone to my Mac and using remote debugging (displaying the debug console on the Mac while browsing Safari on the iPhone). However, as soon as Safari crashes, the debug console on my Mac closes.

Here you can view the "live demo":

http://www.wellness-heaven.de/wellnesshotel/aqua-dome-tirol-therme/testbericht-kulinarik/

Just click on the central, large image to start the Fancybox v3 gallery, then swipe through 10-20 images ...

Any help would be appreciated.

You can select also any other hotel listing on my site:
http://www.wellness-heaven.de/
Then click on the main hotel image to start the image gallery, causing trouble after some swipes ...

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
