### ISSUE TITLE
Autostart feature breaks when script is combined

### ISSUE THREAD

**Issue by RobinClowers** [fancyapps/fancyBox#948]
I'm using the Rails asset pipeline to combine all my scripts into a single file. This breaks fancybox completely because of this:

``` javascript
if ($("script[src*='jquery.fancybox.js']").attr('src').match(/autorun/) ){
```

The `attr` call returns undefined, so this throws.

**Comment by michaelryanmcneill** [comment]
Yes, I also am experiencing this error, commenting it out solves it for me. Would love to see some resolution to this issue.

**Comment by vikasjayaswal** [comment]
Agreed. I am not sure how to fix this? Are you suggesting commenting the entire if block?

/* 
if ($("script[src*='jquery.fancybox.js']").attr('src').match(/autorun/) ){
			$("a[href$='.jpg'],a[href$='.png'],a[href$='.gif'],.fancybox").attr('data-fancybox-group', 'gallery').fancybox();
		} */

**Comment by RobinClowers** [comment]
This would at least keep it from breaking everything without removing the feature.

```javascript
var src = $("script[src*='jquery.fancybox.js']").attr('src')
if src && src.match(/autorun/) ){
  ...
}
```

The autostart feature still wouldn't work if it was combined, but I'm ok with that.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
