### ISSUE TITLE
fancybox 2 doesn't work with bootstrap 3.2

### ISSUE THREAD

**Issue by danieleizik** [fancyapps/fancyBox#949]
Hi,
I can't run fancybox 2 (latest version) on my site which runs bootstrap 3.2.
Links just open normally without fancybox.
I found a solution here: https://github.com/fancyapps/fancyBox/issues/519 but couldn't find the line that needs to be changed.

Please advise if there's a solution to this problem.

Thanks,
Daniel.

**Comment by szabofe** [comment]
Hello
3.2 Bootstrao gallery created with a link to:
http://family-team.emszinet.hu/proghutest/17/sablon2/galeria.html
No need to add the fancybox

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
