### ISSUE TITLE
problem fancybox.ajax

### ISSUE THREAD

**Issue by achEydo** [fancyapps/fancyBox#95]
Hello

Fancybox I use to display two large images side by side.

I use fancybox.ajax

But first click on the image, the box has a size 0, if we click again on the same
image it works.

example: http://fancy.eydo.com/

Thanks for your help

**Comment by fancyapps** [comment]
Preloading images from ajax request seems to be bad idea. But if you really want that, you can do it yourself and later call $.fancybox.open() to display your content.
