### ISSUE TITLE
Chrome Scrolling Issue with open Lightbox

### ISSUE THREAD

**Issue by DerKnob** [fancyapps/fancyBox#950]
Hi,

since some time I have a problem with the scrolling of the background, when the fancybox lightbox is open.

scrollOutside is set to true (default)

You can see the effect here: http://test.cooking4life.de/index.php?menu=apps
And than click on login. The background is scrolling when using the mouse wheel.

This is not happening with the IE or Firefox. And also was not happening with the Chrome in the past. Not sure if this came from an Chrome update or maybe something else I did on the page.

The examples from the fancybox page are working correct.

Anyone a idea?

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
