### ISSUE TITLE
Error when clicking Fancybox for the second time

### ISSUE THREAD

**Issue by moikzz214** [fancyapps/fancyBox#951]
Im using FancyBox to show inline content. It works as expected but if I open the fancybox and close it and then open it again it shows the entire site inside in a fancybox instead the inline content. 
the first time it works fine but when clicking the second time without reloading the page it display the whole page.
here's my code
< a title="Select Specs and Copy" class="spec_link" href="#specs<?php echo $version_id?>"><i class="fa fa-files-o fa-3"></i></a>
< script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".spec_link").fancybox();
    });
    < /script>

**Comment by ShandyMac** [comment]
Hey moikzz214,

I hope you've sorted this issue by now! But just in case, I was experiencing the same issue and managed to work around it with the following JavaScript:

```javascript
function reAddLightboxParent {
        var popupParent = $("#yourPopup").parent();
        jQuery(document).on('fancybox-cleanup', function () {
            popupParent.find('.fancybox-inline-tmp').replaceWith($("#yourPopup"));
        });
}
```

more info can be found <a href="http://mymonkeydo.com/fancybox-not-working-after-second-click/">here</a>

Hope this helps

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
