### ISSUE TITLE
Using Fancybox code with WordPress 

### ISSUE THREAD

**Issue by paaljoachim** [fancyapps/fancyBox#954]
Hey

I have added the following code to the functions.php file:

<code>
/\* Enqueue Fancybox */
add_action( 'wp_enqueue_scripts', 'enqueue_fancybox' );
function enqueue_fancybox() {
    wp_enqueue_style( 'fancybox-css', get_bloginfo( 'stylesheet_directory' ) . '/fancybox/fancybox.css', array(), CHILD_THEME_VERSION );
    wp_enqueue_script( 'fancybox', get_bloginfo( 'stylesheet_directory' ) . '/fancybox/jquery.fancybox.pack.js', array( 'jquery' ), '1.0.0' );
    wp_enqueue_script( 'fancybox-init',  get_stylesheet_directory_uri() . '/fancybox/fancybox-init.js', array( 'fancybox' ), '1.0.0', true );

}
</code>

and added the following to a fancybox-init.js file:

/\* http://code.tutsplus.com/tutorials/add-a-responsive-lightbox-to-your-wordpress-theme--wp-28100 */

<code>
(function($) {

```
// Initialize the Lightbox for any links with the 'fancybox' class
$(".fancybox").fancybox();

// Initialize the Lightbox automatically for any links to images with extensions .jpg, .jpeg, .png or .gif
$("a[href$='.jpg'], a[href$='.png'], a[href$='.jpeg'], a[href$='.gif']").fancybox();

// Initialize the Lightbox and add rel="gallery" to all gallery images when the gallery is set up using [gallery link="file"] so that a Lightbox Gallery exists
$(".gallery a[href$='.jpg'], .gallery a[href$='.png'], .gallery a[href$='.jpeg'], .gallery a[href$='.gif']").attr('rel','gallery').fancybox();

// Initalize the Lightbox for any links with the 'video' class and provide improved video embed support
$(".video").fancybox({
    maxWidth        : 800,
    maxHeight       : 600,
    fitToView       : false,
    width           : '70%',
    height          : '70%',
    autoSize        : false,
    closeClick      : false,
    openEffect      : 'none',
    closeEffect     : 'none'
});
```

})(jQuery);
</code>

 I would to:
Click the image and see the original size image in a lightbox. Not the 100% of the view port. As some images can become too small. I added a max width and max height of none to .fancybox-image and .fancybox-iframe. I was then able to see the image in its original size, but now I am working on getting the skin etc to be the same size. As other parts are now in their original code state much smaller then the new image. How should I fix this?

It would also be nice to have a move the cursor over the image and have a zoom plus icon. Then in the lightbox state zoom minus and click the image to zoom out again.

Btw 
I am writing an article on using lightboxes in WordPress without plugins:
http://easywebdesigntutorials.com/adding-a-lightbox-to-wordpress-without-using-a-plugin/

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.

**Comment by paaljoachim** [comment]
I have downloaded the newest version and here is the init js code that worked with WordPress:

```
jQuery(function( $ ){
	$('a[href*=".jpg"], a[href*=".jpeg"], a[href*=".png"], a[href*=".gif"]').fancybox({
	});	
});
```

I am now working on getting the galleri and options working.
