### ISSUE TITLE
Not responsive with Google Chrome on Windows 8.1

### ISSUE THREAD

**Issue by legolas108** [fancyapps/fancyBox#957]
When resizing window fancyBox won't resize the current gallery photo as it does so nicely with Firefox on Win 8.1, or Chrome on Win7/XP, or Firefox/Chrome on Linux/KDE.

**Comment by levipadre** [comment]
Hi, I have the same problem. Win 8.1, Chrome.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
