### ISSUE TITLE
Slideshow with only 1 element?

### ISSUE THREAD

**Issue by jeffkenny** [fancyapps/fancyBox#958]
You shouldn't be able to hit the [spacebar] to start a slideshow when there's only 1 element in the fancybox and it's not triggered from a gallery.

See here:
http://jsfiddle.net/2LXNh/746/ -- you can click to open the image in a fancybox, but then if you hit the spacebar, it'll start a slideshow and just keep "playing" that 1 image.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
