### ISSUE TITLE
Position title to left or right side

### ISSUE THREAD

**Issue by Znow** [fancyapps/fancyBox#964]
Hi

Im in very need of a way to position the title text to the left or right side, instead of only the top and bottom.

Would be very glad, if anyone had a fix for this

Regards

**Comment by jankoc** [comment]
I am also interested in title to the right. Did you solve this, Znow?

**Comment by Znow** [comment]
Sorry for the late response :)

Nope, did never resolve it.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
