### ISSUE TITLE
Content Security Policy Error

### ISSUE THREAD

**Issue by griesi007** [fancyapps/fancyBox#969]
Hi,

when using the image gallery (FancyBox 2.4.2.7) with Content Security Policy an error message that inline js cannot be executed appears when clicking the next button. This is because of the inline javascript which gets inserted by fancybox on the next / previous buttons. How can fancybox mad compatible with CSP? <a title="Next" class="fancybox-nav fancybox-next" href="javascript:;"><span></span></a>

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
