### ISSUE TITLE
A link in Fancybox is not executable via enter key

### ISSUE THREAD

**Issue by DelawareConsulting** [fancyapps/fancyBox#970]
Dear,

We have a simple fancybox popup in Rails. When the popup opens we set focus so the user can navigate thought it via the keyboard. But they cannot execute the links in popup via the enter key. Though they can execute buttons via the enter key.

 <div id="quickSignin" style="display: none;">
            <div id="wrap">
              <% if @force_light_box %>
              <h1 tabindex="1"><%= t :header_already_account, :scope =>[:quick_sign_in, :index] %></h1>
              <span><%= t("account.message") %></span>
              <% else %>
              <h1 tabindex="1">
              <%= t :header, :scope =>[:quick_sign_in, :index] %></h1>
              <% end %>
              <label id="quickSigninError" style="display:none; color:red; margin-left:5px; font-weight:bold;">
              <%= t(:unauthenticated, :scope =>[ :devise, :failure ]) %></label>
              <%= form_for(User.new, :url =>
              user_session_path(:format => :html), :remote => true, :html => {:id => "myform"}) do |f| %>
              <div class="signedInorNot">
                <%= f.button t("account.yesbttn"), :tabindex => "2", :class =>"nice medium blue button", :id => "openSigninBtn" %>
                <%= f.button t("account.nobttn"), :tabindex=>"3",:class =>"nice medium blue button cancelBtn", :id => "cancelBtn1" %>
              </div>
              <div class="signinBlockPopup" style="display:none">
                <div>
                  <%= f.label :email %>
                  <%= f.text_field :email, :class => "z", :tabindex => "2" %>
                </div>
                <div>
                  <%= f.label :password, t("apply.create.labels.password_clean") %>
                  <%= f.password_field :password, :tabindex => "3" %>
                </div>
              </div>
              <div class="submitbttwrap" style="display:none">
                <%= f.button t("account.sign_in_old"), :class =>"nice medium blue button", :id => "submitBtn", :tabindex => "4" %>
                <% if @force_light_box %>
                <%= f.button t("account.sign_in_new"), :class =>"nice medium blue button", :id => "submitBtnCurrent", :tabindex => "5" %>
                <% end %>
                <%= f.button t("account.cancel"), :class =>"nice medium red button cancelBtn", :id => "cancelBtn", :tabindex => "6" %>
                  <a tabindex="8" href="http://www.google.com">Test </a>
                <p class="interest-desc forgotpasswordPopup">
                <%= link_to t("account.forgot_question"), new_user_password_path, :class =>"forgotPassword", :tabindex => "7" %></p>
                  <div class="large-12 columns">
                  <div id="loadingSpinnerPopup"  style="display: none;">
                    <p><%= t("apply.create.labels.login_message")  %></p>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>

**Comment by fancyapps** [comment]
Hi, I have no idea what could cause this. Maybe upgrading to v3 would help.
