### ISSUE TITLE
Fancybox media helper not loading youtube videos

### ISSUE THREAD

**Issue by colinaut** [fancyapps/fancyBox#971]
Seems to have just happened recently so I'm guessing youtube changed something that broke fancy box embeds. Not working on the main fancy box page either so it's not my code: http://fancyapps.com/fancybox/

**Comment by finion** [comment]
It seems 'http://' has missing on url and I tried:

* add "url = "http://" + url;" on jquery.fancybox-media.js line 184, it works.

```javascript
if (rez) {
    type   = item.type;
    params = $.extend(true, {}, item.params, obj[ what ] || ($.isPlainObject(opts[ what ]) ? opts[ what ].params : null));

    url = $.type( item.url ) === "function" ? item.url.call( this, rez, params, obj ) : format( item.url, rez, params );
    url = "http://" + url;
    break;
}
```

* modified "format( item.url, rez, params );" to "format( url, rez, params );" on jquery.fancybox-media.js line 184, and it doesn't work even the url is correct.

```javascript
if (rez) {
    type   = item.type;
    params = $.extend(true, {}, item.params, obj[ what ] || ($.isPlainObject(opts[ what ]) ? opts[ what ].params : null));

    url = $.type( item.url ) === "function" ? item.url.call( this, rez, params, obj ) : format( url, rez, params );

    break;
}
```

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
