### ISSUE TITLE
fancybox iframe maxHeight and maxWidth values ignored in Google Chrome

### ISSUE THREAD

**Issue by pizzle1983** [fancyapps/fancyBox#975]
I'm experiencing a possible problem which I can also re-create looking at the example on the fancyapps website:

http://fancyapps.com/fancybox/#examples

Clicking on the 'Youtube (iframe)' link when using Google Chrome (I'm using Version 39.0.2171.71 at the moment) displays as 100% height and width and seems to ignore the maxHeight and maxWidth settings of the fancybox. Works OK in the latest versions of FF, IE and Safari.

Also, possibly related to this, loading Google Maps iframe content also tries to be displayed full width and height and then just gives the error 'The Google Maps Embed API must be used in an iframe.'.

This can also be re-created on the fancyapps url above when selecting the 'Google Maps (iframe)' link.

**Comment by johannvdwalt** [comment]
I am experiencing the same issue, but not with iframe, with normal jpeg files.  Is there a woraround to ensure that a small image is not enlarge to fill the viewport of the device as it results in very poor quality display.

**Comment by johannvdwalt** [comment]
Actually re-reading the initial issue, mine is a bit different, as it stretches the photo to fit the viewport of the device larger than the size of the original jpeg.  This does not happen on firefox and Internet explorer, only on chrome.  Check this link for an example (http://johann.vdwalt.net)

**Comment by shaadh** [comment]
Same problem I am facing with my fancybox
http://stackoverflow.com/questions/35358347/fancybox-stretching-to-height-of-browser-window-when-using-an-iframe-only-in-chr

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3 - you can set iframe dimensions using CSS or override them using JS, if needed.
