### ISSUE TITLE
Bower issue

### ISSUE THREAD

**Issue by rctneil** [fancyapps/fancyBox#979]
When I try to install Fancybox using Bower I don;t get the updated bower.json file. Bower also outputs these errors when doing so:

bower fancybox#\*          invalid-meta fancybox is missing "main" entry in bower.json
bower fancybox#\*          invalid-meta fancybox is missing "ignore" entry in bower.json

Any ideas on how to solve this?

**Comment by alerosa** [comment]
Try to install it with the following command:
```
bower install fancybox#master
```

**Comment by nickmeagher** [comment]
@alerosa that helped me!

Thanks!

**Comment by fancyapps** [comment]
Duplicate of #820
