### ISSUE TITLE
Fancybox is not centered when parent window scrolls

### ISSUE THREAD

**Issue by Viswanath588** [fancyapps/fancyBox#980]
I am using Fancybox 1.3.4 version. 
Here my issue is while parent window is scrolling up down respective child fancybox is not centered to the window.

Here is my code for fancy box

  $(".filtersPopup").fancybox({
  'width': '100%',
  'height': '100%',
  'transitionIn': 'elastic',
  'transitionOut': 'elastic',
  'speedIn': 600,
  'speedOut': 200,
  'overlayColor': '#111111',
  'overlayOpacity': 0.4,
  'modal': true,
  'hideOnOverlayClick': false,
  'autoDimensions': true,
  'autoScale': true,
  'centerOnScroll': true ,
  'beforeLoad': function(){
  $("body").css({"overflow-y":"hidden"});
  },
  'afterClose': function(){
  $("body").css({"overflow-y":"visible"});
  },
  'onComplete' : function(){onLoadFiltersCallBack();}
  });

Please help me to slove this issue? i am waiting for someone input.

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
