### ISSUE TITLE
High resolution loading spinners have overlapping image maps.

### ISSUE THREAD

**Issue by TeffenEllis** [fancyapps/fancyBox#982]
Overlaps occur when using a high resolution display.
![screen shot 2015-01-12 at 3 18 58 am](https://cloud.githubusercontent.com/assets/592134/5702267/7f4d5b78-9a0c-11e4-9e35-f7c202887385.png)

**Comment by fancyapps** [comment]
What display are you using?

**Comment by TeffenEllis** [comment]
A late 2013 retina Macbook Pro.

I had some luck fixing the issue by altering the vendor styles:
```css
#fancybox-loading, .fancybox-prev span, .fancybox-next span {  
....
}
```

```css
.fancybox-prev span, .fancybox-next span {
....
}
```

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3 - it is not using images for interface design.
