### ISSUE TITLE
3 Beta 1: Slideshow by click dont start

### ISSUE THREAD

**Issue by derSteffen** [fancyapps/fancyBox#983]
Hello,

I use the Beta-Version with the extension BUTTONS for 2.0 und THUMPS for 3.0 ... everything is fine!
But I can't start the slideshow! If I press the spacebar, the Slideshow wil be start, also the autoplay is going, but not the manual start (th click)

There is no JS-Error! It should be, that the function not will run!

I use the the last file buttons-js from version: 1.0.5 (Mon, 15 Oct 2012)!

Experiment: If I change 
play   : this.list.find('.btnPlay').click( F.play ),
in 
play   : this.list.find('.btnPlay').click( F.toggle),
the Play-Button resize the image! 

But               play   : this.list.find('.btnPlay').click( F.play )       not work if I click the Play-Button in the Buttons-Helper! Also the icon dont switch!

There is no               play: function ( action )                is the fancy-js-code (v3) !!!!

Tested: Firefox, Chrome, IE11

No other JS-FIles in the webside!

Included: Jquery v2.1.0 + jQuery Migrate v1.2.1

Is there an solution?

Thank you very much!

Greetings Steffen

**Comment by derSteffen** [comment]
Any idea?

Becaus the spacebar is going! Is there an opinion, that we can start the spacebar-function by click btnPlay?

Thank you very much!

**Comment by derSteffen** [comment]
Nothing idea?

Which name has the function to toogle (start / stop) the slideshow by the Beta-Version?

**Comment by fancyapps** [comment]
Hi, I'm sorry, I'm currently devoting all my time for final v3. It will look and work completely different from all previous versions (including the beta).

**Comment by derSteffen** [comment]
Thank you vermuch for your feedback!
The Beta works well (for me) but only the manual slideshow CLICK - START/STOP dont work!
Greetings

**Comment by fancyapps** [comment]
Well, if you want to start/stop the slideshow manually, you can like this:

```javascript
$.fancybox.slideshow.start();
$.fancybox.slideshow.stop();
```

**Comment by matthendrix** [comment]
//fancybox slideshow (play/pause button not working in Beta3)
$('body').on('click', 'a.btnPlay', function(){
	if($(this).hasClass('btnPlayOn')) {
		$.fancybox.slideshow.stop();
	}
	else {
		$.fancybox.slideshow.start();
	}
});

**Comment by SalahAdDin** [comment]
:+1:

**Comment by derSteffen** [comment]
Thanks matthendrix ... where did you place this code? In which file and in which part?

Thanks

**Comment by matthendrix** [comment]
Put in the web page html, just before the closing body tag.

**Comment by derSteffen** [comment]
Great, great, great! Thanks!!!

Do you have also a soltion for the expand-Icon? Because, in the buttons you can expand an Image but the css-class for the Expand-Toogle-Icon is disable (the functions can start), but thats wrong ... it is right if the image can't resize ... but there is no different .

Thanks

**Comment by derSteffen** [comment]
Hello matthendrix,

in your solution, there is the error, that if you have an autostart-(slideshow) and then you click the pause-button of the slideshow then the slideshow stop - perfect. But if you click an arrow from the image or the buttons, the slideshow starts automatic. 
This error ist not, if your slideshow dont start automatic.

Do you have an solutin for this?!

Thank you very much!

Greetings

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
