### ISSUE TITLE
Fancybox don't work well in Chrome but work well in FireFox

### ISSUE THREAD

**Issue by Tungxu** [fancyapps/fancyBox#984]
Hi,
I use Prestashop. I met a problem with Fancybox. 
When I click Add to cart, the Fancybox don't display, after I scroll , it displays. 
After I click Close button (X), the popup don't disappear. 
You can see my site: 
http://demo.posthemes.com/pos_sahara_digital3/en/
Do you have idea ?
 Sorry about my english !
Thank you so much !

**Comment by fancyapps** [comment]
It is not even a fancyBox.

2015-01-15 12:19 GMT+02:00 Tungxu <notifications@github.com>:

> Hi,
> I use Prestashop. I met a problem with Fancybox.
> When I click Add to cart, the Fancybox don't display, after I scroll , it
> displays.
> After I click Close button (X), the popup don't disappear.
> You can see my site:
> http://demo.posthemes.com/pos_sahara_digital3/en/
> Do you have idea ?
> Sorry about my english !
> Thank you so much !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fancyapps/fancyBox/issues/984>.
>



-- 
Janis Skarnelis
fancyapps.com
