### ISSUE TITLE
It is wrong way to use $('*')

### ISSUE THREAD

**Issue by powerbot15** [fancyapps/fancyBox#985]
``` javascript
$('*').filter(function(){
    return ($(this).css('position') === 'fixed' && !$(this).hasClass("fancybox-overlay") && !$(this).hasClass("fancybox-wrap") );
}).addClass('fancybox-margin');
```

Hey guys! The construction above _slows_ your plugin too much. Selector `'*'` on big app-pages with many(thousands) DOM-elements slows down dialog opening. If we could do nothing with this logic, maybe we should have some kind of option(callback or custom selector) to optimize this part of code?

``` javascript
$(options.customFilterSelector || '*').filter(...)
```

**Comment by idanhen** [comment]
We had to comment out this section.

it almost killed us :)

**Comment by fancyapps** [comment]
Sorry, update to v3.
