### ISSUE TITLE
Clicking on image scrollsthe page to the top

### ISSUE THREAD

**Issue by Ignitis** [fancyapps/fancyBox#986]
Suppose there are 100 images stacked vertically.
Now, clicking on the 100th image opens the lightbox but also scrolls the page to the top. 

I want the page to remain at the same position when clicked on any image. I checked your homepage and it's working there. But, it's not working with me. 

Can you please suggest what changes do I need to do?

**Comment by eveto** [comment]
same here

**Comment by WulleBulle** [comment]
Hi,


I am using FB 2.1.5 (newest) and having this issue too.
Looks like there is an e.preventDefault() missing somewhere.

**Comment by Ignitis** [comment]
Amazing... So it's finally solved. I am so thankful :)
