### ISSUE TITLE
Scale Issue on Device / Orientation Rotate

### ISSUE THREAD

**Issue by nadeem0mohammed** [fancyapps/fancyBox#987]
Hello!!

Great plugin!! :)

One Issue : When using fancyBox, whether its an image or an iFrame (YouTube), and open this on a mobile device and then rotate (landscape to portrait or vice versa), fancyBox doesn't scale or fit to width of device window?

fancyBox Options:

<pre>
    $(document).ready(function() {
        $(".fancybox").fancybox({
            helpers : {
                media: true,
                title: null                
                },
            width       : 800,
            height      : 450,
            aspectRatio : true,
            scrolling   : 'no',
            openEffect  : 'fade',
            closeEffect : 'fade'
        });
    });
</pre>

Device: SAM GALXY S3
OS: ANDROID 4.2
Browser: FF / CHRME / DOLPHIN

fancyBox version: 2.1.5 PACK 

p.s. this is happening also on your examples! :/

Please also see similar issue: http://stackoverflow.com/questions/23612290/fancybox-not-repositioning-correct-after-orientation-change-on-ipad

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
