### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientWidth' of undefined

### ISSUE THREAD

**Issue by tkn98** [fancyapps/fancyBox#988]
Given that 

    var fancybox = jQuery.fancybox;

by using

            fancybox.helpers.overlay.open();

on `jQuery(document).read()` with version 2.1.5 triggers a 

> Uncaught TypeError: Cannot read property 'clientWidth' of undefined

This error happens with jQuery 1.6.2.

With a vanilla setup it works: http://jsfiddle.net/chssppkn/1 (jQuery 1.6.2)

The error comes from this line: https://github.com/fancyapps/fancyBox/blob/master/source/jquery.fancybox.js#L650

                        rez.w = locked[0].clientWidth;

because `locked[0]` is undefined. The precondition check

                    if (locked && locked.length) {

is not catching up the circumstance the site is able to inject as dependency for `locked`.

**Comment by fancyapps** [comment]
If I remember correctly, minimum jQuery version is 1.7.1.

**Comment by tkn98** [comment]
It's not about the jQuery version, tested it for this case.

**Comment by tkn98** [comment]
If I download the ZIP package and use the files therein I have the error.

If I take the same versioned (but not same file) from http://fancyapps.com/fancybox/source/jquery.fancybox.js I don't have the error.

Using the sources from the website fixes this.
