### ISSUE TITLE
2.1.6 Release

### ISSUE THREAD

**Issue by tkn98** [fancyapps/fancyBox#989]
While looking into a problem (see #988) it came to my attention that I could have benefited from a newer release, next in line could be 2.1.6.

I hereby kindly ask for making a new release containing the current fixes.

**Comment by fancyapps** [comment]
Good news is that v3 is completed, working right now on home page design and documentation.

**Comment by tkn98** [comment]
I don't want to stop you from a v3 release, it's just I already could have benefited from a bugfix release in the 2.1.x lineup.

Would you consider to make a 2.1.x bugfix release (independent for you v3 plans)?

**Comment by fancyapps** [comment]
Just download the latest code for the now - https://github.com/fancyapps/fancyBox/archive/master.zip - and think about it as the latest version.

**Comment by SalahAdDin** [comment]
Oh, so good, thank you!

**Comment by tkn98** [comment]
I'll close it then for now. Would be nice you could release from 3.0.0 ongoing with semver - http://semver.org/ - so it's easy to stay updated. Thanks again!

**Comment by LeonhardtDavid** [comment]
Could you create the 2.1.6 release? I really appreciate that.

**Comment by SalahAdDin** [comment]
Whe the new release version?

**Comment by tkn98** [comment]
@SalahAdDin: To have a version number for the yet "unreleased" patches (the patches are released, but without a specific version identifier)

**Comment by LeonhardtDavid** [comment]
So? When is planed to be released with an specific version?

**Comment by tkn98** [comment]
@LeonhardtDavid: I personally did read @fancyapps's comment https://github.com/fancyapps/fancyBox/issues/989#issuecomment-71029822 in the way that no release at all is planed in the 2.x line-up. Which I think could be progressed by doing such a maintenance release. If you could as well raise your concerns to him, we perhaps can generate some traction.

**Comment by SalahAdDin** [comment]
Please

**Comment by evetere** [comment]
Having v3 never can be an excuse for stopping fixing 2.x, or it will be deprecated immediately? Never seen that. Please release a much needed 2.1.6. Thanks. @fancyapps @LeonhardtDavid @tkn98

**Comment by SalahAdDin** [comment]
Only update it please :+1:
