### ISSUE TITLE
Inline content show/hide using class

### ISSUE THREAD

**Issue by julianxhokaxhiu** [fancyapps/fancybox#990]
Hi,

I've found that you're using jQuery method `.show()` and `.hide()` [to show/hide the div](https://github.com/fancyapps/fancyBox/blob/master/source/jquery.fancybox.js#L1114) with the specified ID.

Is it possible to use/toggle a class? Something like:

``` js
{
 // ...
 inlineContentToggleClass: 'hidden'
 // ...
}
```

useful for example when you integrate fancyBox inside a Bootstrap 3 project.

Thanks in advice,
Julian

**Comment by fancyapps** [comment]
Sure, it would be nice to avoid inline styling. I am just not sure about "inlineContentToggleClass" naming :)

**Comment by julianxhokaxhiu** [comment]
As I'm not using it anymore I'll close the issue :) Thanks anyway.
