### ISSUE TITLE
Unexpected change fancybox-overlay>fancybox-wrap to fancybox-wrap+fancybox-overlay

### ISSUE THREAD

**Issue by ihorzenich** [fancyapps/fancyBox#993]
Recall #fancybox when it's already open, change DOM from 

``` html
fancybox-overlay > fancybox-wrap
```

to

``` html
fancybox-wrap + fancybox-overlay
```

Steps to reproduce:
1. Execute `$.fancybox('Test');`
![developer tools - http___fancyapps com_fancybox_ 2015-01-30 15 23](https://cloud.githubusercontent.com/assets/1684521/5976229/1dc0f586-a894-11e4-9c8b-0c144a55dc8f.png)
2. Execute `$.fancybox('Test2');`
![developer tools - http___fancyapps com_fancybox_ 2015-01-30 15 26 18](https://cloud.githubusercontent.com/assets/1684521/5976252/5f087ac8-a894-11e4-84c4-c92deccc06bb.png)

**Comment by danielplath** [comment]
I also have the Problem. The overlay is in some cases a extra container, separated to the fancybox-wrap.  I actually need fancybox-wrap in facybox-overlay. How can I fix it?
thanks a lot for your great work!

**Comment by tmrfcb** [comment]
adding  : # showEarly : false # to the helpers will resolve the problem 
helpers: {
   overlay: { 
      showEarly : false
   }
},

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
