### ISSUE TITLE
mousewheel apple magic mouse

### ISSUE THREAD

**Issue by beyoyo2** [fancyapps/fancyBox#995]
Having some unexpected scrolling issues using the apple magic mouse. Is there any way to lock down the scrolling so it doesn't jump/skip images ... basically only allowing scrolling on 1-axis when using the magic mouse?

**Comment by marcobiedermann** [comment]
@beyoyo2 I think I know your problem. You have to lock the overlay. I tried it on the [demo page](http://fancybox.net/). The x-axis works fine but when I try scrolling on the y-axis, the whole content is scrolling.

```
$('.fancybox').fancybox({
  helpers: {
    overlay: {
      locked: true
    }
  }
});
```

See: http://fancyapps.com/fancybox/#docs

**Comment by beyoyo2** [comment]
@marcobiedermann, I tried this out and it doesn't appear to do anything differently. If I "scroll-down" with the magic mouse it slides the image in from the bottom.. and it is not the next one in sequence.
```
<script type="text/javascript">
$('.fancybox')
    .attr('rel', 'gallery1')
    .fancybox({
        beforeLoad: function() {
            var el, id = $(this.element).data('title-id');

            if (id) {
                el = $('#' + id);
            
                if (el.length) {
                    this.title = el.html();
                }
            }
        },
		helpers : {
			title: {
				type: 'inside'
			},
			overlay: {
				locked:true
			}
		},
		loop : true
    });
</script>
```

**Comment by stevedaddy** [comment]
@beyoyo2 you can set
defaults: {
mouseWheel : false,

**Comment by fancyapps** [comment]
The problem with swiping on touchapads/mouses is that they typically trigger scroll events multiple times for a long period of time and it is not possible to stop them, even unbinding does not help, because after binding they keep triggering again.
