### ISSUE TITLE
How do I make fancybox use its larger icons

### ISSUE THREAD

**Issue by fatetrader** [fancyapps/fancyBox#996]
How to make fancybox 2 use its larger versions of icons?

fancybox_loading@2x.gif
fancybox_sprite@2x.png

**Comment by marcobiedermann** [comment]
Fancybox is using them if the device ratio is 1.5 or higher

```
@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
	   only screen and (min--moz-device-pixel-ratio: 1.5),
	   only screen and (min-device-pixel-ratio: 1.5) {}
```

**Comment by fatetrader** [comment]
Ok, I get it it will just use larger sprites but relative size is the same on the page, I tested it by lowering pixel-ratio and it displayed other @2x sprites but dimensions on screen were the same as smaller versions, quite useful to know, thanks.

**Comment by marcobiedermann** [comment]
You are welcome. If you like to emulate it, there is an option in Google Chrome.
Open up web Inspector -> click the mobile Phone icon on the upper left and select Apple iPhone for example. This device has a device ratio of 2. If you are using `min-device-picel-ratio` make sure that you are using background-size and the source image has to be twice as big as the container.

These resources might help you out:
http://css-tricks.com/snippets/css/retina-display-media-query/
http://code.tutsplus.com/tutorials/the-right-way-to-retinafy-your-websites--net-31793

If you got any more questions about this topic, you can hit me up at Twitter [@m412c0b](https://twitter.com/m412c0b). For now, I think you can close this issue :)

**Comment by fatetrader** [comment]
Thanks this is really cool, I didn't know about this emulator in chrome, it is very handy.
