### ISSUE TITLE
Starting a vimeo video at a specific start time with fancybox

### ISSUE THREAD

**Issue by Devpaq** [fancyapps/fancybox#998]
I am trying to use fancybox with vimeo and have the vimeo video start at a certain point.

I am normally able to start a vimeo video at a specific start point by adding #t=1m15s to the video url. For example:  https://vimeo.com/channels/staffpicks/119293996#t=1m15s

But when I use fancybox media helper it seems to remove the #t=1m15s from the url and wont start from the desired time. 
Here is a jsfidlle: http://jsfiddle.net/8z3ueL23/

It looks like the the regular expression is not handling the hash at 
https://github.com/fancyapps/fancyBox/blob/master/source/helpers/jquery.fancybox-media.js#L106

**Comment by fancyapps** [comment]
Hi, please, upgrade to v3.
