### ISSUE TITLE
Website distorts/jumps when clicking on Next/Prev buttons on iOS 8.1.3

### ISSUE THREAD

**Issue by hanazair** [fancyapps/fancyBox#999]
I'm using FancyBox 2.1.5 and when viewing a gallery on my iPhone6 running iOS 8.1.3 I get brief jerky website distortion each time the I click Nex/Prev and next photo loads. 

Sorry if the description isn't more informative, didn't know how else to describe it. 

Here is the URL of a site where I'm using it: http://domstroy.kz/project-1/

**Comment by BackuPs** [comment]
Hi 

set the prev next  effect to fade and easing to linear

			nextEffect : 'fade', // 'elastic', 'fade' or 'none'
			nextSpeed  : 250,
			nextEasing : 'linear',
			nextMethod : 'changeIn',

			// Changing previous gallery item
			prevEffect : 'fade', // 'elastic', 'fade' or 'none'
			prevSpeed  : 250,
			prevEasing : 'linear',
			prevMethod : 'changeOut',

Best regards,
BackuPs

**Comment by fancyapps** [comment]
I suggest you to upgrade to v3.

**Comment by BackuPs** [comment]
Where is V3?  I see only 2.1.6 on the internet

**Comment by fancyapps** [comment]
There is a message on top of the page, but if you missed it, then there it is - http://fancyapps.com/fancybox/3/

**Comment by BackuPs** [comment]
So in order to get the mentioned issue fixed we now suddenly have to buy a license and have to rewrite all our scripts as FB 2.1.5 / FB 2.1.6 are using different code and are not compatible at all with the new version.

**Comment by fancyapps** [comment]
v3 is a free upgrade and updating to v3 should not be much problem.

**Comment by BackuPs** [comment]
Hmmm i am missing something. Was version 2.15 not a free unpaid version? When did this js become a licensed plugin?  Wasn't that from version 2.16?

**Comment by fancyapps** [comment]
v2 has always been dual licensed - CC-NonCommercial for personal use/non-commercial and commercial licenses for commercial projects.

**Comment by BackuPs** [comment]
Ah ok. i was not aware of that.  So If i want to use it in my own personal website then i dont need a license.   If however i want to use v 2.15 in a commercial project i need to buy a license? But for V 3 i always need a license? Correct?

**Comment by BackuPs** [comment]
So if i own a license for 2.1.5 it is automatically a license for v 3.0?

**Comment by fancyapps** [comment]
You are correct about v2. Since it caused a lot of questions like "is this commercial/do I need license?", it was decided to simplify licensing - open source projects can use it under GPLv3 license (that means, if you want to use v3 for free, you have to make source code of your project freely accessible) and you need to have commercial license if your do not want to license it under GPLv3 terms.

And yes, you are correct about automatic upgrading.

**Comment by BackuPs** [comment]
Thank you for clearing that up.  Please close the thread as all is clear now.
